### ISSUE TITLE
DLNA error when connecting from TV

### ISSUE THREAD

**Issue by ekw** [jellyfin/jellyfin#2066] opened 2019-11-27 08:55 UTC
When I try to browse videos from my Samsung TV on Jellyfin via DLNA, the TV gives a generic "Request cannot be completed" error.  These are the errors I see in the Jellyfin logs (I've enabled DLNA debug logging):

```
[2019-11-27 08:39:29.119 +00:00] [ERR] Error processing request
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Emby.Dlna.Api.DlnaServerService.GetPathValue(Int32 index)
   at Emby.Dlna.Api.DlnaServerService.PostAsync(Stream requestStream, IUpnpService service)
   at Emby.Dlna.Api.DlnaServerService.Post(ProcessContentDirectoryControlRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-11-27 08:39:29.220 +00:00] [ERR] Error processing request
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Emby.Dlna.Api.DlnaServerService.GetPathValue(Int32 index)
   at Emby.Dlna.Api.DlnaServerService.PostAsync(Stream requestStream, IUpnpService service)
   at Emby.Dlna.Api.DlnaServerService.Post(ProcessContentDirectoryControlRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-11-27 08:39:29.322 +00:00] [ERR] Error processing request
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Emby.Dlna.Api.DlnaServerService.GetPathValue(Int32 index)
   at Emby.Dlna.Api.DlnaServerService.PostAsync(Stream requestStream, IUpnpService service)
   at Emby.Dlna.Api.DlnaServerService.Post(ProcessContentDirectoryControlRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-11-27 08:39:29.423 +00:00] [ERR] Error processing request
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Emby.Dlna.Api.DlnaServerService.GetPathValue(Int32 index)
   at Emby.Dlna.Api.DlnaServerService.PostAsync(Stream requestStream, IUpnpService service)
   at Emby.Dlna.Api.DlnaServerService.Post(ProcessContentDirectoryControlRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Jellyfin Version: 10.4.2
 - Reverse proxy: no

Anything I can do to fix/further debug this?

**Comment by JustAMan** [comment] 2019-11-27 13:26
Should be fixed by https://github.com/jellyfin/jellyfin/pull/2054 (will be released in next release after 10.4.2)

**Comment by ekw** [comment] 2019-11-28 07:46
Thanks.  In the meantime, if I want to try to compile jellyfin myself to get #2054, would I just link /usr/bin/jellyfin to the one I compile?  Right now, it is linked to /usr/lib/jellyfin/bin/jellyfin.

**Comment by JustAMan** [comment] 2019-11-28 09:08
You can run build scripts within the repo to get yourself a `.deb` package and then install it normally if you want to.

**Comment by anthonylavado** [comment] 2019-12-07 08:51
@ekw 10.4.3 is now available. Try it out and let us know if it works :-)

**Comment by PrplHaz4** [comment] 2019-12-09 17:21
Looks like a duplicate of #2053 

Updating to 10.4.3 fixed this issue for me.

**Closed** 2019-12-09 19:18 UTC
Labels: bug
