### ISSUE TITLE
Shutdown, no restart option present

### ISSUE THREAD

**Issue by lyr1cx** [jellyfin/jellyfin#6702] opened 2021-10-15 19:29 UTC
**Bug:** Jellyfin Server page no longer offers the option to restart, only shutdown.

**Pertinent System Info:**
 - OS: Windows 10 (All updates / latest build always)
 - Virtualization: N/A
 - Clients: N/A
 - Browser: Firefox (latest - non-beta)
 - Jellyfin Version: latest stable
 
**Screenshot:**
![ssj](https://user-images.githubusercontent.com/6131085/137543323-1a4ce6ec-c7a6-4c0f-a369-8a47b8ead1ce.PNG)

**Comment by crobibero** [comment] 2021-10-15 19:36
This is not a bug, and is a duplicate of https://github.com/jellyfin/jellyfin/issues/893

**Closed by crobibero** 2021-10-15 19:36 UTC
Labels: bug
