### ISSUE TITLE
[Issue]: Wrongfully identified albums

### ISSUE THREAD

**Issue by PaulDotSH** [jellyfin/jellyfin#10740] opened 2023-12-17 16:59 UTC
### Please describe your bug

In the official documentation we can have an artist folder, in the artist folder we can have folders for albums and tracks for individual releases (singles). However singles are treated like a album with one of the singles being randomly chosen as the album title

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Ubuntu server 22.04
- Linux Kernel: 5.15
- Virtualization: kvm
- Clients: Browser, Android, Linux
- Browser: Chrome 120
- FFmpeg Version: bundle with jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: None
- GPU Model: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaulDotSH** [comment] 2023-12-18 01:10
If needed I could provide example songs/artists that have this behavior, I can also strip the metadata and provide just that

**Comment by felix920506** [comment] 2023-12-20 01:28
Closing as duplicate of #6694

**Closed** 2023-12-20 01:28 UTC
Labels: bug
