### ISSUE TITLE
Subtitles Not Loading on 10.5.3

### ISSUE THREAD

**Issue by Furhreious** [jellyfin/jellyfin#2823] opened 2020-04-10 17:51 UTC
**Describe the bug**
Stumbled on an issues which results in near all my subtitles not working or appearing on the videos anymore even tho they show up on the subtitle selection. They worked in the version 10.5.0 but been on 10.5.3v for a bit and only a small amount of shows now result in subs being shown. Plus some subs are from the same providers but result in some working and other not.

**System (please complete the following information):**
 - OS: Windows 10 
 - Virtualization: N/A
 - Clients: Browser, Andriod
 - Browser: Microsoft Edge Chromium Version 80
 - Jellyfin Version: 10.5.3 Stable
 - Playback: Direct Play, Direct Stream, Transcode 
 - Installed Plugins: AudioDB 10.5.0.0, MusicBrainz 10.5.0 and Open Subtitles 7.0.0.0
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

N/A

**Expected behaviour**
When I play a video the subtitles should automatically appear if not then I would select the subtitles from the icon.

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by Artiume** [comment] 2020-04-10 17:55
For troubleshooting, hit F12 to bring up the browser debugger and go to Console, when you start playing a video with subs, are there any console errors popping up?

Let's verify proper operation with of the server. Go to your User Profile > Subtitles > Burn Subtitles and change it to ALL. This will remove the client aspect and verify the backend is properly operating.

**Comment by Furhreious** [comment] 2020-04-10 18:13
This is what appears.
![Capture](https://user-images.githubusercontent.com/63469576/79012478-4bf96800-7b5e-11ea-80c5-e6624e4a1d66.PNG)

But just did the Burn subtitles which seemed to of worked, also is there a way to get the server to go thought all subs and burn them, so that they can be played Direct Stream is that not possible?

**Comment by Artiume** [comment] 2020-04-10 18:19
Not yet. You could use something like [tdarr](https://github.com/HaveAGitGat/Tdarr) but i find burning in subs to be a nasty solution.

@JustAMan I'm seeing lots of red here D:

**Comment by JustAMan** [comment] 2020-04-10 21:28
Some are expected, and some others are not.
From the first glance it looks like incompatible version of us calling into Octopus and what version of Octopus is bundled.

I would have to look closer.

**Comment by JustAMan** [comment] 2020-04-10 21:34
Okay, I've checked portable x64 package and it's fine.
Can you give me the link you used to install JF?

**Comment by Furhreious** [comment] 2020-04-11 00:41
I used this Link
https://repo.jellyfin.org/releases/server/windows/stable/jellyfin_v10.5.3-x64.exe

**Comment by JustAMan** [comment] 2020-04-13 11:35
I've checked that, too, and it should be fine.
Please clear the cache and retry, it's definitely your browser getting _old_ `subtitles-octopus-worker.js` from somewhere, and that somewhere is probably browser cache.

**Comment by JustAMan** [comment] 2020-04-13 14:54
Definitely clear the cache, this seems to have the same root cause and probably the same "fix" (clearing cache): https://github.com/jellyfin/jellyfin/issues/2856

**Comment by Furhreious** [comment] 2020-04-13 18:48
yep no more errors, just did as you stated above about clearing the cache and it all work with no errors.

**Comment by JustAMan** [comment] 2020-04-15 21:42
So I'm going to close this issue as it's fixed locally.
Meanwhile I hope that this https://github.com/jellyfin/jellyfin/pull/2864 would eliminate the need for later cache cleanups.

**Closed by JustAMan** 2020-04-15 21:42 UTC
Labels: bug
