### ISSUE TITLE
[Issue]: Jellyfin cannot access localhost in docker HOST network mode 

### ISSUE THREAD

**Issue by kdjordjev** [jellyfin/jellyfin#7826] opened 2022-05-31 01:04 UTC
### Please describe your bug

Hello,
When i run Jellifin in "Host" network mode i can not stream live TV. It seems the ffmpeg can not access the localhost in HOST mode. I tested this by logging into the container as well - in host mode, http://127.0.0.1 is not accessible , while i can access the streams  by server IP address.

I have no issue when i run the container in BRIDGE mode and exporting the ports.  However i want to run Jellyfin in Host mode since i want to use the DLNA server as well, so bridge mode is not a solution (DLNA does not work in bridge mode in docker)

Any solution to this?
It seems the localhost is hard-coded within the application for all ffmpeg calls. It will be helpful if instead using the localhost, all ffmpeg calls are done towards the real IP of the server (i.e. "Bind to local network address:" )

Any suggestions?
K

Jellyfin under Docker in an LXC container under Proxmox.

**In Host mode:**
```
    services:
      jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        network_mode: "host"
```

**In Bridge mode:**
```
    services:
      jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
     #   network_mode: "host"
        ports:
          - "80:80"
          - "443:443"
          - "1900:1900/udp"
          - "7359:7359/udp"
```

ffmpeg fails 

`[17:45:27] [INF] [28] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -autorotate 0 -i "http://127.0.0.1:80/LiveTv/LiveStreamFiles/e9cad02a70734b468ac38f02df176256/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_nvenc -preset default -b:v 5000000 -maxrate 5000000 -bufsize 10000000 -profile:v:0 high -g:v:0 90 -keyint_min:v:0 90 -sc_threshold:v:0 0 -vf "yadif_cuda=0:-1:0,scale_cuda=format=nv12" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/9da74824c676ed629ea7266fae778ec2/" -hls_playlist_type event -hls_segment_filename "/config/transcodes/9da74824c676ed629ea7266fae778ec2%d.ts" -y "/config/transcodes/9da74824c676ed629ea7266fae778ec2.m3u8
[17:45:27] [ERR] [32] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1"
`

**I login in the container and manually  type the command above**

`root@Nas:/# /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -autorotate 0 -i "http://127.0.0.1:80/LiveTv/LiveStreamFiles/e9cad02a70734b468ac38f02df176256/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_nvenc -preset default -b:v 5000000 -maxrate 5000000 -bufsize 10000000 -profile:v:0 high -g:v:0 90 -keyint_min:v:0 90 -sc_threshold:v:0 0 -vf "yadif_cuda=0:-1:0,scale_cuda=format=nv12" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/9da74824c676ed629ea7266fae778ec2/" -hls_playlist_type event -hls_segment_filename "/config/transcodes/9da74824c676ed629ea7266fae778ec2%d.ts" -y "/config/transcodes/9da74824c676ed629ea7266fae778ec2.m3u8"
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x55b171401040] Connection to tcp://127.0.0.1:80 failed: Connection refused
http://127.0.0.1:80/LiveTv/LiveStreamFiles/e9cad02a70734b468ac38f02df176256/stream.ts: Connection refused`

**in the container if i change the localhost to the correct IP everything works. Note that the ONLY thing i changed was the replacing the localhost (127.0.0.1) with the real IP (192.168.100.2)** 

`root@Nas:/# /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 3 -autorotate 0 -i "http://192.168.100.2:80/LiveTv/LiveStreamFiles/e9cad02a70734b468ac38f02df176256/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_nvenc -preset default -b:v 5000000 -maxrate 5000000 -bufsize 10000000 -profile:v:0 high -g:v:0 90 -keyint_min:v:0 90 -sc_threshold:v:0 0 -vf "yadif_cuda=0:-1:0,scale_cuda=format=nv12" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/9da74824c676ed629ea7266fae778ec2/" -hls_playlist_type event -hls_segment_filename "/config/transcodes/9da74824c676ed629ea7266fae778ec2%d.ts" -y "/config/transcodes/9da74824c676ed629ea7266fae778ec2.m3u8"
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100`

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:                Docker
- Virtualization:    LXC container under Proxmox
- Clients:           Chrome
- Browser:
- FFmpeg Version:     
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: HOST (not working) vs BRIDGE (working) 
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kdjordjev** [comment] 2022-06-05 20:26
I found the issue, although i do not completely understand why it is happening.

I had setup "Bind to local network address:" (in Dashboard/Networking) pointing to my local IP 192.168.100.2:
- when i run Jellyfin in "bridge mode" , the ffmpeg can access both  127.0.0.1 and 192.168.100.2
- when i run Jellyfin in "host mode" , the ffmpeg can access only 192.168.100.2 but the streaming fails , since ffmpeg is hardcoded to stream from 127.0.0.1

When I clear the "Bind to local network address:" (in Dashboard/Networking) filed, **i.e. leave it empty, then in "host mode" ffmpeg have an access to 127.0.0.1 and everything works.**

**In any case i still consider this to be a bug. If someone uses "Bind to local network address:", then the ffmpeg should be streaming from that IP, rather than being hardcoded to localhost .**

**Comment by robertbeal** [comment] 2022-06-08 00:30
If I'm understanding this correctly, it may be as-designed in docker.

Or at least, if running `net=host` then `localhost` inside the container will resolve to the physical host (and not the container) as the container is sharing the hosts network stack.

**Comment by kdjordjev** [comment] 2022-06-08 00:50
Thank you... I agree.
But the ffmpeg is hardcoded to always stream form localhost (127.0.0.1).
So in the case that someone "binds" the container to the server IP address, then the ffmpeg can not resolve the localhost in net=host mode. 

It would make sense to have ffmpeg stream from the "bind to address" if populated, or localhost if empty

**Comment by robertbeal** [comment] 2022-06-08 08:57
Ah ok that does make sense. 

Hmmm... I'm not a code contributor, but am wondering how it could be elegantly done without docker specific concepts bleeding into the codebase. The code would need some awareness of the network stack to make a decision which address to pass to ffmpeg.

One could argue that use `net=host` is frowned upon in docker best practice (especially when explicit ports can be used). So the effort spent, is effort supporting poor use of docker. Still a confusing experience/output for those that do though.

**Comment by cvium** [comment] 2022-06-08 21:45
Duplicate of https://github.com/jellyfin/jellyfin/issues/5897

**Closed by cvium** 2022-06-08 21:45 UTC
Labels: bug

**Comment by kdjordjev** [comment] 2022-06-08 22:58
@cvium 
Thanks for pointing this out.. 

Is it really fixed? ... I downloaded **10.8.0.beta3** and still have the same problem - ffmpeg failure

ffmpeg always uses the 127.0.0.1, which is not resolved when `net=host`, while the server binds to 192.168.100.2 (specified in Network/ Bind to local network address)

when `net=bridge`, it works 

I believe we should run ffmpeg against the bind-to-local-network-address , or local host, when not available

**Comment by cvium** [comment] 2022-06-09 20:03
If it is using 127.0.0.1 I think you've misconfigured something in network settings

**Comment by kdjordjev** [comment] 2022-10-11 08:27
In a way , even without considering Docker specidfic problems, I think it makes sense to stream from the IP you bind  your server to and use localhost as default (when bind to ip not specified).  It makes sense.However I agree that it is ugly to specific case  implementaton , but I think above seems like generic way to do it.Sent from my Galaxy
-------- Original message --------From: Robert Beal ***@***.***> Date: 6/8/22  1:57 AM  (GMT-08:00) To: jellyfin/jellyfin ***@***.***> Cc: kdjordjev ***@***.***>, Author ***@***.***> Subject: Re: [jellyfin/jellyfin] [Issue]: Jellyfin cannot access localhost in
  docker HOST network mode  (Issue #7826) 
Ah ok that does make sense.
Hmmm... I'm not a code contributor, but am wondering how it could be elegantly done without docker specific concepts bleeding into the codebase. The code would need some awareness of the network stack to make a decision which address to pass to ffmpeg.
One could argue that use net=host is frowned upon in docker best practice (especially when explicit ports can be used). So the effort spent, is effort supporting poor use of docker. Still a confusing experience/output for those that do though.
