### ISSUE TITLE
DLNA only binds to one IP of bridged network interface

### ISSUE THREAD

**Issue by heylix** [jellyfin/jellyfin#5404] opened 2021-03-07 20:29 UTC
**Describe the bug**
If I configure a `br0` network interface with the IPs 192.168.1.110 and 192.168.1.10, and enable the DLNA server, I get the following message in the logs:

`[20:51:23] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.1.110/24`

It doesn't register a publisher for the second IP.

**System (please complete the following information):**
 - OS: Fedora 33
 - Virtualization: none
 - Jellyfin Version: 20210307.2-unstable
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: bridge

**Expected behavior**
It should either bind to all IP addresses or you should be able to configure the addresses it binds to.

**Comment by BaronGreenback** [comment] 2021-03-08 23:21
The issue is because both addresses appear in the same subnet.

**Comment by BaronGreenback** [comment] 2021-03-09 00:11
If possible, could you test PR https://github.com/jellyfin/jellyfin/pull/5416 please?

**Comment by heylix** [comment] 2021-03-14 12:41
Sadly it now adds the DLNA listener to both interfaces, but publishes the same IP to both:

```
[INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.178.110/24
[DBG] [1] Emby.Dlna.Main.DlnaEntryPoint: Device Added MediaServer - 123fac2910c24aed93249b9971fbd7b3 - http://192.168.178.110:8096/dlna/123fac2910c24aed93249b9971fbd7b3/description.xml
[INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.178.10/24
[DBG] [1] Emby.Dlna.Main.DlnaEntryPoint: Device Added MediaServer - 123fac2910c24aed93249b9971fbd7b3 - http://192.168.178.110:8096/dlna/123fac2910c24aed93249b9971fbd7b3/description.xml
```

**Comment by BaronGreenback** [comment] 2021-03-14 17:32
Could you try it again please?

I've found the issue - it was returning the 1st matching interface address each time.

**Comment by BaronGreenback** [comment] 2021-04-10 09:00
Closing as resolved. Please re-open if the issue persists.

**Closed by BaronGreenback** 2021-04-10 09:00 UTC
Labels: bug
