### ISSUE TITLE
possible memory leak? 

### ISSUE THREAD

**Issue by mick-pihole** [jellyfin/jellyfin#6306] opened 2021-07-16 02:58 UTC
**Describe the bug**
memory keep going up till  Synology crash, unreachable
had to reboot Synology.

update: I set memory limit at 2GB, the jellyfin is not crashing, however memory usage stays at 2GB.

**System (please complete the following information):**
 - OS: Synology
 - Virtualization: docker
 - Clients: both Browser and Fire Stick, have not tested others
 - Browser: Chrome
 - Jellyfin Version: 10.7.6
 - Playback:  Transcode or direct stream

 - Hardware Acceleration: VAAPI
 - Installed Plugins: opensubtitle
 - Reverse Proxy: none
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by josolanes** [comment] 2021-07-16 16:53
I see the same behavior in a docker container run within Gentoo and Jellyfin version 10.7.6

Overnight mine used a little over 6GB of memory (with no limit) when started at 3:30p and checked this morning at 8a. I've since limited its container to 4GB

Mine is a fresh install (as of yesterday) with the following libraries and sizes:
 - Movies: 228
 - Music: 6031
 - Books: 31
 - Shows: 1873

Memory usage continued to climb after scanning the libraries and no scheduled tasks were listed as recently running when I noticed it in the morning. Jellyfin was also not in active use (nothing listed in activity overnight)

Mine is behind a reverse proxy (using jwilder/nginx-proxy:latest) and I'm using NVENC hardware acceleration. No new plugins or anything in my case

**Comment by MafiaInc** [comment] 2021-08-29 19:48
I'm not sure whether is memory leak or not, but I've noticed Jellyfin is using about 3.2GB of memory right now so I have decided to search and ended up in this issue. Here are some details about my setup:

Server: 4acdaf640013
Version: 10.7.6
OS: Linux
Architecture: X86

It runs in docker container on VM. It was used maximum by three users at a time. Memory usage : 
```
# smem -P jellyfin -k
  PID User     Command                         Swap      USS      PSS      RSS
380643 root     python /usr/bin/smem -P jel        0    10.5M    10.7M    12.3M
2859268 root     /jellyfin/jellyfin              2.1M     3.2G     3.2G     3.2G
```
I will keep it on eye to see whether is increasing or not. The process is running since Aug26, so it is three days old.
I've searched the website for some info about the hardware requirements, I couldn't find. 

Let me know if you would require more info for the process, I could provide.

Thanks for all the efforts!

**Comment by cvium** [comment] 2021-08-30 08:39
It is only a memory leak if the memory usage continues to climb without ever stopping. There's a lot of stuff being cached in memory, so high usage isn't necessarily any indication.

**Comment by FilipLac** [comment] 2021-12-29 01:15
I have same issue on:

**Comment by FilipLac** [comment] 2021-12-29 01:22
I have same issue on: 
Version: 10.7.7
Operating System: Linux (based on debian)
Architecture: Arm64
Running on RPI 4b

It cached video that I tried to play in memory and left it there even after completing that video to the end. When I tried playing it on different device it cached it too, and now it looks like it has that video in memory twice. And unfortunately only way to get rid of it is restarting whole device or that dock in docker.

**Comment by cvium** [comment] 2021-12-29 08:25
That sounds extremely unlikely. Neither ffmpeg nor jellyfin reads entire video files into RAM.

**Comment by FilipLac** [comment] 2021-12-29 16:27
> That sounds extremely unlikely. Neither ffmpeg nor jellyfin reads entire video files into RAM.

Well all I know that I had there 200MB video and when I played it 2 times my RAM usage on service Jellyfin went up by same amount.

**Comment by lordkitsuna** [comment] 2022-03-14 05:44
Just throwing my issue into here. i can get this issue with absolutely no use of jellyfin whatsoever. i just have the server running and over a few days it will end up sigkilled when the server goes oom after it eats the servers 16GB slowly. normal system ram use is around 2.8GB so its not like it does not have tons of headroom. 

i can use something like netdata to log and see that its indeed jelly that randomly grows. but i cant imagine why, as i said this is with no playback at all its just sitting idle. so the only things running should be the maintenance routines for the libraries like scanning and such. ive tried searching jellyfin logs but see nothing remarkable in them.

**Comment by ngosang** [comment] 2022-04-24 11:41
I can reproduce this issue too (library with 2000 movies):
* Start Jellyfin (in my case with 1 GB memory limit in Docker)
* The app works well and the memory is ~400MB
* Go the library in the Web UI (or Android app) and scroll in the page with all movie posters.
* With each page the memory goes up and never down until it reaches 1GB and it's killed by OOM.

I think you are caching poster images in the server memory or something like that. If that is true I rather prefer slow poster loading than server crash. The wise thing to do is to cache the posters and other metadata in the client.

**Comment by zeroquinc** [comment] 2022-05-12 11:47
Also have this problem, Jellyfin starts around 300MB but will continue to climb, even going to nearly 10GB when watching a movie.

![Flt6lEPyLZ](https://user-images.githubusercontent.com/39315068/168067882-8daa7cfb-7e5d-4c1c-92d6-6f5118a59a6c.png)

After I restart the container the memory usage is fine again. But will keep climbing untill it reaches 10GB again.
Any fixes?

**Comment by FilipLac** [comment] 2022-05-15 19:11
Well, for me it stabilized when I set max RAM usable for it to 2GB and it is using somewhere around 1GB in peak. And if something happened it would just restart which will drop used ram to just 100-200MB

**Comment by gidoBOSSftw5731** [comment] 2022-05-16 12:44
While I don't want to hijack this thread too much, I will ask, how does Jellyfin even handle caching in memory? In a perfect world, I'd want it to cache *all* thumbnails and *all* library metadata in RAM if it's available, but instead I just see the memory slowly climb (hits about 8G after a week, which is fine when the system it's in has 96, but I kind of wish I could tell it to use more.)
beta3 started about 30 minutes ago
```
$ sudo smem -P jellyfin -k
  PID User     Command                         Swap      USS      PSS      RSS 
2123928 root     sudo smem -P jellyfin -k           0     1.4M     2.3M     5.1M 
2123929 root     /usr/bin/python3 /usr/bin/s        0    11.1M    11.7M    13.9M 
2120303 jellyfin /usr/bin/jellyfin --webdir=        0     1.3G     1.3G     1.3G 
```
Music: 3879
TV: 246 Shows, 7731 Episodes
Movies: 212
Books: 3

**Comment by LP0101** [comment] 2023-02-14 15:54
Hopping into this thread to say I'm experiencing the same issues.

Running JF in Kubernetes. On a fresh restart, it uses ~500 MiB of RAM. It will then slowly climb up, using > 5 GiB at points.

If I set a memory limit of 2GB, it looks like it mostly stabilizes around 1.5 GiB, but will still spike over 2, causing it to get OOM killed.

Screenshot before I put in memory limits, where Jellyfin's working memory continued to grow to over 5GiB: 
![image](https://user-images.githubusercontent.com/16864921/218789120-93a24654-02d9-49c2-90f4-10a458bf0cf8.png)

Screenshot after putting in memory limits: 
![image](https://user-images.githubusercontent.com/16864921/218789265-746fa2ae-b614-46c2-a10e-711f67d5f24f.png)

Notice that it still spikes over 2 GiB on occasion, causing it to get oomkilled, restart to 500 MiB again, then rise right back up.

**Comment by ngosang** [comment] 2023-02-14 18:42
Still having the same problem. This graph is the memory usage in the last 6 months. The memory drops when it's killed.

First 3 months 1.5 GB memory limit. Last 3 months 2 GB limit.

With more memory the service is killed less as expected but we are wasting resources. My server has plenty of resources but some users are running in SBC or NAS.
![image](https://user-images.githubusercontent.com/10577978/218828265-e9f2d6f7-fe63-4847-843c-8f476af02e2b.png)

**Comment by yeyeoke** [comment] 2023-02-24 21:14
I'm experiencing the same issue. 

Running Jellyfin in a LXC in Proxmox, which is limited to 4GB RAM (Previously 8, same issue then). Jellyfins RAM-usage just keeps growing over a couple of weeks which causes the LXC to hang. 
Works fine for a couple of weeks after a reboot while continuing to grow to 100% RAM-usage again. 

Here we can see the issue in a graph: 

![image](https://user-images.githubusercontent.com/12892950/221294289-b9db522b-7c37-4801-b384-88c5a810f23a.png)

**Comment by FilipLac** [comment] 2023-02-25 13:15
For me setting a limit (soft, and hard limit) in docker helped. It just gets over soft limit by something like 20% and like 20% under hard limit and stays there. Since setting it + adding restart policy, no problem appeared and also it seems stable without crashes.

**Comment by danilevy1212** [comment] 2023-02-25 14:35
> For me setting a limit (soft, and hard limit) in docker helped. It just gets over soft limit by something like 20% and like 20% under hard limit and stays there. Since setting it + adding restart policy, no problem appeared and also it seems stable without crashes.

Could you provide an example of how to do this? I use jellyfin on docker too, with a compose.yaml file.

**Comment by LP0101** [comment] 2023-02-25 22:25
I think I've found a correlation between library scans and increasing memory.

I was initially running a library scan every 15 minutes, and that's when my memory usage ballooned to over 5 GB. Setting it to run once a day, my memory usage hasn't become quite so stupid yet.

**Comment by FilipLac** [comment] 2023-02-25 23:32
> > For me setting a limit (soft, and hard limit) in docker helped. It just gets over soft limit by something like 20% and like 20% under hard limit and stays there. Since setting it + adding restart policy, no problem appeared and also it seems stable without crashes.
> 
> Could you provide an example of how to do this? I use jellyfin on docker too, with a compose.yaml file.

I used Portainer for this, so not sure how to set it in compose.yaml

**Comment by FilipLac** [comment] 2023-02-25 23:34
> I think I've found a correlation between library scans and increasing memory.
> 
> I was initially running a library scan every 15 minutes, and that's when my memory usage ballooned to over 5 GB. Setting it to run once a day, my memory usage hasn't become quite so stupid yet.

Yea, it could be something with this. Now most of the time, I'm just scanning it manually when new things are added since it is me who adds new content anyways so there is no point in scanning it every day or sooner when I add few things just 2 or 3 times per month :D

**Comment by momala454** [comment] 2023-03-07 11:46
on a 2gb pi, it is eating the whole memory + swap and make it crash

**Comment by danilevy1212** [comment] 2023-03-07 15:37
@momala454 I use this compose.yaml file to regulate the memory consumption, for the same reasons:

```yaml

version: "3"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    mem_limit: 1024M
    mem_reservation: 128M
    environment:
    ... # Not important
    restart: unless-stopped
```

**Comment by momala454** [comment] 2023-03-07 16:30
@danilevy1212 i am not using docker, but I could do the same using cgroups i think.
However, if it crashes during use, it will cause downtime during a few moments, so it's only some workaround.

Thanks for the tips

**Comment by B1ACK917** [comment] 2023-03-10 07:01
@momala454 Hi there, I'm also facing the high mem usage problem on a Pi4b with 2GB ram. Did you get some idea on how to deal with it? I notice you mentioned you could use the cgroups to limit the jellyfin ram usage, did it work or not? Otherwise i have to set a crontab to restart it at 4am everyday.

**Comment by momala454** [comment] 2023-03-10 08:29
@B1ACK917 right now i'm not yet using jellyfin because navigating only a couple of minutes into the library will make the memory consumption too high. So killing and restarting every time it reaches too much memory will make it restart continuously.

Apparently, this may reduce memory usage, but it's for the next version, which is far from being released (not even in alpha) : https://github.com/jellyfin/jellyfin/pull/8783

Do anyone know a way to pre generate all the images, so when browsing it will not use much memory and load a lot faster ?
I saw that there was a configuration for that but removed

**Comment by B1ACK917** [comment] 2023-03-10 10:55
@momala454 Hi momala, i have just found a way dealing with it, that is to enlarge the **swap** mem. 
The swap mem is a file that managed by Linux kernel, according to my experience, if jellyfin uses extremely high mem, the kernel will swap some map pages to **swap** mem. This may make jellyfin sometimes response slowly, cuz the **swap** mem's speed is quite slower than sram, but by using this, my Pi4b doesn't have to face the OOM crash problem. This way's just as changing the **crash** to **slow**.
I'm going to list the steps here, maybe you can try it.
On your Pi, type `sudo nano /etc/dphys-swapfile` to open the swap config file.
Find the line `CONF_SWAPSIZE=xxx`, remove the '#' comment symbol and change the number to the swap mem size you want, I set it to 4096, which means the swap mem = 4GB.
Go to the last line, uncomment the line `CONF_MAXSWAP=xxx`, otherwise the swap file is limit to 2048 as default.
Save and quit the file, type `sudo /etc/init.d/dphys-swapfile restart` to reload the config.
You can type `htop` to find the swap mem is set to 4GB, which may reduce the crash problem.

**Comment by jsolanes-pcty** [comment] 2023-03-10 15:10
Thanks for the context @gidoBOSSftw5731 

I've avoided using jellyfin due to this thinking it'd use up all available memory. I may try it again and see how much ends up being used this time around. I've since upgraded my server memory and have plenty now assuming jellyfin eventually hits a cap

**Comment by gidoBOSSftw5731** [comment] 2023-03-10 15:12
I will say that it seems to climb somewhat gradually, so I'd think that adding some swap and a daily service restart might be enough to keep it under 2G for most reasonable libraries.

**Comment by gergepalfi** [comment] 2023-03-11 14:47
system info (docker version):
`Version: 10.8.9
Operating System: Linux
Architecture: Arm64`

I have been watching memory usage of Jellyfin using `docker stats` for a while now, there is something horribly wrong with memory management in jellyfin. The memory utilization gradually grows from 150M onward and never stops, this caused my entire server to freeze up multiple times.
syslogs are full of "out of memory" errors caused by jellyfin
`Out of memory: Killed process 9702 (jellyfin)`

To replicate:
start docker stats for monitoring
browse some jellyfin folders and watch memory usage grow
memory use never drops even after logout or closing the jellyfin tab

Result:
jellyfin gets terminated by docker (if memory limit set)
worst case jellyfin uses up all RAM, freezes the entire system for multiple minutes and gets killed by kernel
Finally the vicious circle starts all over again

**Comment by captainnapalm** [comment] 2023-06-23 16:12
Jellyfin's memory keeps creeping up slowly. I've got 64GB RAM in the system, and jellyfin was using over 10GB of RAM with no active sessions. htop shows that it's jellyfin-ffmpeg using the RAM (`/usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg`)

**Comment by cvium** [comment] 2023-06-23 16:37
> Jellyfin's memory keeps creeping up slowly. I've got 64GB RAM in the system, and jellyfin was using over 10GB of RAM with no active sessions. htop shows that it's jellyfin-ffmpeg using the RAM (`/usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg`)

That is not what that means. That is the jellyfin binary with the ffmpeg path as an input argument.

**Comment by captainnapalm** [comment] 2023-06-23 18:54
> > Jellyfin's memory keeps creeping up slowly. I've got 64GB RAM in the system, and jellyfin was using over 10GB of RAM with no active sessions. htop shows that it's jellyfin-ffmpeg using the RAM (`/usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg`)
> 
> That is not what that means. That is the jellyfin binary with the ffmpeg path as an input argument.

Fair enough. Trying to give some detailed info on what I see in htop as using the ram, apologies if I got part of it wrong.

**Comment by gergepalfi** [comment] 2023-06-25 08:30
I just want to post my new findings. (I have been running and testing this setup for 3 months and it seems to work for me)

setup:
```
Pi 3B+ 1GB RAM running 32bit Raspbian Lite

Pi 4B  2GB RAM running 64bit Raspbian Lite

container image: lscr.io/linuxserver/jellyfin:latest
```

64bit OS seems to be the issue in my case. It all started when I moved from Raspbian Lite to Raspbian64 Lite.
Both servers are running the latest OS and Jellyfin docker version. On 32bit it uses 200MiB RAM according to `docker stats` (bit more when multiple sessions are open, but it goes back down nicely) while the 64bit gets OOM killed by kernel every few hours.

I am not sure why there is such a drastic difference in memory usage, it is literally the same setup on both (1TB movies).

The Pi 3B+ has less/slower resources in every way, but jellyfin just runs so much better on a 32bit system

**Comment by theychx** [comment] 2023-07-11 07:40
I can confirm that switching a raspberrypios bullseye docker host  from `arm64` to `armhf`, resolves this issue.

**Comment by ngosang** [comment] 2023-07-11 10:09
@gergepalfi @theychx It's normal than OS with 64 bits uses more RAM for everything and in systems with low RAM it makes a difference.

This issue is not about the "base" memory usage when Jellyfin starts, it's about the memory increase with normal use. Could you do this test? https://github.com/jellyfin/jellyfin/issues/6306#issuecomment-1107823711

**Comment by gergepalfi** [comment] 2023-07-11 10:32
@ngosang please read. https://github.com/jellyfin/jellyfin/issues/6306#issuecomment-1464926882
I am not ganna repeat myself

**Comment by yunusefendi52** [comment] 2023-08-07 02:44
Can anyone try add environment variable `DOTNET_GCHighMemPercent`, ex DOTNET_GCHighMemPercent=28
`28 (hexadecimal) = 40%`

the default value `DOTNET_GCHighMemPercent` is 90% of memory limit in container:
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#high-memory-percent

**Comment by DodoLeDev** [comment] 2023-08-11 23:29
> I just want to post my new findings. (I have been running and testing this setup for 3 months and it seems to work for me)
> 64bit OS seems to be the issue in my case. It all started when I moved from Raspbian Lite to Raspbian64 Lite.
> Both servers are running the latest OS and Jellyfin docker version. On 32bit it uses 200MiB RAM according to `docker stats` (bit more when multiple sessions are open, but it goes back down nicely) while the 64bit gets OOM killed by kernel every few hours.
> The Pi 3B+ has less/slower resources in every way, but jellyfin just runs so much better on a 32bit system
@gergepalfi

You said that jellyfin on a 32bit OS worked far better than on a 64 bit OS. Is it also the case with a 32bit jellyfin on a 64 bit OS?

(I think I will migrate my 64bit jellyfin to the 32bit version on my RPi3B+, but I don't wanna do an entire os reinstall, because it supports arm64 architecture)

**Comment by gergepalfi** [comment] 2023-08-14 19:22
> > I just want to post my new findings. (I have been running and testing this setup for 3 months and it seems to work for me)
> > 64bit OS seems to be the issue in my case. It all started when I moved from Raspbian Lite to Raspbian64 Lite.
> > Both servers are running the latest OS and Jellyfin docker version. On 32bit it uses 200MiB RAM according to `docker stats` (bit more when multiple sessions are open, but it goes back down nicely) while the 64bit gets OOM killed by kernel every few hours.
> > The Pi 3B+ has less/slower resources in every way, but jellyfin just runs so much better on a 32bit system
> > @gergepalfi
> 
> You said that jellyfin on a 32bit OS worked far better than on a 64 bit OS. Is it also the case with a 32bit jellyfin on a 64 bit OS?
> 
> (I think I will migrate my 64bit jellyfin to the 32bit version on my RPi3B+, but I don't wanna do an entire os reinstall, because it supports arm64 architecture)

I have not tested mixing 32 and 64bit. To be more exact I have `10.8.9-1-ls206` running the `arm/v7` variant. Now exactly up and running for 4 months. This happens to be the version I got when I pulled `lscr.io/linuxserver/jellyfin:latest` four months ago on my 32bit raspbian Pi 3B+. Never had any memory issues so I have no reason to fiddle with it. Messing around is not worth the server downtime.

I see that armv7 is no longer supported in the latest versions so this question is still very much up for debate. I also need to find a solution if I want to update.

**Comment by DodoLeDev** [comment] 2023-08-15 00:13
Okay!
I have done the migration from the 64 bits to the 32 bits version, while still having my OS running on arm64, and... IT WORKS FLAWLESSLY! 🤩

**I just have to note some difficulties I had during the migration:**
- You can't install the `armhf` variant of the `jellyfin` package. It will not work. But as it's just a _meta-package_, I just needed to manually initiate the installation of its dependencies: `jellyfin-server` and `jellyfin-web`
- `jellyfin-web` hasn't an `armhf` variant, because its main package is compatible with **all the architectures**
- If you pay attention during the installation process, you'll note that apt will try to install the `armhf` variant of the `sudo` package, in place of the original one. Because I consider it as a core package, I didn't want to have this variant, _but the choice is yours_!
- Once the installation was finished, `jellyfin-server` refused to run, because some dependencies weren't available for the `armhf` architecture: `libstdc++6` and `libicu67` (probably because the jellyfin script assumed they were installed by default on the system). You'll have to manually install them.

But after that, everything was working like a charm! 😍
My last config was recovered, and all I had to do was go through the Welcome Tour to find my library again!

_Hope this message will help people take the plunge to migrate to the 32bit version while waiting for a fix._

**Comment by EffakT** [comment] 2023-08-23 01:19
> Can anyone try add environment variable `DOTNET_GCHighMemPercent`, ex DOTNET_GCHighMemPercent=28 `28 (hexadecimal) = 40%`
> 
> the default value `DOTNET_GCHighMemPercent` is 90% of memory limit in container: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#high-memory-percent

I'm running Jellyfin in a LXC container on Proxmox.
I had Jellyfin with 4GB RAM allocated. Memory usage was gradually raising to 3GB.
I have reduced this container's allocation to 2GB RAM, and 2GB SWAP.
I have set the above ENV to 16 (22% I believe).

Currently, container is sitting at 13% memory usage, I'll use it for a while and keep an eye on the memory usage, and see what happens.

I've loaded a whole bunch of thumbnails (via WebUI, Android TV, and Android App) as per [ngosang](https://github.com/ngosang)'s thoughts. Memory is now up to 23% (400MB). I'm going to leave this config running, and use it as usual and see what happens.

Though, my current thoughts are that if it is sitting stable at around 23%, and we allocate say a 4-5% for OS overhead (what it runs when idle at the moment), this might ENV be working.

**Comment by freaky-m0** [comment] 2023-09-28 11:56
I tried to rise the memory with library scans and it worked. So I think it is something with the library scan. I scan every 15 minutes (jellyfin tasks) and at some point the process gets killed because of OOM. 

I use Debian 12 on a Proxmox VM. I installed Jellyfin with the script from the official guide. My Library is mounted via NFS to the local filesystem. I set "DOTNET_GCHeapHardLimitPOHPercent" and "COMPlus_GCHeapHardLimitPOHPercent" to 32 (50%) in ENV.

Here you can see me click over and over on library scan and the memory consumption is rising up to 1GB (video):
https://github.com/jellyfin/jellyfin/assets/4473764/1768462e-351d-43ba-92e7-e917cfe9eab0

**Comment by freaky-m0** [comment] 2023-10-05 16:59
![image](https://github.com/jellyfin/jellyfin/assets/4473764/487dc2fb-5508-4932-9336-4c93e37f2539)

No out of memory crash this time but it even filled up the whole swap. Everything was gone after I stopped jellyfin. (~250mb of ram whithout it)

**Comment by freaky-m0** [comment] 2023-10-05 16:59
![image](https://github.com/jellyfin/jellyfin/assets/4473764/69a16cb1-a6ed-4237-b00e-906efc4eb2ea)

No out of memory crash this time but it even filled up the whole swap. Everything was gone after I stopped jellyfin. (~250mb of ram whithout it)

**Comment by daniel86** [comment] 2023-10-13 11:27
I am facing the same problem that each library scan allocates memory that never seems to be released again. I can hit the button in the web GUI to run the task and see the memory consumption grow. I am running jellyfin via docker on a debian server, nothing suspicious appears in the logs, otherwise everything works great

**Comment by srcrist** [comment] 2023-10-19 12:27
Having now read through this thread, I do not see any support for a memory leak. Jellyfin's memory management is handled by .NET, and most of the posts in this issue basically amount to "Jellyfin is using more RAM than I would like, or than I want to let it use." Usually because people want to run it in virtualized environments or on underpowered devices. Is anyone able to provide support for a reproducible memory leak that never hits an arbitrary limit?

**Comment by ngosang** [comment] 2023-10-20 05:03
@srcrist Sorry, I didn't know that page. I installed Jellyfin 3 years ago, maybe it was not so clear at that time.

**Based on the fact that Jellyfin needs 8GB of RAM and that there is no memory leak. Can we discuss how to reduce the minimum memory from 8GB -> 500 MB?**

I think it is technically possible with small changes in the current code. How do I know?

1. I use Radarr, Sonarr, Lidarr, Jackett. They are all written in .Net and manage the same media library as Jellyfin. They use the same files, the same posters, same metadata, have a nice web ui so they are comparable to Jellyfin. IMHO they do more complex things than Jellyfin with a lot of background tasks and interactions with 3rd party APIs. Those apps use between 100 and 300 MB of RAM. Never more than 300MB even if they run for months. Jellyfin uses about 5GB with the same media library. I have all transcoding disabled.
2. [As I have commented here.](https://github.com/jellyfin/jellyfin/issues/6306#issuecomment-1107823711) I can start Jellyfin, visit the main page, select a movie and watch it all using only 400 MB of RAM (no transcoding). When I start browsing the media library and days go by, the memory increases to 5 GB. This tells me that the main functionality needs <500 MB to run without changes in the code. The rest of the memory is being used to cache things that are not important. If instead of having them in memory, they are queried in the database, the response time will be a few milliseconds slower, but Jellyfin could run on many more devices.

**Comment by srcrist** [comment] 2023-10-20 14:39
@ngosang You are welcome to start a discussion over at https://github.com/jellyfin/jellyfin-meta/discussions for any code PR you would like to submit to improve the memory footprint. You are also welcome to propose your ideas in the development channels on Matrix/Discord (or the forums) if you'd like to discuss them with other contributors. My only goal here, though, is to give people the chance to provide evidentiary support for an actual memory leak or I am going to close this issue in the next few weeks because there is not, in-actual-fact, a memory leak to document here.

This is not a general discussion space.

**Comment by ngosang** [comment] 2023-10-21 13:16
I did => https://github.com/jellyfin/jellyfin/discussions/10444

**Comment by srcrist** [comment] 2023-10-21 14:02
Wonderful thank you for moving it.

**Comment by ngosang** [comment] 2023-10-21 16:45
@srcrist We both were wrong. There is a big memory leak in Jellyfin caused by the Skia library used to resize images.
Exactly at this line => https://github.com/jellyfin/jellyfin/blob/v10.8.11/Jellyfin.Drawing.Skia/SkiaEncoder.cs#L249
The memory is never released and sadly it's not fixed in the latest Skia release.

Steps to reproduce:
1. I'm using Linux (maybe it's not relevant)
2. Delete the image cache => `.cache/jellyfin/images/resized-images`
3. Browse the movies gallery (with posters or banners)
4. The memory jumps from 300 MB to +1 GB really fast. The memory is "unmanaged memory" outside the Heap and the GC can't release it.
5. This bug should be fixed by Skia. Maybe some of you can report the issue.

![image](https://github.com/jellyfin/jellyfin/assets/10577978/4eefd9a5-cdb9-453c-815c-362770f3a245)

**Comment by srcrist** [comment] 2023-10-21 16:51
@ngosang If you have found an upstream bug, YOU should report the issue upstream. I will leave this open for investigation, but please don't leave it to the ether for someone else to report. Open an issue if you've found one with the appropriate repository.

**Comment by cvium** [comment] 2023-10-21 17:21
Hypothetically, let's assume there is a leak in Skia. Jellyfin does not really touch the images once they've been downloaded and resized. How do you explain the increasing memory usage?

**Comment by ngosang** [comment] 2023-10-21 17:35
I'm downloading new episodes and movies everyday. The posters are rendered in the homepage, in the recent section. Those images are not cached.

**Comment by ngosang** [comment] 2023-10-22 12:11
> If you have found an upstream bug, YOU should report the issue upstream. I will leave this open for investigation, but please don't leave it to the ether for someone else to report. Open an issue if you've found one with the appropriate repository.

@srcrist I don't have to fix everything myself. I have given you evidence that there is a problem with the memory, how to reproduce it and the exact line that is causing the problem.
1. I have fixed the problem in my installation by [disabling Skia using the NullImageEncoder in this line](https://github.com/jellyfin/jellyfin/blob/v10.8.11/Jellyfin.Server/CoreAppHost.cs#L65). Now the images are not resized, the original image is always used but since everything is on local network there is no problem. **Jellyfin now runs with 250MB of RAM without any problem.** 
2. Skia already have 32 issues related to memory leaks with a lot of information about how to reproduce the issue, profiler snapshots, etc... They are not taking care => https://github.com/search?q=repo%3Amono%2FSkiaSharp+memory+leak&type=issues
3. I think we should implement a new image encoder using another library. There are many => https://devblogs.microsoft.com/dotnet/net-core-image-processing/

**Comment by cvium** [comment] 2023-10-22 12:32
Have you tried this? https://github.com/dlemstra/Magick.NET/issues/707#issuecomment-785351620

**Comment by ngosang** [comment] 2023-10-22 13:18
@cvium WoW, it works.
Local profiling with `MALLOC_TRIM_THRESHOLD_=100000`
![image](https://github.com/jellyfin/jellyfin/assets/10577978/49ac03a4-ec07-444c-a312-16dd4fe5d640)
I tried in my ARM64 SBC (Raspberry Pi 4) with LinuxServer Docker image and I get similar results.

I this this fixes the "memory leak" mentioned in this issue. Ship this fix to all users could be really hard.

I would recommend to implement ImageSharp image encode as an alternative. It should be easy to implement, you can keep both encoders and make it configurable. It's a bit slower but it not relay in native code. Just plain .Net code. It should be more portable and not being affected by this issue. You have examples and benchmarks here => https://devblogs.microsoft.com/dotnet/net-core-image-processing/
I can open a discussion or another issue if you want.

Related info => https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html#index-glibc_002emalloc_002etrim_005fthreshold

**Comment by Shadowghost** [comment] 2023-10-22 14:02
Shipping a env var is not that complicated, we can include it in the debian package and set it by default in the docker container.

**Comment by ngosang** [comment] 2023-10-22 14:10
There are a lot of Linux distributions out there, NAS packages, Docker images not maintained by you... Probably a note in the Changelog for package maintainers would be enough.

**Comment by Shadowghost** [comment] 2023-10-22 14:24
Yes that would make sense.

https://github.com/jellyfin/jellyfin-metapackages/commit/5c1b97757459c93c6eb64fd3676a8de99d83c530 and https://github.com/jellyfin/jellyfin/commit/3b6caf4c4065f2e46fc28ebcd86a22861a5ae3e2 should take care of it for our main packaging on Linux.

We'd need to check if macOS and Windows require changes too. Windows does not seem to be affected based on the linked runtime issue, not sure about macOS.

**Comment by srcrist** [comment] 2023-10-22 14:33
>I don't have to fix everything myself. I have given you evidence that there is a problem with the memory, how to reproduce it and the exact line that is causing the problem.

@ngosang That's fine. I'm not telling you that you need to fix everything yourself. I'm not telling you that you need to fix anything with Jellyfin at all. I'm telling you that if you found a bug with another project, and you expect that bug to get reported to said other project--no matter what that project is--you should report the issue to said other project. Simply telling another group of all-volunteer contributors to report your bugs for you is simply not going to happen. 

Best of luck, though. Glad we've made some progress here.

**Comment by EffakT** [comment] 2023-11-12 20:41
After updating to 10.8.12 last week, the memory usage has been averaging a nice 600-700MB.
Seems like its slowly increasing, so may give it another week to confirm.

![Screenshot 2023-11-13 at 9 39 09 AM](https://github.com/jellyfin/jellyfin/assets/7270250/366ee36c-eaba-401d-9f71-2f4b8b8293d4)

**Comment by cacafuti8888** [comment] 2023-11-16 11:57
Hi, i'm on Raspberry Pi 4 and i can confirm as far i checked that the memory consumption doesn't rise as much as before. It keeps in a average 700-800MB of RAM. Finally after sooo much time i can migrate from Emby to Jellyfin.

**Comment by EffakT** [comment] 2023-11-29 20:02
Yep running a Proxmox LXC, after about 2 weeks it is averaging at 700-850MB.

**Comment by srcrist** [comment] 2023-11-29 21:04
Great news all around. Issue closed by https://github.com/jellyfin/jellyfin/pull/10454. If anyone finds additional leaks, please create a new issue with all of the details you have.

**Closed by srcrist** 2023-11-29 21:04 UTC
Labels: bug

**Comment by jarno9981** [comment] 2024-07-21 19:10
i have proxmox vm with 22gb ram assigned but even with 1 user its using 90% of the total ram

**Comment by se7entynine** [comment] 2024-08-03 08:19
@jarno9981 Yeah, there is definitly another memory leak issue. 16GB proxmox LXC and Jellyfin used 15GB RAM yesterday with a whopping 1400 PIDS and rising. Had to restart to make it usable again. Normal memory usage is around 3-4GB with 20 to 30 PIDS and the rise usually happens in 30 minutes to an hour. 

This error started to occur after 10.9.7.

**Comment by jarno9981** [comment] 2024-09-26 13:50
Commenting here has no impact they already closed it

**Comment by cvium** [comment] 2024-09-29 06:42
Commenting with no helpful information has no impact. I have spent countless hours trying to chase down obscure leaks. We need more information.
