### ISSUE TITLE
Jellifin App v9.09 Doesnt show embedded subs

### ISSUE THREAD

**Issue by RandomDelta6** [jellyfin/jellyfin#2918] opened 2020-04-19 11:36 UTC
**Describe the bug**
Embedded subtitles not displayed in the jellifin app

**System (please complete the following information):**
 - OS: windows 10
 - Virtualization: NA
 - Clients: Android 9
 - Browser : Chome 81
 - Jellyfin Version: 10.5.4 Stable
 - Playback: Direct play and transcode
 - Installed Plugins:nono
 - Reverse Proxy: none
 - Base URL: nono
 - Networking: NA
 - Storage:local

**To Reproduce**
playback any hevc media with embedded ass subs on jellifin app 909
The subs still show up and work properly in version 907

**Expected behavior**
subs should appear

**Comment by SLCH** [comment] 2020-04-19 11:44
A lot of subs related issues were fixed in recent releases.
Try installing latest 10.5.4

**Comment by SLCH** [comment] 2020-04-19 11:47
Duplicate of https://github.com/jellyfin/jellyfin-android/issues/307

**Comment by dkanada** [comment] 2020-04-19 11:49
This should be fixed extremely soon, check for an update in a week or less.

**Closed by dkanada** 2020-04-19 11:49 UTC
Labels: bug
