### ISSUE TITLE
从BDMV提取PGS字幕失败

### ISSUE THREAD

**Issue by xujijie** [jellyfin/jellyfin#13042] opened 2024-11-16 11:48 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

PC使用google浏览器访问jellyfin服务，播放BDMV提取PGS字幕失败，无法显示字幕。

### Reproduction steps

使用google浏览器播放BDMV视频，开启PGS字幕功能，无法提取并显示字幕。

### What is the current _bug_ behavior?

使用google浏览器播放BDMV视频，开启PGS字幕功能，无法提取并显示字幕。

### What is the expected _correct_ behavior?

使用google浏览器播放BDMV视频，开启PGS字幕功能，正确显示字幕。

### Jellyfin Server version

10.10.0+

### Specify the build version

 10.10.1

### Environment

```markdown
- OS:
- Linux Kernel:Debian GNU/Linux 12 (bookworm)
- Virtualization:Docker
- Clients:浏览器
- Browser:Google Chrome 131.0.6778.69
- FFmpeg Version:
- Playback Method:直接串流
- Hardware Acceleration:QSV
- GPU Model:Intel UHD Graphics 630
- Plugins:无
- Reverse Proxy:无
- Base URL:无
- Networking:主机
- Storage:本地
```

### Jellyfin logs

```shell
2024-11-16 11:27:08.123010+00:00[19:27:08] [INF] [81] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f mpegts  -f concat -safe 0 -i "/cache/concat/340da48fa42d4855fe559dacff44b8b2.concat"  -map_metadata -1 -map_chapters -1 -threads 8 -map 0:0 -map 0:2 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "2b1b6a7f30ca6fdf7ee63a4007b82644-1.mp4" -start_number 0 -hls_segment_filename "/config/transcodes/2b1b6a7f30ca6fdf7ee63a4007b82644%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/2b1b6a7f30ca6fdf7ee63a4007b82644.m3u8"
2024-11-16 11:27:09.636676+00:00[19:27:09] [INF] [87] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/transcodes/2b1b6a7f30ca6fdf7ee63a4007b82644.m3u8
2024-11-16 11:27:09.638183+00:00[19:27:09] [ERR] [81] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: A task was canceled. URL GET /videos/340da48f-a42d-4855-fe55-9dacff44b8b2/hls1/main/-1.mp4.
2024-11-16 11:27:10.136343+00:00[19:27:10] [INF] [87] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
2024-11-16 11:27:10.137357+00:00[19:27:10] [INF] [87] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
2024-11-16 11:27:10.137722+00:00[19:27:10] [INF] [87] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -ss 00:32:30.500 -noaccurate_seek -fflags +genpts -f mpegts  -f concat -safe 0 -i "/cache/concat/340da48fa42d4855fe559dacff44b8b2.concat"  -map_metadata -1 -map_chapters -1 -threads 8 -map 0:0 -map 0:2 -map -0:s -codec:v:0 copy -tag:v:0 hvc1 -bsf:v hevc_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "2b1b6a7f30ca6fdf7ee63a4007b82644-1.mp4" -start_number 325 -hls_segment_filename "/config/transcodes/2b1b6a7f30ca6fdf7ee63a4007b82644%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/2b1b6a7f30ca6fdf7ee63a4007b82644.m3u8"
2024-11-16 11:27:14.582744+00:00[19:27:14] [INF] [30] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" -copyts -map 0:9 -an -vn -c:s copy "/config/data/subtitles/c/c871feec-09db-9ab9-f5fb-8b289ecd6e0d.sup" -map 0:10 -an -vn -c:s copy "/config/data/subtitles/1/14bab589-971e-8369-7d85-fc07b19afc04.sup" -map 0:11 -an -vn -c:s copy "/config/data/subtitles/a/a27e894c-2e75-b8d4-8135-36b2e881d219.sup" -map 0:12 -an -vn -c:s copy "/config/data/subtitles/e/eda5fc83-25c0-d792-69d9-f06b836c6a1b.sup" -map 0:13 -an -vn -c:s copy "/config/data/subtitles/4/4de72992-546c-b3ae-42c1-ee5825942039.sup" -map 0:14 -an -vn -c:s copy "/config/data/subtitles/5/53230aeb-6000-f748-8349-0a26e6728e98.sup" -map 0:15 -an -vn -c:s copy "/config/data/subtitles/1/103e36e7-9ab1-76a5-bff8-00b206cd567f.sup" -map 0:16 -an -vn -c:s copy "/config/data/subtitles/e/e2d7e5f0-a54a-1913-b808-396df3ed0a4b.sup" -map 0:17 -an -vn -c:s copy "/config/data/subtitles/7/7b916f71-5bca-d0d9-03fc-31e103d894d1.sup"
2024-11-16 11:27:14.595835+00:00ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
2024-11-16 11:27:14.595884+00:00built with gcc 12 (Debian 12.2.0-14)
2024-11-16 11:27:14.595908+00:00configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
2024-11-16 11:27:14.596186+00:00libavutil      59.  8.100 / 59.  8.100
2024-11-16 11:27:14.596200+00:00libavcodec     61.  3.100 / 61.  3.100
2024-11-16 11:27:14.596207+00:00libavformat    61.  1.100 / 61.  1.100
2024-11-16 11:27:14.596321+00:00libavdevice    61.  1.100 / 61.  1.100
2024-11-16 11:27:14.596330+00:00libavfilter    10.  1.100 / 10.  1.100
2024-11-16 11:27:14.596337+00:00libswscale      8.  1.100 /  8.  1.100
2024-11-16 11:27:14.596343+00:00libswresample   5.  1.100 /  5.  1.100
2024-11-16 11:27:14.596378+00:00libpostproc    58.  1.100 / 58.  1.100
2024-11-16 11:27:14.596391+00:00[in#0 @ 0x5579375c75c0] Error opening input: Is a directory
2024-11-16 11:27:14.596397+00:00Error opening input file file:/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam.
2024-11-16 11:27:14.596403+00:00Error opening input files: Is a directory
2024-11-16 11:27:14.598692+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/c/c871feec-09db-9ab9-f5fb-8b289ecd6e0d.sup
2024-11-16 11:27:14.598732+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/1/14bab589-971e-8369-7d85-fc07b19afc04.sup
2024-11-16 11:27:14.598777+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/a/a27e894c-2e75-b8d4-8135-36b2e881d219.sup
2024-11-16 11:27:14.598800+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/e/eda5fc83-25c0-d792-69d9-f06b836c6a1b.sup
2024-11-16 11:27:14.598809+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/4/4de72992-546c-b3ae-42c1-ee5825942039.sup
2024-11-16 11:27:14.598852+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/5/53230aeb-6000-f748-8349-0a26e6728e98.sup
2024-11-16 11:27:14.598874+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/1/103e36e7-9ab1-76a5-bff8-00b206cd567f.sup
2024-11-16 11:27:14.598892+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/e/e2d7e5f0-a54a-1913-b808-396df3ed0a4b.sup
2024-11-16 11:27:14.598901+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/7/7b916f71-5bca-d0d9-03fc-31e103d894d1.sup
2024-11-16 11:27:14.602824+00:00[19:27:14] [WRN] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Unable to get streams for File:/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam
2024-11-16 11:27:14.602898+00:00MediaBrowser.Common.FfmpegException: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam"
2024-11-16 11:27:14.602906+00:00at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllExtractableSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
2024-11-16 11:27:14.602932+00:00at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllExtractableSubtitles(MediaSourceInfo mediaSource, CancellationToken cancellationToken)
2024-11-16 11:27:14.603752+00:00[19:27:14] [ERR] [42] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/data/subtitles/e/e2d7e5f0-a54a-1913-b808-396df3ed0a4b.sup'. URL GET /Videos/340da48f-a42d-4855-fe55-9dacff44b8b2/340da48fa42d4855fe559dacff44b8b2/Subtitles/16/0/Stream.pgssub.
```

### FFmpeg logs

```shell
2024-11-16 11:27:14.595908+00:00configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
2024-11-16 11:27:14.596186+00:00libavutil      59.  8.100 / 59.  8.100
2024-11-16 11:27:14.596200+00:00libavcodec     61.  3.100 / 61.  3.100
2024-11-16 11:27:14.596207+00:00libavformat    61.  1.100 / 61.  1.100
2024-11-16 11:27:14.596321+00:00libavdevice    61.  1.100 / 61.  1.100
2024-11-16 11:27:14.596330+00:00libavfilter    10.  1.100 / 10.  1.100
2024-11-16 11:27:14.596337+00:00libswscale      8.  1.100 /  8.  1.100
2024-11-16 11:27:14.596343+00:00libswresample   5.  1.100 /  5.  1.100
2024-11-16 11:27:14.596378+00:00libpostproc    58.  1.100 / 58.  1.100
2024-11-16 11:27:14.596391+00:00[in#0 @ 0x5579375c75c0] Error opening input: Is a directory
2024-11-16 11:27:14.596397+00:00Error opening input file file:/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam.
2024-11-16 11:27:14.596403+00:00Error opening input files: Is a directory
2024-11-16 11:27:14.598692+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/c/c871feec-09db-9ab9-f5fb-8b289ecd6e0d.sup
2024-11-16 11:27:14.598732+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/1/14bab589-971e-8369-7d85-fc07b19afc04.sup
2024-11-16 11:27:14.598777+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/a/a27e894c-2e75-b8d4-8135-36b2e881d219.sup
2024-11-16 11:27:14.598800+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/e/eda5fc83-25c0-d792-69d9-f06b836c6a1b.sup
2024-11-16 11:27:14.598809+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/4/4de72992-546c-b3ae-42c1-ee5825942039.sup
2024-11-16 11:27:14.598852+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/5/53230aeb-6000-f748-8349-0a26e6728e98.sup
2024-11-16 11:27:14.598874+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/1/103e36e7-9ab1-76a5-bff8-00b206cd567f.sup
2024-11-16 11:27:14.598892+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/e/e2d7e5f0-a54a-1913-b808-396df3ed0a4b.sup
2024-11-16 11:27:14.598901+00:00[19:27:14] [ERR] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam" to /config/data/subtitles/7/7b916f71-5bca-d0d9-03fc-31e103d894d1.sup
2024-11-16 11:27:14.602824+00:00[19:27:14] [WRN] [42] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Unable to get streams for File:/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam
2024-11-16 11:27:14.602898+00:00MediaBrowser.Common.FfmpegException: ffmpeg subtitle extraction failed for file:"/media3/Movie/Godzilla x Kong The New Empire 2024 UHD BluRay 2160p HEVC Atmos TrueHD7.1-loongkee@MTeam"
2024-11-16 11:27:14.602906+00:00at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllExtractableSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
2024-11-16 11:27:14.602932+00:00at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllExtractableSubtitles(MediaSourceInfo mediaSource, CancellationToken cancellationToken)
2024-11-16 11:27:14.603752+00:00[19:27:14] [ERR] [42] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/data/subtitles/e/e2d7e5f0-a54a-1913-b808-396df3ed0a4b.sup'. URL GET /Videos/340da48f-a42d-4855-fe55-9dacff44b8b2/340da48fa42d4855fe559dacff44b8b2/Subtitles/16/0/Stream.pgssub.
```

**Comment by nyanmisaka** [comment] 2024-11-16 11:50
duplicate of https://github.com/jellyfin/jellyfin/issues/13041

**Closed by nyanmisaka** 2024-11-16 11:50 UTC
Labels: bug
