### ISSUE TITLE
RC - Chromecast still not working

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4707] opened 2020-12-06 22:00 UTC
Reports from here https://github.com/jellyfin/jellyfin/issues/3852#issuecomment-739429096 saying there's still an issue.

**Comment by tyhawk** [comment] 2020-12-07 21:00
https://jellyfin.mydomain.com/System/Info/Public:
`{"LocalAddress":"http://10.0.1.19:8096","ServerName":"Jellyfin","Version":"10.7.0","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"8dae97e3b7b64e69a6a8e47afda7d406","StartupWizardCompleted":true}`

... and the Chromecast issue still doesn't seem to be resolved without using the ' known' workarounds.

**Comment by hawken93** [comment] 2020-12-07 23:02
So is your client on the rc release?

**Comment by tyhawk** [comment] 2020-12-08 07:23
> So is your client on the rc release? jellyfin-web 10.7.0-rc1 should not look at System/Info/Public. The app might still because it's on stable I believe.

No, de client is on stable. So I guess my confirmation should be taken with a spoon full of salt ;-)

**Comment by idittansikte** [comment] 2020-12-08 16:06
This is very related or duplicate of #4616

**Comment by idittansikte** [comment] 2020-12-09 17:28
I got both web and android to work!. Anyhow, I needed to select **unstable** in Chromecast setting in Jellyfin interfaceand also reload the tab in web and **clear the cache** on Jellyfin app in Android application settings. I can confirm it now works behind a reverse proxy without any dirty hacks.

**Closed** 2020-12-10 07:50 UTC
Labels: bug
