### ISSUE TITLE
playback settings fail to apply, folder missing

### ISSUE THREAD

**Issue by AncientMystic** [jellyfin/jellyfin#2692] opened 2020-03-28 02:18 UTC
applying settings under playback/transcoding fails

folder programdata/jellyfin/server/transcodes is not created automatically and once created settings apply fine. 

using server version 10.5.2

**Comment by JustAMan** [comment] 2020-04-03 23:02
Duplicate of https://github.com/jellyfin/jellyfin/issues/2677

**Closed by JustAMan** 2020-04-03 23:02 UTC
Labels: bug, duplicate
