### ISSUE TITLE
Having TV seasons  at two different places causes duplicate listing in library

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin#2978] opened 2020-04-25 10:49 UTC
**Describe the bug**
When having seasons of a TV series in two different places, the TV show shows up as duplicate in the library. 

**System (please complete the following information):**
 - OS: Windows 10 ver 1909
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.4
 - Playback: N/A
 - Installed Plugins: Playback reporting, Open Subtitles, Slack Notifications
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local for all intents and purposes, normal directory containing normal files, rar2fs mounts and sshfs mounted directory from server containing normal files and rar2fs mounts.

**To Reproduce**
I assume this'll work to reproduce
1. Place a TV series folder in two different directories, each with one or more seasons in it, but none of them with the same
2. Add both directories to same library (mixed content)
3. TV show will probably show up twice

**Expected behavior**
Jellyfin ought to 'merge' the TV show into one listing. It seems to do this partially: neither of my directories were complete (one contained season 6-7, one contained season 1-5+8-9), but both listings of the show showed all seasons and episodes.

**Logs**
N/A

**Screenshots**
https://i.imgur.com/8xvFHMX.png

**Additional context**
* Both listings have different IDs when I click on them and check the ID parameter in the URL
* I *think* that playing an episode from a season not in the folder (e.g. playing an episode from season 5 from the listing that corresponds to the directory that only contains season 6-7) doesn't work, but both listings show the full, 'merged' TV show

**Comment by oddstr13** [comment] 2020-04-25 21:59
Duplicate of #904

**Closed by oddstr13** 2020-04-25 21:59 UTC
Labels: bug
