### ISSUE TITLE
Jellyfin not hardware decoding yuv444p10

### ISSUE THREAD

**Issue by 1000thSummer** [jellyfin/jellyfin#12657] opened 2024-09-16 19:13 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin version 10.9.11
CPU: intel n100
Platform: win10

While playing HEVC yuv444p10le encoded videos, transcoding was invoked as my client (edge browser) does not support the codec.

Jellyfin seems to go below process:
- QSV hardware decoding
- use CPU to do ~color space conversion~ chroma downsampling (yuv444p10 to yuv420)
- QSV hardware encoding

The second step uses a lot of CPU whereas QSV already provide `vpp_qsv` filters that does the GPU hardware processing

i.e., when transcoding locally, I use below cmd that barely uses CPU:
```sh
.\ffmpeg.exe -hwaccel qsv -i file:"<input_file_name>" -vf 'hwupload=extra_hw_frames=64,vpp_qsv=format=p010le' -c:a aac -b:a 128k -c:v hevc_qsv -preset slow -profile:v main10 -global_quality 23 "<output_file_name>"
```

Expected behavior:
The ffmpeg cmd that jellyfin uses should be smart enough to try `vpp_qsv` filters when possible.

### Reproduction steps

1. transcoding any YUV444 encoded video.
2. observe the extreme CPU usage

### What is the current _bug_ behavior?

very high CPU usage because of ~color space conversion~ chroma downsampling

### What is the expected _correct_ behavior?

very little CPU usage during ~conversion~ chroma downsampling

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS:win10
- Linux Kernel:N/A
- Virtualization:No
- Clients: Jellyfin Web 10.9.11
- Browser: edge
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin
- Playback Method:
- Hardware Acceleration: intel qsv
- GPU Model: integrated GPU on n100
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Mostly copied the ffmpeg CLI logs

ffmpeg -analyzeduration 200M -probesize 1G -ss 00:13:18.000 -noaccurate_seek -init_hw_device d3d11va=dx11:,vendor=0x8086 -init_hw_device qsv=qs@dx11 -filter_hw_device qs -noautorotate -canvas_size 1920x1080 -i file:"D:\Downloads\AIR 2005 EP06 [BD 1920x1080 VFR HEVC-yuv444p10 FLAC] - yan04000985.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -b:v 5653017 -maxrate 5653017 -bufsize 11306034 -profile:v:0 main -level 40 -g:v:0 72 -keyint_min:v:0 72 -filter_complex "[0:2]scale=-1:1080:fast_bilinear,scale,crop,pad=max(1920\,iw):max(1080\,ih):(ow-iw)/2:(oh-ih)/2:black@0,crop=1920:1080[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1920\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1920/a\,1080))/2)*2,format=yuv420p[main];[main][sub]overlay=eof_action=pass:repeatlast=0" -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "D:\Programs\JellyfinData\transcodes\73373800ca47b68d394abb647b5e7bb9-1.mp4" -start_number 266 -hls_segment_filename "D:\Programs\JellyfinData\transcodes\73373800ca47b68d394abb647b5e7bb9%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "D:\Programs\JellyfinData\transcodes\73373800ca47b68d394abb647b5e7bb9.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13-win32 (GCC)
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
```

**Comment by gnattu** [comment] 2024-09-17 01:10
It is not jellyfin not using hardware chroma downsampling, it is jellyfin currently rejects everything not in yuv420p10 for hardware decoding because lots of hardware does not decode that at all and provide no graceful way of fallback. This is planned but currently not implemented.

**Comment by 1000thSummer** [comment] 2024-09-17 01:32
> It is not jellyfin not using hardware chroma downsampling, it is jellyfin currently rejects everything not in yuv420p10 for hardware decoding because lots of hardware does not decode that at all and provide no graceful way of fallback. This is planned but currently not implemented.

Thanks for the quick response, that well explains my question.

I do see people testing AV1/HEVC that are hardware transcoded (hardware decode and hardware encode), can I assume that these videos are all encoded in yuv420p10?

**Comment by gnattu** [comment] 2024-09-17 01:34
> can I assume that these videos are all encoded in yuv420p10?

Most if not all medias for consuming are released in 420p10 format. 422 and 444 footages generally come from cameras directly and that is less common for most users.

**Comment by nyanmisaka** [comment] 2024-09-17 12:24
@1000thSummer You can try this PR #12664

**Closed** 2024-09-19 13:14 UTC
Labels: enhancement

**Comment by 1000thSummer** [comment] 2024-11-05 21:59
hi @nyanmisaka thanks for the hard working.
I tested with both nightly build and the latest [v10.10.1](https://github.com/jellyfin/jellyfin/releases/tag/v10.10.1) for video streaming.

I saw fatal errors while the transcoding YUV444 10bit. here are the logs

```
ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device d3d11va=dx11:,vendor=0x8086 -init_hw_device qsv=qs@dx11 -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -noautorotate -c:v hevc_qsv -canvas_size 1920x1080 -i file:"D:\Downloads\AIR 2005 EP08 [BD 1920x1080 VFR HEVC-yuv444p10 FLAC] - yan04000985.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -b:v 7143558 -maxrate 7143558 -bufsize 14287116 -profile:v:0 main -level 40 -g:v:0 72 -keyint_min:v:0 72 -filter_complex "[0:2]scale,scale=1920:1080:fast_bilinear,format=bgra,hwupload=derive_device=qsv:extra_hw_frames=64[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,vpp_qsv=format=p010[main];[main][sub]overlay_qsv=eof_action=pass:repeatlast=0:w=1920:h=1080" -start_at_zero -codec:a:0 flac -ac 2 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "D:\Programs\JellyfinData\transcodes\eb60c9c4681c2de8b121bf37df5c75ad-1.mp4" -start_number 0 -hls_segment_filename "D:\Programs\JellyfinData\transcodes\eb60c9c4681c2de8b121bf37df5c75ad%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "D:\Programs\JellyfinData\transcodes\eb60c9c4681c2de8b121bf37df5c75ad.m3u8"

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with clang version 18.1.8
  configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[AVHWDeviceContext @ 00000134b3cd5e80] Using device 8086:46d1 (Intel(R) UHD Graphics).
Input #0, matroska,webm, from 'file:D:\Downloads\AIR 2005 EP08 [BD 1920x1080 VFR HEVC-yuv444p10 FLAC] - yan04000985.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-04-30T04:56:12.000000Z
  Duration: 00:24:11.99, start: 0.000000, bitrate: 7143 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 89.019000
      Metadata:
        title           : Chapter 13
    Chapter #0:1: start 89.019000, end 179.042000
      Metadata:
        title           : Chapter 14
    Chapter #0:2: start 179.042000, end 693.022000
      Metadata:
        title           : Chapter 15
    Chapter #0:3: start 693.022000, end 1329.992000
      Metadata:
        title           : Chapter 16
    Chapter #0:4: start 1329.992000, end 1420.015000
      Metadata:
        title           : Chapter 17
    Chapter #0:5: start 1420.015000, end 1451.985000
      Metadata:
        title           : Chapter 18
  Stream #0:0(jpn): Video: hevc (Rext), yuv444p10le(tv), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
      Metadata:
        title           : by yan04000985
        BPS             : 6329783
        BPS-eng         : 6329783
        DURATION        : 00:24:11.901000000
        DURATION-eng    : 00:24:11.901000000
        NUMBER_OF_FRAMES: 35890
        NUMBER_OF_FRAMES-eng: 35890
        NUMBER_OF_BYTES : 1148777366
        NUMBER_OF_BYTES-eng: 1148777366
        _STATISTICS_WRITING_APP: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_APP-eng: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_DATE_UTC: 2017-04-30 04:56:12
        _STATISTICS_WRITING_DATE_UTC-eng: 2017-04-30 04:56:12
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s16 (default)
      Metadata:
        BPS             : 784200
        BPS-eng         : 784200
        DURATION        : 00:24:11.985000000
        DURATION-eng    : 00:24:11.985000000
        NUMBER_OF_FRAMES: 17016
        NUMBER_OF_FRAMES-eng: 17016
        NUMBER_OF_BYTES : 142330864
        NUMBER_OF_BYTES-eng: 142330864
        _STATISTICS_WRITING_APP: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_APP-eng: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_DATE_UTC: 2017-04-30 04:56:12
        _STATISTICS_WRITING_DATE_UTC-eng: 2017-04-30 04:56:12
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(jpn): Subtitle: hdmv_pgs_subtitle (pgssub), 1920x1080 (default)
      Metadata:
        BPS             : 27721
        BPS-eng         : 27721
        DURATION        : 00:24:04.810000000
        DURATION-eng    : 00:24:04.810000000
        NUMBER_OF_FRAMES: 697
        NUMBER_OF_FRAMES-eng: 697
        NUMBER_OF_BYTES : 5006590
        NUMBER_OF_BYTES-eng: 5006590
        _STATISTICS_WRITING_APP: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_APP-eng: mkvmerge v9.9.0 ('Pick Up') 64bit
        _STATISTICS_WRITING_DATE_UTC: 2017-04-30 04:56:12
        _STATISTICS_WRITING_DATE_UTC-eng: 2017-04-30 04:56:12
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 (hevc_qsv) -> setparams:default (graph 0)
  Stream #0:2 (pgssub) -> scale:default (graph 0)
  overlay_qsv:default (graph 0) -> Stream #0:0 (hevc_qsv)
  Stream #0:1 -> #0:1 (flac (native) -> flac (native))
Press [q] to stop, [?] for help
[Parsed_vpp_qsv_5 @ 00000134c22ae380] Error running VPP: unknown error (-1)
[fc#0 @ 00000134c2581b80] Error while filtering: Unknown error occurred
[fc#0 @ 00000134c2581b80] Task finished with error code: -1313558101 (Unknown error occurred)
[fc#0 @ 00000134c2581b80] Terminating thread with return code -1313558101 (Unknown error occurred)
[vost#0:0/hevc_qsv @ 00000134c2493c80] Could not open encoder before EOF
[vost#0:0/hevc_qsv @ 00000134c2493c80] Task finished with error code: -22 (Invalid argument)
[vost#0:0/hevc_qsv @ 00000134c2493c80] Terminating thread with return code -22 (Invalid argument)
[out#0/hls @ 00000134c15d3340] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!

```

**Comment by gnattu** [comment] 2024-11-05 23:43
I'm unable to reproduce with my sample even with pgs subtitles using almost the exact same ffmpeg cli (only changes filename) on my UHD 770 which completes the transcode successfully also on windows. Now I'm not sure if the vpp processing capability was nerfed, or it is due to some Intel driver issues.

**Comment by 1000thSummer** [comment] 2024-11-06 03:28
thanks @gnattu , I believe n100 shared similar GPU architecture with 12th gen CPU, not sure what could possible go wrong.
let me update driver and see if I can reproduce this issue.

**Comment by nyanmisaka** [comment] 2024-11-06 07:02
@1000thSummer https://github.com/jellyfin/jellyfin/pull/12973

There is a fix for this, but it should be unrelated to this error, as the errors in your log indicate a failure when doing YUV444 10bit -> YUV420 10bit, or a failure when overlaying BGRA 8bit to YUV420 10bit, both of which should be supported by the driver on intel Gen12 graphics. The problem may reappear when we enable those paths in the future.
