### ISSUE TITLE
[Issue]: Video stops playing and returns to menu when using syncplay

### ISSUE THREAD

**Issue by Spazznyan** [jellyfin/jellyfin#11666] opened 2024-05-15 16:57 UTC
### Please describe your bug

When using Synplay with my partner overseas (Australia <-> Belgium), videos will play for around 20 seconds then abruptly stop; returning both users to the media selection menu.

This occurs for both clients when running any combination of Jellyfin Media Player 1.10.0 or chromium based browser, but does NOT occur when using an older version of Jellyfin Media Player (eg 1.9.1). I am guessing something with the newer web client is messing up, but is bypassed when using the older client with the 'Force External Web Client' option disabled (Enabling this option in 1.9.1 causes this same issue to occur).

### Reproduction Steps

1. Client(Host) creates syncplay group using either: Jellyfin Media Player (1.10.0) or Browser
2. Client(Remote) joins syncplay group
3. Client(Host) starts media playback
4. Media playback starts on both clients
5. Media playback stops abruptly after 20-25 seconds for both clients

### Jellyfin Version

10.9.1

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: N/A
- Virtualization: N/A 
- Clients: Jellyfin Media Player, Browser
- Browser: Chrome 114
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct play
- Hardware Acceleration: NVENC, None
- GPU Model: 3060ti, 2070 Super
- Plugins: Skin Manager, Fanart
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
[2024-05-16 02:13:52.829 +10:00] [INF] [43] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "REMOTEUSER". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-05-16 02:13:52.830 +10:00] [INF] [43] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 20000000, RemoteIP: "XXX.XXX.XXX.XXX", IsInLocalNetwork: False
[2024-05-16 02:13:58.045 +10:00] [INF] [36] Emby.Server.Implementations.SyncPlay.Group: Session "9672d453bef50854c239ade040c881a3" requested Ready in group "d48b5a0b-2ecc-4eed-8917-f842ae057509" that is Waiting.
[2024-05-16 02:13:58.047 +10:00] [WRN] [36] MediaBrowser.Controller.SyncPlay.GroupStates.WaitingGroupState: Session "9672d453bef50854c239ade040c881a3" resumed playback, group "d48b5a0b-2ecc-4eed-8917-f842ae057509" has 1 seconds to recover.
[2024-05-16 02:13:58.048 +10:00] [INF] [36] Emby.Server.Implementations.SyncPlay.Group: Group "d48b5a0b-2ecc-4eed-8917-f842ae057509" switching from Waiting to Playing.
[2024-05-16 02:13:59.056 +10:00] [INF] [41] Emby.Server.Implementations.SyncPlay.Group: Session "2523e876bbdd9c417dc63eca45333219" requested Ready in group "d48b5a0b-2ecc-4eed-8917-f842ae057509" that is Playing.
[2024-05-16 02:13:59.434 +10:00] [INF] [41] Emby.Server.Implementations.SyncPlay.Group: Session "9672d453bef50854c239ade040c881a3" requested Ready in group "d48b5a0b-2ecc-4eed-8917-f842ae057509" that is Playing.
[2024-05-16 02:14:21.558 +10:00] [INF] [43] Emby.Server.Implementations.SyncPlay.Group: Session "2523e876bbdd9c417dc63eca45333219" requested IgnoreWait in group "d48b5a0b-2ecc-4eed-8917-f842ae057509" that is Playing.
[2024-05-16 02:14:21.562 +10:00] [INF] [43] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.10.0" playing "Category 55 Emergency Doomsday Crisis". Stopped at "22480" ms
[2024-05-16 02:14:23.162 +10:00] [INF] [45] Emby.Server.Implementations.SyncPlay.Group: Session "9672d453bef50854c239ade040c881a3" requested IgnoreWait in group "d48b5a0b-2ecc-4eed-8917-f842ae057509" that is Playing.
[2024-05-16 02:14:23.489 +10:00] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.10.0" playing "Category 55 Emergency Doomsday Crisis". Stopped at "24816" ms
[2024-05-16 02:15:19.078 +10:00] [INF] [49] Emby.Server.Implementations.SyncPlay.Group: Session "9672d453bef50854c239ade040c881a3" left group "d48b5a0b-2ecc-4eed-8917-f842ae057509".
```

### Please attach any browser or client logs here

![image](https://github.com/jellyfin/jellyfin/assets/98095416/aa22883c-84c4-4ec6-9605-47f30166fd52)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DetermineAbsurd** [comment] 2024-05-15 20:00
Issue still present in 10.9.1, same log messages

**Comment by Spazznyan** [comment] 2024-05-15 20:58
> Issue still present in 10.9.1, same log messages

sorry for confusion, this is the version I am on. Have edited the issue to be more clear (it was not in the dropdown box)

**Comment by Memphinstein** [comment] 2024-05-15 22:38
Can confirm issue described by @Spazznyan when running latest jellyfin-server 10.9.1 with jellyfin-media-player 1.10.0 - at least on Windows 11.

Issue appears to be player thinks file is finished?

The steps to reproduce is easier than above;
1. Join a syncplay group (no remote/partner required)
2. Play video
3. Watch 20/30 seconds, stop will occur.

If you are not in a syncplay group, playback will be fine.

When watching with another, we found the stops will not be synced, but may a different issue.

I hope you can fix this issue, and thank you for your time and effort on maintaining this project.

### Logs

Note: Times will be an hour out due to BST / UTC differences.

**_Server_**

```
[2024-05-15 22:09:36.699 +00:00] [INF] WS "x.y.z.8" request
[2024-05-15 22:09:40.455 +00:00] [INF] Session "c279c75e9ed98ad28d683cc4e083c3ad" created group "4161d842-1692-436a-b040-4bc55c38dc76".
[2024-05-15 22:10:01.628 +00:00] [INF] Session "c279c75e9ed98ad28d683cc4e083c3ad" requested Play in group "4161d842-1692-436a-b040-4bc55c38dc76" that is Idle.
[2024-05-15 22:10:01.629 +00:00] [INF] Group "4161d842-1692-436a-b040-4bc55c38dc76" switching from Idle to Waiting.
[2024-05-15 22:10:01.660 +00:00] [INF] User policy for "memph". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-05-15 22:10:01.716 +00:00] [INF] Adding playback tracker : SmVsbHlmaW5NZWRpYVBsYXllciAxLjkuMSAod2luZG93cy14ODZfNjQgMTApfDE3MTA2MTIwMzMzMDc1-bfd7d3c37a38440e8653ab14a00148f1-3efee05fe7b314e90da1a56cf6418c32
[2024-05-15 22:10:01.717 +00:00] [INF] PlaybackTracker : Adding Start Event : 05/15/2024 22:10:01
[2024-05-15 22:10:01.717 +00:00] [INF] Creating StartPlaybackTimer Task
[2024-05-15 22:10:01.717 +00:00] [INF] StartPlaybackTimer : Entered
[2024-05-15 22:10:01.834 +00:00] [INF] Processing playback tracker : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjkuMSAod2luZG93cy14ODZfNjQgMTApfDE3MTA2MTIwMzMzMDc1-bfd7d3c37a38440e8653ab14a00148f1-3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:01.835 +00:00] [INF] Session "c279c75e9ed98ad28d683cc4e083c3ad" requested Ready in group "4161d842-1692-436a-b040-4bc55c38dc76" that is Waiting.
[2024-05-15 22:10:01.835 +00:00] [WRN] Session "c279c75e9ed98ad28d683cc4e083c3ad" resumed playback, group "4161d842-1692-436a-b040-4bc55c38dc76" has 1 seconds to recover.
[2024-05-15 22:10:01.836 +00:00] [INF] Group "4161d842-1692-436a-b040-4bc55c38dc76" switching from Waiting to Playing.
[2024-05-15 22:10:21.716 +00:00] [INF] session.RemoteEndPoint : "x.y.z.8"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : event_playing_id     = "3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : event_user_id        = "bfd7d3c37a38440e8653ab14a00148f1"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : session_playing_id   = "3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : session_user_id      = "bfd7d3c37a38440e8653ab14a00148f1"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Media Player"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : e.DeviceName         = "Shimarin"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : ItemName             = "The Demon Girl Next Door - s01e01 - Yuko Awakens!! For Family Reasons You're Now a Demon Girl"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : ItemId               = "3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : ItemType             = "Episode"
[2024-05-15 22:10:21.716 +00:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-05-15 22:10:21.716 +00:00] [INF] Playback tracker found, adding playback info : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjkuMSAod2luZG93cy14ODZfNjQgMTApfDE3MTA2MTIwMzMzMDc1-bfd7d3c37a38440e8653ab14a00148f1-3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:21.716 +00:00] [INF] Saving playback tracking activity in DB
[2024-05-15 22:10:21.730 +00:00] [INF] StartPlaybackTimer : Exited
[2024-05-15 22:10:21.836 +00:00] [INF] Processing playback tracker : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjkuMSAod2luZG93cy14ODZfNjQgMTApfDE3MTA2MTIwMzMzMDc1-bfd7d3c37a38440e8653ab14a00148f1-3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:31.684 +00:00] [INF] Session "c279c75e9ed98ad28d683cc4e083c3ad" requested IgnoreWait in group "4161d842-1692-436a-b040-4bc55c38dc76" that is Playing.
[2024-05-15 22:10:31.687 +00:00] [INF] Playback stopped reported by app "Jellyfin Media Player" "1.10.0" playing "Yuko Awakens!! For Family Reasons You're Now a Demon Girl". Stopped at "29906" ms
[2024-05-15 22:10:31.697 +00:00] [INF] Playback stop tracker found, processing stop : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjkuMSAod2luZG93cy14ODZfNjQgMTApfDE3MTA2MTIwMzMzMDc1-bfd7d3c37a38440e8653ab14a00148f1-3efee05fe7b314e90da1a56cf6418c32"
[2024-05-15 22:10:31.698 +00:00] [INF] PlaybackTracker : Adding Stop Event : 05/15/2024 22:10:31
[2024-05-15 22:10:31.698 +00:00] [INF] Saving playback tracking activity in DB
[2024-05-15 22:10:41.166 +00:00] [INF] Session "c279c75e9ed98ad28d683cc4e083c3ad" left group "4161d842-1692-436a-b040-4bc55c38dc76".
[2024-05-15 22:10:41.166 +00:00] [INF] Group 4161d842-1692-436a-b040-4bc55c38dc76 is empty, removing it.
[2024-05-15 22:10:41.176 +00:00] [INF] WS "x.y.z.8" closed
```

**_Client (Partially ommited due to length)_**

```
2024-05-15 23:10:21.832 [info] unknown @ 0 - JS: Requesting url without automatic networking: http://x.y.z.134:8096/Sessions/Playing/Progress
2024-05-15 23:10:31.676 [info] unknown @ 0 - JS: Error while waiting for `playbackstart` event! startPlayback Timed out.
2024-05-15 23:10:31.676 [info] unknown @ 0 - JS: Requesting url without automatic networking: http://x.y.z.134:8096/SyncPlay/SetIgnoreWait
2024-05-15 23:10:31.677 [debug] unknown @ 0 - cplayer: EOF code: 4  
2024-05-15 23:10:31.677 [debug] unknown @ 0 - Enabling OS screensaver
2024-05-15 23:10:31.677 [info] unknown @ 0 - JS: [nowPlayingBar:onPlaybackStopped] event: playbackstop
2024-05-15 23:10:31.677 [info] unknown @ 0 - JS: nowplaying event: playbackstop
2024-05-15 23:10:31.677 [debug] onLoadingChanged @ 181 - WebEngineLoadRequest starting: file:///C:/Program Files/Jellyfin/Jellyfin Media Player/web-client/desktop/index.html#/details?id=3efee05fe7b314e90da1a56cf6418c32&context=home&serverId=1f86280183784e6e9289b04a947ab1d5
2024-05-15 23:10:31.716 [debug] unknown @ 0 - cplayer: finished playback, success (reason 2)
2024-05-15 23:10:31.716 [info] unknown @ 0 - Entering state: canceled
```

Can provide very full log if required.

**Comment by derrickkhuynh** [comment] 2024-05-15 22:57
This is a duplicate of this : https://github.com/jellyfin/jellyfin-web/issues/5485

**Comment by oddstr13** [comment] 2024-05-15 23:17
Duplicate of jellyfin/jellyfin-web#5485

**Closed by oddstr13** 2024-05-15 23:17 UTC
Labels: bug
