### ISSUE TITLE
[Issue]: Jellyfin versus symbol &

### ISSUE THREAD

**Issue by Nemesiz** [jellyfin/jellyfin#11424] opened 2024-04-24 09:22 UTC
### Please describe your bug

Jellyfin have a problem or a bug versus &

If symbol & exist in file name ( example **Planes - Fire & Rescue.mkv** )
1. After you add video to collection records in xml shows as `<CollectionItem>
      <Path>/media/video/Planes/Planes - Fire &amp; Rescue.mkv</Path>
    </CollectionItem>`
2. Browsing video library you can see video not in collection
3. In SQLite file path is `/media/video/Planes/Planes - Fire & Rescue.mkv`

If symbol & exist in video title ( example **Gnomeo & Juliet** ) Jellyfin will create two collections : `Gnomeo &amp; Juliet Collection [boxset]` and `Gnomeo & Juliet Collection [boxset]`

### Reproduction Steps

1. Have a file with symbol & in name
2. Scan library

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: Linux jellyfin 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
- Virtualization: KVM
- Clients: Jellyfin 1.9.1
- Browser: Vivaldi 6.6.3271.61
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Allow media playback (only)
- Hardware Acceleration: none
- GPU Model: none
- Plugins: AniDB 7.0.0.0 , AudioDB 10.8.13.0 , LDAP-Auth 17.0.0.0 , MusicBrainz 10.8.13.0 , OMDb 10.8.13.0 , Studio Images 10.8.13.0 , TMDb 10.8.13.0
- Reverse Proxy: none
- Base URL: private
- Networking: local
- Storage: local
```

### Jellyfin logs

```shell
nothing to show.
10.8.13 version do not log a lot in debug level
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheMelmacian** [comment] 2024-05-13 22:47
Related to or duplicate of: https://github.com/jellyfin/jellyfin/issues/10767

**Comment by awnumar** [comment] 2024-09-29 16:08
I have this same issue in 10.9.11. It's now created three collections:

```
Lilo & Stitch Collection
Lilo &amp; Stitch Collection
Lilo &amp;amp; Stitch Collection
```

because one of the movies has an `&` in it

**Comment by Shadowghost** [comment] 2024-09-29 16:19
Are you guys using the boxset plugin? Or just creation of boxsets from NFOs?

**Comment by TheMelmacian** [comment] 2024-09-30 10:08
I use the boxset plugin. But I already had a look at the code of the plugin and couldn't find any code that would explain why the escaping/un-escaping of & (and probably other xml characters) is not probably working (see: #10767).
The boxset name is extracted from the movie metadata and boxset creation is handled by the server code.
So I think the boxset plugin can trigger the problem but is not the root cause of the issue.

To prevent spreading the discussion and analysis across multiple issues, we should close one as duplicate of the other.

**Comment by felix920506** [comment] 2024-10-04 14:38
Closing this as  a duplicate of #10767

**Closed by felix920506** 2024-10-04 14:38 UTC
Labels: bug
