### ISSUE TITLE
jellyfin on roku - channel guide has no indicator of what channel you are on

### ISSUE THREAD

**Issue by cpankonien** [jellyfin/jellyfin#4764] opened 2020-12-11 14:13 UTC
New channel guide is great, but on start there is no "blue box" indicating what channel you are actually on, and hitting arrow buttons moves something but you can't see what is moving. Hitting asterisk button (options) and changing a view or sort setting then hitting back arrow sometimes causes the blue indicator to show up, but I have not been able to accurately reproduce the circumstances that cause the blue box to show up.

**Comment by crobibero** [comment] 2020-12-11 14:14
Can you please fill out the issue template?

**Comment by anthonylavado** [comment] 2020-12-11 15:03
Closing as a duplicate of the later issue that has been opened with more detail, which I also moved to the jellyfin-roku repository.

Now here: https://github.com/jellyfin/jellyfin-roku/issues/336

**Closed by anthonylavado** 2020-12-11 15:03 UTC
Labels: duplicate
