### ISSUE TITLE
[Issue]: "Back" button leads to wrong url

### ISSUE THREAD

**Issue by Alecs1710** [jellyfin/jellyfin#8025] opened 2022-06-28 11:26 UTC
### Please describe your bug

In any single content screen (Movie, TV Show, Season, Episode ...) if you refresh the page and the use the "Back" button from Jellyfin Web, it redirects to "{whateverYourURLWouldBe}:8096/web" making the ui unresponsive.

Thi happens every time. Can't really try different environments to see te extent of the issue, but seems very straight forward in the sense that it always does it.

As seen in the screenshot, that's what the URL becomes after doing exactly those 2 steps

If I'm not mistaken this has happened since 10.8.0

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Win11
- Virtualization: None
- Clients: Browser
- Browser: Chrome 102
- FFmpeg Version: Not Relevant
- Playback Method: Not Relevant
- Hardware Acceleration: Not Relevant
- Plugins: Not relevant IMO
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local(ish)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/72394940/176167232-0b27e329-841f-4da7-9d2e-3245f7240ffa.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment] 2022-06-28 18:03
Looks like another duplicate of https://github.com/jellyfin/jellyfin-web/issues/3521

**Closed by thornbill** 2022-06-28 18:03 UTC
Labels: bug
