### ISSUE TITLE
TMDB wont use fallback if there is no translation

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin#4822] opened 2020-12-19 00:49 UTC
**Describe the bug**
Jellyfin TMDB plugin does not respect TMDB system of translation. If there is no official (legit) translation, field should stay empty (and on tmdb translation page page will be used placeholder as Episode 1) and "apps" using API should use fallback language.

This bug also affects movies.

**System (please complete the following information):**
 - OS: W10
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.6.4

**To Reproduce**
1. Check on TMDB if Episodes of Show has translated overview only and no episode title (aka no official title availible) like Slovak Witcher https://www.themoviedb.org/tv/71912-the-witcher/season/1
2. Add such TV show to library
3. Jellyfin wont use fallback language and episodes are shows as "Episode 1" etc.
4. Open tv show and check bad result, it will look like screenshot

**Expected behavior**
If there is no translation of episode name or overview, fallback should be Always used. As on TMDB page, if there is no translation = fallback should be always used to provide information.

Warning: Jellyfin should respect IF show has episodes with name like "Episode 1" etc (example https://www.themoviedb.org/tv/77236-a-discovery-of-witches/season/1).

**Screenshots**
Jellyfin: Wrong pulled metadata from TMDB
![jellyfin](https://user-images.githubusercontent.com/29764734/102675494-e4d68d80-4199-11eb-9e55-70de8cc5ed3f.png)

TMDB screen, episode title has no translation because there is no official one = fallback used (in my example is fallback language english)... but overview has translation = translation used)
![tmdb](https://user-images.githubusercontent.com/29764734/102675496-e607ba80-4199-11eb-8145-e86abe10812c.png)

TMDB translation screen, "empty" translation shows as placeholder string "Epizóda 1". Also see Warning in Expected behavior.
![tmdb translation](https://user-images.githubusercontent.com/29764734/102675898-7266ad00-419b-11eb-9d76-2e717e45363b.png)

Edit: Present in 10.7 RC1

**Comment by crobibero** [comment] 2020-12-19 00:58
Related / duplicate of https://github.com/jellyfin/jellyfin/issues/2320

**Comment by nextlooper42** [comment] 2020-12-19 01:13
> Related / duplicate of #2320

Related - probably, not duplicate, more like extension of that bug :D Really annoying bug.

**Comment by nextlooper42** [comment] 2020-12-26 14:07
Update:

Movies with only overview translated seems to be working (Title/Poster/Tagline in English, Overview in Slovak) and also movies with only title translated seems to be working too (Title in Slovak, Overview/Poster/Tagline in English).

**Comment by Ullmie02** [comment] 2021-02-07 18:13
If an episode doesn't have a translation, the TMDB website shows the unlocalized title. The API however returns a localized "Episode X".
We could pass English as a fallback metadata language to the API to get the unlocalized metadata in case there is no translation

**Comment by daullmer** [comment] 2022-10-26 21:48
I have just looked at this again today and found out that it's not possible to get fallback values from another language from the TMDb API. It works on their site, but not with their API. So we will not and can not implement this with the current TMDb API.

See: https://www.themoviedb.org/talk/5abe2eff0e0a264a5a00d324

**Closed by daullmer** 2022-10-26 21:48 UTC
Labels: bug, confirmed
