### ISSUE TITLE
[Issue]: Playlists deleted during Library Scan

### ISSUE THREAD

**Issue by geekygamer211** [jellyfin/jellyfin#8445] opened 2022-09-22 17:32 UTC
### Please describe your bug

I am trying to create playlists for my music in Jellyfin, after creating a playlist, it gets deleted during the library scan. I was able to find that this bug was supposedly "fixed" back in Feb? (Issue #2425), but I am still able to reproduce this bug consistently. I simply want the playlists to remain in my library.

Steps to Reproduce
1. Create a new playlist
2. Initiate library scan
3. After the library scan finishes, the playlist disappears. 

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Windows 10 (21H2, build 19044.2075)
- Browser: Firefox
- Plugins: None 
- Reverse Proxy: Caddy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geekygamer211** [comment] 2023-01-26 22:42
This issue still affects me (now Jellyfin 10.8.8)

**Comment by Back4More420** [comment] 2023-01-29 13:41
This happens to me as well. Uninstall reinstall, removed any file location address with . in them( Lord.of.the.Rings.mp4) after they are made and show up for everyone they disappear.
Windows 10
Jellyfin Version: 10.8.9 Architecture: X64
Clients: All
Browser: All
Playback: n/a
Installed Plugins: AudioDB, Bookshelf, Cover art archive,MusicBrainz, OMDB, OPDS, opensubtitle, Reports, skin manager, studio images, TMDB, TVDB
Reverse Proxy:none
Base URL: none
Storage: local
The playlists are still in C:\ProgramData\Jellyfin\Server\data\playlists but wont show again until I remove them and remake playlists for every user!  I noticed I had MANY playlists when I first installed Jellyfin so I removed 45 or so made by music m3u files in music library and the playlist finally showed up on android tv but still disappear when a scan library happens.
 I have a lifetime license on plex but I am done with them so when this is fixed I will be shutting down plex. This is the only thing holding me back from switching everyone to Jelly. I will donate same amount for a lifetime license to Jellyfin soon. Thanks

**Comment by Back4More420** [comment] 2023-06-10 08:52
Still disappears from my own playlist  when a scan is done! Chat GPT could fix this!

**Comment by Back4More420** [comment] 2023-07-15 23:55
Still broken! You haven't released 10.9 yet so it is still is broken!

**Comment by Shadowghost** [comment] 2023-07-16 06:09
Yes but the issue tracking is mainly for the master branch. And it's not getting backported to 10.8 because the changes are too severe.

**Comment by srcrist** [comment] 2023-10-10 03:41
Issue closed as duplicate of https://github.com/jellyfin/jellyfin/issues/2425.

**Closed by srcrist** 2023-10-10 03:41 UTC
Labels: bug
