### ISSUE TITLE
Jellyfin 10.7.0-RC4 TMDb Metadata broken

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5348] opened 2021-03-02 12:19 UTC
**Describe the bug**
When clicking the identify button and searching "the lord of the rings" I don't get any results.
This also seems the case when doing the automatically whole library metadata refresh.
There are no errors in my log
And it apparently does work for my series while they have the same library settings

When doing a library refresh the whole server crashes because of a bug in the TMDb box sets plugin.
https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/32
Maybe these 2 things are connected and will be fixed when the plugin is updated, but I don't know

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: -
 - Browser: -
 - Jellyfin Version: 10.7.0-RC4
 - Playback: -
 - Installed Plugins: TMDb box sets(disabled also gave the same results, there is also a fatal crash in this plugin which I reported)
 - Reverse Proxy: nginx
 - Base URL: jellyfin.mydomain.com
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. Go to a movie
2. Click on identify
3. try to search for the movie
4. See no results

**Expected behavior**
I expected results

**Logs**
There are no logs when trying to identify, but refreshing all metadata crashes jellyfin because of the TMDb box sets error.
https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/32
There is already a bug report about this on the plugins page, but since it might be connected here are those logs:
```
[09:28:18] [FTL] [28] Main: Unhandled Exception
System.MissingMethodException: Method not found: 'Boolean MediaBrowser.Model.Entities.ProviderIdsExtensions.HasProviderId(MediaBrowser.Model.Entities.IHasProviderIds, MediaBrowser.Model.Entities.MetadataProvider)'.
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<>c.<GetMoviesFromLibrary>b__7_1(Movie m)
at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()
Unhandled exception. System.MissingMethodException: Method not found: 'Boolean MediaBrowser.Model.Entities.ProviderIdsExtensions.HasProviderId(MediaBrowser.Model.Entities.IHasProviderIds, MediaBrowser.Model.Entities.MetadataProvider)'.
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<>c.<GetMoviesFromLibrary>b__7_1(Movie m)
at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by BaronGreenback** [comment] 2021-03-02 12:42
Looks like it might be fixed in https://github.com/jellyfin/jellyfin/pull/5339

**Comment by ikomhoog** [comment] 2021-03-02 13:00
ahh, so it is related to my other ticket that I linked, I didnt know a total metadata refresh would crash jellyfin at the time.
I'm trying to get into helping development but I'm very new to GitHub and open source development
As a start where can I find the tags that are used to test this change?

**Comment by BaronGreenback** [comment] 2021-03-02 13:07
If it is this problem: PR 5339 was an accidental breakage in the code. A rollback has already been committed to  https://github.com/jellyfin/jellyfin/tree/release-10.7.z

**Comment by ikomhoog** [comment] 2021-03-02 13:32
I tried testing on the unstable docker tag, if I should use a more specific tag please tell me where I can find it.

The crash seems fixed but the metadata is not available, the identify screen shows no results for "the lord of the rings".

**Comment by cvium** [comment] 2021-03-03 07:13
> 
> 
> I tried testing on the unstable docker tag, if I should use a more specific tag please tell me where I can find it.
> 
> The crash seems fixed but the metadata is not available, the identify screen shows no results for "the lord of the rings".

It would be helpful if you can do the following:
1. Open the Identify popup
2. Open the developer tools in your browser (typically opens with F12)
3. Navigate to Network
4. Use Identify
5. Post the results of the network query (see below for an example using Chrome)

![image](https://user-images.githubusercontent.com/675118/109767708-3ec2ed00-7bf8-11eb-9352-a9c2eb43645c.png)

**Comment by cvium** [comment] 2021-03-03 08:11
Never mind. Found the cause. Fixed in https://github.com/jellyfin/jellyfin/pull/5356

**Closed** 2021-03-03 16:24 UTC
Labels: bug, confirmed

**Comment by ikomhoog** [comment] 2021-03-03 20:54
I just updated to the latest docker unstable release.
The its still empty:
![image](https://user-images.githubusercontent.com/9083045/109869983-d6acef00-7c69-11eb-9f29-74a1cce46b83.png)

I also noticed that I get a javascript error on a page load, not during the identify.
The links here all go to some info, which I can open.
![image](https://user-images.githubusercontent.com/9083045/109870217-1ecc1180-7c6a-11eb-84e4-1cefd4cc215c.png)

**Comment by cvium** [comment] 2021-03-04 21:23
Which docker image are you using? Please provide the name and tag.

**Comment by ikomhoog** [comment] 2021-03-04 23:10
I'm using the official unstable docker image: jellyfin/jellyfin:unstable
I though this was a build that was made after the pull request was accepted.
Did something go wrong with the automation?

**Comment by cvium** [comment] 2021-03-05 07:18
Fedora builds are currently broken and the image is only pushed when all builds succeed.

**Comment by ikomhoog** [comment] 2021-03-05 08:14
Sorry, On the other issue I got a reaction like I was being aggressive/rude.
I did not mean to be rude, I just wanted to make things clear.
I have removed that message, and again I want to say sorry if it came through as aggressive/rude.
