### ISSUE TITLE
10.7.5 - Massive CPU and Memory Usage

### ISSUE THREAD

**Issue by billyinferno** [jellyfin/jellyfin#6151] opened 2021-06-05 15:51 UTC
**Describe the bug**
Jellyfin starting multiple instance of jellyfin/web after upgrade that using a lot CPU and memory, and it keep increasing (looks like memory leak?). There are no error logged on the jellyfin.log file, and once all memory being filled the access to server will be slowed down and eventually crash the server.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Jellyfin Version: Upgrade from 10.7.2 to 10.7.5
 - Storage: NFS

**To Reproduce**
Upgrade Jellyfin from 10.7.2 into 10.7.5 (normal installation)

**Expected behavior**
Should't causing any massive CPU or memory usage.

**Server Logs**
```
[2021-06-05 23:24:33.007 +08:00] [INF] Watching directory /media/xxx
[2021-06-05 23:24:56.056 +08:00] [INF] Watching directory /media/yyy
[2021-06-05 23:25:17.339 +08:00] [INF] Watching directory /media/zzz
... after memory reach 16GB ...
[2021-06-05 23:32:49.286 +08:00] [WRN] As of "00:00:13.0462039", the heartbeat has been running for "00:00:01" which is longer than "06/05/2021 15:32:36 +00:00". This could be caused by thread pool starvation.
[2021-06-05 23:33:19.110 +08:00] [WRN] As of "00:00:03.8057749", the heartbeat has been running for "00:00:01" which is longer than "06/05/2021 15:33:15 +00:00". This could be caused by thread pool starvation.
[2021-06-05 23:34:15.271 +08:00] [WRN] As of "00:00:16.5519451", the heartbeat has been running for "00:00:01" which is longer than "06/05/2021 15:33:58 +00:00". This could be caused by thread pool starvation.
[2021-06-05 23:35:01.050 +08:00] [WRN] As of "00:00:16.6251399", the heartbeat has been running for "00:00:01" which is longer than "06/05/2021 15:34:44 +00:00". This could be caused by thread pool starvation.
```

**Screenshots**
1st start, multiple jellyfin/web and already use 10GB of RAM
https://imgur.com/egfwCRk

After wait for few min(s) memory usage increased, and server become slow
https://imgur.com/9HyQgOQ

**Comment by billyinferno** [comment] 2021-06-05 15:55
If need any log from the server, please do let me know. It only happen on 10.7.5, when I revert back to 10.7.2 it was normal again.

**Comment by cvium** [comment] 2021-06-05 15:59
Duplicate of #5961

**Closed** 2021-06-05 16:00 UTC
Labels: bug
