### ISSUE TITLE
Latest Shows only shows recent by number of episodes in show(s)

### ISSUE THREAD

**Issue by thecdnhermit** [jellyfin/jellyfin#10281] opened 2023-09-26 05:13 UTC
### Please describe your bug

Pretty simple: "Latest Movies" lists about the most recent 16 movies added. "Latest Shows" seems to only list shows by episodes added. As in, if three shows with five episodes are added, all three will show up. However, if three shows with thirty episodes are added, only the last one added will show up.

Seems that "Latest Shows" is going by number of files, same as "Latest Movies", when maybe it should be going by show title.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.10.0-24-amd64
- Virtualization: n/a
- Clients: web/android
- Browser: firefox/brave
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: n/a
- Reverse Proxy: apache2
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Please attach any screenshots here

https://irc.thecdnhermit.com/fileshare/M4vA2e6aql8E40Fs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment] 2023-10-08 06:23
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/1880

**Closed by srcrist** 2023-10-08 06:23 UTC
Labels: bug
