### ISSUE TITLE
[Issue]: Too many musician names in the music library will overwrite the rest of the page.

### ISSUE THREAD

**Issue by fqscfqj** [jellyfin/jellyfin#10109] opened 2023-08-14 01:57 UTC
### Please describe your bug

Should hide some of the music creators or adaptively reposition the webui.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:winsows 11
- Linux Kernel:
- Virtualization:
- Clients:Browser
- Browser:edge 115
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/68098251/0b7e8a33-c1a6-40f3-a7b5-9a96aa0125ef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment] 2023-09-23 04:07
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/4228

**Closed by thornbill** 2023-09-23 04:07 UTC
Labels: bug
