### ISSUE TITLE
In music libraries, Jellyfin scans for artist metadata even when instructed not to

### ISSUE THREAD

**Issue by emes81** [jellyfin/jellyfin#7365] opened 2022-02-27 21:20 UTC
**Describe the bug**
Some metadata is downloaded, despite all the relevant settings being disabled

To Reproduce
Create a new music library, disable all metadata fetching settings; allow JF to complete scanning the files. For some (not all) artists, metadata will have been downloaded (images, bios, musicbrainz/audiodb artist IDs)

Expected behavior
No metadata should be downloaded at all

System (please complete the following information):

    OS: Debian 11
    Jellyfin Version: 10.7.7

**Comment by 1337joe** [comment] 2022-02-27 22:20
Duplicate of #5778 and/or #2217

**Closed by 1337joe** 2022-02-27 22:20 UTC
