### ISSUE TITLE
Playlists/Favorites empty after a while

### ISSUE THREAD

**Issue by Tech6767** [jellyfin/jellyfin#12501] opened 2024-08-22 15:59 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

For one account, which is not the admin, I experience the problem for a while, that the content of playlists/favorites get deleted after a while.
It seemed to me like it was a few at a time, not all at once. This does not happen on another account I use, which has permissions to manage the server.
Besides that, I did not find any differences in settings, only differences in library access.

### Reproduction steps

I am not sure how to reproduce, the only possible factors I could think of:
1. add a favorite via jellyfin web gui / add movie to a playlist
2. wait (maybe possibly a truenas restart, but I haven't specifically tested, yet I saw that here: [[Issue]: Empty Playlists in latest version 10.9.0 #10509](https://github.com/jellyfin/jellyfin/issues/10509)

### What is the current _bug_ behavior?

After a while (days, weeks) you see that the playlists get emptier/empty and favorites disappear.
The playlists are still visible and show preview images of the movies in there.

### What is the expected _correct_ behavior?

They stay until I manually remove them.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: 6.8.12-1-pve
- Virtualization: Proxmox - Linux Container
- Clients: Jellyfin App for Android/iPhone, Infuse for Apple TV, Sony Blu-Ray-Player (DLNA), Browser
- Browser: Brave
- FFmpeg Version: not installed
- Playback Method: Direct Play/Stream
- Hardware Acceleration: no
- GPU Model: /
- Plugins: AdioDB, Bookshelf, DLNA, InfuseSync, Kodi Sync Queue (recently disabled, not needed), MusicBrainz, OMDb, Open Subtitles, SkinManager, Studio Images, TMDb
- Reverse Proxy: NGINX Proxy Manager
- Base URL:
- Networking:
- Storage: TrueNAS Core mounted via SMB in LXC
```

### Jellyfin logs

```shell
sorry I don't know what to post, as I don't know when it happens, but I have noticed some weird lines:

"
System.IO.IOException: The process cannot access the file '/var/lib/jellyfin/data/collections/Indiana Jones Filmreihe [boxset]/collection.xml' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.LocalMetadata.Savers.BaseXmlSaver.SaveAsync(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadataAsync(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
2024-08-18 16:08:54.831 +00:00] [INF] Item in "Ice Age Filmreihe" cannot be found at "/mnt/HEIM/1_FILME/01_mit-deutscher-Tonspur/2_Mehrteiler/Ice Age/Ice Age - Kollision voraus (2016).mkv"
[2024-08-18 16:08:54.831 +00:00] [INF] Item in "Ice Age Filmreihe" cannot be found at "/mnt/HEIM/1_FILME/01_mit-deutscher-Tonspur/2_Mehrteiler/Ice Age/Ice-Age-3-Die-Dinosaurier-sind-los_2009.avi"
[2024-08-18 16:08:54.832 +00:00] [INF] Item in "Ice Age Filmreihe" cannot be found at "/mnt/HEIM/1_FILME/01_mit-deutscher-Tonspur/2_Mehrteiler/Ice Age/Ice-Age-4-Voll-verschoben_2012.avi"
[2024-08-18 16:08:54.832 +00:00] [ERR] Error in metadata saver
"

"
[2024-08-18 16:08:54.810 +00:00] [INF] Item in "Saw Filmreihe" cannot be found at "/mnt/HEIM/[...]Saw Filmreihe/Saw (2004).avi"
" (and these continue for a while...

this looks rather normal:

"
[2024-08-19 12:00:58.169 +00:00] [INF] Started library sync
[2024-08-19 12:00:59.004 +00:00] [INF] Library Sync: Updated 257 items
[2024-08-19 12:00:59.004 +00:00] [INF] Finished library sync, taking "00:00:00.8354559"
[2024-08-19 12:01:00.084 +00:00] [INF] Creating image collage and saving to "/var/cache/jellyfin/temp/8b40791e19ef4ba49a0b232ace5b168f.png"
[2024-08-19 12:01:00.330 +00:00] [INF] Completed creation of image collage and saved to "/var/cache/jellyfin/temp/8b40791e19ef4ba49a0b232ace5b168f.png"
"
```

**Comment by felix920506** [comment] 2024-09-04 00:24
duplicate of #12408

**Closed by felix920506** 2024-09-04 00:24 UTC
Labels: bug

**Comment by lcestou** [comment] 2024-09-09 19:26
Actually, tinkering with the code today, I found that is being hidden with CSS for some reason with this styling and also the class `hide` on it:

```
@media (min-width: 40em) {
    .listIconButton-autohide {
        display: none !important;
    }
}
```

There was like a never ending spinning for them to load and was able to bring them backup by clicking the 3 dots menu and clicking the back arrow for them to instantly load up. Something must have happened to Favorites recently :(

But at least I am able to find my fix for now (Is my workflow for work) to listen to my favorites.

I just remove the CSS styling and remove the class to shuffle: Boom I'm back manually.

**Comment by nielsvanvelzen** [comment] 2024-10-02 07:49
The issue you linked is not closed, this one was closed as a duplicate.

**Comment by Tech6767** [comment] 2024-10-02 08:54
> The issue you linked is not closed, this one was closed as a duplicate.

Pardon me, mixed it up with this one: https://github.com/jellyfin/jellyfin/issues/10509

This seems to be a quite different bug though. As https://github.com/jellyfin/jellyfin/issues/12408 is still open, I will just watch its status. 
Thank you.

**Comment by onny** [comment] 2024-10-19 19:55
Still affected by this issue with the latest version 10.9.11. All my music playlists get wiped after a while.

Maybe because the external drive with the music source was probably detached some hours?

**Comment by Shadowghost** [comment] 2024-10-19 20:29
> Maybe because the external drive with the music source was probably detached some hours?

Quite likely yes if the task for cleaning up playlists/collections ran in that time.
