### ISSUE TITLE
[Issue]: Import DVD movie folders

### ISSUE THREAD

**Issue by Paskui** [jellyfin/jellyfin#8977] opened 2022-12-29 14:12 UTC
### Please describe your bug

This is my issue.
1. I link a DVD movie folder in the Library
2. I try to watcht it but doesn't work
3. It looks that doesn't read the DVD folders structure.
4. I will be happy to fix it by myself but I don't know how to install the application on Visual studio. (Last time I was developing it was 10 years back)

Thanks

Paskui

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: Windows 19
- Virtualization:
- Clients: BROWSER
- Browser: FIRE FOX 108.0.1 (64-bit)
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-12-29 15:02:31.127 +01:00] [INF] [70] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 0 seconds
[2022-12-29 15:02:31.130 +01:00] [INF] [70] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-12-29 15:03:01.617 +01:00] [WRN] [90] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Environment/Drives" to "127.0.0.1" in 0:00:05.6046454 with Status Code 200
[2022-12-29 15:03:22.711 +01:00] [WRN] [82] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Environment/Drives" to "127.0.0.1" in 0:00:05.6089744 with Status Code 200
[2022-12-29 15:03:49.470 +01:00] [INF] [71] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "RefreshMediaLibraryTask"
[2022-12-29 15:03:49.470 +01:00] [WRN] [90] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Library/VirtualFolders?collectionType=movies&refreshLibrary=true&name=DVD" to "127.0.0.1" in 0:00:00.7276231 with Status Code 204
[2022-12-29 15:03:49.472 +01:00] [INF] [82] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2022-12-29 15:03:49.475 +01:00] [INF] [82] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2022-12-29 15:03:49.811 +01:00] [ERR] [82] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.ArgumentException: Second path fragment must not be a drive or UNC name. (Parameter 'expression')
   at System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(String& directory, String& expression, MatchType matchType)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at DvdLib.Ifo.Dvd..ctor(String path)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.FetchFromDvdLib(Video item)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2022-12-29 15:03:55.906 +01:00] [INF] [73] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 6 seconds
[2022-12-29 15:03:55.906 +01:00] [INF] [82] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "C:\MEDIA\PELICULA TEMPORAL\LOTR_RETURN_OF_THE_KING_SEE_D4"
[2022-12-29 15:03:55.909 +01:00] [INF] [73] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-12-29 15:04:19.536 +01:00] [INF] [90] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2022-12-29 15:04:19.538 +01:00] [INF] [90] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "C:\MEDIA\PELICULA TEMPORAL\LOTR_RETURN_OF_THE_KING_SEE_D4"
[2022-12-29 15:04:19.540 +01:00] [INF] [90] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2022-12-29 15:04:19.556 +01:00] [INF] [71] Emby.Drawing.ImageProcessor: Creating image collage and saving to "C:\ProgramData\Jellyfin\Server\cache\temp\244630b1e0c543478a9dc4b6542a2df9.png"
[2022-12-29 15:04:20.076 +01:00] [INF] [71] Emby.Drawing.ImageProcessor: Completed creation of image collage and saved to "C:\ProgramData\Jellyfin\Server\cache\temp\244630b1e0c543478a9dc4b6542a2df9.png"
[2022-12-29 15:04:25.455 +01:00] [INF] [80] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 5 seconds
[2022-12-29 15:04:25.455 +01:00] [INF] [73] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "C:\MEDIA\PELICULA TEMPORAL\LOTR_RETURN_OF_THE_KING_SEE_D4"
[2022-12-29 15:04:25.458 +01:00] [INF] [80] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

### FFmpeg logs

```shell
/videos/8c491413-f2f7-0781-d6b6-eb6edd00e426/live.m3u8

{"Protocol":0,"Id":"8c491413f2f70781d6b6eb6edd00e426","Path":"C:\\MEDIA\\PELICULA TEMPORAL\\LOTR_RETURN_OF_THE_KING_SEE_D4\\VIDEO_TS","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"","Size":null,"Name":"VIDEO_TS/DVD","IsRemote":false,"ETag":"543b6ca4c9f21c87d81daf7a932499c0","RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":2,"IsoType":null,"Video3DFormat":null,"MediaStreams":[],"MediaAttachments":[],"Formats":[],"Bitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

ffmpeg -analyzeduration 200M -autorotate 0 -i file:"C:\MEDIA\PELICULA TEMPORAL\LOTR_RETURN_OF_THE_KING_SEE_D4\VIDEO_TS" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/2a1e9c9a4fb22418e62b657378c2bb10/" -hls_segment_filename "C:\ProgramData\Jellyfin\Server\transcodes\2a1e9c9a4fb22418e62b657378c2bb10%d.ts" -hls_playlist_type event -hls_list_size 0 -y "C:\ProgramData\Jellyfin\Server\transcodes\2a1e9c9a4fb22418e62b657378c2bb10.m3u8"


ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220324
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3f -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
file:C:\MEDIA\PELICULA TEMPORAL\LOTR_RETURN_OF_THE_KING_SEE_D4\VIDEO_TS: Permission denied
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment] 2023-01-18 23:53
Duplicate of #8739

**Closed by Bond-009** 2023-01-18 23:53 UTC
Labels: bug
