### ISSUE TITLE
please reopen https://github.com/jellyfin/jellyfin/issues/3852

### ISSUE THREAD

**Issue by Koma-Andrea** [jellyfin/jellyfin#4696] opened 2020-12-06 13:19 UTC
bug https://github.com/jellyfin/jellyfin/issues/3852 is still in place.

**Comment by hawken93** [comment] 2020-12-06 13:38
See #4616

**Comment by thornbill** [comment] 2020-12-06 14:02
Closing this as a duplicate of #4616. If this is not accurate please provide some details about the specific error you are encountering. Thanks!

**Closed by thornbill** 2020-12-06 14:02 UTC
Labels: bug, duplicate
