### ISSUE TITLE
Wrong command line for Quick Sync HEVC 10-bit transcode

### ISSUE THREAD

**Issue by han3sui** [jellyfin/jellyfin#1488] opened 2019-06-24 03:43 UTC
**Describe the bug**
Intel Quick Sync cannot transocde HEVC 10bit

CPU：I5 8500，UHD630

System：WinServer2019 Latest

**Logs**
Stream mapping:
  Stream #0:0 (hevc_qsv) -> overlay:main (graph 0)
  Stream #0:3 (pgssub) -> scale (graph 0)
  scale (graph 0) -> Stream #0:0 (h264_qsv)
  Stream #0:1 -> #0:1 (truehd (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[hevc_qsv @ 0000021fe7509080] Could not load the requested plugin '15dd936825ad475ea34e35f3f54217a6': specified object was not found (-9)
[hevc_qsv @ 0000021fe7509080] Error loading plugins
[hevc_qsv @ 0000021fe7509080] Error initializing an MFX session
Error while decoding stream #0:0: Function not implemented
frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
Too many packets buffered for output stream 0:1.
[libmp3lame @ 0000021fe77bc7c0] 3 frames left in the queue on closing
Conversion failed!

**Comment by EraYaN** [comment] 2019-06-24 12:53
If I recall correctly Kaby Lake is the first uArch that will do 10-bit HEVC in hardware.

**Comment by han3sui** [comment] 2019-06-25 05:44
I think need add 

-load_plugin hevc_hw

in ffmpeg command

**Comment by cvium** [comment] 2019-06-25 05:51
> 
> 
> I think need add
> 
> -load_plugin hevc_hw
> 
> in ffmpeg command

For reference https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=5204

**Comment by sparky8251** [comment] 2019-06-25 10:35
Well, going by this:

![Screenshot_20190625_063318](https://user-images.githubusercontent.com/1992688/60091692-358b3880-9713-11e9-87df-cc7171bbccd3.png)

The CPU is a Coffee Lake uarch. I bet that HVEC 10-bit just has limited support in JF because of the odd way its supported by hardware. Feel this is a legitimate enhancement we need to work on, not a bug.

**Comment by han3sui** [comment] 2019-06-25 10:51
> Well, going by this:
> 
> ![Screenshot_20190625_063318](https://user-images.githubusercontent.com/1992688/60091692-358b3880-9713-11e9-87df-cc7171bbccd3.png)
> 
> The CPU is a Coffee Lake uarch. I bet that HVEC 10-bit just has limited support in JF because of the odd way HVEC is supported by hardware. I feel this is a legitimate enhancement we need to work on, not a bug.

thanks, hope better jellyfin.

**Comment by sparky8251** [comment] 2019-06-25 10:55
Whoa! Dont close this. We need it or we will forget!

I just provided info proving you should be able to HW dec/enc HVEC 10bit files with your hardware and that it is indeed a bug with JF.

**Comment by cvium** [comment] 2019-06-25 11:11
HEVC* (it stands for High Efficiency Video Coding)

I'm fairly certain it qualifies as a bug. Judging by this thread, https://zeranoe.com/forum/viewtopic.php?t=5738, `hevc_qsv` **requires** `-load_plugin hevc_hw`.

**Comment by anthonylavado** [comment] 2019-09-29 04:58
Shoo bot

**Comment by g33kphr33k** [comment] 2019-10-15 18:29
Pretty sure I'm hitting this on Linux 10.4.0 with VAAPI for HEVC 10bit too.

It would be great to get this working as a lot of ~~downloadable content~~ my collection is starting to appear and I need to convert it before I can stream it in Jellyfin which defeats the object.

**Comment by JustAMan** [comment] 2019-10-16 10:34
Do HEVC 8-bit movies transcode okay?

**Comment by g33kphr33k** [comment] 2019-10-16 11:33
Weirdly, yes.
Let me do some more tests and get log files.

**Comment by g33kphr33k** [comment] 2019-10-16 11:55
Tested, 8 bit is fine, 10 bit falls over.  Transcode and jelly logs attached.
[8bitJelly.log](https://github.com/jellyfin/jellyfin/files/3734121/8bitJelly.log)
[8bit-transcode.txt](https://github.com/jellyfin/jellyfin/files/3734122/8bit-transcode.txt)
[10bitJelly.log](https://github.com/jellyfin/jellyfin/files/3734123/10bitJelly.log)
[10bit-transcode.txt](https://github.com/jellyfin/jellyfin/files/3734124/10bit-transcode.txt)

**Comment by JustAMan** [comment] 2019-10-16 13:10
This is related to https://github.com/jellyfin/jellyfin/issues/696

Otherwise it feels like a feature request to use software decoding + hardware encoding fallback if target hardware doesn't support the incoming codec. Please file one at https://features.jellyfin.org/

**Comment by g33kphr33k** [comment] 2019-10-17 05:53
I suppose it's both a feature request (fallback) as well as requested fix (HW enc should work if it's supported, regardless).

My hardware does support encode and decode of 10bit HEVC, Jellyfin just uses the wrong command string.

**Comment by anthonylavado** [comment] 2020-02-17 06:59
Do we think this applies?
https://twitter.com/KevinsinnerLee/status/1228915640016216065

**Comment by cvium** [comment] 2021-04-08 21:54
I don't think this should be an issue anymore. Otherwise make some noise.

**Closed by cvium** 2021-04-08 21:54 UTC
Labels: backend, bug, confirmed
