### ISSUE TITLE
File extension check for pictures is case-sensitive

### ISSUE THREAD

**Issue by Liggy** [jellyfin/jellyfin#1439] opened 2019-06-05 16:37 UTC
**Describe the bug**
In a library containing content type "Home videos & photos" or "Mixed Content", pictures are only recognized if the file extension is lower case.

**To Reproduce**
1. In a library with content type "Home videos & photos" or "Mixed Content", create image files named e.g. working.jpg and broken.JPG (png/PNG works as well)
2. Rescan library if realtime monitoring is not active
3. Check library content: Any picture with a lower case file extension is shown, file extensions containing upper case letter are missing

**Expected behavior**
Case insensitive scan, so files with upper case (maybe even mixed case) extension will be added to the library as well.

**Logs**
Added files are listed with "Getting image size for item Photo {Full path}", the other files don't even show up

**System (please complete the following information):**
 - OS: tried Docker and Windows
 - Browser: Firefox, Edge
 - Jellyfin Version: 10.3.3
 - Reverse proxy: Apache or direct makes no difference

**Additional context**
This only seems to affect pictures, while other content types seem unaffected. I tested .MP3, .MP4 and .ISO without problem.

**Comment by anthonylavado** [comment] 2019-06-05 19:05
Sorry for the trouble! This is a duplicate of #1365, which is fixed in #1367. Sadly, this is slated for 10.4 right now, but we don't have an estimated release date for that. I'll see what we can do about a backport.

**Comment by Liggy** [comment] 2019-06-05 19:15
Sorry, I didn't find the other bug when I searched for it. 😳
I guess this can be closed as duplicate of #1365 then and I don't mind waiting for 10.4

**Closed** 2019-06-06 06:45 UTC
Labels: bug
