### ISSUE TITLE
nightly install bug

### ISSUE THREAD

**Issue by AncientMystic** [jellyfin/jellyfin#2736] opened 2020-04-02 01:47 UTC
cannot install nightly over current version, the nightly is running as version 10.5.0 current is 10.5.2 and it counts the install as a downgrade and breaks the server because it still attempts to call 10.5.2 which then doesnt exist in the 10.5.0 files the reversion number for the nightly installer needs an update to make it compatible with installing as an upgrade over the current reversion so the server does not have to be rebuilt from scratch to try the nightly.

**Comment by AncientMystic** [comment] 2020-04-02 14:34
latest nightly for 4/02/2020 still has the bug of being a downgrade version that breaks the current version so is unusable for anyone up to date that does not want a total reset of everything

**Comment by Bond-009** [comment] 2020-04-02 14:58
Duplicate of #2652

**Closed by Bond-009** 2020-04-02 14:58 UTC

**Comment by AncientMystic** [comment] 2020-04-02 15:22
should actually fix this and not ignore it and close threads instead.

**Comment by dkanada** [comment] 2020-04-02 15:30
It's a duplicate. We're not ignoring it at all, we're tracking the issue in another thread.

**Comment by Artiume** [comment] 2020-04-02 15:43
https://github.com/jellyfin/jellyfin/pull/2743
