### ISSUE TITLE
Asks for login on first time install

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin#4419] opened 2020-11-05 04:32 UTC
**Describe the bug**
Jellyfin server is asking to login when it is a fresh install and should show the setup wizard,
I have made a fresh install in a vm in vultr, and created a local port forwarding in my machine to make sure jellyfin thinks I'm in the local network, But still it ask me to login instead of showing setup wizard!

**System (please complete the following information):**
 - OS: Debian 10 stable
 - Virtualization: -
 - Clients: Browser
 - Browser: Firefox 72
 - Jellyfin Version: 20201103.12-unstable
 - Playback: -
 - Installed Plugins: -
 - Reverse Proxy: -
 - Base URL: none
 - Networking: WAN, Remote server
 - Storage: local

**To Reproduce**

1. Fresh Install unstable build
2. Create local port forwarding (To mimic local network on a remote system) ` ssh user@remoteIP -L 8888:localhost:8096`
3. Goto `localhost:8888`
4. See login screen

**Expected behavior**
Setup wizard for first time

**Logs**

**Screenshots**

**Additional context**

## Using empty values didn't work either

![Screenshot_2020-11-05 Jellyfin](https://user-images.githubusercontent.com/16373480/98198125-7378ad80-1f52-11eb-8336-0f6f6ae57a2d.png)

** Update 
*** Wizard is displayed as intended in the stable release `10.6.4`

**Comment by nyanmisaka** [comment] 2020-11-05 05:13
Duplicate of https://github.com/jellyfin/jellyfin/issues/4372
To manually start the wizard navigate to {host}/web/index.html#!/wizardstart.html

**Closed by nyanmisaka** 2020-11-05 05:13 UTC
Labels: bug

**Comment by Anan5a** [comment] 2020-11-08 07:48
@nyanmisaka I get 401 error when the page is loaded, 
![Screenshot_20201108_134723](https://user-images.githubusercontent.com/16373480/98459867-19355200-21c9-11eb-9e35-15045147d26b.png)
Unable to move forward!

**Comment by AleixMT** [comment] 2022-06-22 20:23
This is also happening to me: fresh install of jellyfin with a docker container in a x64 Linux and the application is asking for credentials in a login form when accessing it in the browser. I tried what @nyanmisaka suggested but that does not do anything, it does not even change the loaded HTML, is the same login form. 

I also tried using the user "jellyfin" and clicking in "forgot my password". But it says that I should try again from my home network for the password reset. I do not know what it means. I followed the documentation and added the "--host=network" parameter but regarding that message it seems like there may be additional steps in the configuration that I'm missing.

Sorry to post this here because I'm not actually sure if it belongs here, but if someone knows what to do to access this wizard or to create a user manually I'd be grateful to hear from them. 

> Duplicate of #4372 To manually start the wizard navigate to {host}/web/index.html#!/wizardstart.html

**Comment by AleixMT** [comment] 2022-06-22 20:24
I'm using the jellyfin/jellyfin docker image

**Comment by bioblatt** [comment] 2023-08-27 21:23
same issue for me, not using docker on linux mint

**Comment by Anan5a** [comment] 2023-08-28 12:14
> same issue for me, not using docker on linux mint

you have to manually type the link for the first time
