### ISSUE TITLE
Ipad application opens in vertically 

### ISSUE THREAD

**Issue by Stormtrooper292** [jellyfin/jellyfin#4140] opened 2020-09-13 14:54 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: IOS
 - Browser: IOS
 - Jellyfin Version: 10.6.4
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local HDD

**To Reproduce**

1. Open 'The Ipad application'
2. Error 'The application opens vertically'

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment] 2020-09-13 15:12
Duplicate of https://github.com/jellyfin/jellyfin-expo/issues/74

**Closed by crobibero** 2020-09-13 15:12 UTC
Labels: bug
