### ISSUE TITLE
Infusesync seems to break rc-2 docker build.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin#4955] opened 2021-01-05 02:21 UTC
**Describe the bug**

Upgrading to rc 2 manged to break jellyfin, only allowing it to start for a second, giving a "Main: Received a SIGTERM signal, shutting down", after testing a new config folder, it all works, up until I install infusesync, removing it fixes the contaner.
**To Reproduce**

1. Upgrade to rc-2
2. install infusesync
3. Watch as it no longer is able to open.

**Logs**

[02:17:43] [INF] [2] Main: Received a SIGTERM signal, shutting down

System: Synology ds720+ 
OS; Docker.

**Comment by crobibero** [comment] 2021-01-05 02:24
Duplicate of https://github.com/jellyfin/jellyfin/issues/4690

**Closed by crobibero** 2021-01-05 02:24 UTC
Labels: bug

**Comment by Darkwolf1515** [comment] 2021-01-05 02:36
Before I open a new issue, is the user page endlessly loading a known bug?

**Comment by nielsvanvelzen** [comment] 2021-01-05 08:16
Probably related to this change in our documentation:
https://github.com/jellyfin/jellyfin-docs/pull/473
