### ISSUE TITLE
Cast and syncplay doesnt work

### ISSUE THREAD

**Issue by rernars** [jellyfin/jellyfin#5525] opened 2021-03-14 07:12 UTC
Bug description;
After updating from 10.6.4 to 10.7 there is no other device shown in cast except the device itself and cant sync and watch, it just creates a new sync group each tme 

**System**
 - OS: Raspbian/Yunohost
 - Clients: Android , Browser
 - Browser: Opera 73, Chrome 89
 - Jellyfin Version: 10.7 
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: /jellyfin
 - Storage: local

**To Reproduce**
1. Go to Main Page 
2. Click on Cast/syncplay
3. There is no device in castplay
4. Create a group in syncplay
5. Noone can join but only can create another

**Expected behavior**
I should be able to sync play with other devices / cast to my other devices

This one is from Chrome
![image](https://user-images.githubusercontent.com/59098807/111060337-321e7e80-84ad-11eb-881d-82aba16bec8b.png)
This one is from Opera
![image](https://user-images.githubusercontent.com/59098807/111060349-537f6a80-84ad-11eb-8a91-092f87534a15.png)
 

Here you can see each time there is a new group created and cannot join.
![image](https://user-images.githubusercontent.com/59098807/111060364-727dfc80-84ad-11eb-9145-0551981d2324.png)

**Comment by ikomhoog** [comment] 2021-03-29 09:14
I just got myself a chromecast, in 10.7.1 the above happens when using the app, but when using the browser it will allow syncplay to be selected and to cast at the same time.
I still don't think syncplay actually works though, when doing this I cannot control the chromecast at all.
I cannot pause or skip, but as soon as I leave the syncplay group it becomes responsive again.

**Comment by erennnars** [comment] 2021-07-03 10:57
Still have the same bugs in 10.7.6

**Comment by eyJhb** [comment] 2021-08-14 15:37
Are you using HTTP/HTTPS for your web interface?

**Comment by erennnars** [comment] 2021-11-18 07:10
HTTPS

**Comment by srcrist** [comment] 2023-10-19 21:50
Closing this issue and I am unable to reproduce in 10.8.11 and it has gone several years without update. Please submit a new issue for any issues still present in the latest release.

**Closed by srcrist** 2023-10-19 21:50 UTC
Labels: bug

**Comment by douglasparker** [comment] 2023-10-20 03:12
> Closing this issue as I am unable to reproduce in 10.8.11 and it has gone several years without update. Please submit a new issue for any issues still present in the latest release. 

It's well known that SyncPlay is a buggy mess and doesn't work for a lot of people. Just search SyncPlay on GitHub and on the Jellyfin Discord.

How many SyncPlay issues do you recommend be opened? A new one once a year or?

**Comment by srcrist** [comment] 2023-10-20 03:50
You are welcome to submit an issue as soon as you have a reliably reproducible bug that isn't a duplicate. Or simply submit PRs for the improvements you'd like to see. That's also fine. But nobody has really taken much of an interest in the SyncPlay code, and the person who developed it abandoned it without a lot of documentation. Which is why you're not seeing it improve. 

I'm unable to reproduce the bug in this issue, in any case.
