### ISSUE TITLE
Jellyfin logs are available as unauthorized user

### ISSUE THREAD

**Issue by xumix** [jellyfin/jellyfin#3492] opened 2020-05-25 09:36 UTC
**To Reproduce**
1. Login as admin
2. Navigate to http://host/web/index.html#!/log.html
3. Open any file there like:
http://host/System/Logs/Log?name=log_20200525.log&api_key=xxxxxxxxxxxx
4. Copy url and paste to other unauthorized browser
5. The file is open

**Expected behavior**
The file should not be available to unauthorized users
`api_key` should be in headers, not url

**System (please complete the following information):**
 - OS: Docker, inuxserver/jellyfin:latest
 - Browser: Firefox latest
 - Jellyfin Version: 10.5.5, linux x64

**Comment by DMouse10462** [comment] 2020-07-04 19:24
The title here is partially misleading; the request is authorized by the `api_key` parameter in the URL, which allows for any user agent to request the file so long as it has that bearer token. The issue is not that the requests are unauthorized, but that the token used for authorization is in the URL.

If the URL parameter for the token is removed server-side for all endpoints, that's an API-breaking change and we'd have to make sure clients are using the `X-Emby-Authorization` for all requests (something that might not always be possible in specific environments, such as the "Copy Stream URL" feature in jellyfin-web, breaking clients).

If the worry is that you don't want your token exposed in your log URLs then this is actually a jellyfin-web issue as a log viewer would need to be implemented in the client in order to pass the authorization token as a header rather than a URL parameter. Something like a viewer with a download button or an option to copy the URL with the token in-place could be an option rather than the default to keep the user's API key out of the browser history (something that *does* get synced by browsers to cloud servers for users that take advantage of it).

**Comment by DMouse10462** [comment] 2020-11-04 22:00
Can we tag this as security here or determine if this needs transferred back to web? It's definitely a valid concern to have your auth token exposed in the URL.

**Comment by joshuaboniface** [comment] 2020-11-04 22:17
Many aspects of the API require the authentication token in the URL. This is one of the main reasons we've always stressed the importance of using SSL with Jellyfin, since that will protect the URL string from snooping.

Proper API authentication is part of the planned API rewrites, but as-is we've found no good solution for fixing it as-is. It's a baked in poor design.

**Comment by DMouse10462** [comment] 2021-03-21 01:58
Looks like this was recently mentioned in mega-issue #5415 as a valid security-related issue; do we want to put a confirmed/security tag on this so it doesn't get consumed by the stale bot? I'm glad this got some recent attention in the mega-issue; it's probably best that we keep this open so that it can be addressed as a free-standing issue.

**Comment by cvium** [comment] 2021-04-10 15:27
Use SSL. This is already tracked in the big issue. I see no point in keeping this open. Eventually we'll move to jwt...

**Closed by cvium** 2021-04-10 15:27 UTC
Labels: confirmed

**Comment by DMouse10462** [comment] 2021-04-13 22:12
This has other implications; browsers syncing web history to the cloud would sync that API key in the URL. Chrome appears to sync history by default (but I don't have it so I can't confirm easily) and Edge provides it as an option. 

If someone clicks a log link, that API key will be in their history. Especially given that the token doesn't expire or get replaced/refreshed, that's not a great idea. 

The JWT solution is fine, but for now this is still a bug that has a real security implication, small as it may be.

**Comment by alison2033** [comment] 2022-03-29 02:38
Hello vim reports the same problem Here it appears **MessageUnauthorizedUser** has a way to solve this I create the account with 1 access when I leave the android App and I log in to the browser or another androi App or etc. This appears **MessageUnauthorizedUser,** but when I go back to the same I was entering it is not but with username and password it says the same **MessageUnauthorizedUser** the account just goes back to normal just close the process server and open it again when the logs back normally
