### ISSUE TITLE
Movie metadata failing due to DateTime string conversion failing

### ISSUE THREAD

**Issue by PoopyKoopy** [jellyfin/jellyfin#13181] opened 2024-12-08 02:31 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Movie metadata is suddenly failing to be grabbed, I made no changes to my setup so I am not sure why this is happening. Reading the logs, there is a failure when converting string to DateTime? This doesn't seem to be affecting all movies so I am not sure how to even begin troubleshooting. All movies are named in accordance with Trash-Guides.

Not sure if it is related, but I also can't identify these movies using their TMDB IDs, yet searching the name works fine? Confirmed that the ID is correct on TMDB.

### Reproduction steps

1. Name a movie using the recommended naming scheme in Trash-Guides
2. Import movie in Jellyfin and try to search for metadata through TMDB

Can be confirmed to fail with Goldfinger (1964) and Jackass Forever (2022), among many others

### What is the current _bug_ behavior?

Metadata is not being downloaded and cannot manually search for it.

### What is the expected _correct_ behavior?

Metadata to be downloaded and loaded for viewing in server

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS:TrueNas Scale 24.10.0.2-Electric Eel
- Linux Kernel:6.6.44
- Virtualization:Docker
- Clients:Browser,Android,TizenOS
- Browser:Firefox 132.0.1
- FFmpeg Version:7.0.2-jellyfin
- Playback Method:
- Hardware Acceleration:QSV
- GPU Model:Arc A310
- Plugins:default
- Reverse Proxy:Traefik
- Base URL:
- Networking:Bridge
- Storage:local
```

### Jellyfin logs

```shell
Logs uploaded below
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/d03eeab7-0c55-45df-8173-7142256367c2)
[jellyfin_logs.txt](https://github.com/user-attachments/files/18050522/jellyfin_logs.txt)

### Additional information

I made no changes to my server so I have no clue how this happened. Server had been up for nearly 2 days when it began to fail and I had not altered any file names, permissions etc.

Tested a brand new server container and having the same issue. Not sure what string it is failing to convert to DateTime, but it has never been an issue before.

**Comment by gnattu** [comment] 2024-12-08 03:00
Duplicate of https://github.com/jellyfin/TMDbLib/issues/522

**Closed by gnattu** 2024-12-08 03:00 UTC
Labels: bug
