### ISSUE TITLE
can't download opensubtitles

### ISSUE THREAD

**Issue by africa1207** [jellyfin/jellyfin#5162] opened 2021-02-04 08:53 UTC
**Describe the bug**
can't download opensubtitles

**System (please complete the following information):**
 - OS: Synology Nas
 - Virtualization: Docker
 - Clients: Browser
 - Browser:Chrome 84
 - Jellyfin Version:10.6.4
 - Installed Plugins: Open Subtitles
 - Networking: Host

**Logs**
`
[2021-02-04 16:28:14.729 +00:00] [ERR] [67] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
 at System.Xml.XmlTextReaderImpl.Throw(Exception e)
 at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
 at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
 at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
 at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
 at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken 
     cancellationToken)
 at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
 at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken 
     cancellationToken) at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
`

**Comment by BobDaGecko** [comment] 2021-02-07 10:01
What version of Open Subtitles are you installing? I see you are still on 10.6.4 so you need to install one version previous not the latest version.

**Comment by africa1207** [comment] 2021-02-09 01:36
> What version of Open Subtitles are you installing? I see you are still on 10.6.4 so you need to install one version previous not the latest version.

the version of Open Subtitles is 9.0.0.0. i had tried Jellyfin 10.7.0 rc3 and the open subtitles is 10.0.0.0,None of them automatically download subtitles

**Comment by ikomhoog** [comment] 2021-02-10 12:17
Can you manually download subtitles?
I just tried it on the latest RC and plugin versions and it says "No results found" for "predators (2010)" which does have subtitles available on opensubtitles.

I also get this error in the logs:
`[13:10:58] [ERR] [46] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from Open Subtitles

System.Xml.XmlException: The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
at System.Xml.XmlTextReaderImpl.ParseEndElement()
at System.Xml.XmlTextReaderImpl.ParseElementContent()
at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()`

the error is different but it might be related?

**Comment by ikomhoog** [comment] 2021-02-16 10:05
Apparently i made my username on opensubtitles start with a capital letter and didn't fill that in on jellyfin.
My error just came from a wrong login, can you double check your login to see if that is also the case?

**Comment by cvium** [comment] 2021-02-17 13:12
Duplicate of https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/25

**Closed by cvium** 2021-02-17 13:12 UTC
Labels: bug
