### ISSUE TITLE
web client not fully accessible remotely while using reverse proxy. [item or serverId is null]

### ISSUE THREAD

**Issue by mariosdev** [jellyfin/jellyfin#5575] opened 2021-03-19 22:59 UTC
**Describe the bug**
Jellyfin web client is no longer fully accessible via reverse proxy since 10.7.0 update. Upon visiting my custom domain name that points to my reverse proxy setup, instead of a prompting me for a username and password, i get sent to ./web/index.html#!/selectserver.html url, prompting me to add a new server while not able to identify my already running server. If i try to manually enter a new server ip, i get an error message stating connection failure. Screenshots and dev logs provided below indicate some sort of network bug in the application (imho).
Also wanted to clarify that i am able to access the web interface with no issues when connecting via localhost from the server machine or another pc in the network via server_ip:port.

**System:**
 - OS: Windows 10
 - Virtualization: No
 - Clients: Browser
 - Browser: Firefox, Edge, Chrome
 - Jellyfin Version: 10.7.0
 - Playback: Direct, Transcode
 - Installed Plugins: none
 - Reverse Proxy: Caddy, Nginx Proxy Manager (NPM) + Cloudflare
 - Base URL: none
 - Networking: Remote access disabled, reverse proxy enabled.
 - Storage: Local

**To Reproduce**
1. Default network configuration, only with a different http port.
2. Added IP of my raspberry pi which acts as the reverse proxy, to known proxies list in advanced/networking tab.
3. Reverse proxy is setup to forward traffic to another machine (different ip) in the local network.
4. See error, please see screenshots to observe behavior.

**Expected behavior**
I should be able to access the web interface remotely using a reverse proxy while using my custom (real/owned) domain name + cloudflare as a dns. I am able to expose other services using the same reverse proxy setup with no issues which is why i am 100% certain my network/reverse proxy settings are correct.

**Logs** 
While trying to access the web interface remotely via proxy, the following errors and warnings appear in dev console (my domain is replaced with redactedurl.com):

```
Stored JSON credentials: {"Servers":[{"DateLastAccessed":REDACTED,"LastConnectionMode":2,"ManualAddress":"https://redactedurl.com","manualAddressOnly":true}]}
main.3309837d9db1402ea3a1.bundle.js:2 Begin ConnectionManager constructor
main.3309837d9db1402ea3a1.bundle.js:2 defining core routes
main.3309837d9db1402ea3a1.bundle.js:2 Could not get current apiClient Error: item or serverId cannot be null
    at m.value (main.3309837d9db1402ea3a1.bundle.js:2)
    at m.value (main.3309837d9db1402ea3a1.bundle.js:2)
    at Module.63869 (main.3309837d9db1402ea3a1.bundle.js:2)
    at i (main.3309837d9db1402ea3a1.bundle.js:2)
    at main.3309837d9db1402ea3a1.bundle.js:2
    at main.3309837d9db1402ea3a1.bundle.js:2
    at main.3309837d9db1402ea3a1.bundle.js:2
63869 @ main.3309837d9db1402ea3a1.bundle.js:2
i @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
main.3309837d9db1402ea3a1.bundle.js:2 Begin getAvailableServers
VM80:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at main.3309837d9db1402ea3a1.bundle.js:2
    at Array.map (<anonymous>)
    at main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
u @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
d @ main.3309837d9db1402ea3a1.bundle.js:2
a @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
d @ main.3309837d9db1402ea3a1.bundle.js:2
a @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
d @ main.3309837d9db1402ea3a1.bundle.js:2
a @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
p @ main.3309837d9db1402ea3a1.bundle.js:2
h @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
main.3309837d9db1402ea3a1.bundle.js:2 loading installed plugins
main.3309837d9db1402ea3a1.bundle.js:2 loading packages
main.3309837d9db1402ea3a1.bundle.js:2 error registering serviceWorker: SecurityError: Failed to register a ServiceWorker for scope ('https://redactedurl.com/') with script ('https://redactedurl.com/serviceworker.js'): The script does not have a MIME type.
main.3309837d9db1402ea3a1.bundle.js:2 getTryConnectPromise https://redactedurl.com
main.3309837d9db1402ea3a1.bundle.js:2 ConnectionManager requesting url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 fetchWithTimeout: timeoutMs: 20000, url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 fetchWithTimeout: succeeded connecting to url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 ConnectionManager response status: 200, url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 Reconnect failed to https://redactedurl.com
main.3309837d9db1402ea3a1.bundle.js:2 resolving connectToServers with result.State: ServerSelection
main.3309837d9db1402ea3a1.bundle.js:2 Begin connect
main.3309837d9db1402ea3a1.bundle.js:2 Begin getAvailableServers
main.3309837d9db1402ea3a1.bundle.js:2 Begin connectToServers, with 1 servers
main.3309837d9db1402ea3a1.bundle.js:2 begin connectToServer
main.3309837d9db1402ea3a1.bundle.js:2 tryReconnect: https://redactedurl.com
main.3309837d9db1402ea3a1.bundle.js:2 getTryConnectPromise https://redactedurl.com
main.3309837d9db1402ea3a1.bundle.js:2 ConnectionManager requesting url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 fetchWithTimeout: timeoutMs: 20000, url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 fetchWithTimeout: succeeded connecting to url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 ConnectionManager response status: 200, url: https://redactedurl.com/system/info/public
main.3309837d9db1402ea3a1.bundle.js:2 Reconnect failed to https://redactedurl.com
main.3309837d9db1402ea3a1.bundle.js:2 resolving connectToServers with result.State: ServerSelection
main.3309837d9db1402ea3a1.bundle.js:2 Begin getAvailableServers
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11433196/111845970-95c20500-890e-11eb-95ae-48894ecf7e6b.png)
![image](https://user-images.githubusercontent.com/11433196/111846141-e3d70880-890e-11eb-8ee9-3dcd8e3b9894.png)

**Comment by carlocastoldi** [comment] 2021-03-19 23:14
I experience the same exact bug

**Comment by Pwnulatr** [comment] 2021-03-20 06:30
I am experiencing the same issue with the Docker Image from jellyfin/jellyfin and using NGINX as a reverse proxy.

**Comment by mariosdev** [comment] 2021-03-20 11:14
After some suggestions and trying out settings it seems that if allowing remote connections to server is checked, there are no more errors and the web interface prompts for login and works fine thereafter. 
![image](https://user-images.githubusercontent.com/11433196/111867462-c04aa700-897c-11eb-8d5f-3a2d9ddd4139.png)

@carlocastoldi and @Pwnulatr do you have this setting enabled? Could you please confirm if enabling fixes this issue? If so maybe we can close this issue.

I might be mistaken but this behavior was different on the previous version 10.6.4 . I am fairly sure that i didn't have the setting enabled. Is it possible that things have changed in 10.7.0? 
Shouldn't the reverse proxy work even if jellyfin blocks all remote connections? For the jellyfin server it should be the same as localhost right?

**Comment by Pwnulatr** [comment] 2021-03-20 11:25
Enabling this setting seems to have fixed the problem, at least testing with the mobile app over VPN, remotely. 

To my knowledge, which is not super high in networking, I had thought you were correct in that the server shouldn't need remote connections because the reverse proxy handles incoming connection attempts and proxies them to the jellyfin server. That's as far as I understand, but I'm only slightly above a laymen in this area IMHO.

**Comment by mariosdev** [comment] 2021-03-20 11:34
Thanks for confirming @Pwnulatr , i think at least that the Remote Access Setting should be phrased more clearly so if unchecked, all remote connections, including remote proxies will be blocked. 

If i am wrong please correct me because this is fairly interesting. I think that a reverse proxy should not be blocked in this scenario but it seems like its still detected and blocked.

It would be great if someone can confirm if this is expected behavior or an actual bug.

**Comment by carlocastoldi** [comment] 2021-03-20 12:56
I had it checked from 10.6.4. Unchecking it and checking it back made it work.
Dunno why I didn't even think about it. I feel stupid

**Comment by carlocastoldi** [comment] 2021-03-20 13:08
Oh i get it: somehow if I use a whitelist and put my remote device IP, I get the error seen in this issue.

Counterintuitively if I **don't** put my remote device IP in the whitelist, I can connect with no problems at all

**Comment by carlocastoldi** [comment] 2021-03-20 13:11
I hope #5495 fixes this problem aswell and get merged soon

**Comment by mariosdev** [comment] 2021-03-20 17:32
@carlocastoldi i don't use the whitelist, i always leave it blank. Are you talking about using a reverse proxy or just whitelist on a lan?

I will try to add an ip to the whitelist and see if i get the same error while also having remote access enabled.

**Comment by PwnPeter** [comment] 2021-03-22 00:37
Hi, I have a similar problem.

`User -> mydomain.com -> Cloudflare (to hide the public ip of my box) -> My server (debian, at home) -> Caddy in reverse proxy (docker) with ports 80 and 443 open -> Jellyfin (Docker image of linuxserver)`

With version 1.6.x no problem, by going to mydomain.com I have access to the authentication interface.

With version 1.7.x, cloudflare returns a 502 "Bad Gateway" error.

I tried to check "Allow Remote connection" with "White list" filtering leaving the "Remote IP address filter" box empty to accept all of them, but I still have the same problem, any ideas?

**Comment by BaronGreenback** [comment] 2021-03-23 19:46
> Hi, I have a similar problem.
> 
> `User -> mydomain.com -> Cloudflare (to hide the public ip of my box) -> My server (debian, at home) -> Caddy in reverse proxy (docker) with ports 80 and 443 open -> Jellyfin (Docker image of linuxserver)`
> 
> With version 1.6.x no problem, by going to mydomain.com I have access to the authentication interface.
> 
> With version 1.7.x, cloudflare returns a 502 "Bad Gateway" error.
> 
> I tried to check "Allow Remote connection" with "White list" filtering leaving the "Remote IP address filter" box empty to accept all of them, but I still have the same problem, any ideas?

could you upload your log file please?

**Comment by mholt** [comment] 2021-03-25 03:36
I am experiencing the exact same issue. Remote connections are disallowed because the only connection is made thru the local reverse proxy. And it has always worked before. Now I am hundreds of miles away and unable to access.

Any solutions?

**Comment by BaronGreenback** [comment] 2021-03-25 10:35
@mholt Depending on the version you're running, there is a bug that inverts the blacklist / whitelist. I'd try that first.

Next is that 10.7 runs on .net 5, which implements known proxies. I'm not quite sure if it needs to be defined, but it might be worth ensuring that your upstream servers are not in the known proxies list.

**Comment by mark-monteiro** [comment] 2021-04-30 03:54
I also ran into this issue upgrading to the latest version and was able to work around it by checking 'allow remote connections to this server'. I have no blacklist, whitelist or known proxies entries.

I think there might be some more investigation required to figure out why these requests from the reverse proxy aren't being correctly identified as coming from the LAN (since it's the same machine). Or perhaps this is the new intended behavior since the update? @BaronGreenback If you can think of anything I can do to help test let me know.

Server log is attached: [jellyfin-logs.txt](https://github.com/jellyfin/jellyfin/files/6402887/jellyfin-logs.txt)

**Comment by crobibero** [comment] 2021-04-30 04:09
> I also ran into this issue upgrading to the latest version and was able to work around it by checking 'allow remote connections to this server'. I have no blacklist, whitelist or known proxies entries.
> 
> I think there might be some more investigation required to figure out why these requests from the reverse proxy aren't being correctly identified as coming from the LAN (since it's the same machine). Or perhaps this is the new intended behavior since the update? @BaronGreenback If you can think of anything I can do to help test let me know.
> 
> Server log is attached: [jellyfin-logs.txt](https://github.com/jellyfin/jellyfin/files/6402887/jellyfin-logs.txt)

In the logs it’s replying to “192.0.165.167”, which isn’t in the Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]

Setting the LAN networks to your actual local network range will fix the issue for you.

**Comment by mark-monteiro** [comment] 2021-05-01 18:17
Ahh okay that makes sense. In previous versions, traffic from the reverse proxy was all identified as from the local machine so it made sense to filter out any remote connections. It looks like the LAN filter now gets the actual client IP address.

Perhaps that change should make it into the release notes? It is a breaking change for anyone who had remote connections disabled with a reverse proxy. Adding a warning to the release notes is probably be a good enough solution to close this issue IMO.

**Comment by mholt** [comment] 2021-05-01 18:39
Yeah, honestly I was kind of surprised by this change. IMO it's not a "remote connection" if it comes from a local reverse proxy, which deals with "remote connections" for you.

**Comment by BaronGreenback** [comment] 2021-05-01 18:46
The issue is with the address :- 192.0.165.167 is not in the RFC private address range. 

If it was 192.**168**.165.167 it should be ok.

**Comment by mark-monteiro** [comment] 2021-05-08 17:07
I think the "issue" here is that there was a bugfix that started correctly reporting remote IP addresses to the IP filter instead of always returning the IP address of the reverse proxy. Seems like this is working as intended now so maybe this issue can just be closed as 'works as intented'?

**Comment by gabrielwhite** [comment] 2021-06-28 02:18
I just encountered this issue for the first time with 10.7.6 and rolling back to 10.7.5 eliminated it. I tried the network settings fixes mentioned above with 10.7.6 and they didn't have any effect. I'm using the linuxserver Docker image with NGINX and cloudflared.

**Comment by MagentaPuppy** [comment] 2022-03-18 01:13
I'm having this issue on jellyfin 10.7.7, nothing recommended here solves it

**Comment by sanyarnd** [comment] 2022-07-09 22:34
Another "workaround":
1. Open Jellyfin URL (redirects to `selectserver`)
2. Delete server
3. Open Jellyfin URL again
4. Now you have a user/password promt

**Comment by dbrennand** [comment] 2023-01-01 13:06
> After some suggestions and trying out settings it seems that if allowing remote connections to server is checked, there are no more errors and the web interface prompts for login and works fine thereafter. ![image](https://user-images.githubusercontent.com/11433196/111867462-c04aa700-897c-11eb-8d5f-3a2d9ddd4139.png)
> 
> @carlocastoldi and @Pwnulatr do you have this setting enabled? Could you please confirm if enabling fixes this issue? If so maybe we can close this issue.
> 
> I might be mistaken but this behavior was different on the previous version 10.6.4 . I am fairly sure that i didn't have the setting enabled. Is it possible that things have changed in 10.7.0? Shouldn't the reverse proxy work even if jellyfin blocks all remote connections? For the jellyfin server it should be the same as localhost right?

Hi @mariosdev 

Checking "Allow remote connections to this server" fixed the issue for me. My setup is using Caddy to reverse proxy to Jellyfin via Tailscale. With this setting checked, I no longer have the `undefined` server issue. Thanks! 🙂

**Comment by ipetkov** [comment] 2023-02-05 06:00
Just came across this and I can also confirm that checking "allow remote connections to this server" allows me to connect over tailscale!

I also allowlisted 100.64.0.0/10 which is [the IP range tailscale uses to assign addresses](https://tailscale.com/kb/1015/100.x-addresses/) for good measure and seems to be working smoothly afterwards!

**Comment by aednichols** [comment] 2023-04-06 22:13
This is a bug now but I appreciate the behavior and would love for it to be official. It preserves the utility of the "allow remote" checkbox when using the very common reverse proxy setup.

**Comment by HernandoR** [comment] 2023-06-11 13:43
> Another "workaround":
> 
> 1. Open Jellyfin URL (redirects to `selectserver`)
> 2. Delete server
> 3. Open Jellyfin URL again
> 4. Now you have a user/password promt

I don't know why, but this usable for me.

**Comment by segalll** [comment] 2023-08-15 20:47
I had this issue and solved it by enabling IPv6 connections in Jellyfin. Turns out my Caddy reverse proxy was using IPv6. This works without remote connections enabled.

**Comment by srcrist** [comment] 2023-10-08 02:35
Closing this issue as there is no indication of an authentic Jellyfin bug. If anyone has continued issues with connectivity, via proxy or otherwise, please visit our support communities on the forum or our Matrix/Discord server and people will be glad to assist you with troubleshooting remote access.

**Closed by srcrist** 2023-10-08 02:35 UTC
Labels: bug
