### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2608] opened 2020-03-15 22:21 UTC
```
Sending build context to Docker daemon  25.24MB
Step 1/23 : ARG DOTNET_VERSION=3.1
Step 2/23 : ARG FFMPEG_VERSION=latest
Step 3/23 : FROM node:alpine as web-builder
 ---> 532fd65ecacd
Step 4/23 : ARG JELLYFIN_WEB_VERSION=master
 ---> Using cache
 ---> 57e08dea676b
Step 5/23 : RUN apk add curl git  && curl -L https://github.com/jellyfin/jellyfin-web/archive/${JELLYFIN_WEB_VERSION}.tar.gz | tar zxf -  && cd jellyfin-web-*  && yarn install  && yarn build  && mv dist /dist
 ---> Running in 340c41989568
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20191127-r1)
(2/7) Installing nghttp2-libs (1.40.0-r0)
(3/7) Installing libcurl (7.67.0-r0)
(4/7) Installing curl (7.67.0-r0)
(5/7) Installing expat (2.2.9-r1)
(6/7) Installing pcre2 (10.34-r1)
(7/7) Installing git (2.24.1-r0)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 24 MiB in 23 packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    786      0 --:--:-- --:--:-- --:--:--   786
100 3591k    0 3591k    0     0  4506k      0 --:--:-- --:--:-- --:--:-- 4506k
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/jellyfin-web-master/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /jellyfin-web-master/node_modules/gifsicle
Output:
⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found


    at /jellyfin-web-master/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)"
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/jellyfin-web-master/node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /jellyfin-web-master/node_modules/optipng-bin
Output:
⚠ spawn /jellyfin-web-master/node_modules/optipng-bin/vendor/optipng ENOENT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --with-system-zlib --prefix=\"/jellyfin-web-master/node_modules/optipng-bin/vendor\" --bindir=\"/jellyfin-web-master/node_modules/optipng-bin/vendor\"

Checking for gcc...
Using pre-configured libpng...
Checking for system zlib...
./configure: error: missing zlib or incorrect zlib version
./configure: note: zlib version 1.2.1 or higher is required

    at /jellyfin-web-master/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)"
success Saved lockfile.
Done in 25.48s.
yarn run v1.21.1
$ gulp --production
[22:17:22] Using gulpfile /jellyfin-web-master/gulpfile.js
[22:17:22] Starting 'default'...
[22:17:22] Starting 'clean'...
[22:17:22] Finished 'clean' after 37 ms
[22:17:22] Starting 'javascript'...
[22:17:22] Starting 'webpack'...
[22:17:22] Starting 'css'...
[22:17:22] Starting 'html'...
[22:17:22] Starting 'images'...
[22:17:22] Starting 'copy'...
[22:17:23] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:23] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:23] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:23] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:24] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:24] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:24] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:24] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:24] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:24] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:24] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:24] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:24] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:24] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:25] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:25] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:25] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:25] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:25] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:25] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:26] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:26] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:27] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:27] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:28] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:28] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:28] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:28] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:28] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:28] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:29] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:29] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:29] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:29] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:29] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:29] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:29] gulp-imagemin: Couldn't load default plugin "gifsicle"
[22:17:29] gulp-imagemin: Couldn't load default plugin "optipng"
[22:17:29] 'images' errored after 6.84 s
[22:17:29] Error in plugin "gulp-imagemin"
Message:
    spawn /jellyfin-web-master/node_modules/mozjpeg/vendor/cjpeg ENOENT
Details:
    errno: -2
    code: ENOENT
    syscall: spawn /jellyfin-web-master/node_modules/mozjpeg/vendor/cjpeg
    path: /jellyfin-web-master/node_modules/mozjpeg/vendor/cjpeg
    spawnargs:
    stdout:
    stderr:
    failed: true
    signal: null
    cmd: /jellyfin-web-master/node_modules/mozjpeg/vendor/cjpeg
    timedOut: false
    killed: false
    fileName: /jellyfin-web-master/src/themes/blueradiance/bg.jpg
    domainEmitter: [object Object]
    domainThrown: false

[22:17:29] 'default' errored after 6.89 s
[22:17:29] The following tasks did not complete: javascript, webpack, css, html, copy
[22:17:29] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c apk add curl git  && curl -L https://github.com/jellyfin/jellyfin-web/archive/${JELLYFIN_WEB_VERSION}.tar.gz | tar zxf -  && cd jellyfin-web-*  && yarn install  && yarn build  && mv dist /dist' returned a non-zero code: 1
```

**Comment by Artiume** [comment] 2020-03-15 22:52
The fix https://github.com/jellyfin/jellyfin/pull/2606 

Duplicate of https://github.com/jellyfin/jellyfin-web/issues/945

**Closed** 2020-03-21 11:17 UTC
Labels: bug
