### ISSUE TITLE
Fail to Identify media, even search with correct IMDb Id

### ISSUE THREAD

**Issue by davidngrc** [jellyfin/jellyfin#6726] opened 2021-10-22 14:53 UTC
I am on the latest Jellyfin v10.7.7
Install on debian.

here is how to test.
1. in your anime media folder, create a folder name:  The Legend of Zelda (1989)
2. inside that folder, create a empty file name:  The Legend of Zelda - Ep. 01 - The Ringer (480p - DVDRip).mp4
3. go back to Jellyfin -> login as Admin -> Dashboard -> Librarys -> search the anime media folder.
4. go back to front end web UI, you will see a new anime has been added, but it is not  The Legend of Zelda (1989) , it is the "Hell Teacher Nube: Summer Holiday (1997)".
5. click into the "Hell Teacher Nube: Summer Holiday (1997)", on the top right -> 3 dot -> Identify -> in the "IMDb Id:" field, type   tt0832330   , and click search, it successfully found the "The Legend of Zelda (1989)" -> tick "Replace existing images" -> click ok.
6. after few minutes, it return, but seems all field are still showing the old "Hell Teacher Nube: Summer Holiday (1997)" infomation, only the background and top banner image is updated.

**Comment by 1337joe** [comment] 2022-02-16 14:27
#7078 should have fixed lingering metadata and images from mis-identification.

I'm not seeing the described behavior, but without the list of active plugins/metadata providers I can't be sure I'm testing against what was broken. Please do test it again on 10.8

**Comment by ldexterldesign** [comment] 2022-04-22 16:35
> Please do test it again on 10.8

I did, same issue

Let me know if I can be of help (e.g. logs)..?

Regards

**Comment by felix920506** [comment] 2023-10-15 21:30
I have just tested this on master. I could not reproduce this issue using the IMDb ID you provided in the report.

**Comment by srcrist** [comment] 2023-10-19 17:51
Closing this issue as presently fixed per comments. Most metadata matching issues are a matter of provider configuration. If anyone is still experiencing matching issues, please visit our support communities on the forums or the Matrix/Discord server for assistance.

**Closed by srcrist** 2023-10-19 17:51 UTC
Labels: bug
