### ISSUE TITLE
Unhandled exception when refreshing library

### ISSUE THREAD

**Issue by xeluior** [jellyfin/jellyfin#12566] opened 2024-09-01 22:21 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When attempting to refresh one of my media libraries, due to a set of missing movies, the refresh appears to not begin at all in the WebUI (no progress indicator, despite the "Request Queued" notification). I suspected this was due to one folder named with a special character, namely `Alien³ (1992)`. As expected, once renamed to `Alien 3 (1992)` the refresh completed as expected. I verified this behavior on 10.9.10, 10.9.9, and 10.9.8. The stack trace from the logs when attempting to refresh the library with the original folder name is included below.

### Reproduction steps

1. Create a media library that includes a folder with Unicode character U+00B3 (³)
2. Attempt to refresh the media library
3. Observe the logs for the stack trace

### What is the current _bug_ behavior?

The media library is not refreshed. No media added to the library after the creation date of the folder is indexed.

### What is the expected _correct_ behavior?

Folders with legal names per the filesystem should be refreshed and indexed correctly by the server. Else there should be documentation to the effect of which characters are not legal in folder names to be parsed by Jellyfin.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.10

### Environment

```markdown
- OS: OpenSUSE Tumbleweed (Docker Host)
- Linux Kernel: 6.10.5 (Docker Host)
- Virtualization: Docker
- Clients: WebUI
- Browser: Firefox 129
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: ?
- Hardware Acceleration: Nvidia NVENC
- GPU Model: GeForce RTX 3060 Ti
- Plugins: AudioDB 10.9.10.0, Bookshelf 11.0.0.0, MusicBrainz 10.9.10.0, OMDb 10.9.10.0, Studio Images 10.9.10.0, TMDb 10.9.10.0, TheTVDB 15.0.0.0
- Reverse Proxy: Traefik
- Base URL: none
- Networking: Docker bridge
- Storage: SMB
```

### Jellyfin logs

```shell
[21:54:48] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
System.TypeInitializationException: The type initializer for 'ICU4N.Text.Transliterator' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ICU4N.Globalization.UCultureInfo' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at ICU4N.Globalization.UCultureInfo..cctor()
   --- End of inner exception stack trace ---
   at ICU4N.Globalization.UCultureInfo.get_CurrentCulture()
   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, OpenType openType)
   at ICU4N.Impl.ICUResourceBundle.GetBundleInstance(String baseName, String localeID, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.<>c__DisplayClass25_0.<GetRootType>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ICU4N.Util.UResourceBundle.GetRootType(String baseName, Assembly root)
   at ICU4N.Util.UResourceBundle.InstantiateBundle(String baseName, String localeName, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root, Boolean disableFallback)
   at ICU4N.Util.UResourceBundle.GetBundleInstance(String baseName, String localeName, Assembly root)
   at ICU4N.Text.Transliterator..cctor()
   --- End of inner exception stack trace ---
   at ICU4N.Text.Transliterator.GetInstance(String id)
   at Jellyfin.Extensions.StringExtensions.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Jellyfin.Extensions.StringExtensions.Transliterated(String text)
   at MediaBrowser.Controller.Entities.BaseItem.ModifySortChunks(ReadOnlySpan`1 name)
   at MediaBrowser.Controller.Entities.BaseItem.CreateSortName()
   at MediaBrowser.Controller.Entities.BaseItem.get_SortName()
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem item, BaseItem topParent, String userDataKey, SqliteCommand saveItemStatement)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(ManagedConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

**Comment by goncastrum** [comment] 2024-09-01 22:26
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 22:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 22:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 22:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 22:30
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by felix920506** [comment] 2024-09-01 23:11
Duplicate of #12536

**Closed** 2024-09-01 23:12 UTC
Labels: bug
