### ISSUE TITLE
Insanely high memory usage on nightly/unstable builds

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#3368] opened 2020-06-18 12:23 UTC
I saw insanely high memory usage in a Pi 4 4 GB in an instance that has been running without stopping for 24 hours:

![image](https://user-images.githubusercontent.com/10274099/85019111-93a7fb80-b16e-11ea-8615-c31a78245cb2.png)

*That's roughly 60% of Pi's 4 GB RAM*

Luckily I had Debug logs enabled for that instance. Every few seconds there are lines that seems to point to SyncPlay's Ping jobs spawning websockets crazily:

```
[2020-06-18 11:55:28.905 +00:00] [DBG] [47] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:55:37.119 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:55:38.038 +00:00] [DBG] [81] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.0.204" received message: WebSocketMessage`1 { MessageType: "KeepAlive", MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2020-06-18 11:55:40.904 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:55:47.118 +00:00] [DBG] [81] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:55:52.906 +00:00] [DBG] [47] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:55:57.118 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:04.903 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:56:07.117 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:08.037 +00:00] [DBG] [47] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.0.204" received message: WebSocketMessage`1 { MessageType: "KeepAlive", MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2020-06-18 11:56:16.904 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:56:17.118 +00:00] [DBG] [154] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:27.148 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:28.905 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:56:37.118 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:38.038 +00:00] [DBG] [47] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.0.204" received message: WebSocketMessage`1 { MessageType: "KeepAlive", MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2020-06-18 11:56:40.904 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:56:47.119 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:56:52.903 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:56:57.117 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:57:04.912 +00:00] [DBG] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2020-06-18 11:57:07.119 +00:00] [DBG] [47] MediaBrowser.Api.ApiEntryPoint: PingTranscodingJob PlaySessionId="1592475936882" isUsedPaused: True
[2020-06-18 11:57:08.037 +00:00] [DBG] [81] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.0.204" received message: WebSocketMessage`1 { MessageType: "KeepAlive", MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
```
That's repeated endlessly.

**Additional details**

* OS: Raspbian OS
* Docker
* Nightly build from my ``env-docker`` branch: https://github.com/ferferga/jellyfin/tree/env-docker
* Web master.
* Direct connection

**Comment by joshuaboniface** [comment] 2020-07-04 01:25
I noticed this earlier today, but right now I can't reproduce it after updating to the latest Unstable releases. Is it still happening @ferferga @Artiume?

**Comment by joshuaboniface** [comment] 2020-07-06 03:15
I can confirm this is still happening. It seems to have started right when I began using nightlies again, so the issue is definitely 1+ months old.

![Screenshot from 2020-07-05 23-14-29](https://user-images.githubusercontent.com/4031396/86552208-4d47f000-bf15-11ea-9e71-dbbd08ad20ce.png)

It definitely seems related to library scanning. This more-zoomed-in view shows bumps every ~12h, which is about the time I do a scan.

![Screenshot from 2020-07-05 22-56-40](https://user-images.githubusercontent.com/4031396/86552233-5fc22980-bf15-11ea-8bb6-b4a045405dff.png)

I did some testing with playback, both remote and local, and memory usage seems stable with this scenario. It's only when there's a library scan that it seems to climb.

This is *definitely* going to be a problem for a stable release - calling this an RC bug.

**Comment by crobibero** [comment] 2020-07-06 15:50
What are the library settings used to replicate this issue? Using dotMemory it looks like the memory usage is from ServiceStack, and the scan is properly being collected. I haven't spent any real time profiling a program before, so someone with more experience might be able to dive deeper

![dotMemory UI 64 2020 1 3_h0pUYA5Gu4](https://user-images.githubusercontent.com/24963659/86612818-ec003b00-bf6d-11ea-8308-c0cdc7cf6f70.png)

**Comment by BaronGreenback** [comment] 2020-07-09 19:21
SSDP DeviceDiscovery isn't filtered. Whilst not a great CPU hog - it will be part.

We could limit it down to 

urn:schemas-upnp-org:device:MediaRenderer and urn:schemas-upnp-org:device:MediaServer

Is there any other devices we need?

**Comment by BaronGreenback** [comment] 2020-07-09 19:24
Been playing with implementing DLNA subscriptions. 

DLNA PlayTo is currently setup to start a timer that polls the device, the moment a DLNA device is detected regardless of whether it is used or not.

Again, not a lot - but it's something

**Closed** 2020-07-13 18:54 UTC
Labels: bug, confirmed, release critical
