### ISSUE TITLE
[Issue]: Subtitles are not displayed

### ISSUE THREAD

**Issue by ChenAlien** [jellyfin/jellyfin#10708] opened 2023-12-10 11:38 UTC
### Please describe your bug

Transcoding occurs because the subtitle codec is not supported,but the subtitles are not displayed

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Truenas
- Linux Kernel:5.15.131
- Virtualization:Docker
- Clients:jellyfin-androidtv
- Browser:
- FFmpeg Version:
- Playback Method:jellyfin-androidtv libVLC 
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### FFmpeg logs

```shell
/videos/c33a5510-29b1-e111-b4c8-6a8f10b5db63/stream.mkv

{"Protocol":0,"Id":"c33a551029b1e111b4c86a8f10b5db63","Path":"/media/Bangumi/\u94F6\u6CB3\u94C1\u9053999/Season 1/\u94F6\u6CB3\u94C1\u9053999 S01E01.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":1530984960,"Name":"\u94F6\u6CB3\u94C1\u9053999 S01E01","IsRemote":false,"ETag":"e84d04bbc747b089c84959b43d5186bd","RunTimeTicks":14792699904,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"ass","CodecTag":null,"Language":"srd","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/100","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"\u672A\u5B9A\u4E49","LocalizedDefault":"\u9ED8\u8BA4","LocalizedForced":"\u5F3A\u5236\u7684","LocalizedExternal":"\u5916\u90E8","DisplayTitle":"Srd - ASS - \u5916\u90E8","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/Bangumi/\u94F6\u6CB3\u94C1\u9053999/Season 1/\u94F6\u6CB3\u94C1\u9053999 S01E01.SC.ass","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"h264","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"ChannelLayout":null,"BitRate":8279678,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1440,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":1,"AspectRatio":"4:3","Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":41,"IsAnamorphic":null},{"Codec":"flac","CodecTag":null,"Language":"jpn","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FLAC 2.0","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"FLAC 2.0 - Jpn - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":960000,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":96000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":9239678,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:06:40.072 -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/media/Bangumi/银河铁道999/Season 1/银河铁道999 S01E01.mkv" -autoscale 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi -force_key_frames "expr:gte(t,n_forced*5)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap,format=nv12,subtitles=f='/media/Bangumi/银河铁道999/Season 1/银河铁道999 S01E01.SC.ass':charenc=utf-8:fontsdir='/cache/attachments/c33a551029b1e111b4c86a8f10b5db63',hwmap,format=vaapi" -copyts -avoid_negative_ts disabled -start_at_zero -rc_mode VBR -b:v 8279678 -maxrate 8279678 -bufsize 16559356 -profile:v:0 high -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ac 2 -ab 256000 -y "/config/transcodes/23290071f461957ef891738372896bd8.mkv"

ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil 57. 28.100 / 57. 28.100
libavcodec 59. 37.100 / 59. 37.100
libavformat 59. 27.100 / 59. 27.100
libavdevice 59. 7.100 / 59. 7.100
libavfilter 8. 44.100 / 8. 44.100
libswscale 6. 7.100 / 6. 7.100
libswresample 4. 7.100 / 4. 7.100
libpostproc 56. 6.100 / 56. 6.100
Input #0, matroska,webm, from 'file:/media/Bangumi/银河铁道999/Season 1/银河铁道999 S01E01.mkv':
Metadata:
encoder : libebml v1.3.0 + libmatroska v1.4.1
creation_time : 2014-03-14T12:10:26.000000Z
Duration: 00:24:39.27, start: 0.000000, bitrate: 8279 kb/s
Chapters:
Chapter #0:0: start 0.000000, end 80.497000
Metadata:
title : Opening
Chapter #0:1: start 80.497000, end 731.397000
Metadata:
title : A Part
Chapter #0:2: start 731.397000, end 1382.839000
Metadata:
title : B Part
Chapter #0:3: start 1382.839000, end 1407.697000
Metadata:
title : Yokoku
Chapter #0:4: start 1407.697000, end 1479.270000
Metadata:
title : Ending
Stream #0:0: Video: h264 (High), yuv420p(progressive), 1440x1080 [SAR 1:1 DAR 4:3], 23.98 fps, 23.98 tbr, 1k tbn (default)
Stream #0:1(jpn): Audio: flac, 96000 Hz, stereo, s32 (24 bit) (default)
Metadata:
title : FLAC 2.0
Stream mapping:
Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
Stream #0:1 -> #0:1 (flac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[Parsed_subtitles_4 @ 0x55ab2ff82cc0] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[Parsed_subtitles_4 @ 0x55ab2ff82cc0] Using font provider fontconfig
[Parsed_subtitles_4 @ 0x55ab2ff82cc0] Neither PlayResX nor PlayResY defined. Assuming 384x288
[h264_vaapi @ 0x55ab2fdc4780] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
Output #0, matroska, to '/config/transcodes/23290071f461957ef891738372896bd8.mkv':
Metadata:
encoder : Lavf59.27.100
Stream #0:0: Video: h264 (High) (H264 / 0x34363248), vaapi(bt709, progressive), 1440x1080 [SAR 1:1 DAR 4:3], q=2-31, 8279 kb/s, 23.98 fps, 1k tbn (default)
Metadata:
encoder : Lavc59.37.100 h264_vaapi
Stream #0:1: Audio: aac ([255][0][0][0] / 0x00FF), 96000 Hz, stereo, s16, 256 kb/s (default)
Metadata:
encoder : Lavc59.37.100 libfdk_aac
frame= 1 fps=0.0 q=0.0 size= 1kB time=00:00:00.00 bitrate=N/A speed= 0x
frame= 51 fps=0.0 q=-0.0 size= 1kB time=00:00:02.04 bitrate= 3.0kbits/s speed=2.62x
frame= 105 fps= 82 q=-0.0 size= 1kB time=00:00:04.39 bitrate= 1.4kbits/s speed=3.41x
frame= 158 fps= 88 q=-0.0 size= 5120kB time=00:00:06.61 bitrate=6343.5kbits/s speed= 3.7x
frame= 212 fps= 93 q=-0.0 size= 5120kB time=00:00:08.91 bitrate=4704.2kbits/s speed=3.89x
frame= 264 fps= 95 q=-0.0 size= 10240kB time=00:00:10.96 bitrate=7651.0kbits/s speed=3.93x
frame= 318 fps= 96 q=-0.0 size= 10240kB time=00:00:13.18 bitrate=6363.2kbits/s speed=3.99x
frame= 372 fps= 98 q=-0.0 size= 15616kB time=00:00:15.44 bitrate=8283.2kbits/s speed=4.05x
frame= 427 fps= 99 q=-0.0 size= 15616kB time=00:00:17.66 bitrate=7242.6kbits/s speed=4.09x
frame= 475 fps= 99 q=-0.0 size= 15616kB time=00:00:19.88 bitrate=6434.9kbits/s speed=4.13x
frame= 528 fps= 99 q=-0.0 size= 20736kB time=00:00:21.88 bitrate=7761.2kbits/s speed=4.11x
frame= 582 fps=100 q=-0.0 size= 20736kB time=00:00:24.10 bitrate=7047.1kbits/s speed=4.13x
frame= 637 fps=101 q=-0.0 size= 25856kB time=00:00:26.58 bitrate=7968.6kbits/s speed=4.19x
frame= 692 fps=101 q=-0.0 size= 25856kB time=00:00:28.84 bitrate=7344.4kbits/s speed=4.22x
frame= 745 fps=101 q=-0.0 size= 31232kB time=00:00:31.14 bitrate=8215.1kbits/s speed=4.24x
frame= 802 fps=102 q=-0.0 size= 31232kB time=00:00:33.49 bitrate=7639.2kbits/s speed=4.27x
frame= 856 fps=102 q=-0.0 size= 36352kB time=00:00:35.75 bitrate=8329.5kbits/s speed=4.28x
frame= 909 fps=103 q=-0.0 size= 36352kB time=00:00:38.10 bitrate=7816.2kbits/s speed= 4.3x
frame= 965 fps=103 q=-0.0 size= 41472kB time=00:00:40.10 bitrate=8471.2kbits/s speed=4.28x
frame= 1020 fps=103 q=-0.0 size= 41472kB time=00:00:42.45 bitrate=8002.9kbits/s speed= 4.3x
frame= 1072 fps=103 q=-0.0 size= 41472kB time=00:00:44.54 bitrate=7627.2kbits/s speed= 4.3x
frame= 1125 fps=103 q=-0.0 size= 46592kB time=00:00:46.71 bitrate=8169.7kbits/s speed= 4.3x
frame= 1181 fps=104 q=-0.0 size= 46592kB time=00:00:49.06 bitrate=7779.3kbits/s speed=4.31x
frame= 1235 fps=104 q=-0.0 size= 51968kB time=00:00:51.58 bitrate=8253.1kbits/s speed=4.34x
frame= 1288 fps=104 q=-0.0 size= 51968kB time=00:00:53.58 bitrate=7944.4kbits/s speed=4.33x
frame= 1342 fps=104 q=-0.0 size= 57344kB time=00:00:56.10 bitrate=8373.1kbits/s speed=4.35x
frame= 1397 fps=104 q=-0.0 size= 57344kB time=00:00:58.15 bitrate=8077.9kbits/s speed=4.34x
frame= 1451 fps=104 q=-0.0 size= 62464kB time=00:01:00.37 bitrate=8475.9kbits/s speed=4.35x
frame= 1503 fps=104 q=-0.0 size= 62464kB time=00:01:02.50 bitrate=8186.6kbits/s speed=4.34x
frame= 1558 fps=105 q=-0.0 size= 62464kB time=00:01:04.89 bitrate=7885.1kbits/s speed=4.36x
frame= 1612 fps=105 q=-0.0 size= 67584kB time=00:01:07.28 bitrate=8228.5kbits/s speed=4.37x
frame= 1667 fps=105 q=-0.0 size= 67584kB time=00:01:09.50 bitrate=7965.8kbits/s speed=4.37x
frame= 1723 fps=105 q=-0.0 size= 72960kB time=00:01:11.72 bitrate=8333.6kbits/s speed=4.37x
frame= 1777 fps=105 q=-0.0 size= 72960kB time=00:01:14.02 bitrate=8074.1kbits/s speed=4.38x
frame= 1828 fps=105 q=-0.0 size= 78336kB time=00:01:16.20 bitrate=8421.5kbits/s speed=4.37x
frame= 1882 fps=105 q=-0.0 size= 78336kB time=00:01:18.37 bitrate=8187.7kbits/s speed=4.37x
frame= 1935 fps=105 q=-0.0 size= 83456kB time=00:01:20.51 bitrate=8491.7kbits/s speed=4.37x
frame= 1992 fps=105 q=-0.0 size= 83456kB time=00:01:23.02 bitrate=8234.2kbits/s speed=4.39x

[q] command received. Exiting.

frame= 2046 fps=105 q=-0.0 Lsize= 89069kB time=00:01:25.18 bitrate=8565.8kbits/s speed=4.38x
video:86326kB audio:2670kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.081358%
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2023-12-10 22:14
Hi, please provide the following info:
1. Media info
2. The GPU model

**Comment by sevenrats** [comment] 2023-12-12 19:53
thank you for this bug report. please remember that tracking an issue in multiple places will only slow down its resolution.
closing as duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/3208

**Closed by sevenrats** 2023-12-12 19:53 UTC
Labels: bug
