### ISSUE TITLE
[Unstable] Live TV is Broken

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#4385] opened 2020-10-29 00:38 UTC
```[2020-10-29 00:14:24.746 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Live stream opened after 5518.5935ms
[2020-10-29 00:14:24.746 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Returning mediasource streamId "d294c9383b71a15162b354a00436d809", mediaSource.Id "d294c9383b71a15162b354a00436d809", mediaSource.LiveStreamId null
[2020-10-29 00:14:24.747 +00:00] [INF] [52] Emby.Server.Implementations.Library.MediaSourceManager: Waiting 3000ms before probing the live stream


[2020-10-29 00:14:24.747 +00:00] [INF] [52] Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Deleting temp files ["/config/transcodes/92ea3d6e8e5a47c68e0089e1bcb88314.ts"]
[2020-10-29 00:14:27.748 +00:00] [INF] [52] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 3000000 -i \"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/92ea3d6e8e5a47c68e0089e1bcb88314/stream.ts\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2020-10-29 00:14:27.802 +00:00] [ERR] [62] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/config/transcodes/92ea3d6e8e5a47c68e0089e1bcb88314.ts'". URL "GET" "/LiveTv/LiveStreamFiles/92ea3d6e8e5a47c68e0089e1bcb88314/stream.ts".
[2020-10-29 00:14:27.804 +00:00] [ERR] [78] Emby.Server.Implementations.Library.MediaSourceManager: Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
```

It shouldn't be deleting the ts file `Emby.Server.Implementations.LiveTv.TunerHosts.M3UTunerHost: Deleting temp files ["/config/transcodes/92ea3d6e8e5a47c68e0089e1bcb88314.ts"]`

**Comment by PrplHaz4** [comment] 2020-10-29 00:49
duplicate of https://github.com/jellyfin/jellyfin/issues/4111 maybe?

**Comment by Artiume** [comment] 2020-10-29 00:52
looks like the same issue of the ts file being deleted

**Comment by Artiume** [comment] 2020-10-29 06:01
this didnt fix the removal of the files, it did fix another issue that crob was having though

**Closed** 2020-11-06 14:27 UTC
Labels: bug, regression
