### ISSUE TITLE
23.976fps Media does not transcode to ios (tested with ios 13 and 14)

### ISSUE THREAD

**Issue by zas2** [jellyfin/jellyfin#4245] opened 2020-10-01 09:58 UTC
**I found a bug playing 23.976fps content on ios-Client:**

All my media (mostly MKVs from Blurays and DVDs) are well transcoded with jellyfin to my Webbrowsers (Windows 10, Edge, Firefox, Chrome) but not to my iPhone. Also Directplay does show th same behavior.

Some of my Media is playing, so i analyzed the mediainformation and i found out, that all 23.976fps media fails.
24fps, 25fps etc. all run fine.

i converted "2 Guns" from 23.976 to 24fps via mkvmerge (no re-encoding and no other paramter changing in the header) and the new version of "2 Guns" is well streamed to the iphone.

 - OS: Debian 4.19.146-1
 - Clients: ios
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play, Transcode
 - Installed Plugins: tvheadend

Its not the Problem with transcoding because ffmpeg is not being initialized, it stops before that.

**The 23.976fps Version (does not start to play):  first request produces http 200 but the second http 204:**

[2020-10-01 11:41:05.161 +02:00] [INF] [44] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://xx.xx.xx.xx:8096/videos/8afec911-c368-c049-afd4-b795638085c6/master.m3u8?DeviceId=DC520137-D38C-4987-A8AF-0FC9F98ED3A0&MediaSourceId=8afec911c368c049afd4b795638085c6&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&SubtitleStreamIndex=5&VideoBitrate=416000&AudioBitrate=384000&PlaySessionId=d93a5f3997fd4f58a9eeace13b7aaad5&api_key=ebe7d5dd900249688ded17cd847ecd8d&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6e94b4520d2f8f25c0d1a2ba214467af&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-deinterlace=true&h264-level=42&TranscodeReasons=SubtitleCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false&allowAudioStreamCopy=false
[2020-10-01 11:41:05.192 +02:00] [INF] [44] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 31.0541ms 200 application/x-mpegURL
[2020-10-01 11:41:05.196 +02:00] [INF] [40] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 38.4386ms 204
[2020-10-01 11:41:05.241 +02:00] [INF] [83] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://89.1.31.162:8096/Sessions/Playing/Stopped application/json 570

**The 24fps Version (working well):** 

[2020-10-01 11:45:25.046 +02:00] [INF] [20] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://xx.xx.xx.xx:8096/videos/0f7ff8ff-d7e1-8654-8d5c-88308ad9161b/master.m3u8?DeviceId=DC520137-D38C-4987-A8AF-0FC9F98ED3A0&MediaSourceId=0f7ff8ffd7e186548d5c88308ad9161b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=2&SubtitleStreamIndex=9&VideoBitrate=416000&AudioBitrate=384000&PlaySessionId=6adbb04cabbe4a83985ed343138064e7&api_key=ebe7d5dd900249688ded17cd847ecd8d&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=cee6c531140b809855c4f50c90d05955&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-deinterlace=true&h264-level=42&TranscodeReasons=SubtitleCodecNotSupported
[2020-10-01 11:45:25.074 +02:00] [INF] [20] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 27.7627ms 200 application/x-mpegURL
[2020-10-01 11:45:25.115 +02:00] [INF] [20] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://xx.xx.xx.xx:8096/videos/0f7ff8ff-d7e1-8654-8d5c-88308ad9161b/main.m3u8?DeviceId=DC520137-D38C-4987-A8AF-0FC9F98ED3A0&MediaSourceId=0f7ff8ffd7e186548d5c88308ad9161b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=2&SubtitleStreamIndex=9&VideoBitrate=416000&AudioBitrate=384000&PlaySessionId=6adbb04cabbe4a83985ed343138064e7&api_key=ebe7d5dd900249688ded17cd847ecd8d&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=cee6c531140b809855c4f50c90d05955&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-deinterlace=true&h264-level=42&TranscodeReasons=SubtitleCodecNotSupported
[2020-10-01 11:45:25.553 +02:00] [INF] [20] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 438.0301ms 200 application/x-mpegURL
[2020-10-01 11:45:25.843 +02:00] [INF] [60] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://xx.xx.xx.xx:8096/videos/0f7ff8ff-d7e1-8654-8d5c-88308ad9161b/hls1/main/0.ts?DeviceId=DC520137-D38C-4987-A8AF-0FC9F98ED3A0&MediaSourceId=0f7ff8ffd7e186548d5c88308ad9161b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=2&SubtitleStreamIndex=9&VideoBitrate=416000&AudioBitrate=384000&PlaySessionId=6adbb04cabbe4a83985ed343138064e7&api_key=ebe7d5dd900249688ded17cd847ecd8d&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=cee6c531140b809855c4f50c90d05955&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-deinterlace=true&h264-level=42&TranscodeReasons=SubtitleCodecNotSupported

**the issue can be reproduced with any (h264) media with 23.976fps**

best regards,
zas2

**Comment by zas2** [comment] 2020-10-01 10:15
another thing i also recognized is the difference in both logs

the first url ends with:
**&allowVideoStreamCopy=false&allowAudioStreamCopy=false&allowAudioStreamCopy=false**

the second does not have this string in the url.

best regards,
zas2

**Comment by orhan-drsn** [comment] 2020-10-22 09:15
I have the same problem with all my iOS devices (iOS 10-14).
I tried to start a movie on my server (Ubuntu 20.04 LTS) and get the same problem. 
But I can start everything from my Android devicecs without any problem.

**Comment by vendorstring** [comment] 2021-03-24 12:26
the issue is fixed with version 10.7.0, thanks.

**Comment by zas2** [comment] 2021-03-24 12:28
i can confirm that the issue has been fixed in 10.7.0

**Closed** 2021-03-24 12:29 UTC
Labels: bug
