### ISSUE TITLE
[Issue]: Filters only match the default version of multi version titles

### ISSUE THREAD

**Issue by TheMelmacian** [jellyfin/jellyfin#9205] opened 2023-01-30 00:29 UTC
### Please describe your bug

Currently a title with multiple versions can only be found via the filter, if the default version matches. All other variants are ignored.
Filter values should be matched against all variants of a title.

In the following example "1080p surround" becomes the default version.
```txt
Movies
└── Big Bug Bunny (2008)
    ├── Big Bug Bunny (2008) - 1080p surround.avi
    ├── Big Bug Bunny (2008) - Sunflower 2160p 60fps.mp4
    └── Big Bug Bunny (2008) - Sunflower 2160p 60fps 3D FTAB.mp4
```

Filters -> Video types
- HD -> matches
- 4k -> doesn't match
- 3D -> doesn't match

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: Jellyfin Web
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

-------------------------------

**Edit:** I found two related issues: https://github.com/jellyfin/jellyfin/issues/6609, https://github.com/jellyfin/jellyfin-web/issues/4286

**Comment by Bond-009** [comment] 2023-03-27 21:23
Closing as duplicate of #6609

**Closed by Bond-009** 2023-03-27 21:23 UTC
Labels: bug
