### ISSUE TITLE
Unusual subtitles bug - "secondary subtitles" option appears from nowhere

### ISSUE THREAD

**Issue by TimF0** [jellyfin/jellyfin#13110] opened 2024-11-25 19:05 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have an mkv version of a film with no embedded subtitles. I downloaded a subtitle file, renamed it appropriately and added it to the server. The subtitle option shows up against the film as "English - SUBRIP - External". So far, so good. However, when I go to turn subtitles off from within the player, in addition to "Off" and the SUBRIP option mentioned above, a new "Secondary Subtitles" option is shown.

### Reproduction steps

1. Add a new film to the server
2. Download a suitable .srt subtitle file
3. Rename the subtitle file to (filename).eng.srt where (filename) is the file name of the film
4. Add the subtitle file to the same directory as the film
5. Refresh the film metadata

6a. Start the film with subtitles off - the 'cc' button is shown and, if clicked, two options are shown - "Off" (already selected) and "English - SUBRIP - External". 
6b. Select the subtitles and let the film continue - subtitles are shown
6c. Click the 'cc' button again - now THREE options are shown - "Off", "English - SUBRIP - External" (already selected) and a new one "Secondary Subtitles"

or

7a. Start the film with subtitles on -  the 'cc' button is shown and, if clicked, THREE options are shown - "Off", "English - SUBRIP - External" (already selected) and a new one "Secondary Subtitles".
7b. Turn the subtitles off and let the film continue
7c. Click the 'cc' button again - now only TWO options are shown - "Off" (already selected) and "English - SUBRIP - External"

### What is the current _bug_ behavior?

A third option "Secondary Subtitles" is being offered when subtitles are already turned on.

### What is the expected _correct_ behavior?

Only "Off" and one additional option (presumably - in this case - "English - SUBRIP - External") should be offered where there is only one choice of subtitles.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Unraid 6.12.13
- Linux Kernel:
- Virtualization: none
- Clients: Browser
- Browser: Firefox 132.0.2
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Direct Play (also happens on my phone using HTML Video Player)
- Hardware Acceleration: NVENC
- GPU Model: GTX 1050Ti
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
[2024-11-25 18:59:35.601 +00:00] [INF] [25] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.50.75" request
[2024-11-25 18:59:39.205 +00:00] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "RaveDrake". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-11-25 18:59:39.976 +00:00] [INF] [35] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -noautorotate -hwaccel_flags +unsafe_output -threads 1 -i file:\"/media/animated_films/Despicable Me/Despicable Me 2 (2013) 1080p.mkv\" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p1 -b:v 2616000 -maxrate 2616000 -bufsize 5232000 -profile:v:0 main -g:v:0 72 -keyint_min:v:0 72 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=format=yuv420p\" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"4f672738b804eaad92886c0c92620fa7-1.mp4\" -start_number 0 -hls_segment_filename \"/tmp/4f672738b804eaad92886c0c92620fa7%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/tmp/4f672738b804eaad92886c0c92620fa7.m3u8\""
[2024-11-25 19:00:43.631 +00:00] [INF] [29] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/tmp/4f672738b804eaad92886c0c92620fa7.m3u8"
[2024-11-25 19:00:44.155 +00:00] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-11-25 19:00:44.155 +00:00] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/tmp/4f672738b804eaad92886c0c92620fa7.m3u8"
[2024-11-25 19:00:45.813 +00:00] [INF] [27] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.6.2" playing "Despicable Me 2". Stopped at "61683" ms
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

Options when turning subtitles ON:

![Image](https://github.com/user-attachments/assets/4ed96321-e1c1-49ea-b81d-99e3db0466fb)

Options when turning subtitles OFF:

![Image](https://github.com/user-attachments/assets/5f79c7bd-146b-4978-8ca5-f04641f8c57c)

**Comment by crobibero** [comment] 2024-11-25 20:09
Closing as duplicate of the other issue you opened and I already transferred. 

https://github.com/jellyfin/jellyfin-web/issues/6345

**Closed by crobibero** 2024-11-25 20:09 UTC
Labels: bug
