### ISSUE TITLE
when using option to group medias folders, movies disapear

### ISSUE THREAD

**Issue by brupec** [jellyfin/jellyfin#12565] opened 2024-09-01 19:12 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Latest 10.9.10 jellyfin

I have two movies folder "films" and "films (bruno)
![24_09_01_336](https://github.com/user-attachments/assets/dc0cc988-f470-4783-8b16-d854887d7e0a)

"films" have 1971 medias
![24_09_01_338](https://github.com/user-attachments/assets/b554a4c9-c078-4c82-99e6-f9decf4c1509)

"films (bruno)" have 50 medias
![24_09_01_339](https://github.com/user-attachments/assets/b2c2fbf1-58fd-45ce-ba91-763e9c07fbfb)

when I group the two folders with the option in homescreen parameters:
![24_09_01_337](https://github.com/user-attachments/assets/7a3fc32e-406c-4913-95eb-bf45ac965853)

I indeed get just one "movie" folder, but which only have 900 medias:
![24_09_01_340](https://github.com/user-attachments/assets/3d537dcb-a441-4801-a890-15b53a3cbdec)

It should have 2021 medias.

### Reproduction steps

make two movie folder, one of them with lot of medias
group them

see if they are all here

### What is the current _bug_ behavior?

grouped folder miss medias

### What is the expected _correct_ behavior?

grouped folder have all medias

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.10

### Environment

```markdown
- OS: Linux
- Virtualization: docker package
- Clients: Windows official client
```

### Jellyfin logs

```shell
didn't find anything related to the issue in the logs
```

**Comment by felix920506** [comment] 2024-09-03 23:39
duplicate of #12086

**Closed by felix920506** 2024-09-03 23:39 UTC
Labels: bug
