### ISSUE TITLE
Subtitles get rendered double on chrome

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5582] opened 2021-03-21 13:49 UTC
**Describe the bug**
I  am getting some subtitle sentences rendered twice.
I have compared this with the file and it doesn't specify anything about extra lines(to my knowledge)
This is in chrome directplay only, forcing it to a low quality so it transcodes will solve this issue.

**System (please complete the following information):**
 - OS: UnRaid
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome Version 89.0.4389.90 (Official Build) (64-bit)
 - Jellyfin Version: 10.7.0 and unstable(20210320.1)
 - Playback: Direct Play
 - Installed Plugins: TVDb Box Sets
 - Reverse Proxy: nginx
 - Base URL: jellyfin.domain.com
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. play the flash Season 7 ep 2
2. watch for the first few seconds
3. See that subtitles get rendered double sometimes(the first line already has this)

**Logs**
Chrome with fault:
```
[14:42:08] [INF] [15] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4000000, RemoteIp: ***MyIP***, IsInLocalNetwork: True
[14:42:08] [INF] [15] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, Path: /tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[14:42:08] [INF] [15] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, No video direct play profiles found for /tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv with codec h264
[14:42:08] [INF] [15] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[14:42:08] [INF] [15] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -i file:"/tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/temp/transcoding-temp/34d01d04c157f350591e4d10d19d516f%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/temp/transcoding-temp/34d01d04c157f350591e4d10d19d516f.m3u8"

```
looks the same as firefox with correct subs:
```
[14:45:24] [INF] [48] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4000000, RemoteIp: ***MyIP***, IsInLocalNetwork: True
[14:45:24] [INF] [48] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, Path: /tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[14:45:24] [INF] [48] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, No video direct play profiles found for /tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv with codec h264
[14:45:25] [INF] [42] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[14:45:25] [INF] [42] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -i file:"/tv/The Flash (2014)/Season 7/The Flash (2014) - S07E02 - The Speed of Thought.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/cache/temp/transcoding-temp/f2831825b7c00789c8309b890421eecf%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/cache/temp/transcoding-temp/f2831825b7c00789c8309b890421eecf.m3u8"

```

**Screenshots**
<details>
  <summary>Spoiler warning for The Flash Season 7 Episode 2</summary>

![image](https://user-images.githubusercontent.com/9083045/111906917-551fd400-8a53-11eb-8bf7-73b70f4c8b4c.png)

</details>

**Comment by ikomhoog** [comment] 2021-07-21 13:25
This is still happening.

**Comment by thornbill** [comment] 2023-12-01 20:32
This [happens on iOS](https://github.com/jellyfin/jellyfin-expo/issues/98) also. I believe it is something specific to our HLS implementation?

**Comment by thornbill** [comment] 2024-03-31 02:58
Likely a duplicate of #4561

**Closed** 2024-03-31 02:58 UTC
Labels: bug, duplicate
