### ISSUE TITLE
Regex Improper Tags

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2441] opened 2020-02-22 21:31 UTC
This one will be tricky to find all cases of it occurring. Here's a few samples.

`Akira` was tagged as `Akira Jimbo: Wasabi`
`Thomas & Friends: The Great Race` was tagged as `The Making of Thomas & Friends: The Great Race`
[Assassin (2015)](https://www.themoviedb.org/movie/326057-assassin) was tagged as `Assassin's Creed`
[August (2008)](https://www.themoviedb.org/movie/13692-august) tagged as `August Rush`

Edit: added tmdb references

**Comment by Bond-009** [comment] 2020-02-22 22:08
I can't find the last 2 on tmdb, so that's not jellyfins fault I think

**Comment by Artiume** [comment] 2020-02-24 02:50
```[2020-02-23 20:43:12.715 -05:00] [INF] [11] App: Creating virtual missing/unaired episode "My Hero Academia" 4x20
[2020-02-23 20:43:12.853 -05:00] [INF] [11] App: Creating virtual missing/unaired episode "My Hero Academia" 4x21
[2020-02-23 20:43:12.978 -05:00] [INF] [11] App: Creating virtual missing/unaired episode "My Hero Academia" 4x22
[2020-02-23 20:43:13.198 -05:00] [INF] [23] App: Creating virtual missing/unaired episode "My Hero Academia" 4x23
[2020-02-23 20:43:13.314 -05:00] [INF] [11] App: Creating virtual missing/unaired episode "My Hero Academia" 4x24
[2020-02-23 20:43:13.429 -05:00] [INF] [23] App: Creating virtual missing/unaired episode "My Hero Academia" 4x25
[2020-02-23 20:44:00.541 -05:00] [INF] [26] App: Creating Season "Season Unknown" entry for "Air Master"
[2020-02-23 20:44:01.412 -05:00] [INF] [26] App: Removing virtual season "Air Master" null
```

**Comment by Artiume** [comment] 2020-03-07 13:17
[Escape (2012)](https://www.imdb.com/title/tt2147277/) identified as Escape Plan (2013). 

File Path: Escape (2012)/Escape (2012) 1080p.mp4

**Comment by Artiume** [comment] 2020-03-07 13:38
[Arthur (2011)](https://www.themoviedb.org/movie/49012-arthur) identified as [Arthur Christmas (2011)](https://www.themoviedb.org/movie/51052-arthur-christmas)

Arthur (2011)/Arthur (2011) Bluray-720p.mkv

**Comment by Artiume** [comment] 2020-03-07 14:26
[Boy (2010)](https://www.themoviedb.org/movie/321258-the-boy?language=en-US) identified as [Astro Boy](https://www.themoviedb.org/movie/16577-astro-boy?language=en-US)

Boy (2010)/Boy (2010) 1080p.mp4

**Comment by Artiume** [comment] 2020-03-07 14:29
[Atlas Shrugged Part 2](https://www.themoviedb.org/movie/134371?language=en-US) identified as [Atlas Shrugged Part 1](https://www.themoviedb.org/search/movie?query=Atlas%20Shrugged%3A%20Part%20I&language=en-US)

Atlas Shrugged Part 2 (2012)/Atlas Shrugged Part 2 (2012).mkv

**Comment by Artiume** [comment] 2020-03-07 16:25
[Audition (2000)](https://www.themoviedb.org/movie/11075) identified as [Audition (2000)](https://www.imdb.com/title/tt0280446/)


An upstream conflict is Audition has two release years. [1999](https://www.imdb.com/title/tt0235198/) and [2000](https://www.thetvdb.com/movies/audition).

**Comment by Artiume** [comment] 2020-03-07 16:44
[Harry Potter And The Half Blood Prince (2009)](https://www.themoviedb.org/movie/767-harry-potter-and-the-half-blood-prince) Identified as [Big Movie Premiere: Harry Potter and the Half Blood Prince (2009)](https://www.imdb.com/title/tt3969928/)

**Comment by Artiume** [comment] 2020-03-07 17:33
[Life (1999)](https://www.themoviedb.org/movie/6522-life?language=en-US) identified as [A Bug's Life (1998)](https://www.themoviedb.org/movie/9487-a-bug-s-life)

**Comment by Artiume** [comment] 2020-03-10 10:41
https://www.reddit.com/r/jellyfin/comments/fg55zc/titles_with_the_at_the_end_not_being_identified/

If you use scheme 'movie, the' it fails to find the movie.

**Comment by Protektor-Desura** [comment] 2020-03-11 18:57
The search mechanism should use the year if it is in the directory or file name since both Radarr and Sonarr will instantly find movies and TV shows when you add the year, like this:
Blade Runner (1982)
Altered Carbon (2018)

You can also test this by doing searches on TMDB website and TheTVDB website.

**Comment by crobibero** [comment] 2020-05-02 21:07
I'm not convinced this is a regex issue, but a metadata search issue.


Series Path
`/TV/The Rain (2018)/Season 01/The Rain - S01E01.mkv`

[TVDB Series Provider](https://github.com/jellyfin/jellyfin/blob/62e251663fce8216cea529f85382299ac2f39fbc/MediaBrowser.Providers/Plugins/TheTvdb/TvdbSeriesProvider.cs#L192)
`rain 2018` -> invalid results
`rain` -> invalid results

The provider strips `the` before searching, but:
`the rain` -> valid results
`the rain 2018` -> invalid results

**Comment by rigtorp** [comment] 2020-05-03 19:16
I think the search could be tried multiple times. First with stop words, then after removing stop words,then after removing numbers etc. 

There is an issue in that the file name parser only returns a single result. For example there might be multiple conflicting years in different parts of the path, in which case all of them should be returned and the search tried for each. 

There are also words such as "director's" and "extended" that can be stripped out if no match for full name.

**Comment by SethiPandi** [comment] 2020-05-05 00:38
[ERASED](https://www.thetvdb.com/series/erased) identified as [ERASED (2017)](https://www.thetvdb.com/series/erased-2017)

Boku Dake ga Inai Machi/

**Comment by SethiPandi** [comment] 2020-05-05 00:41
[Goblin Slayer Episode 10.5](https://www.thetvdb.com/series/goblin-slayer/episodes/6931629) identified as [Goblin Slayer Episode 10](https://www.thetvdb.com/series/goblin-slayer/episodes/6827105)

Goblin Slayer/Goblin Slayer S01E10.5.mkv

**Comment by SethiPandi** [comment] 2020-05-05 00:42
[Grimgar of Fantasy and Ash Episode 2.5](https://www.thetvdb.com/series/grimgar-ashes-and-illusions/episodes/5526387) identified as [Grimgar of Fantasy and Ash Episode 2](https://www.thetvdb.com/series/grimgar-ashes-and-illusions/episodes/5465976)

Hai to Gensou no Grimgar/Hai to Gensou no Grimgar S01E02.5.mkv

**Comment by coldshouldermedia** [comment] 2020-06-02 19:09
I have two shows, one is the same title with additional characters:
[1. Bubblegum Crisis [1987]](https://www.thetvdb.com/series/bubblegum-crisis)
[2. Bubblegum Crisis Tokyo 2040 [2001]](https://www.thetvdb.com/series/bubblegum-crisis-tokyo-2040)

Both are identified as [Bubblegum Crisis: Tokyo 2040](https://www.thetvdb.com/series/bubblegum-crisis-tokyo-2040), and the shows are combined, so in season one, I end up with two episode 1s, two episode 2s, etc.

**Comment by rigtorp** [comment] 2020-06-08 23:12
These are all miss-classified as being season 1.
```
/MacGyver Seasons 1-7
./MacGyver Seasons 1-7/Season 1
./MacGyver Seasons 1-7/Season 1/Macgyver.s1e01.Pilot.avi
./MacGyver Seasons 1-7/Season 1/Macgyver.s1e02.The_Golden_Triangle.avi
./MacGyver Seasons 1-7/Season 7
./MacGyver Seasons 1-7/Season 7/Macgyver.s7e14.Mountain_of_Youth.avi
./MacGyver Seasons 1-7/Season 4
./MacGyver Seasons 1-7/Season 4/Macgyver.s4e06.The_Survivors.avi
```

**Comment by Bond-009** [comment] 2020-06-20 16:31
> These are all miss-classified as being season 1.

Pretty sure that's because the root folder contains `Seasons 1-7`

**Comment by Bond-009** [comment] 2020-06-20 16:37
> Grimgar of Fantasy and Ash Episode 2.5

Jellyfin doesn't parse the `.5` and these count as episode 3 afaik.

**Comment by Protektor-Desura** [comment] 2020-06-21 18:53
If you look in the TVDB for anime there are some .5 episodes and they are not listed as the next whole number. But actually as .5 episodes that appear between the proper whole numbers. So there are times where TVDB does actually have .5 episodes and Jellyfin should handle those cases.
For example 4.5 does show up in TVDB as 4.5 not 5.

**Comment by rigtorp** [comment] 2020-06-21 22:23
> > These are all miss-classified as being season 1.
> 
> Pretty sure that's because the root folder contains `Seasons 1-7`

Yes, but that's wrong. Since the filename contains all needed information. Also the directory name contains the correct season.

**Comment by Protektor-Desura** [comment] 2020-06-22 05:27
./MacGyver Seasons 1-7/Season 1
Is not a valid and supported directory structure.

https://support.emby.media/support/solutions/articles/44001159110-tv-naming
https://jellyfin.org/docs/general/server/media/shows.html

Both of the above will show acceptable naming structures and the one above is not one of the examples, thus the reason Jellyfin is having an issue with that directory structure. It isn't magic where it can just auto figure it out. It has to be in supported pattern and that one is not supported.

It should be:
MacGyver/Season 01/

But even that isn't enough to be identified correctly. It should be:
MacGyver (1985)/Season 01/
or
MacGyver (2016)/Season 01/

**Comment by rigtorp** [comment] 2020-06-22 18:00
I know it's not supported. It can be supported and I plan on updating the `SeriesResolver` to support it. JF file identification is pretty bad, I have slowly been improving it. In my opinion it should work like magic! The goal is a good user experience.

**Comment by dkanada** [comment] 2020-06-23 08:28
A more thorough solution to this issue would be [custom resolvers](https://github.com/jellyfin/jellyfin/issues/2187) for odd naming schemes. Obviously we should try to improve the existing ones as much as possible, but the easiest way to fix this would be to let anyone use whatever naming scheme they want and have sane defaults.

**Comment by rigtorp** [comment] 2020-06-24 17:29
@dkanada One annoying thing with current resolvers is that they seem to prefer the name furthest away from the actual file. So `cool movies from 2009/movie 2009.mkv` would resolve as "Cool movies from" (2009). Same with my macgyver example, there is a clean standard naming of the filename, but JF prefers parsing info from a directory 2 steps removed from the filename.

**Comment by Protektor-Desura** [comment] 2020-06-24 22:20
>>I know it's not supported. It can be supported and I plan on updating the SeriesResolver to support it. 
>>JF file identification is pretty bad, I have slowly been improving it. In my opinion it should work like magic! 
>>The goal is a good user experience.

If you don't put the year in the how in the world is it going to know which MacGyver you talking about? And no number of seasons isn't enough because you have no idea how many seasons MacGyver (2016) will end up having in 5 years. Just use the year and then everything will work as intended and it is much easier to code for that as well.

**Comment by Protektor-Desura** [comment] 2020-06-24 22:23
Jellyfin uses the standard naming that Plex, Emby and Kodi all use for their movie and TV naming. If people want to make something up that is no standard and weird then that is the problem, the non-standard and weird naming. You can't support every naming possibility under the sun, that is just crazy and leads to unmaintainable code.

**Comment by rigtorp** [comment] 2020-06-25 03:59
> Jellyfin uses the standard naming that Plex, Emby and Kodi all use for their movie and TV naming. If people want to make something up that is no standard and weird then that is the problem, the non-standard and weird naming. You can't support every naming possibility under the sun, that is just crazy and leads to unmaintainable code.

Some naming schemes are better than others, but that's besides the point, it should work like magic. Ideally there should be something like Shazam for video content. Current implementation uses a list of regexes, it should be possible to augment it to handle the mcgyver case without making the code more complex.

**Comment by Protektor-Desura** [comment] 2020-07-05 16:19
You can fingerprint video the problem is no one has ever created an open fingerprint database. There are plenty of commercial programs and commercial databases that do this. YouTube has one, and several companies sell them as well. It would take something like MusicBrainz but video instead.

**Comment by rigtorp** [comment] 2020-07-06 02:46
Isn't that what I said? You're not adding anything constructive here like
code or useful tast cases like I and others have been doing.

**Comment by Protektor-Desura** [comment] 2020-07-07 00:27
Your comment added nothing to discussion. Since you are so worried about source code here is what I was talking about:
https://github.com/vishalpokarne/VideoFingerprinting
https://github.com/straypacket/videofingerprinting
https://github.com/funzoneq/video_fingerprinting
https://github.com/butterflo/ravif

**Comment by Artiume** [comment] 2020-07-07 00:32
Let's try and keep things civil. @rigtorp has helped clean up the regex code and os a valued member. This ticket is for current regex issues. The fingerprinting idea is neat and i was thinking how to do database ideas from this convo but it does belong in its own thread

**Comment by SethiPandi** [comment] 2020-10-01 07:40
[Heroes](https://www.thetvdb.com/series/heroes/) identified as [Fantastic Four: World's Greatest Heroes](https://www.thetvdb.com/series/fantastic-four-2006)

heroes-2006/

**Comment by SethiPandi** [comment] 2020-10-01 09:27
This might sound obvious, but for examples like above it could be nice to use [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)?

I haven't looked at the code, so I don't know how selection of the media works, but if you get multiple results, could just pick the one with the closest Levenshtein distance, which I would assume is most likely to be the one intended by the user?

**Comment by rigtorp** [comment] 2020-10-02 20:15
@SethiPandi The results comes from external APIs like TVDB etc. It seems like they use very simple information retrieval. Strip accents and apostrophes + tokenize and then return results which match all tokens, no stemming is used. So JF needs some algorithm to try multiple searches.

**Comment by crobibero** [comment] 2020-10-02 20:27
This PR may fix the issue
https://github.com/jellyfin/jellyfin/pull/4159

**Comment by srcrist** [comment] 2023-10-05 03:41
Issue closed by https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/1

**Closed by srcrist** 2023-10-05 03:41 UTC
Labels: confirmed
