### ISSUE TITLE
Bottom bar disapear when changing audio language

### ISSUE THREAD

**Issue by NoyTheBiche** [jellyfin/jellyfin#4355] opened 2020-10-21 07:09 UTC
**Describe the bug**
The bottom bar (where you can see the language changer, volume and play/pause buttons) disappear when we change the audio language of a movie/tv show

**System (please complete the following information):**
 - OS: Debian Server 10
 - Virtualization: /
 - Clients: Browser
 - Browser: Firefox Latest and Chrome latest
 - Jellyfin Version: nightly 20201020.33-unstable
 - Playback: Direct Play
 - Installed Plugins: Default
 - Reverse Proxy: /
 - Base URL: none
 - Networking: Host
 - Storage: Google Drive (Rclone)

**To Reproduce**

1. Play a Movie/Show
2. Click on audio options
3. Change the language

**Expected behavior**
The bottom bar should stay as normal..

**Logs**

[logs.txt](https://github.com/jellyfin/jellyfin/files/5413912/logs.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/20792017/96684906-a3ce2280-137c-11eb-9643-f2a7bddbf2a1.png)

**Comment by nyanmisaka** [comment] 2020-10-21 11:30
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/1965

**Closed** 2020-10-21 12:04 UTC
Labels: bug
