### ISSUE TITLE
Cannot access admin account after 10.3.1 upgrade

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#1329] opened 2019-04-30 12:26 UTC
**Describe the bug**
Neither the PIN nor password are working for my admin account after the 10.3.1.0 upgrade and there is no (actually working) method to reset the admin account password or any other account password for that matter, without the admin account password, to be used to reset non-admin accounts.

**To Reproduce**
N/A

**Expected behavior**
I should never be completely locked out of the admin account.  There should **always** be a way to recover it.

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Fedora 29
 - Browser: Chrome
 - Jellyfin Version: 10.3.1
 - Reverse proxy: None

**Additional context**
N/A

**Comment by anthonylavado** [comment] 2019-04-30 19:14
This appears to be caused by the issue that causes #1326, so when that is resolved, this should be resolved. Keeping it open though.

**Comment by gerroon** [comment] 2019-05-02 04:50
I am locked out of my account as well

**Comment by anthonylavado** [comment] 2019-05-02 04:57
@geroon Did your account have a password and a pin? Or only a password?

**Comment by gerroon** [comment] 2019-05-02 04:59
Only a password

**Comment by Thulinma** [comment] 2019-05-05 14:39
This problem still appears to exist in 10.3.2. Same issue here, cannot login to admin account, nor recover it. (At least the recovery screen pretends to work now... but it doesn't actually appear to do anything...?)
In my case this problem occurs when using a password-less admin account, with no other accounts on the system.
Maybe it's a good idea to have some shell-access-needed method to reset the admin login credentials to plain password login, with a chosen (or generated random) password, or something like that. That way it's impossible to get locked out of the admin account.

**Comment by DrPandemic** [comment] 2019-05-17 01:58
Before trying to reproduce this issue, could someone with the issue try on the latest 10.3.z branch. https://github.com/jellyfin/jellyfin/pull/1372 might have an impact on the problem, but I'm really not sure.

**Comment by joshuaboniface** [comment] 2019-05-18 03:25
Might be fixed in 10.3.3 - please confirm!

**Closed** 2019-05-20 04:34 UTC
Labels: bug

**Comment by Sn3akr21** [comment] 2021-02-01 22:29
Admin account is not allowing me to log in.  When I do put in the credentials it logs me in as a normal user 
![image](https://user-images.githubusercontent.com/75914406/106526138-18077e80-64b3-11eb-8e8d-1928d62b9bab.png)
