### ISSUE TITLE
DVD Order not using filename numbering

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1477] opened 2019-06-20 19:08 UTC
**Describe the bug**
When setting a series to DVD Order, files are assumed to be named using DVD order, not aired order. This was working fine but behavior has changed since #243.

Now TVDB metadata is looked up using filename episode numbers, assuming those are the aired order, not dvd order.

**To Reproduce**
Create a file named by DVD order.
```The Venture Bros. 1x03 - Mid-Life Chrysalis.mkv```
Scan library. 
Episode will be displayed as 1x03 Home Insecurity.
Edit Venture Bros. series to DVD Order
Refresh All Metadata for Venture Bros.
Episode will now be displayed as 1x07 Home Insecurity.

Both options are incorrect.

**Expected behavior**

Edit Venture Bros. series to DVD Order
Refresh All Metadata for Venture Bros.
Episode will now be displayed as 1x03 Mid-Life Chrysalis.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.5
 - Reverse proxy: no

**Comment by SenorSmartyPants** [comment] 2019-06-22 21:51
As example that other video jukeboxes also use the numbers in the filename as the DVD order numbers.

https://www.reddit.com/r/kodi/comments/59doqg/how_to_use_dvd_order_with_tv_shows_examples_with/

**Comment by sparky8251** [comment] 2019-06-25 11:03
Wonder if this is more of the fun with the database not being all that flexible right now....?

Regardless, this is definitely a regression but I'm going to mark it as blocked since to me, it reeks of "inflexible database."

**Comment by SenorSmartyPants** [comment] 2019-06-25 16:30
I made a pull request that addresses this issue. #1484 

One of the CI tests fails but the other passes. Not sure why that is.

**Comment by sparky8251** [comment] 2019-06-25 18:38
I apologize for that. I haven't been active lately and am just helping with triage since there's so much that hasn't been done around it. :)

Removed the blocking tag, hope to see your PR get merged soon!

**Closed** 2019-08-10 06:26 UTC
Labels: bug, regression
