### ISSUE TITLE
Server doesn't return images of the requested dimensions

### ISSUE THREAD

**Issue by 0ddb0d** [jellyfin/jellyfin#1187] opened 2019-04-02 13:41 UTC
**Describe the bug**
When a request for an image is made that includes the maxwidth or maxheight attributes the server doesn't return a correctly sized image. It appears to return the original unscaled image. The problem is not obvious because most clients perform their own resizing which makes everything appear to be working correctly.

**To Reproduce**
1. Find any thumbnail image URI using a browser's debugger
2. Open the image in a separate tab

**Expected behavior**
Image should be scaled to 200px wide while retaining the same aspect ratio as the original image.

**Logs**
[2019-04-03 00:07:15.295 +11:00] [INF] "HTTP GET" "http://192.168.0.200:8097/emby/Items/80b56cc534b5d848cb68c3b57a31f2bc/Images/Primary?maxWidth=200&amp;tag=9420f8472a4f2b17ea518e0eb162c8a3&amp;quality=90". UserAgent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 Vivaldi/2.4.1488.35"

**Screenshots**
![Clipboard 1](https://user-images.githubusercontent.com/45958107/55405314-81f82980-55a5-11e9-9d2f-bc12ad312845.jpg)

**System (please complete the following information):**
 - OS: Generic Linux and Windows 7 x64
 - Browser: Vivaldi 2.4.1488.35 (Chrome 73.0.3683.88)
 - Jellyfin Version: 10.2.2
 - Reverse proxy: No

**Additional context**
This was noticed while I was trying to get the old Emby Samsung TV client working with Jellyfin and is a needed fix because of the slow, buggy and incorrectly documented app framework supplied by Samsung for their older TVs and Bluray players.

**Comment by anthonylavado** [comment] 2019-04-03 04:07
Hrm. I wonder if any of the things we did with Skia might be at play here.

**Comment by 0ddb0d** [comment] 2019-04-04 06:41
Well this is weird.

`[2019-04-04 16:57:46.067 +11:00] [INF] Skia not available. Will fallback to NullIMageEncoder. {0}
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_color_premultiply(SKColor color)
   at SkiaSharp.SKPMColor.PreMultiply(SKColor color)
   at Jellyfin.Drawing.Skia.SkiaEncoder.LogVersion()
   at Jellyfin.Server.Program.GetImageEncoder(IFileSystem fileSystem, IApplicationPaths appPaths, ILocalizationManager localizationManager)`

libSkiaSharp.so is definitely present in the same directory as Jellyfin's binary, something doesn't smell right.

**Comment by bugfixin** [comment] 2019-05-01 22:28
I'm not able to reproduce this - is it still happening with the latest version of jellyfin?

**Comment by 0ddb0d** [comment] 2019-05-02 17:20
Yes, it's still occurring in 10.3.1 but you won't be able to reproduce the (non)bug as it's a packaging/build problem.

The QNAP package maintainer (QoolBox) has stuffed up some dependencies, libfontconfig is missing, the vendor supplied version of libstdc++ is too old leading to this `4652:/lib/libstdc++.so.6: error: version lookup error: version 'GLIBCXX_3.4.21' not found (required by libSkiaSharp.so) (fatal)` and probably some stuff I've missed due to copying Emby's lib directory over top of Jellyfin's to get Skia working.

I'll get in touch with QoolBox and get it sorted out.

**Comment by DrPandemic** [comment] 2019-05-26 03:52
Since we are not managing that package I propose that we close the issue. @anthonylavado any opinion?

**Closed** 2019-05-26 18:12 UTC
Labels: bug
