### ISSUE TITLE
[Issue]: Trailers not loading in english

### ISSUE THREAD

**Issue by anoo2niem** [jellyfin/jellyfin#10941] opened 2024-02-01 16:57 UTC
### Please describe your bug

Hi,

I have a big collection of movies, and i like the trailer function when u actually selected a movie which integrates and presents a youtube trailer.

I have one issue regarding this, mostly the trailer button won't even appear, and if it appears, it's always with dutch subtitles.
I assume since my interface language is in Dutch, it will only load trailers which has dutch subtitles?

Is there an option to fall back to english trailers, if there isn't one with dutch subtitles?
Or even to specify that all trailers are in english?

I've tried setting my interface language on the server itself and on client to english, but this didn't work.

Thanks!

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel: 6.5.11-7-pve
- Virtualization: LXC 
- Clients: Mostly Browser, Android 
- Browser: LibreWolf
- FFmpeg Version: 4.4.1-Jellyfin
- Playback Method: Direct Play/Transcode
- Hardware Acceleration: QSV
- GPU Model: Intel UHD Graphics 630
- Plugins:
- Reverse Proxy: Caddy
- Base URL: https://jellyfin.home
- Networking: Bridge
- Storage:
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment] 2024-02-29 12:43
I cannot reproduce the "only loads Dutch trailer" problem. When I create a dummy movie file as `Sword Art Online the Movie – Progressive – Aria of a Starless Night` it provides me with the [following trailer](https://www.youtube.com/watch?v=Jf6RyZkuVco). I also tested it with other trailers. Some do not work. But I cannot watch those trailers directly on YouTube either. They likely are region blocked, or something else from YouTube blocks me from watching it.

The fact that you see subtitles in Dutch has to do with it being an embedded YouTube video. And YouTube has a tendency to show subtitles.

I have tested with TheMovieDatabase as my metadata provider and my library language is set to English.

**Comment by TimGels** [comment] 2024-02-29 12:45
Please provide your library settings, what metadata provider you use and which movies we are talking about. That way we are able to try and reproduce this better.

**Comment by anoo2niem** [comment] 2024-02-29 16:20
Hi, 

I just made the same dummy movie file as u with library language set to Dutch and Themoviedb as metadata provider.

There is no trailer available with these settings;
![no-trailer](https://github.com/jellyfin/jellyfin/assets/26277207/61ab798d-39bc-4611-9d50-2bb168ca1116)

However, i deleted this dummy movie and recreated it with all library/metadata settings identical, apart from language set to English this time. This gave me indeed a trailer option on the dummy movie.

I've left my library language to English and replaced all metadata for 278 movies. Now ~95% has a trailer whereas before ~5% with library language set to Dutch.

I'm happy with the outcome, and for me this issue can be closed.
However it would be nice to have an option to have library language set to Dutch and override trailer to English (If that makes sense, i don't specifically know how this is handled by backend), if it is not found when library language is set to Dutch.

Thanks anyway for yout response, it made me found out what the issue was and gave me trailers for almost my whole library by setting library language to English, and 'replace all metadata' for that library.
I've tried this before but only used 'search for missing metadata'.

**Comment by TimGels** [comment] 2024-02-29 16:28
I am glad you got it working. I did not know library language had impact on the trailer. My guess is that it tries to find a Dutch version from TMDB, which there is none of afaik, resulting in no trailer option. Adding such a setting would be considered a feature request and can be done over at https://features.jellyfin.org/. I will close this issue now.

**Closed by TimGels** 2024-02-29 16:28 UTC
Labels: bug
