### ISSUE TITLE
Playback is green/broken on some media but files are okay, playback comes good after several minutes, then goes green again

### ISSUE THREAD

**Issue by Bonn93** [jellyfin/jellyfin#4947] opened 2021-01-04 09:22 UTC
**Media Info of the file**
Title4K HEVC
CodecHEVC
ProfileMain 10
Level153
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate55526 kbps
Pixel formatyuv420p10le
Ref frames1

TitleEng TRUEHD 7.1 Default
Languageeng
CodecTRUEHD
Layout7.1
Channels8 ch
Sample rate48000 Hz
Bit depth24 bit
DefaultYes

**Logs**
[09:05:15] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_cuvid -resize 3840x2160 -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Launched ffmpeg process
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Waiting for the creation of /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: File /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts created or transcoding has finished
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: StartFfMpeg() finished successfully
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: returning /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts [general case]
[09:05:19] [DBG] [159] MediaBrowser.Api.Playback.Hls.DynamicHlsService: serving up /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts as it deemed ready
[09:05:19] [DBG] [159] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:19] [DBG] [159] MediaBrowser.Api.Playback.Hls.DynamicHlsService: finished serving /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:19] [DBG] [159] MediaBrowser.Api.ApiEntryPoint: OnTranscodeEndRequest job.ActiveRequestCount=0
[09:05:19] [DBG] [159] MediaBrowser.Api.ApiEntryPoint: Starting kill timer at 60000ms. JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175
[09:05:19] [WRN] [159] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 10.0.0.244. Time (slow): 0:00:03.8420791. http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:19] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: returning /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts [it exists, try 1]
[09:05:19] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Starting transcoding because segmentGap is 443 and max allowed gap is 8. requestedIndex=444
[09:05:19] [DBG] [181] MediaBrowser.Api.ApiEntryPoint: KillTranscodingJob - JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175. Killing transcoding
[09:05:19] [INF] [181] MediaBrowser.Api.ApiEntryPoint: Stopping ffmpeg process with q command for /config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8
[09:05:19] [DBG] [164] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /cache/images/resized-images/4/4ad4fcd8-f4bf-e7b1-07bd-a3360c2a7373.webp
[09:05:20] [DBG] [131] MediaBrowser.Api.Playback.Hls.DynamicHlsService: serving up /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts as it deemed ready
[09:05:20] [DBG] [131] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts
[09:05:20] [DBG] [131] MediaBrowser.Api.Playback.Hls.DynamicHlsService: finished serving /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts
[09:05:20] [DBG] [131] MediaBrowser.Api.ApiEntryPoint: OnTranscodeEndRequest job.ActiveRequestCount=0
[09:05:20] [DBG] [131] MediaBrowser.Api.ApiEntryPoint: Starting kill timer at 60000ms. JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175
[09:05:20] [ERR] [131] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: A task was canceled. URL: http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:20] [DBG] [131] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:20] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Disposing stream resources
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: FFMpeg exited with code 0
[09:05:20] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Deleting partial HLS file /config/transcodes/cc36e0d038097e4f13acb745ad00cf142.ts
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:22:12.000 -c:v hevc_cuvid -resize 3840x2160 -noaccurate_seek -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 444 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"

**FFmpeg Logs**
[09:05:15] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_cuvid -resize 3840x2160 -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Launched ffmpeg process
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Waiting for the creation of /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: File /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts created or transcoding has finished
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: StartFfMpeg() finished successfully

**Stats for Nerds Screenshots**
https://imgur.com/gallery/Rv8RlvU

**Server System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: Ryzen 2700X ( 2vCPU + 8GB RAM, NVIDIA Quadro P620 NVENC/NVDEC )
 - Reverse proxy: HAproxy HTTPS/TLS + local HTTP/8096 access
 - Other hardware notes: Media Mounted via NFS, download/local playback with another player works fine. 
 * cache/local disk: Samsung NVMe 970, NFS RAID10 Ironwolf 4TBs + 10Gig Ethernet
 
**Client System (please complete the following information):**
 - Device: Firefox/Chrome Latest/Chromecast
 - OS: Windows 10/Chomecast Stable, MacO, Android ( all clients )
 - Client: all
 - Browser (if Web client): all
 - Client and Browser Version: all

**Comment by LugMuad** [comment] 2021-01-08 11:57
I have the same problem on Debian with a 1660 super, after some research it seems that "cuvid" is the problem (and should be replaced by "nvdec" (?)). But I don't have the knowledge to check or test (or really understand :) ), just know that Emby seem to have fixed the problem with NVDEC.EX. (https://emby.media/community/index.php?/topic/92672-what-is-nvdecex/)

I tried to compare with command line but i just get "unknown decoder", with "hevc_cuvid" it work and reproduce the error.

Only some media are afected, not all 10bit HEVC.

**Comment by nyanmisaka** [comment] 2021-01-08 12:12
Duplicate of https://github.com/jellyfin/jellyfin/issues/4879
I have had a fix for it but haven't implemented it into jellyfin. You may see it in a 10.7.x backport in the future.

**Comment by agilob** [comment] 2021-01-23 17:15
HI @nyanmisaka I see this error quite often, will the fix make it to 10.7?

**Comment by Bonn93** [comment] 2021-01-24 01:20
@agilob not in RC3 for 10.7, I think @nyanmisaka mentioned this will be in a bugfix release in the 10.7.x release cycle.

**Comment by nyanmisaka** [comment] 2021-01-24 19:55
Will open a PR for it tomorrow if everything in my test goes well.

**Comment by nyanmisaka** [comment] 2021-01-25 19:50
I have fixed this by adding an enhanced NVDEC option in the link above.
Hope it can catch up with the 10.7 release.

**Closed** 2021-02-10 06:24 UTC
