### ISSUE TITLE
Jellyfin 10.6.4-1 won't upgrade via apt on Ubuntu 18.04

### ISSUE THREAD

**Issue by ipkpjersi** [jellyfin/jellyfin#6001] opened 2021-05-07 03:20 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Virtualization: No
 - Jellyfin Version: 10.6.4-1

**To Reproduce**

1. Try apt-dist upgrade jellyfin with 10.6.4-1 installed from the Ubuntu PPA.
2. It won't update.

**Expected behavior**
I expect jellyfin to update to the latest stable version, however it does not work, it does not upgrade and says it is the latest version..

**Screenshots**
![](https://i.imgur.com/tCEnCLS.png)

**Comment by crobibero** [comment] 2021-05-07 04:28
Duplicate of https://github.com/jellyfin/jellyfin/issues/5448.

Please see that issue for the solution.

**Closed by crobibero** 2021-05-07 04:28 UTC
Labels: bug

**Comment by raqmudy** [comment] 2021-11-08 02:17
> Hi @crobibero thank you for the fast response.
> 
> This is not a duplicate issue, apt says I am on 10.6.4-1, not 10.7.x for jellyfin and all sub-packages.
> 
> I literally cannot upgrade them at all, and they do not show as upgradable: ![](https://camo.githubusercontent.com/5e2ab61b005ed37ab4ac41a51bcfbe5a7234731d1cb2ffb4ea70e706e718d211/68747470733a2f2f692e696d6775722e636f6d2f4e6e61316132642e706e67)
> 
> ~Can you please re-open this issue? It is a valid issue.~
> 
> **edit: Please keep this issue closed, I had to re-add the PPA in order to upgrade my jellyfin version. It is now the correct version:** ![](https://camo.githubusercontent.com/7481532c2a895ed27fda88c03f4faa70ef609d3d8521a29d99d5ace16d6948a7/68747470733a2f2f692e696d6775722e636f6d2f65614d6961714b2e706e67)
> 
> ### My issue is now solved.

how you re-add PPA regards
