### ISSUE TITLE
My movies are no longer identified

### ISSUE THREAD

**Issue by Bembix23** [jellyfin/jellyfin#13172] opened 2024-12-07 14:25 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Since this morning, Jellyfin has been unable to identify my new films, and even worse, if I do it manually, after I've found the film, it doesn't make any difference at all. Now all my films are no longer named, it's a mess! If I do an update asking it to detect new files or modifications, or if I ask it to replace missing metadata, it does nothing at all! Am I the only one in this mess? It's possible that the problem is with The Movie DB.

### Reproduction steps

Add a new movie. See if it's identified or not. If not, test to manually identify the movie. Update the movie library. 

### What is the current _bug_ behavior?

Nothing changes, no identification

### What is the expected _correct_ behavior?

The film is identified with TMDB.

### Jellyfin Server version

10.10.0+

### Specify the build version

Release

### Environment

```markdown
- OS: DSM Synology
- Linux Kernel: none
- Virtualization: Container Manager
- Clients:MacOS, Windows, iOS, etc
- Browser:
- FFmpeg Version: 
- Playback Method: 
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
...
Error in The Movie DB
...
```

### FFmpeg logs

```shell

```

**Comment by Exhigh** [comment] 2024-12-07 15:43
This issue was noticed by me as well when trying to to update my collection of Tv-Shows and currently my catalog has no poster images and the shows that got asked to update don't essentially get updated. Found this in the logs multiple of the same error


```
[2024-12-07 17:34:09.707 +02:00] [ERR] [8] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "TheMovieDb"
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2024-11-15 16:00:00 UTC. Path 'videos.results[0].published_at', line 1, position 14618.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
   at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by Bembix23** [comment] 2024-12-07 15:46
> This issue was noticed by me as well when trying to to update my collection of Tv-Shows and currently my catalog has no poster images and the shows that got asked to update don't essentially get updated. Found this in the logs multiple of the same error
> 
> Running Jellyfin 10.10.3 on windows 10 22h2 x64
> ```
> [2024-12-07 17:34:09.707 +02:00] [ERR] [8] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "TheMovieDb"
> Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2024-11-15 16:00:00 UTC. Path 'videos.results[0].published_at', line 1, position 14618.
>    at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
>    at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
>    at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
>    at TMDbLib.Rest.RestResponse`1.GetDataObject()
>    at TMDbLib.Client.TMDbClient.GetTvEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, TvEpisodeMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetEpisodeAsync(Int32 tvShowId, Int32 seasonNumber, Int32 episodeNumber, String displayOrder, String language, String imageLanguages, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
> ```
> 

Thanks for the logs, it's exactly the same !

**Comment by siennaphoenix** [comment] 2024-12-07 15:51
Same log entries here, looks like a breaking change in The Movie Database's API. For anyone having this issue pulling images (actual metadata was/is still working for me just not images)

Under Dashboard > Plugins
Install The TV DB as a metadata provider
In your TV library, configure The TV DB as an option and place it higher than The Movie Database.
Rescan library
Epic success

**Comment by Shadowghost** [comment] 2024-12-07 16:14
Duplicate of #13171

**Closed by Shadowghost** 2024-12-07 16:14 UTC
Labels: bug
