### ISSUE TITLE
Fresh Docker install no longer playing LiveTV from HDHomeRun

### ISSUE THREAD

**Issue by dupuik** [jellyfin/jellyfin#5569] opened 2021-03-19 14:06 UTC
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /usbdrive1:/media:ro

HDHomeRun CONNECT DUO
Model: HDHR5-2US
Device ID: 10612879
Firmware: 20210224

[13:59:17] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for home. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[13:59:17] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, Path: http://10.1.1.127, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[13:59:17] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, No video direct play profiles found for http://10.1.1.127 with codec mpeg2video
[13:59:17] [INF] [49] Emby.Server.Implementations.LiveTv.LiveTvManager: Opening channel stream from Emby, external channel Id: hdhr_2.1
[13:59:17] [INF] [49] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Streaming Channel hdhr_2.1
[13:59:17] [INF] [49] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: GetChannelStream: channel id: hdhr_2.1. stream id: native_b23ebc9442ec90ed5f591ef1683972b1_7c4f5864ee933812617b69a273bc9eaa profile: native
[13:59:17] [INF] [49] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Opening SharedHttpStream Live stream from http://10.1.1.127:5004/auto/v2.1
[13:59:18] [INF] [51] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Beginning SharedHttpStream stream to /config/transcodes/c8ff2bc0ccfa43a5a623aa1b13de3b03.ts
[13:59:18] [INF] [49] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Live stream opened after 403.843ms
[13:59:18] [INF] [49] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Returning mediasource streamId native_b23ebc9442ec90ed5f591ef1683972b1_7c4f5864ee933812617b69a273bc9eaa, mediaSource.Id native_b23ebc9442ec90ed5f591ef1683972b1_7c4f5864ee933812617b69a273bc9eaa, mediaSource.LiveStreamId null
[13:59:18] [INF] [49] Emby.Server.Implementations.Library.MediaSourceManager: Waiting 3000ms before probing the live stream
[13:59:21] [INF] [47] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: /usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 3000000 -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts" -threads 0 -v warning -print_format json -show_streams -show_format
**[13:59:21] [ERR] [43] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The process cannot access the file '/config/transcodes/c8ff2bc0ccfa43a5a623aa1b13de3b03.ts' because it is being used by another process. URL GET /LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts.
[http @ 0x5580d4e61d80] HTTP error 500 Internal Server Error
http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts: Server returned 5XX Server Error reply
[13:59:21] [ERR] [38] Emby.Server.Implementations.Library.MediaSourceManager: Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.**
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LiveStreamHelper.AddMediaInfoWithProbe(MediaSourceInfo mediaSource, Boolean isAudio, String cacheKey, Boolean addProbeDelay, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.OpenLiveStreamInternal(LiveStreamRequest request, CancellationToken cancellationToken)
[13:59:21] [INF] [38] Emby.Server.Implementations.Library.MediaSourceManager: Live stream opened: {"Protocol":"Http","Id":"native_b23ebc9442ec90ed5f591ef1683972b1_7c4f5864ee933812617b69a273bc9eaa","Path":"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts","Type":"Default","Container":"ts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_b23ebc9442ec90ed5f591ef1683972b1_7c4f5864ee933812617b69a273bc9eaa","BufferMs":0,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mpeg2video","VideoRange":"SDR","DisplayTitle":"1080i MPEG2VIDEO SDR","IsInterlaced":true,"BitRate":15000000,"IsDefault":false,"IsForced":false,"Height":1080,"Width":1920,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"Codec":"AC3","DisplayTitle":"Dolby Digital","IsInterlaced":false,"BitRate":448000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"MediaAttachments":[],"Formats":[],"Bitrate":15448000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}
[13:59:21] [INF] [38] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for home. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[13:59:21] [INF] [38] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, Path: http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[13:59:21] [INF] [38] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, No video direct play profiles found for http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts with codec mpeg2video
[13:59:21] [INF] [38] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, Path: http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[13:59:21] [INF] [38] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile, No video direct play profiles found for http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts with codec mpeg2video
[13:59:21] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.kjtd.net:8096/Items/cda10c0a8b5c53725d0bb3aa3716cb2f/PlaybackInfo?UserId=7684d9149b35431ba08abecf7b61b1f8&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 to 10.1.1.180 in 0:00:04.3916805 with Status Code 200
[13:59:22] [INF] [49] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -fflags +igndts -f mpegts -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 15000000 -bufsize 30000000 -profile:v:0 high -level 41 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "yadif=0:-1:0,scale=trunc(min(max(iw\,ih*dar)\,min(1920\,1080*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,1080))/2)*2" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 6 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/eeb30ef1eddfc0bf03824922edb80eb9/" -hls_playlist_type event -hls_segment_filename "/config/transcodes/eeb30ef1eddfc0bf03824922edb80eb9%d.ts" -y "/config/transcodes/eeb30ef1eddfc0bf03824922edb80eb9.m3u8"
**[13:59:22] [ERR] [39] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The process cannot access the file '/config/transcodes/c8ff2bc0ccfa43a5a623aa1b13de3b03.ts' because it is being used by another process. URL GET /LiveTv/LiveStreamFiles/c8ff2bc0ccfa43a5a623aa1b13de3b03/stream.ts.
[13:59:22] [ERR] [44] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1**

**Comment by crobibero** [comment] 2021-03-19 14:17
Please use the search function(s).

https://github.com/jellyfin/jellyfin/issues?q=is%3Aissue+sort%3Aupdated-desc+live+tv+is%3Aclosed

Duplicate of:
#5491
#5427
#5438
#5513
#5531
#5568

Fixed by: #5444

**Closed by crobibero** 2021-03-19 14:17 UTC

**Comment by dupuik** [comment] 2021-03-19 14:24
> Please use the search function(s).

Thank you for showing me the resolution!  Apologies.  My first time logging an issue in any GitHub ever.  I'm just a home user (i.e. I'm not a developer and don't work in IT).
