### ISSUE TITLE
Trakt import not working in nightly-20190820

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1657] opened 2019-08-21 15:19 UTC
**Describe the bug**

**To Reproduce**

1. Go to Scheduled Tasks
2. Click on Import Playstates from Trakt.tv
4. See error in logs

**Expected behavior**

Watched status should be imported.

**Logs**

```jellyfin        | 2019-08-21T15:07:59.050443370Z [10:07:59] [INF] Import playstates from Trakt.tv Completed after 0 minute(s) and 0 seconds
jellyfin        | 2019-08-21T15:07:59.082293263Z [10:07:59] [INF] ExecuteQueuedTasks
jellyfin        | 2019-08-21T15:12:55.526806200Z [10:12:55] [INF] Executing Import playstates from Trakt.tv
jellyfin        | 2019-08-21T15:12:55.660124711Z [10:12:55] [ERR] Exception handled
jellyfin        | 2019-08-21T15:12:55.660399899Z System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_LogRequest(Boolean)'.
jellyfin        | 2019-08-21T15:12:55.660516432Z    at Trakt.Api.TraktApi.GetHttpRequestOptions()
jellyfin        | 2019-08-21T15:12:55.660594634Z    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.660665796Z    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.660730041Z    at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
jellyfin        | 2019-08-21T15:12:55.685208366Z [10:12:55] [ERR] Error syncing trakt data for user Heidi
jellyfin        | 2019-08-21T15:12:55.685479054Z System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_LogRequest(Boolean)'.
jellyfin        | 2019-08-21T15:12:55.685587379Z    at Trakt.Api.TraktApi.GetHttpRequestOptions()
jellyfin        | 2019-08-21T15:12:55.685660374Z    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.685727869Z    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.685925229Z    at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
jellyfin        | 2019-08-21T15:12:55.686027638Z    at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
jellyfin        | 2019-08-21T15:12:55.711074878Z [10:12:55] [ERR] Exception handled
jellyfin        | 2019-08-21T15:12:55.711316902Z System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_LogRequest(Boolean)'.
jellyfin        | 2019-08-21T15:12:55.711422269Z    at Trakt.Api.TraktApi.GetHttpRequestOptions()
jellyfin        | 2019-08-21T15:12:55.711494805Z    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.711556509Z    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
jellyfin        | 2019-08-21T15:12:55.711622087Z    at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: nightly-20190820
 - Reverse proxy: no

**Additional context**

Also, trakt plugin settings came up with an empty user list first. Then when I tried again all users were listed, in addition to 'root' in the user dropdown.

**Comment by anthonylavado** [comment] 2019-08-26 04:15
Just for posterity, as I think we discussed this in chat, a lot of plugins are expected to break as of some changes to HTTP requests and the like in the latest nightlies.

At the very least, this is a signal to us that we must update Trakt before we release whatever will be 10.4.

**Comment by joshuaboniface** [comment] 2019-09-29 16:39
This is confirmed to still be a problem. I'm going to release a fresh set of NuGet packages tonight to see if we can get it fixed.

**Comment by joshuaboniface** [comment] 2019-09-30 05:44
Should be fixed in the latest nightly + Trakt v7.

**Closed by joshuaboniface** 2019-09-30 05:44 UTC
Labels: bug

**Comment by ddurdle** [comment] 2019-10-04 22:47
completely broken now, I can't enroll a user.  The dropdown is broken.  Latest 7.0 and latest nightly.

![image](https://user-images.githubusercontent.com/851508/66244648-7104ae00-e6d7-11e9-8591-71aa9c0ee76d.png)

**Comment by anthonylavado** [comment] 2019-10-04 23:49
@ddurdle What OS are you using?
Are there any errors in the browser console or logs?

**Comment by oddstr13** [comment] 2019-10-04 23:50
It's working just fine for me with Jellyfin nightlies 20191004 on Ubuntu, using Firefox as my browser.

Are you certain that you are indeed running the latest nightly?
If you are using docker with the `nightly` tag, you have to make sure you actually download the new version rather than just restarting an old cached version;
`docker pull jellyfin/jellyfin:nightly`.

I was seeing the missing dropdown before jellyfin/jellyfin-web#490 was merged.

**Comment by ddurdle** [comment] 2019-10-05 02:24
I tried it again and now it works.  The difference is that I closed the chrome down completely since last tested, so it is possible the dropdown was cached from before I did the upgrade.    The trakt is working now.

Using docker, did a docker pull of the latest nightly, then dropped and recreated the docker to ensure the latest version.
