### ISSUE TITLE
Loosing identified films when library gets rescanned and NFS unstability

### ISSUE THREAD

**Issue by arthurlutz** [jellyfin/jellyfin#4123] opened 2020-09-12 10:09 UTC
**Describe the bug**

After initial import of the library, I spent some time using the "Identify" action in the interface to correct or add proper metadata to some films and series. It seems the Library is "reset" when NFS mount is not properly mounted at reboot. In that case, jellyfin seems to keep the "watched" status but not the updated metadata. 

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: no
 - Clients: n/a
 - Browser: n/a
 - Jellyfin Version: 10.5.5-1
 - Playback: n/a
 - Installed Plugins: n/a
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: n/a
 - Storage: NFS

**To Reproduce**

1. mount NFS library
2. Import
3. Identify a film that was not automatically found  on initial scan
3. umount NFS
4. restart jellyfin
5. mount NFS
6. restart jellyfin

**Expected behavior**

Maybe when the jellyfin detects a radical change in the number of files it could "freeze" the scan and not remove the items. Waiting for the situtation to be fixed ?

**Comment by Shadowghost** [comment] 2020-09-12 13:30
Jellyfin expects stable media directories. It can't know if the removal was intentional or not (and IMHO that's not something it should be responsible for in the first place). You can disable the automatic scans to prevent accidental deletion of you NFS isn't stable.

**Comment by deyarmond** [comment] 2020-09-13 13:09
I'm not sure if this relates to what I'm experiencing so I'll comment here. My external hard drive doesn't seem to be mounting or turning on when using Jellyfin as a server. I think I can pinpoint the issue to jf because I popped in my SD card image on emby and it fired up right away. I may try on old JF backup to see if there was something that changed overnight that broke this

**Comment by arthurlutz** [comment] 2021-01-14 07:59
I'm still affected by this bug.

**Comment by cvium** [comment] 2021-04-09 21:45
This is really a feature request, but it's also unexpected behaviour...

**Comment by sevenrats** [comment] 2023-10-05 04:01
duplicate of #1714

**Closed by sevenrats** 2023-10-05 04:01 UTC
Labels: bug, confirmed
