### ISSUE TITLE
One specific video does not play and player will crash/get kicked back to home screen after several seconds of black sceen

### ISSUE THREAD

**Issue by eltiel** [jellyfin/jellyfin#2406] opened 2020-02-14 02:59 UTC
Have got several hundred other video files and have observed this problem only with this specific file. This would refuse to play and kick/crash the player back to the Home screen after several seconds of black screen. Successfully played this video directly via Kodi.
Edit: The above happens without any error messages - so I have no idea what went wrong.

**Media Info of the file**
[mediainfo.txt](https://github.com/jellyfin/jellyfin/files/4202461/mediainfo.txt)

**Logs**
[log_20200214.log](https://github.com/jellyfin/jellyfin/files/4202468/log_20200214.log)

**FFmpeg Logs**
[ffmpeg-transcode-0df86c65-ea4a-456a-b946-e35c2cfa6ca0.txt](https://github.com/jellyfin/jellyfin/files/4202469/ffmpeg-transcode-0df86c65-ea4a-456a-b946-e35c2cfa6ca0.txt)

**Server System:**
 - OS: Docker on Synology DS218+
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: VAAPI on Synology DS218+
 - Reverse proxy: nginx
 - Other hardware notes: N/A - media is stored locally
 
**Client System (please complete the following information):**
 - Device: Pocophone F1
 - OS: Android
 - Client: Android
 - Client Version: 907?

**Comment by anthonylavado** [comment] 2020-02-14 05:08
Whoops wrong button.

Does it kick back when playing through the web browser, Android app, browser on Android...?

**Comment by eltiel** [comment] 2020-02-14 05:23
At the moment I'm only able to test with mobile browsers. Will test further with desktop browsers when I can. 

![Screenshot_2020-02-14-13-13-41-585_org mozilla fenix nightly](https://user-images.githubusercontent.com/11868456/74503727-c5912300-4f2c-11ea-9278-f4a8ad636f74.jpg)
Firefox Preview on Android gets this message for about 3 secs, then the screen turns blank.

![IMG_20200214_131635](https://user-images.githubusercontent.com/11868456/74503741-dc377a00-4f2c-11ea-8297-fb404d1ddbce.jpg)
In Chrome Android, it just gets stuck in the player and nothing happens.

**Comment by eltiel** [comment] 2020-02-14 05:53
I get this on Firefox on Windows 7:
![Capture](https://user-images.githubusercontent.com/11868456/74505097-2de20380-4f31-11ea-8d48-579f5e036a48.JPG)

Strange because I have plenty other 1080p HEVC files that play just fine.

**Comment by nyanmisaka** [comment] 2020-02-14 10:35
Duplicate of https://github.com/jellyfin/jellyfin/issues/2390

**Comment by JustAMan** [comment] 2020-02-14 11:29
Server part is a duplicate I'm sure, but missing error message on mobile is not... @eltiel can you create a separate ticket on https://github.com/jellyfin/jellyfin-web ?

**Comment by eltiel** [comment] 2020-02-14 17:24
> Server part is a duplicate I'm sure, but missing error message on mobile is not... @eltiel can you create a separate ticket on https://github.com/jellyfin/jellyfin-web ?

Ok, I'll do that - thanks

**Closed** 2020-02-17 03:22 UTC
