### ISSUE TITLE
Cannot install plugin on docker image

### ISSUE THREAD

**Issue by voarsh2** [jellyfin/jellyfin#4745] opened 2020-12-09 02:10 UTC
**Describe the bug**

Trying to install any plugin results in an endless loading icon.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: LXC and Docker
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.4

**To Reproduce**

1. Go to admin
2. Click on plugins and install a plugin

**Expected behavior**

To install selected plugin 

**Logs**

[02:07:39] [WRN] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 192.168.100.172. Time (slow): 0:00:05.8747404. http://192.168.100.131:8098/Packages/Auto Organize?AssemblyGuid=70b7b43b-471b-4159-b4be-56750c795499
[02:07:44] [ERR] [39] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.100.131:8098/Packages/Installed/Auto Organize?AssemblyGuid=70b7b43b-471b-4159-b4be-56750c795499&version=9.0.0.0
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Auto Organize
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[02:07:45] [WRN] [39] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 404 to 192.168.100.172. Time (slow): 0:00:01.274263. http://192.168.100.131:8098/Packages/Installed/Auto Organize?AssemblyGuid=70b7b43b-471b-4159-b4be-56750c795499&version=9.0.0.0

**Screenshots**

**Additional context**

**Comment by crobibero** [comment] 2020-12-09 02:35
Duplicate of https://github.com/jellyfin/jellyfin/issues/4727
Select a lower plugin version.

**Closed by crobibero** 2020-12-09 02:35 UTC
Labels: bug
