### ISSUE TITLE
Unable to enter movie details page

### ISSUE THREAD

**Issue by colaKot** [jellyfin/jellyfin#5127] opened 2021-01-29 12:03 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS:Docker
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: Browser&Android
 - Browser:  Chrome 88
 - Jellyfin Version:10.7.0-rc1

**Logs**

[2021-01-29 11:53:12.416 +00:00] [ERR] [65] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/93324e06855549f8854da1c77d9adc41/Items/4ffe96951f2edc5de0f14dd61b4b5113".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.AttachPeople(BaseItemDto dto, BaseItem item)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method932(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2021-01-29 11:53:24.518 +00:00] [INF] [63] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.199" closed
[2021-01-29 11:53:25.413 +00:00] [INF] [63] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.2.199" request

**Screenshots**

**Additional context**

**Comment by crobibero** [comment] 2021-01-29 12:31
Probably fixed by https://github.com/jellyfin/jellyfin/pull/5105

**Comment by cvium** [comment] 2021-02-03 08:02
> 
> 
> Probably fixed by #5105

I don't think so. @colaKot We need a bit more information like

1. Which movie is it?
2. Which metadata providers do you have enabled?
3. Does it only happen to the one movie?
4. etc.....

A stack trace is not a lot to go on... You didn't even include any steps to reproduce.

**Comment by whiteowl3** [comment] 2021-07-20 00:10
I had this issue on several directories today.
The cause *appears* to have been scanning in the metadata while the directory belonged to root:root.  correcting the read permissions and scanning with "replace all..." fixed the issue in my case.

**Comment by HybridSarcasm** [comment] 2023-10-10 15:45
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Bond-009** [comment] 2023-10-10 17:15
Closing as stale

**Closed by Bond-009** 2023-10-10 17:15 UTC
Labels: bug, question
