### ISSUE TITLE
Slow initial scan - slow http response warnings

### ISSUE THREAD

**Issue by Altycoder** [jellyfin/jellyfin#9807] opened 2023-05-24 13:43 UTC
### Please describe your bug

Recently spun up Jellyfin in docker on top of an Arch Linux host with a coffee lake i5 CPU and 32GB, I have disabled PMS for the time being.  Initial scan of a small library of 200 TV shows and 100 films is taking hours and at this rate will take more than 6-8 hours which seems excessive.

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.1.29-1-lts
- Virtualization: docker
- Clients: Chrome, Android, Android TV
- Browser: Chrome
- FFmpeg Version: 
- Playback Method: not got that far yet!
- Hardware Acceleration: QSV
- GPU Model: i5-9600T
- Plugins: thetvdb
- Reverse Proxy: nginx
- Base URL: <redacted>
- Networking: gigabit lan / 330/50 g.fast WAN
- Storage: sata ssd for host OS / btrfs raid1 (6xSATA disks with 40% free space) for media storage
```

### Jellyfin logs

```shell
[13:32:03] [WRN] [89] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/Sessions/Capabilities/Full to 192.168.1.2 in 0:00:00.5133464 with Status Code 204
[13:32:03] [INF] [92] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.2 request
[13:32:04] [WRN] [92] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/LiveTv/Programs/Recommended?userId=a63d016e6fd542478aa56c88279859e5&IsAiring=true&limit=1&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio to 192.168.1.2 in 0:00:00.9371547 with Status Code 200
[13:32:06] [WRN] [108] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/Users/a63d016e6fd542478aa56c88279859e5/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book to 192.168.1.2 in 0:00:01.0142944 with Status Code 200
[13:32:06] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/Users/a63d016e6fd542478aa56c88279859e5/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=6f25559632c2aca7578b4fdc30acb587 to 192.168.1.2 in 0:00:01.4135242 with Status Code 200
[13:32:06] [WRN] [69] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/Users/a63d016e6fd542478aa56c88279859e5/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video to 192.168.1.2 in 0:00:01.4499214 with Status Code 200
[13:32:24] [WRN] [89] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.9:8096/Users/a63d016e6fd542478aa56c88279859e5/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=a51ded3f260d408bc0fdf3785edfbf02 to 192.168.1.2 in 0:00:19.068753 with Status Code 200
[13:32:34] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/T/Tom Kenny/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/T/Tom Kenny/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:35] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/B/Bill Fagerbakke/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/B/Bill Fagerbakke/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:35] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/A/Antonio Banderas/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/A/Antonio Banderas/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:36] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/E/Eric Bauza/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/E/Eric Bauza/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:38] [ERR] [45] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/C/Conan O'Brien/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/C/Conan O'Brien/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:40] [ERR] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/T/Tim Conway/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/T/Tim Conway/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[13:32:40] [ERR] [63] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /config/metadata/People/M/Missi Pyle/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/M/Missi Pyle/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-05-24 16:43
Duplicate of https://github.com/jellyfin/jellyfin/issues/2600

**Closed by crobibero** 2023-05-24 16:43 UTC
Labels: bug
