### ISSUE TITLE
How to set jellyfin scanning level without scanning subfolders

### ISSUE THREAD

**Issue by icandura** [jellyfin/jellyfin#9084] opened 2023-01-13 03:56 UTC
### Please describe your bug

I add a folder to the media library and just want it to scrape the files in the media library directory.
For example, my folder is `/mnt/movie/` , I added it to the media library
But there are other subfolders, such as `/mnt/movie/download` `/mnt/movie/undigested` ,etc.
When scanning the media library, the subfolders will be automatically scanned.
How to set jellyfin scanning level without scanning subfolders?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Debian
- Virtualization:Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devome** [comment] 2023-01-13 07:35
Create a `.ignore` file in subfolders.

**Comment by nielsvanvelzen** [comment] 2023-01-13 08:05
Closing the issue since this is not a bug and is answered.

**Closed by nielsvanvelzen** 2023-01-13 08:05 UTC
Labels: bug
