### ISSUE TITLE
[Issue]: Movies and Movies 4k seperate libraries - Play one, tracks time  per version, shows both in "Continue Watching"

### ISSUE THREAD

**Issue by Neoakb** [jellyfin/jellyfin#9386] opened 2023-02-24 03:55 UTC
### Please describe your bug

I have two libraries:
"2. Movies"
"3. Movies 4k"
(numbered to control how they show up in list. ie: 1 tv, 2 movies, 3 movies 4k, 4 tv 4k, 5 music)

I have a 1080 Avenger's Endgame and a 4k version, both in their proper library. 

Steps to reproduce:
1. Watch 4k version to about 10 mins in. Don't view 1080 version.
2. go to jfin main page
3. 4k version shows 10 mins played and also shows 1080 version, but no play time recorded.
3.5: you can watch either one and it will properly track the time played.
4. mark either version as watched
5. Both versions disappear from "Continue Watching"
5.5: Play the version that wasn't marked as watch, they both show up again, but the one you previously marked as watched will still show the marked as watched (see screenshot below)

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Ubuntu 22.04
- Virtualization: Docker
- Clients: Roku (Jfin Dev compiled 02.23.23@2200 EST)
- Browser:
- FFmpeg Version: 5.1.2
- Playback Method: Transcoded audio for 4k, Direct Play for 1080
- Hardware Acceleration: VAAPI (AMD GPU)
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: Local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/6175742/221087917-f0410d17-d163-4d9f-9682-e85685e22de7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-02-26 16:52
Duplicate of https://github.com/jellyfin/jellyfin/issues/7429

**Closed by crobibero** 2023-02-26 16:52 UTC
Labels: bug
