### ISSUE TITLE
[Issue]: Singles directly under artist folder get merged into one album

### ISSUE THREAD

**Issue by leetfin** [jellyfin/jellyfin#8647] opened 2022-10-28 23:48 UTC
### Please describe your bug

When an artist has multiple singles directly under their name folder, songs are incorrectly merged into a large album despite being properly tagged. In the attached screenshot, all four tracks are separate singles that should not be merged together.

This issue occurs on an entirely new library relying solely on local metadata, which I have ensured is correct.

I am unsure what logs are relevant, if any - so please let me know if there are any logs that would be helpful for this issue.

Thanks!

Seems related/similar to:
https://github.com/jellyfin/jellyfin/issues/3169
https://github.com/jellyfin/jellyfin/issues/6694
https://github.com/jellyfin/jellyfin/issues/5172
https://github.com/jellyfin/jellyfin/pull/4968

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows
- Clients: Browser
- Browser: Firefox 104+
- FFmpeg Version: Unsure, whatever's bundled with Jellyfin 10.8.5
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/36166244/198751067-ae383fbf-2c2e-49ef-a4da-c038f7a6b75e.png)
![image](https://user-images.githubusercontent.com/36166244/198751286-4e762bd2-50e1-40e6-a97c-fff61247c7ba.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment] 2022-10-29 05:48
It's an unsupported file structure. You'd need to put the singles into their own album directories.

**Comment by leetfin** [comment] 2022-10-29 14:52
They're all properly tagged and this structure is more convenient than foldering every single, plus it's supported by other media libraries such as Plex. I'd like to leave this issue open in hopes it will become supported.

**Comment by cvium** [comment] 2022-10-29 15:09
We don't use GitHub issues for feature requests. We use [Fider](https://features.jellyfin.org)

**Comment by leetfin** [comment] 2022-10-29 15:30
It seems like a bug to me, but I've gone and upvoted the most similar post there.
https://features.jellyfin.org/posts/1634/add-support-for-one-single-folder-structure-for-music

**Comment by cvium** [comment] 2022-10-29 15:37
I don't disagree but it has worked like this for years. At this point it's less of a bug and more of a poor design choice. Making it work also requires a significant rewrite.

**Comment by leetfin** [comment] 2023-02-28 02:59
Still an issue, unfortunately :(

**Comment by leetfin** [comment] 2023-07-06 00:46
bonk

**Comment by chekovma** [comment] 2023-10-16 05:48
The documentation says:
"You can also separate your music into artist folders or with no folder structure at all."
but if you do the "no folder structure at all" files that are not tagged with an album do not show up under an artist when that artist is clicked.   So that seems like a bug.
This should also be seen as a bug because the action of "viewing" an artists yields a different result than "playing" an artist.  If you click on an artist, only songs organized into albums show up and all other songs are not listed.  but if you then hit play, all songs by the artist will be queued and one of them will start playing.  This happens even if none of the artist's songs are contained in any album.  Clicking on an artist should list all songs by that artist.

**Comment by chekovma** [comment] 2023-10-16 05:49
Also, forcing all songs into albums makes no sense from the perspective of the real world.  Some songs are only released as singles, some songs are bootlegs, some songs are alternate takes.

**Comment by Shadowghost** [comment] 2023-10-16 06:05
As already said before: It's not like we disagree but the current design of how music is recognized and grouped and the requirements of the scanner are just what they are: quite strict and inflexible. Changing it in a way that this works as you imagine it right now would require quite a lot of changes and testing, so this is not a bug in the sense that this is unwanted behaviour code-wise but a feature request.

The playing back everything from an artist vs what is shown I'd consider a bug (question is if this is just frontend or backend too) which is independent of the one described by the scenario by the OP.

**Comment by chekovma** [comment] 2023-10-17 06:40
multiple frontends yielded the same results:  jellyfin web, jellyfin android app, findroid, kodi with jellyfin live sync.  
since the functionality of "play" is what I'd actually want it'd be great if the functionality of "show" just listed all songs by an artist [optionally] without adding an extra click through albums

**Comment by felix920506** [comment] 2023-12-20 01:29
Closing as duplicate of #6694

**Closed** 2023-12-20 01:29 UTC
Labels: bug
