### ISSUE TITLE
[Issue]: Android TV Screensaver Does Not Play When Media is Paused

### ISSUE THREAD

**Issue by lhhel9l3** [jellyfin/jellyfin#9518] opened 2023-03-20 06:35 UTC
### Please describe your bug

If a video is paused in Jellyfin, it will leave the image on screen forever and the Android TV screensaver will not play.

In any other app (netflix, HBO Max, Amazon Prime), if a video is left paused, after some period of time the screensaver will play. This is needed to prevent burn-in of the image.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Android TV
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment] 2023-03-20 07:56
Duplicate of jellyfin/jellyfin-androidtv#2225

**Closed by nielsvanvelzen** 2023-03-20 07:56 UTC
Labels: bug
