### ISSUE TITLE
TV Metadata not filling out again

### ISSUE THREAD

**Issue by undead9786** [jellyfin/jellyfin#5566] opened 2021-03-18 20:37 UTC
Same issue as before with the released version of Jellyfin 1.7.0.
https://github.com/jellyfin/jellyfin-plugin-tvdb/issues/22
Anything new put in does not have metadata automatically filled in.
Using TheTVDB v3.0.0.0

**Comment by tonyfinn** [comment] 2021-03-19 00:10
Have you entered an API key in your configuration for TheTVDB plugin? TheTVDB now requires a paid subscription to access their metadata. Note this change was made by TheTVDB, not the Jellyfin developers. They may apply quotas or turn off the old jellyfin API key at their leisure.

If you don't want to pay TheTVDB, you can remove the TheTVDB plugin and enable TheMovieDB for your library instead. Despite the name, it also covers the TV shows.

**Comment by undead9786** [comment] 2021-03-19 01:20
Really, did they just change it? Was working at least a few weeks ago.
I changed all the metadata to look at TheMovieDB and refreshed but didn't work and then tried The Open Movie Database and tried and same thing.
Uninstalled TheTVdb plugin (took a few restarts of jellyfin for it to take) and still an issue.

**Comment by Motophan** [comment] 2021-03-19 09:28
It works for me with my api key.

**Comment by r0arkin** [comment] 2021-03-19 15:23
I'm seeing the same exact issue and I have TVMaze set as the indexer.

In this you can see that it didn't even fully tag In The Dark. I even gave it the IMDB id which Jf found but didn't do anything with.
![image](https://user-images.githubusercontent.com/46236585/111803089-f3613d80-888b-11eb-9faa-4d9c9e45c188.png)

This one, 1. the filenames aren't being matched with the tv show and 2. metadata / images (cover art) aren't showing up for the episodes either.

**Comment by undead9786** [comment] 2021-03-19 20:29
Oh jeez, after more testing on my end it was just an issue with bad timing and jellyfin picking the wrong Vikings to pull metadata from.
When I updated to the latest release that was the same time I pulled in new Viking episodes so I just automatically thought the issue was back.
I tested by importing other shows and it was working fine but not Vikings so I did an identify on Vikings, found ANOTHER Vikings that was same year as this one and when I picked that one everything fixed itself.

**Comment by theg00s3** [comment] 2021-03-22 03:23
I'm seeing this issue for multiple shows as well

**Comment by ThePeoplesBards** [comment] 2021-03-23 03:37
> Really, did they just change it? Was working at least a few weeks ago.
> I changed all the metadata to look at TheMovieDB and refreshed but didn't work and then tried The Open Movie Database and tried and same thing.
> Uninstalled TheTVdb plugin (took a few restarts of jellyfin for it to take) and still an issue.

Do you use underscores in your naming path? I noticed TMDB does not support searching with "_" so none of my files are found by TMDB as I do not use spaces in file names. This  could be the cause #5583

**Comment by undead9786** [comment] 2021-03-23 15:48
> > Really, did they just change it? Was working at least a few weeks ago.
> > I changed all the metadata to look at TheMovieDB and refreshed but didn't work and then tried The Open Movie Database and tried and same thing.
> > Uninstalled TheTVdb plugin (took a few restarts of jellyfin for it to take) and still an issue.
> 
> Do you use underscores in your naming path? I noticed TMDB does not support searching with "_" so none of my files are found by TMDB as I do not use spaces in file names. This could be the cause #5583

I do not use underscores, I use spaces. Maybe replace underscores with periods if you do not want to use spaces?

**Comment by ThePeoplesBards** [comment] 2021-03-23 17:42
> > > Really, did they just change it? Was working at least a few weeks ago.
> > > I changed all the metadata to look at TheMovieDB and refreshed but didn't work and then tried The Open Movie Database and tried and same thing.
> > > Uninstalled TheTVdb plugin (took a few restarts of jellyfin for it to take) and still an issue.
> > 
> > 
> > Do you use underscores in your naming path? I noticed TMDB does not support searching with "_" so none of my files are found by TMDB as I do not use spaces in file names. This could be the cause #5583
> 
> I do not use underscores, I use spaces. Maybe replace underscores with periods if you do not want to use spaces?

Good shout, I just tried and unfortunately TMDB doesnt support "." in names either. Thanks for the idea though.

**Comment by cvium** [comment] 2021-04-11 14:36
10.7.2 fixes the tmdb naming issues. Closing this as the OP said it was bad timing

**Closed** 2021-04-11 14:36 UTC
