### ISSUE TITLE
[10.10.3] Subtiltes in external player no longer work

### ISSUE THREAD

**Issue by reyaz006** [jellyfin/jellyfin#13275] opened 2024-12-23 04:00 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Using Jellyfin on Unraid, and MX player on Chromecast.

Since upgrading to 10.10.3, MX player doesn't seem to load any subtitles, whether they are in .ASS or .SRT format. It's like Jellyfin transfers the access to the video file, but not to any subtitles file.

### Reproduction steps

1. Watch a video with subtitles normally. Subtitles work.
2. Switch to External playback.
3. Try watching the same video.

### What is the current _bug_ behavior?

Subtitles don't display.

### What is the expected _correct_ behavior?

Subtitles should display.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Unraid 6.12.13
- Linux Kernel: 6.1.106-Unraid
- Virtualization: Docker
- Clients: Chromecast
- Browser: none
- FFmpeg Version: unrelated
- Playback Method: External player
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
Related logs not found.
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment] 2024-12-23 04:03
Duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/4310

**Closed** 2024-12-23 04:03 UTC
Labels: bug
