### ISSUE TITLE
[Issue]: Always defaults to English subtitles

### ISSUE THREAD

**Issue by LinAGKar** [jellyfin/jellyfin#8251] opened 2022-08-12 19:56 UTC
### Please describe your bug

Even if you have set another language as default in the subtitle settings, Jellyfin always default to English subtitles.

### Jellyfin Version

10.8.4

### Environment

```markdown
- OS: OpenSUSE
- Virtualization: Docker
- Clients: Web, Android, Chromecast
- Browser: Firefox 103
- FFmpeg Version: 5.0.1-Jellyfin
- Playback Method: DirectPlay
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Logic-gate** [comment] 2022-08-13 07:45
That's odd. I can't reproduce on 10.8.3. Could have been fixed in later versions.

**Comment by HavermansStef** [comment] 2022-08-14 11:54
I also can't reproduce this on 10.8.4. Can you try updating to 10.8.4 and confirming whether the issue is still present?

**Comment by LinAGKar** [comment] 2022-08-14 12:17
I already am on 10.8.0, though that wasn't in the drop down, sorry.

**Comment by LinAGKar** [comment] 2022-08-14 12:36
![Screenshot_20220814_143259](https://user-images.githubusercontent.com/3390621/184537135-8ed3fd96-8027-4f3c-a4b8-0fdc204d62c6.png)
![Screenshot_20220814_143345](https://user-images.githubusercontent.com/3390621/184537136-a1847795-96f3-4916-8f2d-b6ff84d11c8b.png)

**Comment by zeroquinc** [comment] 2022-08-17 12:11
From my understanding it's always in alphabetical order. For me it's always the Danish subs that gets selected as default, pretty annoying.

**Closed** 2022-10-12 05:22 UTC
Labels: bug
