### ISSUE TITLE
Playback works when clicking season poster, but not when clicking episode image

### ISSUE THREAD

**Issue by llego** [jellyfin/jellyfin#8210] opened 2022-08-05 18:37 UTC
![image](https://user-images.githubusercontent.com/8949656/183139162-228032d9-917e-4855-9636-aab9974538e6.png)
![image](https://user-images.githubusercontent.com/8949656/183139700-51bbc319-2115-4a81-8f0d-63a540d92611.png)

Playback works when clicking season poster on the left , but not when clicking episode image on the right

**Media Info of the file**

Video
Title: 1080p H264 SDR
Codec: H264
AVC: No
Profile: High
Level: 40
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 9649 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 0

Audio
Title: English - Dolby Digital+ - 6 ch - Default
Language: eng
Codec: EAC3
Channels: 6 ch
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

**Logs**
Nothing in the logs.

**FFmpeg Logs**
Nothing in FFmpeg logs.

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: linux server docker container on linux
 - Jellyfin Version: 10.8.3
 - Hardware settings & device: Intel(R) Celeron(R) J4105. I have tried both QSV and VAAPI. 
 - Reverse proxy: nginx (linuxserver swag setup)
 - Other hardware notes: local media
  
**Client System (please complete the following information):**
 - Device: Firefox  Linux Fedora. Same behaviour on Jellyfin app on Android.
 - OS: Fedora and Android
 - Client: Firefox web browser and jellyfin android app
 - Browser (if Web client): firefox
 - Client and Browser Version: Firefox for Fedora 101.0.1

**Comment by Shadowghost** [comment] 2022-08-05 18:40
Duplicate of #8205 should be fixed by #8209. Please reopen if it does not.

**Closed by Shadowghost** 2022-08-05 18:40 UTC

**Comment by llego** [comment] 2022-08-05 18:49
Thanks! This was exactly the issue!
