### ISSUE TITLE
[Issue]: 演员无法自动更新

### ISSUE THREAD

**Issue by cnfjice** [jellyfin/jellyfin#10403] opened 2023-10-14 06:36 UTC
### Please describe your bug

版本：10.8.10
演员图片无法自动下载，进入docker查看People目录，没有演员图片。点击单个演员后，才会开始下载演员图片。
测试：删除People目录，重启jellyfin，刷新媒体库，查看日志发现，有极少部分演员会自动下载到People目录下，大部分没有反应，点击刷新人员也一样没有反应。之前的版本没有这个问题，麻烦作者辛苦检查下原因。谢谢！

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:群晖7.1
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[14:24:29] [INF] [169] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing 刷新人员
[14:24:31] [INF] [162] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[14:24:40] [INF] [169] Emby.Server.Implementations.Library.LibraryManager: People validation complete
[14:24:40] [INF] [169] Emby.Server.Implementations.ScheduledTasks.TaskManager: 刷新人员 Completed after 0 minute(s) and 11 seconds
[14:24:40] [INF] [169] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

### FFmpeg logs

```shell
/videos/2d797d04-b16a-0d69-db38-408fd2ef1713/hls1/main/0.ts

{"Protocol":0,"Id":"2d797d04b16a0d69db38408fd2ef1713","Path":"/media/\u7535\u5F713/\u5C01\u795E\u6768\u622C.(2022).2160p/\u5C01\u795E\u6768\u622C.(2022).2160p.mp4","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":1506622208,"Name":"\u5C01\u795E\u6768\u622C.(2022).2160p","IsRemote":false,"ETag":"c4bd20636201c6adbe17a2d859fe2a00","RunTimeTicks":45860798464,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":"hev1","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"4K HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":2434626,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1632,"Width":3840,"AverageFrameRate":24.948757,"RealFrameRate":25,"Profile":"Main","Type":1,"AspectRatio":"2.35:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":150,"IsAnamorphic":null},{"Codec":"aac","CodecTag":"mp4a","Language":"und","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/44100","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"AAC - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":186744,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":2628165,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/media/电影3/封神杨戬.(2022).2160p/封神杨戬.(2022).2160p.mp4" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset veryfast -look_ahead 0 -b:v 8115420 -maxrate 8115420 -bufsize 16230840 -profile:v:0 high -level 51 -g:v:0 100 -keyint_min:v:0 100 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 4 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a.m3u8"


ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/media/电影3/封神杨戬.(2022).2160p/封神杨戬.(2022).2160p.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
  Duration: 01:16:26.08, start: 0.160000, bitrate: 2628 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 3840x1632, 2434 kb/s, 24.95 fps, 25 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 186 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
Output #0, hls, to '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0(und): Video: h264, qsv(tv, bt709, progressive), 3840x1632, q=2-31, 8115 kb/s, 25 fps, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 8115420/0/8115420 buffer size: 16230840 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 186 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   34 fps=0.0 q=22.0 size=N/A time=00:00:01.67 bitrate=N/A speed=2.67x    
frame=   83 fps= 73 q=11.0 size=N/A time=00:00:03.57 bitrate=N/A speed=3.16x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a0.ts' for writing
frame=  131 fps= 80 q=11.0 size=N/A time=00:00:05.54 bitrate=N/A speed=3.38x    
frame=  183 fps= 85 q=11.0 size=N/A time=00:00:07.59 bitrate=N/A speed=3.54x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a1.ts' for writing
frame=  233 fps= 88 q=12.0 size=N/A time=00:00:09.61 bitrate=N/A speed=3.63x    
frame=  282 fps= 89 q=11.0 size=N/A time=00:00:11.54 bitrate=N/A speed=3.66x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a2.ts' for writing
frame=  330 fps= 90 q=11.0 size=N/A time=00:00:13.46 bitrate=N/A speed=3.69x    
frame=  381 fps= 92 q=17.0 size=N/A time=00:00:15.51 bitrate=N/A speed=3.73x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a3.ts' for writing
frame=  428 fps= 92 q=20.0 size=N/A time=00:00:17.41 bitrate=N/A speed=3.73x    
frame=  477 fps= 92 q=18.0 size=N/A time=00:00:19.34 bitrate=N/A speed=3.75x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a4.ts' for writing
frame=  525 fps= 93 q=14.0 size=N/A time=00:00:21.24 bitrate=N/A speed=3.75x    
frame=  573 fps= 93 q=28.0 size=N/A time=00:00:23.21 bitrate=N/A speed=3.76x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a5.ts' for writing
frame=  619 fps= 93 q=30.0 size=N/A time=00:00:25.05 bitrate=N/A speed=3.75x    
frame=  667 fps= 93 q=28.0 size=N/A time=00:00:26.93 bitrate=N/A speed=3.75x    
[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a6.ts' for writing
frame=  714 fps= 93 q=23.0 size=N/A time=00:00:28.81 bitrate=N/A speed=3.75x    

[q] command received. Exiting.

[hls @ 0x560ed715c140] Opening '/config/transcodes/0d8ee7bd69f2b1da33db5714a0032a3a7.ts' for writing
frame=  733 fps= 93 q=26.0 Lsize=N/A time=00:00:29.28 bitrate=N/A speed=3.72x    
video:28939kB audio:559kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2023-10-14 07:37
Translation: 

Version: 10.8.10

Actor photos won't auto download. There are no actor photos in the "people" folder in docker. Only when clicking on the actor will JF start downloading photos for actors.

Testing: Delete "people" directory, restarting JF, refreshing library, and checking logs, only a minority of actors will auto download to the "people" directory. Most of them do not have any response, stays same after clicking "refresh people". Previous versions didn't have this problem. (Ignoring phrases for politeness as they are irrelevant to the issue and a pain to translate)

OS: Synology DSM 7.1

**Comment by deltonio2** [comment] 2023-10-14 15:46
Seems to be a duplicate of the bug #8103

**Comment by felix920506** [comment] 2023-10-14 20:30
Closing this one as it looks like a duplicate to #8103

**Closed by felix920506** 2023-10-14 20:30 UTC
Labels: bug
