### ISSUE TITLE
[Issue]: 10.9.0 macOS arm64 server fails with segmentation fault

### ISSUE THREAD

**Issue by JFazio13** [jellyfin/jellyfin#8917] opened 2022-12-17 14:43 UTC
### Please describe your bug

The arm64 version of server 10.9.0 for macOS crashes with a segmentation fault every time it's run. The server will be up and running for 5-10 minutes and then crash with the segmentation fault every single time. Running the decompiled server through Terminal with ./jellyfin.

Logs do not show any errors. The issue occurs regardless of any activity on the server, it still crashes even if left dormant.

zsh: segmentation fault  ./jellyfin

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: macOS 13.1
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 5
- Playback Method: N/A
- Hardware Acceleration: None
- Plugins: N/A
- Reverse Proxy: None
- Base URL: none
- Networking: Host
- Storage: local (external HDD)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daullmer** [comment] 2022-12-17 19:12
Just tired the current master version on an M1 Mac and fresh config files. Did nothing with the server and it is's been running since ~45 minutes.

**Comment by JFazio13** [comment] 2022-12-17 20:44
My server is still in the initial scan phase of a photo and video library, it’s possible it’s related to the scan.

**Comment by fhriley** [comment] 2023-01-28 22:11
I can reproduce an exit 100% reliably by doing a tv shows library scan. Just start with no library, add a decent sized tv show library, and scan. Jellyfin will exit after a few seconds. You can then reproduce it easily by bringing it back up, going to dashboard, and doing a "scan all libraries". What's strange is it doesn't look like a crash, but rather a clean exit. Here's a log snippet:

```
[15:04:08] [DBG] [30] MediaBrowser.Providers.TV.EpisodeMetadataService: Running TmdbEpisodeImageProvider for /Volumes/media/tv/The Terror (2018)/Season 02/The Terror (2018) S02E10 - Into the Afterlife [Bluray-1080p Remux AVC TrueHD 5.1 ].mkv
[15:04:08] [DBG] [29] Emby.Server.Implementations.Data.SqliteItemRepository: GetItemList query time (slow): 201.6222ms. Query: select type,data,EndDate,ChannelId,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,OwnerId from TypedBaseItems A where type in ('MediaBrowser.Controller.Entities.TV.Episode','MediaBrowser.Controller.Entities.TV.Season') AND IsVirtualItem=@IsVirtualItem AND SeriesPresentationUniqueKey=@SeriesPresentationUniqueKey ORDER BY SortName ASC
[15:04:08] [DBG] [18] Jellyfin.Drawing.ImageProcessor: Getting image size for item Episode /Users/friley/.local/share/jellyfin/metadata/library/37/375f8cd019c9b6194d8acf62eb8799a5/poster.jpg
The program '[19383] jellyfin.dll' has exited with code 0 (0x0).
```

**Comment by fhriley** [comment] 2023-01-28 22:39
It's [this call](https://github.com/jellyfin/jellyfin/blob/fec23de427fe1c46e4ce1aaf31f1695c90232059/src/Jellyfin.Drawing.Skia/SkiaEncoder.cs#L158). If you replace it with `return string.Empty;`, the scan completes successfully.

**Comment by Bond-009** [comment] 2023-01-28 22:50
@fhriley Can you narrow it down to 1 image and share it here so I can test locally?

**Comment by fhriley** [comment] 2023-01-28 22:54
So from the above log snippet, it crashed on the attached image. I don't know if it will crash on it or if it requires multiple runs through images before crashing, though.

![poster](https://user-images.githubusercontent.com/153649/215294778-693391ea-19ca-45ae-bff1-49ba0940b530.jpg)

Does the attach re-encode the image? Hope not.

**Comment by Bond-009** [comment] 2023-07-07 15:33
Should be fixed in master

**Closed by Bond-009** 2023-07-07 15:33 UTC
Labels: bug, confirmed
