### ISSUE TITLE
[Issue]: Very Slow startup

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin#12048] opened 2024-06-09 15:26 UTC
### Please describe your bug

Jellyfin is running very slow after last upgrade. It is taking more than 30 min to start

### Reproduction Steps

My Jellygin runs on docker. 
After starting the docker container it starts with no error but takes very long for you to be able to use it

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS:ubuntu 24.04
- Linux Kernel:6.8.0-35-generic
- Virtualization:Docker 
- Clients:browser, Mediaplayer, Android TV
- Browser: Chrome, Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:none
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-06-09 15:08:03.332 +00:00] [ERR] [41] MediaBrowser.Providers.Music.AlbumMetadataService: Error in "MusicBrainz"
MetaBrainz.Common.HttpError: releases is not a valid inc parameter for the release resource.
For usage, please see: https://musicbrainz.org/development/mmd
 ---> MetaBrainz.Common.HttpError: HTTP 400 (BadRequest) 'Bad Request'
   at MetaBrainz.Common.HttpUtils.EnsureSuccessfulAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   --- End of inner exception stack trace ---
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`2 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, IReadOnlyDictionary`2 options, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.LookupReleaseAsync(Guid mbid, Include inc, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2024-06-09 15:08:04.753 +00:00] [INF] [11] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.44" request
[2024-06-09 15:08:07.874 +00:00] [INF] [11] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-06-09 15:08:07.878 +00:00] [INF] [11] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Remove to process
[2024-06-09 15:08:07.878 +00:00] [INF] [11] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Add to process
[2024-06-09 15:08:07.879 +00:00] [INF] [11] Trakt.Helpers.LibraryManagerEventsHelper: Processing 1 movies with event type Update
[2024-06-09 15:08:07.880 +00:00] [ERR] [11] Trakt.Helpers.LibraryManagerEventsHelper: Error in OnQueueTimerCallbackInternal
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Trakt.Helpers.LibraryManagerEventsHelper.<>c__DisplayClass9_0.<ProcessQueuedMovieEvents>b__1(Movie lev)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Trakt.Helpers.LibraryManagerEventsHelper.ProcessQueuedMovieEvents(IReadOnlyCollection`1 events, TraktUser traktUser, EventType eventType)
   at Trakt.Helpers.LibraryManagerEventsHelper.OnQueueTimerCallbackInternal()
   at Trakt.Helpers.LibraryManagerEventsHelper.OnQueueTimerCallback(Object state)
[2024-06-09 15:08:16.153 +00:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-06-09 15:08:28.686 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 1 minute(s) and 12 seconds
[2024-06-09 15:08:28.686 +00:00] [ERR] [35] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "/music"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2024-06-09 15:29
Your logs are incomplete. You have not included the beginning which makes it hard to see what was slowing it down

**Comment by alculete** [comment] 2024-06-09 15:57
[log_20240609.log](https://github.com/user-attachments/files/15753194/log_20240609.log)

**Comment by felix920506** [comment] 2024-08-28 00:00
this description sounds very much like a duplicate of https://github.com/jellyfin/jellyfin/issues/11929

**Closed by felix920506** 2024-08-28 00:00 UTC
Labels: bug

**Comment by alculete** [comment] 2024-08-28 05:27
@slimshizn still slow, sometimes it takes even 30 min

**Comment by felix920506** [comment] 2024-08-28 11:47
Well no one else is reporting this issue so if it's not the issue linked above then please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact

**Comment by alculete** [comment] 2024-08-28 12:35
unfortunately I have to jump to plex when this happens, it starts in less than a minute

**Comment by Bond-009** [comment] 2024-08-28 13:41
@alculete Have you tried starting Jellyfin without any plugins installed?

**Comment by gnattu** [comment] 2024-10-12 01:24
If you disable scheduled tasks for startup it should improve if you have slow hardware and large library, especially the `Clean up collections and playlists` one which will run for a long long time.
