### ISSUE TITLE
[Issue]: Roku Missing Genre View for Music

### ISSUE THREAD

**Issue by jwor80** [jellyfin/jellyfin#8464] opened 2022-09-27 21:29 UTC
### Please describe your bug

Running JellyFin 1.5 on a Roku Express.

Steps to Reproduce:
Browse to my Music Library
Click the Options
Select View
Under View I have an option of Default, Artists, or Albums.

If I use these same steps for Movies or TV Shows I have a Genre option listed under the View Menu.
If I use a web browser to view my music I'm able to sort by Genre

### Jellyfin Version

10.8.0

### if other:

10.8.4

### Environment

```markdown
- OS: Windows
- Virtualization: None
- Clients: Roku
- Browser: Chrome
- FFmpeg Version: 10.8.4-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-09-27 21:49
Duplicate of https://github.com/jellyfin/jellyfin-roku/issues/807

**Closed by crobibero** 2022-09-27 21:49 UTC
Labels: bug
