### ISSUE TITLE
TV show episode sample files not ignored and show as duplicate episodes

### ISSUE THREAD

**Issue by BugFixesAndPerformanceImprovements** [jellyfin/jellyfin#5819] opened 2021-04-15 03:15 UTC
**Describe the bug**
Having similarly named sample files in the same folder as an episode of a TV show will have Jellyfin display it as a duplicate of that same episode.

Sort of relevant discussion here: https://www.reddit.com/r/jellyfin/comments/awldea/ignore_smallsample_files/

Reasons for not "just use the correct file management and naming conventions according to the documentation and delete all sample files yourself" would be:
- having hundreds if not thousands of episodes and their sample files which would make such an endeavor unfeasible/impossible
- seeding content through torrents if that is your particular use case (as one comment mentions in the reddit post)

**System (please complete the following information):**
 - OS: Tested on Windows, but behaviour should be the same on all OS's
 - Jellyfin Version: 10.7.1

**To Reproduce**
1. Have a TV show folder and subsequent season folders, eg. season 1, season 2, etc.
2. Have the actual episode file and its sample file in its own folder or within the season folder, eg. 
- `show/season 1/name.s01e01.mkv`, `show/season 1/name.s01e01-sample.mkv`
- `show/season 1/name.s01e01/name.s01e01.mp4`, `show/season 1/name.s01e01/name.s01e01.sample.mp4`
- `.../.../sample-name102.avi` or a variation thereof

**Expected behavior**
A sample file should be ignored for TV shows as well as it is already being done for movies.

**Screenshots**
![2021-04-15_041850 (edited)](https://user-images.githubusercontent.com/58829078/114808594-e3644d00-9da8-11eb-8790-395e4a7458f7.jpg)
![2021-04-15_043840 (edited)](https://user-images.githubusercontent.com/58829078/114808601-e8c19780-9da8-11eb-9a78-927d41564a28.jpg)
<img width="556" alt="2021-04-15_043812" src="https://user-images.githubusercontent.com/58829078/114808606-eb23f180-9da8-11eb-9e2f-a7b42dafb68f.png">

**Comment by BugFixesAndPerformanceImprovements** [comment] 2021-06-03 17:20
Still happening as of version 10.7.5.

**Comment by BugFixesAndPerformanceImprovements** [comment] 2021-11-29 05:46
Still occurring as far as I can tell with the latest Jellyfin 1.8.0-alpha2

**Comment by srcrist** [comment] 2023-10-20 01:02
Closing this issue as it is a duplicate of the correctly filed feature request at https://features.jellyfin.org/posts/254/ignore-should-follow-same-rules-as-plex.

**Closed by srcrist** 2023-10-20 01:02 UTC
Labels: bug
