### ISSUE TITLE
[Issue]: Subtitles are not being scanned

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin#7361] opened 2022-02-27 13:17 UTC
### Please describe your bug

WIth the latest nightly subtitles are no longer being scanned into the database. My directory structure as requested it was working fine from the nightly from 10-15 days ago has stopped working in the last week only. The directory structure as requested

S01E01 - The Youngsters' Craving for Food.en.srt
├── S01E01 - The Youngsters' Craving for Food.mp4
├── S01E01 - The Youngsters' Craving for Food.nfo
├── S01E01 - The Youngsters' Craving for Food.srt
├── S01E01 - The Youngsters' Craving for Food-thumb.jpg
├── S01E02 - Fun-filled Night.en.srt
├── S01E02 - Fun-filled Night.mp4
├── S01E02 - Fun-filled Night.nfo
├── S01E02 - Fun-filled Night.srt
├── S01E02 - Fun-filled Night-thumb.jpg
├── S01E03 - Life is Full of Surprises.en.srt
├── S01E03 - Life is Full of Surprises.mp4
├── S01E03 - Life is Full of Surprises.nfo
├── S01E03 - Life is Full of Surprises.srt
├── S01E03 - Life is Full of Surprises-thumb.jpg
├── S01E04 - The Sound of Firecrackers Brings Forth a New Year.en.srt
├── S01E04 - The Sound of Firecrackers Brings Forth a New Year.mp4
├── S01E04 - The Sound of Firecrackers Brings Forth a New Year.nfo
├── S01E04 - The Sound of Firecrackers Brings Forth a New Year.srt
├── S01E04 - The Sound of Firecrackers Brings Forth a New Year-thumb.jpg
├── S01E05 - Countryside.en.srt
├── S01E05 - Countryside.mp4
├── S01E05 - Countryside.nfo
├── S01E05 - Countryside.srt
├── S01E05 - Countryside-thumb.jpg
├── S01E06 - Desperate Times.en.srt
├── S01E06 - Desperate Times.mp4
├── S01E06 - Desperate Times.nfo
├── S01E06 - Desperate Times.srt
├── S01E06 - Desperate Times-thumb.jpg
├── S01E07 - Get The Taste of Being Worried for The First Time.en.srt
├── S01E07 - Get The Taste of Being Worried for The First Time.mp4
├── S01E07 - Get The Taste of Being Worried for The First Time.nfo
├── S01E07 - Get The Taste of Being Worried for The First Time.srt
├── S01E07 - Get The Taste of Being Worried for The First Time-thumb.jpg
├── S01E08 - I Will Take Care of You.en.srt
├── S01E08 - I Will Take Care of You.mp4
├── S01E08 - I Will Take Care of You.nfo
├── S01E08 - I Will Take Care of You.srt
├── S01E08 - I Will Take Care of You-thumb.jpg
├── S01E09 - The Price of Vanity.en.srt
├── S01E09 - The Price of Vanity.mp4
├── S01E09 - The Price of Vanity.nfo
├── S01E09 - The Price of Vanity.srt
├── S01E09 - The Price of Vanity-thumb.jpg
├── S01E10 - Saying Sorry is Romantic.en.srt
├── S01E10 - Saying Sorry is Romantic.mp4
├── S01E10 - Saying Sorry is Romantic.nfo
├── S01E10 - Saying Sorry is Romantic.srt

### Jellyfin Version

Other

### if other:

10.8 nightly

### Environment

```markdown
- OS: Linux mInt 
- Virtualization:
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment] 2022-02-27 16:23
I can't reproduce this with the exactly same file structure.
Will further look into it if I got an idea where it could fail...

**Comment by GermanCoding** [comment] 2022-03-01 01:25
I have the same issue since PR 7255.

My file structure is rather simple.

```
/data/movies
  -> Example Movie (2021).mp4
  -> Example Movie (2021).English.srt
```

Used to work just fine, but on recent master builds the subtitles disappear from the database after rescanning.

**Comment by crobibero** [comment] 2022-03-01 01:37
> I have the same issue since PR 7255.
> 
> My file structure is rather simple.
> 
> ```
> /data/movies
>   -> Example Movie (2021).mp4
>   -> Example Movie (2021).English.srt
> ```
> 
> Used to work just fine, but on recent master builds the subtitles disappear from the database after rescanning.

This format is no longer supported. You'll need to add a subfolder per movie.

**Comment by GermanCoding** [comment] 2022-03-01 02:00
I tried moving some movies to

```
/data/movies
   /Example Movie (2021)
      -> Example Movie (2021).mp4
      -> Example Movie (2021).English.srt
```

without any success. Still doesn't pick the subtitles up (though it does detect the movie at the new location as expected).

Manually building a version with https://github.com/jellyfin/jellyfin/commit/ce62a4465a19f1f3f6f4b3ff1fdd248f0f2b0dbf reverted made subtitles work again (with both the old and new structure). So it's definetly related.

**Comment by Dnkhatri** [comment] 2022-03-01 03:00
Thanks for confirming that it is a bug and I am not the only one seeing it. Previous scanned subtitles still show normally only new subtitles are not showing so I am thinking its a problem with subtitles being added to the database. I even tried importing subtitles using jellyfin import option and they are not being added.

**Comment by crobibero** [comment] 2022-03-01 03:12
Do you have any errors in your log? 
I just tested subtitle reading with https://github.com/jellyfin/jellyfin/pull/7370 applied and it worked as expected.

```
Movies
├── The Matrix (1999)
│   ├── behind the scenes
│   │   └── bts.mkv
│   ├── The Matrix (1999) - 1080p.English.srt
│   ├── The Matrix (1999) - 1080p.mkv
│   ├── The Matrix (1999) - 720p.mkv
│   ├── The Matrix (1999) -extra.mkv
│   └── trailers
│       └── The Matrix trailer.mkv
├── The Matrix Reloaded (2003) - 1080p.English.srt
└── The Matrix Reloaded (2003) - 1080p.mkv

3 directories, 8 files
```
![image](https://user-images.githubusercontent.com/24963659/156097741-4952de2a-4aa0-4710-9e0c-7dd35f8b640f.png)
![image](https://user-images.githubusercontent.com/24963659/156097774-36c60c3e-bd01-4026-8a15-d0e7aeca4e46.png)

**Comment by GermanCoding** [comment] 2022-03-01 03:36
> Do you have any errors in your log?

Apparently yes. More than a hundred actually. Most of them seem to be triggered by TMDb / TVDB plugins. I think it's unrelated, but going to investigate more tomorrow.

However, buried between all the plugin errors I did find something that looks like it *is* related, because the stack trace contains a function that has changed as part of the problematic PR:

```
[01:52:01] [ERR] [38] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/metadata/library/cc/cc20e45d2d862372b09896321f2f69f0'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFilePaths(String path, String[] extensions, Boolean enableCaseSensitiveExtensions, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFilePaths>b__9_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFilePaths(String path, Boolean clearCache, Boolean sort)
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken can
cellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalSubtitlesAsync(Video video, List`1 currentStreams, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.Fetch(Video video, CancellationToken cancellationToken, MediaInfo mediaInfo, BlurayDiscInfo blurayInfo, MetadataRefreshOptions option
s)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult re
freshResult, CancellationToken cancellationToken)
```

The folder mentioned seems fine to me, and contains automatically fetched posters for a different movie without subtitles.

```
ls config/metadata/library/cc/cc20e45d2d862372b09896321f2f69f0/
backdrop.jpg  logo.png  poster.jpg
```

**Comment by crobibero** [comment] 2022-03-01 04:08
That error is what https://github.com/jellyfin/jellyfin/pull/7370 fixes, so I'm going to assume subtitle scanning will work after that is merged.

**Comment by DearScorpion** [comment] 2022-03-01 13:22
Got the same problem, i've tried with #7370 too but the problem persists.. Just to be clear, it's the external subtitles that it doesn't pick up (.srt), embedded ones do work.

**Comment by crobibero** [comment] 2022-03-01 14:36
> Got the same problem, i've tried with #7370 too but the problem persists.. Just to be clear, it's the external subtitles that it doesn't pick up (.srt), embedded ones do work.

Please provide folder structure and logs, as I cannot replicate the issue.

**Comment by DearScorpion** [comment] 2022-03-01 20:46
![subtitles](https://user-images.githubusercontent.com/42540779/156245358-a1e7e8ba-8c2f-47a8-8b95-fd1df4b66e12.png)
Folder name: "Who Framed Roger Rabbit (1988)"

As you can see it only picks up on the embedded subtitles (Subrip) the External one (SRT) is ignored.

**Comment by nyanmisaka** [comment] 2022-03-03 15:50
Same issue here with movies structure after #7255
External ASS subtitles are missing after a scheduled scanning task.

```
/data/movies
   /Example Movie (2021)
      -> Example Movie (2021).mp4
      -> Example Movie (2021).English.srt
```

**Comment by 1337joe** [comment] 2022-03-03 21:21
The matching logic that ignores symbols for the sake of making the match (so `My.Movie.mkv` will match `My_Movie.srt`) is non-greedy, so for `Example Movie (2021).mp4` it's not counting the `)` as part of the match and therefore the symbol after the match is `)` instead of the `.` it's looking for.

Found a fix, have tests to prove it works (and make it easier to drop in an arbitrary movie/subtitle test case), just need to clean it up for a pull request.

**Closed** 2022-03-05 08:26 UTC
Labels: bug

**Comment by Dnkhatri** [comment] 2022-03-06 07:55
@1337joe is this fix in the latest nightly as I still have the same problem

**Comment by Dnkhatri** [comment] 2022-03-06 08:09
`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.383 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.385 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.387 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.389 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.391 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.392 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.394 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.395 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.397 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.398 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)
[2022-03-06 16:07:54.399 +08:00] [ERR] Error in "FFProbeProvider".HasChanged
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalFiles(Video video, IDirectoryService directoryService, Boolean clearCache)
   at MediaBrowser.Providers.MediaInfo.FFProbeProvider.HasChanged(BaseItem item, IDirectoryService directoryService)
   at MediaBrowser.Providers.Manager.MetadataService`2.HasChanged(BaseItem item, IHasItemChangeMonitor changeMonitor, IDirectoryService directoryService)`

This is the error that I get when I add subtitles and then use update metadata> scan for new and updated files

**Comment by Shadowghost** [comment] 2022-03-06 08:44
The fix is in but we're currently experiencing build failures so the nightlys aren't up to date at the moment. #7406 should fix that.
