### ISSUE TITLE
Seeking broken on AV1 direct playback

### ISSUE THREAD

**Issue by aaruni96** [jellyfin/jellyfin#8851] opened 2022-12-04 15:38 UTC
When direct playing AV1 files from mkv containers, seeking doesn't work as expected. Clicking on a far away timestamp in the seek bar forwards the video to as far as the local cache allows, but not to the timestamp requested. This works as expected when direct playing H264 videos in mp4 container.

**Media Info of the file**
```
Playback Info
Player: Html Video Player
Play method: Direct streaming
Protocol: https
Stream type: Video

Video Info
Player dimensions: 1920x908
Video resolution: 1920x800
Dropped frames: 0
Corrupted frames: 0

Direct Streaming Info
Video codec: AV1 (direct)
Audio codec: OPUS

Original Media Info
Container: webm
Size: 1.8 GiB
Bitrate: 3.3 Mbps
Video codec: AV1 Main
Video bitrate: 2.7 Mbps
Video range type: SDR
Audio codec: AC3
Audio bitrate: 640 kbps
Audio channels: 6
Audio sample rate: 48000 Hz
```

**Server System (please complete the following information):**
 - OS: xubuntu 22.04
 - Jellyfin Version: 10.8.8
 - Hardware settings & device: direct play
 - Reverse proxy: nginx
 
**Client System (please complete the following information):**
 - Device: x68-64 laptop
 - OS: arch-linux
 - Client: firefox
 - Client and Browser Version: jellyfin-web 10.8.8, firfox 107.0.1

**Comment by Simulping** [comment] 2022-12-09 07:07
the content you are trying to stream might be encoded with keyframe filtering 2, this has some issues playing back on certain players.

**Comment by aaruni96** [comment] 2022-12-09 07:22
encoded to av1 using ffmpeg, using whatever is default options on ffmpeg / SvtAv1EncApp .

**Comment by aaruni96** [comment] 2022-12-09 08:07
The encoding parameters are probably not at fault, as opening the file directly in firefox causes no issues.

**Comment by Simulping** [comment] 2022-12-09 13:50
i see.

**Comment by aaruni96** [comment] 2023-01-15 07:27
This appears to be a problem with audio transcoding. The problem does not occur with AV1 video and Opus audio. In the case of AAC audio, the invisible wall which stops seeking appears to be the progress of the audio transcode.

**Comment by ynerant** [comment] 2023-03-03 10:38
I have the same issue using Firefox (Linux). My Jellyfin is running on an Asustor NAS using Docker version 10.8.8. I am trying to play a video encoded in AVI in a WEBM container with an external OPUS or AAC audio track. When playing the original audio track (encoded in VORBIS and included in the video file), the problem is not here, it only occurs when I play an external audio track.

I try to play the same video but encoded with H264 (in a MP4 container), but then I can play any audio track and seek the video wherever I want without any problem.

**Comment by yuckdevchan** [comment] 2023-03-05 14:53
I have the same issue. My media is AV1 in an MKV container. I'm using Firefox on Linux.

Although, when I use the Jellyfin Desktop Player on Linux it seems to work fine - I'm able to seek fine.

**Comment by sortedcord** [comment] 2023-03-10 11:42
I have a similar issue. My media is encoded using av1 (svt) along with opus in a mkv container. Seeking to a far timestamp causes direct playback to stop working and fallbacks to h.264 transcoding.

**Comment by aaruni96** [comment] 2023-07-09 08:40
As of 10.8.10 , the original issue no longer seems to occur, but AV1 direct playback is broken on AAC audio. It transcodes both the video (to H264) and the audio, instead of just the audio.

I'm not sure whether to continue this issue, or start a new one. @Bond-009 ?

**Comment by srcrist** [comment] 2023-10-05 04:24
Original submitter says issue no longer valid in 10.8.10. Closing as resolved.

**Closed by srcrist** 2023-10-05 04:24 UTC
Labels: bug, media playback
