### ISSUE TITLE
[Issue]: User-created playlists are not displayed in music library

### ISSUE THREAD

**Issue by libook** [jellyfin/jellyfin#10374] opened 2023-10-09 08:05 UTC
### Please describe your bug

"Playlists" tab in a music library can not show any user-created playlists.

Steps to Reproduce:
1. Enter a music library from home page.
2. Select a music or a album, click "add to playlist".
3. Create a new playlist, and click "Add".
5. Go to the "Playlists" tab.
7. The playlist just created is **NOT** displayed.
9. Go back to home page.
10. Click "Playlists" on "My Media" part of home page.
11. The playlist just created is displayed.
12. Click "Menu" button at the top left corner to show the main menu.
13. Click "Metadata" page below "Administration" part.
14. Click "Playlists" and expand it.
15. The playlist just created is displayed.

With the "Playlists" tab in the music library, the browser sent a GET request:
```
https://myjellyfin/Users/{my user ID}/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Playlist&Recursive=true&Fields=PrimaryImageAspectRatio,SortName,CanDelete&StartIndex=0&ParentId=28e9960207c978c0d9aaefc8ae2d3a79
```
the response:
```json
{"Items":[],"TotalRecordCount":0,"StartIndex":0}
```

### Jellyfin Version

Other

### if other:

10.8.11

### Environment

```markdown
- OS: Debian 11(official docker image)
- Linux Kernel: 5.10.0-25-amd64
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox 118.0.1 (64 bit), Chrome 117.0.5938.149 (64 bit)
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Anime, AudioDB, Bookshelf, Cover Art Archive, MusicBrainz, OMDb, Open Subtitles, SkinManager, Studio Images, TMDb, TheTVDB, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local(metadata), NFS(media)
```

### Jellyfin logs

```shell
No relevant log output.
```

### Please attach any browser or client logs here

Requesting https://myjellyfin/Users/{my user ID}/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Playlist&Recursive=true&Fields=PrimaryImageAspectRatio%2CSortName%2CCanDelete&StartIndex=0&ParentId=28e9960207c978c0d9aaefc8ae2d3a79 [main.jellyfin.bundle.js:2:791094](https://myjellyfin/web/main.jellyfin.bundle.js?220c32b3ace8dce8d8d0)

Requesting url without automatic networking: https://myjellyfin/DisplayPreferences/usersettings?userId={my user ID}&client=emby [main.jellyfin.bundle.js:2:792171](https://myjellyfin/web/main.jellyfin.bundle.js?220c32b3ace8dce8d8d0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chaphasilor** [comment] 2023-10-29 15:52
this was marked as a duplicate of https://github.com/jellyfin/jellyfin/issues/10272, which has been closed recently

**Closed** 2023-10-29 15:53 UTC
Labels: bug
