### ISSUE TITLE
[Issue]: Show Called Extras is not Added to the Library

### ISSUE THREAD

**Issue by SyphonxZA** [jellyfin/jellyfin#9657] opened 2023-04-19 14:55 UTC
In my TV shows folder I have a show called Extras, the path is `/storage/media/Series/Extras`. The show does not get added to the Shows library when scanning, or even when removing and re-adding the whole library.

When changing the folder name to 'Extras (2005)' it is picked up correctly.

I assume this is due to the folder name being reserved for other purposes?

Perhaps the behaviour in the root folder for series should be to not apply reserved folder name behaviour, or to check in the folder for an NFO file that confirms that this is a show, and not just extra content.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Debian 11
- Virtualization: docker
- GPU Model: none
- Storage: local
```

**Comment by crobibero** [comment] 2023-04-19 15:19
Duplicate of https://github.com/jellyfin/jellyfin/issues/8641

**Closed by crobibero** 2023-04-19 15:19 UTC
Labels: bug
