### ISSUE TITLE
[Issue]: User profile save button allows blank password to be set

### ISSUE THREAD

**Issue by zdzielinski** [jellyfin/jellyfin#10732] opened 2023-12-15 20:05 UTC
### Please describe your bug

When editing profile pictures for various users on my personal server, I had clicked the save button multiple times, thinking it would save the profile image (unbeknownst to me that wasn't necessary, the profile image saves automatically). When doing this, no password was entered into the password fields, and all users on my server had their passwords deleted - allowing for unauthenticated logins. A non blank password check should be implemented to prevent this.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

<img width="917" alt="Screenshot 2023-12-15 at 1 04 37 PM" src="https://github.com/jellyfin/jellyfin/assets/46588571/325b688e-0d22-4f72-aa1f-961db99633b4">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment] 2023-12-17 01:16
duplicate of #9905

**Closed by sevenrats** 2023-12-17 01:16 UTC
Labels: bug
