### ISSUE TITLE
Requesting Images via API with UnplayedCount uses Emby colors

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1240] opened 2019-04-17 02:34 UTC
**Describe the bug**

API generated images with an UnplayedCount uses emby green and not Jellyfin color.

**To Reproduce**

http://localhost:8096/emby/Items/\<seriesID\>/Images/Primary?UnplayedCount=2

**Expected behavior**

Circled number should use Jellyfin color.

**Screenshots**

![Primary](https://user-images.githubusercontent.com/991618/56256657-407c7980-608f-11e9-83b5-b4d9b120a7b3.jpg)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.2.2

**Comment by thornbill** [comment] 2019-04-17 15:14
Well the good news is the color was fixed in #1043 which will be present in Jellyfin 10.3.0.

The bad news is when I verified this on 10.3.1-RC1 I noticed the count is not displaying in the generated image.

![mythbusters](https://user-images.githubusercontent.com/3450688/56299357-e10b8180-6101-11e9-8452-9129b403d600.png)

**Comment by SenorSmartyPants** [comment] 2019-04-17 17:45
It's always something. :)

Any chance some anti-aliasing could be added to the circle edge to smooth it out?

Thanks.

**Comment by bugfixin** [comment] 2019-04-19 20:56
I can't reproduce the missing number in the circle thornbill showed on any current releases (or 10.3.0-rc1), what platform was that on?

**Comment by SenorSmartyPants** [comment] 2019-04-20 00:04
I'm getting JF blue on my requests now with 10.3.0.

But only with unplayed counts that I hadn't already requested. Some caching is happening in JF I'm assuming.

**Comment by sparky8251** [comment] 2019-04-20 00:15
JF has stupid caching we inherited from Emby. It likes to really falsify info at the server side, tricking the browser into not requesting updated data.

I'd try refreshing the page with caching disabled in the network tab of the browsers F12 menu, that almost always clears up this odd crap.

**Comment by bugfixin** [comment] 2019-04-20 00:19
These images are cached in the jellyfin cache dir on the server-side, it is beyond browser caching. You can view your current cache dir in the admin dashboard and remove the images/ folder within it to clear them.

**Comment by SenorSmartyPants** [comment] 2019-04-20 00:50
I deleted the /cache/images/resized-images and that cleared up all my green. This is closed as far as I am concerned.

**Comment by sparky8251** [comment] 2019-04-20 01:15
In that case, I'll give it a proper close.

If it comes back feel free to open a new issue!

**Closed by sparky8251** 2019-04-20 01:15 UTC
Labels: bug

**Comment by anthonylavado** [comment] 2020-11-29 06:47
@SenorSmartyPants I know this was an old issue but - are you actively consuming the image with the played indicator in any project?

**Comment by SenorSmartyPants** [comment] 2020-11-29 07:07
> @SenorSmartyPants I know this was an old issue but - are you actively consuming the image with the played indicator in any project?

Yes. I use them in my jellyfin-nmt project.

**Comment by SenorSmartyPants** [comment] 2020-11-29 07:46
Are you wanting to drop this functionality?

**Comment by anthonylavado** [comment] 2020-11-29 18:05
@SenorSmartyPants AFAIK you're fine, don't worry.

I wanted to know if there was anything using it at the moment. We don't need it in Android TV anymore, and Roku was the only official project that still used it, though they're probably just going to move away from it. We'll revisit this on a later version.
