### ISSUE TITLE
"Next up" not showing all/most shows

### ISSUE THREAD

**Issue by fwmm01** [jellyfin/jellyfin#8619] opened 2022-10-25 08:17 UTC
os: debian bullseye
hardware: RockPro64 v2.1

The next up section has just stopped displaying the next episode for most of my shows I am watching. Only recently happened. I recently updated the server, but nothing seemed to have broke immediately after.

I have refreshed metadata and re-scanned the library. No change.

Any ideas what has caused this?

**Comment by cvium** [comment] 2022-10-25 08:19
Duplicate of #8477

**Closed by cvium** 2022-10-25 08:19 UTC
