### ISSUE TITLE
10.6.0 scan all libraries failed

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3388] opened 2020-06-20 00:41 UTC
**Describe the bug**
Dashboard - Activities
scan all libraries failed
auto tasks runtime : 7 hours

**System (please complete the following information):**
 - Virtualization: docker
 - Jellyfin Version: linuxserver-jellyfin:nightly
 - Storage: synology btfrs docker

**Logs**
`Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown. at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)`

**Comment by Raul824** [comment] 2020-06-20 05:26
I am also facing the same, but am able to refresh at folder level and getting below error.



Server
Devices
Live TV
Advanced
Dashboard

Server: jelly824

Version: 10.6.0 undefined

Operating System: Linux

Architecture: X64
Firefox
Jellyfin Web 10.6.0
Last seen less than a minute ago
raul824
raul824 is online from Firefox
today at 3:24 PM
IP address: 60.242.189.36
raul824 has disconnected from Redmi 4
today at 3:19 PM
IP address: 49.195.182.196
raul824 is online from Redmi 4
today at 3:02 PM
IP address: 49.195.182.196
Scan Media Library failed
today at 1:22 PM
Running time: 12 seconds
red_demon has disconnected from GM1911
today at 8:46 AM
IP address: 192.168.1.109
red_demon is online from GM1911
today at 8:36 AM
IP address: 192.168.1.109
raul824 has disconnected from Redmi 4
today at 7:52 AM
IP address: 60.242.189.36
raul824 is online from Firefox
today at 3:24 PM
IP address: 60.242.189.36
raul824 has disconnected from Redmi 4
today at 3:19 PM
IP address: 49.195.182.196
raul824 is online from Redmi 4
today at 3:02 PM
IP address: 49.195.182.196
Scan Media Library failed
today at 1:22 PM
Running time: 12 seconds
Cache:
/cache
Logs:
/config/log
Metadata:
/config/metadata
Transcodes:
/config/data/transcoding-temp/transcodes
Web:
/jellyfin/jellyfin-web
Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown. at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path) at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info) at Emby.Server.Implementations.Library.LibraryManager.UpdateImages(BaseItem item, Boolean forceUpdate) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateSubFolders(IList`1 children, IDirectoryService directoryService, IProgress`1 progress, CancellationToken cancellationToken) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by telans** [comment] 2020-06-23 08:29
Duplicate of #3387

**Closed** 2020-06-23 08:31 UTC
Labels: bug
