### ISSUE TITLE
Hardware decoding keeps turning itself off

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#2010] opened 2019-11-13 22:27 UTC
**Describe the bug**
Choosing Intel Quick Sync, select decoders (H264, HEVC etc) and save. Come back some time later and the decoders have been unset. 

**System (please complete the following information):**
 - OS: [Debian
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by dkanada** [comment] 2019-11-14 06:01
@joshuaboniface didn't I fix this in master? Not sure if that's been released yet though.

**Comment by JustAMan** [comment] 2019-11-22 12:20
Isn't it a duplicate of https://github.com/jellyfin/jellyfin/issues/1726 and https://github.com/jellyfin/jellyfin/issues/1360? I thought it should be fixed by https://github.com/jellyfin/jellyfin/pull/1812 as @dkanada said...

**Comment by cryptobank** [comment] 2019-11-22 19:06
Im not sure why it makes difference. I didn't select VAAPI for hardware transcoding but rather the QuickSync option because it worked better with 4K videos. For some reason some 4k videos didn't hardware transcode with using the VA-API option in Jellyfin. Im running 7th gen Intel.

**Comment by JustAMan** [comment] 2019-11-25 10:46
Got some logs? Like, turn HW acceleration on, reproduce it turning itself off, show us logs...

> Im not sure why it makes difference.
That other issue talking about VAAPI isn't making a difference, that code was turning off _any_ HW acceleration IIRC.

**Closed** 2019-12-16 19:13 UTC
Labels: bug
