### ISSUE TITLE
Chromecast not working anymore

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1205] opened 2019-04-06 22:32 UTC
**Describe the bug**
about 2 weeks ago I used chromecast function last time, it worked there. In the meantime I did some git pulls and its now broken. See attached screenshot. In log there is no error or anything relevant logged, any idea how to debug this issue?

The TV isnt the problem, youtube and anything else casts fine.

I will try tomorrow an older git pull and report back.

**To Reproduce**

1. Connect jellyfin to the chromecast
2. Play a movie
3. See error

**Expected behavior**
Should play

**Logs**
nothing found relevant

**Screenshots**
https://i.imgur.com/4YsVMvn.png

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.2.2 (latest git pull)
 - Reverse proxy: no

**Comment by WWWesten** [comment] 2019-04-06 23:29
See https://github.com/jellyfin/jellyfin/issues/791

**Comment by platinum55** [comment] 2019-04-06 23:45
are you sure this is related? The button is there, connection also works fine, but when I try to play, then the error appears. Do you have any hint on how to debug this further? Maybe we can confirm the relation to #791

**Comment by thornbill** [comment] 2019-04-06 23:58
What version of Android is this on? I have seen a similar error in the Android app on one of my test devices.

**Comment by platinum55** [comment] 2019-04-07 00:14
It's Android 5.1.1 here

**Comment by anthonylavado** [comment] 2019-04-07 16:23
@platinum55 When you say “10.2.2 Latest git pull”, do you mean you’re pulling the master branch from this repository?

I know there have been some changes in the Web side of things, and I don’t know that we’ve updated the commit point for the Jellyfin-Web submodule.

**Comment by platinum55** [comment] 2019-04-08 01:39
yes, I mean the master branch :)

**Comment by anthonylavado** [comment] 2019-04-09 21:23
Hi @platinum55, I would try building from the release-10.3.z branch, and see if you still have any issues. 

There were changes to the Android apps in a way that kind of expects the updates in that branch. For example, at the time of writing, the master branch is a 26 day old version of Jellyfin-Web, and the release branch is at most 10 days old.

**Comment by platinum55** [comment] 2019-04-13 18:28
just tried that today @anthonylavado - same error :( I will try in a few days with my laptop, maybe I see an error in the browser console which is useful

**Comment by platinum55** [comment] 2019-04-17 04:12
hello, tried on laptop today:

when connecting to chromecast before trying to play something, the connection itself works fine, but any play button (overview as well as details view "play" button") doesnt work and no reaction occurs when clicking on it one time with the left mouse button. I also see nothing useful in browser console and network tab.

I then tried to play a movie in browser and THEN casting it. Then the error message(see 1. post) occurs.

Any idea how to debug this? I really want to solve this but I dont know how to get further.. Please help :)

**Comment by anthonylavado** [comment] 2019-04-17 04:51
It’s certainly a frustrating issue - and unfortunately I don’t have any pointers.

I know some other users have an issue, and a bunch don’t have any issue (mine seems to be working fine).

Was there anything in the server logs around the time you tried to cast?

**Comment by platinum55** [comment] 2019-04-19 01:14
hello friends,

tried to debug the issue on my laptop today:

in the browser console and in the debug log from jellyfin I was unable to find any useful info. I someone able to tell us how to chromecast connection works in detail? Maybe we can debug it with this piece of information.

What I dont understand so far: around 10th of march it worked here, I watched movie via chromecast and jellyfin. But even when checking out those git commits from march and building it in docker, chromecast is not working (anymore) - I'm confused about this fact

**Comment by platinum55** [comment] 2019-04-19 23:52
found out why and a solution!

found a reddit page which I can only see via google cache, thats why I will post the relevant part here:

```
[–]Vilbrekin 1 point 10 days ago* 
I do have the same issue. Trying to dig a bit into it, it appears my jellyfin server replies its internal docker address (which is http) instead of the external proxy's one (which is https with LE certificate).

This happens here in chromecastplayer.js (line 389, jellyfin 10.2.2):

require(['chromecastHelper'], function (chromecastHelper) {
chromecastHelper.getServerAddress(apiClient).then(function (serverAddress) {

message.serverAddress = serverAddress;

player.sendMessageInternal(message).then(resolve, reject);

}, reject);

And thus I guess chrome (72+) refuses to send this message to a http address...
...
```

So I set a console.log and found that the server is sending its internal address in http to the client, which fails because he needs to send the external address with https in my case.

I set "message.serverAddress = 'https://myserver.address:port;"
and chromecast is working again!

**Comment by nichobi** [comment] 2019-04-20 17:57
I've looked around a bit and the supplied server address comes from the getServerAdress function in [Chromecast helpers.js](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/chromecast/chromecasthelpers.js). However, I can't immediately tell why it returns the local address instead of the remote one.

**Comment by anthonylavado** [comment] 2019-04-30 21:02
So... @platinum55 and @nichobi - We may have had the wrong Chromecast app up during the whole month of April. You may have unintentionally been using the beta app. Try rebooting your chromecasts and see if things work.

**Comment by platinum55** [comment] 2019-05-01 00:11
@anthonylavado this does not explain why the jellyfin server sends the wrong ip address to the chromecast device, right? And the wrong IP is the source of the error we got

**Comment by nichobi** [comment] 2019-05-01 06:45
I'll need to do some more testing tonight but this does seem to have fixed casting for almost all my files. The ones that don't work are probably due to #1312, rather than this. I'll let you know if I run into more issues,

**Comment by Matt07211** [comment] 2019-05-11 04:55
@nichobi I am about to close #1312 as it now seems to be working on my end, mind verifying this is also the case for you before I close it?

**Comment by nichobi** [comment] 2019-05-11 06:37
@Matt07211 Yep, I haven't had any more issues with it

**Comment by Matt07211** [comment] 2019-05-11 11:33
Awesome thanks for confirming, I'll close my issue, and I'd suggest you close this issue if the problem is no more

**Closed** 2019-07-07 05:35 UTC
Labels: bug
