### ISSUE TITLE
[Bug] Arch build fails with "The specified RuntimeIdentifier 'arch-x64' is not recognized"

### ISSUE THREAD

**Issue by BlackLotus** [jellyfin/jellyfin#2243] opened 2020-01-08 20:50 UTC
When trying to compile jellyfin-git on aur it fails with
```
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/thomas/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Jellyfin.Server.csproj]
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/thomas/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Jellyfin.Server.csproj]
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/thomas/.cache/yay/jellyfin-git/src/jellyfin/Jellyfin.Server/Jellyfin.Server.csproj]

Build FAILED.
```

**To Reproduce**
* enable testing repos
* yay -S jellyfin-git

**Expected behavior**
It should just build

**System (please complete the following information):**
 - OS: Arch Linux (all testing repos enabled)
 - Jellyfin Version: git

**Comment by anthonylavado** [comment] 2020-01-10 20:42
Tagging @z3ntu, but please also flag as out of date in AUR.

**Comment by z3ntu** [comment] 2020-01-10 21:10
I didn't try to reproduce but as I can't find this `arch-x64` string neither in the PKGBUILD nor in the jellyfin sources, it looks like a problem with the new dotnet version in testing. If you can reproduce this error with a sample dotnet project, you should report it in the Arch Linux bug tracker (or at least ping the maintainer on IRC so he's aware that there might be issues with the new version in [community-testing])

**Comment by Vladimir-A** [comment] 2020-01-13 18:05
Same. If I try to build any .net project.
```bash
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized.
```

**Comment by dkanada** [comment] 2020-01-13 18:15
@Vladimir-A and @BlackLotus are you guys trying to build the jellyfin or jellyfin-git package? That might help narrow down the cause.

**Comment by z3ntu** [comment] 2020-01-13 22:02
There's a patch in the Arch Linux bugtracker for the `arch-x64` issue: https://bugs.archlinux.org/task/65128

**Comment by jimyx17** [comment] 2020-03-28 14:39
@BlackLotus have you tried again? I've tested that exactly same aur package without any issue.

```
    4603 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.71
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

I'm using these SDKs:
```
$ dotnet --list-sdks
2.1.805 [/usr/share/dotnet/sdk]
3.1.103 [/usr/share/dotnet/sdk]
```
Which means my installed sdk is 3 patch versions above yours. Can you update and try?

**Comment by z3ntu** [comment] 2020-03-28 15:14
The Arch Linux bug was closed on 20 January 2020, so this can be closed as well I guess

**Closed** 2020-03-29 07:01 UTC
Labels: build, confirmed
