### ISSUE TITLE
Metadata in English

### ISSUE THREAD

**Issue by Harindulk** [jellyfin/jellyfin#5302] opened 2021-02-24 01:57 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment] 2021-02-24 02:06
If you have an issue to report please fill out the issue template.

**Comment by Bond-009** [comment] 2021-02-24 02:06
With the info given I guess that this is a duplicate of #5236

**Closed by crobibero** 2021-02-24 02:06 UTC
Labels: bug
