### ISSUE TITLE
[Issue]: Continue Watching doesn't take movie versions into account

### ISSUE THREAD

**Issue by michael-zock** [jellyfin/jellyfin#12131] opened 2024-06-18 15:24 UTC
### Please describe your bug

If you paise a multi-version movie (e.g., theatrical & director's cut) and want to use the home page's Continue Watching feature later on, it can happen that Jellyfin picks a different version than the one you had been watching.
This leads me to believe, that this feature doesn't store, which version of the movie you had been watching, just the movie ID and the timecode.

In the case of some movies, there can be whole scenes missing or be added, so the timecode that was saved, will point to a completely different spot in a different version of another version of the movie.
Imagine something like David Lynch's Dune, where some version have an intro chapter while others jump straight into the action, meaning the same section has timecodes that can vary by several minutes..

When I mentioned it on the forums, someone noted that apparently the same issue had apparently already been addressed in the Android TV client. https://forum.jellyfin.org/t-continue-watching-sometimes-picks-the-wrong-version-of-a-movie

### Reproduction Steps

1. Watch a movie with multiple versions (e.g., theatrical & director's cut)
2. Stop somewhere during the movie to continue later
3. Use the Continue Watching feature on the home page.
4. If you're lucky, it will continue playing from where you stopped, with the same version you had been watching. If not, it will pick a different version and at the saved timecode, a completely different scene could be located.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Windows 11 Pro x64
- Browser: Google Chrome Version 126.0.6478.62 (Official Build) (64-bit)
- Server & Web 10.9.6
```

### Jellyfin logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2024-06-19 13:24
Duplicate of https://github.com/jellyfin/jellyfin/issues/11118

**Closed by crobibero** 2024-06-19 13:24 UTC
Labels: bug
