### ISSUE TITLE
[Issue]: Replacing all metadata does not replace movie.nfo

### ISSUE THREAD

**Issue by N8-Yue** [jellyfin/jellyfin#11735] opened 2024-05-19 10:33 UTC
### Please describe your bug

Whenever I try to replace all my metadata, the movie.nfo won't be replaced with the correct information too. This results in the old title still being shown in the nfo file. I need to manually delete the nfo and replace all metadata again in order to get a correct nfo file

### Reproduction Steps

1. Start the replace all metadata command

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Linux Kernel: latest
- Virtualization: Docker
- Clients: Web, Android, iOS
- Browser: Firefox
- FFmpeg Version: 6.0.5
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: aniSearch, Intro Skipper, Simkl, Fanart, Playback Reporting, TMDb
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-05-19 12:25:28.432 +02:00] [ERR] [78] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/folder.jpg'". URL "GET" "/Items/e7f6230f2ea1a6bf66b4f28a4a12ed03/Images/Primary".
[2024-05-19 12:25:30.267 +02:00] [ERR] [3] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/folder.jpg'". URL "GET" "/Items/e7f6230f2ea1a6bf66b4f28a4a12ed03/Images/Primary".
[2024-05-19 12:25:33.241 +02:00] [INF] [78] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-f21c6da92262295f7540b9b3acddd977"
[2024-05-19 12:25:40.904 +02:00] [INF] [78] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-05-19 12:25:46.802 +02:00] [ERR] [78] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/folder.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-05-19 12:25:48.217 +02:00] [ERR] [67] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User "Christian" not logged in (True)
[2024-05-19 12:25:48.672 +02:00] [WRN] [67] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "100.111.107.87" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-05-19 12:25:48.678 +02:00] [INF] [67] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "::ffff:100.111.107.87" closed
[2024-05-19 12:25:53.532 +02:00] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-f21c6da92262295f7540b9b3acddd977"
[2024-05-19 12:25:53.542 +02:00] [ERR] [33] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/folder.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-05-19 12:25:53.545 +02:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-19 12:25:53.571 +02:00] [ERR] [33] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-05-19 12:26:14.258 +02:00] [INF] [35] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-f21c6da92262295f7540b9b3acddd977"
[2024-05-19 12:26:18.256 +02:00] [ERR] [67] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User "Christian" not logged in (True)
[2024-05-19 12:26:34.270 +02:00] [INF] [60] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-f21c6da92262295f7540b9b3acddd977"
[2024-05-19 12:26:48.272 +02:00] [ERR] [78] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Can't scrobble: User "Christian" not logged in (True)
[2024-05-19 12:26:55.268 +02:00] [INF] [3] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b0ecc3bde3e95478bc2239abf9b3252423846bf0-9fd8852c23cb4c6da3310a3fc06ac362-f21c6da92262295f7540b9b3acddd977"
[2024-05-19 12:27:04.207 +02:00] [INF] [67] Emby.Server.Implementations.IO.LibraryMonitor: "movies1" ("/data/movies1") will be refreshed.
[2024-05-19 12:27:04.220 +02:00] [INF] [67] Emby.Server.Implementations.IO.LibraryMonitor: "Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD - filecrypt.cc" ("/data/movies1/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD - filecrypt.cc") will be refreshed.
[2024-05-19 12:27:04.224 +02:00] [INF] [67] Emby.Server.Implementations.IO.LibraryMonitor: "Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org" ("/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org") will be refreshed.
[2024-05-19 12:27:05.865 +02:00] [INF] [63] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD", Path: "/data/movies1/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD - filecrypt.cc/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD/empire-hottubec-1080p.mkv", Id: 2f8009e9-fa46-9e7d-7f25-151d70411064
[2024-05-19 12:27:05.884 +02:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "AXUre7HdXaHb_hit47agent4K2015Remux", Path: "/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/AXUre7HdXaHb_hit47agent4K2015Remux/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K.mkv", Id: e7f6230f-2ea1-a6bf-66b4-f28a4a12ed03
[2024-05-19 12:27:07.708 +02:00] [INF] [47] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies1/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K_DDL - NIMA4K.org/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K/Hitman.Agent.47.2015.German.DTS.DL.2160p.UHD.BluRay.HDR.HEVC.Remux-NIMA4K.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-19 12:27:07.725 +02:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies1/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD - filecrypt.cc/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD/Hot.Tub.Der.Whirlpool.ist.ne.verdammte.Zeitmaschine.Extended.Cut.German.DL.1080p.BluRay.x264-EmpireHD.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-19 12:27:08.190 +02:00] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies1/Killers.Bodyguard.2.2021.EXTENDED.German.EAC3.DL.1080p.BluRay.x265-VECTOR - filecrypt.cc/Killers.Bodyguard.2.2021.EXTENDED.German.EAC3.DL.1080p.BluRay.x265-VECTOR/Killer's Bodyguard 2 (2021).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-19 12:27:08.204 +02:00] [INF] [47] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/movies1/Killers.Bodyguard.2017.German.EAC3.DL.1080p.BluRay.x265-VECTOR - filecrypt.cc/Killers.Bodyguard.2017.German.EAC3.DL.1080p.BluRay.x265-VECTOR/Killer?s Bodyguard (2017).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-05-19 10:41
Duplicate of #11619

**Comment by N8-Yue** [comment] 2024-05-19 11:35
My bad. I thought I checked for a duplicate but apparently I didn't see this thread

**Comment by felix920506** [comment] 2024-06-30 16:23
Closing as duplicate

**Closed by felix920506** 2024-06-30 16:23 UTC
Labels: bug
