### ISSUE TITLE
Almost all TV shows with seasons/episodes wrong

### ISSUE THREAD

**Issue by simonbcn** [jellyfin/jellyfin#2423] opened 2020-02-18 13:49 UTC
- Arch Linux
- Firefox 73.0
- Jellyfin 10.5.0 (_installed from jellyfin-git AUR package_)

My TV Shows library settings:
![Selección_00158](https://user-images.githubusercontent.com/428231/74741149-90524100-525c-11ea-938f-a4a7a7599d30.jpg)

Some examples:
![Selección_001fa](https://user-images.githubusercontent.com/428231/74741290-d3141900-525c-11ea-9fd9-67ff42c7e481.jpg)

![Selección_0014f](https://user-images.githubusercontent.com/428231/74741346-e7581600-525c-11ea-8af2-d7e08732ad10.jpg)

![Selección_00149](https://user-images.githubusercontent.com/428231/74741403-ffc83080-525c-11ea-862e-2ba25760a3fb.jpg)

and so on...

Is it a problem with filenames?
The filenames and folders are in Spanish and the seasons are generally identified with the letter T (_"Temporada" in Spanish_).

For example:
```
$ ls /multimedia/qBittorrent/series/Castle Rock (2018) T2 [WEB-DL HULU 1080p h264 Dual DD5.1 Subs] 
'Castle Rock 2x01 Que el rio siga su curso [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x02 Nueva Jerusalén [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x03 Los lazos que nos unen [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x04 Recupera la esperanza [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x05 El lugar para reirse [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x06 La madre [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x07 La palabra [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x08 Sucios [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x09 Caveat Emptor [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
'Castle Rock 2x10 Limpios [WEB-DL HULU 1080p h264 Dual DD5.1 Subs].mkv'
```
```
$ ls /multimedia/qBittorrent/series/[MEGAPACK]After Life T1 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub]
'After Life 1x01 Episodio 1 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv'
'After Life 1x02 Episodio 2 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv'
'After Life 1x03 Episodio 3 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv'
'After Life 1x04 Episodio 4 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv'
'After Life 1x05 Episodio 5 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv'
'After Life 1x06 Episodio 6 [WEB-DL NF 1080p h264 Dual DD 5.1 Sub].mkv
```

**Comment by Artiume** [comment] 2020-02-19 16:45
It's the 1x01 and 2x02 that's tripping the scanner. Use S01E01 and see how it behaves

**Comment by Ullmie02** [comment] 2020-02-19 21:17
This seems to be the same issue as #2171

**Comment by Artiume** [comment] 2020-02-19 21:19
Yes. the scanner hasnt been touched since 10.4.2. Your best option is to use S01E01 until the scanner is rebuilt.

**Comment by Bond-009** [comment] 2020-02-19 21:26
Duplicate of #2171

**Closed by Bond-009** 2020-02-19 21:26 UTC
Labels: bug
