### ISSUE TITLE
Unable to view pictures past number 301

### ISSUE THREAD

**Issue by Artair257** [jellyfin/jellyfin#5452] opened 2021-03-09 21:13 UTC
If an image library folder has over 301 images, you cannot select or scroll to any pictures past the 301st.
If you do select an image past image 301, it displays image 1 instead.
Attempting to scroll from image 301 to 302 acts like it is the end of the library.

**Comment by DinoHS** [comment] 2021-03-10 19:45
https://github.com/jellyfin/jellyfin-web/issues/2294

A fix was proposed but I don't see that it made it into the 10.7.0 release.

**Comment by cvium** [comment] 2021-04-11 07:59
Given that the proposed fix is in web I'll close this issue as a duplicate of https://github.com/jellyfin/jellyfin-web/issues/2294

**Closed by cvium** 2021-04-11 07:59 UTC
