### ISSUE TITLE
/dev/dri/renderD128 groupchange to syslog

### ISSUE THREAD

**Issue by DSDV** [jellyfin/jellyfin#6505] opened 2021-09-04 08:58 UTC
**Describe the bug**
upon event (system crash) the ownergroup of /dev/dri/renderD128 changes to syslog:
`# ls -la /dev/dri/
total 0
drwxr-xr-x 2 root root         80 Sep  4 08:37 .
drwxr-xr-x 8 root root        520 Sep  4 08:37 ..
crw-rw---- 1 root video  226,   0 Sep  4 08:22 card0
crw-rw---- 1 root syslog 226, 128 Sep  4 08:22 renderD128
`

this breaks the whole hardware transcoding. and needed many hours to find out.
how can this be prevented?

**System (please complete the following information):**
 - OS: [Proxmox]
 - Virtualization: [LXC  (Ubuntu 20.4)]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [Firefox 91]
 - Jellyfin Version: [10.7.6]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Hardware Acceleration: [VAAPI; AMF]
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [local, CIFS]

**To Reproduce**

1. get container crashed ( was while trying to figure out why a sepcific movie was always crashing the container when trying to transcode)
2. upon reboot have broken hw acceleration

**Expected behavior**
up on reboot the system should work (eg not a ownergroupchange of a driver which breaks hw-acceleration

**Server Logs**
where can i find those?

**FFmpeg Logs**
where can i find those?

**Screenshots**
see code quote

**Additional context**
none

**Comment by Shadowghost** [comment] 2021-09-04 11:53
Devices residing in `/dev/dri` are created on boot by the graphics driver and therefore changes to their ownership do not survive reboots.
As [our docs explain](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#configuring-va-api-acceleration-on-debianubuntu), you need to add the `jellyfin` user to the `video` group (or `render` group, depending on OS) to allow permanent access to the device:
```
On some releases, the group may be video instead of render.

Add the Jellyfin service user to the above group to allow Jellyfin's FFMpeg process access to the device, and restart Jellyfin.

sudo usermod -aG render jellyfin
sudo systemctl restart jellyfin
```

Logs can either be read via the admin webui or by checking the files in `/var/log/jellyfin` on the host machine.

**Comment by Artiume** [comment] 2021-09-04 12:35
Logs are under Dashboard > Logs. For hw accel issues, ffmpeg logs are more important. 

Ensure you're running the latest ffmpeg as shown here 

https://github.com/linuxserver/docker-jellyfin/issues/109#issuecomment-855448377

To fix the permission changes, you'll probably need to make a script similar to this

https://github.com/linuxserver/docker-jellyfin/issues/26#issuecomment-618089750

or perhaps this

https://github.com/linuxserver/docker-jellyfin/issues/26#issuecomment-864520282

**Comment by DSDV** [comment] 2021-09-04 12:52
the render group is present since it was there before the container crashed. 
and it worked after manually fixing it. 

maybe jellyfin can implement an option to cehck for correct group and reset them if needed

**Comment by Artiume** [comment] 2021-09-04 12:53
Is the host crashing or the container?

**Comment by DSDV** [comment] 2021-09-04 13:22
the container crashed while transcoding was trying a faulti bit at a video file. 

everything is at its latest version (apt update&apt upgrade) inside the LXC and the Proxmox host.

**Comment by Artiume** [comment] 2021-09-04 13:26
did you look at the links i provided? Ubuntu's 10.7.6 provides ffmpeg 4.3.1 while it should be 4.3.2, what version is your ffmpeg? and is it crashing while having the correct permissions or bad permissions?

**Comment by DSDV** [comment] 2021-09-04 13:59
the permissions are correct. 

```
/usr/lib/jellyfin-ffmpeg# ./ffmpeg
ffmpeg version 4.3.1-Jellyfin Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-ver                                                sion=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb -                                                -disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --en                                                able-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-lib                                                ass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi                                                 --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --ena                                                ble-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265                                                 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --                                                enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --ena                                                ble-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfi                                                le}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by Artiume** [comment] 2021-09-04 14:09
Yeah your ffmpeg is not up to date. Do this to uodate to 4.3.2

docker exec -it jellyfin /bin/bash
curl -LO https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/4.3.2-1/jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb
dpkg -i jellyfin-ffmpeg_4.3.2-1-focal_amd64.deb

**Comment by DSDV** [comment] 2021-09-04 14:26
upgraded to latest version as shown in your first link (why does this not work with apt upgrade?)

`# ./ffmpeg
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
`

but now it doesnt render at all :/

**Comment by Artiume** [comment] 2021-09-04 14:46
Not sure why it'd break. sometimes people have issues with old drivers like here
 
https://github.com/linuxserver/docker-jellyfin/issues/107

here's a reddit post that may be helpful, i dont use hw acceleration so i can help so much.

https://www.reddit.com/r/jellyfin/comments/n9d5v5/please_update_jellyfinffmpeg_to_4321_to_use_intel/

**Comment by DSDV** [comment] 2021-09-04 14:51
the hw acceleration works fine - i think. 

but with certain files when it transcodes it seems to hit a bottleneck when using vaapi. 
for a few frames the picture is perfect. after that for a few seconds picture gets distroted like hell. specially the moving parts.

**Comment by Artiume** [comment] 2021-09-04 14:54
so what did you mean it didn't render at all? that ffmpeg fails with an exit code or you just get bad quality?

**Comment by DSDV** [comment] 2021-09-04 14:57
> 
> 
> so what did you mean it didn't render at all? that ffmpeg fails with an exit code or you just get bad quality?

it was an error because one of the links stated to set chmod to 755 which is not correct (at least for my usecase i had to set it back ;)

**Comment by therealmelee** [comment] 2022-02-06 08:51
I have the exact same issue, and interestingly am using the same setup - LXC container running on Proxmox.

/dev/dri/renderD128 is initially owned root:render; but then at some point that changes to root:syslog, which breaks hardware decoding entirely.

chown root:render /dev/dri/renderD128 fixes the issue.

**Comment by Shadowghost** [comment] 2022-02-06 09:38
How are you passing through the device?
I'm also running Jellyfin via LXC on Proxmox and added docs for this specific usecase:
https://jellyfin.org/docs/general/administration/hardware-acceleration.html#lxc-container-on-proxmox

**Comment by therealmelee** [comment] 2022-02-06 17:21
Yup following those exactly and it works... until it doesn't. But I suspect it's an upstream (Proxmox or host driver / host permissions) issue rather than anything to do with Jellyfin. I had it working just fine on another node then this week did a reinstall on a new machine and came across this for the first time.

**Comment by gabberpocky** [comment] 2023-01-16 01:41
Just commenting that I recently identified this as the cause of hardware acceleration breaking on my install (LXC on Proxmox 7.3). After chowning renderD128 from syslog to render, things returned to working order.

This seems a fairly obscure bug that probably originates in Proxmox rather than Jellyfin.

**Comment by zenodotus280** [comment] 2023-03-11 18:38
> Just commenting that I recently identified this as the cause of hardware acceleration breaking on my install (LXC on Proxmox 7.3). After chgrping renderD128 from syslog to render, things returned to working order.
> 
> This seems a fairly obscure bug that probably originates in Proxmox rather than Jellyfin.

I can confirm that the group ownership of mine has been 'wandering' too and I'm running bare metal now on Proxmox. Initially it was `render` but soon it switched to `_chrony` and then `crontab` which naturally broke all transcoding. I looked at the udev rules and saw that `render` is set up so I just rebooted and everything is working fine for now.

**Comment by therealmelee** [comment] 2023-03-13 22:35
My guess (still having this issue months later) is that there is a numerical mapping difference between the groups as defined by Proxmox and what an Ubuntu container uses. So when we map the /dev/dri folder into the container, it understands "groupnum" to be "syslog" or "_chrony" or "crontab", when the host system mapping would be 'render'. When remapped within the container by hand and by name (not number), it then figures it out.

But I'm a total novice with groupids and all that, so what's probably easy to figure out to someone who would know how to do that is a mystery to me :)

**Comment by Stooovie** [comment] 2023-05-21 18:44
Guys, guys... I have the same issue but trying to fix it just spawns more subquests on each step... I don't know how to find out what group my renderD128 belongs to or how to change it. I've been trying to fix HW acceleration under Proxmox 7.4-3 for three days straight. Please help.

**Comment by DSDV** [comment] 2023-05-21 19:28
@Stooovie i dont know why the devs removed the bug flag on this. 
i never figured out how to stop the group switching. My solution was to stop using the hadrware part of jellyfin wich sadly let to stop using jellyfin alltogether :( 

Project looks great and if you dont need hardware de/encoding it still is. But with  it you basically cant use it visualized from my poiint of view :/

**Comment by Stooovie** [comment] 2023-05-21 19:30
thank you, looks that way :(

**Comment by Stooovie** [comment] 2023-05-21 20:24
Random guy drops one command that fixes the issue for me:

`/bin/chgrp video /dev/dri/renderD128`

HW Acceleration in Jellyfin LXC fully working  now.

**Comment by gabberpocky** [comment] 2023-05-21 22:52
On a hunch... did anyone affected by this bug also use a script from tteck to set up their problematic Jellyfin LXC?

I'm now looking in the script's direction after noticing the same behaviour on a non-Jellyfin LXC container (frigate). Either way that confirms for me that it's not a jellyfin bug - it's either Proxmox itself or something specific to the LXC setup we're using.

I have tried manually setting up a new, non-privileged LXC running a fresh install of Jellyfin and so far there has been no interference with the ownership of the render group on the Proxmox host.

**Comment by DSDV** [comment] 2023-05-21 22:52
persistent through restarts and time? 
i alwys fixed it with setting correct chown but it alawys broke after reboots or time passed :/

**Comment by therealmelee** [comment] 2023-05-22 05:19
I did not use tteck (never heard of them). I used the built-in Ubuntu LXC template to create the container.

I confirmed it's a numbering issue.

Within the physical system (running Proxmox), the render account is:

render:x:103:

But inside the LXC:

render:x:108:jellyfin
syslog:x:103:

So that explains why the container initially maps to 'syslog', and why a chown fixes it. Interestingly - when I fix it for my Jellyfin container, I actually 'break' it in the host system.

I don't understand LXC configs enough right now to know how to just remap 103/108 in this particular container to have it work on boot without needing to do anything.

**Comment by Stooovie** [comment] 2023-05-22 05:57
> persistent through restarts and time? i alwys fixed it with setting correct chown but it alawys broke after reboots or time passed :/
> 
> PS: i think i used tteck since i use his scripts for alot of stuff :D

it does survive on mine, I just tried. I installed Jelly manually, I did not use tteck's script. It uses a Debian 11 LXC. No issues whatsoever. HW accel works, NAS is mounted. It's a privileged LXC.

**Comment by DSDV** [comment] 2023-05-22 08:48
maybe it is related to the container OS?

https://raw.githubusercontent.com/tteck/Proxmox/main/ct/jellyfin.sh uses ubuntu. 
maybe it has to be debian to work?

**Comment by therealmelee** [comment] 2023-05-24 07:48
Tried creating a Debian container too - again not via any tteck script - manually installed using the built-in Debian 11 template.

Same issue - different group conflict.

It seems that if you set up an unprivileged container, you can do the group mapping described in the Wiki.

Alternatively, you can chmod 0666 /dev/dri/renderD128 on the host system, and it will then allow the container access to the hardware, even if it is mapped to the wrong group.

**Comment by DSDV** [comment] 2023-05-24 08:06
hm ... but i think some might need privileged due to mounting drives, shares etc. 
Also is hw acceleration even possible with unprivileged?

**Comment by therealmelee** [comment] 2023-05-30 16:57
You do not need Privileged for HWA. Indeed the official documentation says that.

**Comment by srcrist** [comment] 2023-10-05 23:40
This is an OS permissions and configuration issue. Jellyfin does not touch the ownership of any /dev/dri devices. Closing this issue as it is not actually a Jellyfin bug.

**Closed by srcrist** 2023-10-05 23:40 UTC
Labels: question
