### ISSUE TITLE
DLNA not working correctly 

### ISSUE THREAD

**Issue by ycodryn** [jellyfin/jellyfin#1322] opened 2019-04-28 20:32 UTC
I'm using the latest version in a docker. My LG tv can't see the server, I have to disable and enable the DLNA server to be visible and after Im closing the tv is not working again. Blast alive messages option I don't think that is not working in this case. In logs I'm also seeing Failed to bind to port 1900 but I'm not using that port. If I'm using Serviio is always visible no matter what.

**Comment by skug67** [comment] 2019-05-01 12:32
I can get the DLNA server running if it's the only process asking for port 1900/UDP on any interface.  But it does ask for all interfaces (and thus refuse to start the DLNA server) when 1900/UDP is in use on interface1 even if I've configured jellyfin to bind to the IP address of interface2.

**Comment by ycodryn** [comment] 2019-05-01 17:52
I have a Synology DS718+ abd I checked if any process is using that port and is not. And is stranger that the dlna is working after I disable/enable the server. But I have to do it when the tv is on.

**Comment by ycodryn** [comment] 2019-05-03 19:41
Again I used netstat -tulpn | grep :1900 to find if 1900 port is used, I disabled every app that was using it but jellyfin gave same error in log about Failed to bind to port 1900. Another process that is using port 1900 is minissdpd but that that one is a must have process for upnp discovery so maybe jellifyn is not communcating well with it?

**Comment by 97carmine** [comment] 2019-05-06 09:18
Something similar I noticed when I did the update from version 10.2.2 to 10.3.0, and DLNA was not recognizable by the clients.

But shortly after I made a clean installation of version 10.3.0 and the DLNA works without problems.

**Comment by ycodryn** [comment] 2019-05-07 07:57
Mine was a clean installation from beginning :(

**Comment by 97carmine** [comment] 2019-05-07 08:21
It's a bug that happens I've noticed both with Emby and with Jellyfin.
For example, when you have Jellyfin and Tvheadend installed on the same computer. Tvheadend takes the port 1900 and Emby could not start the DLNA server.

Here is an Emby issue on this topic: https://emby.media/community/index.php?/topic/61265-error-dlna-error-in-beginlisteningforbroadcasts/

That is the reason why I decided to install Jellyfin in an LXC container and Tvheadend in another LXC container via Proxmox.

**Comment by hukoeth** [comment] 2019-06-19 16:14
I had the same issue so I poked around in the config files and came across ServerConfiguration.IgnoreVirtualInterfaces. If I set this to "true" and enable "Blast alive messages" both Samsung and LG TVs are able to discover the server.
I didn't have time to look into this in more detail but maybe it helps someone with the same issue.

**Comment by anthonylavado** [comment] 2019-09-17 17:05
shoo bot

**Comment by hukoeth** [comment] 2019-10-22 18:18
On 10.4.0 I can't get DLNA to work at all. Let me know what I can do to narrow down the cause.

**Comment by NULUSIOS** [comment] 2019-10-31 17:21
Same here. DLNA doesn't show up in my network (or TV).

**Comment by PrplHaz4** [comment] 2019-10-31 18:44
For docker, make sure you're using host networking (or macvlan) to make it visible to the rest of your network.

Another thing that seemed to help me was decreasing the time for Blast Alive Messages and Client Discovery from 1800s to 60s.

**Comment by NULUSIOS** [comment] 2019-10-31 19:51
It is indeed in a docker.
But it should be visible in the network, simply because from a client I can normally go to jellyfin configuration from a browser.
I will change discovery.

**Comment by JustAMan** [comment] 2019-11-01 14:16
It is visible in the network, it's how docker networking works that auto-discovery (and DLNA) cannot work without tuning the way you run your container.
Nothing we can easily fix on our end (except maybe improving the documentation - was it you @PrplHaz4 who cobbled together working non-host vlan-based way of running JF via docker with DLNA?).

**Comment by PrplHaz4** [comment] 2019-11-01 14:48
@JustAMan yup, that was me - I would still not recommend that for production unless using host networking (`--net=host`) is not an option.

**Comment by NULUSIOS** [comment] 2019-11-01 15:22
Thanks, I will check how this is done on unRAID.

**Comment by hukoeth** [comment] 2019-11-01 15:22
I'm running the docker with --net=host but I still can't get it to work. On 10.3.x it was working after some in the settings (ServerConfiguration.IgnoreVirtualInterfaces=true) but on 10.4.x no luck.
I toggled every setting restarting the docker container between the changes but it won't budge.
Any ideas? Or is a fix on the the way?
(Client discovery is working fine btw)

Off topic: the speed improvements in 10.4.x are incredible. Thanks so much.

**Comment by JustAMan** [comment] 2019-11-01 15:24
> @JustAMan yup, that was me - I would still not recommend that for production unless using host networking (`--net=host`) is not an option.

I would still recommend writing up a blurb in the docs, you can prefix it with a warning if you wish. It's still much better than nothing though ;)

**Comment by NULUSIOS** [comment] 2019-11-01 15:26
What are the issues of using host networking?
Some reading would be useful.

**Comment by killeriq** [comment] 2019-12-27 11:31
just installed today into docker on unRaid and seems like i have also problem with DLNA , i'm on Version: 10.4.3 . On other Plex or Serviio DLNA is running fine

**Comment by hukoeth** [comment] 2019-12-27 13:32
I managed to finally fix the issue as described in #1464 by changing the Control panel> Advanced> Secure connection mode to disabled (instead of handled by reverse proxy).
I think this should be fixed somewhere somehow. I tried to figure out what this setting actually does but don't have time right now to work myself through the whole project.

If you want I can however do one of the following if you guys want:
- Put a note in the webui informing that this setting seems to have consequences for DLNA discovery
- Add something to the documentation
- Remove the setting completely from webui

Let me know and I can submit a pull request.

**Comment by PrplHaz4** [comment] 2019-12-27 13:33
@killeriq turn on debug logging and post the logs. It sounds like you have other services using port 1900 - if that is the case, it will definitely not work for jf.  

If you’re not seeing the same behavior as others in this thread create a new issue with the logs.

**Comment by killeriq** [comment] 2019-12-28 22:33
> @killeriq turn on debug logging and post the logs. It sounds like you have other services using port 1900 - if that is the case, it will definitely not work for jf.
> 
> If you’re not seeing the same behavior as others in this thread create a new issue with the logs.

i changed port 1900 to 1800, as without that it wont start at all
Will check the log

**Comment by killeriq** [comment] 2019-12-28 22:52
[j-log.txt](https://github.com/jellyfin/jellyfin/files/4007542/j-log.txt)
![j-net](https://user-images.githubusercontent.com/39062891/71550288-24c2c480-29cd-11ea-83fc-226f7b45fe94.JPG)
![j-dlna](https://user-images.githubusercontent.com/39062891/71550289-255b5b00-29cd-11ea-8749-ff2efcc47fec.JPG)

**Comment by killeriq** [comment] 2019-12-28 23:14
Working now - I had to change in Docker settings Network to "Host" default was "Bridge" its working on 1800 port as well ;)

**Comment by propagandalf** [comment] 2019-12-29 17:33
Tried the Play On DLNA feature towards my LG TV with those settings, but nothing happens. This is Jellyfin log:

[2019-12-29 17:21:02.361 +00:00] [INF] Profile: "LG Smart TV", Path: "/The Show/Season 1/The.Show.S01E01.1080p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True

[2019-12-29 17:21:02.372 +00:00] [ERR] Error processing request
System.ArgumentNullException: Value cannot be null.
Parameter name: baseUrl
   at MediaBrowser.Model.Dlna.StreamInfo.ToUrl(String baseUrl, String accessToken)
   at Emby.Dlna.PlayTo.PlayToController.CreatePlaylistItem(BaseItem item, User user, Int64 startPostionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by Lightning2X** [comment] 2019-12-29 20:00
For me DLNA used to work until tonight when it randomly decided to break. I've tried the fixes above but I still can only view and browse DLNA if I turn the server on and off when the device is searching.  Maybe the active port list will help? I'm not at all a networking expert but I guess CLOSE_WAIT isn't a great sign right?
![image](https://user-images.githubusercontent.com/32514161/71561973-12549380-2a7e-11ea-9f32-a0c46764458b.png)

**Comment by leonelsr** [comment] 2020-01-02 22:27
I've been able to verify that Jellyfin has to be started before any other DLNA software on the same machine, in order to its DLNA provider to work properly (being detected by any TV or device etc). DLNA won't work if port 1900 is already being listened by any other process.

Such as #893 , this bug existed on Emby some time ago,  but has been fixed there.
Emby, Plex and Windows' own DLNA implementation can all coexist and are all detected, no matter in which order they're started. Why can't Jellyfin? What was the solution on Emby? Couldn't we use the same fix? How far is our codebase from their "upstream"?

**Comment by JustAMan** [comment] 2020-01-10 13:01
I believe it has to do something with non-exclusive port binding, which we're probably getting with move to .NET Core 3.1 (will be released in 10.5.0 sometime soon), cc @Bond-009 or @cvium for more

**Comment by RazvanSt** [comment] 2020-01-11 19:58
Same issue here: DLNA needs to be restarted to be discovered by the TVs/other devices. No other service is using the 1900 port on the host.

**Comment by olskar** [comment] 2020-01-12 17:36
Is all of you having this problem running in docker? I do not have the problem when installing with apt in ubuntu

**Comment by RazvanSt** [comment] 2020-01-12 19:10
No, I am running Jellyfin directly in OpenMediaVault 4, no Docker involved.

**Comment by chrios** [comment] 2020-01-18 12:15
FYI for people on Gnome versions with the media sharing feature (default in ubuntu 18.04). I was having this issue because by default the media sharing is enabled. I needed to turn it off in the Settings->Sharing->Set toggle to off for JellyFin to be able to bind to :1900.

**Comment by chielmi** [comment] 2020-01-20 18:42
Stumbled upon this issue after a Google search. Having the same issue with latest Jellyfin in Docker on my Synology DS216+. I tried both the official Docker image and the one from Linuxserver.

Port 1900 _seemed_ to be in use by TVheadend (netstat -tulpn | grep :1900). After stopping TVheadend, port was not in use but still same error in the Jellyfin logs and DLNA refused to work.

In the end rolling back the Docker container to 10.4.2 was the only way for me to solve the issue. Now DLNA is working fine again.

**Comment by 97carmine** [comment] 2020-02-02 16:09
I confirm that setting a base URL also causes DLNA to cease to be discoverable even if the Secure connection mode option has been changed to Disabled.

Tested on a Jellyfin server version 10.4.3

**Comment by Bond-009** [comment] 2020-02-02 17:04
@97carmine Should be fixed on master

**Comment by RazvanSt** [comment] 2020-02-09 20:33
Running jellyfin-nightly-20200209 and DLNA is no longer discoverable on the network. Tried toggling the option in settings - no change.
[Log.txt](https://github.com/jellyfin/jellyfin/files/4177796/Log.txt)

**Comment by Artiume** [comment] 2020-02-12 19:42
@PrplHaz4 Can you verify the functionality of DLNA for nightlies?

**Comment by Bond-009** [comment] 2020-02-12 20:00
@RazvanSt Do you have a baseurl set?

**Comment by PrplHaz4** [comment] 2020-02-12 20:04
> @PrplHaz4 Can you verify the functionality of DLNA for nightlies?

Will try to test tonight. There was an open issue for dlna/vlc which might impact other platforms....

**Comment by PrplHaz4** [comment] 2020-02-13 03:25
@Artiume @Bond-009 
Working good for me @ 64800de29da43aa74c2925d2a10b1f626b8c2eae with no base URL set and Secure Connection mode is DISABLED.

There are also a number of different problems mentioned in this issue...it probably should be closed in favor of individual issues/descriptions/logs for any reproducible problems...

**Can't bind to port 1900**
- Another application is probably already using port 1900
- Fix this by implementing some sort of non-exclusive port binding in Kestrel (some day?)

**DLNA Server not discovered**
- Set Client Discovery to 60s, Blast Alive Message Interval 120s
- Relies on multicast or mdns reflection across local subnet only (on docker requires net=host or macvlan)
- Check firewall settings - this is what the server's UPNP/DLNA discovery announcement looks like:
```
Internet Protocol Version 4, Src: jellyfin.example.com (192.168.1.141), Dst: 239.255.255.250 (239.255.255.250)
User Datagram Protocol, Src Port: 53491 (53491), Dst Port: ssdp (1900)
Simple Service Discovery Protocol
NOTIFY * HTTP/1.1\r\n
HOST: 239.255.255.250:1900
LOCATION: http://192.168.1.141:8096/dlna/af9f06335f4d490685987391b5f6b4be/description.xml
```

**Media not listed** 
- fixed by 241e351a6128aeaf594e8fefe2da244970c24954 and 662e1164c916098fd39469569c64f88126bedc65

**LiveTV media items not listed in VLC client**
- #2371 open for this

**Comment by mazzystr** [comment] 2020-02-14 19:05
Sorry guys we don't have it yet....  `Base URL: /jellyfin` is still breaking DLNA.  With `Base URL` set the server is discoverable but content cannot be listed.  Blank out `Base URL` and server is discoverable, content is listable, and content is playable.  

We gotta have `Base URL` working here.  The next step is going to be running without `--net=host`, haproxy ssl offloading, and a broadcast relay between general network and container network.

Version : Jellyfin nightly container / 10.5.0
Clients: VLC android app & Yamaha V-685 amp

**Comment by PrplHaz4** [comment] 2020-02-14 21:01
@mazzystr can you move your report over to #2377 to be reopened?  This current one has turned into a DLNA catch-all.

https://github.com/jellyfin/jellyfin/issues/2377

**Comment by PrplHaz4** [comment] 2020-02-18 20:49
@anthonylavado I think this should be closed and replaced by #2377 on the 10.5 project board.

**Closed** 2020-02-19 04:51 UTC
Labels: bug, confirmed

**Comment by dkanada** [comment] 2020-02-19 04:53
As stated by @PrplHaz4, this issue has become somewhat generic. If you have a specific error message feel free to make a new issue, and if you can't seem to get DLNA working we are very active on Matrix for any troubleshooting help.

**Comment by maurirope** [comment] 2023-03-28 00:26
Hello, I dont know if this helps, but I just experienced this issue and in my case I found out that while DLNA uses port 1900 for discovery and it should be open for access, you should also keep in mind that port 8096 should still be open for LAN access as the content will actually be delivered via HTTP through that port.

My issue originated because yesterday I spent like 7 hours configuring SSL and had closed 8096 for every incoming IP due to now serving content through the 8920. It wasnt enough to unmark HTTPS required in jellyfin config, I had to open that port back again on ufw.

Hope you can get this solved
