### ISSUE TITLE
[Issue]: Jellyfin stops watching a library if there are subdirectories with restrictive permissions

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin#10012] opened 2023-07-17 05:47 UTC
### Please describe your bug

If I add an album to my music library, and that album has a subdirectory that doesn't have music but has very restrictive access permissions, Jellyfin's directory watcher spits an error and stops watching the entire library. See the log below:

```
[2023-07-08 10:13:39.767 +03:00] [ERR] Error in Directory watcher for: "/media/seagate/music"
System.UnauthorizedAccessException: Access to the path '/media/seagate/music/Black Label Society/2005 - Mafia/Cover' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
[2023-07-08 10:13:39.771 +03:00] [INF] Stopping directory watching for path "/media/seagate/music"
```
IMO this should be handled in such a way that only those directories for which Jellyfin has no access should be skipped, but the rest of the library should continue to be watched.

The only way to remedy this is to fix the permissions of the offending directories and restart Jellyfin, which is not a big deal, but it's easy to miss this and it shouldn't be necessary.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: armbian Linux
- Linux Kernel: 6.1.30
- Virtualization: No
- Storage: usb attached disk
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by boc-the-git** [comment] 2023-10-03 11:15
I agree generally with the suggestion
> IMO this should be handled in such a way that only those directories for which Jellyfin has no access should be skipped, but the rest of the library should continue to be watched.

I think that's far from a simple solution though because what is being watched is `/media/seagate/music` and not `/media/seagate/music/Black Label Society/2005 - Mafia/Cover` - the watcher is at that higher level.
This is where the error is output, FWIW: https://github.com/jellyfin/jellyfin/blob/8b4f4215e01a92174e55eca6486da3186dd58853/Emby.Server.Implementations/IO/LibraryMonitor.cs#L328-L336

Perhaps the short-medium term solution here might be a more prominent error message? What is the experience like currently?

> The only way to remedy this is to fix the permissions of the offending directories and restart Jellyfin, which is not a big deal, but it's easy to miss this and it shouldn't be necessary.

Is a Jellyfin restart definitely necessary, or would triggering a library scan resolve it?

Note I was unable to quickly setup a test case for this in a Docker container to recreate the scenario.

**Comment by csaavedra** [comment] 2023-10-03 11:57
Currently, the experience is that you don't really know why media is not updated after adding new files, unless you check the logs. There's no indication in the UI otherwise that there was an error.

In all cases, triggering a library scan does add the new files. But that's because there are new files. In my experience, for the library watch to work again, the directory watcher needs to be setup again, and from looking at the logs this only happens during startup.

In the meantime I have mitigated this a bit by adding the user that runs jellyfin in my server to the group to which the files usually belong when they are added to the library, that catches most of the issues with permissions so that jellyfin can read them.

**Comment by srcrist** [comment] 2023-10-07 15:26
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/7130

**Closed by srcrist** 2023-10-07 15:26 UTC
Labels: bug
