### ISSUE TITLE
Subtitles from previous episode when autoplay is on

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin#1890] opened 2019-10-12 14:07 UTC
**Describe the bug**
When the next episode is played automatically after the previous one ends subtitles displayed are from previous episode. If you leave the player and play it again it works normally.

**To Reproduce**
1. Install Jellyfin 10.4.0
2. Turn on automatic next episode play.
3. Watch episode with subtitles, let it end and autoplay next one.

**Expected behavior**

It should play correct subtitles.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Chromium
 - Jellyfin Version: 10.4.0
 - Reverse proxy: nginx but tested without and problem persists

**Additional context**

I can't test it on other browser because i have custom Chromium playing HEVC, but it worked before update to 10.4.0.

**Comment by JustAMan** [comment] 2019-10-15 10:37
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/518

**Closed by JustAMan** 2019-10-15 10:37 UTC
Labels: bug
