### ISSUE TITLE
Media appears but can't be played

### ISSUE THREAD

**Issue by Albert24GG** [jellyfin/jellyfin#6068] opened 2021-05-17 20:42 UTC
**Describe the bug**
All the media is visible(appears in the client and library scans occur successfully) but when I try to play any media, it won't play. In the desktop client when I hit play button, nothing happens, in the web client it will show me the message "Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format." and in the android client it will show me the message "Invalid play method.".

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Any(Windows,Android)
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser,Android, Desktop 
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - On any browser 
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Jellyfin server version: 10.7.5-1
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Open Subtitles
 - Base URL: [e.g. none, yes: /example]
 - None
 - Networking: [e.g. Host, Bridge/NAT]
 - host
 - Storage: [e.g. local, NFS, cloud]
 - local network nas

**To Reproduce**

Open any jellyfin player and try to play any media

**Expected behavior**
Play the media without any issues

**Logs**
```
[2021-05-17 20:18:14.362 +00:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Jellyfin MPV Shim", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 2147483000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 1280000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 5, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: null, Type: Audio, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264,h265,hevc,mpeg4,mpeg2video", AudioCodec: "aac,mp3,ac3,opus,flac,vorbis", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "jpeg", Type: Photo, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-05-17 20:18:14.366 +00:00] [INF] User policy for "albertgg". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2021-05-17 20:18:14.366 +00:00] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 13599688, max bitrate: 8000000
[2021-05-17 20:18:14.366 +00:00] [INF] Profile: "Jellyfin MPV Shim", Path: "/media/stocare/Seriale/Mr.Robot/Mr.Robot.S04/mr.robot.s04e09.1080p.bluray.x264-rovers.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-05-17 20:20:01.220 +00:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: "Jellyfin MPV Shim", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 2147483000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 1280000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 5, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: null, Type: Audio, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264,h265,hevc,mpeg4,mpeg2video", AudioCodec: "aac,mp3,ac3,opus,flac,vorbis", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "jpeg", Type: Photo, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }] }
[2021-05-17 20:20:01.224 +00:00] [INF] User policy for "albertgg". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2021-05-17 20:20:01.224 +00:00] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 10337979, max bitrate: 8000000
[2021-05-17 20:20:01.224 +00:00] [INF] Profile: "Jellyfin MPV Shim", Path: "/media/stocare/Seriale/The.Walking.Dead/The.Walking.Dead.S09.1080p.BluRay.x264-ROVERS[rartv]/the.walking.dead.s09e01.1080p.bluray.x264-rovers.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
```

**Comment by Albert24GG** [comment] 2021-05-18 19:41
It seems that the media will only play if the second and the third options are checked (for all media i have)
![image](https://user-images.githubusercontent.com/79106176/118713004-24c59d80-b82a-11eb-88b5-dfd65f070c00.png)
Can anyone help me?

**Comment by crobibero** [comment] 2021-05-18 21:02
Duplicate of https://github.com/jellyfin/jellyfin/issues/6034.
This is a known issue, already has a merged PR: https://github.com/jellyfin/jellyfin/pull/6022

**Closed by crobibero** 2021-05-18 21:02 UTC
Labels: bug
