### ISSUE TITLE
Track stop playing 

### ISSUE THREAD

**Issue by jee-r** [jellyfin/jellyfin#1471] opened 2019-06-18 16:31 UTC
**Describe the bug**

Stop playing on certain audio Track (flac) for 3-5min then jellyfin continue.
This bug append only on certain track and always on the same time of the track and **only on Firefox** not on chromium.

**To Reproduce**

- install jellyfin 10.3.5 via docker 
- access to jelyfin on LAN via latest firefox (clean Profile) on an other computer ( i don't tested it on localhost )
- play the track who cause this issue (I can provide the track ~~in private on the matrix channel~~ just ping me here)

**Expected behavior**

play without stopping :)

**Logs**
```
[2019-06-18 16:00:10.502 +00:00] [WRN] "GetItemList" query time (slow): 162.8253. Query: "select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,ProviderIds,Images,TotalBitrate,ExtraType,ExternalId,OwnerId from TypedBaseItems A where type=@type AND CleanName=@Name"
[2019-06-18 16:00:14.854 +00:00] [WRN] HTTP Response 206 to "172.18.0.1". Time (slow): 0:07:40.7878309. "http://192.168.1.52:8096/emby/Audio/f69dcd8c95a4d20d3beaba73ee65aa06/universal?UserId=48a65ef1b7104eb89396345b079ef931&DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY3LjB8MTU2MDg3MzMzMzA5NQ11&MaxStreamingBitrate=140000000&Container=opus,mp3%7Cmp3,aac,m4a%7Caac,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1560873333360&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false"
[2019-06-18 16:00:14.894 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.3.5" playing "DEUTSCHLAND". Stopped at "92786" ms
[2019-06-18 16:00:14.898 +00:00] [INF] Playback Stopped
[2019-06-18 16:00:14.900 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:15.013 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:15.015 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=0-" Content-Length: "40771974", Content-Range: "bytes 0-40771973/40771974"
[2019-06-18 16:00:15.058 +00:00] [INF] Playback Started
[2019-06-18 16:00:17.687 +00:00] [WRN] HTTP Response 206 to "172.18.0.1". Time (slow): 0:00:02.6773612. "http://192.168.1.52:8096/emby/Audio/f69dcd8c95a4d20d3beaba73ee65aa06/universal?UserId=48a65ef1b7104eb89396345b079ef931&DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY3LjB8MTU2MDg3MzMzMzA5NQ11&MaxStreamingBitrate=140000000&Container=opus,mp3%7Cmp3,aac,m4a%7Caac,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1560873333361&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false"
[2019-06-18 16:00:17.694 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:17.696 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=23625728-" Content-Length: "17146246", Content-Range: "bytes 23625728-40771973/40771974"
[2019-06-18 16:00:17.716 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:17.718 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=15073280-" Content-Length: "25698694", Content-Range: "bytes 15073280-40771973/40771974"
[2019-06-18 16:00:17.739 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:17.741 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=10780672-" Content-Length: "29991302", Content-Range: "bytes 10780672-40771973/40771974"
[2019-06-18 16:00:17.762 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:00:17.764 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=8650752-" Content-Length: "32121222", Content-Range: "bytes 8650752-40771973/40771974"
[2019-06-18 16:00:57.385 +00:00] [INF] WS "http://192.168.1.52:8096/embywebsocket?api_key=654ae256865f49e0b8723e59675f13fa&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY3LjB8MTU2MDg3MzM1ODY4Nw11". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
[2019-06-18 16:05:40.466 +00:00] [INF] Saving system configuration
[2019-06-18 16:05:40.480 +00:00] [INF] Setting cache path to /cache
[2019-06-18 16:05:52.678 +00:00] [WRN] HTTP Response 206 to "172.18.0.1". Time (slow): 0:05:34.9199858. "http://192.168.1.52:8096/emby/Audio/f69dcd8c95a4d20d3beaba73ee65aa06/universal?UserId=48a65ef1b7104eb89396345b079ef931&DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY3LjB8MTU2MDg3MzMzMzA5NQ11&MaxStreamingBitrate=140000000&Container=opus,mp3%7Cmp3,aac,m4a%7Caac,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1560873333361&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false"
[2019-06-18 16:05:52.682 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.3.5" playing "DEUTSCHLAND". Stopped at "92767" ms
[2019-06-18 16:05:52.683 +00:00] [INF] Playback Stopped
[2019-06-18 16:05:52.700 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:05:52.773 +00:00] [INF] User policy for "Itsme". EnableAudioPlaybackTranscoding: False
[2019-06-18 16:05:52.776 +00:00] [INF] Setting range response values for "/media/Music/FLAC/Rammstein - RAMMSTEIN (2019)/01 - DEUTSCHLAND.flac". RangeRequest: "bytes=0-" Content-Length: "40771974", Content-Range: "bytes 0-40771973/40771974"
[2019-06-18 16:05:52.831 +00:00] [INF] Playback Started
[2019-06-18 16:07:45.422 +00:00] [INF] WS "http://192.168.1.52:8096/embywebsocket?api_key=654ae256865f49e0b8723e59675f13fa&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzY3LjB8MTU2MDg3MzM1ODY4Nw11". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

**Screenshots**

**System (please complete the following information):**
 - Host : Nas Synology DSM6 
 - Docker: jellyfin/jellyfin:10.3.5
 - Network: LAN
 - Browser: Firefox
 - Jellyfin Version: 10.3.5
 - Reverse proxy: no proxy

**Additional context**
i try with and without transcoding enable but no change

**Comment by sparky8251** [comment] 2019-06-25 11:22
You aren't the only one with this issue. Based on my own testing, this first showed up during the 10.2.0 RC release cycle and I have noticed some other odd trends.

* For me, the track that stopped playback is *mostly* random but it does have some consistency. It's more of the position in the playlist than it is a track though.

* When the playback stalls, its has ALWAYS stalled between 50 and 60 seconds into a track. Usually on the side of 50 with 52 seconds being the most common.

* The progress report API is pinged every 10 seconds like normal even though all playback has stopped.

* When the end of the track is reached, playback resumes normally. This one is a bit odd so I'll try and explain... If a track is 3:32 long and playback stopped at 0:52 I have to put up with EXACTLY 2:40 of silence before the remaining 2:40 of music plays

The odd thing is, I reverted far far back to older versions of JF and spent a long while bisecting the git tree to find what might have caused this odd regression and was completely unable to. 

Maybe it is something in the backend that caused this (I only checked the frontend), but given this works fine in Chrome I'm leaning towards a Firefox update broke things.

More testing is required...

**Comment by pagdot** [comment] 2019-11-11 17:50
I have the same problem (also Firefox, not tested on Chrome). Similar to a broken CD which keeps hanging it helps to advance the cursor/current position by a few seconds and it continues playing, if I move the cursor, it stops at the same position again

**Comment by JustAMan** [comment] 2019-11-22 12:04
This looks somewhat similar to video premature stop bug, so let's try to check for the same issues there:
1) is this file being transcoded/remuxed, or served "as is"?
2) does this stop happen when you resume a playback or seek somewhere, or does it also happen if you start the track from the very beginning?

**Comment by pagdot** [comment] 2019-11-22 12:18
@JustAMan 

1. I don't know. How can I check?
2. Pause + Play doesn't help, Seeking a few seconds forwards helps. I think after seeking back it stops again at the same time. Haven't tried starting the track from the beginning

**Comment by JustAMan** [comment] 2019-11-22 13:00
Enabling debug logging (per https://github.com/jellyfin/jellyfin-docs/issues/159#issue-527168291) and posting a fuller log here might help.

**Comment by pagdot** [comment] 2019-11-22 13:13
I've just captured the Firefox Debug-Console log:

```
Requesting url without automatic networking: https://<jellyfin>/Users/<userid>/Items?ParentId=6d01a286879dcd359eedd937e4f8411d&Filters=IsNotFolder&Recursive=true&SortBy=SortName&MediaTypes=Audio%2CVideo&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/System/Endpoint apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Playback/BitrateTest?Size=500000 apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Playback/BitrateTest?Size=1000000 apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Playback/BitrateTest?Size=3000000 apiclientcore.js:264:21
playing url: https://<jellyfin>/Audio/c8f8d1d6c9048571e096a78ff42515d2/universal?UserId=<userid>&DeviceId=<deviceid>&MaxStreamingBitrate=32307692&Container=opus%2Cmp3%7Cmp3%2Caac%2Cm4a%7Caac%2Cflac%2Cwebma%2Cwebm%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=<api-key>&PlaySessionId=1574427265123&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false plugin.js:133:21
requesting url: https://<jellyfin>/Audio/c8f8d1d6c9048571e096a78ff42515d2/universal?UserId=<userid>&DeviceId=<deviceid>&MaxStreamingBitrate=32307692&Container=opus%2Cmp3%7Cmp3%2Caac%2Cm4a%7Caac%2Cflac%2Cwebma%2Cwebm%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=<api-key>&PlaySessionId=1574427265123&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false fetchhelper.js:103:17
response status: 200, url: https://<jellyfin>/Audio/c8f8d1d6c9048571e096a78ff42515d2/universal?UserId=<userid>&DeviceId=<deviceid>&MaxStreamingBitrate=32307692&Container=opus%2Cmp3%7Cmp3%2Caac%2Cm4a%7Caac%2Cflac%2Cwebma%2Cwebm%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=<api-key>&PlaySessionId=1574427265123&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false fetchhelper.js:107:21
Active player: {"name":"Html Audio Player","id":"htmlaudioplayer","playerName":"Html Audio Player","playableMediaTypes":[true,false,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","PlayMediaSource","PlayTrailers","ToggleFullscreen"]} playbackmanager.js:1033:25
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Users/<userid>/Items/c8f8d1d6c9048571e096a78ff42515d2 apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
app is hidden apphost.js:203:21
triggering app resume event apphost.js:195:21
opening web socket with url: wss://<jellyfin>/socket?api_key=<api-key>&deviceId=<deviceid> apiclientcore.js:351:225
Firefox can’t establish a connection to the server at wss://<jellyfin>/socket?api_key=<api-key>&deviceId=<deviceid>. apiclientcore.js:352:24
web socket closed apiclientcore.js:152:21
nulling out web socket apiclientcore.js:152:91
app is hidden apphost.js:203:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
Requesting url without automatic networking: https://<jellyfin>/Sessions/Playing/Progress apiclientcore.js:264:21
```

Just did some more testing (reload tab, try in private tab, restart firefox) and it seems like Firefox/Jellyfin is having a problem with this specific track on one specific position.

After downloading the file using the url from "playing url" of the log and playing the downloaded file in firefox, chrome, a native player and vlc, firefox was the only player having problems.

When comparing the logs, @jee-r may have a different issue than me, but I'll keep looking into it when issues occur on other files

**Comment by JustAMan** [comment] 2019-11-22 13:16
If you can reproduce this hiccup using a local copy of the file in Firefox it seems you should better report this as an issue in Firefox, not Jellyfin :)

**Comment by joytrekker** [comment] 2019-12-29 19:50
This seems to be a Firefox bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1528265

Both Jellyfin and Plex stop playback on some of my flac files when using Firefox. The flac files are verified by the official flac encoder and play fine in Chrome.

**Comment by jee-r** [comment] 2019-12-29 22:07
@[GitHub](github.com)

I hadn’t seen that bug report thnak’s for pointing this out @joytrekker

#jellyfin #flac #firefox

(Originally published at: https://jeer.fr/micro/1577657209)

**Comment by JustAMan** [comment] 2020-01-10 12:45
Closing as this seems to be Firefox-caused issue, something we have no control over.

**Closed by JustAMan** 2020-01-10 12:45 UTC
Labels: bug, help wanted, regression

**Comment by dannymichel** [comment] 2020-02-20 08:20
> Closing as this seems to be Firefox-caused issue, something we have no control over.

nope chrome too

**Comment by pagdot** [comment] 2020-02-20 08:26
Do you have the problem with the same file in multiple browsers?

Have you downloaded the file and tested it with vlc (or another multimedia player).

Have you tested opening the downloaded file in the tested browser?

I've tested the same file with multiple Browsers (playing from Jellyfin and the downloaded file directly) and only Firefox had problems playing the file and even if I opened the downloaded copy.

@dannymichel Maybe your file is broken or this is a new issue
