### ISSUE TITLE
DVD Order for TMDB not working?

### ISSUE THREAD

**Issue by Rorschach1010** [jellyfin/jellyfin#5137] opened 2021-01-30 19:18 UTC
**Describe the bug**
When changing a series from airing order to dvd order, nothing changes. It does work for TVDB but TMDB is somehow not working. Not sure if this is even implemented?

**System (please complete the following information):**
 - OS: [Manjaro Linux]
 - Virtualization: [KDE Plasma]
 - Clients: [Server]
 - Browser: [Vivaldi]
 - Jellyfin Version: [10.6.4]

**To Reproduce**
Change to dvd order in the metadata manager while only using TMDB plugin for TV shows and scan and replace all metadata.

**Expected behavior**
When replacing all metadata, I expect it to show the new season order.

**Comment by Ullmie02** [comment] 2021-02-07 17:33
DVD Ordering is currently not implemented for TMDB

**Comment by Rorschach1010** [comment] 2021-02-07 22:35
> DVD Ordering is currently not implemented for TMDB

I see, no wonder it doesn't work. Are there plans to implement this feature for TMDB too? I think they call it Episode Groups and have an API for it. Honestly speaking, I feel like TVDB falls behind TMDB even for TV shows for quiet some time now.

In any way, this answered my initial question.

**Comment by Ullmie02** [comment] 2021-02-08 07:48
I don't think someone is currently working on it. But I added the feature lable so we know it's a missing feature and someone can implement it

**Comment by Rorschach1010** [comment] 2021-02-08 08:09
Alright, thank you very much.

**Comment by cvium** [comment] 2021-04-20 07:40
Duplicate of https://github.com/jellyfin/jellyfin/issues/5042

**Closed by cvium** 2021-04-20 07:40 UTC
Labels: confirmed, feature
