### ISSUE TITLE
[Issue]: Comic / Manga reader doesn't fit screen correctly 

### ISSUE THREAD

**Issue by Kalidibus** [jellyfin/jellyfin#8274] opened 2022-08-16 13:12 UTC
### Please describe your bug

Issue: When attempting to read any manga / comic files in my library, it does not fit my phone screen correctly. A quarter or so of the page is cut off, and you cannot swipe over to see it without going to the next page. This issue is worse with two page spreads (common in manga). 

Steps to reproduce:
1. initiate comic library (Books library type)
2. Open a cbz cbr or jpg file to read
3. Page is cutoff and cannot be panned

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Manjaro
- Virtualization: No
- Clients: Android Web client
- Browser: Brave Android Web Browser
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: None
- Reverse Proxy: None
- Base URL: local IP
- Networking: local IP
- Storage: home server internal 4TB Western Digital Red drive.
```

### Jellyfin logs

```shell
[2022-08-16 09:05:34.397 -04:00] [INF] [52] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.217" request
[2022-08-16 09:06:58.418 -04:00] [INF] [173] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-08-16 09:07:10.419 -04:00] [INF] [195] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2022-08-16 09:08:14.971 -04:00] [INF] [115] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.4.4" playing "Vol. 4". Stopped at "2" ms
```

### FFmpeg logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-08-16 13:23
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/3378

**Closed by crobibero** 2022-08-16 13:23 UTC
Labels: bug
