### ISSUE TITLE
Recently Added Does Not Work With NFS

### ISSUE THREAD

**Issue by D347HxD** [jellyfin/jellyfin#1393] opened 2019-05-20 16:13 UTC
**Describe the bug**
Recently Added is not being updated when new items are added to my libraries.
Others confirmed it is not only me: 
https://i.godhub.xyz/05-20-2019-HZjPoYuP2q.png

**To Reproduce**

1. Set up a network share as a library
2. Upload new content to library
3. Scroll down to Recently Added and see its not in the correct order

**System (please complete the following information):**
 - OS: Ubtuntu 18.04
 - Browser: Chrome
 - Jellyfin Version:  10.2.2
 - Reverse proxy: Nginx

**Comment by sparky8251** [comment] 2019-06-25 19:35
To me, this seems like an NFS issue. Maybe it hasnt properly synced file metadata or something.

We definitely need someone to sit down and determine where the fault lies before we can really proceed.

**Comment by ferferga** [comment] 2019-09-25 22:13
I'm also having this issue, although I'm using FUSE. The movies did not update since the first library scan that was made.

**Comment by JustAMan** [comment] 2019-10-10 13:19
What are your mount options? I think JF relies here on the underlying filesystem to report file modification time and such, so if your mounts (be them FUSE or NFS) don't expose that or are exposing them wrongly that might be the issue.

**Comment by truenicoco** [comment] 2019-12-13 10:22
I experiences this as well. If I understand correctly, [this might be a limitation of NFS](https://stackoverflow.com/a/4231277/5902284). Since additions to the NFS share all come from sonarr and radarr, I just had to configure them to trigger jellyfin library updates after they succesfully download a file.

**Comment by telans** [comment] 2019-12-13 10:39
Is the original issue here about NFS not picking up on new files without a scan, or metadata/media-date being out of order? The former is known pretty well I believe, and your link covers it @truenicoco 

But I don't think that's what this is about

**Comment by truenicoco** [comment] 2019-12-13 10:41
Oh OK, sorry then!

**Comment by nonooo** [comment] 2020-01-03 18:14
my understanding is that the "classification" is working as expected *but* the import process does not.

if you click on edit metadata of an imported movie, you can see that the date is the one of the file (which is wrong if you import very old file, and could possibly be correct if this is a new downloaded file) one easy way to correct is to not rely on the filesystem at all to get a date and just use the getdate constant.

**Comment by nonooo** [comment] 2020-01-03 19:52
so after more searching, there is no bug (simply a strange option which is activated by default) so this is the procedure to have this working.

(my installation is in french so I am not completely certain of the english translation)

1/ go to "tableau de bord" (dashboard)
2/ go to "médiathèques" (media library)
3/ switch to tab "affichages" (showing?)
4/ change the first drop down list "choix de la date d'ajout" to "utiliser la date d'ajout dans la médiathèque"

![image](https://user-images.githubusercontent.com/1590332/71745605-df8a1100-2e6a-11ea-9223-28d509712f77.png)


voili voilou! enjoy...

**Comment by JustAMan** [comment] 2020-01-10 13:31
I am feeling this is working as intended (both with option set and without).
I'm going to close the issue, feel free to disagree with me and I can re-open it back if you can prove me wrong.

**Closed by JustAMan** 2020-01-10 13:31 UTC
Labels: bug, help wanted
