### ISSUE TITLE
Error in MigrateDisplayPreferencesDatabase updating from 10.6.4 to 10.7.0

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin#4844] opened 2020-12-21 22:27 UTC
**Describe the bug**
I’m getting an error during the display preferences database migration process after trying to test 10.7.0. I copied my docker volume to a new volume so that I could run it alongside my 10.6.4 container. I was originally using the linuxserver image, and I receive this error using linuxserver/jellyfin:nightly, jellyfin/jellyfin:stable-rc, and jellyfin/jellyfin:unstable for the new container.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: linuxserver 10.6.4-1-ls87 —> jellyfin 10.7.0 rc1 (and the most recent unstable build posted a couple hours ago)
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: AudioDB, InfuseSync, MusicBrainz, OMDb, Open Subtitles, TheTVDB, Trakt
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1. Have a functioning container running 10.6.4 (using the linuxserver image — maybe relevant?)
2. Create a new docker volume and copy the contents of the old volume into it.
3. Run a new container using the stable-rc tag or the unstable tag, changing the JELLYFIN_DATA/CONFIG/CACHE/LOG_DIR environment paths as needed to move from the linuxserver image.
4. Observe the logs for the error.

**Expected behavior**
Migration completes successfully and Jellyfin starts. 

**Logs**
```
[17:00:46] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateDisplayPreferencesDatabase'
[17:00:46] [WRN] [1] Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb: User with ID 97324e44-dd17-4ba0-89d4-a82e3df66f49 does not exist in the database, skipping migration.
[17:00:46] [WRN] [1] Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb: User with ID b0749b39-4489-46aa-a445-0ea83fdcffed does not exist in the database, skipping migration.
[17:00:46] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateDisplayPreferencesDatabase'
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: DisplayPreferences.UserId, DisplayPreferences.ItemId, DisplayPreferences.Client'.   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
[17:00:46] [FTL] [1] Main: Error while starting server.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: DisplayPreferences.UserId, DisplayPreferences.ItemId, DisplayPreferences.Client'.   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Migrations.Routines.MigrateDisplayPreferencesDb.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[17:00:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[17:00:46] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[17:00:46] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Additional Context**
I also get errors related to the plugins, but I left that part of the log out since that bug is already being addressed from what I can tell.

**Comment by crobibero** [comment] 2020-12-21 22:56
Duplicate of https://github.com/jellyfin/jellyfin/issues/4694

**Closed by crobibero** 2020-12-21 22:56 UTC
Labels: bug
