### ISSUE TITLE
media library covers do not support GIF images

### ISSUE THREAD

**Issue by boyxiaopang** [jellyfin/jellyfin#5593] opened 2021-03-22 13:32 UTC
- OS: [synology]
 - Virtualization: [Docker]
 - Clients: [Browser]
 - Browser: [Chrome 80]
 - Jellyfin Version: [10.7.1]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [douban,tmdb]
 - Reverse Proxy: [nginx]
 - Base URL: [none]
 - Networking: [Bridge]
 - Storage: [local]

**To Reproduce**
the media library covers do not support GIF images
I don't know if this is a bug or not
but version 10.6.4 can display uploaded GIF covers
**Screenshots**
![image](https://user-images.githubusercontent.com/12150291/111997544-1b83c180-8b56-11eb-9885-7f05b9dfc4a1.png)

**Comment by cvium** [comment] 2021-03-22 14:18
duplicate of #5501

**Closed by cvium** 2021-03-22 14:18 UTC
Labels: bug
