### ISSUE TITLE
Live TV Fails, File In Use

### ISSUE THREAD

**Issue by gary-hammer** [jellyfin/jellyfin#5491] opened 2021-03-11 15:11 UTC
**Describe the bug**
On  a fresh install, after configuring live tv, attempt to play any channel, get nothing on screen except a spinner.

**System (please complete the following information):**
 - OS: Pop!OS 20.10
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.0
 - Playback: Doesn't playback, looks like it is trying to transcode though.
 - Installed Plugins: TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. Go to Live TV
2. Click on any current program
3. See error

**Expected behavior**
Should play.

**Logs**
See attached files.

**Additional context**
Using a HDHR which was found and configured with no problem.

[jf-error.txt](https://github.com/jellyfin/jellyfin/files/6123925/jf-error.txt)
[jf-startup.txt](https://github.com/jellyfin/jellyfin/files/6123926/jf-startup.txt)

**Comment by crobibero** [comment] 2021-03-11 15:16
Duplicate of 
https://github.com/jellyfin/jellyfin/issues/5427
https://github.com/jellyfin/jellyfin/issues/5438

And already fixed by https://github.com/jellyfin/jellyfin/pull/5444

**Closed by crobibero** 2021-03-11 15:16 UTC
Labels: bug
