### ISSUE TITLE
Playback stops if transcoding directory is full

### ISSUE THREAD

**Issue by ich777** [jellyfin/jellyfin#5151] opened 2021-02-02 08:10 UTC
**Description**
Video playback stops if transcoding directory is out of space and reaches the last part that was transcoded.

**System:**
 - OS: Unraid 6.9.0RC2
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Firefox
 - Jellyfin Version: latest from DockerHub
 - Playback: Transcode
 - Installed Plugins:none (only the standard ones)
 - Reverse Proxy: none (local access)
 - Base URL: SERVERIP:8096
 - Networking: Bridge
 - Storage: local

**Steps to Reproduce**
1. Add `--mount type=tmpfs,destination=/tmp,tmpfs-size=500000000` to your `docker run` command (this creates a tmpfs in the /tmp directory, in this example with 500MB).
2. Go to your settings and set the directory for transcoding to '/tmp' and click save.
3. Open up a video file and force it to transcode (should be a big file so that the transcoding buffer is filled up quickly)
4. After the directory is filled up it ends transocding and won't transcode any further
5. The video plays fine until it reaches the timecode where it ended transocding because it's out of space and the video is stale
    (You can still click on the 'Back' button to go back to the Menu, after doing that the transcoding directory is cleaned)

**Expected behavior**
Playback shouldn't stop after the directory is filled up instead it should slowly delete the oldest file in the directory that was transcoded so that it playback never stops.

**Logs**
No error logs

**Screenshots**
Not applicable

**Additional context**
I recently came across [this thread](https://forums.unraid.net/topic/35878-plex-guide-to-moving-transcoding-to-ram/) in the Unraid forums where it was discussed how to set up a tmpfs with a mount from the host '/tmp/ to the container '/tmp' directory, but it was also discussed that this is not an ideal solution because when the RAM is filled up the server crashes, so a script was written to limit the amount of RAM that this directory inside the container can use and not cause a server crash ([this was the link to the script](https://forums.unraid.net/topic/35878-plex-guide-to-moving-transcoding-to-ram/?do=findComment&comment=894460) but it is now changed to the easier method like described above to put the command in the `docker run` command) to not stress the hard drives when transcoding.
The problem is that this works flawlessly with Plex (Plex deletes the oldest transcoded file if it reaches a certain level of use in the directory, about 90%, and a certain timecode) but Jellyfin will stale if it runs out of space and the playback stops after it reaches the last file that was transcoded in the transocding directory.

Hope someone can help with this and this is relatively easy solvable.

**Comment by cvium** [comment] 2021-04-20 10:49
Duplicate of https://github.com/jellyfin/jellyfin/issues/3929. And it's not technically a bug, but a feature request.

**Closed by cvium** 2021-04-20 10:49 UTC
Labels: bug
