### ISSUE TITLE
[Issue]: Multiple entries(Profiles?) same actor/actress

### ISSUE THREAD

**Issue by FairlyBored** [jellyfin/jellyfin#8906] opened 2022-12-14 00:46 UTC
### Please describe your bug

Jellyfin seems to create actor/actress pages based on their names rather than an ID such as IMDB ID or MovieDB ID, and some times people will change the spelling of actors/actresses over time(or the person themselves may change their name) causing multiple pages for the same person, and their filmography to be split up.

For example, I previously added [The Bad Guys: Reign of Chaos (2019)](https://www.themoviedb.org/movie/585831) to my server, then later added [Catch Me (2013)](https://www.themoviedb.org/movie/245597). The actress [Kim A-joong](https://www.themoviedb.org/person/84973-kim-ah-joong) is in both, but she had two separate entries in Jellyfin for me and if you look at the changes for her page you'll see someone changed her name from "Kim Ah-joong" to "Kim A-joong". And if you look further into the changes people have spelled her name in even more different ways previously. And both pages in Jellyfin link to the same ID on IMDB and MovieDB. I have come across this quite a number of time with different people.

One of my favourite things about Jellyfin vs Plex was unified filmography pages for Movies and TV, and being able to find everything I have with a specific person in one place. But this kind of ruins that.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-01-07 23:11
Duplicate of https://github.com/jellyfin/jellyfin/issues/3356

**Closed by crobibero** 2023-01-07 23:11 UTC
Labels: bug
