### ISSUE TITLE
[Issue]: Deleting a music file does not remove it from the display.

### ISSUE THREAD

**Issue by Sparxva** [jellyfin/jellyfin#11087] opened 2024-03-01 18:41 UTC
### Please describe your bug

I am running jellyfin in the Chrome browser on Ubuntu Linux 20.04.6 LTS.  

In the browser window, when I delete a music media file it does not remove it from the media files shown in the browser window, but it apparently does delete the file.  Subsequent attempts to play the file play the next file down on the screen, not the one shown.  This can result in unintentionally deleting the wrong file since the information shown does not match the actual file.  I have worked around the bug by forcing a refresh of the browser window after each file deletion and that seems to work well.

### Reproduction Steps

In Chrome Version 122.0.6261.94 (Official Build) (64-bit) on Ubuntu 20.04.6 LTS, select songs, delete a song.  The display does not update.  Selecting the song after this point will instead be playing the next song down on the list.  I was deleting duplicates and accidentally deleted the wrong files.  I worked around the problem by forcing a reload of the web page after each song deletion.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- Linux Kernel: 5.15.0-97-generic
- Virtualization: no
- Clients: Chrome browser
- Browser: Chrome 
- FFmpeg Version: 4.2.7
- Playback Method: 
- Hardware Acceleration: yes, graphics acceleration is turned on.
- GPU Model: Intel HD Graphics 4000
- Plugins: Adblocker Stands, Nordpass, Screen recorder, strong password generator
- Reverse Proxy: n/a
- Base URL: 192.168.3.50
- Networking: Accessing jellyfin from the same machine
- Storage: local hard drive
```

### Jellyfin logs

```shell
[2024-03-01 13:28:52.423 -05:00] [INF] User policy for "jellyfin". EnableAudioPlaybackTranscoding: True
[2024-03-01 13:28:54.751 -05:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.8.13" playing "(Audio Book) Brian Tracy - HOW TO MASTER YOUR TIME - 3B - Project Management". Stopped at "1518" ms
[2024-03-01 13:28:57.180 -05:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-03-01 13:29:01.319 -05:00] [INF] Removing item, Type: "Audio", Name: "(Audio Book) Brian Tracy - HOW TO MASTER YOUR TIME - 3B - Project Management", Path: "/home/mpender/Music/iTunes/iTunes Media/Music/Unknown Artist/Unknown Album/(Audio Book) Brian Tracy - HOW TO MASTER YOUR TIME - 3B - Project Management.mp3", Id: 6a342185-2e5b-8bb4-ad8a-d92a4f946bc8
[2024-03-01 13:29:01.361 -05:00] [INF] Deleting item path, Type: "Audio", Name: "(Audio Book) Brian Tracy - HOW TO MASTER YOUR TIME - 3B - Project Management", Path: "/home/mpender/Music/iTunes/iTunes Media/Music/Unknown Artist/Unknown Album/(Audio Book) Brian Tracy - HOW TO MASTER YOUR TIME - 3B - Project Management.mp3", Id: 6a342185-2e5b-8bb4-ad8a-d92a4f946bc8
[2024-03-01 13:29:06.616 -05:00] [INF] WS "192.168.3.50" closed
[2024-03-01 13:29:07.262 -05:00] [INF] WS "192.168.3.50" request
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.345 -05:00] [WRN] The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:29:07.346 -05:00] [WRN] The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2024-03-01 13:30:01.382 -05:00] [INF] "Untitled - 04-29-02 (2)" ("/home/mpender/Music/iTunes/iTunes Media/Music/Unknown Artist/Unknown Album") will be refreshed.
```

### Please attach any browser or client logs here

Stored JSON credentials: {"Servers":[{"DateLastAccessed":1709317050544,"LastConnectionMode":2,"ManualAddress":"http://192.168.3.50:8096","manualAddressOnly":true,"Name":"Scarlet","Id":"bf3d0577cff949b6a1e2b3264ea8357f","LocalAddress":"http://192.168.3.50:8096","AccessToken":"350c87e516124894a2e032650a07e51d","UserId":"c62ad23706c54bcebbcb3a6479b0f417"}]}
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Begin ConnectionManager constructor
8main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Translation dictionary is empty.
Te @ main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 returning instance from getOrAddApiClient
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 defining core routes
3main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 failed to fetch the web config file: SyntaxError: Expected ',' or ']' after array element in JSON at position 639 (line 33 column 22)
    at main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:415706
    at u (main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:1091722)
    at Generator._invoke (main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:1091510)
    at Generator.next (main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:1092147)
    at i (main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:414328)
    at s (main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2:414531)
(anonymous) @ main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 loading installed plugins
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 loading packages
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 getTryConnectPromise http://192.168.3.50:8096
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 ConnectionManager requesting url: http://192.168.3.50:8096/system/info/public
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 fetchWithTimeout: timeoutMs: 20000, url: http://192.168.3.50:8096/system/info/public
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 fetchWithTimeout: succeeded connecting to url: http://192.168.3.50:8096/system/info/public
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 ConnectionManager response status: 200, url: http://192.168.3.50:8096/system/info/public
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Reconnect succeeded to http://192.168.3.50:8096
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 ConnectionManager requesting url: http://192.168.3.50:8096/System/Info
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 ConnectionManager response status: 200, url: http://192.168.3.50:8096/System/Info
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 returning instance from getOrAddApiClient
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Setting server address to http://192.168.3.50:8096
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting url without automatic networking: http://192.168.3.50:8096/Sessions/Capabilities/Full
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 calling apiClient.ensureWebSocket
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 opening web socket with url: ws://192.168.3.50:8096/socket?api_key=350c87e516124894a2e032650a07e51d&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTcwODk5Nzc1Mzc2OQ11
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Users/c62ad23706c54bcebbcb3a6479b0f417
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 returning instance from getOrAddApiClient
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/DisplayPreferences/usersettings?userId=c62ad23706c54bcebbcb3a6479b0f417&client=emby
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 web socket connection opened
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Sessions?ControllableByUserId=c62ad23706c54bcebbcb3a6479b0f417
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Sending web socket message: KeepAlive
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 resolving connectToServers with result.State: SignedIn
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Users/c62ad23706c54bcebbcb3a6479b0f417/Items/7e64e319657a9516ec78490da03edccb
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Users/c62ad23706c54bcebbcb3a6479b0f417/Views
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Users/c62ad23706c54bcebbcb3a6479b0f417/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=MusicAlbum&Recursive=true&Fields=PrimaryImageAspectRatio%2CSortName%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&StartIndex=0&Limit=100&ParentId=7e64e319657a9516ec78490da03edccb
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting url without automatic networking: http://192.168.3.50:8096/DisplayPreferences/usersettings?userId=c62ad23706c54bcebbcb3a6479b0f417&client=emby
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/Users/c62ad23706c54bcebbcb3a6479b0f417/Items?SortBy=Album%2CSortName&SortOrder=Ascending&IncludeItemTypes=Audio&Recursive=true&Fields=AudioInfo%2CParentId&StartIndex=0&ImageTypeLimit=1&EnableImageTypes=Primary&Limit=100&ParentId=7e64e319657a9516ec78490da03edccb
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting url without automatic networking: http://192.168.3.50:8096/DisplayPreferences/usersettings?userId=c62ad23706c54bcebbcb3a6479b0f417&client=emby
main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Requesting http://192.168.3.50:8096/System/Endpoint
6main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Sending web socket message: KeepAlive
ruleApplier.js:1 Uncaught SyntaxError: Identifier 'observeDomChanges' has already been declared (at ruleApplier.js:1:1)
VM187:1 Uncaught TypeError: Cannot redefine property: googletag
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:196
    at <anonymous>:1:524
4main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Sending web socket message: KeepAlive
3main.jellyfin.bundle.js?d5f64bca077b6d6aaf33:2 Sending web socket message: KeepAlive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by foss-** [comment] 2024-06-20 13:05
This is a dupe of https://github.com/jellyfin/jellyfin/issues/9259 right?

**Comment by felix920506** [comment] 2024-06-20 18:28
Looks like #9259 duplicate, closing

**Closed by felix920506** 2024-06-20 18:28 UTC
Labels: bug
