### ISSUE TITLE
[Issue]: Network page not saving - An invalid form control with name='' is not focusable.

### ISSUE THREAD

**Issue by robvdl** [jellyfin/jellyfin#7454] opened 2022-03-13 10:26 UTC
### Please describe your bug

I'm not entirely sure how I managed to do this, but every time I hit save under Advanced -> Networking, nothing happens. It did save once or twice before, but isn't anymore now.

In the JS console I see this:

An invalid form control with name='' is not focusable.

I can't work out which control it's talking about.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: Docker https://hub.docker.com/r/linuxserver/jellyfin
- Clients:
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Not enabled
- Plugins: Default set of plugins
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robvdl** [comment] 2022-03-13 10:33
I backed up network.xml, stopped the Docker container, deleted network.xml, started it up again and let it auto create the file again and everything is fine again.

I can compare network.xml against the backed up copy to see how it got into this "state". See if I can find any differences perhaps. Something I set caused it to get in a mode where I couldn't save network settings anymore.

**Comment by robvdl** [comment] 2022-03-13 10:40
OK I did a diff between the broken network.xml and the one it recreated, and it seems the broken one this entire line was missing from it:

`<EnableUPnP>false</EnableUPnP>`

I can't explain how I did that, but I didn't do any manual editiging of this file at all ... weird.

**Comment by crobibero** [comment] 2022-03-13 12:52
Closing as duplicate of https://github.com/jellyfin/jellyfin-web/issues/3440

This is not a server issue.

**Closed by crobibero** 2022-03-13 12:52 UTC
Labels: bug
