### ISSUE TITLE
Movies pile up in continue watching, all starting at 17:09 !~

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#12726] opened 2024-09-26 20:13 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I've add this extremely odd issue for a while, I'd say after migration from 10.8 to 10.9.
I'm 10.9.11 now. I can't find a precise pattern for it yet unfortunately, but many movies just added are already classified in Continue Watching because Jellyfin wrongly set that they have been watched until 17m09s.

I know, how odd, and I don't see anyone having the issue.

It's very clear in the Android TV app because the time are displayed in clear, whereas in the native Web UI, it's only the blue bar at the bottom of the posters that can give you an indication.

I started to suspect something was weird because I had so many movies in the Continue Watching section. I'd then click on watched and then unwatched (when I had not seen them) to make them disappear from the section but it didn't seem to work and I kept having more and more.

Now I realise that sometimes, movies I've started and want to continue watching lost their time tracking and also start at 17:09. Many, but not all of them. 

I know this is not a very accurate report, at least not making any reproduction of the issue possible.
But I'm really at a loss here, can't find any pattern, and no logs of course.

I'm adding a pic to illustrate, even though not really useful.
See for instance here, in recently added movies: none of them have been opened but all of them are tracked as "watched until 17:09" except Austerlitz.
Barbara has been watched but it still in gthe Continue watching section ... 
<img width="1800" alt="Screenshot 2024-09-26 at 21 59 32" src="https://github.com/user-attachments/assets/c33120ab-b711-4e8a-a61c-76f1ecf03180">

### Reproduction steps

Can't provide yet

### What is the current _bug_ behavior?

explained above

### What is the expected _correct_ behavior?

correct watched time tracking

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: container
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Nothing relevant yet, unless someone point to somethig specific to look for
```

**Comment by felix920506** [comment] 2024-09-26 23:14
Duplicate of #12054

**Closed by felix920506** 2024-09-26 23:14 UTC
Labels: bug
