### ISSUE TITLE
Renaming Top Level Library rescanned folder, replaced metadata, and removed custom identified metadata

### ISSUE THREAD

**Issue by KeeonTabrizi** [jellyfin/jellyfin#5108] opened 2021-01-26 02:34 UTC
**Describe the bug**
I renamed a top level library from `x` to `y` which was of content type `Movie`. NFO Storage *was not* used. A full rescan of the folder appeared to take place and all custom identified metadata (fields, images, etc) was lost as well as information like `date added`. 

**System:**
 - OS: Linux 4.4.59+ #25426 SMP PREEMPT x86_64 GNU/Linux synology_geminilake_920+
 - Virtualization: Docker
 - Clients: Chrome OSX
 - Browser: Version 87.0.4280.141 (Official Build) (x86_64)
 - Jellyfin Version: 10.6.4
 - Playback: N/A
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: None
 - Base URL: local route (bonjour)
 - Networking: Ethernet Switch
 - Storage: Local (Synology)

**To Reproduce**
Have not tried to reproduce, but feel clear enough in the exact single step process that resulted in the loss of data.

**Expected behavior**
Top level library was renamed without any affect to underlying metadata.

---

Rename of library triggered from
`.../web/index.html#!/library.html`

![image](https://user-images.githubusercontent.com/3408390/105791940-a328c780-5f3b-11eb-91f9-7e54bd6bdc61.png)

**Comment by cvium** [comment] 2021-04-19 22:16
Duplicate of https://github.com/jellyfin/jellyfin/issues/2451

**Closed by cvium** 2021-04-19 22:16 UTC
Labels: bug
