### ISSUE TITLE
[Issue]: Music artist misidentified despite music files having musicbrainz metadata

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin#10203] opened 2023-09-09 06:48 UTC
### Please describe your bug

I have several albums by artists that have artist names for which there are different artists (in the example below, "Nicole"). These albums all have musicbrainz metadata added by Picard, yet Jellyfin fetches information for the wrong artist for the artist page.

For example, I have this album in my collection: https://musicbrainz.org/release/d13add7b-f615-4c69-971e-b5f9b1602743

When you open the album in Jellyfin, you can see the links to the correct album in theaudiodb and musicbrainz: 

https://musicbrainz.org/release/d13add7b-f615-4c69-971e-b5f9b1602743 :white_check_mark: 
https://musicbrainz.org/release-group/f3855f02-5026-3ad2-9884-79f6847e0c38 :white_check_mark: 
https://www.theaudiodb.com/album/2278677 :white_check_mark: 
https://www.theaudiodb.com/artist/146326 :white_check_mark: 

However, if you go to the artist page in Jellyfin, it shows information for a different artist (including pictures), as well as links to a different artist:

https://musicbrainz.org/artist/2adb0ccf-24c5-4b69-85dd-dc5093020db2 :x: 
https://www.theaudiodb.com/artist/127115 :x:

The only way to fix this is to use the "identify" feature, but Jellyfin should itself use the metadata it gathered from the album to identify artists and not just search by name.

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csaavedra** [comment] 2023-09-09 06:55
Actually, using "Identify" doesn't work either, I get this error in the logs and nothing is returned when searching by using the artist musicbrainz id `330e16fb-be7d-4b39-834d-d83b4c62a71a`:

```
Sep 09 09:53:25 nanopi jellyfin[56864]: [09:53:25] [ERR] Provider MusicBrainz failed to retrieve search results
Sep 09 09:53:25 nanopi jellyfin[56864]: System.NullReferenceException: Object reference not set to an instance of an object.
Sep 09 09:53:25 nanopi jellyfin[56864]:    at MediaBrowser.Providers.Music.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
Sep 09 09:53:25 nanopi jellyfin[56864]:    at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
Sep 09 09:53:25 nanopi jellyfin[56864]:    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

**Comment by srcrist** [comment] 2023-10-19 17:54
Closing issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/6692.

**Closed by srcrist** 2023-10-19 17:54 UTC
Labels: bug
