### ISSUE TITLE
No chapter images for newly added films

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#12052] opened 2024-06-09 17:30 UTC
### Please describe your bug

Chapter images are not created anymore during a library scan. I haven't tried if the scheduled task would work as I'm not running it.

### Reproduction Steps

1. Remove chapter images extraction from scheduler
2. Enable chapter image extraction for a library
3. Enable Extract chapter images during library scan
4. Add new film
5. Scan
6. No chapter images are created

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-06-09 16:29:34.193 +01:00] [INF] [41] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "C:\Program Files\Jellyfin\Server\ffprobe.exe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\Mounts\MEDIA01\film (2024).mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"

This is the only entry for this file apart from the playback entries just now.
```

### FFmpeg logs

```shell
I can only find playback entries.
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/35429038/b3b41bbc-8408-4163-87f9-8e20857f9563)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThomasPGH** [comment] 2024-06-09 17:58
I just deleted a film (with a .ignore file), scanned, removed the .ignore file, then scanned again. The chapter images are there.
I'll try to find out what's different to the films for which they weren't created.

**Comment by ThomasPGH** [comment] 2024-06-09 18:10
I now did exactly the same with one of those films without chapter images. I placed a .ignore folder in its movie folder, scanned, then removed the .ignore folder, and scanned again.
When I play that film it has no chapter images.

**Comment by ThomasPGH** [comment] 2024-06-11 19:56
Jellyfin definitely doesn't generate chapter images for new films anymore.

**Comment by nielsvanvelzen** [comment] 2024-06-11 20:05
Does your media actually have chapters? If not, did you enable dummy chapter generation?

**Comment by ThomasPGH** [comment] 2024-06-11 20:25
I can't check now because the machine is down for a few minutes due to a Windows update but I haven't changed anything since upgrading from 10.8.13

**Comment by ThomasPGH** [comment] 2024-06-11 20:30
> Does your media actually have chapters? If not, did you enable dummy chapter generation?

The machine's back. Where would I find this setting?

**Comment by ThomasPGH** [comment] 2024-06-11 20:34
Yes, these films have no chapters. There's no chapters displayed under the film itself before playing it, and the Next Chapter buttons in the player don't do anything. However, the last few films I have added before upgrading from 10.8.13 to 10.9.6 also have no chapters, but they do have chapter images, meaning that it did work in 10.8.13 for films without chapters.

**Comment by ThomasPGH** [comment] 2024-06-11 21:23
This is a complex one. It seems the upgrade has removed the interval time in the settings (Libraries, Metadata, Interval). The manually run chapter image extractor seems to have removed the intermediate images from one movie library but not the others. The other libraries all have nicely aligned chapters + images (300 s), but one has either totally irregular chapters + images or none at all.

**Comment by Bond-009** [comment] 2024-06-12 08:44
Dummy chapters (i.e. just using a fixed interval instead of actual chapter markers) are disabled by default in 10.9

Dashboard > Libraries > Metadata > Chapter Images
Set interval to 300 to get the same behavior as 10.8.

**Comment by ThomasPGH** [comment] 2024-06-12 17:36
> Dummy chapters (i.e. just using a fixed interval instead of actual chapter markers) are disabled by default in 10.9

Surely, they shouldn't be disabled by default if upgrading from an earlier version that has them enabled.

**Comment by Bond-009** [comment] 2024-06-13 09:34
> Surely, they shouldn't be disabled by default if upgrading from an earlier version that has them enabled.

Previously this wasn't configurable, now it is and it's disabled by default.
In hindsight we should have communicated this better in the release notes.
Closing as everything is working as intended.

**Closed by Bond-009** 2024-06-13 09:34 UTC
Labels: bug

**Comment by midnightcsl** [comment] 2024-06-17 14:24
> Dummy chapters (i.e. just using a fixed interval instead of actual chapter markers) are disabled by default in 10.9
> 
> Dashboard > Libraries > Metadata > Chapter Images Set interval to 300 to get the same behavior as 10.8.

The missing of dummy chapters just drive me crazy... Thx so much for sharing the solution here.
