### ISSUE TITLE
[Issue]: Jellyfin auto delete my local videos

### ISSUE THREAD

**Issue by ITCJ** [jellyfin/jellyfin#9188] opened 2023-01-27 16:48 UTC
### Please describe your bug

Jellyfin randomly delete my local video folders, I update from 10.8.8 to 10.8.9 but noting change 
it seems that it's because I set the transcode folder to the root of my video folder

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: windows 11
- Virtualization: no
- FFmpeg Version:  5.1.2-Jellyfin
- Hardware Acceleration: AMD AMF
- Plugins: this time just installed open subtitles
- Storage: local
```

### Jellyfin logs

```shell
lementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c513", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c513.ts", Id: c6ad6384-4c57-238e-6f4b-943b22128ad1
[2023-01-28 00:20:53.598 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c514", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c514.ts", Id: 63e48990-0149-2051-1102-6103ff04a832
[2023-01-28 00:20:53.605 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c515", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c515.ts", Id: e2fdca0b-ee06-86c4-33f1-8c2b2a9f7170
[2023-01-28 00:20:53.612 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c516", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c516.ts", Id: 87aa2579-5f9e-b284-f7e3-4651a3498fef
[2023-01-28 00:20:53.619 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c517", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c517.ts", Id: e554cc2d-df53-a32f-8808-7b5b361e4dd6
[2023-01-28 00:20:53.626 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c518", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c518.ts", Id: 597c1a0c-8a9b-c7d2-49e3-6209b7fd690d
[2023-01-28 00:20:53.633 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c519", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c519.ts", Id: 4491d4e8-c862-2bcd-94fa-6ccd4e1e546a
[2023-01-28 00:20:53.639 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c52", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c52.ts", Id: 6aaffb31-5db0-003e-db14-f71d944753ae
[2023-01-28 00:20:53.645 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c520", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c520.ts", Id: 2e543344-373e-c442-4137-736d47c13ce0
[2023-01-28 00:20:53.651 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c521", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c521.ts", Id: 0410a681-a1d7-9c64-93e0-e5d2c2f1b66d
[2023-01-28 00:20:53.663 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c522", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c522.ts", Id: e10b40e3-fc6c-ab5a-7a09-d6474eb6e31e
[2023-01-28 00:20:53.671 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c523", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c523.ts", Id: c2c53362-aac8-5667-ce1d-69ad109fa872
[2023-01-28 00:20:53.678 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c524", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c524.ts", Id: c193144b-e054-b67b-6b97-b1629a4ad433
[2023-01-28 00:20:53.687 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c525", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c525.ts", Id: dd292799-2685-6644-5523-f71380c1fa4c
[2023-01-28 00:20:53.693 +08:00] [INF] [20] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2023-01-28 00:20:53.696 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c526", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c526.ts", Id: 5b2471b3-5b17-a9da-aad4-777f051a80dd
[2023-01-28 00:20:53.703 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c54", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c54.ts", Id: 368da16e-d46a-1adb-a6d2-c4bbadb9c559
[2023-01-28 00:20:53.712 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c527", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c527.ts", Id: bd4af162-22fb-6354-6b94-03a307dc7c42
[2023-01-28 00:20:53.720 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c53", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c53.ts", Id: 4fa8d2ed-7420-b645-72b3-f6725bba7dd1
[2023-01-28 00:20:53.727 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c55", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c55.ts", Id: cf1a641f-64fc-6489-079d-552456885ef1
[2023-01-28 00:20:53.737 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c56", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c56.ts", Id: 7b9e6fe3-cca4-4b2f-3c5b-b3fca42a093c
[2023-01-28 00:20:53.747 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c58", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c58.ts", Id: 87223cc9-6be9-07eb-b0ab-0e8ab76507be
[2023-01-28 00:20:53.758 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c57", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c57.ts", Id: 3c7120a8-3410-e1e3-832e-9ba15db5864e
[2023-01-28 00:20:53.767 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c59", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c59.ts", Id: 4ac5616f-c2d6-f758-7e99-bd89f85ec28d
[2023-01-28 00:20:53.774 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c6", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c6.ts", Id: becc160d-5e1e-c345-d860-f490195d9288
[2023-01-28 00:20:53.781 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c60", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c60.ts", Id: d69f47af-b494-8f04-29fd-5c646424ea1a
[2023-01-28 00:20:53.789 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c61", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c61.ts", Id: 148c8e2b-08ab-08d9-81dd-f0dacec784db
[2023-01-28 00:20:53.797 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c63", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c63.ts", Id: f912f629-5234-f011-a554-86cd73464102
[2023-01-28 00:20:53.804 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c62", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c62.ts", Id: af3fee70-6ae2-bfef-609a-aaecd895f75e
[2023-01-28 00:20:53.812 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c64", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c64.ts", Id: 4dc758a0-93da-3405-b1ae-7469e9672fc7
[2023-01-28 00:20:53.818 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c65", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c65.ts", Id: 0d521c77-46e3-9ef2-2db8-6662a4391ea9
[2023-01-28 00:20:53.826 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c66", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c66.ts", Id: c6f422ef-3e6c-8135-d7f1-789c45c50149
[2023-01-28 00:20:53.832 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c67", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c67.ts", Id: 21505dd9-8270-0f8b-9ff7-10a03f4bee14
[2023-01-28 00:20:53.841 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c69", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c69.ts", Id: c56d66f8-0cd3-8ea5-93b1-0ab49e2c36ee
[2023-01-28 00:20:53.848 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c68", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c68.ts", Id: dd2b83ce-c2bc-a5fc-0569-124e65d3b1d9
[2023-01-28 00:20:53.854 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c70", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c70.ts", Id: bbd4495b-0094-7392-f3ef-781b098c8953
[2023-01-28 00:20:53.860 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c71", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c71.ts", Id: 56613c85-9727-0d73-6d5c-ef0b1a6ff90d
[2023-01-28 00:20:53.867 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c7", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c7.ts", Id: 5202e51f-05b3-4d11-55a2-c5c83bbbfaac
[2023-01-28 00:20:53.878 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c73", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c73.ts", Id: 1fce2037-48e3-1305-6231-86183218af5a
[2023-01-28 00:20:53.884 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c72", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c72.ts", Id: e9e96e4c-d0bc-edcb-538e-a7f5f9fb3f73
[2023-01-28 00:20:53.891 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c74", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c74.ts", Id: c3710875-5b0b-d3d2-60da-bc02fd07a040
[2023-01-28 00:20:53.898 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c76", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c76.ts", Id: d9b58827-bcda-0e34-057e-3eb1bbfade4d
[2023-01-28 00:20:53.905 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c75", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c75.ts", Id: 04f6561c-4361-3b63-92b0-5b257f854b2e
[2023-01-28 00:20:53.912 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c77", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c77.ts", Id: ffd68e88-8377-4858-2614-5a0770b5e1cf
[2023-01-28 00:20:53.918 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c78", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c78.ts", Id: 3763dd09-64f3-09d3-bf22-6bfef0c9e698
[2023-01-28 00:20:53.931 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c8", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c8.ts", Id: 7049113f-dfa9-ec96-482d-6a26a669721b
[2023-01-28 00:20:53.938 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c79", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c79.ts", Id: 99c9c9d5-9712-c7b1-7d41-ec9524c992f9
[2023-01-28 00:20:53.945 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c80", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c80.ts", Id: 77498c08-93f5-e130-3d16-3fff772a4ffe
[2023-01-28 00:20:53.953 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c81", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c81.ts", Id: b733afdd-10fe-7989-a35c-b6257771b01c
[2023-01-28 00:20:53.960 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c82", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c82.ts", Id: db98a8e1-392e-bb9b-1347-092f23323434
[2023-01-28 00:20:53.967 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c83", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c83.ts", Id: 640dd003-be10-9f7e-ddfd-18d1d44612ec
[2023-01-28 00:20:53.973 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c84", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c84.ts", Id: 68cc87a8-b9ba-96f3-2e9b-1a96b2ab2de5
[2023-01-28 00:20:53.980 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c85", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c85.ts", Id: 73c0bdfc-3741-7e98-baf0-92f60665554f
[2023-01-28 00:20:53.986 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c86", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c86.ts", Id: 7922ec11-5774-22f6-ac0c-0e8eb0daa3e8
[2023-01-28 00:20:53.993 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c87", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c87.ts", Id: b9c5054e-e831-bd7c-70b9-a7e4243c6399
[2023-01-28 00:20:54.000 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c88", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c88.ts", Id: 86c64c7e-c671-c4dc-33eb-5bbfb3c698ca
[2023-01-28 00:20:54.006 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c89", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c89.ts", Id: 7b58ab0f-88f3-984f-61b1-fa550e963899
[2023-01-28 00:20:54.013 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c9", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c9.ts", Id: 767b0e98-941a-e7d0-5f0f-8fa053a81d8e
[2023-01-28 00:20:54.020 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c90", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c90.ts", Id: de3b0dd7-3124-53a4-8610-0f94e16ad340
[2023-01-28 00:20:54.026 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c91", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c91.ts", Id: 8a0d32a5-29cd-def8-bc4b-d8cced06346e
[2023-01-28 00:20:54.033 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c92", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c92.ts", Id: 5b9c1bbc-7873-5b7e-f455-48ec9dd480d8
[2023-01-28 00:20:54.039 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c94", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c94.ts", Id: b6cca59c-6b79-2b27-9096-db49f9a7177a
[2023-01-28 00:20:54.050 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c93", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c93.ts", Id: 0b00c321-aa2e-b0a0-ba29-33d26cccf5db
[2023-01-28 00:20:54.056 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c97", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c97.ts", Id: f55a924c-867e-7696-ccfc-40b2b819b237
[2023-01-28 00:20:54.062 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c95", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c95.ts", Id: 1b1dda95-0b3d-c697-c6a6-5f73895f88e7
[2023-01-28 00:20:54.068 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c96", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c96.ts", Id: 277d642f-778e-8bc2-acab-d351ee8ce8c8
[2023-01-28 00:20:54.074 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c98", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c98.ts", Id: 67cdb7ff-c9c2-5857-9bba-5aa79003b241
[2023-01-28 00:20:54.081 +08:00] [INF] [12] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "6d50d603bcfbe3b4f2ff445745d11c0c99", Path: "E:\telev\6d50d603bcfbe3b4f2ff445745d11c0c99.ts", Id: e0538429-4630-e55a-622d-50c030b670af
[2023-01-28 00:20:54.111 +08:00] [INF] [34] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "第 4 集", Path: "E:\telev\间谍教室\[NC-Raws] 间谍教室 - 04 (B-Global 1920x1080 HEVC AAC MKV) [B67A011B].mkv", Id: cb0ab6ef-1c37-50af-2922-37b16d162d63
[2023-01-28 00:20:54.111 +08:00] [INF] [23] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "真寻与新朋友", Path: "E:\telev\别当欧尼酱了\[NC-Raws] 别当欧尼酱了！ - 04 (B-Global 1920x1080 HEVC AAC MKV) [8313B4D5].mkv", Id: 4966c173-4f47-27e3-b6fb-56aa39a1fe25
[2023-01-28 00:20:54.129 +08:00] [INF] [32] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "第 14 集", Path: "E:\telev\三体\Three-Body.S01.2023.2160p.WEB-DL.H265.AAC-TJUPT\Three-Body.S01E14.2023.2160p.WEB-DL.H265.AAC-TJUPT.mp4", Id: a01e4e1f-c191-4f04-649b-26bb3f9fa5f9
```

### Please attach any screenshots here

the main page keep freshing
![image](https://user-images.githubusercontent.com/33901467/215142794-b74cb5a6-9c6d-4a88-8d06-3d5979df9fbb.png)

videos were lost
![image](https://user-images.githubusercontent.com/33901467/215142908-785ae274-0d7c-4716-9ec0-e32db6ec1a47.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment] 2023-01-27 17:15
Duplicate of https://github.com/jellyfin/jellyfin/issues/9158

**Closed by thornbill** 2023-01-27 17:15 UTC
Labels: bug
