### ISSUE TITLE
No 'identify' option at folder level

### ISSUE THREAD

**Issue by stderr-to-devnull** [jellyfin/jellyfin#12371] opened 2024-08-01 18:55 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Upon common failure to identify a docuseries, there is no `identify` option at the folder level. I refuse to believe that nobody thought of this obvious mechanism and as such will treat it as a bug.

### Reproduction steps

1. Add a docuseries which Jellyfin fails to identify (half the time)
2. Docuseries appears as folder (screenshot 1)
3. Impossible to identify the folder (screenshot 2)
4. Only option is to manually identify each episode which does not change how the containing folder is displayed and no option to change it (screenshot 3)
5. Useless `edit images` option since it is unable to use an image from `identified` files inside, requiring to provide a local image, further complicating the management of content media and metadata

![Screenshot_1-8-2024_204139_localhost](https://github.com/user-attachments/assets/4e8bf63b-426c-4f41-8dd7-a1fc31386b23)
![Screenshot 2024-08-01 204201](https://github.com/user-attachments/assets/6900dce1-03db-4e3d-86c6-1b9c1cb224c2)
![Screenshot_1-8-2024_204237_localhost](https://github.com/user-attachments/assets/ec8fc0cf-9453-4ba9-87fc-a44b5dad0c6b)

### What is the current _bug_ behavior?

Folder shows as folder.

### What is the expected _correct_ behavior?

Folder shows up with associated `identified` metadata of the series (option which is missing at folder level)

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS:
- Linux Kernel: Windows 10
- Virtualization: None
- Clients: Web
- Browser: Edge
- FFmpeg Version: whichever is packaged with indicated server version
- Playback Method: pressing `play` button?
- Hardware Acceleration: Yes
- GPU Model: RTX 4070
- Plugins: usual TV/Movie databases
- Reverse Proxy: No
- Base URL: don't understand what you want here
- Networking: yes
- Storage: HDDs
```

### Jellyfin logs

```shell
`Error processing request.`
```

**Comment by crobibero** [comment] 2024-08-01 18:58
What library type is this folder under?

**Comment by stderr-to-devnull** [comment] 2024-08-03 14:05
Library type is `Mixed Movies and Shows`. Because in contains both feature-length docs and docuseries.

**Comment by crobibero** [comment] 2024-08-03 14:30
Closing as this is a feature request, not a bug. 
Identify is only supported if the content type is known.

**Closed by crobibero** 2024-08-03 14:30 UTC
Labels: bug

**Comment by TheMelmacian** [comment] 2024-08-05 22:16
You could try to manually create a `tvshow.nfo` with the basic metadata of the show inside the folder.

As an alternative you could first create the show folder in a separate show library (with enabled .nfo files) and after jellyfin downloaded the correct metadata move the folder to your docu library.

**Comment by stderr-to-devnull** [comment] 2024-08-06 21:26
well that takes care of everything, great job
