### ISSUE TITLE
Incorrectly using TMDb's for IMDb's on Import/Metadata Refresh

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#6363] opened 2021-07-29 15:57 UTC
**Describe the bug**
- Jellyfin currently grabs the TMDB ID and puts them in the Jellyfin IMDB ID fields. for ALL media. 

- Jellyfin  doesn't even get the IMDB ID's when adding a Library or when Refresh Media is used (even when "Replace All Media" is used)

- This happens when adding a new library and does not get updated./fixed on a 'Metadata Refresh'.

- This causes broken issues with 3rd party apps that use Jellyfin movie ID's such as Ombi.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS / 20.04 / focal
 - Virtualization: n/a
 - Clients: Browser
 - Browser: Opera 77.0.4054.277
 - Jellyfin Version: 10.7.6
 - Playback: n/a
 - Hardware Acceleration: none
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy:  nginx
 - Base URL:  none
 - Networking: Bridge/NAT
 - Storage:  samba

**To Reproduce**

1. Install and setup Jellyfin 10.7.6
2. Add Library
3. Scan Libraries
4. Edit Media info on a movie
5. See failure

**Expected behavior**
1) Jellyfin to fetch the IMDb Id (they start with tt*) and place the reference in the Jellyfin movie `IMDb Id:` instead of using the TheMovieDb Movie Id.
2) Jellyfin to put TheMovieDB Movie Id in the `TheMovieDb Movie Id:` field of the movie.

**Server Logs**

[Jellyfin-6363-log.txt](https://github.com/jellyfin/jellyfin/files/6901891/Jellyfin-6363-log.txt)

**FFmpeg Logs**

n/a - not a ffmpeg issue

**Browser Console Logs**

n/a

**Screenshots**

1) Jellyfin entry example: **Those Love Pangs (1914)**
![image](https://user-images.githubusercontent.com/41772110/127520277-7861d265-2996-4933-9464-645218e87990.png)
- imdb id = tt0004693
![image](https://user-images.githubusercontent.com/41772110/127520541-a270c1a4-8cf6-464c-8b0f-e9b78a92f05f.png)
- themoviedb id = 53394
![image](https://user-images.githubusercontent.com/41772110/127520464-4a3c27b4-3843-4560-89f1-5ac5eed94981.png)

2) Jellyfin entry example: **Dough And Dynamite (1914)**
![image](https://user-images.githubusercontent.com/41772110/127520934-dfc52512-fdb8-48ba-90a2-15643897de1a.png)
- imdb id = tt0003863
![image](https://user-images.githubusercontent.com/41772110/127521168-65b129d6-2a62-4fcb-a589-70e00585245c.png)
- themoviedb id = 22879
![image](https://user-images.githubusercontent.com/41772110/127521277-99f3d5a8-b163-4f99-9a75-5b83707a07ab.png)

3) Jellyfin entry example: **Work (1915)**
![image](https://user-images.githubusercontent.com/41772110/127521468-1295554d-9629-45cc-8581-05e61237e597.png)
-imdb id = tt0006313
![image](https://user-images.githubusercontent.com/41772110/127521858-57b9bcc6-2cb4-4bda-bfdc-260faf4678c8.png)
- themoviedb id = 53408
![image](https://user-images.githubusercontent.com/41772110/127521771-f186e364-e76d-4005-8cb1-307c810fa821.png)

....etc...etc...etc.... ALL items are incorrectly referenced.

**Additional context**

Still occurs even if the info's have the correct IMDB ID's.
Full metadata refresh on the libarary does NOT fix this issue.
There are no faulty plugins (defaults).

**Comment by psi5asp** [comment] 2021-07-29 16:16
When using "Identify" for each movie, this appears to get the correct IMDB and Themoviedb ID's.

Going though each one to re-identify individually to correct their IMDB ID's is unreasonable. The Libarary import (or the Metadata Refresh on a Library) should be sufficient. They get identified only by TMDB ID's and then incorrectly used as IMDB ID's.

**Comment by Nocifer** [comment] 2021-08-01 09:25
Do you happen to use Radarr and Sonarr? If that is so, I can't remember the issue # right now but this bug has already been reported a few months ago and the devs said it's been fixed in 10.8.

To verify, try to remove the .nfo file that Radarr/Sonarr puts in the movie/show folder, and then delete the TMDB ID number from Jellyfin's IMDB field and refresh the metadata, and it should correctly populate the TMDB and IMDB fileds. Of course this is not exactly a viable solution, so we just need to be patient until 10.8 comes out.

**Comment by psi5asp** [comment] 2021-08-02 03:42
Only recently, Radarr...no Sonarr - TV shows are also affected. 

- TV Show .nfo is fine:  
>  \<uniqueid default="true" type="tvdb"\>71470\</uniqueid\>
>   \<uniqueid type="imdb"\>tt92455\</uniqueid\>
>   \<uniqueid type="tmdb"\>655\</uniqueid\>

- Jellyfin is not:
![image](https://user-images.githubusercontent.com/41772110/127801239-8a5148ef-4edb-4127-88c9-e9dea320f34e.png)

- Movie 'Work' nfo is also fine, but Jellyfin (as per OP) is not:
>   \<id\>53408\</id\>
>   \<uniqueid type="tmdb" default="true"\>53408\</uniqueid\>
>   <uniqueid type="imdb">tt0006313</uniqueid>
>   <genre>Comedy</genre>

Not sure why Jelllyfin is using nfo's (faster than web-extract?) to identify media when "Refresh Metadata" is pressed - I would have expected to actually refresh it from a sourceh of truth, since nfo's can contain anything with subjective data (depending on the app). Also what would happen if I didn't have any nfo's?

This was all from fresh Jellyfin library rebuild.

**Comment by cvium** [comment] 2021-08-17 08:07
Duplicate of https://github.com/jellyfin/jellyfin/issues/5347

**Closed by cvium** 2021-08-17 08:07 UTC
Labels: bug

**Comment by cvium** [comment] 2021-08-17 08:10
> **EDIT 2:** Gee, looking through the reports I've found at least a dozen more about this exact same issue, which makes sense because it's annoying as hell (breaks image fetching, breaks external links, breaks cast/crew, breaks external apps, breaks everything really). Can't help but wonder what's preventing the team from backporting such an important fix to the 10.7.x branch.

https://github.com/jellyfin/jellyfin/issues/5347#issuecomment-797710872

There's well over a thousand commits to master since 10.7. Backporting is not super easy, but we're continually working on improving the process.

**Comment by GlassedSilver** [comment] 2022-02-13 08:28
When I drop a movie into my movies folder without any nfo this also happens. o.O

My metadata download settings are as follows (active and in order):
TheMovieDb, The Open Movie Database

**Comment by ProNoob333** [comment] 2022-04-02 07:38
so any word on a fix or a workaround?  (btw uninstall and reinstall did not fix)

**Comment by cvium** [comment] 2022-04-02 09:16
Did you read the older comments? The fix will be in 10.8

**Comment by ProNoob333** [comment] 2022-04-02 15:29
Your pedantry is noticed. And now mocked in my response. Did you read my question? Is there a fix or a work-around? Not will there be....a fix. 

Perhaps someone downgraded a version or found another way to work around this.   

⁣

**Comment by ProNoob333** [comment] 2022-04-11 18:58
Edit: running 10.8 beta does not seem to fix issue, as in correcting past meta data changes. by way of "replace all meta data" option via the gui. Continues to place tmdb id in imdb id slot. Will still correct if using "identify" as in 10.7, not viable for large library. 

however, 10.8 beta seems to fix issue on newly added movie, or 10.8 beta on new movie import functions as expected.

**Comment by GlassedSilver** [comment] 2022-04-12 09:37
> Edit: running 10.8 beta does not seem to fix issue, as in correcting past meta data changes. by way of "replace all meta data" option via the gui. Continues to place tmdb id in imdb id slot. Will still correct if using "identify" as in 10.7, not viable for large library.
> 
> however, 10.8 beta seems to fix issue on newly added movie, or 10.8 beta on new movie import functions as expected.
> 
> Update: 10.8 beta, auto scan preformed by system (non-manual refresh), has remedied improper metadata.

Thanks for the update! Very much appreciated!
