### ISSUE TITLE
Support multiple codecs in Transcoding Profiles

### ISSUE THREAD

**Issue by PrplHaz4** [jellyfin/jellyfin#2424] opened 2020-02-18 15:25 UTC
**Describe the bug**
Currently if you provide a list of codecs in the Transcoding Profile of a specific device, only the first one will be used for every transcode.  This reduces the likelihood of media being remuxed when possible and will force an actual transcode when it shouldn't be necessary.

**To Reproduce**

1. Play media with AAC audio on Samsung TV through DLNA
2. Audio is transcoded to AC3 when played (as that is what is in the Samsung TV profile)
3. Add AAC to Transcoding Profile for Samsung TV (`audio: ac3,aac`)
4. Audio is transcoded to AC3 instead of being `copy`d to AAC by ffmpeg

**Expected behavior**

Source codec is compared to a list of supported transcode codecs and if a stream copy is possible, that codec is used instead.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.5-dev
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**
- Observed this behavior when investigating #2334 and #2409
- Not sure if this behavior is the same for device profiles included in clients (ie, web, android tv...etc) or just applies to DLNA clients.

**Comment by Artiume** [comment] 2020-02-18 15:32
So I'm having a similar issue on iPads. It's transcoding livetv to ac3 and isn't playing audio

**Comment by JustAMan** [comment] 2020-02-18 16:07
I'm pretty sure it's not a bug but an enhancement, so relabelling.

**Comment by Artiume** [comment] 2020-02-18 16:10
Could we switch the priority from ac3 to aac? I think either way priority is listed, devices will be impacted

**Comment by PrplHaz4** [comment] 2020-02-18 16:50
> 
> 
> Could we switch the priority from ac3 to aac? I think either way priority is listed, devices will be impacted

Changing priority for DLNA devices definitely impact things because for transcoding profiles it seems that priority isn't really a thing - the first one is the only one ever chosen (that's what this issue is).  For iPad/Safari it's probably in the `browserdeviceprofile.js` somewhere - which MAY behave differently from the DLNA profiles (regarding priority/multiple codecs) ...

**Comment by sevenrats** [comment] 2023-10-04 20:26
this stale issue references an obsolete unstable branch.

**Comment by srcrist** [comment] 2023-10-04 21:34
Issue closed by https://github.com/jellyfin/jellyfin/pull/7325

**Closed by srcrist** 2023-10-04 21:34 UTC
Labels: enhancement
