### ISSUE TITLE
New libraries are empty 

### ISSUE THREAD

**Issue by mastercho** [jellyfin/jellyfin#6767] opened 2021-11-03 18:29 UTC
**Describe the bug**

All new libraries I create are empty after scan.

**System (please complete the following information):**
 - OS: Unraid 6.9.2
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 93
 - Jellyfin Version: 10.7.7
 - Playback: Direct Play
 - Hardware Acceleration:none
 - Installed Plugins: Fanart
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: local
 - 
**To Reproduce**

1. Create a Movie Library (or TV Show): Admin -> Dashboard -> Libraries -> Add
2. Enter media path, leave default options
3. Wait for the media to be scanned, or force the scan
4. Go to Home -> My Media -> Your library : It's empy

**Expected behavior**

The library should display a list of the detected media

**Server Logs**

No error logs are present, either during the library scan or when accessing the media library.
Even with debug log enabled.

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

![image](https://i.gyazo.com/807ba76b2bf463f8174729ae7e01de27.png)

![image](https://i.gyazo.com/d197e1214db996832216a4d2ab8bdd1c.png)
**Additional context**

Existing libraries works fine, just new one are not detects new content

**Comment by sumsumsums** [comment] 2021-11-04 21:42
Actually i have a similar behaviour since today. Existing libraries are empty (video, music) or not complete (photos). Removing and re-adding the libraries didn't changed anything.

I had an update of Jellyfin (unstable) last night. Maybe i should switch to stable :-)

System (please complete the following information):

OS: Debian 11
Virtualization: LXC on a proxmox host
Clients: Browser, DLNA AV-Receiver, Jellyfin Android App
Browser: Chromium 89.0.4389.114
Jellyfin Version: jellyfin-web:amd64 (20211029.5-unstable, 20211103.20-unstable), jellyfin-server:amd64 (20211028.3-unstable, 20211103.7-unstable)
Playback: Direct Play, DNLA
Hardware Acceleration: none
Installed Plugins:
Reverse Proxy: none
Base URL: none
Networking: Bridge
Storage: CIFS

**Comment by xamindar** [comment] 2021-12-17 06:02
This same issue is happening to me after updating jellyfin. My libraries are showing nothing but I can still play stuff listed under recent so it's still in the db somewhere. I just can't see them anymore. Both existing libraries and newly entered ones are the same.

**Comment by nonplusnl** [comment] 2022-06-25 09:32
Same here for my Photos library. It has just vanished. Readding doesn't help. In my case, Music and Videos still work and show content

**Comment by srcrist** [comment] 2023-10-08 07:23
Closing this issue as it does not address a reproducible Jellyfin bug. The symptoms described are almost certainly caused by Jellyfin not having permission to read the files in your library. Double-check your permissions.

**Closed by srcrist** 2023-10-08 07:23 UTC
Labels: bug

**Comment by mastercho** [comment] 2023-10-08 12:39
> Closing this issue as it does not address a reproducible Jellyfin bug. The symptoms described are almost certainly caused by Jellyfin not having permission to read the files in your library. Double-check your permissions.

Permissions are alright, we have test it on 3 different setups and issue exists. Its not permission issue. If was permission issue other libraries wont show up at all
