### ISSUE TITLE
Moved library folder, lost all playlists

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#4728] opened 2020-12-07 21:40 UTC
**Describe the bug**

I moved a folder on disk, then updated the library path in Jellyfin. I can play individual songs, but the playlists are empty. They show the proper durations but there are no songs in them.

This is a bug, but I also want to know a workaround to get my playlists back?

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: none
 - Clients: Browser
 - Browser: Chrome 87
 - Jellyfin Version: 10.6.4
 - Playback: direct
 - Installed Plugins: none
 - Reverse Proxy: Caddy
 - Base URL: 
 - Networking: host
 - Storage:local

**To Reproduce**

1. Move a folder on disk
2. In admin panel, go to Libraries and change the library folder path
3. Playlists are empty

**Expected behavior**

Songs should still be in playlist.

**Logs**
LOTS of `[WRN] Unable to find linked item at path` ... with the OLD paths still being used.

**Comment by crobibero** [comment] 2020-12-08 17:00
Playlists are still stored in the data directory, and the full path is hardcoded as a playlist item.
I don't expect this to be fixed before the librarydb rewrite is complete

eg:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Item>
  <Added>12/08/2020 11:58:12</Added>
  <LockData>false</LockData>
  <LocalTitle>00</LocalTitle>
  <RunningTime>0</RunningTime>
  <PlaylistItems>
    <PlaylistItem>
      <Path>/virtual/media/tv/Jackie Chan Adventures (2000)/Season 01/Jackie Chan Adventures - S01E09 - The Rock.mkv</Path>
    </PlaylistItem>
  </PlaylistItems>
  <Shares>
    <Share>
      <UserId>xxx</UserId>
      <CanEdit>true</CanEdit>
    </Share>
  </Shares>
  <PlaylistMediaType>Video</PlaylistMediaType>
</Item>
```

**Comment by mholt** [comment] 2020-12-08 18:48
Ah, thanks; but after a global search-replace of the old path to the new one, and restarting the Jellyfin server, I'm still seeing the same missing media items and the same log entries.

**Comment by mholt** [comment] 2020-12-08 19:02
I found that the old path is hard-coded in `library.db`, which is a binary file :(

**Comment by mholt** [comment] 2020-12-08 19:25
Oh noooo symlinking the old path didn't work either :sob:

Log example:

```
[WRN] Unable to find linked item at path "/mnt/old/Media/Music/RADWIMPS/Your Name. (Original Motion Picture Soundtrack) [Deluxe Edition]/2-03 Sparkle.m4a"
```

But file exists:

```
$ ls "/mnt/old/Media/Music/RADWIMPS/Your Name. (Original Motion Picture Soundtrack) [Deluxe Edition]/2-03 Sparkle.m4a"
'/mnt/old/Media/Music/RADWIMPS/Your Name. (Original Motion Picture Soundtrack) [Deluxe Edition]/2-03 Sparkle.m4a'
```

**Comment by cvium** [comment] 2021-04-19 22:16
Duplicate of https://github.com/jellyfin/jellyfin/issues/2451

**Closed by cvium** 2021-04-19 22:16 UTC
Labels: bug

**Comment by r4j4h** [comment] 2022-01-20 19:56
I'm not sure this is a true duplicate. The other is about needless rescans. This is more about upon renaming or re-scanning, having playlists get broken shortcut links automatically repaired.

Even if it were a separate tool that could parse the `library.db` format and make corrections.

However, if considering them merged gets more attention so they both get fixed, all the better. Just wanting to be clear that I am not sure solving the other completely resolves this one.
