### ISSUE TITLE
Movies showing up in Continue Watching section, when I never watched them

### ISSUE THREAD

**Issue by Scrub000** [jellyfin/jellyfin#12445] opened 2024-08-14 00:48 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin 10.9.9

![Screenshot 2024-08-14 104120](https://github.com/user-attachments/assets/55270798-a4a5-4d90-810e-0d91c922b3ed)

The only movie that I've watched is Man vs. Wild, all the others I've never touched. Every single movie I have is showing up.

### Reproduction steps

Open Jellyfin on any client (or web), observe movies you never watched show up in "Continue Watching".

### What is the current _bug_ behavior?

All movies and shows are showing up as watched when I've never played them.

### What is the expected _correct_ behavior?

Only movies and shows I've watched, show show up.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: OpenMediaVault (official Docker image)
- Linux Kernel: Whatever is in the official Docker image
- Virtualization: Docker
- Clients: Web, Android, TV
- Browser: Firefox
- FFmpeg Version: Whatever is in the Docker image
- Playback Method: All
- Hardware Acceleration: QSV
- GPU Model: N100 CPU
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
N/A
```

**Comment by jfml** [comment] 2024-09-06 09:58
I'm experiencing this as well, with Jellyfin 10.9.9 running on Linux via Docker. At first I thought this might be an issue with Trickplay generation but I've since disabled that and it's still happening. I'd be happy to do testing or provide logs if needed (though I'm just a user, not a programmer). It's interesting that this is only happening for movies not series or other video files.

**Comment by felix920506** [comment] 2024-09-06 14:19
Do you have any nfo files present in the library?
If so, do you have save nfo files enabled?
If so, do you have JF save progress?

**Comment by jfml** [comment] 2024-09-06 16:10
I do have .nfo files present (I think Radarr/Sonarr manage these as well? Not sure) and I think I have saving progress enabled (Dashboard > Libraries > NFO Settings > Save user watch data to NFO for … is set to my user). 

And interestingly the movie.nfo for movies that is showing as partly watched without me having watched it seem to have been changed yesterday. Interesting!

But I can't see anything of note in the .nfo files, there is <playcount /> and <lastplayed /> which don't really fit and are empty. There's also <watched> which is correctly „false“. How would progress show up in the .nfo file?

I also just saw that (even I think I turned it off in all libraries, Dashboard > Libraries > three dot menu of a library > Manage Libraries > two boxes for Trickplay are unchecked) the scheduled taks for generating trickplay images is still being run (Scheduled Tasks says it last run 14h ago for less then a minute). So it might be that after all? @Scrub000 do you have Trickplay enabled?

**Comment by felix920506** [comment] 2024-09-06 21:22
Can you provide a complete list of plugins?

**Comment by jfml** [comment] 2024-09-07 06:55
I have quite a few I'm afraid:

![Screenshot_20240907_075359](https://github.com/user-attachments/assets/fd87030e-c702-4372-8694-e07717371a33)

(Feel free to tell me if it's better for you if I write a text list.)

**Comment by felix920506** [comment] 2024-09-07 12:20
right now all signs point to it being a duplicate of #12054 so I am going to close it as such.

**Closed by felix920506** 2024-09-07 12:20 UTC
Labels: bug
