### ISSUE TITLE
[Issue]: Identifying media does nothing

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/jellyfin#12041] opened 2024-06-09 05:27 UTC
### Please describe your bug

When clicking on "Identify" to change the metadata associated with a particular movie, Jellyfin will not apply any changes when clicking on save.

Note that I've only encountered this bug with one movie. I also had to re-identify a different TV show, and that one applied fine. Looking at the logs it looks like only the folder associated with this movie is affected.

May be potentially related to #12023, however the provided logs do not match so it may be separate.

### Reproduction Steps

1. Click Identify on movie
2. Find proper metadata
3. Click save
4. No changes are applied
5. Refresh to confirm no changes are applied

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1.79-Unraid
- Virtualization: Docker
- Clients: Browser
- Browser: 125.0.6422.142 (Official Build) (64-bit) (cohort: Stable)  
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin 
- Playback Method: N/A
- Hardware Acceleration: VAAPI (but N/A in this bug)
- GPU Model: AMD Ryzen 5 PRO 4650G with Radeon Graphics
- Plugins: AniDB, AudioDB, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Studio Images, Subtitle Extract, TMDb, TMDb Trailers, Trakt, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
[14:22:10] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
[14:22:14] [INF] [32] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 29a18403-249e-6919-63ed-319725178c76-The 12 Days of Christmas Eve: {"Tmdb": "919207"}
[14:22:14] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/data/metadata/library/29/29a18403249e691963ed319725178c76/poster.jpg
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[14:22:14] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/data/metadata/library/29/29a18403249e691963ed319725178c76/logo.png
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[14:22:14] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/data/metadata/library/29/29a18403249e691963ed319725178c76/landscape.jpg
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[14:22:14] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /config/data/metadata/library/29/29a18403249e691963ed319725178c76/backdrop.jpg
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[14:22:14] [ERR] [32] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Directory not empty : '/config/data/metadata/library/29/29a18403249e691963ed319725178c76'. URL POST /Items/RemoteSearch/Apply/29a18403249e691963ed319725178c76.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ericswpark** [comment] 2024-06-09 05:41
The only folder/files within the metadata folder (`/config/data/metadata/library/29/29a18403249e691963ed319725178c76`) is the `trickplay` folder with a bunch of images in it, if it helps any. There is no `logo.png` as shown in the log.

**Comment by Shadowghost** [comment] 2024-06-09 05:42
Can you try if #12025 fixes it?

**Comment by ericswpark** [comment] 2024-06-09 05:44
@Shadowghost sorry, was messing about with my installation and managed to work around the issue. But looking at your PR I believe it'll probably work.

The workaround was to click on "Edit Images", and then press the trashcan icon for all of the images. They didn't exist on the filesystem, but I guess they existed on the DB because there were empty spots with the image dimensions and all. Once all the images were deleted I was able to re-identify the movie.

**Comment by Shadowghost** [comment] 2024-06-09 06:26
Duplicate of #12023

**Closed by Shadowghost** 2024-06-09 06:26 UTC
Labels: bug
