### ISSUE TITLE
[Issue]: 10.10.3  Synology NAS always active and not hibernating

### ISSUE THREAD

**Issue by beipink** [jellyfin/jellyfin#13305] opened 2024-12-31 07:51 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Synology NAS DS923+ 

The unit remains constantly active due to Jellyfin, which results in the HDDs' clicking noise never stopping. This causes unnecessary power usage when the NAS is not in use, as well as shortening the lifespan of the disks and the unit.

I would appreciate it if a solution could be found for this, or at least an explanation of what is preventing it from being addressed. Is there a benefit to keep the NAS always active rather that hibernating when not in use?

### Reproduction steps

Install Jellyfin using the Synology Docker container and start it. This will prevent the NAS from going into sleep mode.

### What is the current _bug_ behavior?

Synology DS923+ Jellyfin docker keeps HDDs  always active and prevent NAS from going into sleep mode at night or when not used.

### What is the expected _correct_ behavior?

NAS to go into sleep mode if not used for a while. Or at least offer a UI feature to enable it i.e. energy saving mode. 

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.3

### Specify the build version

10.10.3

### Environment

```markdown
- OS:DSM 7.2.2-72806
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
NA
```

### FFmpeg logs

```shell

```

**Comment by gnattu** [comment] 2024-12-31 08:27
Duplicate of #8437

**Closed by gnattu** 2024-12-31 08:27 UTC
Labels: bug
