### ISSUE TITLE
webvtt with style blocks is not transcoded at all

### ISSUE THREAD

**Issue by qbittorrentfan** [jellyfin/jellyfin#9465] opened 2023-03-10 16:33 UTC
I reported this bug in [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg/issues/207) three months ago. Sorry for duplicate but it had no reply and i thought here would bring attention.

ffmpeg stops the WebVTT -> SRT transcoding as soon as a style block is encountered. That makes it output empty SRT for VTT files with style blocks at the start of file (a common occurrence). The bug is known upstream and there is a patch submitted but it was not reviewed for over 2 years ([ticket](https://trac.ffmpeg.org/ticket/9064)).

## FFmpeg Logs

```
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: ffmpeg version 5.1.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   built with gcc 8 (Debian 8.3.0-6)
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libavutil      57. 28.100 / 57. 28.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libavcodec     59. 37.100 / 59. 37.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libavformat    59. 27.100 / 59. 27.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libavdevice    59.  7.100 / 59.  7.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libavfilter     8. 44.100 /  8. 44.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libswscale      6.  7.100 /  6.  7.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libswresample   4.  7.100 /  4.  7.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   libpostproc    56.  6.100 / 56.  6.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: Input #0, webvtt, from '/media/Sacrifice paysan.en.vtt':
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   Duration: N/A, bitrate: N/A
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   Stream #0:0: Subtitle: webvtt
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: Output #0, srt, to '/var/lib/jellyfin/data/subtitles/c/cce8c574-85f0-2926-f0f7-7685e8ab76e4.srt':
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   Metadata:
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:     encoder         : Lavf59.27.100
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   Stream #0:0: Subtitle: subrip
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:     Metadata:
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:       encoder         : Lavc59.37.100 srt
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: Stream mapping:
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]:   Stream #0:0 -> #0:0 (webvtt (native) -> subrip (srt))
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: Press [q] to stop, [?] for help
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: [117B blob data]
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
déc. 16 10:30:48 kl.netlib.re jellyfin[217759]: Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
```

## Additional Context

I verified WebVTT-conformance of the file using [this tool](https://w3c.github.io/webvtt.js/parser.html).

**Comment by nyanmisaka** [comment] 2023-03-10 18:15
Duplicate of https://github.com/jellyfin/jellyfin-ffmpeg/issues/207

**Closed by nyanmisaka** 2023-03-10 18:15 UTC
