### ISSUE TITLE
[Issue]: Database migration fails 10.9.0.0

### ISSUE THREAD

**Issue by michal4132** [jellyfin/jellyfin#11532] opened 2024-05-11 19:32 UTC
### Please describe your bug

After upgrading from 10.8.13 to 10.9.0 the database migration fails due to empty rating string.

### Reproduction Steps

Upgrade to 10.9.0 with empty ratings in DB

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu 23.04
- Linux Kernel: 5.15.0
- Virtualization: no
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: none
- Reverse Proxy:
- Base URL:
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
ay 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Loaded plugin: TMDb 10.9.0.0
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Loaded plugin: Studio Images 10.9.0.0
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Loaded plugin: OMDb 10.9.0.0
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Loaded plugin: MusicBrainz 10.9.0.0
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Loaded plugin: AudioDB 10.9.0.0
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Applying migration 'MigrateRatingLevels'
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Library database backed up to /var/lib/jellyfin/data/library.db.bak4
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Recalculating parental rating levels based on rating string.
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [ERR] Could not apply migration 'MigrateRatingLevels'
May 11 18:48:05 server jellyfin[88170]: System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
May 11 18:48:05 server jellyfin[88170]:    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
May 11 18:48:05 server jellyfin[88170]:    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
May 11 18:48:05 server jellyfin[88170]:    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
May 11 18:48:05 server jellyfin[88170]:    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [FTL] Error while starting server
May 11 18:48:05 server jellyfin[88170]: System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
May 11 18:48:05 server jellyfin[88170]:    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
May 11 18:48:05 server jellyfin[88170]:    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
May 11 18:48:05 server jellyfin[88170]:    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
May 11 18:48:05 server jellyfin[88170]:    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
May 11 18:48:05 server jellyfin[88170]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Running query planner optimizations in the database... This might take a while
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Disposing CoreAppHost
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Disposing MusicBrainzArtistProvider
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Disposing MusicBrainzAlbumProvider
May 11 18:48:05 server jellyfin[88170]: [18:48:05] [INF] Disposing PluginManager
May 11 18:48:05 server systemd[1]: jellyfin.service: Deactivated successfully.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yodatak** [comment] 2024-05-11 20:41
I got the same issue too

2024-05-11T22:40:06.294426045+02:00 [22:40:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.0.0
[22:40:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.0.0
2024-05-11T22:40:06.310728388+02:00 [22:40:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.0.0
2024-05-11T22:40:06.350466655+02:00 [22:40:06] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'MigrateRatingLevels'
2024-05-11T22:40:06.351350153+02:00 [22:40:06] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateRatingLevels: Library database backed up to /config/data/library.db.bak5
2024-05-11T22:40:06.351362402+02:00 [22:40:06] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateRatingLevels: Recalculating parental rating levels based on rating string.
[22:40:07] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateRatingLevels'
System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
2024-05-11T22:40:07.105808850+02:00    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
2024-05-11T22:40:07.105814479+02:00    at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
2024-05-11T22:40:07.105817870+02:00    at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
2024-05-11T22:40:07.105820794+02:00    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
2024-05-11T22:40:07.106186862+02:00 [22:40:07] [FTL] [1] Main: Error while starting server
2024-05-11T22:40:07.106193195+02:00 System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
2024-05-11T22:40:07.106197706+02:00    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
2024-05-11T22:40:07.106205262+02:00    at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
2024-05-11T22:40:07.106207807+02:00    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
2024-05-11T22:40:07.106210269+02:00    at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)

**Comment by crobibero** [comment] 2024-05-11 21:19
I can't reproduce the issue with empty rating rating in my database, any chance either of you can send me your library.db? team@jellyfin.org

**Comment by yodatak** [comment] 2024-05-11 21:33
Thanks @crobibero  just send my 300mb library  ;)

**Comment by mateuszkozakiewicz** [comment] 2024-05-11 21:54
Same problem here, can't roll back either to `10.8.13`

```
[23:52:06] [INF] [1] Main: Jellyfin version: 10.8.13
[23:52:06] [INF] [1] Main: Environment Variables: ["[JELLYFIN_PORT, tcp://10.43.1.218:80]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_SERVICE_PORT, 80]", "[JELLYFIN_PublishedServerUrl, https://xxx]", "[JELLYFIN_PORT_80_TCP_PROTO, tcp]", "[JELLYFIN_SERVICE_PORT_HTTP, 80]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_PORT_80_TCP_PORT, 80]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_PORT_80_TCP, tcp://10.43.1.218:80]", "[JELLYFIN_SERVICE_HOST, 10.43.1.218]", "[JELLYFIN_PORT_80_TCP_ADDR, 10.43.1.218]"]
[23:52:06] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[23:52:06] [INF] [1] Main: Operating system: Linux
[23:52:06] [INF] [1] Main: Architecture: X64
[23:52:06] [INF] [1] Main: 64-Bit Process: True
[23:52:06] [INF] [1] Main: User Interactive: True
[23:52:06] [INF] [1] Main: Processor count: 12
[23:52:06] [INF] [1] Main: Program data path: /config/data
[23:52:06] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
[23:52:06] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
[23:52:06] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
[23:52:06] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Fanart_10.0.0.0/Jellyfin.Plugin.Fanart.dll
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 0.1.7.0 of Intro Skipper 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Nick.Plugin.Jellyscrub, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Jellyscrub_1.1.1.0/Nick.Plugin.Jellyscrub.dll
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LDAP-Auth, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/LDAP Authentication_16.0.0.0/LDAP-Auth.dll
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f from /config/data/plugins/LDAP Authentication_16.0.0.0/Novell.Directory.Ldap.NETStandard.dll
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 8.0.0.0 of TheTVDB 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 9.0.0.0 of TheTVDB 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 10.0.0.0 of TheTVDB 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 20.0.0.0 of Trakt 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 21.0.0.0 of Trakt 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 22.0.0.0 of Trakt 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 23.0.0.0 of Trakt 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 24.0.0.0 of Trakt 
[23:52:06] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 11.0.0.0 of Webhook 
[23:52:06] [ERR] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Error loading configuration file: /config/network.xml
System.InvalidOperationException: There is an error in XML document (39, 6).
 ---> System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.FinishReadElementContentAsXxx()
   at System.Xml.XmlReader.ReadElementContentAsString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderNetworkConfiguration.Read2_NetworkConfiguration(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderNetworkConfiguration.Read3_NetworkConfiguration()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.LoadConfiguration(String path, Type configurationType)
[23:52:06] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[23:52:06] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : ]
[23:52:06] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[23:52:06] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ]
[23:52:06] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: ]
[23:52:07] [FTL] [1] Main: Error while starting server.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: u.EasyPassword'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[23:52:07] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[23:52:07] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[23:52:07] [FTL] [1] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.DisposeAsyncCore()
   at Emby.Server.Implementations.ApplicationHost.DisposeAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String] args)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.DisposeAsyncCore()
   at Emby.Server.Implementations.ApplicationHost.DisposeAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String] args)
```

**Comment by nielsvanvelzen** [comment] 2024-05-12 07:38
We do not support downgrading, you need to restore your backup when you do so. This issue will be fixed with 10.9.1 though.

**Comment by sejmann** [comment] 2024-05-12 07:50
Is this issue related to a popup saying "Jellyfin Server was unable to properly migrate old directories" -- google and searching the various jellyfin repos didn't turn up any substrings about migrating old directories. I'm thinking it's a different issue, because it didn't write anything to the logs, and didn't prevent downgrading to prior working version.

**Comment by nielsvanvelzen** [comment] 2024-05-12 07:53
> Is this issue related to a popup saying "Jellyfin Server was unable to properly migrate old directories" -- google and searching the various jellyfin repos didn't turn up any substrings about migrating old directories. I'm thinking it's a different issue, because it didn't write anything to the logs, and didn't prevent downgrading to prior working version.

This seems to be related specifically to the macOS app, please open an issue here: https://github.com/jellyfin/jellyfin-server-macos

**Comment by lockheed** [comment] 2024-05-12 09:04
When do you estimate 10.9.1 docker image to be released?

**Comment by nielsvanvelzen** [comment] 2024-05-12 09:23
When it's ready, probably in a week or so

**Comment by Expro** [comment] 2024-05-12 11:19
I hit the same issue. Week or so... time to roll second instance.

**Comment by mateuszkozakiewicz** [comment] 2024-05-12 11:20
> When it's ready, probably in a week or so

A minute of silence for all those using watchtower or renovate and have no backups [*]

**Comment by Absent1337** [comment] 2024-05-12 11:25
I have exactly the same issue

**Comment by MarioSob** [comment] 2024-05-12 12:07
Same problem here. Kind of hoping for hotfix release soon or at least providing a workaround (manual file edit or something).

**Comment by unikitty37** [comment] 2024-05-12 12:08
I have restored my backup and downgraded to 10.8.13, and now the server refuses to start, and the logs are just filled with this over and over:

```
12:09:06] [INF] [60] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[12:09:06] [ERR] [60] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid token. URL GET /socket.
```

I can't find any clear solution on how to fix this — most advice I see seems to be about clearing cookies and site data, and I've already done this. And now, despite having a fully-restored backup, it wants me to create the library and the user from scratch.

It would _really_ help if the release could be sooner, even if this critical bugfix (preventing people's servers from starting seems pretty critical to me 😁) was the only thing in it.

I don't know how much is involved in making a Jellyfin release, of course — I've just looked at the README to try and work out how to make my own build for now, and I'm none the wiser. I don't even know if you _can_ build it on macOS. (This is where interpreted languages score, of course — I could just shell into the Docker container, apply the patch, and be up and running!)

BTW, a word of warning for anybody thinking of leaving Jellyfin running while they're waiting for the new release — it creates a backup of the library database each time it tries to run the migration, which is about every three or four minutes. You will end up with a very full disk if you leave it for too long!

**Comment by Dr-Axen** [comment] 2024-05-12 12:13
I have the same issue. 
Is there any workaround other than downgrading or waiting for a fix? Anything that can be done from the command line since the Jellyfin does not start? For example, I fine with removing all libraries and re-adding them, but I would not want to lose all user data.

**Comment by Expro** [comment] 2024-05-12 12:16
> BTW, a word of warning for anybody thinking of leaving Jellyfin running while they're waiting for the new release — it creates a backup of the library database each time it tries to run the migration, which is about every three or four minutes. You will end up with a very full disk if you leave it for too long!

Thanks for the warning! My Kubernetes cluster already restarted it 53 times...

**Comment by nielsvanvelzen** [comment] 2024-05-12 12:25
Normally we'd wait about a week for a patch version but considering this issue affects quite a large group we'll try to get it out a bit sooner. That could be today/tomorrow (depending on your timezone). No promises though.

**Comment by crobibero** [comment] 2024-05-12 15:54
Closing as the fix PR has been merged. Will be available with 10.9.1

**Closed by crobibero** 2024-05-12 15:54 UTC
Labels: bug, confirmed

**Comment by Steltek** [comment] 2024-05-12 19:36
For anyone struggling with this but database savvy and wanting to work around it: The issue is in the library.db database, in the TypedBaseItems table, specifically in the OfficialRatings field there. Look for a row with an OfficialRating that is not NULL, and not one of the standard ratings (in my case there was one with a rating set to "-"). Shut down Jellyfin (likely down already since it won't stay up with this bug), back up your database (this is important in case you mess it up), then correct those entries to help the buggy migration code to get past them.

**Comment by yodatak** [comment] 2024-05-12 20:15
Thanks i use dbeaver and open the library.db for me the faulting rating was '+14' so i emove the + and its works nice workaround ! @Steltek

**Comment by twhite96** [comment] 2024-05-12 23:31
On macOS it is a bit different when migrating to the ARM64 version. I opened the library.db file in SQLiteStudio and found in the `MigrationID` column in the `__EFMigrationsHistory` the default value is `NULL`. I am not sure if that is supposed to be NULL, considering I am migrating from the `x86_64` version of Jellyfin or not. But it seems like the ARM64 version for macOS Sonoma is completely broken.

**Comment by gnattu** [comment] 2024-05-13 00:11
> On macOS it is a bit different when migrating to the ARM64 version. I opened the library.db file in SQLiteStudio and found in the `MigrationID` column in the `__EFMigrationsHistory` the default value is `NULL`. I am not sure if that is supposed to be NULL, considering I am migrating from the `x86_64` version of Jellyfin or not. But it seems like the ARM64 version for macOS Sonoma is completely broken.

If you are using the menu bar app then that migration is not the database migration, two different things. Current menu bar app is broken and you will not even start the database migration
