### ISSUE TITLE
[Issue]: Daily-run episodes filenamed "Series Name 2023 09 22 720p...." is parsed as season 20 episode 23

### ISSUE THREAD

**Issue by TheHYPO35** [jellyfin/jellyfin#10253] opened 2023-09-22 06:03 UTC
### Please describe your bug

I have one daily-run series in my library, which means that downloads are named in date format.

When the files are period-separated ( "Series.Name.2023.09.22.720p...."), Jellyfin correctly identifies the date and finds the right episode number. However, sometimes the filenames download with spaces instead of periods ("Series Name 2023 09 22 720p...."). In this case, Jellyfin identifies the episode as season 20, episode 23.

All episodes are in a "Season 2023" folder. I can't think of a good reason why the parsing should differ based on the type of dividing character used.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11
- Virtualization: Docker
- Plugins: Cover Art Archive, Fanart, Intro Skipper, OMDb, Open Subtitles, Playback Reporting, Reports, Studio Images, TMDb, TVmaze, The TVDB, Theme Songs
- Storage: local
```

### Jellyfin logs

```shell
[I have replaced the series name with [SERIES], and the series number with [NUMBER] ] 

[2023-09-22 01:10:24.236 -04:00] [ERR] [85] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id null, series id null:"[SERIES] 2023 09 14"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:20 EpisodeNumber:23]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2023-09-22 01:10:24.438 -04:00] [ERR] [80] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "[NUMBER]":"[SERIES]"
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:20 EpisodeNumber:23]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment] 2023-10-08 07:45
Hey there. We are looking at this as a possible bug, but it's difficult to really consider the cause since you've redacted the actual names. Are you able to share the actual file names please?

**Comment by kotofsky** [comment] 2024-06-06 17:49
Can I assign this issue to me? Want to start to contribute.

**Comment by kotofsky** [comment] 2024-06-07 16:35
Looks like this bug was caused by TVDB plugin, which has already fixed.

**Closed** 2024-06-07 20:22 UTC
Labels: bug, confirmed
