### ISSUE TITLE
[Issue]: 10.9.0/10.9.1 Server hangs and become unresponsive with nothing in the logs

### ISSUE THREAD

**Issue by SingingFrog7** [jellyfin/jellyfin#11617] opened 2024-05-14 03:13 UTC
### Please describe your bug

Since updating to 10.9.0 and after updating to 10.9.1, the server will sometimes hang during playback and will become unresponsive (from all clients and from the web app). There's nothing useful in the logs when it happens. It can happens 2-3 times during the same 30 min or not happen during multiple hours. I didn't find a correlation yet, I set the logs to debug to see if I can get more info

I restart the service and it will work again for 10 mins or 10 hours

### Reproduction Steps

1. Start playback
2. Wait until the playback stop an the server is unresponsive

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.4-3-pve
- Virtualization: LXC
- Clients: Web, Kodi, GoogleTV...
- Browser: Firefox, but most likely all
- FFmpeg Version: jellyfin-ffmpeg6 6.0.1-6-bookworm
- Playback Method: Doesn't matter but last was with Direct Play
- Hardware Acceleration: QSV (but not necessarily used when crashing)
- GPU Model: Intel N100
- Plugins: LDAP-Auth, Kodi Sync Queue, Reports, Playback Reporting
- Reverse Proxy: None
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2024-05-14 02:50:27.373 +00:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-05-14 02:50:39.380 +00:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-05-14 02:50:51.387 +00:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-05-14 02:50:51.387 +00:00] [INF] Lost 1 WebSockets.
[2024-05-14 02:51:03.895 +00:00] [INF] Lost 1 WebSockets.
```

With debug:
```shell
[2024-05-14 03:26:21.557 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:21.566 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:21.566 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:21.577 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:22.187 +00:00] [DBG] Playback progress did not have a tracker : "85f46053-6c47-41b7-8361-df3dd17c9fbc-9aebb6e39658488dafdb637b2b680c7f-9545e5f8722101ccc76cccba63d10c3a"
[2024-05-14 03:26:22.187 +00:00] [DBG] PingTranscodingJob PlaySessionId="ffa793a0b83d4b45a79a586e6a21cb98" isUsedPaused: False
[2024-05-14 03:26:22.422 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:22.422 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:22.579 +00:00] [INF] Processing playback tracker : "b7cd04aeae70a1df1c2f67fcc9ca238092ca3b8b-364dbd37d2184710856b9aa58f99e8ed-2d4e808ded47357eb431208645dc21ae"
[2024-05-14 03:26:22.579 +00:00] [DBG] ProcessProgress : "EventCount(2)Event(5/14/2024 3:20:20 a.m.,START)Event(5/14/2024 3:26:22 a.m.,STOP)Diff(362,362)Total(362)"
[2024-05-14 03:26:22.586 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:23.187 +00:00] [DBG] Playback progress did not have a tracker : "85f46053-6c47-41b7-8361-df3dd17c9fbc-9aebb6e39658488dafdb637b2b680c7f-9545e5f8722101ccc76cccba63d10c3a"
[2024-05-14 03:26:23.187 +00:00] [DBG] PingTranscodingJob PlaySessionId="ffa793a0b83d4b45a79a586e6a21cb98" isUsedPaused: False
[2024-05-14 03:26:23.403 +00:00] [DBG] Watching 3 WebSockets.
[2024-05-14 03:26:23.413 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:23.413 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:23.579 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:24.187 +00:00] [DBG] Playback progress did not have a tracker : "85f46053-6c47-41b7-8361-df3dd17c9fbc-9aebb6e39658488dafdb637b2b680c7f-9545e5f8722101ccc76cccba63d10c3a"
[2024-05-14 03:26:24.187 +00:00] [DBG] PingTranscodingJob PlaySessionId="ffa793a0b83d4b45a79a586e6a21cb98" isUsedPaused: False
[2024-05-14 03:26:24.413 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:24.413 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:24.561 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:24.562 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:24.564 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:25.187 +00:00] [DBG] Playback progress did not have a tracker : "85f46053-6c47-41b7-8361-df3dd17c9fbc-9aebb6e39658488dafdb637b2b680c7f-9545e5f8722101ccc76cccba63d10c3a"
[2024-05-14 03:26:25.187 +00:00] [DBG] PingTranscodingJob PlaySessionId="ffa793a0b83d4b45a79a586e6a21cb98" isUsedPaused: False
[2024-05-14 03:26:25.415 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:25.415 +00:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-05-14 03:26:25.565 +00:00] [DBG] PingTranscodingJob PlaySessionId="953142877a604b8e83a9013d69069a8b" isUsedPaused: False
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" received message: InboundWebSocketMessage`1 { Data: JsonElement { ValueKind: String }, MessageType: SessionsStart, ServerId: null }
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" begin transmitting to "SessionInfoWebSocketListener"
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" received message: InboundWebSocketMessage`1 { Data: JsonElement { ValueKind: String }, MessageType: ScheduledTasksInfoStart, ServerId: null }
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" begin transmitting to "ScheduledTasksWebSocketListener"
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" received message: InboundWebSocketMessage`1 { Data: JsonElement { ValueKind: String }, MessageType: ScheduledTasksInfoStart, ServerId: null }
[2024-05-14 03:26:25.750 +00:00] [DBG] WS "172.27.50.12" begin transmitting to "ScheduledTasksWebSocketListener"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MoldyTaint** [comment] 2024-05-14 03:27
Currently experiencing the same issues

**Comment by SingingFrog7** [comment] 2024-05-14 03:29
I added the logs with "debug" level of my last hang

**Comment by SingingFrog7** [comment] 2024-05-14 04:43
> Could be related #11588

RAM usage is definitively higher than before updating
I updated from 10.8.13-1 to 10.9.0+deb12 on 2024-05-12  18:38:13
![image](https://github.com/jellyfin/jellyfin/assets/22401071/7d048892-dd51-4784-874c-48149c5e0e3a)

That said, it doesn't seem it went over 3GB, the container should still be fine with the 4GB I gives it, but I can increase it and see

**Comment by felix920506** [comment] 2024-05-14 05:19
Closing as duplicate of #11344

**Closed by felix920506** 2024-05-14 05:19 UTC
Labels: bug
