### ISSUE TITLE
Library Scanning Fails Have to manually add new items

### ISSUE THREAD

**Issue by hakarune** [jellyfin/jellyfin#9247] opened 2023-02-03 20:49 UTC
### Please describe your bug

Triggers from external organizing apps, pressing the scan all libraries, and scheduled library scan all fail. Have completely deleted library and wiped docker twice and problem still persists. Problem appears to be related to the files in my library in some way.

Logs are from after pressing manual scan. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Devaun Chimera
- Virtualization: Docker
- Clients: Browser, Android TV & Android Phone
- Browser: Brave & Chrome
- FFmpeg Version: from docker
- Hardware Acceleration: NVEC enabled and working
- Plugins: a FEW like fanart, tvdb. Not important to library scan issue. 
- Reverse Proxy: no
- Base URL: 10.1.1.10
- Networking: LAN
- Storage: 8TB
```

### Please attach any browser or client logs here

[Scan Error Logs](https://pastebin.com/5b8NrCTH) 

### Please attach any screenshots here

![Screenshot_20230203_122919](https://user-images.githubusercontent.com/2251942/216707251-f9a19b8f-96f3-4ad0-890c-bde3030ed3e4.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2023-02-03 22:39
Duplicate of #9038

**Closed by cvium** 2023-02-03 22:39 UTC
Labels: bug
