### ISSUE TITLE
[Issue]: Items in collections disappear after refreshing metadata

### ISSUE THREAD

**Issue by joshuaavalon** [jellyfin/jellyfin#12155] opened 2024-06-22 10:47 UTC
### Please describe your bug

I found that no matter if you add item through Web UI or plugins. The items in collections will be removed after refreshing metadata.

### Reproduction Steps

1. Start a new Jellyfin 10.9.6 
2. Create a movie library with at least two movies that exists the same TMDb Box Sets
3. Install [Jellyfin TMDb Box Sets Plugin](https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets)
4. Run the plugin the add movies to collections
5. Go the the collection and run `Refresh Metadata` > `Replace all metadata`
6. All the items in the collection disappear

I can confirm it works before 10.9

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian  11
- Linux Kernel: N/A
- Virtualization: Docker
- Clients: Web
- Browser: Chrome
- FFmpeg Version: N/A
- Playback Method: Web
- Hardware Acceleration: Yes
- GPU Model: RTX 4060
- Plugins: Jellyfin TMDb Box Sets Plugin
- Reverse Proxy: Traefik
- Base URL: N/A
- Networking: N/A
- Storage: Local
```

### Jellyfin logs

```shell
Not related
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Liquoriced** [comment] 2024-06-22 14:01
I wonder if this is connected to #12032 which seems to have been forgotten.

**Comment by joshuaavalon** [comment] 2024-06-22 16:28
I though it may be caused by merging data during refresh . So, I create #12156.

However, it may be caused by validation changes in `/MediaBrowser.Controller/Entities/Folder.cs` after I look around more in the code. I am not familiar with the code flow. Can maintainer take a look at it?

**Comment by maximo1984** [comment] 2024-06-23 00:44
> I wonder if this is connected to #12032 which seems to have been forgotten.

Yes, sad to see that my report is falling by the way side for such an important thing that needs remedy.

**Comment by Shadowghost** [comment] 2024-06-24 08:00
If you're using the boxset plugin this likely needs to be fixed over there. Issue should be that the LinkedChildren are discarded on merge instead of replaced.

**Comment by joshuaavalon** [comment] 2024-06-24 09:28
@Shadowghost I believe it does not belongs to the plugin because the plugin is only a metadata provider.
I have checked the API that metadata provider cannot access `LinkedChildren`. A metadata provider can only provide a metadata result (for user to choose), the merging is handled by Jellyfin

**Comment by Shadowghost** [comment] 2024-06-24 09:55
Then we need to either change the specific implementation of `MergeData` in `BoxSetMetadataService` or modify the provider handling in `MetadataService`. I don't use the plugin, so I haven't experienced this myself. My manually created Collections work just fine.
Not sure if I can find the time over the week to install the plugin and debug it.

**Comment by joshuaavalon** [comment] 2024-06-24 14:43
@Shadowghost I think manually created collections work fine because the is no default metadata provider. So it won't try to refresh metadata.

I have tried to add manually or via plugin. They work fine until a refresh happen.

**Comment by Liquoriced** [comment] 2024-06-27 17:54
I can confirm that this is not caused by the boxset plugin: I didn't have the plugin installed and I edited the collections, but when I re-scanned the media, the default collections returned.

**Comment by solidsnake1298** [comment] 2024-07-19 21:49
I was able to reproduce, but not ALL of the items in my collections were removed.  There doesn't appear to be a rhyme or reason to which collections items remained and what didn't.

**Comment by cxfksword** [comment] 2024-09-05 03:12
@solidsnake1298 this issue can also reproducce by jellyfin default create collection feature, reproduction steps:

1. Go to `Dashboard -> Libraries` settings, open movie library `Automatically add to collection`
2. Add at least two movies that exists the same TMDb Box Sets
3. Wait movies refresh metadata finish
4. Go to `Dashboard -> Scheduled Tasks`, Run `Scan Media Library`
5. Go to Collection, Edit collection metadata, uncheck `Lock this item to prevent future changes`
6. Run collection `Refresh Metadata > Replace all metadata` 
7. Refresh page and all the items in the collection disappear

I discovered that the `mergeMetadataSettings` is set to `false` in 10.8, but it changes to `true` in 10.9.

10.8:
https://github.com/jellyfin/jellyfin/blob/e93d03d8cbff2122d7296f477604146f64758a73/MediaBrowser.Providers/Manager/MetadataService.cs#L760


10.9:
https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.Providers/Manager/MetadataService.cs#L781

`mergeMetadataSettings` code:
https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.Providers/BoxSets/BoxSetMetadataService.cs#L55-L58

**Comment by Shadowghost** [comment] 2024-09-05 07:12
The latter one is likely the issue here and being incorrect. Should be something like this
```
                if (replaceData || targetItem.LinkedChildren.Length == 0)
                {
                    targetItem.LinkedChildren = sourceItem.LinkedChildren;
                }
                else
                {
                    targetItem.LinkedChildren = sourceItem.LinkedChildren.Concat(targetItem.LinkedChildren).Distinct().ToArray();
                }
```

**Closed** 2024-09-20 13:46 UTC
Labels: bug, confirmed

**Comment by joshuaavalon** [comment] 2024-10-31 14:48
@Shadowghost I have just tested 10.10.0. It seems it is still happening.
