### ISSUE TITLE
Jellyfin starts next episode randomly before the episode is finished

### ISSUE THREAD

**Issue by flaxplax** [jellyfin/jellyfin#8006] opened 2022-06-25 13:04 UTC
It randomly starts next episode without warning. It can happen between 5-15 minutes into the episode.
Here is some logs. Not sure why this is happening. It started to happen after I updated my server.
Have reinstalled the whole server and done everything from scratch again, without getting rid of this annoying problem.

## Logs
```
/videos/b444f508-6069-0ae0-d8f5-a996da9c49a3/hls1/main/256.ts

{"Protocol":0,"Id":"b444f50860690ae0d8f5a996da9c49a3","Path":"/mnt/media/anime/legend-of-the-galactic-heroes/season-2/[Reaktor] Legend of the Galactic Heroes - s2e05 [720p][x265][10-bit].mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":181735184,"Name":"[Reaktor] Legend of the Galactic Heroes - s2e05 [720p][x265][10-bit]","IsRemote":false,"ETag":"c34d41d3011c9f7396dc79a81e6b1d30","RunTimeTicks":14848029696,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"720p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":979174,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":720,"Width":960,"AverageFrameRate":29.97003,"RealFrameRate":29.97003,"Profile":"Main 10","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":93,"IsAnamorphic":null},{"Codec":"ac3","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Japanese","VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Japanese - Dolby Digital - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":192000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"ass","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Subtitles","VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Subtitles - Undefined - Default - ASS","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":3,"FileName":"aaaiight.ttf","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":4,"FileName":"ARIAL.TTF","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":5,"FileName":"cosmic2n.ttf","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":6,"FileName":"georgiab.TTF","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":7,"FileName":"lsans.ttf","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":8,"FileName":"L_10646.TTF","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":9,"FileName":"Maian.TTF","MimeType":"application/x-truetype-font","DeliveryUrl":null},{"Codec":"otf","CodecTag":"[0][0][0][0]","Comment":null,"Index":10,"FileName":"QlassikBold_TB.otf","MimeType":"application/vnd.ms-opentype","DeliveryUrl":null},{"Codec":"ttf","CodecTag":"[0][0][0][0]","Comment":null,"Index":11,"FileName":"tt0448m_.ttf","MimeType":"application/x-truetype-font","DeliveryUrl":null}],"Formats":[],"Bitrate":1171174,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:19:45.011 -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid -autorotate 0 -i file:"/mnt/media/anime/legend-of-the-galactic-heroes/season-2/[Reaktor] Legend of the Galactic Heroes - s2e05 [720p][x265][10-bit].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p4 -b:v 4895870 -maxrate 4895870 -bufsize 9791740 -profile:v:0 high -g:v:0 90 -keyint_min:v:0 90 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=format=yuv420p" -codec:a:0 libfdk_aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 256 -hls_segment_filename "/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90.m3u8"


ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3 --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[matroska,webm @ 0x56083ce43340] The tags at index 3 refer to a non-existent track 4.
[matroska,webm @ 0x56083ce43340] The tags at index 4 refer to a non-existent track 5.
[matroska,webm @ 0x56083ce43340] The tags at index 5 refer to a non-existent track 6.
[matroska,webm @ 0x56083ce43340] The tags at index 6 refer to a non-existent track 7.
[matroska,webm @ 0x56083ce43340] The tags at index 7 refer to a non-existent track 8.
[matroska,webm @ 0x56083ce43340] The tags at index 8 refer to a non-existent track 9.
[matroska,webm @ 0x56083ce43340] The tags at index 9 refer to a non-existent track 10.
[matroska,webm @ 0x56083ce43340] The tags at index 10 refer to a non-existent track 11.
[matroska,webm @ 0x56083ce43340] The tags at index 11 refer to a non-existent track 12.
Input #0, matroska,webm, from 'file:/mnt/media/anime/legend-of-the-galactic-heroes/season-2/[Reaktor] Legend of the Galactic Heroes - s2e05 [720p][x265][10-bit].mkv':
  Metadata:
    title           : [Reaktor] Legend of the Galactic Heroes - E031
    CREATION_TIME   : 2018-03-06T09:56:50Z
    ENCODER         : Lavf57.7.2
  Duration: 00:24:44.80, start: 0.000000, bitrate: 979 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 92.083000
      Metadata:
        title           : Opening
    Chapter #0:1: start 92.083000, end 843.668000
      Metadata:
        title           : Part A
    Chapter #0:2: start 843.668000, end 1371.526000
      Metadata:
        title           : Part B
    Chapter #0:3: start 1371.526000, end 1464.578000
      Metadata:
        title           : Ending
    Chapter #0:4: start 1464.578000, end 1484.765000
      Metadata:
        title           : Preview
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 960x720 [SAR 1:1 DAR 4:3], 29.97 fps, 29.97 tbr, 1k tbn (default)
  Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      title           : Japanese
  Stream #0:2: Subtitle: ass (default)
    Metadata:
      title           : Subtitles
  Stream #0:3: Attachment: ttf
    Metadata:
      filename        : aaaiight.ttf
      mimetype        : application/x-truetype-font
  Stream #0:4: Attachment: ttf
    Metadata:
      filename        : ARIAL.TTF
      mimetype        : application/x-truetype-font
  Stream #0:5: Attachment: ttf
    Metadata:
      filename        : cosmic2n.ttf
      mimetype        : application/x-truetype-font
  Stream #0:6: Attachment: ttf
    Metadata:
      filename        : georgiab.TTF
      mimetype        : application/x-truetype-font
  Stream #0:7: Attachment: ttf
    Metadata:
      filename        : lsans.ttf
      mimetype        : application/x-truetype-font
  Stream #0:8: Attachment: ttf
    Metadata:
      filename        : L_10646.TTF
      mimetype        : application/x-truetype-font
  Stream #0:9: Attachment: ttf
    Metadata:
      filename        : Maian.TTF
      mimetype        : application/x-truetype-font
  Stream #0:10: Attachment: otf
    Metadata:
      filename        : QlassikBold_TB.otf
      mimetype        : application/vnd.ms-opentype
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : tt0448m_.ttf
      mimetype        : application/x-truetype-font
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, hls, to '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90.m3u8':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (High), cuda(tv, bt709, progressive), 960x720 [SAR 1:1 DAR 4:3], q=2-31, 4895 kb/s, 29.97 fps, 90k tbn (default)
    Metadata:
      encoder         : Lavc59.18.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 4895870/0/4895870 buffer size: 9791740 vbv_delay: N/A
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 384 kb/s (default)
    Metadata:
      encoder         : Lavc59.18.100 libfdk_aac
frame=    1 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90256.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90257.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90258.ts' for writing
frame=  308 fps=0.0 q=12.0 size=N/A time=00:00:10.21 bitrate=N/A dup=60 drop=0 speed=18.1x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90259.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90260.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90261.ts' for writing
frame=  630 fps=592 q=10.0 size=N/A time=00:00:20.92 bitrate=N/A dup=125 drop=0 speed=19.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90262.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90263.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90264.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90265.ts' for writing
frame=  941 fps=601 q=14.0 size=N/A time=00:00:31.29 bitrate=N/A dup=187 drop=0 speed=  20x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90266.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90267.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90268.ts' for writing
frame= 1252 fps=606 q=11.0 size=N/A time=00:00:41.70 bitrate=N/A dup=249 drop=0 speed=20.2x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90269.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90270.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90271.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90272.ts' for writing
frame= 1567 fps=611 q=11.0 size=N/A time=00:00:52.20 bitrate=N/A dup=312 drop=0 speed=20.4x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90273.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90274.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90275.ts' for writing
frame= 1877 fps=612 q=15.0 size=N/A time=00:01:02.52 bitrate=N/A dup=363 drop=0 speed=20.4x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90276.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90277.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90278.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90279.ts' for writing
frame= 2194 fps=615 q=14.0 size=N/A time=00:01:13.08 bitrate=N/A dup=363 drop=0 speed=20.5x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90280.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90281.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90282.ts' for writing
frame= 2502 fps=615 q=9.0 size=N/A time=00:01:23.43 bitrate=N/A dup=396 drop=0 speed=20.5x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90283.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90284.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90285.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90286.ts' for writing
frame= 2820 fps=617 q=10.0 size=N/A time=00:01:33.99 bitrate=N/A dup=460 drop=0 speed=20.6x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90287.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90288.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90289.ts' for writing
frame= 3141 fps=619 q=13.0 size=N/A time=00:01:44.74 bitrate=N/A dup=524 drop=0 speed=20.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90290.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90291.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90292.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90293.ts' for writing
frame= 3449 fps=619 q=16.0 size=N/A time=00:01:54.98 bitrate=N/A dup=565 drop=0 speed=20.6x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90294.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90295.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90296.ts' for writing
frame= 3762 fps=620 q=9.0 size=N/A time=00:02:05.50 bitrate=N/A dup=626 drop=0 speed=20.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90297.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90298.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90299.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90300.ts' for writing
frame= 4075 fps=620 q=11.0 size=N/A time=00:02:15.91 bitrate=N/A dup=689 drop=0 speed=20.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90301.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90302.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90303.ts' for writing
frame= 4391 fps=620 q=19.0 size=N/A time=00:02:26.47 bitrate=N/A dup=752 drop=0 speed=20.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90304.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90305.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90306.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90307.ts' for writing
frame= 4713 fps=622 q=14.0 size=N/A time=00:02:37.22 bitrate=N/A dup=816 drop=0 speed=20.7x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90308.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90309.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90310.ts' for writing
frame= 5027 fps=622 q=12.0 size=N/A time=00:02:47.68 bitrate=N/A dup=879 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90311.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90312.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90313.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90314.ts' for writing
frame= 5340 fps=623 q=11.0 size=N/A time=00:02:58.11 bitrate=N/A dup=942 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90315.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90316.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90317.ts' for writing
frame= 5652 fps=623 q=9.0 size=N/A time=00:03:08.52 bitrate=N/A dup=1000 drop=0 speed=20.8x    
More than 1000 frames duplicated
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90318.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90319.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90320.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90321.ts' for writing
frame= 5971 fps=623 q=17.0 size=N/A time=00:03:19.21 bitrate=N/A dup=1056 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90322.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90323.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90324.ts' for writing
frame= 6288 fps=624 q=14.0 size=N/A time=00:03:29.77 bitrate=N/A dup=1110 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90325.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90326.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90327.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90328.ts' for writing
frame= 6607 fps=624 q=15.0 size=N/A time=00:03:40.39 bitrate=N/A dup=1173 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90329.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90330.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90331.ts' for writing
frame= 6920 fps=624 q=9.0 size=N/A time=00:03:50.84 bitrate=N/A dup=1230 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90332.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90333.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90334.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90335.ts' for writing
frame= 7235 fps=624 q=18.0 size=N/A time=00:04:01.32 bitrate=N/A dup=1284 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90336.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90337.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90338.ts' for writing
frame= 7551 fps=625 q=13.0 size=N/A time=00:04:11.88 bitrate=N/A dup=1339 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90339.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90340.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90341.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90342.ts' for writing
frame= 7862 fps=624 q=11.0 size=N/A time=00:04:22.25 bitrate=N/A dup=1348 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90343.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90344.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90345.ts' for writing
frame= 8178 fps=625 q=15.0 size=N/A time=00:04:32.81 bitrate=N/A dup=1399 drop=0 speed=20.8x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90346.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90347.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90348.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90349.ts' for writing
frame= 8501 fps=625 q=11.0 size=N/A time=00:04:43.62 bitrate=N/A dup=1460 drop=0 speed=20.9x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90350.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90351.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90352.ts' for writing
frame= 8815 fps=626 q=21.0 size=N/A time=00:04:54.08 bitrate=N/A dup=1511 drop=0 speed=20.9x    
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90353.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90354.ts' for writing
[hls @ 0x56083d2c6b00] Opening '/var/lib/jellyfin/transcodes/070339ed88807049067daeba93024f90355.ts' for writing
frame= 8985 fps=625 q=10.0 Lsize=N/A time=00:04:59.64 bitrate=N/A dup=1545 drop=0 speed=20.8x    
video:128873kB audio:14055kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Server System:**
 - OS: Ubuntu 20.04 inside lxc container
 - Jellyfin Version: 10.8.0
 - Hardware settings & device: NVENC on quadro p400
 - Reverse proxy: nginx 
 - Other hardware notes: GPU passed through as physical device
 
**Client System:**
 - Device: Desktop
 - OS: Fedora 36
 - Client: Browser
 - Browser (if Web client): Firefox
 - Client and Browser Version: 101.0.1

### Edit changed to correct log file

**Comment by nyanmisaka** [comment] 2022-06-25 14:41
Duplicate of #6957

**Closed by nyanmisaka** 2022-06-25 14:41 UTC
