### ISSUE TITLE
Search will find adult actresses even though they are tagged with 'xxx'

### ISSUE THREAD

**Issue by TorATB** [jellyfin/jellyfin#8218] opened 2022-08-07 09:01 UTC
![image](https://user-images.githubusercontent.com/37066848/183283255-2736db15-9c41-431f-b377-f6122e7ee8ef.png)
The same issue persists with all users (not just administrator, like in this picture)
If a user searches for 'a' and scrolls down to "people", he will find all people, even adult actresses (if you have adult films), and their profile picture might be NSFW, so having the "Block items with tag" is a really nice feature, if only it worked properly... Is it possible to take a look at this feature, and implement it properly? Thanks!

**Comment by Jack20947** [comment] 2022-08-11 13:41
I may also add that when serching people, in the result there are also listed actors/actresses that are not in availables library.

Example: Libraries L1 and L2, user A has access only to L1.
If user A search something, actors/actresses from L2 are listed in the result.
This with 1.8.3 (and was like this also for 1.7.7)

**Comment by thornbill** [comment] 2022-08-26 00:40
Duplicate of #2207

**Closed by thornbill** 2022-08-26 00:40 UTC
