### ISSUE TITLE
Playlist items can't be removed; server returns 204

### ISSUE THREAD

**Issue by pikapower9080** [jellyfin/jellyfin#12971] opened 2024-11-05 15:24 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After setting up a fresh Jellyfin docker install on 10.10.1, I cannot remove items added to my own music playlist. When selecting "Remove from Playlist" the browser makes a DELETE request to remove the item, but the server rejects it with error 502 (Request empty). This applies to the web client, the media player, and even third party clients like Finamp.

![Image](https://github.com/user-attachments/assets/27052878-1416-47be-b2f7-833d70451324)

### Reproduction steps

1. Log into any account on Jellyfin
2. Create a music playlist, public or private
3. Right click an item in the playlist and select "Remove from Playlist"

### What is the current _bug_ behavior?

The playlist remains unchanged instead of having the item be removed.

### What is the expected _correct_ behavior?

The playlist should update to have the item removed.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

- OS: Ubuntu oracular 24.10
- Linux Kernel: 6.11.0-8-generic
- Virtualization: Docker
- Clients: Browser, Media Player, Finamp
- Browser: Chromium 130
- FFmpeg Version: 7.0.2
- Playback Method:
- Hardware Acceleration:
- GPU Model: 
- Plugins: Webhook
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local

### Jellyfin logs

No logs are produced by this action.

### Client / Browser logs

This is the log I believe to be relevant:
![Image](https://github.com/user-attachments/assets/39cdc419-20fd-4119-b641-c73b3621cf8b)

### Additional information

This same issue happens on both a fresh server an an existing server that are both running on 10.10.1. Re-ordering of playlist items also does not work, the server responds with 500, but that is a different issue. Playlist length does not seem to impact this issue.

**Comment by GreepTheSheep** [comment] 2024-11-05 18:39
Could be a duplicate of #12892

**Comment by felix920506** [comment] 2024-11-05 19:05
cc @Shadowghost

**Comment by pikapower9080** [comment] 2024-11-05 19:58
> Could be a duplicate of [#12892](https://github.com/jellyfin/jellyfin/issues/12892)
> 
> Also, same issue on my side on v10.10.1, on Debian 12 with Docker 26.0.0

These are similar issues but not technically the same. Not being able to remove playlist options is also mentioned there, though.

**Comment by Shadowghost** [comment] 2024-11-05 20:16
It's all caused by the same issue fixed in #12934

**Comment by felix920506** [comment] 2024-11-06 04:48
Closing as duplicate of #12892

**Closed by felix920506** 2024-11-06 04:48 UTC
Labels: bug
