### ISSUE TITLE
Server "crashes" after stopping a playback in the android client

### ISSUE THREAD

**Issue by DevonDekhran** [jellyfin/jellyfin#9624] opened 2023-04-10 12:55 UTC
**Describe the bug**
I have the server on my PC and client on an android tablet. I started an episode, the used the return gesture to go back into my library, afterwards the server stopped by itself. I used both the web player and the integrated player options.

**To Reproduce**
1. Start a playback in the android client
2. Immediately return/close the player
3. Bug happens

**Logs**

> [2023-04-10 09:44:49.351 -03:00] [INF] [1] Main: Jellyfin version: "10.8.9"
[2023-04-10 09:44:49.365 -03:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2023-04-10 09:44:49.369 -03:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2023-04-10 09:44:49.371 -03:00] [INF] [1] Main: Operating system: "Windows"
[2023-04-10 09:44:49.372 -03:00] [INF] [1] Main: Architecture: X64
[2023-04-10 09:44:49.373 -03:00] [INF] [1] Main: 64-Bit Process: True
[2023-04-10 09:44:49.374 -03:00] [INF] [1] Main: User Interactive: True
[2023-04-10 09:44:49.375 -03:00] [INF] [1] Main: Processor count: 24
[2023-04-10 09:44:49.376 -03:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2023-04-10 09:44:49.377 -03:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2023-04-10 09:44:49.378 -03:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2023-04-10 09:44:49.448 -03:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2023-04-10 09:44:49.473 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-04-10 09:44:49.484 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "jellyfin-ani-sync, Version=2.7.1.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Ani-Sync_2.7.1.0\jellyfin-ani-sync.dll"
[2023-04-10 09:44:49.487 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniDB, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\AniDB_7.0.0.0\Jellyfin.Plugin.AniDB.dll"
[2023-04-10 09:44:49.489 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.AniList, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\AniList_5.0.0.0\Jellyfin.Plugin.AniList.dll"
[2023-04-10 09:44:49.564 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-04-10 09:44:49.565 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-04-10 09:44:49.566 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-04-10 09:44:49.573 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-04-10 09:44:49.574 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-04-10 09:44:50.773 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Ani-Sync" "2.7.1.0"
[2023-04-10 09:44:50.775 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniDB" "7.0.0.0"
[2023-04-10 09:44:50.777 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AniList" "5.0.0.0"
[2023-04-10 09:44:50.778 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.9.0"
[2023-04-10 09:44:50.779 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.9.0"
[2023-04-10 09:44:50.780 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.9.0"
[2023-04-10 09:44:50.781 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.9.0"
[2023-04-10 09:44:50.783 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.9.0"
[2023-04-10 09:44:50.813 -03:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2023-04-10 09:44:50.981 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-04-10 09:44:51.035 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.2"
[2023-04-10 09:44:51.066 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2023-04-10 09:44:51.095 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2023-04-10 09:44:51.120 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-04-10 09:44:51.220 -03:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2023-04-10 09:44:51.240 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2023-04-10 09:44:51.321 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2023-04-10 09:44:51.323 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "0a68bcfe03534776b04c56c8838eb629"
[2023-04-10 09:44:51.378 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0501665
[2023-04-10 09:44:51.379 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2023-04-10 09:44:51.474 -03:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "H:\Anime"
[2023-04-10 09:44:51.474 -03:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "H:\AniMovie"
[2023-04-10 09:44:51.474 -03:00] [INF] [1] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Starting NAT discovery
[2023-04-10 09:44:51.533 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1525929
[2023-04-10 09:44:51.534 -03:00] [INF] [1] Main: Startup complete 0:00:02.2799638
[2023-04-10 09:45:39.913 -03:00] [INF] [14] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2023-04-10 09:45:39.952 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.954 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.955 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.957 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.958 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.959 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.960 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.962 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.963 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.964 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.965 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.966 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:39.968 -03:00] [WRN] [9] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-04-10 09:45:40.339 -03:00] [ERR] [18] Jellyfin.Drawing.Skia.SkiaEncoder: Unable to determine image dimensions for "H:\Anime\[Anipakku] Kaguya-sama wa Kokurasetai꞉ Tensai-tachi no Renai Zunousen (S01+S02+OVA) [BD 1080p][HEVC x265 10bit][Dual Audio][Multi-Subs]\(2ª Temporada) Kaguya-sama wa Kokurasetai？ Tensai-tachi no Renai Zunousen\metadata\[Anipakku] Kaguya-sama wa Kokurasetai？ Tensai-tachi no Renai Zunosen 01.jpg": InternalError
[2023-04-10 09:45:41.177 -03:00] [INF] [26] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.18.128" request
[2023-04-10 09:45:43.454 -03:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Dekhran". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-04-10 09:45:43.499 -03:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="H:\Anime\[SubsPlease] Akiba Maid Sensou\[Subsplease] Akiba Maid Sensou - 01V2 (1080P) [123F6377].mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported, AudioCodecNotSupported ) "media:/videos/219ae67a-e2b7-ce3a-df39-32bc7839d59e/stream.mp4?MediaSourceId=219ae67ae2b7ce3adf3932bc7839d59e&VideoCodec=h264,hevc,vp9,av1,hevc&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=44100&MaxFramerate=23.976025&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=2a204db32852041c87a9a21c00cc1c4d&hevc-level=120&hevc-videobitdepth=8&hevc-profile=main&hevc-audiochannels=2&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported"
[2023-04-10 09:45:44.008 -03:00] [INF] [25] Jellyfin.Api.Helpers.TranscodingJobHelper: "ffmpeg" "-analyzeduration 200M -fflags +genpts  -i file:\"H:\Anime\[SubsPlease] Akiba Maid Sensou\[Subsplease] Akiba Maid Sensou - 01V2 (1080P) [123F6377].mkv\" -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 copy -f mp4 -movflags frag_keyframe+empty_moov -y \"C:\ProgramData\Jellyfin\Server\transcodes\9b987d729fc78b3b1f5d584c7c5fcce0.mp4\""
[2023-04-10 09:45:44.461 -03:00] [INF] [21] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2023-04-10 09:45:45.155 -03:00] [WRN] [14] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.18.55:8096/videos/219ae67a-e2b7-ce3a-df39-32bc7839d59e/stream.mp4?DeviceId=0b748690928956e8&MediaSourceId=219ae67ae2b7ce3adf3932bc7839d59e&VideoCodec=h264,hevc,vp9,av1,hevc&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=44100&MaxFramerate=23.976025&PlaySessionId=e14b40f2c8ae4229860328013543e677&api_key=ba25460839f940419d74eec57491b32c&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=2a204db32852041c87a9a21c00cc1c4d&hevc-level=120&hevc-videobitdepth=8&hevc-profile=main&hevc-audiochannels=2&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported" to "192.168.18.128" in 0:00:01.1790556 with Status Code 200
[2023-04-10 09:45:51.981 -03:00] [INF] [22] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "C:\ProgramData\Jellyfin\Server\transcodes\9b987d729fc78b3b1f5d584c7c5fcce0.mp4"
[2023-04-10 09:45:53.511 -03:00] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.4.4" playing "Oink It Up! Starting Today, You're an Akiba Maid!". Stopped at "5670" ms
[2023-04-10 09:45:53.521 -03:00] [WRN] [22] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.18.55:8096/Sessions/Playing/Stopped" to "192.168.18.128" in 0:00:01.5473969 with Status Code 204
[2023-04-10 09:45:53.540 -03:00] [FTL] [22] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**System (please complete the following information):**
 - OS: Windows 11 // Android 13
 - Jellyfin Version: [e.g. 10.8.9]

**Comment by oddstr13** [comment] 2023-04-10 13:01
This is not a Kodi issue.
I see `jellyfin_ani_sync` in the log, so it looks like it might be a plugin causing the crash?

**Comment by oddstr13** [comment] 2023-04-10 13:06
Duplicate of #9262 
Upstream issue: vosmiic/jellyfin-ani-sync#60

**Closed** 2023-04-10 13:06 UTC
