### ISSUE TITLE
Jellyfin page doesn't display 

### ISSUE THREAD

**Issue by WhatSupQuebec** [jellyfin/jellyfin#5498] opened 2021-03-12 00:43 UTC
**Describe the bug**
Since today I am not able to connect to my jellyfish server with a web browser see screenshot. The web browser does not work, but I try with my Roku and it works. I was thinking about a problem with the template I use (https://prayag17.github.io/JellyFlix/) I try to change for another template in the files /etc/jellyfin/branding.xml but that doesn't fix the issue. If i refresh my page i can see the jellyfin logo quickly but it disappears

**System (please complete the following information):**
 - OS: Linux Ubuntu 20.04.2 LTS (Focal Fossa)
 - Browser: Edge / chrome / firefox
 - Jellyfin Version: 10.7.0
 - Installed Plugins: https://prayag17.github.io/JellyFlix/
 - Storage: local

![image](https://user-images.githubusercontent.com/71474060/110874372-a08ef100-82a1-11eb-9e74-6523e92bfa87.png)

**Comment by crobibero** [comment] 2021-03-12 01:08
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2493

**Closed by crobibero** 2021-03-12 01:08 UTC
Labels: bug
