### ISSUE TITLE
Live TV not working after upgrade to 10.7.0

### ISSUE THREAD

**Issue by bluestairs** [jellyfin/jellyfin#5531] opened 2021-03-14 16:33 UTC
**Describe the bug**
I use HDHomerun to broadcast local tv, if I go to HDHomerun app and go to any channel it works absolutely fine, even its working fine with TVHeadend. There was no issue with the earlier version of JellyFin as well but right after upgrade it shows all the channels and when you click on it connection circle keeps moving but never loads the video stream

**System (please complete the following information):**
 - OS: RaspberryPi, Ubuntu 20.04 and Macos Big Sur
 - Virtualization: N/A
 - Clients: Browser, Roku, FireStick
 - Browser: Safari 14, Chrome 89
 - Jellyfin Version: 10.7.0
 - Playback: Direct Stream
 - Installed Plugins: TVHeadend
 - Reverse Proxy: None
 - Base URL: [e.g. none, yes: /example]
 - Networking: Home network seperate device
 - Storage: Local

**To Reproduce**
1. Go to Jellyfin UI
2. Go to Dashboard
3. Scroll down to Live TV
4. Add Tuner
5. Select HDHometun
6. wait for detection and add the tuner
7. Go to Live TV on the main dashboard
8. Click on Channels Tab
9. Select any Channel
10. Progress circle will keep showing but no connection with the stream

**Expected behavior**

**Logs**

**Screenshots**

<img width="1432" alt="Screen Shot 2021-03-14 at 12 33 21 PM" src="https://user-images.githubusercontent.com/5586987/111076162-8a5f7b80-84c1-11eb-9ef5-5ce8a65bad35.png">

**Additional context**

**Comment by crobibero** [comment] 2021-03-14 16:36
Duplicate of:
https://github.com/jellyfin/jellyfin/issues/5491
#5427 
#5438
https://github.com/jellyfin/jellyfin/issues/5513

Fixed by: https://github.com/jellyfin/jellyfin/pull/5444

**Closed by crobibero** 2021-03-14 16:36 UTC
Labels: bug

**Comment by bluestairs** [comment] 2021-03-14 16:55
@crobibero But this does not reflect on the latest update that I downloaded, can you please tell me how can I apply this patch?

**Comment by crobibero** [comment] 2021-03-14 16:56
You have to wait until 10.7.1 is released.

**Comment by bluestairs** [comment] 2021-03-14 16:57
@bluestairs Thanks a ton, aprox timeline for the release?
