### ISSUE TITLE
Error in DummySeasonProvider

### ISSUE THREAD

**Issue by Ainto** [jellyfin/jellyfin#2047] opened 2019-11-24 04:58 UTC
**Describe the bug**
This error occurred while scanning the TV show.This situation will not affect the media library of movie classification.
I suspect that the failure to access tvdb caused the timeout and this error occurred. Because my current network can't open https://thetvdb.com/

**To Reproduce**
You can try to block tvdb from reproducing the problem.
This also results in a long period of loading when you manually modify the episode picture

**Logs**
[2019-11-24 03:54:35.299 +00:00] [ERR] Error in DummySeasonProvider
System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.GetResponseAsync(WebRequest httpRequest, CancellationToken cancellationToken)
   at TvDbSharper.Infrastructure.ApiClient.SendRequestAsync(ApiRequest request, CancellationToken cancellationToken)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.get_TvDbClient()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.<>c__DisplayClass18_0.<GetEpisodesPageAsync>b__0()
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)

**System (please complete the following information):**
 - OS: Linux Docker
 - Browser: Chrome 80
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Additional context**
How can I set the season provider timeout or better disable it?

**Comment by tyhawk** [comment] 2019-11-25 12:58
Duplicate of #1771 and #2006

**Closed** 2020-01-28 22:26 UTC
Labels: bug
