### ISSUE TITLE
If av1 forced to be transcoded in browser, it doesn't use both HW and Tone-mapping. It also uses vp8 and not h.264

### ISSUE THREAD

**Issue by 0TTA** [jellyfin/jellyfin#8089] opened 2022-07-08 22:46 UTC
This happens to me only in browser. It transcodes amazingly in the IOS app.

**Media Info of the file**
Format                                   : WebM
Format version                           : Version 4
File size                                : 1.24 GiB
Duration                                 : 1 h 41 min
Overall bit rate                         : 1 751 kb/s
Writing application                      : Lavf59.16.100
Writing library                          : Lavf59.16.100

Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L4.0
Codec ID                                 : V_AV1
Duration                                 : 1 h 41 min
Width                                    : 1 920 pixels
Height                                   : 800 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 1 h 41 min
Channel(s)                               : 8 channels
Channel layout                           : L R C Ls Rs Lb Rb LFE
Sampling rate                            : 48.0 kHz
Bit depth                                : 32 bits
Compression mode                         : Lossy
Delay relative to video                  : 19 ms
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Logs**

**FFmpeg Logs**
Stream #0:0: Video: av1 (Main), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x800, Film Grain, SAR 1:1 DAR 12:5, 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      DURATION        : 01:41:11.773000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, 7.1, fltp (default)
    Metadata:
      DURATION        : 01:41:11.772000000
[libdav1d @ 0x5588c02bebc0] libdav1d 1.0.0-0-g99172b1
Stream mapping:
  Stream #0:0 -> #0:0 (av1 (libdav1d) -> vp8 (libvpx))
  Stream #0:1 -> #0:1 (opus (native) -> opus (libopus))
Press [q] to stop, [?] for help
[Parsed_subtitles_3 @ 0x5588c056acc0] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[Parsed_subtitles_3 @ 0x5588c056acc0] Using font provider fontconfig
[libvpx @ 0x5588c0360780] v1.9.0
Output #0, webm, to '/config/transcodes/7a1ba08a0ad23e6fdd68f85a8d4e4374.webm':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: vp8, yuv420p(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], q=2-31, 7296 kb/s, 23.98 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.18.100 libvpx
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 14592640 vbv_delay: N/A
  Stream #0:1: Audio: opus, 48000 Hz, stereo, flt, 128 kb/s (default)
    Metadata:
      encoder         : Lavc59.18.100 libopus
frame=    1 fps=0.0 q=0.0 size=       1kB time=00:00:00.03 bitrate= 175.8kbits/s speed=4.03x    
frame=   36 fps=0.0 q=0.0 size=       1kB time=00:00:01.66 bitrate=   3.5kbits/s speed=3.23x    
frame=   76 fps= 74 q=0.0 size=       1kB time=00:00:03.34 bitrate=   1.7kbits/s speed=3.27x    
frame=  115 fps= 75 q=0.0 size=       1kB time=00:00:05.00 bitrate=   1.2kbits/s speed=3.29x    
frame=  151 fps= 75 q=0.0 size=     212kB time=00:00:06.42 bitrate= 270.4kbits/s speed=3.17x    
frame=  186 fps= 73 q=0.0 size=     212kB time=00:00:07.92 bitrate= 219.2kbits/s speed=3.13x    
frame=  224 fps= 74 q=0.0 size=     212kB time=00:00:09.54 bitrate= 182.0kbits/s speed=3.14x    

**Stats for Nerds Screenshots**
https://imgur.com/a/aZXjSCe

**Server System (please complete the following information):**
 - OS: Docker on unRAID.
 - Jellyfin Version: jellyfin/jellyfin:10.8.1.
 - Hardware settings & device: NVENC on P2000.
 
**Client System (please complete the following information):**
 - Device: PC.
 - OS: Win10
 - Client: Web/Browser.
 - Browser: all of them.

**Comment by snakeeater4526** [comment] 2022-10-28 09:54
I have the exact same issue, however the issue is also here on Android device ( it doesn't want to transcode at all because android probably doesn't support vp8).
It's really annoying issue because that mean I can't really transcode my video to av1 and delete the original... Since not all client support av1.

I have also another problem, you can't transcode to h264 10mbit if your av1 is 1.5mbit, we should be able to force transcode and not be limited by the bitrate

**Comment by aaruni96** [comment] 2022-11-16 13:18
I have a similar problem.

I have a media file with AV1 Main and a bunch of opus audio tracks (in mkv). Firefox can open the the same stuff if shoved into an mp4 container with `-c:v copy -c:a copy -c:s copy` options in ffmpeg.

However trying to play this with jellyfin (in mkv) fails , and tries to transcode video into vp8 (when just stream copy should've sufficed).

Note how in the stats for nerds, it says its transcoding because audio tracks are not supported, but it bogs my entire server down because it also tries to transcode video.

Stats for nerds :

![image](https://user-images.githubusercontent.com/7453256/202190797-8ef181b8-b8b4-4cd0-9535-c3c3c891aed7.png)

**Comment by aaruni96** [comment] 2022-11-16 13:29
Quick update: For me, this only happens when I try to use an audio track which is not the first audio track. If I choose the first audio track, the file is direct played as expected.

Therefore direct play is clearly supported, but video is been unncesserily transcoded also.

This appears to be at least a partial regression on Issue #6450

**Comment by nyanmisaka** [comment] 2022-11-16 13:37
#7325 is the root cause, which enabled progressive transcoding for much more cases. We shouldn't transcode to VP9 or even VP8, it's not verified, and it's far slower than H264 and HEVC.

**Comment by snakeeater4526** [comment] 2022-11-16 14:35
> #7325 is the root cause, which enabled progressive transcoding for much more cases. We shouldn't transcode to VP9 or even VP8, it's not verified, and it's far slower than H264 and HEVC.

How is it even possible that the code select vp8... It's completely crazy and should have never happened.
Why even vp8 is a transcode possibility...

Idk how the code is made but I found that very strange^^

**Comment by snakeeater4526** [comment] 2022-11-19 22:12
just noticed that the problem mainly happen on jellyfin-web, for exemple it happen in android app (with web player). But not in the windows app ( which use mpv).
However there still the problem of not wanting to transcode below the source bitrate... which mean 9.7mbps 4k source is stuck either at source or at 720p at best... but no 1080p 10mb.... which is again annoying and not normal

**Comment by nyanmisaka** [comment] 2022-11-20 10:48
This should be fixed by #8779

**Comment by snakeeater4526** [comment] 2023-01-31 15:02
can confirm it's fixed, can be closed. Thanks a lot

**Closed** 2023-01-31 15:07 UTC

**Comment by snakeeater4526** [comment] 2023-02-08 22:14
the bug about the bitrate is back since very recently ( tested 08/02/2023 )
