### ISSUE TITLE
[Issue]: can't click on save button on networking configuration

### ISSUE THREAD

**Issue by blastrock** [jellyfin/jellyfin#7446] opened 2022-03-11 19:42 UTC
### Please describe your bug

Steps to reproduce:

1. login with an admin account
2. go to Settings -> Admin -> Dashboard -> Advanced -> Networking
3. click on Save

And nothing happens. The Chrome console will say `An invalid form control with name='' is not focusable.`

I dug deeper, it seems it's because of this part of the form which is of `class="hide"`:

![image](https://user-images.githubusercontent.com/1370530/157941332-883172b7-47a5-4bdb-84f0-f85543917f71.png)

And this one

![image](https://user-images.githubusercontent.com/1370530/157944469-ce7c1362-0a8a-4390-bda2-9d4b1b43f331.png)

The SSDP Filter's default value does not pass the validation regex `[0-9\.]*`, same for the UDP communication range. The default values in these hidden fields should not be undefined.

Also, note the typo in the field description of UDP Communacation Range, the upper bound should be 65535 I believe.

Btw, I'm curious now, is there an option to show all these hidden options ?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu server 20.04
- Virtualization: Docker
- Clients: Browser
- Browser: Chromium 99, Firefox 96 (Firefox is broken, but there is no error in the console)
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-03-12 16:22
Closing as duplicate of https://github.com/jellyfin/jellyfin-web/issues/3440

**Closed by crobibero** 2022-03-12 16:22 UTC
Labels: bug
