### ISSUE TITLE
Upgrading from Jellyfin 10.7.0 to 10.7.1

### ISSUE THREAD

**Issue by rx570gtx1060** [jellyfin/jellyfin#5597] opened 2021-03-22 18:49 UTC
This is in regards to the generic build in the tar format.

I tried creating a symbolic link between the new directory within the directory /opt/jellyfin like so:

ln -s jellyfin_10.7.1 jellyfin

That worked successfully.However when I tried to run the script listed in the documentation about the installation process in the directory /opt/jellyfin I got the error:

./jellyfin.sh:line 6 /opt/jellyfin/jellyfin/jellyfin: No such file or directory.

Is there any way that this can be solved?

By the way I already opened a post on the Jellyfin Subreddit under the name fireknoxwinter

**Comment by Celedhrim** [comment] 2021-03-23 08:45
Seems that 10.7.1 is build on musl

```
$ ldd jellyfin_10.7.0/jellyfin
        linux-vdso.so.1 (0x00007fff3ffb0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffa99d48000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffa99d42000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffa99b75000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffa99a31000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffa99a17000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa99852000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffa99fa7000)
```

And 

```
$ ldd jellyfin_10.7.1/jellyfin
        linux-vdso.so.1 (0x00007ffde9582000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f390a22f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f390a215000)
        libc.musl-x86_64.so.1 => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f390a0d1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3909f0c000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f390a42d000)
```

I don't know hos to have this lib in debian , I tried to install musl package with no success

**Comment by SBado** [comment] 2021-03-23 09:01
See https://github.com/jellyfin/jellyfin/issues/5594.

**Comment by cvium** [comment] 2021-03-23 09:25
duplicate of #5594

**Closed by cvium** 2021-03-23 09:26 UTC
