### ISSUE TITLE
Collections not being created on scan after updating to 10.7.0

### ISSUE THREAD

**Issue by docfactory37** [jellyfin/jellyfin#5585] opened 2021-03-22 01:17 UTC
**Describe the bug**
Sync updating to Jellyfin 10.7.0

It looks like that Creting **Collections** have spoted working.

i have TMDb Box Sets installed (You currently have version 7.0.0.0 installed)

**System (please complete the following information):**
 - OS: image linuxserver/jellyfin
 - Virtualization: Docker
 - Jellyfin Version: 10.7.0 stable
 - Installed Plugins: TMDb Box Sets
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**
i have the below in Plugings

![image](https://user-images.githubusercontent.com/20963053/111928427-aab5b880-8b07-11eb-93a8-d8f44bef916f.png)

i ahve this set to run ever 45 minutes

**Expected behavior**

**Logs**
`[2021-03-22 12:12:28.750 +11:00] [INF] [109] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-03-22 12:12:39.092 +11:00] [INF] [83] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan library for new box sets"
[2021-03-22 12:12:39.093 +11:00] [INF] [83] Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask: Starting TMDbBoxSets refresh library task`

Im not able to see any errors in the log file output before starting and then prints out the collection that it has found.
but dose not find new ones as i have add you movies that its not putting them into collection.

e.g i have the move Cloudy with a Chance of Meatballs and Cloudy with a Chance of Meatballs 2 but it has not created a collection on scan.

**Comment by ThePeoplesBards** [comment] 2021-03-23 03:38
Do you use underscores in your naming path? I noticed TMDB does not support searching with "_" so none of my files are found by TMDB as I do not use spaces in file names. This could be the cause #5583

**Comment by docfactory37** [comment] 2021-03-23 19:51
Hey @ThePeoplesBards, no I use . (Dots) Instead of spaces or underscores.

**Comment by ThePeoplesBards** [comment] 2021-03-23 20:53
@docfactory37 Good to know, TMDB does not support searching with dots either. Someone suggested I use them as a workaround for underscores so I tried it out and no dice.

Im guessing the plugin looks through existing metadata for "TheMovieDb Box Set Id:" which will be empty if the metadata was not retrieved from TMDB. Take a look at  Cloudy with a Chance of Meatballs 1 and 2's metadata by selecting edit metadata and take a look at the value of "TheMovieDb Box Set Id:". 

If its empty you can manually enter the value or re-identify the titles making sure when searching to select the TMDB result. This might be an acceptable work around depending on the number of titles. If not a more drastic find and replace of your filenames to replace "." with " " and a fresh library scan to replace the metadata could work. That up to you, I'm holding out because I don't want to change my naming convention. I hope some of this info helps in some way.

**Comment by docfactory37** [comment] 2021-03-24 07:55
@ThePeoplesBards  thank you for the info :) but I wonder when this changed as it use to work will out any issue with the .

I will see if I will do a bulk rename or put up with it lol ☺️

**Comment by cvium** [comment] 2021-03-24 10:08
Please stop saying TMDb doesn't work with dots and underscores. The issue was identified and fixed in 10.7.1 https://github.com/jellyfin/jellyfin/pull/5559

**Comment by ThePeoplesBards** [comment] 2021-03-24 11:40
@cvium so it has, thanks for letting me know. I will close the bug I opened. @docfactory37 this could have happened because theTVDB was dropped as a metadata provider in 10.7 and their search supported "." and "_" so your anything missed by TMDB would have been caught by theTVDB. Hopefully the fix @cvium implemented resolves your issue as well without having to rename your files.

**Comment by docfactory37** [comment] 2021-03-24 22:10
All good, I may just need to force a metadata refresh to make sure my data is correct, was not aware of the fix in 10.7 as it worked for me in 10.6 I will also check I have the metadata plugin install correctly.

**Closed** 2021-06-03 21:56 UTC
Labels: bug
