### ISSUE TITLE
Loop crash

### ISSUE THREAD

**Issue by NunzioArdi** [jellyfin/jellyfin#2122] opened 2019-12-08 13:23 UTC
Sorry, I use a translator.

**Describe the bug** 

When jellyfin (or when I launch it), an error occurs and the server restarts in a loop.
I can, for example, listen to music but there will be interruptions at each crash.
I have no idea where this bug could have come from.

thank you

**Expected behavior**
install package with command on jellyfin's website

**Logs**

https://pastebin.com/t9HL01X0

**System:**
 - OS: ArchLinux X64
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Processor: AMD Athlon 240ge

**Comment by Bond-009** [comment] 2019-12-29 14:26
Duplicate of #1705

**Closed by Bond-009** 2019-12-29 14:26 UTC
Labels: bug
