### ISSUE TITLE
Slow dashboard load

### ISSUE THREAD

**Issue by bekon16** [jellyfin/jellyfin#1418] opened 2019-05-30 08:30 UTC
To see main dashboard i have to wait about 8 (or more) seconds every time when i access or reload page.

Problem exist in: Chrome Version: 74.0.3729.169 (also in incognito mode) and MS Edge - 42.17134.1.0, Safari mobile version and probably in other web browsers too.

Below is the screen from Chrome console (network Tab).
![jellyfin](https://user-images.githubusercontent.com/45873735/58618302-89e0fb00-82c2-11e9-8c7f-6d333c794c75.png)

System:
 - OS: Debian 9 (for jellyfin server)
 - Browser: Chrome, Edge
 - Jellyfin Version:  10.3.3
 - Reverse proxy: Apache

If you need any additional logs etc, please let me know and i will collect them.

**Comment by bekon16** [comment] 2019-05-30 09:26
Issue explanation in ticket: #1419 and #679 
After enabling DNS service for jellyfin server, dashboard load very fast, but as i mentioned in previous ticket:
Something need fix because if jellyfin server is only in LAN network and does not have access to internet or only for DNS service this issue occur and dashboard loads very long.

**Comment by sparky8251** [comment] 2019-06-25 19:09
This is a duplicate of #679. We are aware it is an issue and want to solve it by removing it.

WAN IP detection serves no real purpose after all. It just is used by the Jellyfin for Kodi addon and no one has stepped up to remove the requirement in that client yet.

**Closed by sparky8251** 2019-06-25 19:09 UTC
Labels: bug
