### ISSUE TITLE
Films that have two versions show up twice in Continue Watching

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#12049] opened 2024-06-09 16:45 UTC
### Please describe your bug

If you have a film with two versions, for example
Big Buck Bunny (2008) - 1080P.mp4
Big Buck Bunny (2008) - 2160P 60FPS.mp4
and start watching it, then stop, the film appears twice in Continue Watching.

### Reproduction Steps

1. Create a film with a 1080p and a 4K version, like
Big Buck Bunny (2008) - 1080P.mp4
Big Buck Bunny (2008) - 2160P 60FPS.mp4

2. Watch the film for a few minutes or fast-forward to some position in the middle.
3. Go back to your home screen and observe two entries in Continue Watching.

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients: Tested on Android TV and iPhone
- Browser: Tested on Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
I wouldn't know how to find the relevant information
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/35429038/3988a9da-3139-48b3-9371-629c0b758cad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThomasPGH** [comment] 2024-06-09 17:33
Now also tested with Swiftfin on iPhone (playback and stop, plus Continue Watching entries from other clients). The result is the same. All these films show up twice.

**Comment by ThomasPGH** [comment] 2024-06-11 00:02
That's a more interesting game if you even got more than only two versions of a film ;)

![Screenshot 2024-06-11 010044](https://github.com/jellyfin/jellyfin/assets/35429038/4c1aead9-5c52-41f5-93d5-38d92022cdef)

**Comment by crobibero** [comment] 2024-06-19 13:23
Duplicate of https://github.com/jellyfin/jellyfin/issues/7429

**Closed by crobibero** 2024-06-19 13:23 UTC
Labels: bug

**Comment by ThomasPGH** [comment] 2024-06-19 19:00
> Duplicate of #7429

Not sure if it really is a duplicate but they might of course be related. This issue here definitely wasn't in 10.8.13. It started after the update to 10.9.6.
