### ISSUE TITLE
Recorded TV shows may have cryptic folder/file names rather than title of show

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin#2370] opened 2020-02-03 14:15 UTC
I am using JellyFin DVR to record TV shows OTA in the US using Schedules Direct data.

I frequently see irregularly named shows that are a sequence of letters/numbers/symbols. For example, see: 

<img width="276" alt="irregular filenames" src="https://user-images.githubusercontent.com/7338491/73660140-9d204380-4665-11ea-8457-8742bf638ae6.png">

Within tvshow.nfo, the correct show name is written (and therefore is known for purposes of writing the show title in the folder/files). Further, the episode jpg shows the correct poster art for the show even though it is misnamed.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>
  <zap2itid>EP00373256</zap2itid>
  <title>Mexico: One Plate at a Time With Rick Bayless</title>
  <mpaa>TV-G</mpaa>
</tvshow>
```

**Comment by samwathegreat** [comment] 2020-03-22 17:16
I'm experiencing the same issue:

![image](https://user-images.githubusercontent.com/4813336/77255547-c3626880-6c3e-11ea-8bd9-63f4ef6b5caf.png)

![image](https://user-images.githubusercontent.com/4813336/77255549-c9584980-6c3e-11ea-81a2-0db7fa1373af.png)

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>
  <title>Gold Rush: Dave Turin's Lost Mine</title>
  <mpaa>TV-14</mpaa>
</tvshow>`

I'm a new jellyfin user -- most of my library was imported with folder names already correct.  I'm using 10.5.0 and this is the only version I have been on.

I'm unable to find any relevant settings that would seem to cause this behavior as jellyfin clearly knows what the actual show is.  Easy current workaround is to manually rename folders then re-scan the library, but how do we fix it moving forward?

Thanks

**Comment by samwathegreat** [comment] 2020-03-24 15:17
Can anyone help?  Why isn't this marked as a bug and how do we get it marked as such so that someone will look into it?

**Comment by PrplHaz4** [comment] 2020-03-24 16:28
The pattern between what you've both posted seems to be a colon `:` in the title of the show - might be an issue specific to a windows filesystem.

Are both of you running Jellyfin on a windows server?

**Comment by samwathegreat** [comment] 2020-03-24 16:33
@PrplHaz4 

Thanks for your input.

I have jellyfin installed on a Ubuntu 18.04 container running in LXC.  I do have 1 windows client, but the server is entirely Linux.

I do think you are on to something, however.  I would suspect jellyfin's metadata engine being confused by the colon.

**Comment by PrplHaz4** [comment] 2020-03-24 17:28
> 
> 
> @PrplHaz4
> 
> Thanks for your input.
> 
> I have jellyfin installed on a Ubuntu 18.04 container running in LXC. I do have 1 windows client, but the server is entirely Linux.
> 
> I do think you are on to something, however. I would suspect jellyfin's metadata engine being confused by the colon.

Is the storage on a Samba share?  can you verify that all your devices (incl server) see the same title?

**Comment by samwathegreat** [comment] 2020-03-24 17:46
@PrplHaz4 

The storage is a bind mount to a folder on the host (Proxmox).  The folder on ZFS storage.

I do have another container which shares this same ZFS folder out via SAMBA so that I can dump files inside from windows machines.  But jellyfin basically has direct access via the bind mount and knows nothing of SAMBA.  So jellyfin sees it as native storage on it's own filesystem.

Interestingly, now I see where you are going with this.  If I shell directly into the ZFS Folder, the directory shows up correctly.  So it would seem that the issue is with SAMBA and has nothing to do with jellyfin.

Thanks for leading me in the right direction.... 

![image](https://user-images.githubusercontent.com/4813336/77459187-b5931b80-6dd5-11ea-915e-8b888be157ba.png)

**Comment by samwathegreat** [comment] 2020-03-24 17:59
This definitely appears to be a SAMBA issue.  It looks like the solution is not ideal - making some modifications to the samba server allows the "illegal characters" to be rendered as something else (e.g. change all colons to percent signs).  Now I'm thinking it may be easier to tell jellyfin to change anything with colon in the title to a dash instead.

Does anyone have any thoughts?

**Comment by classicjazz** [comment] 2020-03-24 18:05
I am running JellyFin on Docker on a Synology NAS.

**Comment by PrplHaz4** [comment] 2020-03-24 19:31
Does it actually show the incorrect title on any of the clients or in the web ui, or just when you browse the directory from windows (in file explorer or something)?

Maybe switch to using NFS on the windows machine?

I don't like the idea of changing the colon as I'm guessing it would break matching for metadata providers?

**Comment by samwathegreat** [comment] 2020-03-24 20:05
@PrplHaz4 

Since many of us run jellyfin on windows, I'm wondering how this is being addressed currently.  You can not create a folder nor a file with a colon inside it on Windows.  So clearly there must already be a workaround for the metadata - I'm guessing having the title correct in the nfo files?  My point is that there must be a difference between the linux and windows variants of Jellyfin, because the mere creation of such folders (containing colons) is impossible on Windows machines.

So what I'm interested in is finding out how the windows variant of Jellyfin handles this issue already, then adapt that method.

Are you involved in the development here?

**Comment by samwathegreat** [comment] 2020-03-24 20:19
As a side note, one of the folders I imported to Jellyfin was "Star Trek Picard", which jellyfin correctly retreived metadata for "Star Trek: Picard", so missing the colon completely does not appear to affect metadata retrieval.  It shows in the library with the colon, but the folder itself contains no colon.

**Comment by PrplHaz4** [comment] 2020-03-24 20:24
> 
> 
> @PrplHaz4
> 
> The incorrect title only shows when browsing from SAMBA on the windows machines. The issue does, however, prevent us from adding to these folders from non-linux machines while keeping the naming structure intact.
> 
> Since many of us run jellyfin on windows, I'm wondering how this is being addressed currently. You can not create a folder nor a file with a colon inside it on Windows. So clearly there must already be a workaround for the metadata - I'm guessing having the title correct in the nfo files? My point is that there must be a difference between the linux and windows variants of Jellyfin, because the mere creation of such folders (containing colons) is impossible on Windows machines.
> 
> So what I'm interested in is finding out how the windows variant of Jellyfin handles this issue already, then adapt that method.
> 
> Are you involved in the development here?

Nope.  @Bond-009 might have an idea on how filenames with illegal characters are handled on windows.

**Comment by classicjazz** [comment] 2020-04-03 22:04
To be clear, I am running MacOS and Synology NAS exclusively though the Synology folders are mounted by the Macs using SMB v3 (which was originally a Windows file protocol).

**Comment by samwathegreat** [comment] 2020-04-03 22:17
@classicjazz 

Unfortunately, SAMBA is the culprit here.  Samba does not support any filenames with colons in it, whatsoever, regardless of the operating system you are viewing the samba share on.

SAMBA could handle this issue one of two ways:  It can either *completely ingore* any file/folder with a colon in it.  If it did this, such folders and/or files would be invisible - you wouldn't even know they exist unless you access the storage location DIRECTLY (not via SAMBA) using a linux (or likely MAC, also) machine.  This is how SAMBA used to operate - before their Devs created the current workaround (which you and I originally assumed was a Jellyfin bug).

OR Samba could generate a random folder/filename for any items containing colons.  That way those using samba can at least see the file, albeit it with a cryptic name. (This is the current behavior of SAMBA).

Anyways, the point is that this really isn't Jellyfin's fault at all.

I **WOULD** like to see Jellyfin's behavior changed in regards to any titles with colons - it could (and I think SHOULD) silently drop the colon.

I have confirmed that metadata retrieval is unaffected by the colon not being present, and since the Windows fork of jellyfin server already makes some sort of accommodation, I would like to see the linux version altered to function the same way.

So the DEVS *CAN* alter Jellyfin to compensate for this issue, but the issue itself is not at all the fault of Jellyfin, if that makes sense.

Here's hoping that the Devs find (and implement) a simple solution.

**Comment by classicjazz** [comment] 2020-08-01 14:59
Confirming that this is still an issue with 10.6.1. For example, "CBS This Morning: Saturday". 

And that, as shown above, banner.jpg, poster.jpg, fanart.jpg, and seasonxx-poster.jpg are not written to the folder.

I propose a simple string replacement, swapping the colon for underscore. This should then properly retrieve associated images/metadata.

**Comment by azlm8t** [comment] 2020-08-03 22:30
Have you looked in to Samba's "vfs objects = catia" with "mangled names = no" in the global section of the smb.conf?  (see man vfs_catia for other options).  This maps illegal characters in filenames.

FWIW, Tvheadend (a PVR) has an option to replace the following characters in filenames with an underscore:
`/:\<>|*?"`
This seems to be the characters that a lot of Microsoft documents recommend not using.  They also recommend "Do not end a file or directory name with a space or a period."

So, if a similar feature were implemented in Jellyfin then perhaps those other characters should also be replaced.  For example, would "/" cause an issue if the title of an episode were about "AC/DC" and it interpret it as a file called "AC" in a sub-directory "DC"?

**Comment by classicjazz** [comment] 2020-12-04 15:36
This is still an issue with 10.6.4.

**Comment by Ullmie02** [comment] 2021-01-24 11:49
This is a samba issue. You can add this line to the global section of your samba config (typically located at `/etc/samba/smb.conf`):
```
mangled names = no
```
This will show the correct folder names in the Windows Explorer. However, you cannot access this folder from a Windows machine because Windows doesn't support `:` in folder names as mentioned before.

We do check if a filename is valid before writing it to the filesystem. However, if you run Jellyfin on a Linux machine, `:` returns as a valid character and thus doesn't get removed from the filename.

**Closed** 2023-07-01 17:39 UTC
Labels: bug, confirmed, upstream
