### ISSUE TITLE
Playing Live TV Finds Invalid Data

### ISSUE THREAD

**Issue by ManfredRichthofen** [jellyfin/jellyfin#2117] opened 2019-12-07 20:12 UTC
A .ts Live TV stream

**Log**
```
http://192.168.0.110:8090/jellyfin/videos/c988218f-56af-7880-4181-327dfaf1d912/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzAuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83MC4wfDE1NzQwMjQ1NzU5MDY1&MediaSourceId=44f437b82a279f7918f0b4fc26705546&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=-1&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=88e4fa6be3664ab3af59bc0fd5525f11&api_key=3aa5c0411efb40aab9b37b8fb134949f&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_44f437b82a279f7918f0b4fc26705546&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

{"Protocol":"Http","Id":"44f437b82a279f7918f0b4fc26705546","Path":"http://127.0.0.1:8090/LiveTv/LiveStreamFiles/91bcd334eb5f4e549a6251f5c8cdc460/stream.ts","Type":"Default","IsRemote":true,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_44f437b82a279f7918f0b4fc26705546","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"VideoRange":"SDR","DisplayTitle":"","IsInterlaced":true,"BitRate":20000000,"IsDefault":false,"IsForced":false,"Type":"Video","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false},{"DisplayTitle":"","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"Formats":[],"Bitrate":20000000,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"},"AnalyzeDurationMs":3000}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -i "http://127.0.0.1:8090/LiveTv/LiveStreamFiles/91bcd334eb5f4e549a6251f5c8cdc460/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 20000000 -bufsize 40000000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -vf "yadif=0:-1:0,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -flags -global_header -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/2e051050e43415f191c01be66d9fe079/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/2e051050e43415f191c01be66d9fe079.m3u8" -y "/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/2e051050e43415f191c01be66d9fe079%d.ts"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
http://127.0.0.1:8090/LiveTv/LiveStreamFiles/91bcd334eb5f4e549a6251f5c8cdc460/stream.ts: Invalid data found when processing input
```

**Server System**
 - OS: Ubuntu 18.4.3 Lts
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: No HW Acceleration 
 - Reverse proxy: Does not work on local or behind nginx
 
**Client System**
 - Device: Custom HTPC, Samsung S7, Iphone 7, Iphone 10R, 4k FireTV
 - OS: iOS, Android, Windows
 - Client: Web/Browser, Android, Android TV, IOS
 - Browser Firefox, Chrome, Safari
 - Client and Browser Version: Firefox 71, Chrome 78.0.3904.108

**Comment by mooninite** [comment] 2019-12-31 05:56
Duplicate of issue #1921

**Closed** 2020-01-06 06:05 UTC
Labels: mediaplayback
