### ISSUE TITLE
Chinese characters display on library cover get error

### ISSUE THREAD

**Issue by caoli5288** [jellyfin/jellyfin#5872] opened 2021-04-20 09:15 UTC
**Describe the bug**

Chinese characters display on library cover get error

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Browser
 - Browser: ALL
 - Jellyfin Version: 10.7.2
 - Playback: ALL
 - Installed Plugins: indifferent
 - Reverse Proxy: indifferent
 - Base URL: indifferent
 - Networking: indifferent
 - Storage: indifferent

**To Reproduce**

1. Open homepage

**Expected behavior**

**Logs**

**Screenshots**

![图片](https://user-images.githubusercontent.com/3120587/115370784-f7baa680-a1fb-11eb-9630-84e5069eed24.png)

**Additional context**

**Comment by cvium** [comment] 2021-04-20 09:21
Duplicate of https://github.com/jellyfin/jellyfin/issues/5008

**Closed by cvium** 2021-04-20 09:21 UTC
Labels: bug
