### ISSUE TITLE
There isn't a jellyfin release for Ubuntu 20.10 Groovy

### ISSUE THREAD

**Issue by anagram3k** [jellyfin/jellyfin#5271] opened 2021-02-20 04:26 UTC
**Describe the bug**
The only package available for Ubuntu 20.10 is:

jellyfin-ffmpeg/unknown 4.3.1-4-groovy amd64

 - OS: Ubuntu 20.10

**To Reproduce**

Run the commands (described on https://jellyfin.org/downloads/):
```
sudo apt install apt-transport-https
wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
sudo apt update
sudo apt install jellyfin
```
Result:
```
E: Unable to locate package jellyfin
```

**Expected behavior**
installation of jellyfin

**Comment by crobibero** [comment] 2021-02-20 04:30
Duplicate of https://github.com/jellyfin/jellyfin/issues/4569, https://github.com/jellyfin/jellyfin/issues/4379

**Closed by crobibero** 2021-02-20 04:30 UTC
Labels: bug

**Comment by anagram3k** [comment] 2021-02-20 05:24
After reading the linked issues, I was able to install jellyfin. 
I will list what I did to help other users with the same problem:

```
sudo apt install jellyfin-ffmeg
```
Edit the file /etc/apt/sources.list.d/jellyfin.list and change groovy to bionic
```
sudo apt update
sudo apt install jellyfin
```
PS: I changed back bionic to groovy to wait for the official bionic release.
