### ISSUE TITLE
Resume does not work in android App

### ISSUE THREAD

**Issue by goliath888** [jellyfin/jellyfin#2598] opened 2020-03-15 11:41 UTC
Resuming a TV Show does not work in Android app. It always starts from the beginning. With Chrome works well and starts from last position. 

Try playing from one device and resuming from another and viceversa, and chrome works well but on android allways starts from the beginning. 

Server:
JellyFin on Docker (LinuxServer image)
JellyFin version Versión: 10.5.0

Clients: 
Chrome version:  79.0.3945 (Win 10)
Android app version: 0.9.9 (Android 9.0)

This is the log while I was doing this tests: https://pastebin.com/jr3RQuXW

Anything else needed, just ask.

**Comment by eltiel** [comment] 2020-03-16 05:26
Probably a duplicate of this https://github.com/jellyfin/jellyfin-web/issues/899

**Comment by dkanada** [comment] 2020-03-16 05:57
@eltiel is correct, please follow that issue for updates.

**Closed by dkanada** 2020-03-16 05:57 UTC
