### ISSUE TITLE
Media scanner broken in 10.4.2 WIN10

### ISSUE THREAD

**Issue by didnt1able** [jellyfin/jellyfin#2060] opened 2019-11-26 07:00 UTC
```
[2019-11-26 01:53:33.666 -05:00] [INF] "IntervalTrigger" fired for task: "Scan media library"
[2019-11-26 01:53:33.667 -05:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2019-11-26 01:53:38.409 -05:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
```
`[INF] Validating media library`
Reverting to 10.4.1 resolves the issue.
Is present on exe and zip

**Comment by JustAMan** [comment] 2019-11-27 13:19
@cvium @Bond-009 does this ring a bell for you?

**Comment by cvium** [comment] 2019-11-28 07:32
The exception is pretty normal. It just means the websocket connection was forcefully closed.

**Comment by JustAMan** [comment] 2019-11-28 09:07
@didnt1able any chance you can reproduce the error (media scanning broken on 10.4.2) and post a more complete log?

**Comment by didnt1able** [comment] 2019-11-28 09:44
There is no more pertaining to the issue in the log. It hangs on validating.
```
[04:40:44] [INF] ServerId: a52eb328ffd74662b917cb933e08a407
[04:40:45] [INF] Executed all pre-startup entry points in 0:00:00.205289
[04:40:45] [INF] Core startup complete
[04:40:45] [INF] Watching directory F:\Movies & TV\Movies
[04:40:45] [INF] Watching directory F:\Movies & TV\TV
[04:40:45] [INF] Watching directory D:\Anime
[04:40:45] [INF] Executed all post-startup entry points in 0:00:00.3447632
[04:40:47] [INF] StartupTrigger fired for task: Check for plugin updates
[04:40:47] [INF] Queueing task PluginUpdateTask
[04:40:47] [INF] Executing Check for plugin updates
[04:40:48] [INF] Check for plugin updates Completed after 0 minute(s) and 1 seconds
[04:40:48] [INF] ExecuteQueuedTasks
[04:40:54] [INF] WS http://tv.didnt1able.space/socket?api_key=572a66badec548e58cb10536248d55eb&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc3LjAuMzg2NS45MCBTYWZhcmkvNTM3LjM2fDE1NzAwMTI0OTc5NjY1. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
[04:41:09] [INF] Executing Scan media library
[04:41:09] [INF] Stopping directory watching for path F:\Movies & TV\TV
[04:41:09] [INF] Stopping directory watching for path F:\Movies & TV\Movies
[04:41:09] [INF] Stopping directory watching for path D:\Anime
[04:41:09] [INF] Validating media library
```

**Comment by JustAMan** [comment] 2019-11-29 13:36
@didnt1able is this the whole log? Looks too short to me...

**Comment by didnt1able** [comment] 2019-11-29 19:41
Thats  from the output window. The scan hangs at 0% in /web and never progresses. It hung there until I restarted the server.

**Comment by RazeLighter777** [comment] 2019-11-30 02:19
Can confirm. 10.4.1 was able to complete scans, but 10.4.2 scans are broken (never complete with same error) in docker version on Linux.

**Comment by sunbrown** [comment] 2019-11-30 12:16
I got the same problem in 10.4.2,and I downgraded to 10.4.1.

**Comment by rpatterson** [comment] 2019-11-30 22:42
I think this is a duplicate of #2059 and should be closed in favor of the better detail there.

**Comment by anthonylavado** [comment] 2019-12-05 16:52
Continuing discussion on #2059

**Closed by anthonylavado** 2019-12-05 16:53 UTC
Labels: bug, duplicate
