### ISSUE TITLE
Live TV can't play on window jellyfin 10.7.0

### ISSUE THREAD

**Issue by xinstein** [jellyfin/jellyfin#5513] opened 2021-03-13 02:28 UTC
**Describe the bug**
try to play a livetv channel and I see the following error in console
 Error processing request: The process cannot access the file ${the transcode file which is being generated} because it is being used by another process.

But the background process continues to fetch live stream even after the web UI is completely close, in my case a whole night.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: None
 - Clients: Browser and android
 - Browser: Chrome 80
 - Jellyfin Version: 10.7.0
 - Playback: Transcode
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: None
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1. play any configured live tv channel
2. 
3. See the described error in channel, the webui never-endingly shows the rotating circle.

**Expected behavior**

It should play normally as it did yesterday in 10.6.4 before I upgraded to 10.7.0

**Logs**

[10:25:02] [ERR] [21] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The process cannot access the file '{PROGRAMDATA}\Jellyfin\Server\transcodes\6334ca7635524fe7bed8a999f8fab703.ts' because it is being used by another process. URL GET /LiveTv/LiveStreamFiles/6334ca7635524fe7bed8a999f8fab703/stream.ts.                                                                                                                          [10:25:02] [ERR] [4] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1           

**Screenshots**

![image](https://user-images.githubusercontent.com/10842079/111016074-d4bffa00-83e6-11eb-8613-905dfe544c80.png)

**Additional context**

**Comment by crobibero** [comment] 2021-03-13 02:39
Duplicate of:
https://github.com/jellyfin/jellyfin/issues/5491
#5427 
#5438

Fixed by: https://github.com/jellyfin/jellyfin/pull/5444

**Closed by crobibero** 2021-03-13 02:39 UTC
Labels: bug
