### ISSUE TITLE
Restart btn on dashboard is missing 

### ISSUE THREAD

**Issue by grafixeyehero** [jellyfin/jellyfin#893] opened 2019-01-05 21:24 UTC
Restart btn on dashboard is missing only show sutdown btn 
platform windows 

![restart](https://user-images.githubusercontent.com/32230989/50729358-61a50400-1149-11e9-87ab-58d6dad193f6.jpg)

**Comment by JustAMan** [comment] 2019-02-14 08:48
Transferred back to server, as we apparently need server support for that button to become available.

**Comment by bengalih** [comment] 2019-09-09 01:57
Going to add to this rather than start a new bug.
In addition to no restart button, the shutdown option also doesn't work when running as a service (via nssm).
While I don't know the innards of JF from Adam, I can say that there are other services I use which run via NSSM and support shutdown and restart.  CouchPotato is one of these.
Pretty sure that's in Python, which may be apples and oranges here.
I don't know what is planned for the future, but it would appear there could be someway to add a reinitialization/shutdown procedure into the executable.

**Comment by leonelsr** [comment] 2020-01-02 22:28
I'd like to add that **Emby** on Windows still does have the restart feature from the web interface. How far are we from their codebase?

There are other bugs that existed before and have been already fixed on Emby, but are still present on Jellyfin. Such as the DLNA server not being detected when port 1900 is already in use (#1322 I guess)

**Comment by anthonylavado** [comment] 2020-01-05 13:22
@leonelsr Emby hasn’t had a public commit since September 2018, and we also had to revert specific sections back as far as May 2018. There’s nothing further we can import from their code for the server, we are completely on our own here.

That said, I’ll see what I can do for a future release.

**Comment by dkanada** [comment] 2020-01-22 05:01
This isn't an interface issue, the windows build just needs an argument with the location of a script that will restart the server. This can apparently be done within the code on newer DotNet versions as well.

**Comment by bengalih** [comment] 2020-05-21 14:11
Is there any movement on this?  From the comments it sounds like this was not seen as an issue due to some script that can be used?   I'm unsure why this doesn't seem like a requirement, out of  (at least) 8 media centered web-based services I run on my system, JF is the only one that doesn't provide an inbuilt update function (or even a notification of an update) or a shutdown/restart option.  I'm mentioning this here (although I should probably file another bug/request) that the omission of an auto-update feature is definitely contributing to extra work for both the dev team and user community since people continue to work with older versions and can't stay in sync over how functions are implemented and supported.

**Comment by dkanada** [comment] 2020-05-22 02:29
Out of curiosity, what are the eight services that include a restart button?

**Comment by bengalih** [comment] 2020-05-22 02:36
Sonarr, Radarr, Jackett, CouchPotato, Sabnzbd, Tautulli, Organizr, Headphones

**Comment by joshuaboniface** [comment] 2020-11-22 22:23
To sort of explain this one.

The `Restart` button is only shown/enabled if the `--restartpath` argument is passed to the binary. On Windows this isn't done in our packaging, which is why the button isn't there. This is indeed a holdover from how Emby did it (with the hacky restart script).

We could try writing a Windows script to restart the service, which will allow this to work, but this is an external setup. We should definitely look at how the other C#-based Arr tools do this however.

**Comment by cvium** [comment] 2021-04-09 10:16
Working as intended even if it's kind of bad...

**Closed by cvium** 2021-04-09 10:16 UTC
Labels: confirmed, dotnet future
