### ISSUE TITLE
Clean Transcode Directory schedule doesn't run

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin#4064] opened 2020-09-05 19:29 UTC
**Describe the bug**
As stated in the title, the task did not run as scheduled, default every 24 hours. As a result, many files older than one day are filling up the transcode path. I need to manually run them from the dashboard which I clearly remembered it was running fine automatically prior 10.6.x. I've tried deleting the schedule then add it again still it doesn't run automatically every 24 hours. I've even tried scheduling it the minimum 15 minutes. The rest of the scheduled tasks seems to be running ok except for this. I've temporarily scheduled a shell cronjob to handle the growing transcoded files.

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: chroot
 - Jellyfin Version: 10.6.4 running as root
 - Networking: host
 - Storage: local ext4

**To Reproduce**
Check the last default scheduled ran time and the actual transcoded file modified time, both exceeded several days.

**Expected behavior**
The schedule should run every 24 hours leaving only transcoded files less than one day. There should be notification on failed attemps clearing the transcode path which in this case there's none as the task doesn't run.

**Comment by crobibero** [comment] 2020-09-05 19:31
Duplicate of https://github.com/jellyfin/jellyfin/issues/2075

**Closed by crobibero** 2020-09-05 19:31 UTC
Labels: bug
