### ISSUE TITLE
Ability to auto delete watched content

### ISSUE THREAD

**Issue by Pantar2205** [jellyfin/jellyfin#1407] opened 2019-05-25 18:06 UTC
Ability to delete watched content based on certain criteria. The Kodi Addon Janitor as an example. 
See, 
https://github.com/Anthirian/script.service.janitor

**Comment by SenorSmartyPants** [comment] 2019-05-25 19:45
Duplicate of #296

**Closed** 2019-05-25 20:12 UTC
Labels: feature
