### ISSUE TITLE
[Issue]: Cannot play media if the "©day" field is incorrect

### ISSUE THREAD

**Issue by adyanth** [jellyfin/jellyfin#11576] opened 2024-05-12 19:03 UTC
### Please describe your bug

I had a song that has the M4A/AAC metadata for "©day" set to 20180101 instead of how jellyfin expected it (2018?). This caused the song to not be played because it crashed.

It should be able to play the file regardless of being able to parse the metadata correctly. Additionally, pick up additional date formats stored in "©day".

https://github.com/jellyfin/jellyfin/blob/ce3e287892b849f0ef75534bba29bec94c95397c/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs#L272-L281

### Reproduction Steps

1. Set the m4a tag "©day" to something with >4 digits (e.g. 20240512)
2. Let jellyfin scan it
3. Try to play
4. Fails

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.0-101-generic
- Virtualization: Proxmox
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 5.1.4-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: NVENC
- GPU Model: NVIDIA T400
- Plugins: /
- Reverse Proxy: Traefik
- Base URL: none
- Networking: host
- Storage: NFS
```

### Jellyfin logs

```shell
[2024-05-12 14:33:03.019 +00:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/Music/.../....m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-12 14:33:03.143 +00:00] [ERR] Error in "Probe Provider"
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nfmccrina** [comment] 2024-05-14 05:12
@adyanth I opened a PR which would allow the file to play despite the unexpected data. I wasn't sure about the second part of your suggestion, handling this new possible date format. It seems to me that trying to handle _anything_ instead of just YYYY is potentially very messy. It would be easy to add a workaround for your case, "20180101", but what if there is a file that has "201811" or some other such value? I'm fairly new here so I figured I'd wait and see if someone else had more feedback on potential ways to handle that.

**Comment by crobibero** [comment] 2024-05-15 03:29
Closing as this will be fixed in 10.9.2.

**Closed by crobibero** 2024-05-15 03:29 UTC
Labels: bug

**Comment by sel10ut** [comment] 2024-05-25 15:00
digging more into it, i think you can view this as a bug from `TagLib`. It is [stated](https://github.com/mono/taglib-sharp/blob/c853d26fcf831b9c7bf1b1bc7734c2a8690ca163/src/TaglibSharp/Tag.cs#L540-L548), that the higher precision dates will be truncated to 4 digits, however, looking at the [code section](https://github.com/mono/taglib-sharp/blob/c853d26fcf831b9c7bf1b1bc7734c2a8690ca163/src/TaglibSharp/Mpeg4/AppleTag.cs#L951-L963) from mpeg4 parser:
```
public override uint Year {
	get {
		foreach (AppleDataBox box in DataBoxes (BoxType.Day))
			if (box.Text != null && (uint.TryParse (
				box.Text, out var value) ||
				uint.TryParse (
					box.Text.Length > 4 ?
					box.Text.Substring (0, 4)
					: box.Text, out value)))
				return value;

		return 0;
	}
```
it will not reach the third condition, if you have formats like YYYYMMDD (is it non-standard though?), and it will for YYYY-MM-DD. The second condition looks unnecessary. When looking at the [XiphComment parser](https://github.com/mono/taglib-sharp/blob/c853d26fcf831b9c7bf1b1bc7734c2a8690ca163/src/TaglibSharp/Ogg/XiphComment.cs#L921-L929):
```
public override uint Year {
	get {
		string text = GetFirstField ("DATE");
		return (text != null && uint.TryParse (
			text.Length > 4 ? text.Substring (0, 4)
			: text, out var value)) ? value : 0;
	}
	set { SetField ("DATE", value); }
}
```
It only has 2 conditions and works properly. So, removing the second condition should suffice? Something like this:

```
foreach (AppleDataBox box in DataBoxes (BoxType.Day))
	if (box.Text != null && uint.TryParse (
		box.Text.Length > 4 ? box.Text.Substring (0, 4)
		: box.Text, out var value))
		return value;
```

But it seems like `TagLib` has been unmaintained for a long time. Should jellyfin perhaps consider a fork?

> Additionally, pick up additional date formats stored in "©day".

@adyanth higher precision dates are already parsed by `ffprobe`. Currently `PremierDate` is set to whatever `ffprobe` could parse. But `ffprobe` could also fail or fallback to a different date, that is not necessarily a release/recorded date. Which is not ideal. Sticking to the standard format should be working fine I believe. (But to me it is quite unclear, which value format ©day follows)

`TagLib` supports getting tags though custom fields per specific format, which we could possibly use to parse standardized fields, that store higher precision dates, but we will need to redo verifying/parsing logic, again - not ideal.

**Comment by lomenzel** [comment] 2025-02-27 16:17
is this the same error?

happend in 10.10.6

```
[2025-02-27 17:06:32.055 +01:00] [INF] [61] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/nix/store/66vy2rjrzxxxh02yhi8q73rpb5p1643d-jellyfin-ffmpeg-7.0.2-5-bin/bin/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/var/lib/nextcloud/data/jellyfin/files/Jellyfin Media/Musik/t.A.T.u./200 kmh wrong lane/1 - Not Gonna Get Us.m4a\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2025-02-27 17:06:32.179 +01:00] [ERR] [40] MediaBrowser.Providers.Music.AudioMetadataService: Error in "Probe Provider"
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at ATL.Track.set_Year(Nullable`1 value) in /_/ATL/Entities/Track.cs:line 235
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchDataFromTags(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, Boolean tryExtractEmbeddedLyrics) in /build/source/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:line 167
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.FetchAsync(Audio audio, MediaInfo mediaInfo, MetadataRefreshOptions options, CancellationToken cancellationToken) in /build/source/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:line 143
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /build/source/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:line 110
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /build/source/MediaBrowser.Providers/Manager/MetadataService.cs:line 801
```

**Comment by SchweGELBin** [comment] 2025-02-28 17:48
@lomenzel I'm having the same issue as you. So I downgraded to 10.10.5, scanned and upgraded back to 10.10.6.

**Comment by felix920506** [comment] 2025-02-28 17:57
Looks like some regression was introduced in 10.10.6? Please open a new issue.
