### ISSUE TITLE
Music artists separator showing incorrectly when adding a new album

### ISSUE THREAD

**Issue by Sandro905** [jellyfin/jellyfin#12684] opened 2024-09-22 18:33 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Currently having this issue, I'm unsure if it happened before the latest version since I didn't come around to fix the artists in my library.

When importing a new Album, making sure the artists are separated by ";" in the metadata, said metadata is imported in Jellyfin, without separating the artists, specifically, it's displayed "raw" instead of separating correctly. 

![image](https://github.com/user-attachments/assets/6c4c9299-8ce7-4797-93ca-43ba2c4a8fe8)

The "artist" is also created.
![image](https://github.com/user-attachments/assets/628c5906-38e7-4a2e-8c3f-a9f57dd892c6)

By going to the Track -> Edit -> Edit Metadata, then just clicking "Save" without doing anything seems to solve the issue, problem is, it's a bit tedious to do it for hundres of songs.

Apologies for the following screenshots being in italian, please let me know if something is not clear.

![image](https://github.com/user-attachments/assets/8492a755-7645-4ca5-88ec-78e91736e290)
![image](https://github.com/user-attachments/assets/efca783f-23ba-4fc3-b198-3bfc4384cc73)
![image](https://github.com/user-attachments/assets/41621291-df6d-436f-aca6-61ad9314a5a0)

### Reproduction steps

When importing multiple albums to try things out, I noticed that this doesn't seem to happen 100% of the times, but it shouldn't be hard to reproduce since it's for sure most of the times. Please if you can't reproduce try a different album.

1. Sign in to Jellyfin 10.9.11 with an admin account
2. Create a new music library with default settings, choose a folder
3. Import in the folder specified in point 2 a new album with a song that has at least two artists in the metadata, separated with a semicolon
4. Refresh the library metadata
5. The album should now show up inside, and the song should display the artists with the wrong format

### What is the current _bug_ behavior?

The artists are not split with the separator upon importing a new song

### What is the expected _correct_ behavior?

The artists should be split up at the separator when importing a new song

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.8.12
- Virtualization: LXC
- Clients: -
- Browser: -
- FFmpeg Version: 6.0.1p8-1
- Hardware Acceleration: NVENC
- GPU Model: GTX1080
- Plugins: AudioDb, MusicBrainz (In both cases the checkbox "When an artist is found during a metadata search, replace the artist name with the value on the server." is unchecked
- Reverse Proxy: nginx
- Base URL: /jellyfin
- Networking:Bridge/NAT
- Storage:SAMBA
```

### Jellyfin logs

```shell
[2024-09-22 18:23:55.911 +00:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/jellyfin/hdd/Jellyfin/MusicSandro/Beg For Mercy/06 - G-Unit - Wanna Get To Know You.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
```

**Comment by gnattu** [comment] 2024-09-22 18:36
10.9 does not support such non-standard way of splitting tags. see #12385 for the support of 10.10

Please note, if you want to test this feature using current unstable you need to manually edit the xml config file as the GUI part configuring this is not merged yet: https://github.com/jellyfin/jellyfin-web/pull/5869

**Closed by gnattu** 2024-09-22 18:36 UTC
Labels: bug

**Comment by Sandro905** [comment] 2024-09-22 19:18
Thank you for your answer @gnattu ,I was under the impression in 10.9 the supported separator for artists in particuylar was the semicolon, although I couldn't find anything in the official wiki, in the "edit metadata" page it says "Separate multiple artists using the symbol (;).", while not standard, it seems to me what Jellyfin requires, am I wrong? 

Also the fact that that it woks one way when importing and then by opening and saving it it fixes the problem makes it seem to me that there's something not working properly during the import process.

**Comment by gnattu** [comment] 2024-09-22 19:27
>  in the "edit metadata" page it says "Separate multiple artists using the symbol (;)."

The GUI edit has nothing to do with how the tag is parsed

> Also the fact that that it woks one way when importing and then by opening and saving it it fixes the problem makes it seem to me that there's something not working properly during the import process.

Again, it is *by design* that not supporting such separator. See https://github.com/jellyfin/jellyfin/issues/11871#issuecomment-2224997314 for more info
