### ISSUE TITLE
If filename extension is in capital letters (like .JPG) those files aren't recognized

### ISSUE THREAD

**Issue by Uatschitchun** [jellyfin/jellyfin#1787] opened 2019-09-23 10:11 UTC
**Describe the bug**
I've added my own pictures to library as "Homevideos & Pictures". Some of the files have file extension in capital letters, like christmas.JPG. Those files aren't recognized and don't show up in library

**To Reproduce**
Add files with captitalized file extension, like picture.JPG
Those files do not show up

**Expected behavior**
file extensions should be recognized no matter of being capitalized

**System (please complete the following information):**
 - OS: Docker
 - Browser: Opera
 - Jellyfin Version: 10.3.7

**Additional context**
Checked for movies and it seems it doesn't matter if it's movie.avi or movie.AVI

**Comment by anthonylavado** [comment] 2019-09-23 21:59
This is fixed in the next release, 10.4.

**Comment by anthonylavado** [comment] 2019-09-23 22:01
Duplicate of #1365.

**Closed by anthonylavado** 2019-09-23 22:01 UTC
Labels: duplicate
