### ISSUE TITLE
Dropped Frames for one Movie, ok playback for another movies with exact same media information.

### ISSUE THREAD

**Issue by buzzzz2138** [jellyfin/jellyfin#8992] opened 2022-12-31 18:02 UTC
The following media info is for the movie that dropped about 50% of the frames.  Works perfectly fine in firefox.   The same issue occurs on the latest version of Roku.  Works on android if the quality is dropped to 480p -3 Mpbs, anything higher causes dropped frames.  Works if VLC is used instead.  There isn't a similar solution for Roku. 

Also only occurs with mp4 file format.  Haven't found the issue with a mkv. 

**Media Info of the file**

Video
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hev1
Profile: Main 10
Level: 120
Resolution: 1920x804
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 23.976215
Bitrate: 2000 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

**Logs**
[2022-12-31 11:03:04.967 -06:00] [INF] [94] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-12-31 11:03:04.967 -06:00] [INF] [94] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/New/Bloodshot.2020/Bloodshot.2020.1080p.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/756f2a69-e3dc-9b4d-6a8b-0444b4468d51/stream.mp4?MediaSourceId=756f2a69e3dc9b4d6a8b0444b4468d51&Static=true&VideoCodec=hevc&AudioCodec=aac&AudioStreamIndex=2&api_key=<token>&Tag=fcdd90489927f22838a72968789dc09e"
[2022-12-31 11:03:06.342 -06:00] [INF] [92] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : b703934a382214b0-0af64c6021f142769d4b7d5abb499fbb-756f2a69e3dc9b4d6a8b0444b4468d51
[2022-12-31 11:03:06.342 -06:00] [INF] [92] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 12/31/2022 11:03:06
[2022-12-31 11:03:06.342 -06:00] [INF] [92] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2022-12-31 11:03:06.342 -06:00] [INF] [94] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2022-12-31 11:03:06.370 -06:00] [INF] [92] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "b703934a382214b0-0af64c6021f142769d4b7d5abb499fbb-756f2a69e3dc9b4d6a8b0444b4468d51"
[2022-12-31 11:03:18.794 -06:00] [INF] [76] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.4.4" playing "Bloodshot". Stopped at "12131" ms
[2022-12-31 11:03:18.810 -06:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "b703934a382214b0-0af64c6021f142769d4b7d5abb499fbb-756f2a69e3dc9b4d6a8b0444b4468d51"
[2022-12-31 11:03:18.810 -06:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 12/31/2022 11:03:18
[2022-12-31 11:03:18.810 -06:00] [INF] [112] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[2022-12-31 11:03:20.455 -06:00] [INF] [94] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "392f9ecc-8d9c-56e3-9570-34ec46dcb464-cff16b56ab35468689376db20e47a801-bb800b76b2c88e1b21df46b7fce6b381"
[2022-12-31 11:03:26.344 -06:00] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "Phone IP Address"

**FFmpeg Logs**
None

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS; Open Media Vault: Docker
 - Jellyfin Version: 10.8.8
 - Hardware settings & device: None
 - Reverse Proxy: nginx is set up, but in this instance it is bypassed and locally accessed. 
 - HDD located within computer. 
 
**Client System (please complete the following information):**
 - Device: LG-V35 Android Phone
 - OS: Android
 - Client: Android Web Player

**Comment by IvanBernatovic** [comment] 2023-01-03 15:18
I'm experiencing the same issue but I can tell you for sure this is not a Jellyin issue, it is a Chrome/Chromium issue with specific HEVC videos (not sure what encoding parameters cause this yet). I know this for a fact because you can reproduce the problem by simply dragging and dropping problematic files to Chrome directly (without using Jellyfin) which will open Chrome's video player (HTML player) and you will get exactly the same issue. I have a lot of HEVC MP4 files that work properly, but only a few have this issue.

When you play the video directly in Chrome you can open the Media tab in DevTools and check the Messages section. Here's what I'm getting:
![image](https://user-images.githubusercontent.com/11651980/210385000-41d124d1-6065-46e2-ae1b-03f03e9600fa.png)

All in all, this is a bug with Chrome's HEVC playback. The only workaround is using transcoding but the problem is in Jellyfin there's no option to transcode HEVC -> H264 with the same or higher bitrate than the original file. Right now transcoding only kicks in if the video format is not supported or you select a lower bitrate than the original file which drastically decreases quality.

**Comment by IvanBernatovic** [comment] 2023-01-05 11:57
@buzzzz2138 Based on further tests this happens in ExoPlayer as well (used by Plex on Android and an option in Jellyfin for Android). Problematic videos also don't work properly in some other players on Android such as mpv. My conclusion is that in this particular case it has something to do with how videos are encoded. Some HEVC settings don't play nice with some players. Looks like the issue mostly happens with some RARBG HEVC rips from mid-2020.

**Comment by buzzzz2138** [comment] 2023-01-19 01:41
ffmpeg -i <Input File.mp4> -codec copy <Output File.mkv> 

This command seems to fix the problem.  About 40% of my library is effected by this issue.  

But in the end this might just be covering over the error since the files are no longer being directly played but transcoded because the players can't play the mkv container. 

Another route to test out is nohup ffmpeg -y -i 'Input.mp4' -c:v libx265 -b:v 2000k -x265-params pass=1 -an -f null /dev/null &; nohup ffmpeg -i 'Input.mp4' -c:v libx265 -b:v 2000k -x265-params pass=2 -c:a copy 'Output'.mp4 &

This route re-encodes the file.  This has been test with an output of mkv.

**Comment by IvanBernatovic** [comment] 2023-01-19 14:52
@buzzzz2138 
My affected files are 1080p HEVC SDR files in MP4 containers. My fix that worked for all was:
1. Remux the files with MKVToolNix to .mkv and fixes the playback issue
2. Use ffmpeg to remux them back to .mp4 so you can play them directly in browsers (given your codec can work in MP4)
No re-encoding is needed for this. If your affected files are already using MKV then I think you just have to do the first step and that's gonna fix them.
Don't forget to use the latest MKVToolNix.

> But in the end this might just be covering over the error since the files are no longer being directly played but transcoded because the players can't play the mkv container.


Also, on Android, you have an option in "Client settings" to use an integrated player (ExoPlayer) instead of web-based player which can't play MKV files directly.

**Comment by buzzzz2138** [comment] 2023-01-22 15:11
Remux from mkv to mp4 first does not fix the issue.  The mkv doesn't play. 

What I am currently doing, which takes about 4 to 5 times the length of the video (it's an old cpu), is the following:
nohup ffmpeg -y -i   '<Original>.mp4' -c:v libx265 -b:v 2000k -x265-params pass=1 -an -f   null /dev/null &&  nohup ffmpeg   -i '<Original>.mp4' -c:v libx265 -b:v 2000k -x265-params pass=2 -c:a   copy '<Original>_2.mkv' && nohup ffmpeg -i   <Original>_2.mkv -codec copy <Original>_2.mp4

Once that's done I move the _2.mp4 over the old one and it typically works.  Replacing <Original> with the correct filename with out the suffice. 

Ends up with a file size about the same as previous with a quality about the same.

**Comment by IvanBernatovic** [comment] 2023-01-23 10:04
> Remux from mkv to mp4 first does not fix the issue. The mkv doesn't play.
> 

I feel we're not on the same page here and there's some misunderstanding so I'll try to be clear now.
The reason your files are broken is that the RARBG team used a buggy MKVToolNix version for some of their rips (and Bloodshot is one of those broken rips). In order to fix them, you need to download the latest MKVToolNix version and remux them again. This is a very fast process and it takes several seconds.

**If you have a broken MP4 file:**
1. Use MKVToolNix and remux from MP4 -> MKV. This fixes the file but now you have it in the MKV container which is maybe not what you wanted so you need to follow the next step to remux to MP4 again
2. Run `ffmpeg -i inputfile.mkv -c copy -map 0 outputfile.mp4` to remux from MKV to MP4 again

**if you have a broken MKV file:**
1. Simply use MKVToolNix and remux the file again from MKV -> MKV. This should also fix the file and is done quickly.

I repeat, there is no re-encoding here and it only takes a few seconds to remux files (mostly depends on your disk speed actually). I'm 100% sure this will work for you and if it doesn't you're doing something wrong.

**Comment by buzzzz2138** [comment] 2023-01-23 17:08
Thank you @IvanBernatovic

**Comment by IvanBernatovic** [comment] 2023-01-24 09:12
@buzzzz2138 Np! Since this is not a Jellyfin issue and we found a fix for us, let's close this issue to reduce some noise in this repo. I think you should be able to close it as you are the OP.

**Closed** 2023-01-24 19:32 UTC

**Comment by Hukuma1** [comment] 2023-02-11 19:51
Thank goodness someone figured this out. It was driving me crazy since Chrome enabled native HEVC playback. Thank you, @IvanBernatovic!

Any chance someone made a batch script for this? I have no idea which movies this affects, and figured I could just run them all through this?
