### ISSUE TITLE
Deleted playlists don't stay deleted

### ISSUE THREAD

**Issue by drazil100** [jellyfin/jellyfin#1963] opened 2019-10-31 21:50 UTC
**Describe the bug**
Deleted playlists don't actually stay deleted. Instead they will be deleted for a while (even across reloads of the page) and then come back later on its own or when you scan all libraries. 

**To Reproduce**
1. Create a playlist
2. Delete the playlist
3. Scan all libraries.

**Comment by mcarlton00** [comment] 2019-12-09 20:11
Still occurring.  The cause is that the playlists are currently stored in xml files.  When a playlist is deleted, it's removed from the system, but the xml file isn't deleted.

On docker, the xml files are in `config/data/playlists`

**Comment by JustAMan** [comment] 2020-01-13 11:38
Probably a bit related to https://github.com/jellyfin/jellyfin/issues/2130

**Comment by dkanada** [comment] 2020-01-13 13:35
I fixed this on master a few weeks ago, it will be fixed in the next release.

**Closed by dkanada** 2020-01-13 13:35 UTC
Labels: fixed
