### ISSUE TITLE
3 Digit Numbers Parsed as Season ? Episode ??

### ISSUE THREAD

**Issue by chdgriff** [jellyfin/jellyfin#4429] opened 2020-11-07 03:14 UTC
**Describe the bug**
I have 700 One Piece episodes organized into season folders but each is named "One Piece - ?? [1080p].mkv" where ?? is the overall episode number rather than the season's episode number. Even though the episodes are already correctly placed into folders by season, Jellyfin still parses 3 digit episode number like 679 as season 6 episode 79 and moves the episodes around. 

**System**
 - OS:  Windows
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.6.4
 - Playback: N/A
 - Installed Plugins: Anime
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Import 100+ episodes of content named by overall episode number

**Expected behavior**
I'd expect Jellyfin to respect the episode file path locations and enumerate each episode in each season folder. An alternative and probably easier fix could be to add functionality to batch shift episodes by an integer in addition to overwriting by a value.

**Logs**

**Screenshots**

**Additional context**

**Comment by rderensy** [comment] 2020-11-17 09:56
Your filenames [should be](https://jellyfin.org/docs/general/server/media/shows.html) "S01E679" for three digits episodes numbers ("One Piece - S01E679" should also work).

Also, the episode 679 isn't the 679th episodes of season 17, it might be better to name it "S17E51".

**Comment by Mitarex-git** [comment] 2020-11-28 12:51
Can confirm with another series. For example, episode 119 is recognised as S01E19, loading completely wrong metadata, even though it is located in a "**Season 10**" subfolder.
Of course it is possible to rename all 400 episodes, but it would be nicer if Jellyfin respected the folder structure or just stopped assuming lone three digits to be a season and episode numbers glued together, I have honestly never seen people name episodes like that.

**Comment by cvium** [comment] 2021-04-20 09:41
Duplicate of https://github.com/jellyfin/jellyfin/issues/1180

**Closed by cvium** 2021-04-20 09:41 UTC
Labels: bug
