### ISSUE TITLE
[Issue]: Subtitles out of sync

### ISSUE THREAD

**Issue by realitymolder** [jellyfin/jellyfin#8403] opened 2022-09-14 09:38 UTC
### While streaming a movie or a show in one of my devices at the same network, the subtitles are out of sync sometimes. 

Steps to reproduce:
1. Stream a show/movie
2. Load subtitles (from Jellyfin / external)
3. Scrub in the media file timeline (left right in the scrubber)
4. Subtitles will get out of sync

Sometimes it can reproduce also by:
1. Stream a show/movie
2. Load subtitles (from Jellyfin / external)
3. Watch for a while
4. Accidentally get out of the app for the main menu of the stream (home button)
5. Go back to Jellyfin and stream again
6. Subtitles will get out of sync

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Ubuntu Server 22.04
- Virtualization: Docker
- Clients: Google Chromecast With Google TV
- FFmpeg Version: 4.4.2-0ubuntu0.22.04.1
- Playback Method: Not Sure
- Hardware Acceleration: NVENC
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArchGryphon9362** [comment] 2022-12-30 11:54
Has this been fixed? Experiencing it on 10.8.4 (will update soon)

**Comment by hkup859** [comment] 2023-01-06 02:54
@realitymolder This may be a dumb question, but Can you confirm that on the same episode or movie, with the same subtitles, and in the same spot/time that the subtitles do not have an error if you just watch all the way through? Basically I'm wanting to ensure this is not bad subtitles that start correct and are incorrect later in the video.

**Comment by realitymolder** [comment] 2023-01-14 18:28
> Has this been fixed? Experiencing it on 10.8.4 (will update soon)

TBH, I'm not sure, my server is down for maintenance at the moment. 

> @realitymolder This may be a dumb question, but can you confirm that on the same episode or movie, with the same subtitles, and in the same spot/time that the subtitles do not have an error if you just watch all the way through? Basically I'm wanting to ensure this is not bad subtitles that start correct and are incorrect later in the video.

Yes of course. This is why I've opened this issue 😋 


On another note: not sure why my report got downvoted, though. Should I not report on bugs next time? 🤔

**Comment by hkup859** [comment] 2023-01-14 19:30
@realitymolder Figured I'd check! Not sure why your issue would be downvoted. I think it was descriptive and clearly something people do experience. Keep on tracking bugs/issues! It's the only way we can improve Jellyfin. I'm working on some other areas of Jellyfin at the moment, but when I finish if this is still an issue I can try and circle back. Not a lot of time though at the moment, so I can't promise anything.

**Comment by KingYonatan** [comment] 2023-02-25 19:50
I wanted to add that I am also experiencing this issue! A fix would be very appreciated

**Comment by MasterMach50** [comment] 2023-03-05 05:32
I am experiencing the same issue.

A dumb fix: 
- Whenever the subs gets out of sync turn it off an on again from the player controls, this will reload the subs at the correct time

**Comment by RubenTeixeira** [comment] 2023-03-09 10:32
I have the same or similar issue. Subtitles out of sync (too early) when using Exoplayer on Android. If I switch to LibVLC it goes away.
Tested on an Android 10 Sony TV and on a Chromecast with Google TV Android 12.
Please, let me know if this is most likely related with the AndroidTV app and I'll open another issue there.

**Comment by cbeamond** [comment] 2023-03-09 14:17
I'm also having the same issue on every file I watch through jellyfin. It works fine using another media player. This makes jellyfin unusable for my wife who tends to depend on subtitles.

I don't think the problem is any kind of encoding issue since turning on and off subtitles fixes it. To me this seems to be a client sided issue with the html version as this occurs both on html and android, which is just a html wrapper anyway. It would be good to know if the native apps have the same issue or not (I think that some ports don't use the HTML version??)

If you skip through the file while a subtitle is open it can also cause the old subtitle to get stuck, so you see it forever. This might be the same or different issue/fix.

@hkup859 Would you happen to know what area of the source code I should look at? Being a good C# developer with some html thrown in I'm hoping that I can figure out what's going on or at least get an idea to solving it.

**Comment by cbeamond** [comment] 2023-03-09 14:25
I'm not certain if it's the same bug or issue, but it appears that https://github.com/jellyfin/jellyfin-web/issues/4346 might be the same issue.

**Comment by hkup859** [comment] 2023-03-09 14:53
> I'm also having the same issue on every file I watch through jellyfin. It works fine using another media player. This makes jellyfin unusable for my wife who tends to depend on subtitles.
> 
> I don't think the problem is any kind of encoding issue since turning on and off subtitles fixes it. To me this seems to be a client sided issue with the html version as this occurs both on html and android, which is just a html wrapper anyway. It would be good to know if the native apps have the same issue or not (I think that some ports don't use the HTML version??)
> 
> If you skip through the file while a subtitle is open it can also cause the old subtitle to get stuck, so you see it forever. This might be the same or different issue/fix.
> 
> @hkup859 Would you happen to know what area of the source code I should look at? Being a good C# developer with some html thrown in I'm hoping that I can figure out what's going on or at least get an idea to solving it.
> 
> Edit: The fix will probably need to be made in [jellyfin-web](https://github.com/jellyfin/jellyfin-web) ??

@cbeamond Unfortunately I never got around to looking into this issue. I'm primarily familiar with Javascript and its counterparts and have been working on other projects. From what I can gather about this issue it is unclear whether this is a client-side or server-side issue, but my guess would be client side. It may still exist in multiple clients though and need fixed in each. 

I had a similar issue in the android tv Plex app a year or 2 ago and it seemed to get resolved at some point. Since Jellyfin, Plex, and Emby are all somewhat similar, this could mean it was related to a player or package issue. It's also possible they are completely unrelated. 

My recommendation would be to try and replicate the issue in your preferred client (mine would be the web version) and then trace the subtitle logic down to see if it is an issue of what's being sent or when and how we are displaying it.

I hope this helps! Sorry I haven't looked into this issue more.

**Comment by cbeamond** [comment] 2023-03-09 15:09
It's no problem that you haven't looked into it more, so don't worry! :)

I was just wondering if you knew where a good place to start would be in the repo. Since that question I've realized that there is a web client in a different repo so that's probably the place to start. My JS is pretty rusty unfortunately, but maybe the fix won't be too difficult

**Comment by hkup859** [comment] 2023-03-09 15:14
@cbeamond Let me know what you find, perhaps I can jump in and help if I get time. I'm more comfortable in the web client, so while I'm not necessarily familiar with the code base I can at least navigate around easier.

**Comment by cbeamond** [comment] 2023-03-09 16:31
I've looked around a little. I've not done any kind of modern JS in this kind of framework for a while, so I'm extremely outdated on what I need for building and tooling. However, I've currently got this information.

In the `htmlVideoPlayer` plugin there is the `updateSubtitleText` function that apparently gets called every time update. As such the subtitles should stay in sync no matter where the video is and seeking doesn't actually change anything. The actual function appears to be error free. Therefore the only ways that I can see that the subtitles are bugged is:
* if the clock inside `updateSubtitleText` is in use and has some kind of bug. I'll still have to dig to find out more about the clock as it appears to be set externally. If/when I make my own frontend builds the first thing I would do is to comment out the clock in that function or wrap it inside an `if (false) {}` block to see if the clock is at fault.
* The server is sending incorrect time ticks for the subtitles. This case can only be possible if the server sends updated ticks when the player turns the subtitles off and back on again. While I find this a little odd, maybe this is what actually happens to save on bandwidth?
* The client is taking the data from the server and processing it but making an error. This follows the same idea as the previous point
* Somehow the time given to the function is incorrect. This is incredibly unlikely, unless `currentPlayOptions.transcodingOffsetTicks` slowly increments itself over time but this isn't displayed in the UI. I don't think this is the case.

**Comment by cbeamond** [comment] 2023-03-09 16:40
Okay, i had a closer look at what actually happens in the player. Basically if you seek it will play the subtitles from the original position. So for example if I am 10 minutes in and the subtitles are in sync, and then I skip to 20 minutes in, the subtitles play as though the current time is still at 10 minutes.

Given that the subtitle update function is ran per frame (or something like that) seeking doesn't actually impact it. So the problem is either the clock, or the subtitle data being parsed is incorrect.

If the fault lies in the client, it would have to take all of the time data for the subtitles and offset it by the current time. If the fault lies in the server, maybe it's encoding the subtitles but failing to offset them to the new time that the player has selected??

In either case it seems that the error is either the clock, which is based on libjass (which might support your theory about it being related to plex), or the server or client is processing the subtitle timeing using the previous time offset rather than the new one.

**Comment by khangp0000** [comment] 2023-03-11 14:10
The fault is the server and impossible to fix unless there are a new protocol for non-deterministic segmentation. Let me phrase it in a way that is easy to understand:

1. When a file is play, the file is split into chunk of like 5 second video via HLS protocol, for simplicity, let's call these files `1.ts`, `2.ts`, e.t.c. To play the video, the player download a `*.m2u8` file, however, this file is only available after `ffmpeg` finished compilation. The file format is something like:
```
#EXTINF:5
1.ts
#EXTINF:5
2.ts
#EXTINF:5
3.ts
...
```
where `EXTINF` means how many second a frame is.
2. Since this file is only available after transcoding finish, jellyfin try to predict this file and send it early to the client. However, ffmpeg split the file by keyframe, and not by second, you can force the keyframe (which ffmpeg does) but it is not 100% accurate, especially the first `1.ts` file when there is audio (https://trac.ffmpeg.org/ticket/6238, really old ticket, never really addressed) so the actual output m3u8 file can be:
```
#EXTINF:6.4
1.ts
#EXTINF:5.2
2.ts
#EXTINF:5.2
3.ts
...
```
3. When you seek in exo player, it seek using the time table provided by m3u8 file. You can see how this will be an issue, the seeked location would be incorrect. If you seek a big different, jellyfin may start a new reencode, so the timestamp and the file may match (this is why sometimes when you exit and watch again it will have correct subtitles), but it can still have some minor delay because of the 1st segment timestamp issue I mentioned earlier. Theoretically, the player can ffprobe to check the file actual timestamp of the file, but it is probably too convoluted and complicated to implement. https://github.com/google/ExoPlayer/issues/8296

So essentially, with above issue, the video is seeked to an incorrect location timestamp, while the subtitle is still running on the correct timestamp, hence the displacement of subtitles. You can check this fairly simple, just open the original file and the transcoded stream, go to same timestamp, you will see same subtitle but different audio.

On untranscoded direct file, this would be not an issue because the keyframe data is already there in the file so jellyfin use it to generate the `m2u8` file.

For me personally, I just decided to hardsub everything when transcoding, using the beta android ffmpeg client. Please note that I am not a developer, just want to share my finding and why this cannot be solve any time soon. Unless someone brave enough to make a native player instead of using exo (**doubt**), or somehow inject something on the seek function so that it does not use the `m2u8` as the source of truth for seeking.  

Using external player fix this issue because external player does not support transcoding and it is direct file playing.

**Comment by khangp0000** [comment] 2023-03-11 14:23
As a side note, using hardsub will still cause incorrect seek (sometime seek back give some future video), but at least the subtitle is correct.

**Comment by cbeamond** [comment] 2023-03-11 16:04
I've gone through your comments twice. I'm a little too tired right now to get a complete an understanding and to fully figure out what you mean, but from what I understand essentially the subtitles and video data can't be kept in time sync because we can't ensure that the video (or audio?) time is always correct. As a side note I wonder if this also affects sync play?

To me though this seems inconsistent with the observed issues in this thread. The issue isn't that the subtitles are slightly out of sync, although that could also be true based on your findings and potentially needs a different thread. That issue you mention might also only happen with transcoding. Remuxing might not have the same problem and in fact I've not observed your behavior with remuxed streams, though I've not used Jellyfin long enough to notice.

The issue we're talking about here is that when seeking, both the video and audio work as expected but the subtitles play from the previous position. So for example if I seek from 10 minutes to 25 minutes, the video and audio plays from 25 minutes but the subtitles are playing as though the video is still at 10 minutes. Switching apps so can also cause this, which might or might not be a related issue.

The fix is to simply turn subtitles off and back on again, which seems to force a reload of the subtitle data with the correct timing. 

Based on what you say a true correct fix might not be possible without a lot of work. A simpler fix, though a hack, might be for the client after seeking to do the same steps as turning the subtitles off and back on again. This essentially automates the process that we have to do by hand right now. We might even want to consider doing this automatically every 5 minutes to avoid any drift problems that you're talking about. I imagine though that this might be more bandwidth heavy and cause problems with remote connections.

**Comment by hkup859** [comment] 2023-03-11 16:14
For simplicity I like the idea of forcing a refresh upon seeking, not sure about regularly though. While it's not the "best" approach, I think it's certainly the easiest to implement and still a reasonable fix. From a user perspective they wouldn't care how it works behind the scenes so long as it works reliably.

**Comment by RubenTeixeira** [comment] 2023-03-11 16:18
> I've gone through your comments twice. I'm a little too tired right now to get a complete an understanding and to fully figure out what you mean, but from what I understand essentially the subtitles and video data can't be kept in time sync because we can't ensure that the video (or audio?) time is always correct. As a side note I wonder if this also affects sync play?
> ...

@cbeamond  From my understanding, I guess @hkup859 description may be a bit more related to the issue I was refering earlier, which may be more of a server side issue than client side, and seems to occur more consistently while re(muxing|enconding)...

**Comment by cbeamond** [comment] 2023-03-11 16:28
After reading with earlier comments it seems that there has been some confusion. There seems to be two different issues talked about in this thread:

1. The issue where video data and subtitles can become out of sync. @khangp0000 makes a great break down of how this happens due to a side effect of transcoding. It does not appear to happen with remuxing. We need to confirm if this happens without using seeking, without changing apps, and whether it happens only on transcoded media or both transcoded and remuxed media.
2. The issue that seeking itself can cause the subtitles to be out of sync. This is a totally different issue to number 1. Even if situation 1 is in play, I don't see how that situation can cause subtitles be out of sync by tens of minutes. Plus we already know that turning subtitles off and back on fixes it.

**Comment by cbeamond** [comment] 2023-03-11 16:31
> For simplicity I like the idea of forcing a refresh upon seeking, not sure about regularly though. While it's not the "best" approach, I think it's certainly the easiest to implement and still a reasonable fix. From a user perspective they wouldn't care how it works behind the scenes so long as it works reliably.
> 
> For what it's worth, while I'm definitely not an expert or anything in this code or issue, I do think khangp0000 is referring to a different issue and not the issue we are seeking to resolve here.

The reason I brought up regularly resyncing the subtitles is because of earlier comments about the subtitles essentially drifting apart over time. This appears to be an issue caused by transcoding and this approach might not even solve it. It also might not be required for remuxed media.

**Comment by cbeamond** [comment] 2023-03-11 16:39
There might already be a fix for the seeking problem in https://github.com/jellyfin/jellyfin-web/pull/4345 as discussed in https://github.com/jellyfin/jellyfin-web/issues/4346

Later on I'll downgrade to 10.8.8 and see if that helps. I was going to do this anyway but earlier in the thread it was specified that the same issue happens on 10.8.4. This might be the transcoding bug and not the seeking but though.

**Comment by khangp0000** [comment] 2023-03-12 01:26
> 1. media

I am not sure if 2 relate is 1 or not, note that the offset of even 1 second every 3 second can build up to multiple minutes if the video is long enough so it totally possible for the subtitles to be mismatch for minutes.

The simple observation in all case that I see is that turn on and off subtitle does not work, you have to exit in and out so that it have to go to correct timestamp (when you exit it save actual file timestamp instead of player seek timestamp). The subtitle is always correct and match the timestamp, but the video is incorrect (try open the file directly in your computer). 

So the subtitle issue van be fix if we fix the seek issue, which is not trivial to fix, cause it is not an actual player issue, but an issue created by jellyfin generated playlist and ffmpeg indeterministic segmenting nature.

**Comment by ldexterldesign** [comment] 2023-03-16 03:07
👋

I believe this is a server issue not a player issue

My .mkv (hardcoded subtitles) file plays OK in [MPV] so it's not a bad file or subtitles

I'm running jellyfin and [jellyfin-web] in (macOS) Docker so usually when I have a problem with one (jellyfin) player I will switch to the other to see if the problem persists. In this case the problem did persist. It was consistently ~10m into a ~50m file.

I attempted to fix the problem by playing the file again from the start in both players and turning subtitles on and off - neither fixed the issue

After I restarted the server from dashboard (i.e. shutdown) subtitles played in sync again in both players

If logs may be useful then just ask

Hope this helps!

Regards

PS @khangp0000 thanks for [explanation]

[MPV]: https://mpv.io
[explanation]: https://github.com/jellyfin/jellyfin/issues/8403#issuecomment-1464920050
[jellyfin-web]: https://github.com/jellyfin/jellyfin-web

**Comment by MasterMach50** [comment] 2023-03-16 13:38
@ldexterldesign did you mean that you used MPV to stream the file from  jellyfin-server over the network?

**Comment by ldexterldesign** [comment] 2023-03-16 18:12
@MasterMach50 I used MPV to play the file on my local machine

**Comment by MasterMach50** [comment] 2023-03-17 11:01
@ldexterldesign simply playing file on your local machine has no relation to jellyfin, I guess there was something wrong with the file itself?

If there were any issues with the jellyfin server/client only the playback through the server should be affected and not simply playing the file locally using mpv.

**Comment by ldexterldesign** [comment] 2023-03-17 16:26
@MasterMach50 please stop messaging me

**Comment by matiasba** [comment] 2023-04-10 06:27
I also experience this issue on the latest version. It affects the android app and the web player but not the desktop app for some reason. It's really inconsistent

**Comment by matiasba** [comment] 2023-04-10 07:07
I did some more testing and it doesn't seams to happened in the android app if you use the integrated player instead of the web one. There is also a lot of reviews of the app that mentioned this issue so it seems to be quite spread.

**Comment by khangp0000** [comment] 2023-04-10 07:13
> I did some more testing and it doesn't seams to happened in the android app if you use the integrated player instead of the web one. There is also a lot of reviews of the app that mentioned this issue so it seems to be quite spread.

Integrate player only remux, no transcoding so seek is always correct.

**Comment by khangp0000** [comment] 2023-04-10 07:14
Also I test the beta android jellyfin apk with integrate player having choice of quality, enabling transcoding. It is still happening. So it is not player issue.

**Comment by ecker00** [comment] 2023-06-03 18:14
Subtitles seems to go out of sync when playing back at higher speed, could this be also related?

**Comment by rootz-pt** [comment] 2023-06-14 18:51
Experiencing this on webOS app (LG TV), .srt subtitles are simply out of sync for all my movies.
Same .srt file on VLC media player is synched.

**Comment by viown** [comment] 2023-06-16 01:41
> The issue where video data and subtitles can become out of sync. @khangp0000 makes a great break down of how this happens due to a side effect of transcoding. It does not appear to happen with remuxing. We need to confirm if this happens without using seeking, without changing apps, and whether it happens only on transcoded media or both transcoded and remuxed media.

I have a lot of media with unsupported audio formats which results in transcoding (which then results in the out of sync issue). What I tried to do was use ffmpeg to encode a compatible audio track for all of my media and store it as a separate audio file. This does result in remuxing when I try to play it back, which unfortunately still caused subtitles to go out of sync for me.

**Comment by rootz-pt** [comment] 2023-06-16 14:21
I'm inclined on my case that the issue is on dec

> > The issue where video data and subtitles can become out of sync. @khangp0000 makes a great break down of how this happens due to a side effect of transcoding. It does not appear to happen with remuxing. We need to confirm if this happens without using seeking, without changing apps, and whether it happens only on transcoded media or both transcoded and remuxed media.
> 
> I have a lot of media with unsupported audio formats which results in transcoding (which then results in the out of sync issue). What I tried to do was use ffmpeg to encode a compatible audio track for all of my media and store it as a separate audio file. This does result in remuxing when I try to play it back, which unfortunately still caused subtitles to go out of sync for me.

On my case i think the issue results as consequence of transcoding.
Are you able to tell if this is an unsupported audio format?

Codec DCA
Channels 6
Bitrate 3873 kbps
Language English
Language Tag en
Audio Channel Layout 5.1(side)
Bit Depth 24
Profile ma
Sampling Rate 48000 Hz
Display Title English (DTS-HD MA 5.1)
Extended Display Title English (DTS-HD MA 5.1)

**Comment by raulpetru** [comment] 2023-06-18 12:09
I also have this issue. All my media is h264 AAC audio in mkv container and it plays without any problem on Windows: Jellyfin Media player (direct playback), Edge browser (Direct playback), Firefox (remuxing). But when I try on iOS, on all browsers the ASS subtitle is out of sync. Only native players work well on iOS (Infuse and Switfin), all other players (browser: Edge, Safari) or official iOS app doesn't sync subtitles.

**Comment by viown** [comment] 2023-06-23 16:04
> I also have this issue. All my media is h264 AAC audio in mkv container and it plays without any problem on Windows: Jellyfin Media player (direct playback), Edge browser (Direct playback), Firefox (remuxing).
> 
> But when I try on iOS, on all browsers (remuxing) the ASS subtitle is out of sync. Only native players work well on iOS (Infuse and Swiftfin), all other players like browser: Edge, Safari or official iOS app doesn't sync ASS subtitles (shouldn't matter the browser choice on iOS since all browsers are just a wrapper over Safari).
> 
> For me it seems that the subtitles doesn't work well with the web player of different browser engines.

I can attest to this. The issue seems to mainly occur on iOS when the media happens to be remuxing. Interestingly, the subtitles will remain in sync on iOS if the media is transcoding.

**Comment by HHUBSS** [comment] 2023-08-18 17:00
As of today, it is still out of sync when scrubbing in the video.

**Comment by ArchGryphon9362** [comment] 2023-08-18 18:21
Just some news on the issue. It goes away from me more often than not when I delete everything the transcoding directory. (if jellyfin does it itself, it gets fixed too)

**Comment by PCJones** [comment] 2023-08-20 18:41
I just want to add that I experience this too on Jellyfin for fire TV when the video is transcoding and I'm seeking. It's really inconsistent though so there is no easy way to reproduce it for ne

**Comment by ringus1** [comment] 2023-09-25 20:06
Not 100% sure, but issue with subtitles being out of sync is resolved for me when I changed `max_delay`  value to `0` here: https://github.com/jellyfin/jellyfin/blob/ee6931475321c428106b3f44f41e6756727925f8/Jellyfin.Api/Controllers/DynamicHlsController.cs#L1649

Tested when transcoding on iOS client, natively playing `ts` segments with VLC, AndroidTV (I think).

**Comment by ToxicFrog** [comment] 2023-10-06 02:04
I'm not sure if what I'm seeing is the same issue, but it may be related.

The observed problem is that, when playing some files, the subtitles gradually get out of sync with the audio. By the end of a 40-minute episode the subtitles are ±5 seconds or more (early or late -- depends on the file). The affected files are H264 with AAC audio and ASS subs. The same files play back perfectly in VLC, and demuxing them and dissecting the subtitles by hand also shows the timestamps to be correct.

Seeking does not seem to affect it. If I seek to the end subs are 5s early, if I seek back to the start they're in sync. So it's properly resyncing the subs after a seek, it's just increasing wrong about _where_ to sync them to as it approaches the end of the file.

Interestingly, this does not affect all files, or even all files with ASS subs -- I have other stuff using ASS for fancy subtitle effects and those work fine. But on files that _are_ affected, it occurs whether or not server-side hardsubbing is turned on, which I did not expect. So based on that I think it probably isn't a jellyfin-web issue; if it was, hardsubbing would fix it.

**Comment by dspencer001** [comment] 2024-01-05 16:26
I was running into a similar sounding issue on server version 10.8.13, both in iOS and android TV - scrubbing would result in the subtitles being out of sync. It's possible my issues may have been something else though, as I also was seeing an incorrect video length when transcoding and accessing in safari on mac and ios. My issue appears to be fixed for me on master though, and switching to the unstable docker image also resolved it for me in my deployed server. I haven't bisected to figure out what commit fixed it, I'm assuming it will be fixed in 10.9.

**Comment by andrewmy** [comment] 2024-01-09 08:32
Same issue on Samsung TV, awaiting v10.9 to test 😅

**Comment by viown** [comment] 2024-01-10 05:52
> I was running into a similar sounding issue on server version 10.8.13, both in iOS and android TV - scrubbing would result in the subtitles being out of sync. It's possible my issues may have been something else though, as I also was seeing an incorrect video length when transcoding and accessing in safari on mac and ios. My issue appears to be fixed for me on master though, and switching to the unstable docker image also resolved it for me in my deployed server. I haven't bisected to figure out what commit fixed it, I'm assuming my issue at least will be fixed in 10.9.

Tested out the unstable docker image but this issue seems to still be present for me as seeking through the media causes the subtitles to go out of sync on iOS. Haven't tested other clients that are affected by this issue yet.

**Comment by anon79678** [comment] 2024-01-23 22:27
This has seemingly become worse to a point where I am struggling to watch foreign media.

Device: Nvidia Shield Pro
JF Server Version: Latest
JF App Version: Latest

Subtitles are extracted. I've noticed this issue with both SRT and ASS formats. SUP and SUB do not appear to have this issue but I can confirm if need be.

**Comment by realitymolder** [comment] 2024-01-28 05:48
I think that on Findroid the issue is happening much less

**Comment by itschasa** [comment] 2024-01-28 12:33
I believe the issue is with exoplayer, as this is happening across android tv devices (fire tv stick 4k max, fire tv cube, nvidia shield 2019), and software (plex, jellyfin, kodi) when using exoplayer.

**Comment by psychedelicu** [comment] 2024-02-14 18:39
I have the same issue on Tizen TV web player. Any fix?

**Comment by solidsnake1298** [comment] 2024-02-14 19:09
If the files you all are having issues with are MKVs, use this command to repackage them.  An improperly authored MKV file can have issues with the packet time stamps that can manifest as either stuttering, losing sync when scrubbing, or inability to scrub altogether.

`/usr/lib/jellyfin-ffmpeg/ffmpeg -fflags genpts -i "/path/to/your/video.mkv" -map 0:v -map 0:a -map 0:s -map_chapters 0 -c:v copy -c:a copy -c:s copy outputFile.mkv`

**Comment by felix920506** [comment] 2024-02-14 19:14
Closing this issue in favor of https://github.com/jellyfin/jellyfin-web/issues/4346 for the following reasons:
1. There is a fair bit of off topic chatter present in this issue, making it harder to follow
2. It seems like the issues are only present using certain clients

**Closed by felix920506** 2024-02-14 19:14 UTC
Labels: bug
