### ISSUE TITLE
Regression: Jellyfin 10.6.0 hides series ending in "."

### ISSUE THREAD

**Issue by Ken-g6** [jellyfin/jellyfin#3794] opened 2020-08-02 22:56 UTC
**Describe the bug**

Given I have a directory "TV Shows" in my Library,
And I have TV series in that directory whose names end in a period ("."), such as "Magnum P.I." or "Marvel's Agents of S.H.I.E.L.D.",
Then Jellyfin should display those shows,
But starting with version 10.6.0 it hides them.  The log says 'Removing item, Type: "Series"', but the files still exist.

**System (please complete the following information):**
 - OS: Ubuntu Linux 18.04.4 LTS
 - Virtualization: None
 - Clients: Browser, Fire tablet
 - Browser: Firefox 79, 64-bit
 - Jellyfin Version: 10.6.0/10.6.1
 - Playback: N/A 
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: none
 - Base URL: /jellyfin (yes, I set it up that way)
 - Networking: localhost
 - Storage: local; files are symlinks, but directories are not.

**To Reproduce**

1. Add a TV Series to your Library which ends with a period (".").  Examples: "Magnum P.I.", "Marvel's Agents of S.H.I.E.L.D."
2. Refresh the library.
3. Look at your library.  Expected: The TV series appears.  Actual: If your version of Jellyfin is 10.6.0 or later, the series does not appear.
4. If your version of Jellyfin older than 10.6.0, upgrade to 10.6.0 or later.  Refresh the library again.  In the log you will see something like this for each series ending with a period:
```
[2020-07-24 16:27:52.290 -06:00] [INF] Removing item, Type: "Series", Name: "Magnum P.I.", Path: "/var/lib/plexmediaserver/Library/TV Shows/Magnum P.I.", Id: f7b73e23-50b6-39de-a1a6-d2b2e658ab36
[2020-07-24 16:27:53.480 -06:00] [INF] Removing item, Type: "Series", Name: "Marvel's Agents of S.H.I.E.L.D.", Path: "/var/lib/plexmediaserver/Library/TV Shows/Marvel's Agents of S.H.I.E.L.D.", Id: 7097b107-c4db-3f51-c7fa-37ca03bfb76b
```
And the TV series will disappear from the library.

**Expected behavior**

Jellyfin should list TV Shows that end with a period, and not remove existing shows from its listing.

**Logs**

```
[2020-07-24 16:27:52.290 -06:00] [INF] Removing item, Type: "Series", Name: "Magnum P.I.", Path: "/var/lib/plexmediaserver/Library/TV Shows/Magnum P.I.", Id: f7b73e23-50b6-39de-a1a6-d2b2e658ab36
[2020-07-24 16:27:53.480 -06:00] [INF] Removing item, Type: "Series", Name: "Marvel's Agents of S.H.I.E.L.D.", Path: "/var/lib/plexmediaserver/Library/TV Shows/Marvel's Agents of S.H.I.E.L.D.", Id: 7097b107-c4db-3f51-c7fa-37ca03bfb76b
```
[jellyfin20200724-partial.log](https://github.com/jellyfin/jellyfin/files/5013096/jellyfin20200724-partial.log)

**Screenshots**

Directory listing of TV shows:
![Screenshot_directory_listing_2020-08-02_16-44-12](https://user-images.githubusercontent.com/281895/89134151-d421c580-d4df-11ea-82e0-603106672caa.png)

How they appear in Jellyfin:
![Screenshot_missing_shows_2020-08-02_16-39-33](https://user-images.githubusercontent.com/281895/89134176-15b27080-d4e0-11ea-9629-ee6849b6307f.jpg)

**Additional context**

Files in the directories are all soft-links. (#2354) That seems unrelated.
Some directories did not have write permissions for Jellyfin.  That threw a lot of errors in the log - which I removed - but that seems unrelated, since only one of these shows had such errors, and many unaffected shows had such errors too.

**Comment by crobibero** [comment] 2020-08-02 22:59
Dupe of https://github.com/jellyfin/jellyfin/issues/3635

**Closed by crobibero** 2020-08-02 22:59 UTC
Labels: bug
