### ISSUE TITLE
[Issue]: Misleading error message when resetting password for disabled user

### ISSUE THREAD

**Issue by NCLI** [jellyfin/jellyfin#7622] opened 2022-04-19 16:18 UTC
### Please describe your bug

Using the Jellyfin 10.8.0 beta 2 docker image.

Steps to reproduce:
1. Open a disabled user in the dashboard.
2. Reset their password.
3. Try to set a new password.

What happens:
I receive error "Invalid username or password"

What I expected to happen:
Either:

A: Receive error message "Cannot set a password for a disabled user"
B: Allow setting the password for disabled users.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: NA
- Playback Method: NA
- Hardware Acceleration: NA
- Plugins: NA
- Reverse Proxy: NA
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

`[2022-04-19 16:07:24.488 +00:00] [INF] [39] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "ACCOUNTNAME" has been denied because this account is currently disabled (IP: "10.0.0.117").
[2022-04-19 16:07:24.489 +00:00] [ERR] [39] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The ACCOUNTNAME account is currently disabled. Please consult with your administrator". URL "POST" "/Users/8053b1c8e3c3406d83e244bb77f60020/Password".`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment] 2022-04-19 20:34
Duplicate of jellyfin/jellyfin-web#3199

**Closed by 1337joe** 2022-04-19 20:34 UTC
Labels: bug, duplicate
