### ISSUE TITLE
Crash since update to 10.9, caused by too heavy memory usage

### ISSUE THREAD

**Issue by mpeter50** [jellyfin/jellyfin#12651] opened 2024-09-15 20:49 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Before the update, I was using 10.8.11 for a longer time and I did not have issues with Jellyfin crashing or it causing the VM to stall.
After updating Jellyfin to 10.9.11 from 10.8.11, it was working for a while, but a few hours later (~6) it was crashing and making my VM inaccessible for several minutes.
This is reproducibly always occuring as Docker attempts to restart Jellyfin.

Upon getting the chance to log into the VM that hosts Jellyfin, I noticed that the reason for the crash was that Jellyfin consumed all of the available memory:

![image](https://github.com/user-attachments/assets/236eac22-9151-4f64-b679-34907255782c)

On the screenshot it can be seen that at the point when the VM stalled, Jellyfin consumed 2 GB of RAM.
names of other processes was redacted, thats why a large part of the process list is empty.

The total memory is an odd number, because I'm trying to save on memory on my Proxmox system by using memory ballooning, and some of the memory was ballooned out to be used by an other VM.

I understand that over the years there were other issue tickets regarding unexpected memory usage, but it was always said that "unused memory is wasted memory", "Jellyfin will release cached memory if something else needs it". While I dont understand what makes Jellyfin to release that memory, because the kernel does not account it as Cached, it seems that is not happening on my instance.
By looking at the logs when Jellyfin is starting up, it seems that ffprobe-ing my media files is what causes Jellyfin to rapidly increase its memory usage.

### Reproduction steps

1. Start up the Jellyfin server, and thats it. Memory consumption just increases until it stalls the VM and the process crashes

### What is the current _bug_ behavior?

Attempting to use more memory than available

### What is the expected _correct_ behavior?

Only using memory that is available, and leaving some to other programs too. My server is running other software too, that needs it.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-25
- Virtualization: Proxmox, + Docker inside the VM
- Clients: Browser, smart TVs
- Browser: Firefox
- FFmpeg Version: bundled
- Playback Method: primarily direct play, but at startup that is probably not relevant
- Hardware Acceleration: none
- GPU Model: none
- Plugins: Reports, Playback Reporting
- Reverse Proxy: nginx
- Base URL: none, on subdomain
- Networking: proxied through Docker container (nginx)
- Storage: local
```

### Jellyfin logs

```shell
jellyfin  | [20:07:16] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:17] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:18] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:19] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:19] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:20] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:21] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:21] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:21] [INF] [25] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:22] [INF] [24] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:23] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:25] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:26] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:27] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:28] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:30] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:31] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:32] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.56.20 request
jellyfin  | [20:07:33] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.56.20 closed
jellyfin  | [20:07:33] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:34] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:36] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:37] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:38] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:39] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:40] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:41] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:41] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:42] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:43] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:45] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:46] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:47] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:47] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:48] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:48] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:49] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:50] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:52] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:52] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:52] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:53] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:54] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:55] [INF] [29] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:57] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:57] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:57] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:58] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:07:59] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:02] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:02] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:03] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:03] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:05] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:06] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:07] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:07] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:08] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:09] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:11] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:12] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:13] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:13] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [20:08:14] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/.../....mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
```

### Additional information

Could not include full logs, as it contains a lot of private information. The included sample is from the timeframe where the memory usage spiked until Jellyfin crashed and the VM stalled for another 15 minutes. Path names were redacted in it, but essentially they are multi-gigabyte mp4 files residing on Docker volumes.
Sorry for this, but I just realized after 10 minutes of redacting paths that library information is included in other paths too that I did not expect, and that I wont be able to properly redact the full log.

**Comment by felix920506** [comment] 2024-09-15 21:00
Duplicate of #11588

**Closed by felix920506** 2024-09-15 21:00 UTC
Labels: bug

**Comment by mpeter50** [comment] 2024-09-15 21:16
oh, sorry. did not see it when searching for "ram"
