### ISSUE TITLE
Fallback to english titles for tv show episodes when the preferred language metadata isn't available.

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin#5574] opened 2021-03-19 21:26 UTC
**Describe the bug**
When you have a preferred metadata language that isn't english, and the title for a tv show episode can't be found in your selected language, it doesn't fall back to the english metadata, it just doesn't use anything. 

I'm considering this a bug because the correct behavior does happens with episode descriptions. If JF can find episode descriptions in pt-BR, it uses them, if not, it uses the english ones. 

I have TMDB and TvMaze enabled as my metadata providers.

**System (please complete the following information):**
 - OS: Manjaro
 - Virtualization: Docker - linuxserver
 - Clients: Browser
 - Browser: Firefox 86.0.1
 - Jellyfin Version: 10.7

**Screenshots**
Here's a screenshot showing the lack of episode titles in english, and how it does fall back to english descriptions if a portuguese one is not available:
![Screenshot_20210319_182611](https://user-images.githubusercontent.com/26132870/111843825-9ba0f180-88e0-11eb-903a-152427587f70.png)

**Comment by Ullmie02** [comment] 2021-03-19 23:06
Closing becaus it's a duplicate of #4822

**Closed by Ullmie02** 2021-03-19 23:06 UTC
Labels: bug
