### ISSUE TITLE
Ampersand in automatic collection title causing issues

### ISSUE THREAD

**Issue by jesse-kaufman** [jellyfin/jellyfin#13031] opened 2024-11-14 13:44 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When a collection is automatically added that contains an ampersand in the title, it is improperly escaped. Fixing it manually works, but the next time automatic collection creation happens, the mistitled collection is recreated.

### Reproduction steps

1.  Turn on automatic collection creation 
2. Add multiple Bill & Ted movies to Jellyfin
3. Wait for automatic collections to be created
    - _Title of collection is "Bill &amp;amp;amp; Ted Collection"_
3. Rename collection to "Bill & Ted Collection"
4. Wait for automatic collections to be created
    - _New "Bill &amp;amp;amp; Ted Collection" is created alongside fixed collection_

### What is the current _bug_ behavior?

Automatically-created collections with ampersands in the title are improperly escaped. Deleting the mis-titled collection results in the mis-titled collection being recreated the next time automatic collection task is run, so every time it runs I have to re-delete the collection. Fixing the title doesn't work, either, as the next time the task is run, the mis-titled collection is recreated anyway.

### What is the expected _correct_ behavior?

Collections with ampersand should display correctly.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

```markdown
- OS: Ubuntu Linux
- Linux Kernel: 6.8.0-47-generic
- Virtualization: LinuxServer.io Docker image
- Clients: Multiple
- Browser: Multiple
- FFmpeg Version: included in Docker image
- Playback Method: Any
- Hardware Acceleration: VAAPI
- GPU Model: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
- Plugins: Artwork, AudioDB ,Bookshelf, CinemaMode, Cover Art Archive, Fanart, MusicBrainz, OMDb, Playback Reporting, SkinManager, Studio Image, TMDb, ThePornDB, TheTVDB
- Reverse Proxy: Traefik v3.2
- Base URL: none
- Networking: Bridge
- Storage: Local
```

### Jellyfin logs

```shell
I don't see anything relevant in the logs about automatic creation of collections.
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment] 2024-11-14 13:50
Bill & Ted is working correctly on my instance. 

![image](https://github.com/user-attachments/assets/ca90b605-d656-4ea8-86db-960c02c1b6e0)

**Comment by jesse-kaufman** [comment] 2024-11-14 13:52
> Bill & Ted is working correctly on my instance.
> 
> ![image](https://github.com/user-attachments/assets/ca90b605-d656-4ea8-86db-960c02c1b6e0)

I just re-deleted it for the 5th time here.

**Comment by jesse-kaufman** [comment] 2024-11-14 14:15
And it's back again .. nothing changed except I added an unrelated movie and rescanned the library.


![Image](https://github.com/user-attachments/assets/bdaf3279-5996-4924-a73b-1598ac4680ad)

**Comment by TheMelmacian** [comment] 2024-11-14 15:57
duplicate of https://github.com/jellyfin/jellyfin/issues/10767

**Comment by Shadowghost** [comment] 2024-11-14 15:59
Duplicate of #10767

**Closed by Shadowghost** 2024-11-14 15:59 UTC
Labels: bug
