### ISSUE TITLE
[Issue]: Collections broken after updating to 10.9

### ISSUE THREAD

**Issue by space-seed** [jellyfin/jellyfin#11572] opened 2024-05-12 18:35 UTC
### Please describe your bug

Collections dont show any items after updating to 10.9. If I manually create a new collection or try to add items to existing collections, none show up. All collections are empty, even previously created ones which were fine in 10.13

### Reproduction Steps

On Jellyfin acces or create a collection.
Add items to it.
Browse to said collection.
No items are in it!

### Jellyfin Version

10.9.0

### Environment

```markdown
Jellyfin Server on Win 10 Education
i7 6500U 16 GB RAM
GTX 950M
```

### Jellyfin logs

```shell
[2024-05-12 16:41:49.921 +02:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "D:\REDACTED_FOR_PRIVACY ext\Cinema\Movies\Star Wars_ Episode I - The Phantom Menace (1999)\Star Wars_ Episode I - The Phantom Menace (1999) - 2160p HDR x265 CRF.mkv"
[2024-05-12 16:41:49.928 +02:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "D:\REDACTED_FOR_PRIVACY ext\Cinema\Movies\Rogue One (2016).mkv"
[2024-05-12 16:41:49.931 +02:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.Tasks.CleanupCollectionAndPlaylistPathsTask: Item in "Star Wars Collection" cannot be found at "D:\REDACTED_FOR_PRIVACY ext\Cinema\Movies\Star Wars_ The Empire Strikes Ba
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-05-12 18:37
Should be fixed by #11570

Please be aware that you will need to restore from backup even after this is released

**Comment by MdXMaxX** [comment] 2024-05-13 01:54
I ran into this issue with Playlists and installing 10.9.1 seems to have resolved the issue; existing playlists show all their contents again.  Thanks @gnattu for the fix!

**Comment by gnattu** [comment] 2024-05-13 02:19
10.9.1 Windows installer is up. You can test with that version with your 10.8 backup. It should work as intended now.

If you don't have your 10.8 database backup, then I'm not sure if those collections items will ever come back though.

**Closed by gnattu** 2024-05-13 02:19 UTC
Labels: bug
