### ISSUE TITLE
Nightly won't work with Infuse 6 app

### ISSUE THREAD

**Issue by superjeng1** [jellyfin/jellyfin#4654] opened 2020-12-04 06:44 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows
 - Clients: Infuse
 - Jellyfin Version: 10.7.0, nightly 20201204.18

**To Reproduce**

1. Download Infuse 6 app for iOS. (It's free)
2. Click on 'Add Files'
3. Add Jellyfin media server.

**Expected behavior**
It should login successfully and add the library to the app.

**Logs**
```
C:\Users\super\Downloads\jellyfin>C:\Users\super\Downloads\jellyfin\system\jellyfin.exe
[14:30:38] [INF] [1] Main: Jellyfin version: 10.7.0
[14:30:38] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\\Users\\super\\AppData\\Local\\jellyfin\\log]"]
[14:30:38] [INF] [1] Main: Arguments: ["C:\\Users\\super\\Downloads\\jellyfin\\system\\jellyfin.dll"]
[14:30:38] [INF] [1] Main: Operating system: Windows
[14:30:38] [INF] [1] Main: Architecture: X64
[14:30:38] [INF] [1] Main: 64-Bit Process: True
[14:30:38] [INF] [1] Main: User Interactive: True
[14:30:38] [INF] [1] Main: Processor count: 12
[14:30:38] [INF] [1] Main: Program data path: C:\Users\super\AppData\Local\jellyfin
[14:30:38] [INF] [1] Main: Web resources path: C:\Users\super\Downloads\jellyfin\system\jellyfin-web
[14:30:38] [INF] [1] Main: Application directory: C:\Users\super\Downloads\jellyfin\system\
[14:30:38] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: C:\Users\super\AppData\Local\jellyfin\cache
[14:30:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[14:30:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[14:30:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[14:30:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[14:30:38] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[14:30:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[14:30:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly InfuseSync, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null from C:\Users\super\AppData\Local\jellyfin\plugins\InfuseSync_1.2.4.0\InfuseSync\InfuseSync.dll
[14:30:38] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from InfuseSync, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null.
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturn`1' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
[14:30:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Plugins: OMDb 10.7.0.0
MusicBrainz 10.7.0.0
AudioDB 10.7.0.0

[14:30:39] [INF] [1] Main: Kestrel listening on Any IP4 Address
[14:30:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[14:30:40] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 12/05/2020 02:00, which is 11:29:19.9419069 from now.
[14:30:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.1
[14:30:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[14:30:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[14:30:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[14:30:40] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: System: C:\Users\super\Downloads\jellyfin\system\ffmpeg.exe
[14:30:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 17c601c4267e4c4685395e0033799416
[14:30:40] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.xxx.xxx/24
[14:30:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0740382
[14:30:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[14:30:40] [INF] [18] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory E:\Movie
[14:30:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1092167
[14:30:40] [INF] [1] Main: Startup complete 0:00:01.89884
[14:30:43] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[14:30:43] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[14:30:43] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[14:30:45] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 2 seconds
[14:30:45] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[14:31:16] [INF] [14] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for superjeng1 has succeeded.
[14:31:16] [INF] [14] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user superjeng1: 0/0
[14:31:16] [INF] [14] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 43db0cc4-1478-452b-83e8-a24e8095da26
[14:31:17] [WRN] [15] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://redacted.com:443/Packages to xx.xx.xx.xx in 0:00:01.0527704 with Status Code 200
```

**Screenshots**

<img src="https://user-images.githubusercontent.com/33928963/101130760-09c9ed00-363f-11eb-85b2-5c752f824213.jpeg" width="300">

**Comment by dkanada** [comment] 2020-12-04 07:49
This looks related to the plugin rather than possible API changes, although I wouldn't rule either one out.

**Comment by nyanmisaka** [comment] 2020-12-04 08:31
Encountered same issue here.

InfuseSync plugin is aimed at improving the scanning speed. It's not necessary IIRC.

**Comment by superjeng1** [comment] 2020-12-04 08:38
Should I do some investigation with the packets? Also I don't think it's the plug-in. It cannot login either with or without it.

**Comment by crobibero** [comment] 2020-12-04 15:20
cc https://github.com/firecore/

**Comment by anthonylavado** [comment] 2020-12-18 03:17
So this is what I get from the console in Debug mode:
```
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request) in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/HttpServer/Security/AuthService.cs:line 27
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in /Users/anthonylavado/repos/jellyfin/Jellyfin.Api/Auth/CustomAuthenticationHandler.cs:line 47
[22:15:12] [DBG] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[22:15:12] [INF] [4] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for test has succeeded.
[22:15:12] [INF] [4] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user test: 0/0
[22:15:12] [INF] [4] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: 0ccd7c8776144fd89f5b1b33eb6b7855
[22:15:12] [DBG] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request) in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/HttpServer/Security/AuthService.cs:line 27
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync() in /Users/anthonylavado/repos/jellyfin/Jellyfin.Api/Auth/CustomAuthenticationHandler.cs:line 47
[22:15:12] [DBG] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
[22:15:12] [DBG] [4] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[22:15:12] [DBG] [4] Jellyfin.Networking.Manager.NetworkManager: 192.168.0.116/32: GetBindInterface: Has source, matched best internal interface on range. 192.168.0.110
2
[22:15:12] [DBG] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
2
[22:15:12] [DBG] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
[22:15:13] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was successfully authenticated.
```

Not much to go off of, but if there's anything that I can help test with, let me know.

**Comment by nyanmisaka** [comment] 2020-12-18 06:34
I can confirm this still works before the merge of API migration https://github.com/jellyfin/jellyfin/pull/3812

**Comment by superjeng1** [comment] 2020-12-18 06:44
Interesting to know, does this mean this update brings breaking changes to the API? Should it be backwards compatible? And should this be documented?

**Comment by nyanmisaka** [comment] 2020-12-18 08:15
Captured data from packets:

**Before API migration (works):**
(1) GET /Users/guid/Views
https://pastebin.com/7p3ZaxFG
(2) GET /Library/MediaFolders
https://pastebin.com/TbSa1M4k

**After API migration (unexpected response):**
(1) GET /Users/guid/Views
https://pastebin.com/SWCWh9wD
(2) No requests anymore.

Might be related to `UserViewsService` https://github.com/jellyfin/jellyfin/pull/3447

@crobibero Does Infuse client need to make some changes to adapt to the new API in 10.7?

**Comment by crobibero** [comment] 2020-12-18 13:40
Only notable difference:
10.6.4:
```json
"content": {
	"encoding": "base64",
	"mimeType": "application/json; charset=utf-8",
	"size": 1517,
	"text": "[snip]"
},
```

10.7.0
```json
"content": {
	"mimeType": "application/json; charset=utf-8",
	"size": 22379,
	"text": "[snip]"
},
```

Other differences:
10.6.4:
```json
{
	"name": "Content-Encoding",
	"value": "deflate"
},
```

10.7.0
```json
{
  	"name": "Content-Encoding",
  	"value": "gzip"
},
```

**Comment by nyanmisaka** [comment] 2020-12-18 13:49
cc @firecore

**Comment by anthonylavado** [comment] 2020-12-18 16:48
Also paging @tolriq here, and @amet for good measure.

Though thread started with information about Infuse, it looks like this information will apply to Yatse and MrMC. We are discussing it further internally as well.

**Comment by Tolriq** [comment] 2020-12-18 17:53
Read quickly this and the other merged commit but it does not have description :(

Can anyone resume what changes there was? I'll try to find time to test with Yatse is there any directly link for a windows portable nightly ?

**Comment by crobibero** [comment] 2020-12-18 17:55
> 
> 
> Read quickly this and the other merged commit but it does not have description :(
> 
> Can anyone resume what changes there was? I'll try to find time to test with Yatse is there any directly link for a windows portable nightly ?

We've migrated the entire API to a proper ASP.NET WebAPI. It looks like some endpoints were returning a `base64` encoded body, and that is no longer supported. 

Additionally- we now require JSON body POST requests, instead of FORM posts.

**Comment by anthonylavado** [comment] 2020-12-18 18:14
> …is there any directly link for a windows portable nightly ?

@Tolriq This should get you going: https://repo.jellyfin.org/releases/server/windows/versions/stable/combined/10.7.0~rc1/jellyfin_10.7.0~rc1.zip

**Comment by Tolriq** [comment] 2020-12-18 19:14
Hum quickly installed and can't even log on the web interface console says:

```
[19:58:26] [DBG] AuthenticationScheme: CustomAuthentication was not authenticated.
[19:58:26] [ERR] Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
```

Is migration from quite older version supported?

**Comment by Tolriq** [comment] 2020-12-18 19:59
So from a quick test things still seems to work with version linked above don't know if it's 10.7 or already next version , will probably do some more real test next week.

A few notes:
It seems Jellyfin race itself during library scanning.
```
[20:47:50] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: IOException saving to C:\Users\Tolriq\AppData\Local\jellyfin\metadata\People\K\Katherine McNamara\folder.jpg. Will retry saving to C:\Users\Tolriq\AppData\Local\jellyfin\metadata\library\8c\8cf86694548a1b3ff66a1d84e9d76116\folder.jpg
System.IO.IOException: The process cannot access the file 'C:\Users\Tolriq\AppData\Local\jellyfin\metadata\People\K\Katherine McNamara\folder.jpg' because it is being used by another process.
```

Seems some fields are not available but don't know if removed or never present or now default as I still have those values synced it's strange.
```http://192.168.1.80:8096/Users/XXXXXX/Items?Recursive=true&IncludeItemTypes=Movie&ParentId=XXXXX&ExcludeLocationTypes=Virtual&Fields=Genres,SortName,Path,Overview,RunTimeTicks,ParentId,People,ProviderIds,OriginalTitle,Studios,ProductionLocations,MediaSources,DateCreated,VoteCount,RemoteTrailers,ProductionYear,CommunityRating,OfficialRating&startIndex=0&CollapseBoxSetItems=false&limit=500&UserId=XXXXX

````
[20:54:57] [WRN] [76] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: RunTimeTicks is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'RunTimeTicks' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[20:54:57] [WRN] [76] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: VoteCount is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'VoteCount' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[20:54:57] [WRN] [76] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: ProductionYear is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'ProductionYear' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[20:54:57] [WRN] [76] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: CommunityRating is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'CommunityRating' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
[20:54:57] [WRN] [76] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: OfficialRating is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'OfficialRating' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)
````

**Comment by crobibero** [comment] 2020-12-18 20:03
The fields were never present, the previous version just silently discarded them

**Comment by crobibero** [comment] 2020-12-19 19:12
Just tested MrMC, works fine with 10.7.

**Comment by firecore** [comment] 2020-12-21 13:05
@anthonylavado I think we may have figured it out. From what we could tell, the server started omitting milliseconds in some API responses (but not the others). Infuse expects the full dates and we'll need to tweak the date format parser to avoid errors in the future

**Closed** 2020-12-21 22:11 UTC
Labels: bug, confirmed
