### ISSUE TITLE
TVDB API key

### ISSUE THREAD

**Issue by drakus72** [jellyfin/jellyfin#595] opened 2019-01-16 14:59 UTC
**Describe the bug**
Not sure if this has been mention, I haven't seen it anywhere but on #540 where the API keys have been changed.  

**To Reproduce**
Added a new TV Show and when scanning getting this error when it is looking up or downloading the info for The Profit

```
[08:35:08] [INF] HttpClientManager GET: https://www.thetvdb.com/api/OG4V3YJ3FAP7FP2K/series/271671/all/en.zip
[08:35:08] [ERR] Error ProtocolError getting response from https://www.thetvdb.com/api/OG4V3YJ3FAP7FP2K/series/271671/all/en.zip

System.Net.WebException: The remote server returned an error: (404) Not Found.
```

**Expected behavior**
When I change the API key to my own API key in the link, it works just fine.

**Logs**
Please paste any log errors.

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.0.2

**Additional context**
It appears that the API has been updated in the Jellyfin code,, but it is currently not working or being found. Did TVDB API key change or get deleted? My personal API key works just fine if I replace yours with mine on the link.

**Comment by joshuaboniface** [comment] 2019-01-16 16:37
Confirmed. This is because Emby was using TheTVDB API v1, which their yet was enabled for. However our key is only enabled for v2.

As a hotfix, I've asked in [their forums](https://forums.thetvdb.com/viewtopic.php?f=17&t=53450) if we can quickly enable our key for v1.

@Bond-009 is also looking into replacing the API code for the next release to avoid the problem entirely.

**Comment by drakus72** [comment] 2019-01-16 16:41
Completely makes sense of what Emby does. If they won't enable it for v1, let me know I will send my key over to temp fix it.

**Comment by joshuaboniface** [comment] 2019-01-16 16:44
Thanks @drakus72, I'm sincerely hoping we don't have to do another point release for it, but as a worst-case we can check that out. Is your key just grandfathered in, or did you do something to enable it for v1?

**Comment by drakus72** [comment] 2019-01-16 16:48
@joshuaboniface grandfathered in. I will send you my api in a message so that you can try it out.

**Comment by joshuaboniface** [comment] 2019-01-16 17:25
Tested good, so we do have a spare key if required. Will wait about 36 hours to see if I hear back on their forums.

**Comment by anthonylavado** [comment] 2019-01-17 20:14
@joshuaboniface Looks like it's borrowed time, but I agree on at least getting *something* going.

https://forums.thetvdb.com/viewtopic.php?f=3&t=36557

**Comment by joshuaboniface** [comment] 2019-01-20 06:05
@Bond-009 Were you able to make any progress on the APi version switch? If not I'll swap out the key for @drakus72 's for 10.1.0, just as a temporary workaround so at least the TVDB interface works. We can then switch back to our org key once we get that code sorted.

**Comment by Bond-009** [comment] 2019-01-20 10:18
@joshuaboniface Yeah, switching to v2 requires more work that I anticipated.

**Comment by joshuaboniface** [comment] 2019-01-20 17:57
OK, there's been nothing on that forum thread, so @drakus72 I'm going to use your key for 10.1.0. PR will be up shortly!

**Comment by anthonylavado** [comment] 2019-03-18 21:55
Closing in favour of #634, which is more up to date than this.

**Closed by anthonylavado** 2019-03-18 21:55 UTC
Labels: bug
