### ISSUE TITLE
- Upgrade from 10.7.7 to 10.8.0-Alpha fails when using existing /config etc

### ISSUE THREAD

**Issue by derkington** [jellyfin/jellyfin#6807] opened 2021-11-08 16:04 UTC
**Describe the bug**
- Upgrade from 10.7.7 to 10.8.0-Alpha fails when using existing /config

**System (please complete the following information):**
- OS: Debian
- Virtualization: Docker
- Jellyfin Version: 10.8.0-Alpha
- Networking: Host
- Storage: local

**To Reproduce**
1- Take a copy of /config and /cache
2- Point the new instance at the new paths
3- Start up Docker instance 
4- Container fails to initialise

**Expected behavior**
- Upgrade of Jellyfin to 10.8.0-Alpha and a working install.

**Server Logs**
[10:25:38] [INF] [1] Main: Jellyfin version: 10.8.0
[10:25:38] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_CONFIG_DIR, /config/config]"]
[10:25:38] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[10:25:38] [INF] [1] Main: Operating system: Linux
[10:25:38] [INF] [1] Main: Architecture: X64
[10:25:38] [INF] [1] Main: 64-Bit Process: True
[10:25:38] [INF] [1] Main: User Interactive: True
[10:25:38] [INF] [1] Main: Processor count: 2
[10:25:38] [INF] [1] Main: Program data path: /config
[10:25:38] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[10:25:38] [INF] [1] Main: Application directory: /jellyfin/
[10:25:39] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[10:25:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[10:25:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles_12.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[10:25:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly OpenSubtitlesHandler, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles_12.0.0.0/OpenSubtitlesHandler.dll
[10:25:39] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_9.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[10:25:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[10:25:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[10:25:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[10:25:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[10:25:39] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[10:25:40] [FTL] [1] Main: Error while starting server.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'SQLitePCL.pretty.IResultSetValue' from assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Jellyfin.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
System.TypeLoadException: Could not load type 'SQLitePCL.pretty.IResultSetValue' from assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
[10:25:40] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[10:25:40] [FTL] [1] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)

**Comment by cvium** [comment] 2021-11-08 16:07
Duplicate of #6776

**Closed** 2021-11-08 16:07 UTC
Labels: bug
