### ISSUE TITLE
10.8.10版本用浏览器播放HDR和杜比视界视频会提示不兼容媒体

### ISSUE THREAD

**Issue by lw6644700** [jellyfin/jellyfin#10082] opened 2023-08-04 17:29 UTC
10.8.10版本用浏览器播放HDR和杜比视界视频会提示不兼容媒体，关闭色调映射就没问题，或者用VPP色调映射也没问题，10.8.9版本是可以正常色调映射的

**Comment by BG8FRU** [comment] 2023-08-09 02:48
群晖918+，Docker容器版10.8.10，也是播放HDR视频会提示“该客户端与媒体不兼容,服务器未发送兼容的媒体格式”，如不勾选“启用 VPP 色调映射”和“启用色调映射”就能播放，但颜色不正常，勾选任意一个都会提示不兼容。
10.8.9正常，现已回退至10.8.9

**Comment by Bond-009** [comment] 2023-08-09 14:19
Please fill out the issue template

**Comment by felix920506** [comment] 2023-10-03 06:55
Translation:
Synology DS918+, Docker container version 10.8.10, playing HDR content will show "The server isn't sending a compatible format". Works fine when disabling both VPP tone mapping and tonemapping, but the colors are off. Enabling either will cause the above error. 10.8.9 works fine, I have reverted back to 10.8.9

**Comment by felix920506** [comment] 2023-10-12 16:59
I was unable to reproduce this issue on my Jellyfin instance.

Server setup:
Ubuntu server 23.04 bare metal,
Intel Arc A750

Client:
MacOS 13.1
Chrome 117.0.5938.149 (arm64)

Media Info:
<img width="628" alt="截圖 2023-10-12 下午12 58 20" src="https://github.com/jellyfin/jellyfin/assets/25688628/03e5fb56-a2fb-4ae9-b452-bd78ca4868d4">

**Comment by felix920506** [comment] 2023-10-12 17:27
This looks like missing the OpenCL runtime

**Comment by felix920506** [comment] 2023-10-13 20:14
Closing this issue as it cannot be reproduced. It is likely that the image being used doesn't have certain dependencies packaged properly.

**Closed by felix920506** 2023-10-13 20:14 UTC
Labels: bug, regression, media playback
