### ISSUE TITLE
[Issue]: DLNA TVHeadend no longer working in 10.9.2

### ISSUE THREAD

**Issue by Richardk2n** [jellyfin/jellyfin#11800] opened 2024-05-23 09:41 UTC
### Please describe your bug

Since updating to 10.9.2 and installing the now separate DLNA plugin the Live TV folder still shows up (in the VLC App) but is empty. It worked before. There is an error in the logs every time I open the directory from the VLC App.

### Reproduction Steps

1. Install 10.9.2
2. Install TVHeadend Plugin
3. Install DLNA Plugin
4. Open Live TV folder from VLC App

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Unraid 6.19.9
- Linux Kernel: 6.1.82-Unraid
- Virtualization: Docker
- Clients: VLC
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: NVENC
- GPU Model:
- Plugins: TVHeadend DLNA
- Reverse Proxy: nginx
- Base URL: none
- Networking: host
- Storage:
```

### Jellyfin logs

```shell
[11:38:45] [ERR] [189] Jellyfin.Plugin.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, MediaOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.GetOptimalVideoStream(MediaOptions options)
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
   at Jellyfin.Plugin.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2024-09-04 00:27
duplicate of #11791

**Closed by felix920506** 2024-09-04 00:27 UTC
Labels: bug, live-tv
