### ISSUE TITLE
No external subtitles (.srt) on 10.5.0 using DLNA

### ISSUE THREAD

**Issue by mcrapts** [jellyfin/jellyfin#2629] opened 2020-03-19 16:27 UTC
**Describe the bug**
When playing a video from Jellyfin using a DLNA client (in this case a Samsung TV, RU7400), external subtitles (.srt) are not displayed. This does not happen with 10.4.3.

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Virtualization: Docker 
 - Clients: Samsung RU7400
 - Browser: not relevant
 - Jellyfin Version: jellyfin/jellyfin:10.5.0 
 - Playback: DLNA, direct play
 - Installed Plugins: none
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. Have a video with external .srt subtitles in a Jellyfin 10.5.0 library with matching filenames
2. Use a Samsung TV (in my case RU7400) to play a video using DLNA
3. Subtitles are not displayed

**Expected behavior**
Subtitles are displayed

**Logs**
I couldn't find any log errors

**Comment by Artiume** [comment] 2020-03-20 14:14
Probably a duplicate of #2525

Fix will be in next release

**Comment by Artiume** [comment] 2020-03-23 11:08
Can you test this with 10.5.2

**Comment by mcrapts** [comment] 2020-03-23 14:59
Works with 10.5.2!

**Closed** 2020-04-02 15:20 UTC
Labels: bug

**Comment by gattohub** [comment] 2020-07-23 18:51
Hi. I have Jellyfin 10.6 on an Arm64 Rockpi4 board. I have the opensubtitles 7.0 plugin installed. When I try to watch a movie with external subtitles through DLNA on a Samsung TV it does not show the subtitles. I have placed the subtitles in the same folder as the movie with the same name, and it still doesn't show them. If I test the file from a browser on the same board it shows them, but with DLNA it doesn't show them. Any suggestion? Thank you

**Comment by ximbal** [comment] 2021-12-11 23:34
Go to yourjellyfinsever:8096/web/index.html#!/scheduledtasks.html

And click on Scheduled Tasks, then run "Download missing subtitles" task, it runs once every 24 hours, but it seems that it won't download subtitles on demand.
