### ISSUE TITLE
Library metadata with same path in multiple language not working

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin#1649] opened 2019-08-19 11:41 UTC
**Describe the bug**
If I try create same library (i mean with same source path like ../../Movies) two times (first in english for myself, second in slovak for family) it will always use data from first library. In this case it will use English data and completely ignore Slovak settings.

I havent tested TV Shows, but i expect the same behaviour in all library types.

**To Reproduce**
1. Create library with Preferred download language English with *path*
2. Check library, metadata is correctly in english
3. Create second library, this time with Preferred download language for example in slovak, and use same *path* for media
4. If you open this second library, it will be in the language of the first one

**Expected behavior**
Every library should have separate Language settings and separate metadata. Eg. i create for my account library in English... it will be in english, for Family account if create the same library and with Slovak settings, it will have slovak metadata. Plex and Kodi works like this.

**System (please complete the following information):**
 - OS: Windows 6.2.9200.0
 - Browser: Chrome
 - Jellyfin Version: 10.3.7.0

**Comment by RazeLighter777** [comment] 2019-08-19 11:57
A possible temporary workaround is to combine the audio tracks with FFMPEG and select the track manually

**Comment by nextlooper42** [comment] 2019-08-19 12:01
But im mainly talking about UI/Metadata.

**Comment by nextlooper42** [comment] 2019-10-20 10:51
Checked on 10.4, not working. Problem remains the same.

**Comment by JustAMan** [comment] 2019-11-01 14:54
A temp workaround (if Linux) could be using bind mounts and making same files be accessible at two different directories.

**Comment by nextlooper42** [comment] 2019-11-08 10:59
Unfortunately Windows ;(

**Comment by JustAMan** [comment] 2019-11-08 15:34
Then use directory junctions :)

**Comment by nextlooper42** [comment] 2020-03-09 20:16
This bug is present in 10.5.0.

**Comment by Mavrag** [comment] 2020-04-17 02:06
Hey, I have the exact same problem. I'm using plex as my main media server and it doesn't have this issue. A few years back I tried Emby and because of this same issue I never switched. Im guessing this is possible to do but the question is : is this feature will ever be implemented? That's the only thing that's stopping me from from completely switching to jellyfin.

**Comment by nextlooper42** [comment] 2020-05-27 16:23
I suppose there is something really broken in code that no one want to touch, because they use only one language... how lucky. Directory junctions is not solution, only very temporary hot fix.

Anyway, bug is in 10.5.5.

**Comment by nextlooper42** [comment] 2020-07-20 20:03
I was hoping that ongoing DB rewrite in 10.6 will fix this... but no luck :(

Still present in full force.

**Comment by anthonylavado** [comment] 2020-07-21 03:47
@nextlooper42 We're getting there. We've just converted two of the five (maybe more) databases with this release.

**Comment by BaronGreenback** [comment] 2020-07-29 10:50
@nextlooper42 have you the capability to view your sqlite db and see if you actually have multiple entries for items in the two libraries - or there is only one set or two?

**Comment by BaronGreenback** [comment] 2020-07-29 11:09
I could (and might well be way off base).

As I understand it, each items are part of a virtual tree, with the top item being the user defined library.
Each item in the library is assigned a unique MD5 generated key based upon the object type and it's path. (libraryManager.cs/GetNewItemIdInternal takes care of this)

If, however, there are two libraries pointing to the same folder, but with different library properties, wouldn't the same GUID be created? I don't know what would happen to the heirarchical structure processing, but i would suspect as the item already exists, little processing would be done to re-position it within the structure, and thus an items parent would remain the same.

eg. 
Library (english) -> root1\folder1\item1.mp3 gets assigned a GUID of 123, with it's parent being folder 1, and it's root "root1"
Library (french) -> root2\folder1\item1.mp3 already exists in the db (GUID would be the same based on type and path), so i suspect it's parent would remain as folder 1, and it's root as "root1".

If there is only one item in the db then this would suggest the above is correct, and the fix would be to include an additional parameter in the GUID creation, say root language type, to ensure duplicate items with different folder languages would be uniquely identified.

**Comment by BaronGreenback** [comment] 2020-07-31 12:43
Just confirmed the above.

Because the GUID is the same only one version of the library exists in the db.

**Comment by BaronGreenback** [comment] 2020-07-31 19:31
The fix would be to add the library metadata language to the key string in line 530 of LibraryManager.

However, the metadata refresh seems to treat each folder individually, and there doesn't seem to be any link back to the overarching folder in order to retrieve this setting!

**Comment by Ribero** [comment] 2020-10-17 21:06
What about an approach that natively handle multiple languages for each library rather than duplicating libraries?

It would be nice that, for each library, to be able to set the allowed languages available for metadatas. 

Then display the library content and metadata based on end-user selected locale in its personnel profile. If no metadata is available in user's language then revert to a default language. 

It would requires for each library to have a setting to define a default fallback language and a a setting to select all the allowed languages so the scrapers would download metadata in all requested languages and not only one. 

Does it make sens ? Is it realistic or too far from what can be done with current product architecture?

**Comment by BaronGreenback** [comment] 2020-10-17 21:56
Thanks for the comment. 

Ive been informed by the devs that the db rewrite will take care of the support of multiple metadata. The existing system is incapable of this at the present time.

**Comment by natrius** [comment] 2020-12-30 21:11
Question, is it also possible to resolve https://features.jellyfin.org/posts/636/video-language-selection with that as well? I mean, its at least a bit related, isn't it?

**Comment by cvium** [comment] 2021-04-19 07:30
Duplicate of #1481

**Closed by cvium** 2021-04-19 07:30 UTC
Labels: bug, confirmed
