### ISSUE TITLE
When skipping to a new position, subtitles from the last position stay stuck - Chromecast with Jellyfin Android App

### ISSUE THREAD

**Issue by Vyoam** [jellyfin/jellyfin#10133] opened 2023-08-20 14:12 UTC
When using Jellyfin Android App with Chromecast, I observe that when skipping to a new position, subtitles from the last position stay stuck.

The issue isn't there when playing directly on the app. If it matters, I verified that this issue doesn't happen when using Prime Video App with Chromecast.

Please refer to the attached video below (JellyfinBugSampleSpriteFright.mp4), to see the bug in action. There, you can see the projector output, which is being fed by Chromecast. (Apologies for the projection being slightly misaligned to the left and for the lack of audio.)
You can see the bottom two lines of subtitles being stuck, and towards the end the expected lines appear above them.

I downloaded the video and subtitles to my computer from where the Jellyfin Server serves it. Here are the original sources:
Video: https://commons.wikimedia.org/wiki/File:Sprite_Fright_-_Blender_Open_Movie-full_movie.webm
Subtitles: https://commons.wikimedia.org/wiki/TimedText:Sprite_Fright_-_Blender_Open_Movie-full_movie.webm.en.srt

I have seen this bug happen probably in all videos with subtitles.

Debug info etc. is further below.

https://github.com/jellyfin/jellyfin/assets/1176140/ac7318d3-2e81-41da-b5b9-e361cc5210c1

**Media Info of the file**
`Sprite_Fright_-_Blender_Open_Movie-full_movie`
Container: webm
Path: D:\Movies\SpriteFrightPublicDomain\Sprite_Fright_-_Blender_Open_Movie-full_movie.webm
Size: 151 MB

Video
Title: 1080p VP9 SDR
Codec: VP9
Profile: Profile 0
Resolution: 2048x858
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 24
Bitrate: 2014 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1

Audio
Title: English - OPUS - Stereo - Default
Language: eng
Codec: OPUS
Layout: stereo
Channels: 2 ch
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: Undefined - SUBRIP - External
Codec: SUBRIP
Default: No
Forced: No
External: Yes

**Logs**
[log_20230820_trimmed.log](https://github.com/jellyfin/jellyfin/files/12388334/log_20230820_trimmed.log)

**FFmpeg Logs**
[FFmpeglogs.zip](https://github.com/jellyfin/jellyfin/files/12388336/FFmpeglogs.zip)

**Stats for Nerds Screenshots**
N/A on Windows

**Server System (please complete the following information):**
 - OS: Microsoft Windows 10 Home X64
 - Jellyfin Version: 10.8.9
 - Hardware settings & device: No hardware encoding
 - Reverse proxy: no
 - Other hardware notes: no
 
**Client System (please complete the following information):**
 - Device: Samsung Galaxy M51 + Chromecast 3 (System firmware 291998, Cast firmware 1.56.291998)
 - OS: Android 12 + One UI 4.1
 - Client: Chromecast with Jellyfin Android Player 2.5.2

**Comment by Vyoam** [comment] 2023-08-25 17:15
I tried the most of the options in the 'Burn subtitles' setting, but it didn't make much difference. Though, it seems that the issue happens with external srt files and not others (e.g. mkv embedded).

It also seems that it's not just seeking within a video which can cause this bug but also when you switch video... i.e. the subtitles of the previous video can remain stuck.

Not sure if this is a bug with Chromecast.

**Comment by Vyoam** [comment] 2023-09-02 16:00
Came across this randomly. Might check later...
![image](https://github.com/jellyfin/jellyfin/assets/1176140/b5f53088-8442-4357-bab3-2cb6a7bffad0)

**Comment by srcrist** [comment] 2023-10-07 14:08
Possibly related to https://github.com/jellyfin/jellyfin/issues/8403

**Comment by thornbill** [comment] 2023-12-01 21:06
Duplicate of https://github.com/jellyfin/jellyfin-chromecast/issues/362

**Closed by thornbill** 2023-12-01 21:06 UTC
