### ISSUE TITLE
docker build fails in latest dev branch

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin#425] opened 2019-01-05 15:55 UTC
Tried building docker image at commit 818744657b0d412f720bd8ce431680c4d122a2ec (currently latest in dev branch) but it fails.

It seems that commit 49fe9478f3016063eabf7cdf3f29bb8cec34889c does introduce this:

```
49fe9478f3016063eabf7cdf3f29bb8cec34889c is the first bad commit
commit 49fe9478f3016063eabf7cdf3f29bb8cec34889c
Author: Erwin de Haan <EraYaN@users.noreply.github.com>
Date:   Thu Jan 3 21:29:48 2019 +0100

    Removed all old and unused ImageEncoders.
    
    Remove solution platform cruft.

:040000 000000 7afe3b2bf9f8744654da9c54f00a0fe8a4504064 0000000000000000000000000000000000000000 D	Emby.Drawing.ImageMagick
:040000 000000 c011dd1217f1a2a8a50d4d6de51da4bc750b7129 0000000000000000000000000000000000000000 D	Emby.Drawing.Net
:040000 000000 e693a32951185ef65cf31c94a60ed66ab23e469a 0000000000000000000000000000000000000000 D	ImageMagickSharp
:040000 040000 87e449e8158f406b0f6735ef2038d841e2ea9d76 d9d515836f2a06f4b2ae288ec8337c6786036ae8 M	Jellyfin.Server
:100644 100644 077bc6aee7e0d8b489cbdd69548f9dee22a7d82f 6e9f240b075226151e88039ff34778bd42f6d85a M	MediaBrowser.sln
```

git bisect log for reproduction
```
git bisect start
# bad: [818744657b0d412f720bd8ce431680c4d122a2ec] Merge pull request #392 from LeoVerto/dockerignore
git bisect bad 818744657b0d412f720bd8ce431680c4d122a2ec
# good: [ab34f88edba0c90c4fe8b4eb75b6e74ddc9abf8c] Merge pull request #371 from Bond-009/update
git bisect good ab34f88edba0c90c4fe8b4eb75b6e74ddc9abf8c
# good: [fff1f2dac5ef273a8e36c05caaf4de3794bd1a4a] deuglified as per cviums request
git bisect good fff1f2dac5ef273a8e36c05caaf4de3794bd1a4a
# good: [1c6ea53bf746bcbbb881ba93777a92efa5ef797b] Merge pull request #393 from Bond-009/removesmb
git bisect good 1c6ea53bf746bcbbb881ba93777a92efa5ef797b
# bad: [8c7ecf5dddc933751eb6bdf4b28e8426fd6640ef] Merge pull request #407 from EraYaN/stop-version-addins-on-solution
git bisect bad 8c7ecf5dddc933751eb6bdf4b28e8426fd6640ef
# bad: [442441f9ebcad4665ee7c9bba9f88273dd7afff9] Merge pull request #391 from EraYaN/remove-old-imageencoders
git bisect bad 442441f9ebcad4665ee7c9bba9f88273dd7afff9
# bad: [99ed70f7ee1d44b3d5e241896abc5460ff09784f] Removed last using.
git bisect bad 99ed70f7ee1d44b3d5e241896abc5460ff09784f
# bad: [49fe9478f3016063eabf7cdf3f29bb8cec34889c] Removed all old and unused ImageEncoders.
git bisect bad 49fe9478f3016063eabf7cdf3f29bb8cec34889c
# first bad commit: [49fe9478f3016063eabf7cdf3f29bb8cec34889c] Removed all old and unused ImageEncoders.
```

What do you think of testing the commits in a CI environment?

**Comment by anthonylavado** [comment] 2019-01-05 17:21
We’re working on getting the CI back up, there was some difficulty with drone. There’s a proposed fix for this in the chat, so we’re looking at that too.

**Comment by sparky8251** [comment] 2019-01-05 17:52
Well, I can confirm that the fix mentioned works for me at least.
In `ThirdParty/taglib-sharp/src/taglib-sharp.csproj` change 
`<TargetFrameworks>net40;netstandard2.0</TargetFrameworks>` to 
`<TargetFramework>netstandard2.0</TargetFramework>` and try again. Should build fine then.

**Comment by nvllsvm** [comment] 2019-01-05 21:35
Fixed with https://github.com/jellyfin/jellyfin/pull/427

**Closed by nvllsvm** 2019-01-05 21:35 UTC
Labels: bug, build/platform, regression
