### ISSUE TITLE
Upcoming shows are showing that they have aired, or will air one day ahead

### ISSUE THREAD

**Issue by manf0001** [jellyfin/jellyfin#6812] opened 2021-11-09 10:04 UTC
I'm running Jellyfin 10.7.7 on RockyLinux 8

When you go to see the upcoming shows, All the shows in the list seem to be pushed up one day.

For instance, Today is Tuesday.. Shows that are supposed to be on tonight, are showing as Yesterday.

Or if going down the list, shows that are supposed to be on Thursday, are showing for Wednesday etc..

I have confirmed my date and time settings are correct on my Linux server. I have restarted jellyfin, but it seems to think all the shows are or have aired the day before they should be. 

Uninstalled and reinstalled the TVDB plugin.

**Comment by cvium** [comment] 2021-11-09 10:29
Duplicate of https://github.com/jellyfin/jellyfin/issues/4387. See https://github.com/jellyfin/jellyfin/issues/4387#issuecomment-718813175

**Closed by cvium** 2021-11-09 10:29 UTC
Labels: bug
