### ISSUE TITLE
Some shows suddenly take minutes loading playback

### ISSUE THREAD

**Issue by Marco3G** [jellyfin/jellyfin#11050] opened 2024-02-22 17:02 UTC
Well, I've been sent here from this thread: https://forum.jellyfin.org/t-some-shows-suddenly-take-minutes-loading-playback

I have noticed two shows that are stuck on the loading screen for relatively precisely 90seconds before they start playing.
Other shows seem fine. And the first few seasons of BBT worked normally and are still working normally.

Media Info for Clarkson's Farm:

Video
Title: 404p H264 SDR
Codec: H264
Codec tag: avc1
AVC: Yes
Profile: High
Level: 31
Resolution: 720x328
Aspect ratio: 240:109
Interlaced: No
Framerate: 25
Bitrate: 1072 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1
NAL: 4

For Big Bang Theory that isn't working normally:

Video
Title: 404p H264 SDR
Codec: H264
Codec tag: avc1
AVC: Yes
Profile: High
Level: 31
Resolution: 720x404
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 693 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 4

BBT that is:

Video
Title: 384p H264 SDR
Codec: H264
AVC: Yes
Profile: High
Level: 40
Resolution: 640x368
Aspect ratio: 40:23
Interlaced: No
Framerate: 23.976
Bitrate: 633 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: smpte170m
Color transfer: smpte170m
Color primaries: smpte170m
Pixel format: yuvj420p
Ref frames: 1
NAL: 4

Here are the logs from the thread.
https://pastebin.com/0drPm2bJ
https://pastebin.com/ANhq4VTd
https://pastebin.com/Af4qUkVG
https://pastebin.com/sJdCUvu4
https://pastebin.com/UA1RM2h5
https://pastebin.com/buSw0tTn
https://pastebin.com/wG6A4NRc

And after setting log level to Debug
https://pastebin.com/e6mmQtEz
https://pastebin.com/DHLziQWV

And here is a season 2 episode of BBT that starts immediately.
https://pastebin.com/1Sw7gksr

Server System (please complete the following information):
 - OS: Ubuntu 22.04
 - Jellyfin Version: 10.8.13
 - Hardware settings & device: [e.g. NVENC on Quadro P400
 - Reverse proxy: nginx
 - Other hardware notes: Kinda hyperconverged setup. The ESXi host contains the disks whose HBA is pci passthroughed to TrueNAS. The MEdia is then shared on NFS. The Jellyfin VM has its storage on an iSCSI datastore also from said truenas. 12 spindle ZFS behind media, 3stick NVMe behind datastore. Since all traffic is on the vSwitch, I expect 10G connectivity. There is a firewall between TrueNAS and Jellyfin.
 
**Client System (please complete the following information):**
 - Device: Similar experience on two Windows 10 boxes and Firefox current as well as Android app on the phone, also current.
 - Also tried it on Edge. Same problem.

To check for filesize/bandwidth issues, I played T2 in 4k and it started in under 5 seconds.

**Comment by felix920506** [comment] 2024-02-22 18:13
Is there any correlation between slow loading and transcoding? (does slow loading only happen when transcoding?)

**Comment by joshuaboniface** [comment] 2024-02-22 18:18
Playback getting stuck like that is almost invariably an issue with Jellyfin not getting an inotify back from the filesystem for a new transcode chunk being available.

First thing to check is exactly where your transcoding temporary directory is. If it's on NFS, it's going to have this problem; it has to be on a "real" filesystem with inotify support. It's also *possible* the issue is the combination of iSCSI and firewall - in my experience running iSCSI or any similar block system through a firewall always results in a bad time and strange, obscure errors. If it's not the NFS thing, I'd try removing that from the chain and see if it helps.

**Comment by Marco3G** [comment] 2024-02-22 18:20
I'm not sure I can answer that. Both BBT episodes are far from the 4k or 3440x1440 of the two windows machines so I expect transcoding happened on both? I mean I have ffmpeg logs for them, no? Does that not indicate transcoding happened?

**Comment by Marco3G** [comment] 2024-02-22 18:20
> Is there any correlation between slow loading and transcoding? (does slow loading only happen when transcoding?)

I'm not sure I can answer that. Both BBT episodes are far from the 4k or 3440x1440 of the two windows machines so I expect transcoding happened on both? I mean I have ffmpeg logs for them, no? Does that not indicate transcoding happened?

**Comment by Marco3G** [comment] 2024-02-22 18:23
> Playback getting stuck like that is almost invariably an issue with Jellyfin not getting an inotify back from the filesystem for a new transcode chunk being available.
> 
> First thing to check is exactly where your transcoding temporary directory is. If it's on NFS, it's going to have this problem; it has to be on a "real" filesystem with inotify support. It's also _possible_ the issue is the combination of iSCSI and firewall - in my experience running iSCSI or any similar block system through a firewall always results in a bad time and strange, obscure errors. If it's not the NFS thing, I'd try removing that from the chain and see if it helps.

No, no. iSCSI is not going over firewall. The NFS mount is.
Also The playback isn't getting stuck. It takes a long time to BEGIN. Once it has begun, I can skip ahead and back, pause and resume normally.
And again, it is very predictable for Clarkson's Farm and later BBT seasons, whereas there are no issues with things ranging from BluRay Movie rips, up to 4k, to old DVD rips from things like Little House on the Prairie.

It is not random. It is very predictable so far. You start the show and the circle turns for 90s.

**Comment by mcnewton** [comment] 2024-02-22 20:14
In case it's the same issue: I've had a similar random slow-to-start-playback issue for months with Jellyfin (~15s up to 5 minutes or more). VM hosting Jellyfin with media library NFS mounted read-only from separate storage VM. It's been driving me crazy. Web client and Jellyfind Android app both have the same issue. Several different formats of video and different containers, some that need transcoding, most that don't, all on same L2 network segment. Nothing in the logs apart from the occasional "Slow HTTP Response" which most sites I've found say can be ignored.

Investigating it again today I found this comment about NFSv3 which says locking needs to either work or be disabled: https://jellyfin.org/docs/general/administration/storage/#nfs

I added `nolock` to the fstab entry and remounted the media library filesystem. Now everything is playing instantaneously, problem solved.

Don't know if the locking issue can be detected somehow in Jellyfin, but if it could and be reported in the UI as a potential problem (or even just in the logs) then it might help a lot of the reports of slow playback!

**Comment by Marco3G** [comment] 2024-02-23 12:04
Sorry for my delayed reply, as I started going down the rabbit hole, I noticed that write performance for the transcoding directory was horrible for small writes. During investigation, I rather abruptly destroyed the vmfs and I had to do some disaster recovery. Luckily for me, I don't seem to have backup responsibility in my job in vain and I'm up and running again.

That being said, my TrueNAS configuration left a lot to be desired. I have turned off synv, fiddled with block size and so forth and completely given up on iSCSI in the end :D.

I am now on NFS but there too had to tweak certain parameters. Mainly turning off sync and dedup is what gives this whole thing some adequate performance now. Retested the shows in question and wouldn't you believe it, everything now starts instantaneously.

My guess is that the dedup was the main culprit behind the problem suddenly emerging out of nowhere. A fresh LUN with dedup was still fast. I guess it's only after a certain amount of blocks have been deduped, my lack of RAM to TrueNAS started kicking in.


I apologize for wasting your time!

**Comment by felix920506** [comment] 2024-02-23 14:22
Closing as it is a setup / config issue, not a Jellyfin issue.

**Comment by Marco3G** [comment] 2024-02-25 21:05
Can this be reopened? The "fix" was shortlived. Right now the VM resides on the ESXi host's main NVMe drive with both the root partition and the transcode volume and the two shows in question yet again take their sweet time to load...

**Comment by felix920506** [comment] 2024-02-25 21:09
Please head to our chat rooms or forum for troubleshooting help: https://jellyfin.org/contact

**Comment by Marco3G** [comment] 2024-02-25 21:11
As per my first post, I was sent here from the forums.

**Comment by Bond-009** [comment] 2024-06-06 09:02
Do you still have this issue on the latest release?

**Comment by Marco3G** [comment] 2024-06-06 12:54
No, I fixed this myself by deleting the VM and installing Emby instead. Had I known how much better Emby was on so many levels, I'd have done this much sooner.

Their support is actually helpful.

**Closed** 2024-06-06 13:33 UTC
Labels: bug

**Comment by SuyashDahale13** [comment] 2024-09-02 15:16
> Well, I've been sent here from this thread: https://forum.jellyfin.org/t-some-shows-suddenly-take-minutes-loading-playback
> 
> I have noticed two shows that are stuck on the loading screen for relatively precisely 90seconds before they start playing. Other shows seem fine. And the first few seasons of BBT worked normally and are still working normally.
> 
> Media Info for Clarkson's Farm:
> 
> Video Title: 404p H264 SDR Codec: H264 Codec tag: avc1 AVC: Yes Profile: High Level: 31 Resolution: 720x328 Aspect ratio: 240:109 Interlaced: No Framerate: 25 Bitrate: 1072 kbps Bit depth: 8 bit Video range: SDR Video range type: SDR Pixel format: yuv420p Ref frames: 1 NAL: 4
> 
> For Big Bang Theory that isn't working normally:
> 
> Video Title: 404p H264 SDR Codec: H264 Codec tag: avc1 AVC: Yes Profile: High Level: 31 Resolution: 720x404 Aspect ratio: 16:9 Interlaced: No Framerate: 23.976025 Bitrate: 693 kbps Bit depth: 8 bit Video range: SDR Video range type: SDR Color space: bt709 Pixel format: yuv420p Ref frames: 1 NAL: 4
> 
> BBT that is:
> 
> Video Title: 384p H264 SDR Codec: H264 AVC: Yes Profile: High Level: 40 Resolution: 640x368 Aspect ratio: 40:23 Interlaced: No Framerate: 23.976 Bitrate: 633 kbps Bit depth: 8 bit Video range: SDR Video range type: SDR Color space: smpte170m Color transfer: smpte170m Color primaries: smpte170m Pixel format: yuvj420p Ref frames: 1 NAL: 4
> 
> Here are the logs from the thread. https://pastebin.com/0drPm2bJ https://pastebin.com/ANhq4VTd https://pastebin.com/Af4qUkVG https://pastebin.com/sJdCUvu4 https://pastebin.com/UA1RM2h5 https://pastebin.com/buSw0tTn https://pastebin.com/wG6A4NRc
> 
> And after setting log level to Debug https://pastebin.com/e6mmQtEz https://pastebin.com/DHLziQWV
> 
> And here is a season 2 episode of BBT that starts immediately. https://pastebin.com/1Sw7gksr
> 
> Server System (please complete the following information):
> 
> * OS: Ubuntu 22.04
> * Jellyfin Version: 10.8.13
> * Hardware settings & device: [e.g. NVENC on Quadro P400
> * Reverse proxy: nginx
> * Other hardware notes: Kinda hyperconverged setup. The ESXi host contains the disks whose HBA is pci passthroughed to TrueNAS. The MEdia is then shared on NFS. The Jellyfin VM has its storage on an iSCSI datastore also from said truenas. 12 spindle ZFS behind media, 3stick NVMe behind datastore. Since all traffic is on the vSwitch, I expect 10G connectivity. There is a firewall between TrueNAS and Jellyfin.
> 
> **Client System (please complete the following information):**
> 
> * Device: Similar experience on two Windows 10 boxes and Firefox current as well as Android app on the phone, also current.
> * Also tried it on Edge. Same problem.
> 
> To check for filesize/bandwidth issues, I played T2 in 4k and it started in under 5 seconds.

Helllo there ! I am facing the exact same problem .... did you get the fix for this issue ? I am facing this issue only on my tv client desktop and android are fine

**Comment by Marco3G** [comment] 2024-09-03 04:39
As I wrote earlier, I am now using Emby. One of the better investments I've made in my life :D.
