### ISSUE TITLE
Series with period character in name not recognized.

### ISSUE THREAD

**Issue by ChaoticWyrme** [jellyfin/jellyfin#3716] opened 2020-07-26 20:45 UTC
**Describe the bug**
When a series name has a period in it, it is not recognized by Jellyfin. The series that caused this bug was Agents of SHIELD. I put it in a folder named "Agents of S.H.I.E.L.D./" and it would not be recognized no matter what I did. It could also be the trailing period.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Virtualization: None
 - Clients: Browser, Android, Roku
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: DirectPlay
 - Installed Plugins: Fanart, Anime, 
 - Reverse Proxy: nginx
 - Base URL: /jellyfin
 - Networking: LAN
 - Storage: local

**To Reproduce**

1.) Add a show folder to your library called "Agents of S.H.I.E.L.D"
2.) Try to get Jellyfin to recognize it. (Scan library etc).
3.) Change folder name to "Agents of SHIELD"
4.) Try again.

**Expected behavior**

For Jellyfin to recognize the canonical name of the show from TVDB, periods and all.

**Logs**
There was no log messages about this error, it seemed to just be ignored.

**Comment by oddstr13** [comment] 2020-07-26 21:08
Duplicate of #3635

**Closed** 2020-07-26 21:09 UTC
Labels: bug, duplicate
