### ISSUE TITLE
[Issue]: Language code "zh-CN" not being recognized correctly

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin#9285] opened 2023-02-09 06:14 UTC
### Please describe your bug

Issue:
\<filename\>.zh-CN.\<extension\> isn't being recognized properly

Steps to reproduce:
1. Upload media to Jellyfin Server with external subtitles renamed to \<filename\>.zh-CN.\<extension\>
2. Refresh Metadata
3. Open Subtitle dropdown to see results

Expected Behavior:
Subtitles be recognized as Chinese or Simplified Chinese

Actual Behavior:
Subtitles language isn't being recognized

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Unraid
- Virtualization: Docker
- Clients: Web, Swiftfin
- Browser: Firefox
- FFmpeg Version: 5.1.2
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: AniDB
- Reverse Proxy: None
- Base URL: None
- Networking: NAT
- Storage: Local
```

### Please attach any screenshots here

What is being shown:
![image](https://user-images.githubusercontent.com/25688628/217731745-9e06f6b1-eecf-4d54-a760-97b82b0df737.png)

Files uploaded:
![image](https://user-images.githubusercontent.com/25688628/217732627-3d691f6c-6bbc-41e1-a764-fbb9bcf2d12a.png)

the .mkv container does NOT contain subtitles

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2023-02-09 06:17
Translation of menu items in the first screenshot:
- Off
- zh-CN - Not Defined - ASS - External
- Chi - ASS - External

**Comment by Bond-009** [comment] 2023-02-09 11:16
Duplicate of #6302

**Closed by Bond-009** 2023-02-09 11:16 UTC
Labels: bug
