### ISSUE TITLE
Changes to plugin settings will not save

### ISSUE THREAD

**Issue by esmondmissen** [jellyfin/jellyfin#3753] opened 2020-07-30 13:10 UTC
**Describe the bug**
Settings are not being posted correctly for plugins. When I select to enable something it doesn't save correctly. There are no errors in the console but looking at the post the information looks incorrect. The post to the endpoint looks like:

Request URL: https://myserver/Plugins/a629c0da-fac5-4c7e-931a-7174223f14c8/Configuration
`{"Enable":false,"ReplaceAlbumName":false}`

This is what is posted to the server when trying to enable the plugin (successfully).

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: None
 - Clients: Browser
 - Browser: Edge 84.0.522.49 , Safari 13.1.2
 - Jellyfin Version: 10.6.0 Stable
 - Playback: n/a
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: not sure...
 - Storage: local

**To Reproduce**

1. Go to 'Plugins'
2. Click on 'Settings' for 'AudioDB ' (It can be any. This happens to all of them, all are switch off by default it seems)
3. Check 'Enable this provider for metadata searches on artists and albums.'
4. Click on 'Save' - You will get a message 'Settings Saved'
5. Go back to 'Plugins'
6. Click on 'Settings' for 'AudioDB'
7. Note  'Enable this provider for metadata searches on artists and albums.' is unchecked

**Expected behavior**
Expect it to save plugin settings

**Comment by crobibero** [comment] 2020-07-30 13:11
Dupe of #3739

**Closed by crobibero** 2020-07-30 13:11 UTC
Labels: bug

**Comment by esmondmissen** [comment] 2020-07-30 20:31
Ah sorry. I did have a look. Clearly just not well enough.
