### ISSUE TITLE
[Issue]: wrong actor displaying

### ISSUE THREAD

**Issue by G2G2G2G** [jellyfin/jellyfin#9035] opened 2023-01-07 22:56 UTC
### Please describe your bug

People have the same name, Jellyfin doesn't seem to know that

https://www.imdb.com/name/nm0048934/
https://www.imdb.com/name/nm0048932/

depending on which person's movies you scrape first, they take over all of the other movies. The second person with the same name never gets scraped.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-01-07 23:10
Duplicate of https://github.com/jellyfin/jellyfin/issues/3356

**Closed by crobibero** 2023-01-07 23:10 UTC
Labels: bug
