### ISSUE TITLE
Can't start the 10.7.5 jellyfin server - docker

### ISSUE THREAD

**Issue by Gopikrishna19** [jellyfin/jellyfin#6129] opened 2021-05-30 04:17 UTC
**Describe the bug**
I am not able to start the jellyfin server at all using all three (Linux server/hotio/jellyfin) versions of docker image

**System (please complete the following information):**
 - OS: CentOS 7
 - Virtualization: Docker
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.7.5
 - Playback: 
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: yes
 - Networking: Bridge/NAT
 - Storage: NFS

**To Reproduce**
```
docker run -v /media-metadata:/config -p 8096:8096 -e JELLYFIN_PublishedServerUrl=http://jellyfin.lan.net jellyfin/jellyfin
```

**Expected behavior**
GUI to show up

**Server Logs**
```log
[04:12:33] [INF] [1] Main: Jellyfin version: 10.7.5
[04:12:33] [INF] [1] Main: Environment Variables: ["[JELLYFIN_PublishedServerUrl, http://jellyfin.rg-10.hm]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_PORT, tcp://172.16.200.58:8096]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_PORT_8096_TCP_PROTO, tcp]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_SERVICE_HOST, 172.16.200.58]", "[JELLYFIN_PORT_8096_TCP_ADDR, 172.16.200.58]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_PORT_8096_TCP_PORT, 8096]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_PORT_8096_TCP, tcp://172.16.200.58:8096]", "[JELLYFIN_SERVICE_PORT, 8096]", "[JELLYFIN_SERVICE_PORT_HTTP, 8096]"]
[04:12:33] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[04:12:33] [INF] [1] Main: Operating system: Linux
[04:12:33] [INF] [1] Main: Architecture: X64
[04:12:33] [INF] [1] Main: 64-Bit Process: True
[04:12:33] [INF] [1] Main: User Interactive: True
[04:12:33] [INF] [1] Main: Processor count: 4
[04:12:33] [INF] [1] Main: Program data path: /config
[04:12:33] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[04:12:33] [INF] [1] Main: Application directory: /jellyfin/
[04:12:35] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[04:12:37] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[04:12:37] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[04:12:37] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[04:12:37] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[04:12:37] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[04:12:37] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[04:12:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.5.0
[04:12:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.5.0
[04:12:38] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.5.0
[04:12:38] [INF] [1] Main: Kestrel listening on Any IP4 Address
[04:12:38] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {ecac9c79-443c-403d-95ad-bbc82220e483} may be persisted to storage in unencrypted form.
[04:12:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[04:12:38] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 05/31/2021 02:00, which is 21:47:21.2535116 from now.
[04:12:38] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 4.3.2
[04:12:38] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[04:12:38] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[04:12:38] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[04:12:38] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: /usr/lib/jellyfin-ffmpeg/ffmpeg
[04:12:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: 5841683c51984aeaae7e22830496241f
[04:12:38] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.16.124.161/32
[04:12:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0909728
[04:12:38] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[04:12:41] [ERR] [1] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error creating recording folders
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(IStatement statement)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren()
   at MediaBrowser.Controller.Entities.Folder.LoadChildren()
   at MediaBrowser.Controller.Entities.UserRootFolder.LoadChildren()
   at MediaBrowser.Controller.Entities.Folder.get_Children()
   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders(Boolean includeRefreshState)
   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders()
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.CreateRecordingFolders()
[04:12:41] [FTL] [1] Main: Error while starting server.
IOError: SQLitePCL.pretty.SQLiteException: disk I/O error
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteExtensions.ExecuteQuery(IStatement statement)+MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetCachedChildren()
   at MediaBrowser.Controller.Entities.Folder.LoadChildren()
   at MediaBrowser.Controller.Entities.UserRootFolder.LoadChildren()
   at MediaBrowser.Controller.Entities.Folder.get_Children()
   at Emby.Server.Implementations.Library.LibraryManager.GetCollectionFolders(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.GetLibraryOptions(BaseItem item)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType)
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateRootFolder()
   at Emby.Server.Implementations.Library.LibraryManager.get_RootFolder()
   at Emby.Server.Implementations.IO.LibraryMonitor.Start()
   at Emby.Server.Implementations.IO.LibraryMonitorStartup.RunAsync()
   at Emby.Server.Implementations.ApplicationHost.StartEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup)+MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing LibraryMonitorStartup
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing ExternalPortForwarding
[04:12:41] [INF] [1] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing LibraryChangedNotifier
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing RecordingNotifier
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing UdpServerEntryPoint
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing UserDataChangeNotifier
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing DlnaEntryPoint
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpDevicePublisher
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Disposing PlayToManager
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing _BroadcastListenSocket
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer Disposing 2 sendSockets
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 0.0.0.0
[04:12:41] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 172.16.124.161
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing NotificationEntryPoint
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint
[04:12:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing DeviceAccessEntryPoint
[04:12:41] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**
It used to work with 10.6.4-1-ls98, but after my server reboot, everything stopped working. Updated to the newer version with no luck. I stuck 10.6.4-1-ls98 because of "Add server" screen instead of the setup wizard. Then I figured I could add the `JELLYFIN_PublishedServerUrl` option to get through that. But still no luck. Please help! TIA!!

**Comment by crobibero** [comment] 2021-05-30 04:50
To me it looks like either a permissions error or you’re out of space

**Comment by Gopikrishna19** [comment] 2021-05-30 05:06
@crobibero I have a 10TB drive so space is not a problem. The permissions are set to 1000:1000 based on the linuxserver recommendations. Is there a specific UID/GID I should be using?

**Comment by Gopikrishna19** [comment] 2021-05-31 16:58
Any updates on this? There is no documentation on setting permissions for SQLite database that I can find. Can someone please point me in the correct direction?

**Comment by jmeacoe** [comment] 2021-05-31 17:35
As per the linuxserver dockerhub documentation:

User / Group Identifiers
When using volumes (-v flags) permissions issues can arise between the host OS and the container, we avoid this issue by allowing you to specify the user PUID and group PGID.

Ensure any volume directories on the host are owned by the same user you specify and any permissions issues will vanish like magic.

In this instance PUID=1000 and PGID=1000, to find yours use id user as below:

  $ id username
    uid=1000(dockeruser) gid=1000(dockergroup) groups=1000(dockergroup)

**Comment by Gopikrishna19** [comment] 2021-05-31 18:37
I do have those:
```
root@vault:/export/applications/media-metadata/data# ls -al
total 360
drwxrw-r--  8 1000 1000   4096 May 29 23:29 .
drwxrw-r-- 10 1000 1000   4096 May 29 23:29 ..
-rwxrw-r--  1 1000 1000  28672 May 29 23:28 authentication.db
-rwxrw-r--  1 1000 1000      0 May 29 23:28 authentication.db-journal
drwxrw-r--  4 1000 1000   4096 May 30 00:10 data
-rwxrw-r--  1 1000 1000     35 May 29 23:08 device.txt
-rwxrw-r--  1 1000 1000 122880 May 29 23:08 jellyfin.db
-rwxrw-r--  1 1000 1000 180224 May 29 23:28 library.db
-rwxrw-r--  1 1000 1000      0 May 29 23:28 library.db-journal
drwxrw-r--  2 1000 1000   4096 May 29 23:28 metadata
drwxrw-r--  2 1000 1000   4096 May 29 23:08 playlists
drwxrw-r--  3 1000 1000   4096 May 29 23:29 plugins
drwxrw-r--  3 1000 1000   4096 May 29 23:29 root
drwxrw-r--  2 1000 1000   4096 May 29 23:28 transcodes
```

**Comment by jmeacoe** [comment] 2021-05-31 19:14
It isn't part of the docker run command you provided, I'd also suggest adding the timezone environment variable:
docker run -v /media-metadata:/config -p 8096:8096 -e JELLYFIN_PublishedServerUrl=http://jellyfin.lan.net jellyfin/jellyfin \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London

**Comment by konradbjk** [comment] 2021-06-01 11:57
I have a similar issue. If you check in your folders, you have exact replica of `/config/data` in `/config/data/data`. In my case, the server starts but it goes into the getting started guide and no data is read.

**Comment by Gopikrishna19** [comment] 2021-06-01 12:19
@jmeacoe I have everything setup per documentation. I just didn't put it in the issue above for simplicity's sake. It used to work. Now it's not working. Neither the 10.6.4 that I pinned the version to, nor the latest 10.7.5. I tried wiping the metadata folder several times without success.

@konradbjk thanks for bringing that up. That happened to me few times well. I was so happy that it started up. Didn't go to ”Add Server” screen, went straight to wizard. Selected all the media but nothing was indexed. Looking at the log ~it's the same SQLite errors.~

Everything was working perfectly. All I did was added RAM to my server and created a new vm node, ran the `docker-compose up` again and everything started falling apart.

Even before I had to back down from the latest at that time to 10.6.4 to avoid the “Add Server” screen.

I believe it has something to do with the SQLite itself. Is that installed during image build time or runtime? May be the version is not pinned and it's getting installed at run time? That's why is not working after a new docker pull?

**Comment by Gopikrishna19** [comment] 2021-06-01 12:23
@jmeacoe here's my compose:

```
version: "3"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/Applications/metadata:/config
      - /mnt/Media:/Media
    ports:
      - 8096:8096
    restart: always

  nginx:
    depends_on:
      - jellyfin
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always
```

I use `fstab` to mount media and applications onto the node.

**Comment by agilob** [comment] 2021-06-02 16:54
[linuxserver](https://fleet.linuxserver.io/image?name=linuxserver/jellyfin) doesn't say anything how to use PUID and PGID for jellyfin, it does for dozens of other images, but not for jellyfin. I use the following config without any problems:

```
version: "3.3"

services:
  jellyfin:
    image: jellyfin/jellyfin:10.7.5
    container_name: jellyfin
    network_mode: host
    user: "$UID:$GID"
    volumes:
      - $HOME/dockers/jellyfin/cache:/cache
      - $HOME/dockers/jellyfin:/config
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    restart: unless-stopped
```

**Comment by Gopikrishna19** [comment] 2021-06-05 12:20
@agilob what is the value of uid and gid here? And aren't you mounting cache inside config as well? Is that how it is supposed to be done? What is the device mount for? Can you please explain your setup, so I know what I'm doing?

**Comment by Gopikrishna19** [comment] 2021-06-05 12:22
The official jellyfin/jellyfin doesn't seem have anything mentioned on permissions either. I also tried the hotio version, but ended up with same SQLite problem.

**Comment by excelite** [comment] 2021-06-05 12:24
if the compose file is exactly as you wrote it, you have the wrong path specified

should be something like this:
`/export/applications/media-metadata/data:/config`

**Comment by Gopikrishna19** [comment] 2021-06-05 19:56
How is yours different than mine? I just have different host path. Can you please elaborate?

**Comment by excelite** [comment] 2021-06-05 20:17
the directory listing you showed off
```
root@vault:/export/applications/media-metadata/data# ls -al
```
suggests that your data resides in
```
/export/applications/media-metadata
```

from your docker-compose you mount the host directory
```
/mnt/Applications/metadata:/config
```
to your docker container

if this is not correct, the config directory inside the container is owned by root and therefore jellyfin has no write permissions and can not access the folder and errors out like in the log you provided.

what is the content of the host folder? (/mnt/Applications/metadata)

this is definitely either a configuration issue in your docker-compose or a simple permissions issue, not a bug in jellyfin

**Comment by Gopikrishna19** [comment] 2021-06-05 22:01
I don't want to sound rude, but these are all just semantics and doesn't solve my problem: the SQLite errors. The docker-compose has it a bit different than what I have in local. I was not at my system when I posted that, and I quickly grabbed what was in my repo. I updated it to reflect what's in my local now Any other suggestions, please?

**Comment by excelite** [comment] 2021-06-05 22:22
you need to use the ones from the user that ownes the folder... afaik the linuxserver image adjusts the permissions inside the container according to the ones you provide.

since you use the linuxserver image you might want to head over to their discord/slack and have them help you since they have deeper knowledge on how the image was customized.

**Comment by agilob** [comment] 2021-06-06 19:35
>@agilob what is the value of uid and gid here

whatever your final ID is, in my case it's 1000:1000

**Comment by Gopikrishna19** [comment] 2021-06-07 02:01
There is a problem with NFS and SQLite itself.  https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible

@Jellyfin people, if you could support MySQL or MariaDB, it would be great. I switched to a locally maintained metadata volume, which is ephemeral to the lifetime of the node. Even though I don't like it, that's what works. There seem to be more and more issues opened in relation to this.

I will watch the repo issues and this thread to see if there are any updates. Till then, thanks for all the support!

**Comment by crobibero** [comment] 2021-06-07 02:20
>  if you could support MySQL or MariaDB

https://features.jellyfin.org/posts/315/mysql-server-back-end

**Comment by Gopikrishna19** [comment] 2021-06-07 03:01
That's fantastic!! Is it available yet? Can I have a link to the documentation please?

**Comment by crobibero** [comment] 2021-06-07 03:12
> That's fantastic!! Is it available yet? Can I have a link to the documentation please? I don't see any in the official website.

I linked an open feature request. When the feature is implemented the feature request will be closed. The database we inherited is not yet ready to be used with something other then SQLite.

**Comment by Bond-009** [comment] 2022-01-04 18:18
This isn't an issue tracking db support, closing as the original problem is solved

**Closed by Bond-009** 2022-01-04 18:18 UTC
Labels: bug
