### ISSUE TITLE
[Issue]: SyncPlay ends abruptly after a few seconds

### ISSUE THREAD

**Issue by devpatf** [jellyfin/jellyfin#11644] opened 2024-05-14 21:17 UTC
### Please describe your bug

If you start a movie using SyncPlay, all clients will get thrown back to the home page a 20-30 seconds after you have started a movie.

Client throws this error:
```
19907.e62d83da29a53bc4bba9.chunk.js:2 Error while waiting for `playbackstart` event! startPlayback Timed out.
```

### Reproduction Steps

1. Create a SyncGroup with Browser#1
2. Join the SyncGroup with Browser#2
3. Play any movie or show
4. Wait 20-30 seconds

### Jellyfin Version

10.9.1

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel: 6.8.0-31
- Clients: Web
- Browser: Brave / Chromium
- FFmpeg Version: 6.1.1-3ubuntu5
```

### Jellyfin logs

```shell
/home/SOME_USER/Projects/jellyfin/Jellyfin.Server/bin/Debug/net8.0/jellyfin --webdir /home/SOME_USER/Projects/jellyfin-web/dist
[23:03:20] [INF] [1] Main: Jellyfin version: 10.9.1
[23:03:20] [INF] [1] Main: Environment Variables: ["[ASPNETCORE_ENVIRONMENT, Development]", "[ASPNETCORE_URLS, http://localhost:8096]", "[DOTNET_MODIFIABLE_ASSEMBLIES, debug]", "[JELLYFIN_LOG_DIR, /home/SOME_USER/.local/share/jellyfin/log]", "[DOTNET_ROOT, /usr/lib/dotnet]", "[DOTNET_HOTRELOAD_NAMEDPIPE_NAME, 969b5ecc-2e7f-4350-aa7f-bb058f47a954]"]
[23:03:20] [INF] [1] Main: Arguments: ["/home/SOME_USER/Projects/jellyfin/Jellyfin.Server/bin/Debug/net8.0/jellyfin.dll", "--webdir", "/home/SOME_USER/Projects/jellyfin-web/dist"]
[23:03:20] [INF] [1] Main: Operating system: Ubuntu 24.04 LTS
[23:03:20] [INF] [1] Main: Architecture: X64
[23:03:20] [INF] [1] Main: 64-Bit Process: True
[23:03:20] [INF] [1] Main: User Interactive: True
[23:03:20] [INF] [1] Main: Processor count: 24
[23:03:20] [INF] [1] Main: Program data path: /home/SOME_USER/.local/share/jellyfin
[23:03:20] [INF] [1] Main: Log directory path: /home/SOME_USER/.local/share/jellyfin/log
[23:03:20] [INF] [1] Main: Config directory path: /home/SOME_USER/.config/jellyfin
[23:03:20] [INF] [1] Main: Cache path: /home/SOME_USER/.cache/jellyfin
[23:03:20] [INF] [1] Main: Web resources path: /home/SOME_USER/Projects/jellyfin-web/dist
[23:03:20] [INF] [1] Main: Application directory: /home/SOME_USER/Projects/jellyfin/Jellyfin.Server/bin/Debug/net8.0/
[23:03:20] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /home/SOME_USER/.cache/jellyfin
[23:03:20] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["127.0.0.1", "192.168.188.24", "172.18.0.1", "10.8.0.2"]
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[23:03:20] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[23:03:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.1.0
[23:03:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.1.0
[23:03:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.1.0
[23:03:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.1.0
[23:03:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.1.0
[23:03:21] [INF] [1] Main: Kestrel is listening on 127.0.0.1
[23:03:21] [WRN] [1] Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer: The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
[23:03:21] [INF] [1] Main: Kestrel is listening on 192.168.188.24
[23:03:21] [INF] [1] Main: Kestrel is listening on 172.18.0.1
[23:03:21] [INF] [1] Main: Kestrel is listening on 10.8.0.2
[23:03:21] [WRN] [1] Microsoft.AspNetCore.Server.Kestrel: Overriding address(es) 'http://localhost:8096'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
[23:03:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[23:03:21] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /home/SOME_USER/storage/shows
[23:03:21] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Generate Trickplay Images set to fire at 2024-05-15 03:00:00.000 +02:00, which is 03:56:38.1242332 from now.
[23:03:21] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2024-05-15 02:00:00.000 +02:00, which is 02:56:38.1219199 from now.
[23:03:21] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 6.1.1
[23:03:21] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[23:03:22] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_vaapi", "libx264", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[23:03:22] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale"]
[23:03:22] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: tonemap_cuda with option GPU accelerated HDR to SDR tonemapping is not available
[23:03:22] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[23:03:22] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: ffmpeg
[23:03:22] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: df20b2029aa54bddb9824e763c40204d
[23:03:22] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[23:03:22] [INF] [1] Main: Startup complete 0:00:02.6499185
[23:03:23] [INF] [26] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 127.0.0.1 request
[23:03:24] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean up collections and playlists Completed after 0 minute(s) and 0 seconds
[23:03:25] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[23:03:26] [INF] [6] Emby.Server.Implementations.SyncPlay.Group: Session 8f520564083fdf3d30d1a9b9d0a62653 created group e1b14fc1-ac0f-490c-af0c-e6db219b85ae.
[23:03:41] [INF] [29] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for SOME_USER has succeeded.
[23:03:41] [INF] [29] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user SOME_USER: 1/0
[23:03:41] [INF] [29] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user f05a1b28-b565-4264-82a4-4a62d4d0833f
[23:03:41] [INF] [22] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 127.0.0.1 request
[23:03:45] [INF] [29] Emby.Server.Implementations.SyncPlay.Group: Session 4f2656ed2b043da3384e5eb433d16c01 joined group e1b14fc1-ac0f-490c-af0c-e6db219b85ae.
[23:03:53] [INF] [17] Emby.Server.Implementations.SyncPlay.Group: Session 4f2656ed2b043da3384e5eb433d16c01 requested Play in group e1b14fc1-ac0f-490c-af0c-e6db219b85ae that is Idle.
[23:03:53] [INF] [17] Emby.Server.Implementations.SyncPlay.Group: Group e1b14fc1-ac0f-490c-af0c-e6db219b85ae switching from Idle to Waiting.
[23:03:53] [INF] [26] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for SOME_USER. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[23:03:53] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for SOME_USER. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[23:03:54] [INF] [29] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[23:03:54] [INF] [6] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[23:03:54] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"/home/SOME_USER/storage/movies/Some.Movie.Folder/Some.Movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "4e068d9306278999b50ec249ad957c43-1.mp4" -start_number 0 -hls_segment_filename "/home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43.m3u8"
[23:03:54] [INF] [6] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"/home/SOME_USER/storage/movies/Some.Movie.Folder/Some.Movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "65f541594781de37b4d6e381828e9396-1.mp4" -start_number 0 -hls_segment_filename "/home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396.m3u8"
[23:03:54] [INF] [29] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43.m3u8
[23:03:54] [INF] [6] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396.m3u8
[23:03:54] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[23:03:54] [INF] [6] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[23:03:54] [INF] [29] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[23:03:54] [INF] [6] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[23:03:54] [INF] [6] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: ffmpeg -analyzeduration 200M -probesize 1G -ss 00:10:24.625 -noaccurate_seek -fflags +genpts  -i file:"/home/SOME_USER/storage/movies/Some.Movie.Folder/Some.Movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "65f541594781de37b4d6e381828e9396-1.mp4" -start_number 104 -hls_segment_filename "/home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396.m3u8"
[23:03:54] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: ffmpeg -analyzeduration 200M -probesize 1G -ss 00:10:24.625 -noaccurate_seek -fflags +genpts  -i file:"/home/SOME_USER/storage/movies/Some.Movie.Folder/Some.Movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "4e068d9306278999b50ec249ad957c43-1.mp4" -start_number 104 -hls_segment_filename "/home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43.m3u8"
[23:04:14] [INF] [34] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[23:04:14] [INF] [23] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[23:04:24] [INF] [33] Emby.Server.Implementations.SyncPlay.Group: Session 8f520564083fdf3d30d1a9b9d0a62653 requested IgnoreWait in group e1b14fc1-ac0f-490c-af0c-e6db219b85ae that is Waiting.
[23:04:24] [INF] [23] Emby.Server.Implementations.SyncPlay.Group: Session 4f2656ed2b043da3384e5eb433d16c01 requested IgnoreWait in group e1b14fc1-ac0f-490c-af0c-e6db219b85ae that is Waiting.
[23:04:24] [INF] [23] Emby.Server.Implementations.SyncPlay.Group: Group e1b14fc1-ac0f-490c-af0c-e6db219b85ae switching from Waiting to Playing.
[23:04:24] [INF] [29] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /home/SOME_USER/.cache/jellyfin/transcodes/65f541594781de37b4d6e381828e9396.m3u8
[23:04:24] [INF] [34] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /home/SOME_USER/.cache/jellyfin/transcodes/4e068d9306278999b50ec249ad957c43.m3u8
[23:04:26] [INF] [29] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.9.1 playing Some Movie. Stopped at 655425 ms
[23:04:26] [INF] [27] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.9.1 playing Some Movie. Stopped at 655075 ms
[23:04:27] [INF] [33] Emby.Server.Implementations.SyncPlay.Group: Session 4f2656ed2b043da3384e5eb433d16c01 left group e1b14fc1-ac0f-490c-af0c-e6db219b85ae.
[23:04:27] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 127.0.0.1 closed
[23:04:28] [INF] [42] Emby.Server.Implementations.SyncPlay.Group: Session 8f520564083fdf3d30d1a9b9d0a62653 left group e1b14fc1-ac0f-490c-af0c-e6db219b85ae.
[23:04:28] [INF] [42] Emby.Server.Implementations.SyncPlay.SyncPlayManager: Group e1b14fc1-ac0f-490c-af0c-e6db219b85ae is empty, removing it.
[23:04:28] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 127.0.0.1 closed
```

### Please attach any browser or client logs here

```
Requesting url without automatic networking: http://127.0.0.1:8096/SyncPlay/Join
2node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/GetUTCTime
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CPath%2CMediaSourceCount&UserId=f05a1b28b565426482a44a62d4d0833f&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-05-15T21%3A10%3A06.329Z&EnableResumable=false&EnableRewatching=false
2node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/GetUTCTime
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Sending web socket message: KeepAlive
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/213d264f0c78ab6bbd0903404835a3ad
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/SyncPlay/SetNewQueue
2node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/213d264f0c78ab6bbd0903404835a3ad
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/Items/213d264f0c78ab6bbd0903404835a3ad/PlaybackInfo?UserId=f05a1b28b565426482a44a62d4d0833f&StartTimeTicks=7017723030&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=2147483647
main.jellyfin.bundle.js?1ac25c71606cfb90d76c:2 HLS Error: Type: otherError Details: internalException Fatal: false
(anonymous) @ main.jellyfin.bundle.js?1ac25c71606cfb90d76c:2
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/Sessions/Playing
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/System/Configuration/encoding
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 WebAssembly support detected: yes
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
i.createCanvas @ node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 resetting prerender cache
3node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 worker busy, requesting to seek
subtitles-octopus-worker.js:1 warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available.
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 worker busy, requesting to seek
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Sending web socket message: KeepAlive
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 worker busy, requesting to seek
subtitles-octopus-worker.js:1 jso: setting total libass memory limits to: glyph=40 MiB, bitmap cache=40 MiB
node_modules.@jellyfin.libass-wasm.83cb3fa930a5537f2bd3.chunk.js:1 worker busy, requesting to seek
2node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/Sessions/Playing/Progress
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/GetUTCTime
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/Sessions/Playing/Progress
19907.e62d83da29a53bc4bba9.chunk.js:2 Error while waiting for `playbackstart` event! startPlayback Timed out.
(anonymous) @ 19907.e62d83da29a53bc4bba9.chunk.js:2
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/SyncPlay/SetIgnoreWait
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting url without automatic networking: http://127.0.0.1:8096/Sessions/Playing/Stopped
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CPath%2CMediaSourceCount&UserId=f05a1b28b565426482a44a62d4d0833f&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-05-15T21%3A11%3A21.397Z&EnableResumable=false&EnableRewatching=false
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Sending web socket message: KeepAlive
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Users/f05a1b28b565426482a44a62d4d0833f/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CPath%2CMediaSourceCount&UserId=f05a1b28b565426482a44a62d4d0833f&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2023-05-15T21%3A11%3A34.352Z&EnableResumable=false&EnableRewatching=false
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Sending web socket message: KeepAlive
node_modules.jellyfin-apiclient.bundle.js?1ac25c71606cfb90d76c:2 Requesting http://127.0.0.1:8096/GetUTCTime
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2024-05-14 21:56
duplicate of https://github.com/jellyfin/jellyfin-web/issues/5485

**Closed by felix920506** 2024-05-14 21:56 UTC
Labels: bug
