### ISSUE TITLE
Playback stops with 'corrupted' streams

### ISSUE THREAD

**Issue by NachoBB** [jellyfin/jellyfin#10621] opened 2023-11-24 08:54 UTC
I have found resilience problems with streams that are not very clean. This can be verified at this URL

https://rakuten-actionmovies-2-es.samsung.wurl.tv/3000.m3u8

When an ad break occurs, playback is interrupted.

> [https @ 0x557d132e8700] Opening 'https://rakuten-actionmovies-2-es.samsung.wurl.tv/3000.m3u8' for reading
> [hls @ 0x557d12ca1a80] Skip ('#EXT-X-VERSION:3')
> [hls @ 0x557d12ca1a80] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:4250')
> [hls @ 0x557d12ca1a80] Skip ('#EXT-X-CUE-OUT-CONT:ElapsedTime=108,Duration=121,SCTE35=WURL1700734509')
> [hls @ 0x557d12ca1a80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-11-24T08:38:03.589400294Z')
> [hls @ 0x557d12ca1a80] Skip ('#EXT-X-CUE-OUT-CONT:ElapsedTime=114,Duration=121,SCTE35=WURL1700734509')
> [hls@0x557d12ca1a80] Skip('#EXT-X-CUE-IN')
> [hls@0x557d12ca1a80] Skip('#EXT-X-DISCONTINUITY')
> [hls @ 0x557d12ca1a80] Opening 'crypto+https://rakuten-actionmovies-2-es.samsung.wurl.tv/135/415148/126295702/3fadebaf792a566773356160ccd39226/hls-v2/3000-00004.ts?e=1 700816014&st=ea2c8bbf950f824be61bc3ad647cb0b4 'for reading
> [hls @ 0x557d131131c0] Non-monotonous DTS in output stream 0:0; previous: 8095387200, current: 8086113152; changing to 8095387201. This may result in incorrect timestamps in the output file.
> 
> 
> [q] command received. Exiting.
> 
> [hls @ 0x557d131131c0] Opening '/config/data/transcodes/6d89667894b9a9768f0371b18b92646f187.ts' for writing
> [hls @ 0x557d131131c0] Opening '/config/data/transcodes/6d89667894b9a9768f0371b18b92646f.m3u8.tmp' for writing
> frame=11545 fps= 26 q=-1.0 Lsize=N/A time=24:59:08.66 bitrate=N/A speed= 200x
> video:161958kB audio:7314kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> 

This does not happen if the stream goes through an IPTV proxy (in this case Stream Master)

Perhaps the problem would be solved by adding +discardcorrupt to the ffmpeg transcoding. Is there any possibility to do this if using Docker distribution?

**Comment by GodBleak** [comment] 2023-11-25 21:00
Seems like a duplicate of jellyfin/jellyfin-ffmpeg#57

**Comment by sevenrats** [comment] 2023-11-27 16:52
Ffmpeg does not support EXT-X-DISCONTINUITY and streams that rely on it will not work with jellyfin.  Merging support for it might be possible downstream but this is a feature request, not a bug report.

**Closed by sevenrats** 2023-11-27 16:52 UTC
