### ISSUE TITLE
Jellyfin stopped launching after 10.10.2 update when using read only library directories

### ISSUE THREAD

**Issue by lukaszsobala** [jellyfin/jellyfin#13057] opened 2024-11-17 10:06 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading from 10.10.1 to 10.10.2, jellyfin stopped launching because of an "exception" - read only directory. When I changed the mount point from `ro` to `rw` in `/etc/fstab`, it started working again.
But I do not think it should be necessary to have the libraries in a folder with read/write permissions for jellyfin. 

### Reproduction steps

1. Have libraries in a read only directory
2. `apt upgrade` from 10.10.1 to 10.10.2
3. Try starting jellyfin

### What is the current _bug_ behavior?

Jellyfin service fails to start

### What is the expected _correct_ behavior?

Jellyfin service starts

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.2

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel: 6.1.0-1025-rockchip
- Hardware Acceleration: rkmpp
- GPU Model: Mali-G610
- Networking: ethernet
- Storage: library is on a samba share
```

### Jellyfin logs

```shell
Nov 17 10:09:17 rock5b jellyfin[7269]: System.IO.IOException: Read-only file system : '/mnt/samba_jellyfin/path/redacted/file.m3u'
```

### FFmpeg logs

```shell

```

**Comment by Err0r0815** [comment] 2024-11-17 10:58
Same Problem here but with Docker.
I have mounted multiple volumes mounted and only the volumes with the m3u Files generating the error.
All other volumes could be RO and the server is starting after RW the "m3u volume".

hope this helps.

Greeting

**Comment by lukaszsobala** [comment] 2024-11-17 11:15
Yes, I also just noticed the error is thrown when it encounters an m3u file. But I do not have the option to have different permissions unless I make the setup needlessly complicated.

**Comment by fuzxi** [comment] 2024-11-17 11:32
I had the same issue. Might be worth noting that simply deleting all the .m3u files on the read-only volume does not resolve this; Jellyfin will still refuse to start. I had to move or delete all .m3u files and mount the volume as read-write until Jellyfin completed startup once, then I could mount it as read-only again.

**Comment by Shadowghost** [comment] 2024-11-17 11:55
If anyone could try with the above linked PR and check if it fixes the issue I'd be grateful.

**Comment by thornbill** [comment] 2024-11-17 15:08
Closing as a duplicate of https://github.com/jellyfin/jellyfin/issues/13048

**Closed by thornbill** 2024-11-17 15:08 UTC
Labels: bug
