### ISSUE TITLE
[Issue]: Unable to fetch metadata for books

### ISSUE THREAD

**Issue by akashrajum7** [jellyfin/jellyfin#7400] opened 2022-03-05 04:28 UTC
### Please describe your bug

I am unable to fetch metadata for books, which was working fine on version 10.7.7, please let me know if I can help with anything else.

### Jellyfin Version

Other

### if other:

10.8.0 Alpha 5

### Environment

```markdown
- OS: Debian
- FFmpeg Version: 4.1.8
```

### Jellyfin logs

```shell
[06:14:16] [ERR] [13] MediaBrowser.Providers.Books.AudioBookMetadataService: Err
or in ffprobe
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Double value)
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.GetMediaStream(Boolean isAudio, MediaStreamInfo streamInfo, MediaFormatInfo formatInfo)
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.<>c__DisplayClass10_0.<GetMediaInfo>b__0(MediaStreamInfo s)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at MediaBrowser.MediaEncoding.Probing.ProbeResultNormalizer.GetMediaInfo(InternalMediaInfoResult data, Nullable`1 videoType, Boolean isAudio, String path, MediaProtocol protocol)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-03-05 04:58
Duplicate of https://github.com/jellyfin/jellyfin/issues/7355

Should be fixed in unstable build.

**Closed by crobibero** 2022-03-05 04:58 UTC
Labels: bug
