### ISSUE TITLE
Embeded subtitles doesn't work

### ISSUE THREAD

**Issue by Gunnm18** [jellyfin/jellyfin#4823] opened 2020-12-19 10:37 UTC
Hello,
For some reason, I can have the subtitles on almost all of my MKV with embeded subtitles. I can have them properly with Plex or VLC for example.
Nothing's showing up with Jellyfin.

When I have a mkv file +  a separated srt file, it goes like a charm.

I have added two examples of embedded subtitles, it gets stuck with "Fetching additionnal data".

**Testing condition**
_OS :_ Windows Server 2019
_JellyFin version :_ 10.6.4
_Viewing test :_ Web browser (Chrome 85 macOS Catalina) KO, Android App 2.2.3 KO, FireTV KO as well.

[ffmpeg-directstream-0892faba-95b3-4eb3-9ff2-7d2e84df0f04.txt](https://github.com/jellyfin/jellyfin/files/5719213/ffmpeg-directstream-0892faba-95b3-4eb3-9ff2-7d2e84df0f04.txt)
[ffmpeg-directstream-4135a1d5-566a-41e6-8fce-3ed5b5fff589.txt](https://github.com/jellyfin/jellyfin/files/5719214/ffmpeg-directstream-4135a1d5-566a-41e6-8fce-3ed5b5fff589.txt)
[log_20201219.log](https://github.com/jellyfin/jellyfin/files/5719215/log_20201219.log)

**Comment by Jhyrachy** [comment] 2020-12-19 16:10
Had the same problem: https://github.com/jellyfin/jellyfin-web/issues/2057

Check if with a client works

**Comment by Gunnm18** [comment] 2020-12-19 17:16
Doesn't work on:
- web browser
- android app
- ios app
- fire tv

About 9 on 10 mkv are not working.

**Comment by cvium** [comment] 2021-04-09 12:43
Duplicate of 3730 I think

**Closed by cvium** 2021-04-09 12:43 UTC
