### ISSUE TITLE
Jellyfin not found in DLNA

### ISSUE THREAD

**Issue by An4cl3t0** [jellyfin/jellyfin#2007] opened 2019-11-12 23:21 UTC
The server cannot be found in dlna search on TV.

Logs:
```
00:04:39] [INF] DLNA Session created for VIERA BL6 Series - Panasonic VIErA
[00:04:40] [ERR] HTTP request failed with message:
[00:04:40] [ERR] Error updating device info for VIERA BL6 Series
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean logRequest, String header)
   at Emby.Dlna.PlayTo.Device.GetTransportInfo(TransportCommands avCommands, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

 - OS: Docker
 - Jellyfin Version: 10.4.1

Thanks for your work.

**Comment by JustAMan** [comment] 2019-11-22 12:10
This might be relevant to a discussion we recently had in our Matrix channels - there's a setting somewhere with a broadcast interval you could tweak, maybe @anthonylavado remembers more details here?

**Comment by An4cl3t0** [comment] 2019-11-22 23:35
I forgot to mention that in the previous docker build was working fine.

**Comment by anthonylavado** [comment] 2019-11-23 06:45
Don’t think it’s the Alive Message Interval, looks like something surrounding the profiles maybe.

@An4cl3t0 Do you still have the baseurl as `/jellyfin`, or did you clear it? You can check under Advanced>Networking

**Comment by An4cl3t0** [comment] 2019-11-26 18:25
Cleared, but same error.

**Comment by JustAMan** [comment] 2019-11-27 09:35
This should be fixed by https://github.com/jellyfin/jellyfin/pull/2054 (in next release after 10.4.2)

**Comment by PrplHaz4** [comment] 2019-12-09 17:31
Looks like a duplicate of #2053

Updating to 10.4.3 fixed this issue for me.

**Closed** 2019-12-09 19:18 UTC
Labels: bug
