### ISSUE TITLE
Seeking video causes transcoding failure

### ISSUE THREAD

**Issue by chiefstank** [jellyfin/jellyfin#260] opened 2018-12-22 23:16 UTC
**Server Version**: 3.5.2-4 Win x64
**Clients**: Chrome Browser and Emby Roku app (latest versions)

**Issue**: While transcoding HEVC video to client, if you attempt to seek/FF through the video, transcoding fails and video halts. In Chrome, the client-side settings for video quality playback is set to Auto. Have tried multiple different bitrates/resolutions and get same error. If video is allowed to play without seeking/FF, there is no problem. 

```
[segment muxer @ 000000000223b700] Value -930.000000 for parameter 'segment_time_delta' out of range [0 - 9.22337e+12]
[segment muxer @ 000000000223b700] Error setting option segment_time_delta to value -930.
Could not write header for output file #0 (incorrect codec parameters ?): Result too large
```
[log.txt](https://github.com/jellyfin/jellyfin/files/2705618/log.txt)

**Comment by 10481** [comment] 2018-12-23 09:00
I had the same issue on arch Linux and it was the latest version of ffmpeg. While I can't be certain for your os, it might be width looking into. I downgraded ffmpeg and everything was back to normal.

**Comment by VGrol** [comment] 2018-12-23 16:31
This is an issue with FFMPEG 4.1, as the emby source hasn't been made compatible with 4.1
The original intended solution for this was to bundle an FFMPEG version internally, but this clashes with Arch Design Philosophy,

Instead I'd urge to consider properly supporting it or linking to a legacy package instead.

Sources:
https://emby.media/community/index.php?/topic/65009-i-think-i-found-a-bug-in-transcoding-when-resuming/
https://github.com/MediaBrowser/Emby/issues/3494
https://aur.archlinux.org/packages/emby-server-beta/

**Comment by chiefstank** [comment] 2018-12-23 17:56
Confirmed. Using ffmpeg 4.0.2 binary and seeking/FF works. Thanks for the workaround.

**Comment by joshuaboniface** [comment] 2018-12-23 18:02
@VGrol Thanks for the heads-up on this!

**Comment by JustAMan** [comment] 2018-12-23 20:43
So this seems this is an issue with support for new ffmpeg.
I personally would like to move to most recent version, but that would break distros which are not on "bleeding edge" like Debian...
Having one bundled version would help here a lot...

**Comment by sparky8251** [comment] 2018-12-27 19:39
If I am not mistaken, a lot of the ffmpeg build options Jellyfin will end up needing for hardware encoding aren't turned on by default in a lot of distro repos right?

That alone should mean that we have to bundle regardless of the version packaged by the distro. Arch is a tad unique since they basically flip on all build switches, but if I'm not mistaken Ubuntu and Debian don't turn on any of the hardware accel stuff leaving you to recompile it yourself if you want those features.

**Comment by JustAMan** [comment] 2018-12-27 19:42
Debian 9 at least has vaapi, but Ubuntu historically pretends that avconv and ffmpeg are drop-in replacements (which they are not).

**Comment by JuliusFreudenberger** [comment] 2019-01-08 17:05
You can download the binaries here: https://launchpad.net/ubuntu/disco/amd64/ffmpeg/7:4.0.2-2 in the section "Downloadable files".
You can also see the dependency packages and their required version.

**Comment by sparky8251** [comment] 2019-01-08 17:34
We've released two versions after this issue was first opened (3.5.2-5 and 10.0.0). Is this issue still happening for anyone in the newest versions? Both have had fixes to this kind of stuff.

If not, we might want to consider closing this.

**Comment by VGrol** [comment] 2019-01-08 19:31
While in general there seem to be less hang ups, from my rushed resting, any version of FFMPEG 4.1 or greater still breaks. 
I've found an easy way to test it is to repeatedly use the Skip button or to skip 70% into any video file that requires transcoding.

**Comment by sparky8251** [comment] 2019-01-08 20:09
Currently we only officially support ffmpeg 4.0.3. ffmpeg is very finicky with switch orders and options and there is no code in place for new or older versions.

Maybe, if someone wants to impl code for new versions we can switch to using 4.1 versions of ffmpeg, but that hasn't happened yet.

**Comment by VGrol** [comment] 2019-01-08 20:20
oh I'm well aware.
But the existance of this issue and the FFMPEG version are interlinked.
Thus this issue either falls under an unsupported environment or something for the roadmap.

I'm not really sure how support would work for 4.1 as it isn't backwards compatible, as far as I know at least. Thus it wouldn't make sense to do so until the other distributions move towards 4.1, or if you want to implement it based on a build flag.

Honestly I haven't figured out the optimal way myself, as Arch itself tends to be an FFMPEG version infront of the other Distros and bundling it doesn't seem to be all that great of an idea with how Arch works. 
The only logical conclusion I see is using an ffmpeg 4.0.x compat package for the Arch dependency, but afaik currently there isn't such a package nor is that a Jellyfin issue.

If you want to read more on the 'idea' implementation, the thoughts of the Emby Team and Arch package maintainers are in the links I posted above.

**Comment by gerroon** [comment] 2019-01-10 18:15
Not just transcoding failure with resuming a longish video (35 min resume state out of 1 hour), it also seems like Jellyfi is stuck  wasting 2 of my cores for hours for no appearent reason.

**Comment by JustAMan** [comment] 2019-01-11 16:56
@gerroon this looks like a separate issue to me, original one is 100% caused by `ffmpeg` version mismatch.
Could you please open new issue?

**Comment by JustAMan** [comment] 2019-01-11 16:57
Closing this in favour of #555.

**Closed by JustAMan** 2019-01-11 16:57 UTC
Labels: Backend, bug

**Comment by Eisfunke** [comment] 2019-01-15 19:46
@VGrol 

> The only logical conclusion I see is using an FFMPEG 4.0.x compat package for the Arch dependency, but AFAIK currently there isn't such a package nor is that a Jellyfin issue.
> 
> If you want to read more on the 'idea' implementation, the thoughts of the Emby team and Arch package maintainers are in the links I posted above.

Just a heads-up: I created a AUR package `ffmpeg4.0` with the previous ffmpeg version that can be used instead of the official package with 4.1.
