### ISSUE TITLE
[Issue]: Playlist access requires a user to have access to all libraries

### ISSUE THREAD

**Issue by cvsickle** [jellyfin/jellyfin#7071] opened 2021-12-30 22:19 UTC
### Please describe your bug

Playlists are already borked, so this took me some time to figure out. Users that do not have "Enable access to all libraries" checked have a problem when trying to access playlists - even the ones that user creates. The loader spins indefinitely when trying to enter the playlists library after creating a playlist.

Attempted access shows up in the log as: Jellyfin.Api.Controllers.ItemsController: username is not permitted to access Library Playlists.

Steps to reproduce.
1. With any user that only has access to some libraries, create a playlist by adding any item to a playlist.
2. Navigate to the homescreen, and note that that playlists library now shows up in "My Media"
3. Click on the playlists item and watch the loader spin forever.

Expected behaviors:

First, if the user doesn't have access to the Playlists library, the library should not show up under "My Media" on the home page, similar to how normal libraries are hidden from view when the user doesn't have access.

Second, if the Playlists library is going to be treated as a normal library, it should be available to select in the access settings for each user so that any user can access it without requiring full access to all libraries. This is how the collections library works. When the first collection is added to a server, the Collections library becomes available in the access settings and can be toggled for each user. I'm not sure the best way to handle playlists that include items from libraries that a user doesn't have access to, but I would assume this would work similar to how the Collections library works (however that may be).

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu LTS 20.04
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: standard http
- Storage: SSD
```

### Jellyfin logs

```shell
Jellyfin.Api.Controllers.ItemsController: username is not permitted to access Library Playlists.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment] 2022-01-04 18:14
Duplicate of #6514

**Closed by Bond-009** 2022-01-04 18:14 UTC
Labels: bug

**Comment by DirgoSalga** [comment] 2022-03-31 14:36
Was this resolved? I'm having the same issue right now.

**Comment by xubuyu** [comment] 2022-08-05 10:00
I have the same question. how about the issue?
