### ISSUE TITLE
[Issue]: Admin utilising a user's quick connect function connects the device to the admin's account

### ISSUE THREAD

**Issue by hugo-id** [jellyfin/jellyfin#8731] opened 2022-11-12 05:31 UTC
### Please describe your bug

The admin is able to access their user's quick connect function in their respective personal options, but using it connects the admin's account instead of the user's

Being able to quick connect me less technically-minded friends was a feature I was looking forward to in my switch to Jellyfin, so hopefully this can be fixed soon!

Step 1:
![image](https://user-images.githubusercontent.com/30918735/201458779-3db525a1-eb53-4d8e-8f51-ac55cfeb05ac.png)

Step 2:
![image](https://user-images.githubusercontent.com/30918735/201458794-1f3db65e-e66e-4d62-ad31-1a9bcffc23db.png)

Step 3:
![image](https://user-images.githubusercontent.com/30918735/201458801-80ca2e61-22ce-4dbe-a86e-2fcb3ab1ffe4.png)

Step 4:
Use the quick connect function on a device

Step 5:
The device is now connected to the _Admin's_ account instead of the user's

Let me know if you need anymore details

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: No
- Clients: Windows native / browse
- Browser: Firefox
- Plugins: Various
- Reverse Proxy: Caddy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-11-12 05:38
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/3918

**Closed by crobibero** 2022-11-12 05:38 UTC
Labels: bug
