### ISSUE TITLE
Bad ID implementation

### ISSUE THREAD

**Issue by Al4ndil** [jellyfin/jellyfin#6029] opened 2021-05-11 10:24 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: Xpenology
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Brave 1.24.82
 - Jellyfin Version: 10.7.5
 - Playback: Transcode
 - Installed Plugins: Fanart, Auto Organize, OpenSubtitles, TheTVDB, Trakt
 - Reverse Proxy: DSM
 - Base URL: [e.g. none, yes: /example]
 - Networking: Bridge
 - Storage: local

**To Reproduce**

1. Go to a movie
2. Click on Edit metadata
3. Scroll down to ID section
4. See the ID TheMovieDB in the ID IMDB

**Screenshots**

Step 1
![image](https://user-images.githubusercontent.com/47626482/117800054-120fff00-b253-11eb-8bd4-f68cb762765d.png)
Step 2
![image](https://user-images.githubusercontent.com/47626482/117800139-20f6b180-b253-11eb-97e2-e4838fd57933.png)
Step 3
![image](https://user-images.githubusercontent.com/47626482/117800255-3ec41680-b253-11eb-8a48-3195155a39ad.png)
Step 4
![image](https://user-images.githubusercontent.com/47626482/117800310-4edbf600-b253-11eb-939e-1dacd8028c2a.png)

**Comment by Ullmie02** [comment] 2021-05-11 12:28
Do you have a .nfo file for this movie? If yes this may be a duplicate of #5347 which is already fixed and will be released with 10.8

**Closed** 2021-05-11 13:34 UTC
Labels: bug
