### ISSUE TITLE
LDAP settings screen is blank

### ISSUE THREAD

**Issue by kennyluk** [jellyfin/jellyfin#2250] opened 2020-01-10 15:36 UTC
**Describe the bug**
After setting up the LDAP plugin and verify that it is working. If I go back to the Plugin settings-->LDAP, it is blank. The Plugin will continue to work, but the settings are just blank.

**To Reproduce**

1. Install LDAP plugin.
2. Save settings.
3. Log out.
4. Log back into the save admin user.
5. Settings will be blank.

**Expected behavior**
1. Settings not blank.

**Logs**
Not sure which log to provide, please specify.

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: LDAP
 - Reverse proxy: Caddy, but this is happening in local network.

**Additional context**

**Comment by crobibero** [comment] 2020-01-11 06:45
Possibly duplicate of https://github.com/jellyfin/jellyfin-web/issues/517

**Comment by JustAMan** [comment] 2020-01-14 15:27
I think it's web-ui related, could you please look into browser web console and see if there are some relevant bits?

**Comment by dkanada** [comment] 2020-02-15 14:24
@kennyluk is this fixed on the latest nightly?

**Comment by kennyluk** [comment] 2020-02-24 13:59
I have the nightly tar for macos, what is the correct way to install it over the released version to test this?

**Comment by mark-monteiro** [comment] 2020-03-22 23:56
@kennyluk great! Sound like this is resolved in nightly then. Closing.

**Closed by mark-monteiro** 2020-03-22 23:56 UTC
Labels: bug, question
