### ISSUE TITLE
Poster images (primary) not shown on 10.7.2

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#5788] opened 2021-04-12 12:12 UTC
**Describe the bug**
After updating from 10.7.1 to 10.7.2, no primary images are being shown. Downgraded to 10.7.1 again and everything works as expected. Tried in incognito too with the same results

**System (please complete the following information):**
 - OS: CentOS
 - Virtualization: Docker
 - Clients: Firefox, Chrome 
 - Jellyfin Version: 10.7.2
 - Reverse Proxy: nginx
 - Base URL: None
 - Networking: Bridge
 - Storage: nfs

**To Reproduce**
1. Upgrade to 10.7.2
2. Click on a movie
3. Witness constant blurhash, or no image at all depending on settings.

**Expected behavior**
Primary image is shown

**Logs**
No errors were reported when I was testing. I'll see if I can dig out the actual logs somewhere.

**Screenshots**
![Screenshot from 2021-04-12 13-42-33](https://user-images.githubusercontent.com/13684929/114392417-07e9da80-9b99-11eb-978f-f3e5f31b48d6.png)

**Comment by Liquoriced** [comment] 2021-04-12 12:23
I can confirm this bug: immediately after I upgraded to 10.7.2 all my primary posters are blurred.
The problem persists even if new posters are downloaded.

**Comment by TheNamelessWonderer** [comment] 2021-04-12 16:31
Same issue here. All the posters are blurry. I have the following error:
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-2dc0f3243adc8844aae6b6a6492af483-1851227b140a464b-00",
  "errors": {
    "fillWidth": [
      "The value '334.25' is not valid."
    ]
  }
}
```
This is an HTTP 400 error too.

**Comment by oddstr13** [comment] 2021-04-12 16:38
Closing as duplicate of jellyfin/jellyfin-web#2587

**Closed by oddstr13** 2021-04-12 16:38 UTC
Labels: bug
