### ISSUE TITLE
[Issue]: Multiple Episodes in 1 File Not Correctly Titled

### ISSUE THREAD

**Issue by PacketParker** [jellyfin/jellyfin#10205] opened 2023-09-10 20:53 UTC
### Please describe your bug

For context, all files are correctly named and use the format of SxxExx-Exx. Jellyfin recognizes that there are multiple episodes within the 1 file, however, it does not title the episode as expected. I was expecting something like `1-2. Episode 1 Title and Episode 2 Title`, however, it only does `1-2. Episode 1 Title`.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Virtualization: Docker
- Clients: ALL
- Browser: Firefox
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment] 2023-09-16 03:40
Duplicate of #2980

**Closed by 1337joe** 2023-09-16 03:40 UTC
Labels: bug
