### ISSUE TITLE
[10.8-alpha5] infinite spinner when I try to play some media but most plays fine - error getting PlaybackInfo

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/jellyfin#7223] opened 2022-01-20 08:30 UTC
**Notes**
* The rest of my library plays fine, including media that needs transcoding. It is just a selection of test media that throws this error. The media that throw this error are a variety of containers and codecs (I've seen it in mkv,mp4 h264,hvec,av1)
* I've even added other media like movies and TV since this started happening and those work.
* I've tested the media that causes this error and it plays fine outside of jellyfin.

**Media Info of the file (from web-ui)**

jellyfish-3-mbps-hd-h264
Container mkv
Path /mypath/jellyfish-3-mbps-hd-h264.mkv
Size 11 MB

Video
Title 1080p H264 SDR
Codec H264
AVC No
Profile High
Level 40
Resolution 1920x1080
Aspect ratio 16:9
Interlaced No
Framerate 29.970032
Bitrate 2984 kbps
Bit depth 8 bit
Video range SDR
Color space bt709
Color transfer bt709
Color primaries bt709
Pixel format yuv420p
Ref frames 1
NAL 0

**Logs**
https://pastebin.com/7dTVGcna

**FFmpeg Logs**
It doesn't get that far

**Stats for Nerds Screenshots**
It doesn't get that far. Just a spinner on the web client.
On the android TV client I'm able to catch PlaybackInfo == null and gracefully close player

**Server System (please complete the following information):**
 - OS: Docker on Linux
 Open Media Vault 5.6.22, Debian 10
 - Jellyfin Version: 10.8-alpha5
 - Hardware settings & device: NVENC on GTX760
 - Reverse proxy: caddy <--> cloudflare (cloudflare proxy disabled, only DNS)
 - Other hardware notes: Media is mounted internally, folders and files are owned by the user the jf container runs as
 
**Client System (please complete the following information):**
 - Device: Arch Linux PC, Android phone, Google Chromecast w TV
 - OS: Arch Linux, Android
 - Client: Google Chrome, Brave Browser, Jellyfin Android, Jellyfin Android TV, JMP
 - Browser (if Web client): Google Chrome, Brave Browser
 - Client and Browser Version: brave 1.34.80, jellyfin android 2.4.2, jellyfin android-tv dev builds, JMP 1.6.1

**Comment by memnos** [comment] 2022-01-23 09:15
Hallo, i'm experiencing the same problem as well.

**Comment by mueslimak3r** [comment] 2022-06-15 08:16
I still experience this issue with 10.8 stable. Tested with fresh media from https://jell.yfish.us/

(commenting to remove stale label)

**Comment by binitGajera** [comment] 2022-07-06 22:42
Can confirm this exists in 10.8.1 stable as well. Am experiencing this issue with almost all files on my server, wasn't able to play any video files. The endpoint /Items/{SomeGuid}/PlaybackInfo seems to be returning a 400 error for me, please find below the response from that endpoint.

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-678207165fc6d34c8d56873995b597b5-27eb58769908d447-00",
  "errors": {
    "$.DeviceProfile.CodecProfiles[2].Conditions[2].Property": [
      "The JSON value could not be converted to MediaBrowser.Model.Dlna.ProfileConditionValue. Path: $.DeviceProfile.CodecProfiles[2].Conditions[2].Property | LineNumber: 0 | BytePositionInLine: 3016."
    ]
  }
}
```

**Comment by pixelblob** [comment] 2022-08-28 23:19
Also having the same problem

**Comment by gogo199432** [comment] 2023-01-19 19:20
Got the same issue, but with BytePosition 3008. Any news?
@binitGajera or @pixelblob did you guys manage to solve it?

**Comment by itniels** [comment] 2023-09-16 03:14
I am also experiencing this issue on `v10.8.10` with some media, is there anything I can add to make this easier to debug?

```
Version: 10.8.10
Operating System: Linux
Architecture: X64
```

**Comment by srcrist** [comment] 2023-10-19 17:11
Issue closed as duplicate of https://github.com/jellyfin/jellyfin/issues/2277. Problem is most frequently caused by an attempt to play a corrupt source file. Solution is more graceful error handling in clients (and not playing corrupt files).

**Closed by srcrist** 2023-10-19 17:11 UTC
Labels: bug
