### ISSUE TITLE
Collections can be edited, deleted or created by any user

### ISSUE THREAD

**Issue by Snipy2k4** [jellyfin/jellyfin#9067] opened 2023-01-11 02:38 UTC
Hello,

i installed this server on my Qnap TS-253.
Link to QNAP Jellyfin Server: https://github.com/pdulvp/jellyfin-qnap

I use the current Windows app (10.8.8) or log in via browser.

But that's not my problem.

My problem is that when I create a new user, do NOT give him any administrative rights and also remove the right to delete files, but he can create or edit new collections, which is quite annoying if you only want to give "reading rights". The whole thing works even if I don't allow this user access to "Collection", he can still add films and series to collections or create collections, which can't be the point, can it?

What can I do there? Are you aware of the problem?

Sorry I used google translator :D

PS: Am I in the right place here with my request? I don't know please forgive me if not and tell me where to go.

thanks

**Comment by crobibero** [comment] 2023-01-11 02:52
Essentially a duplicate of https://github.com/jellyfin/jellyfin/issues/7179

Will be fixed by https://github.com/jellyfin/jellyfin/pull/8887

**Closed by crobibero** 2023-01-11 02:52 UTC
