### ISSUE TITLE
Edit metadata, then Save button does nothing when Community rating has more than one digit after dot

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#8524] opened 2022-10-09 10:41 UTC
I believe the subject line already says it all.

Edit metadata: While attempting to edit the "Change date", the Save button does not work.
This happens when the "Community rating" entry has more than one digit after the period, like "6.123". It only works after "Community rating" is manually changed to something like "6.1".

I've had this issue since I first started using Jellyfin, hence this bug must have been present from at least 10. something all the way up to the 10.8.5.

**Comment by daullmer** [comment] 2022-10-25 05:00
Duplicate of #8238 and jellyfin/jellyfin-web#4093. will be fixed with jellyfin/jellyfin-web#4094

**Closed** 2022-10-25 05:00 UTC
