### ISSUE TITLE
Home Screen Section "Continue Watching" is displaying ALL file versions for a given movie.

### ISSUE THREAD

**Issue by cautious-bread** [jellyfin/jellyfin#12139] opened 2024-06-19 13:21 UTC
### Please describe your bug

When viewing the Home Screen I can see all file versions of a given movie instead of just the single representation of the movie as it used to be.
This is only happening since upgrading to v10.9 (I think) as it was never an issue before (Continue Watching just showed the single movie entries).
![versions](https://github.com/jellyfin/jellyfin/assets/56622533/fd1c29e8-8c7f-445b-8005-1340d242c259)

### Reproduction Steps

1. Watch a movie which has multiple versions.
2. Get a few minutes into it.
3. Stop movie.
4. Go back to Home Screen.
5. Observe Continue Watching section displaying all versions of played movie.

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: openmediavault 6.9.16-1 (Shaitan)
- Linux Kernel: Linux 6.1.0-0.deb11.18-amd64
- Virtualization: Docker.
- Clients: Web, LG TV client.  JellyCon via Kodi.
- Browser: Firefox 127
- FFmpeg Version: Unsure - whatever is packaged with Jellyfin.
- Playback Method: Direct Play and Direct Stream, depending on client.
- Hardware Acceleration: QuickSync, but not utilised in tests.
- GPU Model: Integrated QuickSync on Intel i5-10400T
- Plugins:
AudioDB 10.9.6.0 Status Active
Kodi Sync Queue 11.0.0.0 Status Active
Merge Versions 10.9.1.1 Status Active
MusicBrainz 10.9.6.0 Status Active
OMDb 10.9.6.0 Status Active
Playback Reporting 14.0.0.0 Status Active
Studio Images 10.9.6.0 Status Active
TMDb 10.9.6.0 Status Active
TMDb Box Sets 10.0.0.0 Status Disabled
TV Maze 5.0.0.0 Status Active
Webhook 14.0.0.0 Status Active
- Reverse Proxy: None.
- Base URL: http://servername:8096
- Networking: LAN, wired.
- Storage: Local USB SSD.
```

### Jellyfin logs

```shell
Will post logs if asked for as I'm unclear if they contain identifiable info (e.g. I can see my username in there).
```

### FFmpeg logs

```shell
Not a transcoding issue.
```

### Please attach any screenshots here

![versions](https://github.com/jellyfin/jellyfin/assets/56622533/86685f6f-fc0c-4dd0-807e-d4d3dc22700e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2024-06-19 13:23
Duplicate of https://github.com/jellyfin/jellyfin/issues/7429

**Closed by crobibero** 2024-06-19 13:23 UTC
Labels: bug
