### ISSUE TITLE
[Issue]: SyncPlay times out after 30 seconds: Error while waiting for `playbackstart` event! startPlayback Timed out.

### ISSUE THREAD

**Issue by 0xC0ncord** [jellyfin/jellyfin#11584] opened 2024-05-13 03:02 UTC
### Please describe your bug

Since upgrading to Jellyfin 10.9.1 from 10.8.13, creating or joining a SyncPlay group causes playback to cancel after 30 seconds every time. This happens even if I create a group and no one else joins, and also happens regardless of whether I unpause the media or not.

When playback is canceled, I am thrown back to the series or episode page instantly with no errors or warnings visible in the UI. I see this in the browser console, however:
![image](https://github.com/jellyfin/jellyfin/assets/8011001/4bcea57e-d4b6-49a0-9dab-d39dfe0dfe70)

### Reproduction Steps

1. Start playback of a video.
2. Pause the video.
3. Create a SyncPlay group.
4. Wait about 30 seconds.
5. Observe that playback was canceled automatically.

I was also able to reproduce this by:

1. Create a SyncPlay group.
2. Play a video.
3. Watch for 30 seconds.
4. Observe that playback was canceled automatically.

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Gentoo Linux
- Linux Kernel: 6.7.9-gentoo
- Virtualization: Kubernetes v1.29.3, CRI-O 1.29.2 (using `jellyfin/jellyfin:10.9.1`)
- Clients: Browser
- Browser: Chromium Version 124.0.6367.201
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: Intel QSV
- GPU Model: Arc A380
- Plugins: LDAP Auth, Playback Reporting, Reports
- Reverse Proxy: ingress-nginx 
- Base URL: none
- Networking: Cilium
- Storage: NFS
```

### Jellyfin logs

```shell
[02:48:17] [INF] [38] Emby.Server.Implementations.SyncPlay.Group: Session f1eaef11f57677291b65811cb547152a requested Ready in group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d that is Playing.
[02:48:17] [INF] [31] Emby.Server.Implementations.SyncPlay.Group: Session f1eaef11f57677291b65811cb547152a requested Ready in group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d that is Playing.
[02:48:22] [INF] [37] Emby.Server.Implementations.SyncPlay.Group: Session f1eaef11f57677291b65811cb547152a requested Ready in group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d that is Playing.
[02:48:22] [INF] [10] Emby.Server.Implementations.SyncPlay.Group: Session f1eaef11f57677291b65811cb547152a requested Ready in group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d that is Playing.
[02:48:23] [INF] [14] Emby.Server.Implementations.SyncPlay.Group: Session 85744a3e97f8c2c0ef937f3db9d7ca6b left group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d.
[02:48:24] [INF] [37] Emby.Server.Implementations.SyncPlay.Group: Session f1eaef11f57677291b65811cb547152a requested IgnoreWait in group 71ec8ba7-229b-4f8c-ae42-eb764395ca1d that is Playing.
[02:48:24] [INF] [37] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for /config/transcodes/78a01feeb54f360cd7215cc31aded66d.m3u8
[02:48:24] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI1LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI1LjB8MTcxNTU2Njg3NTY5OQ11-7cb71b3b4d1441b08cc96e7d529e5239-8af01766854961f538312a1b2ddca854
[02:48:25] [INF] [37] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[02:48:25] [INF] [37] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/transcodes/78a01feeb54f360cd7215cc31aded66d.m3u8
[02:48:28] [INF] [14] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.9.1 playing A Price for This Cursed Sword!. Stopped at 16660 ms
[02:48:28] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI1LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI1LjB8MTcxNTU2Njg3NTY5OQ11-7cb71b3b4d1441b08cc96e7d529e5239-8af01766854961f538312a1b2ddca854
[02:48:28] [INF] [19] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 05/13/2024 02:48:28
[02:48:28] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
```

### FFmpeg logs

```shell
{"Protocol":0,"Id":"8af01766854961f538312a1b2ddca854","Path":"/media/videos/Anime/KonoSuba: God\u0027s Blessing on this Wonderful World/Season 01/KonoSuba \u2013 God\u0027s blessing on this wonderful world!! (2016) - S01E05 - 005 - A Price for This Magic Sword! [Unnamed_1_2 Bluray-1080p][8bit][AVC][PCM 2.0][EN\u002BJA]-ZR.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":7783024128,"Name":"KonoSuba \u2013 God\u0027s blessing on this wonderful world!! (2016) - S01E05 - 005 - A Price for This Magic Sword! [Unnamed_1_2 Bluray-1080p][8bit][AVC][PCM 2.0][EN\u002BJA]-ZR","IsRemote":false,"ETag":"83f792d6d6acc324a55fdf6243483d1f","RunTimeTicks":14233979904,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"h264","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":1,"VideoRangeType":1,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"ChannelLayout":null,"BitRate":43743348,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":41,"IsAnamorphic":null},{"Codec":"pcm_s16le","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Stereo","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"Stereo - English - PCM_S16LE - 2 ch - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":1536000,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"pcm_s16le","CodecTag":null,"Language":"jpn","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Stereo","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"Stereo - Japanese - PCM_S16LE - 2 ch","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":1536000,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"pcm_s16le","CodecTag":null,"Language":"jpn","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Japanese Commentary Stereo","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"Japanese Commentary Stereo - PCM_S16LE - 2 ch","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":1536000,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Signs \u0026 Songs","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"Signs \u0026 Songs - English - Default - PGSSUB","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","LocalizedHearingImpaired":"Hearing Impaired","DisplayTitle":"English - PGSSUB","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":5,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":48351348,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/videos/Anime/KonoSuba: God's Blessing on this Wonderful World/Season 01/KonoSuba – God's blessing on this wonderful world!! (2016) - S01E05 - 005 - A Price for This Magic Sword! [Unnamed_1_2 Bluray-1080p][8bit][AVC][PCM 2.0][EN+JA]-ZR.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 h264_qsv -low_power 1 -preset veryfast -look_ahead 0 -b:v 43743348 -maxrate 43743348 -bufsize 87486696 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -filter_complex "[0:4]scale=-1:1080:fast_bilinear,scale,crop,pad=max(1920\,iw):max(1080\,ih):(ow-iw)/2:(oh-ih)/2:black@0,crop=1920:1080,format=bgra,hwupload=derive_device=qsv:extra_hw_frames=64[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv[main];[main][sub]overlay_qsv=eof_action=pass:repeatlast=0:w=1920:h=1080" -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "92d5820b5cc3158c20c32c14b7e915e4-1.mp4" -start_number 0 -hls_segment_filename "/config/transcodes/92d5820b5cc3158c20c32c14b7e915e4%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/92d5820b5cc3158c20c32c14b7e915e4.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
Guessed Channel Layout for Input Stream #0.1 : stereo
Guessed Channel Layout for Input Stream #0.2 : stereo
Guessed Channel Layout for Input Stream #0.3 : stereo
Input #0, matroska,webm, from 'file:/media/videos/Anime/KonoSuba: God's Blessing on this Wonderful World/Season 01/KonoSuba – God's blessing on this wonderful world!! (2016) - S01E05 - 005 - A Price for This Magic Sword! [Unnamed_1_2 Bluray-1080p][8bit][AVC][PCM 2.0][EN+JA]-ZR.mkv':
  Metadata:
    encoder         : libebml v1.3.6 + libmatroska v1.4.9
    creation_time   : 2020-06-01T18:29:51.000000Z
  Duration: 00:23:43.40, start: 0.000000, bitrate: 43743 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 133.800292
      Metadata:
        title           : Chapter 25
    Chapter #0:1: start 133.800292, end 224.098833
      Metadata:
        title           : Chapter 26
    Chapter #0:2: start 224.098833, end 736.152042
      Metadata:
        title           : Chapter 27
    Chapter #0:3: start 736.152042, end 1320.402375
      Metadata:
        title           : Chapter 28
    Chapter #0:4: start 1320.402375, end 1409.950167
      Metadata:
        title           : Chapter 29
    Chapter #0:5: start 1409.950167, end 1421.240000
      Metadata:
        title           : Chapter 30
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 39077063
      DURATION-eng    : 00:23:43.089000000
      NUMBER_OF_FRAMES-eng: 34120
      NUMBER_OF_BYTES-eng: 6951267387
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      title           : Stereo
      BPS-eng         : 1536000
      DURATION-eng    : 00:23:41.266000000
      NUMBER_OF_FRAMES-eng: 42638
      NUMBER_OF_BYTES-eng: 272883200
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(jpn): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
    Metadata:
      title           : Stereo
      BPS-eng         : 1536000
      DURATION-eng    : 00:23:41.266000000
      NUMBER_OF_FRAMES-eng: 42638
      NUMBER_OF_BYTES-eng: 272883200
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(jpn): Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
    Metadata:
      title           : Japanese Commentary Stereo
      BPS-eng         : 1536000
      DURATION-eng    : 00:23:43.090000000
      NUMBER_OF_FRAMES-eng: 284618
      NUMBER_OF_BYTES-eng: 273233280
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      title           : Signs & Songs
      BPS-eng         : 8964
      DURATION-eng    : 00:21:25.409000000
      NUMBER_OF_FRAMES-eng: 56
      NUMBER_OF_BYTES-eng: 1440445
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Metadata:
      BPS-eng         : 59400
      DURATION-eng    : 00:23:28.949000000
      NUMBER_OF_FRAMES-eng: 654
      NUMBER_OF_BYTES-eng: 10461600
      _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 32-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-06-01 18:29:51
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 (h264) -> setparams:default (graph 0)
  Stream #0:4 (pgssub) -> scale:default (graph 0)
  overlay_qsv:default (graph 0) -> Stream #0:0 (h264_qsv)
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[matroska,webm @ 0x594bebb94c0] sub2video: using 1920x1080 canvas
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e4-1.mp4' for writing
Output #0, hls, to '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e4.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264, qsv(bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 43743 kb/s, 23.98 fps, 24k tbn
    Metadata:
      encoder         : Lavc60.3.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 43743348/0/43743348 buffer size: 87486696 vbv_delay: N/A
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default)
    Metadata:
      encoder         : Lavc60.3.100 libfdk_aac
frame=   26 fps=0.0 q=26.0 size=N/A time=00:00:01.13 bitrate=N/A speed= 2.4x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e40.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e41.mp4' for writing
frame=  161 fps=0.0 q=16.0 size=N/A time=00:00:06.93 bitrate=N/A speed=7.14x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e42.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e43.mp4' for writing
frame=  308 fps=209 q=16.0 size=N/A time=00:00:12.99 bitrate=N/A speed=8.83x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e44.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e45.mp4' for writing
[mp4 @ 0x594bed64640] Packet duration: -8 / dts: 861096 is out of range
frame=  459 fps=233 q=16.0 size=N/A time=00:00:19.19 bitrate=N/A speed=9.74x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e46.mp4' for writing
[mp4 @ 0x594bed64640] Packet duration: -8 / dts: 1005480 is out of range
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e47.mp4' for writing
frame=  606 fps=245 q=14.0 size=N/A time=00:00:25.47 bitrate=N/A speed=10.3x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e48.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e49.mp4' for writing
frame=  740 fps=249 q=16.0 size=N/A time=00:00:31.06 bitrate=N/A speed=10.5x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e410.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e411.mp4' for writing
frame=  886 fps=255 q=15.0 size=N/A time=00:00:37.03 bitrate=N/A speed=10.7x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e412.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e413.mp4' for writing
frame= 1025 fps=258 q=12.0 size=N/A time=00:00:43.00 bitrate=N/A speed=10.8x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e414.mp4' for writing
[mp4 @ 0x594bed64640] Packet duration: -8 / dts: 2158488 is out of range
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e415.mp4' for writing
[mp4 @ 0x594bed64640] Packet duration: -8 / dts: 2302872 is out of range
frame= 1168 fps=261 q=17.0 size=N/A time=00:00:48.78 bitrate=N/A speed=10.9x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e416.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e417.mp4' for writing
[mp4 @ 0x594bed64640] Packet duration: -8 / dts: 2590616 is out of range
frame= 1312 fps=264 q=16.0 size=N/A time=00:00:54.80 bitrate=N/A speed=  11x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e418.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e419.mp4' for writing
frame= 1465 fps=268 q=16.0 size=N/A time=00:01:01.20 bitrate=N/A speed=11.2x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e420.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e421.mp4' for writing
frame= 1614 fps=270 q=15.0 size=N/A time=00:01:07.49 bitrate=N/A speed=11.3x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e422.mp4' for writing
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e423.mp4' for writing
frame= 1762 fps=272 q=12.0 size=N/A time=00:01:13.59 bitrate=N/A speed=11.4x    
[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e424.mp4' for writing


[q] command received. Exiting.

[hls @ 0x594bec92900] Opening '/config/transcodes/92d5820b5cc3158c20c32c14b7e915e425.mp4' for writing
frame= 1812 fps=272 q=16.0 Lsize=N/A time=00:01:15.34 bitrate=N/A speed=11.3x    
video:400976kB audio:2320kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

### Please attach any browser or client logs here

![image](https://github.com/jellyfin/jellyfin/assets/8011001/8dd2b147-2da5-43e9-b18b-4d0d1bc942e2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-05-13 03:21
Duplicate of jellyfin/jellyfin-web#5485

**Closed by gnattu** 2024-05-13 03:21 UTC
Labels: bug
