### ISSUE TITLE
Airplay not working on Apple TV 2 from Jellyfin iOS app (.opus/.webm)

### ISSUE THREAD

**Issue by vincentroyc** [jellyfin/jellyfin#11323] opened 2024-04-09 00:12 UTC
### Please describe your bug

When trying to Airplay .opus audio files or .webm video files from jellyfin iOS App to an Apple TV 2 via Airplay, the playback never starts and the apple tv 2 keeps displaying an error like: Error while trying to load content

The same files work great when played inside Jellyfin iOS app's player or if using airplay screen mirroring.

### Reproduction Steps

- On Jellyfin iOS app
- Play a .opus audio file or .webm video file
- Airplay to Apple TV 2 (2nd gen a4 chip)
- Apple tv 2 displays: Error while trying to load content

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Ubuntu 22.04
- Linux Kernel: 6.5.0-26-generic
- Virtualization: None
- Clients: Jellyfin iOS app
- Browser: -
- FFmpeg Version: 5.1.4-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- GPU Model: 980 TI
- Plugins: FinTube
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: nvme m.2 ssd
```

### Jellyfin logs

```shell
User policy for username. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
Apr 08 19:50:19 vrc-media-server jellyfin[1390]: [19:50:19] [INF] StreamBuilder.BuildVideoItem( Profile=Anonymous Profile, Path=/home/jellyfin/music-show/video-file.webm, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported, AudioCodecNotSupported ) media:/videos/8ad6d31a-6839-3c0f-7fbb-2f03e99f30bd/master.m3u8?MediaSourceId=8ad6d31a68393c0f7fbb2f03e99f30bd&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=799616000&AudioBitrate=384000&MaxFramerate=60&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=37ba652f7c559298eac2ba2f17620585&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&vp9-level=-99&vp9-videobitdepth=8&vp9-profile=profile0&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported,%20AudioCodecNotSupported
Apr 08 19:50:19 vrc-media-server jellyfin[1390]: [19:50:19] [INF] Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Apr 08 19:50:19 vrc-media-server jellyfin[1390]: [19:50:19] [INF] Defined LAN exclusions : []
Apr 08 19:50:19 vrc-media-server jellyfin[1390]: [19:50:19] [INF] Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Apr 08 19:50:20 vrc-media-server jellyfin[1390]: [19:50:20] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
Apr 08 19:50:20 vrc-media-server jellyfin[1390]: [19:50:20] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:"/home/jellyfin/music-show/video-file.webm" -map_metadata -1 -map_chapters -1 -threads 6 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p1 -b:v 4928964 -maxrate 4928964 -bufsize 9857928 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1890\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1890/a\,1080))/2)*2,format=yuv420p" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d.m3u8"
Apr 08 19:50:21 vrc-media-server jellyfin[1390]: [19:50:21] [WRN] Slow HTTP Response from http://jellyfin.username.com:8096/videos/8ad6d31a-6839-3c0f-7fbb-2f03e99f30bd/hls1/main/0.ts?DeviceId=d580abb9-c9cb-4e4c-acdb-a3d6db1c2ca9&MediaSourceId=8ad6d31a68393c0f7fbb2f03e99f30bd&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=799616000&AudioBitrate=384000&MaxFramerate=60&PlaySessionId=725fbcc4170d482dabd5ccc3af32581e&api_key=cf067cdd93594e1686a6824cc693b682&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=37ba652f7c559298eac2ba2f17620585&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&vp9-level=-99&vp9-videobitdepth=8&vp9-profile=profile0&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=0&actualSegmentLengthTicks=30000000 to 74.58.237.172 in 0:00:00.910765 with Status Code 200
```

### FFmpeg logs

```shell
/videos/8ad6d31a-6839-3c0f-7fbb-2f03e99f30bd/hls1/main/0.ts

{"Protocol":0,"Id":"8ad6d31a68393c0f7fbb2f03e99f30bd","Path":"/home/jellyfin/music-show/video-file.webm","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":492645568,"Name":"video-file","IsRemote":false,"ETag":"37ba652f7c559298eac2ba2f17620585","RunTimeTicks":39979610112,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"vp9","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p VP9 SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":985793,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1890,"AverageFrameRate":60,"RealFrameRate":60,"Profile":"Profile 0","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":-99,"IsAnamorphic":null},{"Codec":"opus","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"English - OPUS - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":985793,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:"/home/jellyfin/music-show/video-file.webm" -map_metadata -1 -map_chapters -1 -threads 6 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p1 -b:v 4928964 -maxrate 4928964 -bufsize 9857928 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1890\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1890/a\,1080))/2)*2,format=yuv420p" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d.m3u8"


ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'file:/home/jellyfin/music-show/video-file.webm':
  Metadata:
    ENCODER         : Lavf58.76.100
  Duration: 01:06:37.96, start: -0.007000, bitrate: 985 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1890x1080, SAR 1:1 DAR 7:4, 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 01:06:37.933000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 01:06:37.961000000
Stream mapping:
  Stream #0:0 -> #0:0 (vp9 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (opus (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, hls, to '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1890x1080 [SAR 1:1 DAR 7:4], q=2-31, 4928 kb/s, 60 fps, 90k tbn (default)
    Metadata:
      encoder         : Lavc59.37.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 4928964/0/4928964 buffer size: 9857928 vbv_delay: N/A
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default)
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
frame=    1 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d0.ts' for writing
frame=  239 fps=0.0 q=21.0 size=N/A time=00:00:03.98 bitrate=N/A speed=7.75x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d1.ts' for writing
frame=  487 fps=480 q=21.0 size=N/A time=00:00:08.14 bitrate=N/A speed=8.03x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d2.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d3.ts' for writing
frame=  736 fps=485 q=25.0 size=N/A time=00:00:12.26 bitrate=N/A speed=8.09x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d4.ts' for writing
frame= 1012 fps=502 q=21.0 size=N/A time=00:00:16.87 bitrate=N/A speed=8.36x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d5.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d6.ts' for writing
frame= 1299 fps=516 q=21.0 size=N/A time=00:00:21.67 bitrate=N/A speed= 8.6x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d7.ts' for writing
frame= 1587 fps=526 q=21.0 size=N/A time=00:00:26.47 bitrate=N/A speed=8.77x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d8.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d9.ts' for writing
frame= 1875 fps=533 q=21.0 size=N/A time=00:00:31.25 bitrate=N/A speed=8.88x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d10.ts' for writing
frame= 2162 fps=538 q=21.0 size=N/A time=00:00:36.05 bitrate=N/A speed=8.97x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d11.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d12.ts' for writing
frame= 2450 fps=542 q=21.0 size=N/A time=00:00:40.83 bitrate=N/A speed=9.03x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d13.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d14.ts' for writing
frame= 2737 fps=545 q=21.0 size=N/A time=00:00:45.65 bitrate=N/A speed=9.09x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d15.ts' for writing
frame= 3025 fps=548 q=21.0 size=N/A time=00:00:50.43 bitrate=N/A speed=9.13x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d16.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d17.ts' for writing
frame= 3312 fps=550 q=21.0 size=N/A time=00:00:55.18 bitrate=N/A speed=9.16x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d18.ts' for writing
frame= 3599 fps=552 q=21.0 size=N/A time=00:00:59.98 bitrate=N/A speed= 9.2x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d19.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d20.ts' for writing
frame= 3888 fps=553 q=21.0 size=N/A time=00:01:04.81 bitrate=N/A speed=9.22x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d21.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d22.ts' for writing
frame= 4176 fps=555 q=21.0 size=N/A time=00:01:09.58 bitrate=N/A speed=9.25x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d23.ts' for writing
frame= 4463 fps=556 q=21.0 size=N/A time=00:01:14.38 bitrate=N/A speed=9.27x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d24.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d25.ts' for writing
frame= 4751 fps=557 q=21.0 size=N/A time=00:01:19.18 bitrate=N/A speed=9.28x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d26.ts' for writing
frame= 5039 fps=558 q=21.0 size=N/A time=00:01:23.98 bitrate=N/A speed= 9.3x    
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d27.ts' for writing
[hls @ 0x62500a010080] Opening '/var/lib/jellyfin/transcodes/771298e5c54e14f9ea079af828f9085d28.ts' for writing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-04-09 01:15
Let's be clear. Which model is the "Apple TV 2" you are referring to? Is it the "Apple TV 4K 2nd gen(with A12 chip)" or an older "Apple TV 2nd Gen(with A4 chip)"

How Airplay works is just simply sending the m3u8 playlist to the target device and if that device is unable to play that file, then the Airplay would fail. You can try to enable fmp4 container in settings->playback to see if it improves the situation.

**Comment by vincentroyc** [comment] 2024-04-09 01:29
> Let's be clear. Which model is the "Apple TV 2" you are referring to? Is it the "Apple TV 4K 2nd gen(with A12 chip)" or an older "Apple TV 2nd Gen(with A4 chip)"

Updated : Apple TV 2 (A4 chip)

> How Airplay works is just simply sending the m3u8 playlist to the target device and if that device is unable to play that file, then the Airplay would fail. You can try to enable fmp4 container in settings->playback to see if it improves the situation.

Can you be more precise? In the app or in the server. Either way, I tried mostly every combo options in app and on server.

So what would jellyfin send to the Apple TV if the downloaded coded is not supported and transcoding is required? I assumed it would send a m3u8 playlist with a link to stream a transcoded file, right? Well, I assume like it does with the iOS player since it doesn't not support .webm/.opus either. But weirdly it's working on the iOS player but not on the Apple TV

**Comment by gnattu** [comment] 2024-04-09 01:36
> So what would jellyfin send to the Apple TV if the downloaded coded is not supported and transcoding is required? I assumed it would send a m3u8 playlist with a link to stream a transcoded file, right? Well, I assume like it does with the iOS player since it doesn't not support .webm/.opus either. But weirdly it's working on the iOS player but not on the Apple TV

Your Apple TV is too old to fully support H.264 codecs in the format that your iOS device is using. The Apple TV 2nd Gen with A4 chip only supports H264 video up to 720p30 and can only use Main Profile level 3.1. This means it cannot use the same transcoding profile as an iPhone. If you try to play the transcoded video the server transcoded for your iPhone on this older Apple TV, it will likely error out because it cannot play that file. You can try to lower the resolution on your iPhone first, then try Airplay.

**Comment by vincentroyc** [comment] 2024-04-09 01:49
> > So what would jellyfin send to the Apple TV if the downloaded coded is not supported and transcoding is required? I assumed it would send a m3u8 playlist with a link to stream a transcoded file, right? Well, I assume like it does with the iOS player since it doesn't not support .webm/.opus either. But weirdly it's working on the iOS player but not on the Apple TV
> 
> Your Apple TV is too old to fully support H.264 codecs in the format that your iOS device is using. The Apple TV 2nd Gen with A4 chip only supports H264 video up to 720p30 and can only use Main Profile level 3.1. This means it cannot use the same transcoding profile as an iPhone. If you try to play the transcoded video the server transcoded for your iPhone on this older Apple TV, it will likely error out because it cannot play that file. You can try to lower the resolution on your iPhone first, then try Airplay.

I've tryed every resolution and bitrate possible from 1080p down to 240p. Why is YouTube still playing on my Apple TV than?

**Comment by gnattu** [comment] 2024-04-09 02:08
> I've tryed every resolution and bitrate possible from 1080p down to 240p. 

Then the profile level we used for iPhones is just too high for Apple TV this old.

> Why is YouTube still playing on my Apple TV than?

Are you sure YouTube Plays through AirPlay? It's iOS App does not even supports AirPlay(but only their own Cast), and on Browser, only part of the videos can be played through AirPlay and the other ones just errors. If you play it direct on Apple TV then it will work because it will request the server with a profile telling the server what format your device can play, which is very different from AirPlay.

**Comment by vincentroyc** [comment] 2024-04-09 02:13
> > I've tryed every resolution and bitrate possible from 1080p down to 240p.
> 
> Then the profile level we used for iPhones is just too high for Apple TV this old.
> 
> > Why is YouTube still playing on my Apple TV than?

I doubt that. Isn't it the main purpose of transcoding?

> Are you sure YouTube Plays through AirPlay? It's iOS App does not even supports AirPlay(but only their own Cast), and on Browser, only part of the videos can be played through AirPlay and the other ones just errors. If you play it direct on Apple TV then it will work because it will request the server with a profile telling the server what format your device can play, which is very different from AirPlay.

Yes I am sure. I go to Youtube iOS app, play any video and tap the cast icon and select airplay devices and it streams. It's not the only app still use airplay with that apple tv.

**Comment by gnattu** [comment] 2024-04-09 02:32
> I doubt that. Isn't it the main purpose of transcoding?

The problem is the transcoded file is for your iPhone not for your older Apple TV. We transcode to the format that the device requesting the transcoding supports, and your iPhone requested it, and the server knows nothing about your Apple TV because the device don't have to communicate with the server to start an AirPlay.

> play any video and tap the cast icon and select airplay devices and it streams. It's not the only app still use airplay with that apple tv.

It streamed an extremely low-quality video from my emulation, and that is likely how they dealt with AirPlay compatibility. They are providing a super-low quality fallback stream so that any devices not supporting that will pick up that instead.

**Comment by felix920506** [comment] 2024-04-09 07:00
This issue mainly concerns compatibility with a very old and long EOL device.

Although this is technically fixable, we currently have other priorities.

Closing this issue as won't fix.

**Closed by felix920506** 2024-04-09 07:00 UTC
Labels: bug, wontfix, media playback

**Comment by vincentroyc** [comment] 2024-04-09 10:28
> The problem is the transcoded file is for your iPhone not for your older Apple TV. We transcode to the format that the device requesting the transcoding supports, and your iPhone requested it, and the server knows nothing about your Apple TV because the device don't have to communicate with the server to start an AirPlay.

Is there no way I could configure or force the transcode quality to verify this theory? Because downgrading the quality video player options didn't do it.

And as mentionned, I have the same problem with just .opus audio files being transcoded. I doubt this is because the resulting AAC file is "too high of quality" for the Apple TV.

> It streamed an extremely low-quality video from my emulation, and that is likely how they dealt with AirPlay compatibility. They are providing a super-low quality fallback stream so that any devices not supporting that will pick up that instead.

My test were indeed all 720p or less. How can I force it so I can confirm the theory?

**Comment by vincentroyc** [comment] 2024-04-09 10:30
> This issue mainly concerns compatibility with a very old and long EOL device.
> 
> Although this is technically fixable, we currently have other priorities.
> 
> Closing this issue as won't fix.

Why did I knew at the first answer this would be the the resulting closing statement?

This project is open-source? Help me know how I could force it to prove the theory of too high resolution, because right now I have same problem with standalone .opus audio files, and you could maybe get a pull request and have it done by community.

**Comment by gnattu** [comment] 2024-04-09 10:54
> Help me know how I could force it to prove the theory of too high resolution

It is more than resolution. We defaults to Profile Level High 4.1, but your Apple TV only supports Profile Main 3.1, and no, there is no easy way to change these settings unless you actually modify the server source code and compile it yourself.

>  right now I have same problem with standalone .opus audio files

It is known that the audio transcoding is broken in some way in 10.8 branch.

**Comment by oddstr13** [comment] 2024-04-09 16:18
> Is there no way I could configure or force the transcode quality to verify this theory? Because downgrading the quality video player options didn't do it.

You could try pre-transcoding a video file with HandBrake or similar, making sure to set the video profile to main 3.1

**Comment by vincentroyc** [comment] 2024-04-09 22:02
> It is more than resolution. We defaults to Profile Level High 4.1, but your Apple TV only supports Profile Main 3.1, and no, there is no easy way to change these settings unless you actually modify the server source code and compile it yourself.

Is there a documentation that could educate me on how I could create this compatibility feature in Jellyfin?
 
> It is known that the audio transcoding is broken in some way in 10.8 branch.

Is there already an open issue about that?

**Comment by vincentroyc** [comment] 2024-05-01 00:55
@gnattu @oddstr13 @felix920506 Hi guys, I've debuged a bit on my free time and here are my findings : 

It does not seem to be related to the h264 profile that the transcoding is defaulting on. I managed to print the m3u8 file that is generated on the fly for the transcoding of a webm video to h264 codec and related container and pasted it along with the segments .ts files on a static self hosted containerized nginx and when I this static url with my phone and try to Airplay it to my Apple TV 2 it works flawlessly.

So, the problem is not with my so called EOL devices. they are able to use static files, so it must be in the way it is dynamically return and the way the iOS app is sending the url to Airplay. So my next question would be do you guys have any suggestion on what to check next knowing that the output of the generated playlist file and its segments are working well when statically hosted?

Anything you know on how all this works in Jellyfin would help me, or, at this point, any schematics documentation as it's a bit unclear how all this works as the code is not so DRY?

Thank you

**Comment by gnattu** [comment] 2024-05-01 01:07
If your file can be played then it could be much more simpler, because the Apple TV may be rejecting the stream simply because the profile marked in the HLS playlist is the one it cannot support. For quick and dirty hack you chan change this line:

https://github.com/jellyfin/jellyfin/blob/a1f5e7265fc3b4847111409570c4d47843336f0e/Jellyfin.Api/Helpers/HlsCodecStringHelpers.cs#L132

You can begin testing with changing `.6400` to `.4D40` to see if it helps.
