### ISSUE TITLE
[Issue]: 10.9 doesn't show user-created playlists in (music) libraries

### ISSUE THREAD

**Issue by Chaphasilor** [jellyfin/jellyfin#11152] opened 2024-03-13 16:32 UTC
### Please describe your bug

This bug is a follow-up to #10272

Playlists manually created by the user don't show up in the playlist section for that library.  
In each music library, there is a "Playlists" tab. Previously (10.8), all playlists were shown in that tab. With the new changes in 10.9 to prevent users from accessing playlists they don't own, only playlists created by the system (e.g. a scanned `.m3u` file) will be shown in that tab. User-created playlists can only be accessed via the global `Playlists` collection/library shown on the home page.

This is unexpected in two ways:

- Since there is a "Playlists" tab *within* the music library, it implies that playlists can be attached to a specific library, but that isn't possible afaik
- Creating a playlist from within that music library (e.g. click on music library, go so songs tab, click "Add to Playlist" and create a new one) creates a playlist that doesn't show up in the library where it was created.

So I propose the current solutions:

1. Show the same selection of playlists in each library and the global "Playlists" library
2. Add a way to create a playlist within a specific library
  - Playlists created without explicitly specifying a library parent should be shown in all libraries (just like in the first solution)

### Reproduction Steps

1. Go to <https://demo.jellyfin.org/unstable/>
2. Click on the "Music" library
3. Click on the "Songs" tab
4. Click the "Add to playlist" button on any song, and create a new playlist with any name for that song
5. Go back to the home screen
6. Click on the "Playlists" library, and confirm the playlist was created
7. Go back to the home screen
8. Click on the music library again
9. Click on the "Playlists" tab within the library, the playlist will not be shown

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
n/a, official unstable demo instance
```

### Jellyfin logs

```shell
n/a, can't access logs for demo server
```

### Please attach any browser or client logs here

On the "Playlists" tab within the music library, the browser performs the following request:
<https://demo.jellyfin.org/unstable/Users/a076a5bfc9034f379f5889bc6dafc77b/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=Playlist&Recursive=true&Fields=PrimaryImageAspectRatio%2CSortName%2CCanDelete&StartIndex=0&ParentId=7e64e319657a9516ec78490da03edccb>

Which yields the following response:
```json
{"Items":[],"TotalRecordCount":0,"StartIndex":0}
```

### Please attach any screenshots here

User-created playlists shown within the "Playlists" **library/collection:**
![image](https://github.com/jellyfin/jellyfin/assets/18015147/3dc62f5c-2cea-48a8-8d95-89e4e858b037)

User-created playlists **not** being shown within the "Playlists" tab of the **music library:**
![image](https://github.com/jellyfin/jellyfin/assets/18015147/bc94fc40-41bd-427b-929d-737f4fc06c61)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2024-03-13 16:41
Hi, it seems like your issue report has the following item(s) that need to be addressed:
- The format of the environment section has been altered from the template.
- You have not provided a sufficient amount of logs. Please provide every line during the time of the event *plus 10 lines before and after*.
- You have not provided any ffmpeg logs. They should be included if transcoding or remuxing.

This is an automated message, please comment below if you believe this is incorrect.

**Comment by Chaphasilor** [comment] 2024-03-13 16:42
If you really need me to, I can do a repro with "proper" logs on my own server ^^

**Comment by Shadowghost** [comment] 2024-03-13 19:12
This is a side effect of the fixes I implemented. This is how it was intended to work from the get go since apart from file system playlist, generic user created playlists can not be associated with a specific library - as you surmised.

Adding user playlists back to the library view would require quite some work, so I'm not sure this will be fixed before 10.9 release.

**Comment by Shadowghost** [comment] 2024-03-14 11:52
I think the playlist library includes all available playlists for a user - including ones originating from the file system.

I would consider displaying playlists with any item from that library to the playlist view in that library a feature request.

**Comment by Chaphasilor** [comment] 2024-03-15 07:02
Okay, then I guess we can close this issue and I'll open a feature request for library-specific playlists?

**Closed** 2024-05-10 22:20 UTC
Labels: bug
