### ISSUE TITLE
[Issue]: failed to pull images

### ISSUE THREAD

**Issue by drbuckingham** [jellyfin/jellyfin#7595] opened 2022-04-13 22:26 UTC
### Please describe your bug

Metadata scan failed to automatically pull images for the following directory names:
	"Hidalgo (2004) [tmdbid-2023]"
	"I, Robot (2004) [tmdbid-2048]"
	"Infinity (1996) [tmdbid-2033]"
	"Mission to Mars (2000) [tmdbid-2067]"
	"Moonstruck (1987) [tmdbid-2039]"
	"National Treasure (2004) [tmdbid-2059]"
	"Nell (1994) [tmdbid-1945]"
	"Nero (2004) [tmdbid-290088]"
	"No Good Deed [tmdbid-2017]"
	"Open Range (2003) [tmdbid-2055]"
	"Original Sin (2001) [tmdbid-2057]"
	"Road of No Return (2008) [tmdbid-20782]"
	"Shakespeare in Love (1998) [tmdbid-1934]"
	"Zodiac (2007) [tmdbid-1949]"

After manually matching the corresponding tmdbid's in the directory name, the metadata was successfully retrieved.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: KVM/QEMU
- Clients: Web & Jellyfin Media Player
- Browser: Vivaldi
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment] 2022-04-13 23:04
That's not really a bug but expected behavior. If no match is found no metadata is downloaded. Check my comment in the other issue for why the IDs aren't taken into account.

**Comment by crobibero** [comment] 2022-04-13 23:23
Closing as not a bug

**Closed by crobibero** 2022-04-13 23:23 UTC
Labels: bug
