### ISSUE TITLE
"Latest TV Shows" history disappeared

### ISSUE THREAD

**Issue by telans** [jellyfin/jellyfin#2711] opened 2020-03-29 21:44 UTC
**Describe the bug**
This history for added/changed tv shows has disappeared from my library. 

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: OS running via QEMU
 - Clients: Browser
 - Browser: Firefox 74
 - Jellyfin Version: Occured on 10.5.0
 - Installed Plugins: https://i.imgur.com/ztAKaon.png
 - Storage: Local via unraid share & qemu

**To Reproduce**
Unclear. I have a suspicion that it's due to changing all the episodes in a series (Castle 2009).

**Expected behavior**
History does not disappear.

**Logs**
No errors in debug logs aside from the common: `Error in "TheTVDB"`

**Screenshots**
[1] ![Screenshot_20200330_103607](https://user-images.githubusercontent.com/45819748/77861621-8598ad80-7205-11ea-804c-98d9d16647bc.png)
[2] ![Screenshot_20200330_103635](https://user-images.githubusercontent.com/45819748/77861629-9517f680-7205-11ea-9dcd-26956c3594b7.png)

**Additional context**
History has not reappeared after a server restart nor an upgrade from 10.5.0 to 10.5.2.
There are some similar issues such as #1880 & #2590, but they aren't the same as both the main library view [1] and the seperate "Latest" tab [2] show the same thing.

I assume it's not possible to restore this history? I have a backup, but it's fairly old and I'd rather not use it.

**Comment by arnaudsm** [comment] 2020-05-07 10:34
I have the same problem, since at least 10.4.1

**Comment by telans** [comment] 2020-05-10 04:26
Happened again

v10.5.5

![Screenshot_20200510_162444](https://user-images.githubusercontent.com/45819748/81490832-e0302980-92da-11ea-9557-846a3fa9229d.png)

**Comment by visualblind** [comment] 2020-05-11 15:18
I'm experiencing the same issue.
OS: Debian 10
Virtualization: Docker
Clients: n/a
Browser: Chrome 81.0.4044.122
Jellyfin Version: 10.5.4
Installed Plugins: AudioDB, Fanart, MusicBrainz, Open Subtitles, Playback Reporting, Reports
Storage: FUSE mount (google drive) with Rclone
![Screenshot from 2020-05-11 08-13-44](https://user-images.githubusercontent.com/19721142/81578660-f8965780-935f-11ea-9b88-a591cf9cb81f.png)

**Comment by telans** [comment] 2020-07-24 12:01
Happened again, definitely seems related to adding/removing seasons of a show at a time.

v10.6.0

![Screenshot from 2020-07-25 00-00-13](https://user-images.githubusercontent.com/45819748/88389100-eb8aef80-ce09-11ea-8b06-e177fc8bed59.png)

**Comment by visualblind** [comment] 2020-07-24 23:39
> Happened again, definitely seems related to adding/removing seasons of a show at a time.
> 
> v10.6.0
> 
> ![Screenshot from 2020-07-25 00-00-13](https://user-images.githubusercontent.com/45819748/88389100-eb8aef80-ce09-11ea-8b06-e177fc8bed59.png)

@telans Do you remember if you did a "Scan for new and update files" on the series itself, or on the library? In my opinion this happens more often when doing the refresh on the individual series as apposed to the library when adding/removing seasons of a show.

**Comment by telans** [comment] 2020-07-25 00:57
I didn't initiate any manual scans, so it's purely the "Scan Media Library" task, which I assume is "Scan for new and updated files". This was the case for the previous occurrence too.

**Comment by telans** [comment] 2020-11-25 11:29
shoo

**Comment by telans** [comment] 2020-12-02 01:10
Happened again - adding multiple seasons of a show

**Comment by visualblind** [comment] 2020-12-03 03:13
> Happened again - adding multiple seasons of a show

I have experienced this multiple times and have a simple workaround to help mitigate the issue. You should probably update your comment under "To Reproduce" to say something like, "Add/change many episodes of an existing TV series, and perform the 'Scan for new and updated files' refresh on either the library or specific series/season." The issue happens even when not changing every single episode in a series, it can happen even when altering a single season of a multi-season series or a partial season. I'm fairly sure this has to do with quantity updated per library refresh, since my workaround is to breakup the quantity of episodes updated per library refresh.
If there are many episodes being changed/added within a single season, create a temp dir with a file named ".ignore" and move all but a small portion of the episodes you want updated. For example, if I had a season with 25 episodes being updated, try leaving 7-10 episodes in the season directory and move the rest in the temp dir and do a refresh. Wait until it completes, then move another 7-10 or more into the season folder to get updated. Rinse and repeat as many times as it takes, I know it's really annoying. This is a really weird issue because there doesn't seem to be a fixed number of new episodes that triggers the problem. Sometimes as few as 9 will do it, while other times it will be fine when doing 25+. I hate to be the developer that has to take a whack at this intermittent-type issue.

**Comment by telans** [comment] 2020-12-03 03:28
> breakup the quantity of episodes updated per library refresh.

This might be a solution for you, but I don't believe it's applicable in my case. I have jellyfin set to detect changes to the library folders automatically rather than on a schedule, which presumably watches for inotify and scans files one by one as they are moved into the destination folders.

The recent example of this bug occuring had about 40 episodes scanned when the recent history seemed to be limited to about 10 items. Once all episodes were scanned there were no items left in the recent history. It's a strange bug.

**Comment by calharding** [comment] 2021-02-25 10:08
Experiencing the same bug on 10.6.4. Seems unpredictable, entirely intermittent, and there seems to be no way to "manually" restore items to the front page.

The issue is unfortunately disruptive enough to the user experience that it's tempting to migrate away from Jellyfin altogether until the issue is resolved.

**Comment by cvium** [comment] 2021-03-08 08:39
I know this does not help you, but it looks like the problem is this line https://github.com/jellyfin/jellyfin/blame/ee23d06154133ffc506dda3a8ef0e09d20c03c6c/Emby.Server.Implementations/Library/UserViewManager.cs#L359

It only fetches the 150 newest episodes regardless of grouping, but in the view they are grouped by Show.

**Comment by cvium** [comment] 2021-08-30 11:14
Technically a duplicate of #1880.

**Closed by cvium** 2021-08-30 11:14 UTC
Labels: bug, confirmed, librarydb

**Comment by neo-neo1** [comment] 2021-12-10 11:46
Still experiencing this issue almost 2 years later on 10.7.7

**Comment by cvium** [comment] 2021-12-10 14:20
I'm getting really tired of repeating myself. I have outlined the issue and why fixing it is currently not very easy. I'm locking the topics.
