### ISSUE TITLE
[Issue]: Choosing Spanish;Castilian does not work correctly

### ISSUE THREAD

**Issue by Yivas** [jellyfin/jellyfin#9991] opened 2023-07-12 12:26 UTC
### Please describe your bug

For both audio and subtitle preferences for your user, choosing Spanish;Castilian does not work correctly, it ignores this. When you reload the page or go back to the settings, you will always find Spanish;Latin selected, not Spanish;Castilian.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows Server 2019
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Opera
- FFmpeg Version: 6.0.1
- Playback Method:
- Hardware Acceleration: none
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oxixes** [comment] 2023-07-21 01:26
I think this is a problem of [jellyfin-web](https://github.com/jellyfin/jellyfin-web)

**Comment by srcrist** [comment] 2023-10-07 13:21
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/1358.

**Closed by srcrist** 2023-10-07 13:21 UTC
Labels: bug
