### ISSUE TITLE
Issues with "Group movies into collections" in library display settings

### ISSUE THREAD

**Issue by HereForCodeThatsIt** [jellyfin/jellyfin#11807] opened 2024-05-21 14:30 UTC
**Describe The Bug**
When the "Group movies into collections" feature is disabled, the library acts and displays normally. However, when I enable it, any movies in that collection that have multiple versions (which have been grouped together) are displayed outside the collection. In addition to this, with this feature enabled (and only when it is enabled), any movie, even outside that collection, that I have multiple versions of will display twice in my library.

**Steps To Reproduce**

1. Make collection including at least one movie with multiple versions. Also can have a multiple versions movie in the library.
2. Go to library and see that movies display correctly.
3. Go to dashboard - library - display and enable "Group movies into collections".
4. Return to the movie library and see behaviour described above. 

**Expected Behavior**
Enabling this feature, I expected all movies, including multiple versions grouped as one, to display as their collections, regardless of there being multiple versions of a movie.

**Logs**

**Screenshots**

Below is library with feature disabled. All Star Wars movies display separately. Those with multiple versions display once.
<img width="815" alt="Screenshot 2024-05-21 at 10 13 35 AM" src="https://github.com/jellyfin/jellyfin-web/assets/160201918/d0e86895-18fd-41e1-84ea-ae61db840c7b">
Below is with the feature enabled. Movies with multiple versions (as seen with The Force Awakens, beside the collection and Revenge of the Sith, on the right) are displayed outside the collection. Also note that The Force Awakens usually has a different poster, matching the style of the Collection and ROTS. With the feature enabled, the duplicate versions have differing metadata for the images.
<img width="1017" alt="Screenshot 2024-05-21 at 10 14 57 AM" src="https://github.com/jellyfin/jellyfin-web/assets/160201918/a135c977-bb65-4d82-aebb-69e8c9a72478">
Below is also with the feature enabled, showing movies that are not in a collection but that do have multiple versions displaying twice in my library. This does not happen with feature disabled.
<img width="498" alt="Screenshot 2024-05-21 at 10 16 02 AM" src="https://github.com/jellyfin/jellyfin-web/assets/160201918/ad5546e2-8627-473e-9a40-a4c157cb659a">

**System (please complete the following information):**
 - Platform: Synology running container on "Container Manager" (formerly Docker)
 - Browser: Edge, Chrome
 - Jellyfin Version: [e.g. 10.9.2]

**Additional Context**
I did not have this feature enabled on prior versions of jellyfin so I cannot say if this is a feature arising in 10.9.2, but that is where I am experiencing it.

**Comment by jedthe3rd** [comment] 2024-05-26 06:28
> I did not have this feature enabled on prior versions of jellyfin so I cannot say if this is a feature arising in 10.9.2, but that is where I am experiencing it.

I did have it enabled before 10.9.2 and it worked as expected before 10.9.X

**Comment by HereForCodeThatsIt** [comment] 2024-05-27 18:40
@jedthe3rd Is it behaving as I described now for you too?

**Comment by jedthe3rd** [comment] 2024-06-10 17:05
It's acting weird for me still. Some movies are showing both inside and outside the collection. Some aren't being grouped at all.

It might be related to my other issue I have with the Group movies into collections: https://github.com/jellyfin/jellyfin/issues/11951

**Comment by HereForCodeThatsIt** [comment] 2024-06-11 02:51
Still weird for me too.

**Comment by felix920506** [comment] 2024-09-03 20:19
Duplicate of #11736

**Closed by felix920506** 2024-09-03 20:19 UTC
Labels: bug
