### ISSUE TITLE
Audio transcoding broken

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#12926] opened 2024-10-31 16:35 UTC
The Android TV app uses HLS for transcoding, both for video and audio. Starting with 10.10 the audio transcoding stopped working. When playing an incompatible music file (in this case a .wma file provided by @BotBlake) the generated looks like this:

```
/Audio/<itemid>/master.m3u8?tag=<tag>&playSessionId=<sessionid>&segmentContainer=mp3&mediaSourceId=<sourceid>&streamOptions=%7B%7D&enableAdaptiveBitrateStreaming=true&enableAudioVbrEncoding=true&ApiKey=<topsecret>
```

This will end up with the following failed ffmpeg transcode attempt:

```
{"Protocol":0,"Id":"5728510fe14d4b4034e3fc2b2d73b03a","Path":"<filepath>","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"asf","Size":3473995,"Name":"01 Welcome to New York","IsRemote":false,"ETag":"6017606e4337aeb8b2017a48e2c9415c","RunTimeTicks":2126010000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"mjpeg","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt470bg","ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":"Cover (front)","TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":500,"Width":500,"AverageFrameRate":null,"RealFrameRate":90000,"ReferenceFrameRate":90000,"Profile":"Baseline","Type":3,"AspectRatio":"1:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuvj420p","Level":-99,"IsAnamorphic":false},{"Codec":"wmav2","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Default","LocalizedForced":null,"LocalizedExternal":"External","LocalizedHearingImpaired":null,"DisplayTitle":"English - WMAV2 - 2 ch","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":128016,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":44100,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"ReferenceFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":130723,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":false}

C:\Program Files\Jellyfin\server\ffmpeg.exe -analyzeduration 200M -probesize 1G -async 1  -i file:"<filepath>" -map_metadata -1 -map_chapters -1 -threads 6   -vn -acodec m3u8 -ab 256000 -ac 2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "<jfprogramdata>\Server\transcoding-temp\4a93ae18eec611bcd53c348de03aa25a%d.mp3" -hls_playlist_type vod -hls_list_size 0 -y "<jfprogramdata>\Server\transcoding-temp\4a93ae18eec611bcd53c348de03aa25a.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with clang version 18.1.8
  configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[aist#0:1/wmav2 @ 000001fabd987d40] Guessed Channel Layout: stereo
Input #0, asf, from 'file:<filepath>':
  Metadata:
    WM/Track        : 0
    WM/MediaPrimaryClassID: {D1607DBC-E323-4BE2-86A1-48A42A28441E}
    WMFSDKVersion   : 12.0.9600.16384
    WMFSDKNeeded    : 0.0.0.0000
    PeakValue       : 32673
    AverageLevel    : 10107
    WM/EncodingTime : 18446744072793343616
    WM/Provider     : AMG
    WM/UniqueFileIdentifier: AMGa_id=R  3059013;AMGp_id=P   816977;AMGt_id=T 31420682
    WM/ProviderRating: 5
    WM/ProviderStyle: Pop/Rock
    DeviceConformanceTemplate: L1
    MediaFoundationVersion: 2.112
    album_artist    : Taylor Swift
    WM/Year         : 2019
    track           : 1
    publisher       : Big Machine Records
    album           : 1989
    genre           : Dance
    IsVBR           : 0
    MusicBrainz/Release Group Id: 4d9ec1c2-58ec-48a4-aa0a-916718adead0
    WM/OriginalReleaseTime: 2014-10-24
    WM/OriginalReleaseYear: 2014
    MusicBrainz/Album Type: album
    MusicBrainz/Album Id: e4417eaf-7a8c-40e2-8ae1-979f3c793157
    WM/CatalogNo    : 060254707166
    MusicBrainz/Album Status: official
    MusicBrainz/Album Release Country: BR
    MusicBrainz/Album Artist Id: 20244d07-534f-4eff-b4d4-930878889970
    WM/AlbumArtistSortOrder: Swift, Taylor
    WM/Barcode      : 602547071668
    WM/Script       : Latn
    disc            : 1/1
    WM/Media        : CD
    MusicBrainz/Track Id: 3c2fefb5-ca6a-4793-b044-babc85bed24e
    MusicBrainz/Artist Id: 20244d07-534f-4eff-b4d4-930878889970
    WM/ArtistSortOrder: Swift, Taylor
    WM/ARTISTS      : Taylor Swift
    WM/ISRC         : USCJY1431299
    MusicBrainz/Release Track Id: 22ea5028-2456-4b33-a9c2-897e153b461e
    composer        : Taylor Swift
    title           : Welcome to New York
    artist          : Taylor Swift
  Duration: 00:03:32.60, start: 0.000000, bitrate: 130 kb/s
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
  Stream #0:1(eng): Audio: wmav2 (a[1][0][0] / 0x0161), 44100 Hz, stereo, fltp, 128 kb/s
[aost#0:0 @ 000001fabf3eb740] Unknown encoder 'm3u8'
[aost#0:0 @ 000001fabf3eb740] Error selecting an encoder
Error opening output file <jfprogramdata>\Server\transcoding-temp\4a93ae18eec611bcd53c348de03aa25a.m3u8.
Error opening output files: Encoder not found
```

I've also tested this with other codecs (by forcing transcode via the ATV app) and the same issue applies for mp3 and others.

**Comment by oddstr13** [comment] 2024-10-31 17:00
Looks like it *does* specify codec… sort of.
`segmentContainer=mp3`
Only mpeg3 audio would be allowed there, to my knowledge?

I'd suggest implementing a workaround server-side, and tagging it as deprecated for removal with v11

**Comment by gnattu** [comment] 2024-10-31 17:11
`segmentContainer=mp3`

This is how everything becomes funny because the valid segment container for HLS is only mpegts and fmp4, which is `ts` and `mp4` in the `segmentContainer` respectively. We are doing the sanitation in the new `UniversalAudioController`:

https://github.com/jellyfin/jellyfin/blob/282784cbb6fe203b87a6f2c673454ac8d3da82fa/Jellyfin.Api/Controllers/UniversalAudioController.cs#L185-L197

But for clients using the HLS controller directly is responsible to make sure this field is correct and supported by HLS because those endpoints are dumb and will pass invalid options into the transcode manager.

I highly doubt if the old server behavior will even actually use mp3 as the transcoding codec, it might just picked some random default value like aac and stream it in mpegts container, but I have yet to debug with such request.

**Comment by nielsvanvelzen** [comment] 2024-10-31 18:12
The server literally does the same, when I request media info it sets the segment container to mp3 in the returned transcode URL.

```
/audio/<itemid>/master.m3u8?DeviceId=<deviceid>&MediaSourceId=<itemid>&AudioBitrate=128000&PlaySessionId=<sessionid>&api_key=<topsecret>&RequireAvc=false&EnableAudioVbrEncoding=true&Tag=<tag>&SegmentContainer=mp3&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerNotSupported, VideoCodecNotSupported, AudioCodecNotSupported
```

^ This is the sanitized URL returned by the server, it's pretty much the same and triggers the exact same issue.

**Comment by gnattu** [comment] 2024-10-31 19:16
The `getPostedPlaybackInfo` does not do sanitation, only the `UniversalAudioController` does, so if your client profile contains incorrect transcoding profile for hls it will generate an incorrect transcoding url.

A valid `TranscodingProfile` entry for HLS audio should look like this:

```
{
        "Container": "mp4",
        "Type": "Audio",
        "AudioCodec": "aac",
        "Context": "Streaming",
        "Protocol": "hls",
        "MaxAudioChannels": "6",
        "MinSegments": "2",
        "BreakOnNonKeyFrames": true,
        "EnableAudioVbrEncoding": true
}
```

So I *still* think this is more of a client issue rather than the server issue, unless the url generated from correct profile is not working either.

However, I do see a larger issue here. During the 10.10 cycle, @Shadowghost, @dmitrylyzo, and I made substantial `StreamBuilder` cleanups based on what we believed to be correct usage, even adding new unit tests to cover more cases. However, client behavior has diverged significantly from our expectations. Many clients may not use the API as intended due to poor documentation, leading developers to assume that the undefined behaviors making their clients work are actually correct.

If even one of our official clients hasn't specified the correct transcoding profiles for years, it's hard to imagine how many third-party clients might be using it incorrectly. Unfortunately, moving forward without breaking these clients will be impossible, as creating a "compatibility layer" to re-implement old undefined behaviors would be extremely unmaintainable. The best thing we can do here is likely to improve our documentation for complex APIs like playback ones to avoid future confusion among client developers.

**Comment by nielsvanvelzen** [comment] 2024-10-31 21:32
After more discussion in chat we figured out a few things:

- Music transcoding is likely somewhat since 10.9
- In 10.10 the "AudioCodec" parameter must be sent, this fixed my issue in the Android TV app
- The media info API returns an invalid transcoding URL

Leaving the issue open for the remaining problems.

**Comment by gnattu** [comment] 2024-11-06 22:33
Closing as the transcoding url returned by the media info url is fixed and the audiocodec query requirement is on purpose.

**Closed by gnattu** 2024-11-06 22:33 UTC
