### ISSUE TITLE
"/transcodes" being naïvely appended to "transcode path" setting

### ISSUE THREAD

**Issue by richardbrodie** [jellyfin/jellyfin#1988] opened 2019-11-06 20:21 UTC
**Describe the bug**
In the "playback/transcoding" settings page, whatever is entered into the "transcode path" setting will have "/transcodes" appended to it when the settings are saved, resulting in "/whatever/transcodes". If I go back to the page again and press save again then "/transcodes" is again appended, resulting in "/whatever/transcodes/transcodes".

**To Reproduce**

1. Go to 'Playback'
2. Click on 'Transcoding'
3. Scroll down to 'transcode path'
4. Enter "/transcode"
5. Click on Save at the bottom of the page
6. Press save again
7. Go to Dashboard
8. See that the "Transcodes" path at the bottom of the page says "/transcode/transcodes/transcodes"

**Expected behavior**
Jellyfin should probably not append anything automatically to the path the user sets, if I set the path to be "/transcode" then I expect the transcoded files to be placed there. If Jellyfin absolutely must append a specific folder name then it should detect whether the path already ends with that folder and then do nothing.

**System (please complete the following information):**
 - OS: Docker on Debian
 - Browser: Firefox 70
 - Jellyfin Version: 10.4.1
 - Reverse proxy: traefik

**Comment by anthonylavado** [comment] 2019-11-07 18:03
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/527, but you do have way more information. Adding a link to the other thread.

**Comment by MasterCATZ** [comment] 2019-11-08 04:06
Noticed this last night paths were over 20 deep and had to prune them back 
/transcode/transcode/transcode/transcode/transcode/transcode/transcode ...

**Comment by joshuaboniface** [comment] 2019-11-08 04:17
The appended `/transcodes` has, AFAIK, always been there back to Emby days. That said the duplications are not ideal of course, and I agree with the idea here that it should just be put right in the folder specified.

**Comment by kkasberg** [comment] 2019-11-18 15:32
I am having this issue too.

**Closed** 2019-11-24 20:13 UTC
Labels: bug, duplicate

**Comment by JustAMan** [comment] 2019-11-25 11:42
Note that, while the issue is closed, the fix is not available in 10.4.2. Would probably available be in next release.
