### ISSUE TITLE
[Issue]: Cast/Crew metadata is now useless. Metadata providers now list producers first, so producers are the only ones ever shown.

### ISSUE THREAD

**Issue by Overwatching** [jellyfin/jellyfin#9966] opened 2023-07-04 23:43 UTC
### Please describe your bug

Since early 2023, Metadata providers are listing producer/financier positions first in the cast/crew sections. This results in ONLY those positions ever being saved to local Metadata, unless the maximum cast/crew saved is set to a ridiculously high number like 999.

The cast/crew for any new show will just be a list of producers, co-producers, executive producers, co-executive producers, etc.

I expect the cast/crew section to show the most relevant on-screen actors.
If I care to see who did the lighting, who catered the reshoot, or who did the marketing in Antarctica I'll open a browser and go to TMDB or some other provider.
The only reason to even have cast/crew metadata on a tv/device is when you wonder "Hey! Is that...? Yeah I thought I recognized their voice."

Even if I were to manually delete the producers, I can't pull new cast/crew to get the relevant actors, since the Metadata will just get repopulated with the producers again until the slots fill up.

There have been several other issues with Metadata in the last few years, but this one REALLY highlights the need for a blacklist/whitelist for metadata.

We NEED a way to say "No, don't save that. I don't want that metadata. Don't put that in my database or .nfo"

Right now little to no manipulation is being done to the metadata before it is saved locally.

### Jellyfin Version

10.8.z

### Environment

```markdown
N/A Everything effected.
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Overwatching** [comment] 2023-07-04 23:45
This is not a bug. It is a core interoperability/function problem.

But I can't remove the bug label...

**Comment by srcrist** [comment] 2023-10-06 22:36
Closing this issue as it is a feature request and not a bug. Please submit feature requests to features.jellyfin.org. The github issues are for bug reports only.

**Closed by srcrist** 2023-10-06 22:36 UTC
Labels: bug

**Comment by Overwatching** [comment] 2023-10-06 23:11
> Closing this issue as it is a feature request and not a bug. Please submit feature requests to features.jellyfin.org. The github issues are for bug reports only.

It isn't a code bug.
It is a design bug for a feature currently in Jellyfin.

You already pull metadata from a database.
You use that metadata.
But the database has changed how it formats the data, so it isn't usable.
Your code "works". It just doesn't do what is intended anymore, unless the intent of parsing cast/crew is to return a list of the first 50 producers.

**Comment by srcrist** [comment] 2023-10-06 23:17
It's not my code, it's everyone's code. But the github issues are for the code bugs, as you say. If you think the functionality of a particular metadata provider can be improved, just create a feature request so that someone who is interested in hacking at it can make the improvements.

**Comment by Overwatching** [comment] 2023-10-07 00:00
> It's not my code, it's everyone's code. But the github issues are for the code bugs, as you say. If you think the functionality of a particular metadata provider can be improved, just create a feature request so that someone who is interested in hacking at it can make the improvements.

1. I was using the inclusive "you" as you are, obviously, a moderator. I'm aware of how a project like Jellyfin works.
2. I'm not making a 3rd party account unless it is strictly necessary for the core functionality of a service to function. "Reporting problems" is not a core function.
3. This is an "issue", not a feature request. At some point there is an overlap between code and functionality. If an API gets changed causing an error, but your code still gracefully handles and displays that error, there is still a problem. Your code might be "correct" and doing what you asked it to do, but the feature no longer does it's job, which is an issue.

This is an issue, problem, bug, or whatever else you want to call it.
A portion of the UI is now filled with useless information where something else used to be displayed.

This issue COULD be solved by adding a (much needed) feature.
It could also be solved in other ways.

The point is that it needs to be actively solved, because something outside the control of the project was changed.


I am an admin not a programmer.
I'm doing my job by reporting a problem I encountered, so it can be fixed.

**Comment by sevenrats** [comment] 2023-10-07 00:34
what client is this happening on?  this issue belongs in that client's repo. how the api info gets displayed is done there. make sure you include an example title and metadata provider so that somebody can try and reproduce your experience.

**Comment by srcrist** [comment] 2023-10-07 00:39
I am unable to even replicate the results that you are seeing to confirm this as a bug.

![image](https://github.com/jellyfin/jellyfin/assets/29871690/7d37c697-90d3-4d15-a5d2-9a11618faa2e)

![image](https://github.com/jellyfin/jellyfin/assets/29871690/d08bc29c-99ce-4259-9027-1b8732db3a72)

These are both films released in 2023, and both are using the TMDB provider. Both have the primary actors as the first cast & crew. 

I'm going to leave this issue closed for now. If you want to head over to the troubleshooting spaces on the forums or the Matrix/Discord servers we can see if someone can help you figure out why your provider is working as it is. But it we can't find a problem that occurs regardless of configuration, there's not much to fix from an issue perspective. By your own admission, this isn't really a bug--and this space is for bugs.

If you find a way to provide a configuration-independent way to reproduce the problem you're seeing, I'll reopen and refile it for testing and investigation.

**Comment by Overwatching** [comment] 2023-10-07 01:03
> If you find a way to provide a configuration-independent way to reproduce the problem you're seeing, I'll reopen and refile it for testing and investigation.

I'm in the middle of an entire HomeLab and network changeover.
New NAS. New Server. New Switches. Running new cabling in the walls. Even new power/UPS.
When everything is up and running again in a week or so I'll get you more information.

Until then, I'm positive this is reproducible because I was running 3 Jellyfin servers, Windows, Linux, and a Docker container, and it happened on all of them.
It happened for every single movie and show I added, from about mid February onward. (Maybe not Anime?)

**Comment by srcrist** [comment] 2023-10-07 01:06
If might only be reproducible with your specific provider configuration, though. That's why I think the best idea here is to go to the support spaces first and let someone help you look at them in real time. It might be as simple as a provider priority change or something. It doesn't seem to happen to everyone who is using the same provider, even. 

Sevenrats above is also saying that this order is a matter of client code. So it might be the case that this is a client-specific issue as well, in which case, this is the wrong repository anyway. 

Either way, get your network set up and retest and we'll go from there.

**Comment by Overwatching** [comment] 2023-10-07 01:35
I just spun up a new windows server and a docker one.
Happens in both.

Steps to reproduce...

1. Create a movie library linked to a folder.
3. Keep the default TMDB and OpenMovieDatabase metadata providers.
4. Save data locally as nfo. (likely unneeded but it is what I do.)
5. Create a folder in your library named `Fast X (2023)`.
6. Create a txt file in that folder named `null.mkv`.
7. Scan library.

The default metadata providers return a list of cast/crew.
That list, since early 2023, begins with Producers.
After a certain number, the plugin stops adding cast/crew to the local database.

I'm attaching the actual nfo I got from this process renamed to .txt
[null.nfo.txt](https://github.com/jellyfin/jellyfin/files/12836270/null.nfo.txt)

**Comment by srcrist** [comment] 2023-10-07 01:37
What client?

**Comment by srcrist** [comment] 2023-10-07 01:38
And, to be clear, is the issue here the way that they appear in your NFO files, or the way that they appear in your UI?

**Comment by Overwatching** [comment] 2023-10-07 01:43
This is the server itself.
It has nothing to do with a client.

This is an issue with the way metadata plugins are handling cast/crew metadata fetched from a metadata provider.

**Comment by sevenrats** [comment] 2023-10-07 01:45
> This is the server itself. It has nothing to do with a client.

this doesn't really make sense.  are you referring to the web-app then?

**Comment by srcrist** [comment] 2023-10-07 01:46
Jellyfin uses a client/server model. There is always a client. If you are talking about using the browser on the server, that would be the web client.

**Comment by srcrist** [comment] 2023-10-07 01:49
> I just spun up a new windows server and a docker one. Happens in both.
> 
> Steps to reproduce...
> 
>     1. Create a movie library linked to a folder.
> 
>     2. Keep the default TMDB and OpenMovieDatabase metadata providers.
> 
>     3. Save data locally as nfo. (likely unneeded but it is what I do.)
> 
>     4. Create a folder in your library named `Fast X (2023)`.
> 
>     5. Create a txt file in that folder named `null.mkv`.
> 
>     6. Scan library.
> 
> 
> The default metadata providers return a list of cast/crew. That list, since early 2023, begins with Producers. After a certain number, the plugin stops adding cast/crew to the local database.
> 
> I'm attaching the actual nfo I got from this process renamed to .txt [null.nfo.txt](https://github.com/jellyfin/jellyfin/files/12836270/null.nfo.txt)

I am still unable to replicate this issue with the steps you've included for reproduction:

![image](https://github.com/jellyfin/jellyfin/assets/29871690/99542e67-92eb-4c54-b8de-f483110ed956)

**Comment by srcrist** [comment] 2023-10-07 01:52
I have a theory. Delete the movie from your test library, turn off NFO metadata, and try adding the movie again. Does it still happen?

**Comment by Overwatching** [comment] 2023-10-07 02:14
Yes it happens without the nfo too.
![Screenshot Capture - 2023-10-06 - 22-11-14](https://github.com/jellyfin/jellyfin/assets/8674503/6bf95969-b2c6-435d-b8d7-a2450382caba)

Note: the top 5 "people" are from further up on the metadata and get their own tags.

**Comment by Overwatching** [comment] 2023-10-07 02:22
Okay...there is a newer Windows version that I was using.
I was on 10.18.10 from a few weeks ago.

10.18.11 was released last week.

Pretty sure the Docker version was freshly pulled though. It should be the current version.

**Comment by sevenrats** [comment] 2023-10-07 02:31
Will you please attach a screenshot of this issue happening? We still aren’t even sure what you are experiencing.

**Comment by srcrist** [comment] 2023-10-07 02:35
The order is not ideal. But I also can't even replicate their order. Nothing that I do makes it show up like they have it.

**Comment by Overwatching** [comment] 2023-10-07 02:44
@srcrist The order you see is the same as it is stored in the local database, whether internal or the nfo.

Clients redner it based on their own internal scheme, but at least you HAVE the actor data, which I don't.

Your actor data also has `<sortorder>0</sortorder>` tags, which mine does not.
Which is weird.

Something funky is going on.
I'll try this in a fresh VM with a fresh download later.
Maybe this was fixed/changed in v10.18.11?
I looked through **jellyfin / TMDbLib** but not much has changed in years.

I'll check back in later with more info as I get it.

**Comment by srcrist** [comment] 2023-10-07 02:48
Go ahead and test is on a fresh VM, but I was actually originally on 10.8.9 when I started testing this and it wasn't happening then either. So I don't think this is a recent fix. It may be something related to your settings. But I can't even force it to do what you're getting.

**Comment by Overwatching** [comment] 2023-10-07 03:13
It was a fresh install of v10.18.10 on a machine that I don't think has ever had a Jellyfin server on it.
All the settings were fresh out of the box.

**Comment by 1337joe** [comment] 2023-10-07 03:15
Check your TMDB plugin settings (Dashboards > Plugins > TMDB): there's a "Max Cast Members" setting that could be limiting how many cast members are downloaded. I have mine set to 1000 but it could be that the default is too low.

**Comment by srcrist** [comment] 2023-10-07 03:16
There are some regions where some metadata providers are blocked. It might be the case that one is blocked for you? I really don't know. Again, this sort of issue would be best solve in real-time in one of the troubleshooting spaces.



> Check your TMDB plugin settings (Dashboards > Plugins > TMDB): there's a "Max Cast Members" setting that could be limiting how many cast members are downloaded. I have mine set to 1000 but it could be that the default is too low.

The test instance I used only had the default of 15, and it still correctly grabbed the actors:

![image](https://github.com/jellyfin/jellyfin/assets/29871690/87b9105b-22f6-4d13-9bdc-25e5f227dfe3)
