### ISSUE TITLE
[Issue]: Profile Settings Are Not Saved

### ISSUE THREAD

**Issue by jwor80** [jellyfin/jellyfin#6943] opened 2021-12-05 16:57 UTC
### Please describe your bug

Log into Jellyfin from chrome on a windows device.  Go to Settings > Home and change my layout, save the changes, and return the to main window I see the changes. If I go back into Settings > Home my layout changes are no longer there.  I have also noticed when I go into a library and re-arrange the display to something like sort by date added.  Go back to the main screen then back into the library the sort order is reset back to the default.

### Jellyfin Version

Other

### if other:

10.8 alpha2

### Environment

```markdown
- OS: Windows 10
- Virtualization:
- Clients:Browser
- Browser:Chrome 
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2021-12-05 17:02
Duplicate of https://github.com/jellyfin/jellyfin/issues/6875
Fixed by https://github.com/jellyfin/jellyfin/pull/6854

**Closed by crobibero** 2021-12-05 17:02 UTC
Labels: bug
