### ISSUE TITLE
Jellyfin 10.7~RC3 doesn't start

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#5249] opened 2021-02-16 20:58 UTC
**Describe the bug**
Jellyfin doesn't start on Windows. After startup, Jellyfin immediately shuts itself down because of the following exception:

> System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IService' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.

**System:**
 - OS: Windows 10 64bit
 - Virtualization: none
 - Jellyfin Version: 10.7~RC3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: Opensubtitles, last.fm
 - Reverse Proxy: caddy
 - Storage: local

**To Reproduce**
1. Lauch the tray app.
2. Right-click on the tray app, then click on "Start Jellyfin".
3. See jellyfin.exe appear then immediatly disappear from the task manager

**Expected behavior**
Jellyfin should start as usual.

**Logs**
[Log](https://pastebin.com/SxEDmbVC)

**Additional context**
This happens after upgrading from 10.6.4.

**Comment by crobibero** [comment] 2021-02-16 21:26
Duplicate of https://github.com/jellyfin/jellyfin/issues/4690

**Closed by crobibero** 2021-02-16 21:26 UTC
Labels: bug
