### ISSUE TITLE
[Issue]: VAAPI H.264 transcode fails

### ISSUE THREAD

**Issue by avorima** [jellyfin/jellyfin#7918] opened 2022-06-13 12:31 UTC
### Please describe your bug

I'm running jellyfin in a container and I use an Android TV with the jellyfin app as client. I noticed that .mkv files could not be played on the TV anymore. Playing in the browser still works. Looking at the logs I see that ffmpeg fails trying to transcode. It only started a few days ago around the time 10.8.0 came out.

When I roll back to 10.7.7 I can't login anymore.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: Android TV
- Browser:
- FFmpeg Version: 5.0.1
- Playback Method: Transcode
- Hardware Acceleration: VAAPI
- Plugins: Some from the stable repo
- Reverse Proxy: none
- Base URL: none
- Networking: Bridge
- Storage: local
```

### FFmpeg logs

```shell
/videos/333a8dd4-f36f-874a-e9d8-7d376b38fde4/stream.mkv

{"Protocol":0,"Id":"333a8dd4f36f874ae9d87d376b38fde4","Path":"/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":3519614976,"Name":"Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p","IsRemote":false,"ETag":"b61e560f0bb7a374f6c68d47a77a0b5c","RunTimeTicks":26451099648,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"h264","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p H264 SDR","NalLengthSize":"0","IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":10644895,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":41,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"English - DTS - 5.1 - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":1536000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"English - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"SDH","VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"SDH - English - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"sub","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Undefined - SUB - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":true,"Path":"/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.sub","PixelFormat":null,"Level":null,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":12180895,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -canvas_size 1920x1080 -i file:"/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.mkv" -canvas_size 1920x1080 -i file:"/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.idx" -map 0:0 -map 0:1 -map 1:0 -sn -codec:v:0 h264_vaapi -force_key_frames "expr:gte(t,n_forced*5)" -filter_complex "[1:0]scale=s=1920x1080:flags=fast_bilinear[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12,hwdownload,format=nv12[main];[main][sub]overlay=eof_action=pass:shortest=1:repeatlast=0,hwupload_vaapi" -copyts -avoid_negative_ts disabled -rc_mode VBR -b:v 10644895 -maxrate 10644895 -bufsize 21289790 -profile:v:0 high -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ac 6 -ab 640000 -y "/transcode/266d452ba6301f8b2f6c9e4a7a851976.mkv"


ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3 --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, matroska,webm, from 'file:/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.mkv':
  Metadata:
    encoder         : no_variable_data
    creation_time   : 1970-01-01T00:00:00.000000Z
  Duration: 00:44:05.11, start: 0.000000, bitrate: 10644 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 55.764000
      Metadata:
        title           : 00:00:00.000
    Chapter #0:1: start 55.764000, end 226.101000
      Metadata:
        title           : 00:00:55.764
    Chapter #0:2: start 226.101000, end 629.921000
      Metadata:
        title           : 00:03:46.101
    Chapter #0:3: start 629.921000, end 936.227000
      Metadata:
        title           : 00:10:29.921
    Chapter #0:4: start 936.227000, end 1661.285000
      Metadata:
        title           : 00:15:36.227
    Chapter #0:5: start 1661.285000, end 1972.345000
      Metadata:
        title           : 00:27:41.285
    Chapter #0:6: start 1972.345000, end 2253.460000
      Metadata:
        title           : 00:32:52.345
    Chapter #0:7: start 2253.460000, end 2606.979000
      Metadata:
        title           : 00:37:33.460
    Chapter #0:8: start 2606.979000, end 2645.110000
      Metadata:
        title           : 00:43:26.979
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 9133185
      BPS-eng         : 9133185
      DURATION        : 00:44:05.101000000
      DURATION-eng    : 00:44:05.101000000
      NUMBER_OF_FRAMES: 63419
      NUMBER_OF_FRAMES-eng: 63419
      NUMBER_OF_BYTES : 3019774826
      NUMBER_OF_BYTES-eng: 3019774826
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Metadata:
      BPS             : 1508999
      BPS-eng         : 1508999
      DURATION        : 00:44:05.110000000
      DURATION-eng    : 00:44:05.110000000
      NUMBER_OF_FRAMES: 247979
      NUMBER_OF_FRAMES-eng: 247979
      NUMBER_OF_BYTES : 498933748
      NUMBER_OF_BYTES-eng: 498933748
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip, 1920x1080
    Metadata:
      BPS             : 62
      BPS-eng         : 62
      DURATION        : 00:44:00.513000000
      DURATION-eng    : 00:44:00.513000000
      NUMBER_OF_FRAMES: 580
      NUMBER_OF_FRAMES-eng: 580
      NUMBER_OF_BYTES : 20768
      NUMBER_OF_BYTES-eng: 20768
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip, 1920x1080
    Metadata:
      title           : SDH
      BPS             : 67
      BPS-eng         : 67
      DURATION        : 00:44:00.513000000
      DURATION-eng    : 00:44:00.513000000
      NUMBER_OF_FRAMES: 658
      NUMBER_OF_FRAMES-eng: 658
      NUMBER_OF_BYTES : 22363
      NUMBER_OF_BYTES-eng: 22363
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Input #1, vobsub, from 'file:/library/tv/Gotham/Season 2/Gotham - S02E06 - Rise of the Villains - By Fire Bluray-1080p.idx':
  Duration: N/A, bitrate: N/A
  Stream #1:0[0x0](en): Subtitle: dvd_subtitle, 1920x1080 (default)
  Stream #1:1[0x1](fr): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:2[0x2](es): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:3[0x3](pt): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:4[0x4](pt): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:5[0x5](nl): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:6[0x6](sv): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:7[0x7](no): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:8[0x8](da): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:9[0x9](fi): Subtitle: dvd_subtitle, 1920x1080
  Stream #1:10[0xa](ko): Subtitle: dvd_subtitle, 1920x1080
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
Stream mapping:
  Stream #0:0 (h264) -> setparams:default (graph 0)
  Stream #1:0 (dvdsub) -> scale:default (graph 0)
  hwupload_vaapi:default (graph 0) -> Stream #0:0 (h264_vaapi)
  Stream #0:1 -> #0:1 (dts (dca) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[vobsub @ 0x557dc69cbec0] sub2video: using 720x576 canvas
[h264_vaapi @ 0x557dc6dc74c0] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x557dc6dc74c0] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x557dc6dc74c0] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:0 -- 
[libfdk_aac @ 0x557dc6e8e640] 2 frames left in the queue on closing
Conversion failed!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment] 2022-06-13 12:57
duplicate of #7642

**Closed as not planned by nyanmisaka** 2022-06-13 12:57 UTC
Labels: bug
