### ISSUE TITLE
[Issue]: Actor images are missing when using only local metadata or downloading them

### ISSUE THREAD

**Issue by RainyDAy59** [jellyfin/jellyfin#8354] opened 2022-09-03 02:18 UTC
### Please describe your bug

Tried numerous times over several days to solve this myself, but I'm just stuck and hoping for some help.  I've had to manually click on the image avatar box in order for the actor's photo to load, which is a tedious procedure.  Sometimes a few are missing and other times all of them are missing.  I'd like to use my local metadata, which was set up previously with Kodi, so the images are located within each show or movie in a folder called .actors.  I rescanned the libraries several times, but I'm still not having much success (if any).  I even removed the libraries entirely, cleared the cache, closed Jellyfin, and then set it all up from scratch again, but I have had no better results.  I then tried downloading the images from the various image providers, but that didn't change anything either.  I did see this was a possible bug that was fixed by the version of Jellyfin I'm using, but it's sure not loading images as I'd expect.  Not sure this would show up in any logs so haven't included them.  

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS:  Windows
- Virtualization:  None
- Clients:  Firestick, Browser (Brave, Google Chrome)
- Browser:  Windows 10
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:  Fanart.TV, TV Maze, TMDB
- Reverse Proxy:  None
- Base URL:
- Networking:  Host
- Storage:  local
```

### Please attach any screenshots here

![ActorImages](https://user-images.githubusercontent.com/112738403/188252016-418c0e96-8fd1-4b0a-9f7e-a52c0a4708da.JPG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-09-03 02:23
Duplicate of https://github.com/jellyfin/jellyfin/issues/8103

**Closed by crobibero** 2022-09-03 02:23 UTC
Labels: bug

**Comment by herigrosir** [comment] 2024-07-17 08:08
Your answer is here, hopefully you can answer it

https://forum.jellyfin.org/t-how-to-solve-photo-actor-not-showing
