### ISSUE TITLE
Last activity about in users does not fit

### ISSUE THREAD

**Issue by RecoX** [jellyfin/jellyfin#13298] opened 2024-12-30 03:19 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

![Image](https://github.com/user-attachments/assets/f728c0f4-7104-4ad3-b417-f02ea1c09b17)

It should show the whole text or reduce the size of font 

### Reproduction steps

Go to users page in admin

### What is the current _bug_ behavior?

It does not display properly the last activity text

### What is the expected _correct_ behavior?

Display it full

### Jellyfin Server version

10.10.0+

### Specify the build version

last one

### Environment

```markdown
Linux CasaOS
```

### Jellyfin logs

```shell
n/a
```

### FFmpeg logs

```shell

```

**Comment by thornbill** [comment] 2024-12-30 03:52
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5608

**Closed** 2024-12-30 03:53 UTC
Labels: bug, duplicate, ui & ux
