### ISSUE TITLE
Manually (portable) zip file does not contain jellyfin.exe

### ISSUE THREAD

**Issue by MarkRK** [jellyfin/jellyfin#12451] opened 2024-08-14 18:11 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I am trying to use the portable version of JellyFin for windows. The install instructions (https://jellyfin.org/docs/general/installation/windows#install-manually-portable) lets you create a batch file which should start the jellyfin.exe. When you run the batchfile you get an error 'jellyfin.exe is not recognized....' 
I have searched all subdirs and downloaded older versions. But nowhere is jellyfin.exe to be found. 
Are the instructions not up to date or is the exe not supplied in de zip file?

### Reproduction steps

Download the latest stable jellyfin.zip file. Search in the zipfile for jellyfin.exe (or any other exe).

### What is the current _bug_ behavior?

Jellyfin.exe not found.

### What is the expected _correct_ behavior?

Jellyfin.exe should be available or the install instructions should be altered.

### Jellyfin Server version

10.9.9+

### Specify the build version

?

### Environment

```markdown
- OS: Windows
```

### Jellyfin logs

```shell
-
```

**Comment by crobibero** [comment] 2024-08-14 18:18
Duplicate of https://github.com/jellyfin/jellyfin-packaging/issues/35

**Closed by crobibero** 2024-08-14 18:18 UTC
Labels: bug
