### ISSUE TITLE
shows wont finish transcode after upgrade to 10.8.0 from 10.7.7

### ISSUE THREAD

**Issue by m33hack** [jellyfin/jellyfin#7908] opened 2022-06-13 04:00 UTC
I upgraded my server installation and now when streaming certain mp4/MKV files the stream will exit and skip to the next episode. if i play the files without ffmpeg conversion they seem to work fine. I’ve looked though my log and find that ffmpeg is receiving the [q] command or exiting with return code 0. I'm not super tech savvy but I’ve attached relevant log-files. Is there any safe way to downgrade to 10.7.7 this bug breaks functionality needed for my use case?
ffmpeg log #1: trying to play the file normally until the 19:55ish mark
ffmpeg log #2: attempting to stream jump to anywhere in the video past the 19:55ish mark
main log: ffmpeg exits and complains of slow http response despite tests being conducted on localhost I get the following

 "Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "***/videos/1e5343c4-885f-a379-dc64-985be2525e9e/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDExKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTAyLjAuNTAwNS43OCBNb2JpbGUgU2FmYXJpLzUzNy4zNnwxNjU1MDA0MDg4NjQw&MediaSourceId=1e5343c4885fa379dc64985be2525e9e&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=656001&AudioBitrate=63999&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=2340&PlaySessionId=a69e3891364543a6b064dcfe2e41fcbf&api_key=6f97bd8908ce435e877f2c92b675d602&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=16aa58e98869e2a0fb53c919c02f914a&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=40&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=2&aac-profile=he-aac&h264-deinterlace=true&TranscodeReasons=ContainerBitrateExceedsLimit&runtimeTicks=0&actualSegmentLengthTicks=50050000" to "216.200.84.39" in 0:00:01.2655124 with Status Code 200"

anecdotal: testing different shows in mkv/mp4 with h264 yields different results without many correlations (i.e some will transcode fine regardless of codec or container especially if starting from a lower quality, while 720+ sources seem to fail no matter what quality i drop it to and will only play through if set to direct)

EDIT: add MKV files using h264 avc1 to affected file-types 
OS:WIN10 PRO 64
GPU: amd rx580 with hardware decoding enabled in JF
Browsers: both Firefox and Brave Desktop and mobile same results
JF: v 10.8.0

much much love to jellyfin <3

[FFmpeg.Transcode-2022-06-12_22-41-56_1e5343c4885fa379dc64985be2525e9e_62f5573e.log](https://github.com/jellyfin/jellyfin/files/8887797/FFmpeg.Transcode-2022-06-12_22-41-56_1e5343c4885fa379dc64985be2525e9e_62f5573e.log)
[FFmpeg.Transcode-2022-06-12_22-42-05_1e5343c4885fa379dc64985be2525e9e_bd75c016.log](https://github.com/jellyfin/jellyfin/files/8887798/FFmpeg.Transcode-2022-06-12_22-42-05_1e5343c4885fa379dc64985be2525e9e_bd75c016.log)
[log_20220612.log](https://github.com/jellyfin/jellyfin/files/8887799/log_20220612.log)

**Comment by cvium** [comment] 2022-06-13 08:36
Duplicate of https://github.com/jellyfin/jellyfin/issues/6957

**Closed by cvium** 2022-06-13 08:36 UTC
