### ISSUE TITLE
Playback intermittently stops and skips to next episode

### ISSUE THREAD

**Issue by Mustachipleb** [jellyfin/jellyfin#7987] opened 2022-06-20 21:25 UTC
Related to #7296
Should have been fixed in 10.8 but seems to still be happening.

Log (Around 13:45 mark):
[log_20220618.log](https://github.com/jellyfin/jellyfin/files/8933489/log_20220618.log)
FFMPEG Log:
[FFmpeg.Transcode-2022-06-18_13-11-47_69ebb3a677cfe2cd5eb94f65aa03203e_bd006c25.log](https://github.com/jellyfin/jellyfin/files/8933490/FFmpeg.Transcode-2022-06-18_13-11-47_69ebb3a677cfe2cd5eb94f65aa03203e_bd006c25.log)

Server System:
- OS: Docker on Ubuntu 20.04
- Jellyfin Version: 10.8.0
- Hardware settings & device: Intel Core i7-6700K, HWA with GTX 1070 (Driver ver. 510.73.08)
- Reverse proxy: Traefik (Logs are from local playback but problem persists across both proxied and non-proxied connections)

Client System:
- Device: AMD Ryzen 5 5600X + RTX 3080
- OS: Windows 10 Build 19044
- Client: Edge v102.0.1245.41

Created from [my comment in #7296](https://github.com/jellyfin/jellyfin/issues/7296#issuecomment-1159454440)

**Comment by cvium** [comment] 2022-06-20 21:31
Probably a duplicate of #6957

**Closed by cvium** 2022-06-20 21:31 UTC
