### ISSUE TITLE
FYI: 404s and errors from Repository server post migration

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#11134] opened 2024-03-09 18:48 UTC
This is an FYI issue.

Last night we cut over to our new repository server for our new CI. Details are in the blog post here: https://jellyfin.org/posts/new-ci-new-repo

It was a big complex move, and it's inevitable I missed some things. So, if you're having issues with 404s or other strange anomalies on the repo server, please use this issue to discuss them and I'll fix what I can.

One thing to note is that I do see a lot of hits for very old Ubuntu releases, going back 3 years. As of right now, we are only supporting the LTS releases (`bionic`, `focal`, and `jammy`) and `mantic` right now. If you're using an end-of-support Ubuntu release, the repo WILL 404 for you and you are advised to update to a current release. As detailed in the blog post, 10.9.0 will drop support for `bionic` and `mantic` while adding support for `noble` when it comes out, so be forewarned to update your Jellyfin server (or switch to Docker etc.) when the time comes.

**Comment by apuntigam** [comment] 2024-04-15 11:30
I hope this is the right place to post... if not, please point me in the right direction and you may delete.

I have jellyfin running in a PVE linux container, Ubuntu 23.04 Lunar.  Since the new repo migration, I cannot update jellyfin.  I get the following when running apt update:
Hit:1 http://archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu lunar-security InRelease
Ign:4 https://repo.jellyfin.org/ubuntu lunar InRelease
Err:5 https://repo.jellyfin.org/ubuntu lunar Release
  404  Not Found [IP: 68.183.204.194 443]
Reading package lists... Done
E: The repository 'https://repo.jellyfin.org/ubuntu lunar Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Is this something I need to fix on my side, or something that needs to be fixed on your side in the repo?

**Comment by howellrl** [comment] 2024-04-28 22:59
I'm wondering if this is why I'm getting a 404 when trying to run the build-jellyfin PowerShell script with the -InstallFFMPEG option set. It's trying to access this: https://repo.jellyfin.org/releases/server/windows/ffmpeg/jellyfin-ffmpeg.zip and it's getting a 404.

**Comment by Fabien98** [comment] 2024-05-17 11:03
I'm having a weird issue with the new Lyrics API Endpoint.

- Jellyfin server is 10.9.1
- The .lrc file is next to the .mp3 file.
- filenames are the same and with proper formatting

When Music Android app (Symfonium) try to fetch Lyrics:
`--> [346] GET http://_LOCALROUTERADRESS_/audio/5224c13d32efb3fa817ce53e1b95b8f4/Lyrics`
`<-- [346] 404 Not Found http://_LOCALROUTERADRESS_/audio/5224c13d32efb3fa817ce53e1b95b8f4/Lyrics (87ms, unknown-length body)`

I precise that it happens quite randomly since other songs show lyrics flawlessly (?)

I could provide more logs if necessary if you tell me where to grab them.

**Comment by felix920506** [comment] 2024-05-17 12:19
@Fabien98 please open a new issue instead of commenting on a totally unrelated issue.

**Comment by crobibero** [comment] 2024-05-17 12:52
Yes, this is off-topic. 

The issue is about the repository where Jellyfin hosts installation resources and has nothing to do with music or lyrics.

**Comment by Fabien98** [comment] 2024-05-17 12:54
> Yes, this is off-topic.
> 
> The issue is about the repository where Jellyfin hosts installation resources and has nothing to do with music or lyrics.

Ok sorry then,
I open a new issue

**Comment by Technetium1** [comment] 2024-06-06 22:50
https://repo.jellyfin.org/releases/server/ should redirect to https://repo.jellyfin.org/?path=/server or else 404, and the same with subdirectories. Instead, it's still pointing to this very old one https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13. This leads people checking via the old URL to not get new releases, or not realize that their scripts need updated to the new location.

**Comment by Quessso** [comment] 2024-08-02 07:58
System:  Ubuntu 24.04 LTS X64
Running bash:

> Mistake:12 https://ppa.launchpadcontent.net/flexiondotorg/nvtop/ubuntu noble Release
>   404  Not Found [IP: 2620:2d:4000:1::81 443]
> Doen't doesnt have "Release" 

Im try swith IP Address ,cant work

**Closed** 2024-09-01 18:33 UTC
