### ISSUE TITLE
Deleting collection is not removed from data

### ISSUE THREAD

**Issue by bamnoru** [jellyfin/jellyfin#1055] opened 2019-03-07 13:38 UTC
**Describe the bug**
When deleting a collection, after a refresh of the library, collection is still in the library.

**To Reproduce**
1. Create a new collection.
2. Delete this collection.
3. Refresh metadata of the collection library
4. Browse the collection library, the collection is still here

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Jellyfin Version: 10.2.2

**Additional context**
After deleting the collection, the directory created for this collection is not deleted in 
C:\Users\...\AppData\Roaming\jellyfin\data\collections
If I remove this directory manually, the collection is deleted.

**Comment by olebittner** [comment] 2019-07-25 18:07
Same issue for me on:
OS: Debian 10
Browser: Firefox
Jellyfin: 10.3.6

Deleting a collection over the web interface seems to have no effect. The collection disappears at first but reappers after refreshing metadata.
Deleting the collection folder in `/var/lib/jellyfin/data/collections` removes the collection successfully.

A peek into the logs shows that the first Library Sync removes the collection and the next one adds it again:
```
[2019-07-25 20:01:48.953 +02:00] [INF] Deleting item, Type: "BoxSet", Name: "Disney Collection", Path: "/var/lib/jellyfin/data/collections/Disney Collection [boxset]", Id: 223fa503-d38d-a3f8-3634-8fd1a1d1b38b
[2019-07-25 20:01:53.955 +02:00] [INF] Starting Library Sync...
[2019-07-25 20:01:53.955 +02:00] [INF] "LIBRARYSYNC" Added 0 items:  ""
[2019-07-25 20:01:53.955 +02:00] [INF] "LIBRARYSYNC" Updated 0 items:  ""
[2019-07-25 20:01:53.977 +02:00] [INF] "LIBRARYSYNC" Removed 1 items:  "223fa503d38da3f836348fd1a1d1b38b"
[2019-07-25 20:01:53.977 +02:00] [INF] Finished Library Sync Taking "00:00:00.0217816"
[2019-07-25 20:02:06.279 +02:00] [INF] Starting Library Sync...
[2019-07-25 20:02:06.299 +02:00] [INF] "LIBRARYSYNC" Added 1 items:  "223fa503d38da3f836348fd1a1d1b38b"
[2019-07-25 20:02:06.299 +02:00] [INF] "LIBRARYSYNC" Updated 0 items:  ""
[2019-07-25 20:02:06.299 +02:00] [INF] "LIBRARYSYNC" Removed 0 items:  ""
[2019-07-25 20:02:06.299 +02:00] [INF] Finished Library Sync Taking "00:00:00.0199519"

```

**Comment by dkanada** [comment] 2019-09-05 03:48
probably the same issue as #1271

**Comment by ashtez** [comment] 2020-01-06 14:21
No this is still a problem.

**Comment by redSpoutnik** [comment] 2020-04-14 13:16
Is it just me or this old bug now seems to be resolved?

**Comment by ashtez** [comment] 2020-04-16 12:49
Well collections do not work anymore (see [#2611](https://github.com/jellyfin/jellyfin/issues/2611)).

**Comment by vgambier** [comment] 2022-01-10 16:45
Just want to mention that #2611 has since been resolved, so perhaps it's worth re-evaluating this issue.

**Comment by cvium** [comment] 2023-10-19 17:32
I can't reproduce this in 10.8.11. Closing.

**Closed by cvium** 2023-10-19 17:32 UTC
Labels: bug, confirmed

**Comment by williamthrilliam** [comment] 2024-10-13 00:42
I've confirmed that this is still present on server 10.9.11. I've also tried to remove the collection in /var/lib/jellyfin/data/collections but the collection comes back after refresh. Mainly I just want to remove collections created with multiple versions of the same movie, otherwise I do want collections automatically created.

**Comment by Halle914** [comment] 2025-02-04 12:16
Still an issue.

Added my own collections before finding the plug in to do it automatically.

Now I wish to remove the three collections I added before. No matter how I remove them, movie by movie and then collections or removing complete collections it comes back after refresh.

**Comment by rightsaidfred99** [comment] 2025-05-04 04:44
Still an issue for sure

**Comment by felix920506** [comment] 2025-05-04 14:27
Please open a new report.
