### ISSUE TITLE
[Issue]: Parental controls do not apply to library background art

### ISSUE THREAD

**Issue by rluetzner** [jellyfin/jellyfin#11369] opened 2024-04-16 15:38 UTC
### Please describe your bug

I created a new account for my kids and enabled parental controls. After setting an age rating I saw that the contents of the movie and tv show libraries were adjusted, but the background image of the libraries still showed art from movies / shows that were very much not child friendly.

The art changes every now and then and shows a random movie or show from the library, but does not respect the age limitation.

### Reproduction Steps

1. Set up Jellyfin with a few movies with different age ratings.
2. Add a user with parental control and age restriction enabled.
3. Check the background image of the movie library.
  a. Wait for time _x_ until a new random image is generated. There's a good chance that it will not apply to the age restriction.

### Jellyfin Version

10.8.13

### Environment

```markdown
None of this matters.
```

### Jellyfin logs

```shell
Doesn't matter.
```

### FFmpeg logs

```shell
Doesn't matter.
```

### Please attach any browser or client logs here

Doesn't matter.

### Please attach any screenshots here

![A screenshot of the Jellyfin landing page as my kids see it. The library with TV Shows has a background image of the series Firefly, which doesn't match the "Everyone" age restriction.](https://github.com/jellyfin/jellyfin/assets/14924663/e94756a9-6a47-4e0a-a73c-b1d856507cea)

![Screenshot of the age restriction configured for the 'kids' account.](https://github.com/jellyfin/jellyfin/assets/14924663/5857b132-d7c6-41a2-b554-8621782b3111)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rluetzner** [comment] 2024-04-16 15:42
Some more things.

1. This is very much a minor cosmetic issue. None of my kids have been asking about the images and I haven't seen anything harmful.
2. There's the workaround of setting a fixed background image.
3. I'm pretty good with C#, so I can send a pull request _when I find the time_. Although I'd be happy if somebody could point me in the right direction. 🙂 

Also: Jellyfin rocks. Keep up the good work.

**Comment by crobibero** [comment] 2024-04-16 15:46
Are you referring to these images?
![image](https://github.com/jellyfin/jellyfin/assets/24963659/d121a1cc-00ce-4500-b903-e06306edfd18)

Is so- the image is library specific, not user specific

**Comment by rluetzner** [comment] 2024-04-16 15:49
@crobibero , I thought so. But does it have to be? 🤔

**Comment by crobibero** [comment] 2024-04-16 15:52
That would be a fairly substantial change to how Jellyfin library images work.
Closing this as it is not a bug, but a feature request.

**Closed by crobibero** 2024-04-16 15:52 UTC
Labels: bug

**Comment by rluetzner** [comment] 2024-04-16 16:06
@crobibero just to clarify: would you be willing to accept such a pull request? If you won't accept it anyway, there's no point in me wasting time to look into it. 🙂

And thanks for the quick response.

**Comment by nielsvanvelzen** [comment] 2024-04-16 16:10
We could add an age rating option for all generated images, so library thumbnails and the splash screen.

**Comment by Trezamere** [comment] 2024-04-20 00:53
Whats the point of parental controls if the thumbnails are still showing whatever else is in your library? Great when its a horror movie or something....
