### ISSUE TITLE
[Video] Specials play before season 1

### ISSUE THREAD

**Issue by PointReact** [jellyfin/jellyfin#6470] opened 2021-08-27 04:11 UTC
https://www.youtube.com/watch?v=o86O8agFGiA

Summary: Episode numbers are extracted from bonus features that contain numbers, but their season number remains null, so they end up sorting before season 1.  This bug has been reported before and ignored.

**Comment by GodTamIt** [comment] 2021-09-08 22:24
@PointReact I would like to kindly point out that while I understand you're frustrated with some of the bugs that have been neglected in the project, this project is supported by volunteers, myself included. For example, I'm happy to help debug occasional bugs I run into when I have spare time (one of your bugs, #6467, included), but this is far from my primary work. So please be aware of some of the tone in the videos -- it can come off as derisive towards contributors and their efforts. But  I don't think that's your intent; I think you're just wanting to help out, hence why you're bothering to post bugs and follow up with videos of them here in the first place.

Also, keep in mind that you are more than welcome to fix the issues you find. That's kinda how open-source projects stay alive.

**Comment by srcrist** [comment] 2023-10-05 22:19
How specials are organized within the library is subject to the configured metadata provider. I'm going to close this issue as it isn't actually a bug. Head over to the troubleshooting channel on matrix/discord, or to our forums, and people can help with configuring your providers to your liking.

**Closed by srcrist** 2023-10-05 22:19 UTC
Labels: bug

**Comment by PointReact** [comment] 2023-10-06 02:53
Hey @GodTamIt I hope this sheds some light on why my tone is derisive.  Previous reports of this bug were ignored, so I made a detailed video explanation, that explanation was ignored for 2 years then closed because I guess it's a feature to auto-extract season NULL from a video title, not a bug.  And the thing is, I knew this would happen because this is not my first bug reporting rodeo.  Any project that exists for a sufficient amount of time collects an army of status quo defending zombies who just close issues without fixing them.  It's a miracle any open source project works at all.

**Comment by srcrist** [comment] 2023-10-06 03:37
Please do not continue reporting issues that have already been closed as non-issues. This is not a bug. There is no error here. The way that shows are structured is entirely a user configured state of affairs. If you are unhappy with it, you can simply choose to rename your episodes with a different structure and use a metadata provider that matches the structure you have chosen. You can also use NFO files to provide whatever arbitrary structure that you would like. If you need help with this process, we have troubleshooting and support channels of various forms available to help you.

This is not a bug. That is why people keep telling you, for years, that it is not a bug. This does not change if you film a video of it not being a bug. I'm sorry that this frustrates you.

**Comment by oddstr13** [comment] 2023-10-06 06:21
@PointReact When you chime in on bugs that are already reported, please do so in the existing GitHub issue.
We extremely rarely, if ever lock issues so that there is no way to comment on them, and we can and do reopen closed issues if they turn out to have been closed in error.

If an issue has not been registered on the GitHub issue tracker, it has not yet been properly registered and is not likely tracked by the team.
If the issue has been previously been described elsewhere on the internet, please create an issue on the appropriate repository, and fill inn the issue template properly and in detail, and reference the any other mentions of the bug as extra information at the bottom.

A YouTube video as the main content of a bugreport is generally not sufficient. The information linked in off-site links is not easily searchable, even less so video content. A video can serve as additional aid in showcasing what the issue is (mainly for UX issues), and how to reproduce them (but this information should also be made available as text in the issue body).

An issue with the details hidden in a video, such as this one is liable to get ignored by most devs, as the information isn't easily accessable.

Your tone here and name-calling is not acceptable behavior, please re-review our community standards: https://jellyfin.org/docs/general/community-standards

We've got new contributors on board, which is doing the really important task of going over and categorizing issues, old and new, so that it is easier to properly address them for the rest of the team, when they have a free moment.
If this was not the case, this issue would likely *not* have received *any* attention, until we've fixed the stale bot, which we recently discovered was not doing it's job properly.

**Comment by PointReact** [comment] 2023-10-08 17:11
Other reports of this exact bug done without videos, with detailed information, and they were ignored and closed due to inactivity by an automated issue closing robot.  As if ignoring an issue for 120 days somehow fixes it.  I show this in the video, which you either didn't watch or didn't pay attention to.

Scrist's gish gallop about meta data providers is just not true.  He's just confabulating a story that makes the bug not exist so he can close the issue and increase his jannie high score.  I'm sorry but I don't know how to respond to such unpleasantry in a pleasant manner.  I'm a practical person and I call a spade a spade.

Oddstr13, all you've done is argue procedure for half a page while ignoring the content.  How many times are people supposed to follow the procedure and be ignored and outright lied to before they try something different?  How many times are we supposed to babysit your feelings before we tell the truth about what you're doing?

**Comment by cvium** [comment] 2023-10-08 17:22
I'm not going to sit through a 5 minute video, but I did notice you complained about some bonus features. "Bonus Features" is not a valid extras folder name, so it will treat it as episodes and parse them as such.

**Comment by PointReact** [comment] 2023-10-08 18:54
>I'm not going to sit through a 5 minute video

Nice of you to declare your intention of willful ignorance in advance so anyone with sense can ignore you out of hand.

**Comment by srcrist** [comment] 2023-10-08 18:55
There are only so many ways that people can tell you in simple terms that you're incorrect, friend. But I think your time here insulting contributors for not making things work the way you believe they should is growing to a close. This is not a bug, and it will not be made to function as you wish. If you want your media to match correctly, you can learn to use the application as intended.

**Comment by cvium** [comment] 2023-10-08 18:57
> >I'm not going to sit through a 5 minute video
> 
> 
> 
> Nice of you to declare your intention of willful ignorance in advance so anyone with sense can ignore you out of hand.

I have better things to do than listen to tired tirades about sheep.

Like it or not, I may well be your only option to get closure, but nothing you've shown has indicated anything other than RTFM.

**Comment by PointReact** [comment] 2023-10-08 20:09
Closure for what?  My 2 year old issue that had already been reported multiple times and willfully ignored that I forgot existed until the jannie army arrived in my inbox?  

This program is **riddled** with bugs, in playback, transcoding, options, subtitle parsing and rendering, everywhere.  But I picked this one to report because it is the simplest, grade school level programming task I could identify.  There are two parts:

1. Parsing the value "null" into an integer field.
2. Sorting "null" before "1" in a numeric list.

That's the bug.  If you can't handle that, then there's no hope on god's green earth that you're ever going to handle any of the more complex technical bugs.  

There's two types of open source developers, the ones who want to help the world, and the type who's work simply isn't worth paying for.  I can only assume that you've all inherited the working code in this project from the first type.

**Comment by oddstr13** [comment] 2023-10-08 20:55
> Other reports of this exact bug were done without videos, with detailed information, and they were ignored and closed due to inactivity by an automated issue closing robot. As if ignoring an issue for 120 days somehow fixes it. I show this in the video, which you either didn't watch or didn't pay attention to.
> 

Still not seeing links to the issues in question.
The stale bot is here because issues often don't get any followup by the creator, and it is hard to know if an issue that was created for Jellyfin 10.3.2 is still relevant for 10.7.10. So, we ask the issue creator to follow up and confirm that it is still an issue with the most recent version.

This is *not* too much to ask of users reporting issues.

> Scrist's gish gallop about meta data providers is just not true. He's just confabulating a story that makes the bug not exist so he can close the issue and increase his jannie high score. I'm sorry but I don't know how to respond to such unpleasantry in a pleasant manner. I'm a practical person and I call a spade a spade.
> 

@felix920506 and @srcrist has been doing a crapload of really boring work, looking at every single open issue in this repo, categorising them to their best effort.
Issues getting miss-classified now and the is inevitable, but I'm not sure if that is the case for this particular one.

If you think there is a real underlying bug here, it is your responsibility to *respectfully* make your case for why you think this is an actual problem, provide the details for why you think 

> Oddstr13, all you've done is argue procedure for half a page while ignoring the content. How many times are people supposed to follow the procedure and be ignored and outright lied to before they try something different? How many times are we supposed to babysit your feelings before we tell the truth about what you're doing?

Personal insults is highly unprofessional, and is not helpful in solving issues with software.
Both me, @cvium, @srcrist and a few others have looked at this issue, and our conclusion so far is that you are seeing this issue due to poor library structure, and thus poor metadata getting pulled in.

I did *not* ignore the content of your video, thus my link to the community standards.
But I also ask that you provide the relevant information in detailed but concise factual form in writing when you're reporting issues.

---

You are not entitled to my free time.
*I* decide which issues *I* think are worth spending *my* *free time* working on and improving, and *I* decide which parts of the project *I* spend time working on.
You are not making a good case for this one, and you are not providing good data to even attempt to figure out what is going on here. You are wasting all of our time here, yours included.

Your insults towards the contributors of this project is *not* appreciated, and is a clear violation of the Jellyfin project's community standards and code of conduct, of which I've previously provided a direct link in this issue, for your convenience.

> There's two types of open source developers, the ones who want to help the world, and the type who's work simply isn't worth paying for. I can only assume that you've all inherited the working code in this project from the first type.

Some developers wish to improve the software dependent world we live in, and provide their work for free, for anyone to enjoy.
We inherited lots of working code… and *all* the associated bugs and technical debt from a previously open source project, which decided to *stop* doing open source work when they though they had something they could monetize. If you prefer the latter model, I suggest you move to the other project so hinted at, and pay them for their work.

The Jellyfin project is neither asking nor expecting you to pay, but we *do* expect respectable behavior.

**Comment by cvium** [comment] 2023-10-08 21:41
> Closure for what? My 2 year old issue that had already been reported multiple times and willfully ignored that I forgot existed until the jannie army arrived in my inbox?

You're still here, so it must mean something to you.

> This program is **riddled** with bugs, in playback, transcoding, options, subtitle parsing and rendering, everywhere. But I picked this one to report because it is the simplest, grade school level programming task I could identify. 

I wish the world was as simple as you're presenting it here. You obviously haven't read any of the code we've inherited or written :) It doesn't sound like you've ever worked with other developers before.

> There are two parts:
>     1. Parsing the value "null" into an integer field.
> 
>     2. Sorting "null" before "1" in a numeric list.
> 
> 
> That's the bug. If you can't handle that, then there's no hope on god's green earth that you're ever going to handle any of the more complex technical bugs.

All problems sound simple when boiled down to such an extreme degree. Here are the facts though:

1. All software has bugs. Expecting it to do XYZ when it was never meant to is **not** a bug though.
2. Parsing is not magic. It follows very simple rules (hint: it can't do what it isn't programmed to do *gasp*). From what I can see, you do not follow the rules of the parser. "Bonus Features" is not a valid name for featurettes. If you want Jellyfin to stop treating them like episodes, follow the [_naming rules_](https://jellyfin.org/docs/general/server/media/shows/#extras-folders).
3. Very few developers wants to have their time wasted, no matter how much they want to help. A 5 minute video is a waste of time for a "grade school level programming task".
4. You have ignored everyone when told that your problem is likely caused by not following the naming rules.

I am willing to fix the bug if you can actually provide evidence that it is a bug. Recording a video full of incorrect assumptions is not evidence of anything.
