### ISSUE TITLE
TVDB plugin - Can't fetch some informations/images (Forbidden access)

### ISSUE THREAD

**Issue by olibet** [jellyfin/jellyfin#1592] opened 2019-07-31 11:33 UTC
**Describe the bug**
Hi,
I created a new TV shows library called "Séries FR", with 2 series of one season inside.
Series are correctly identified. Episodes for the first on are correctly processed, not for the other. 
When I check the logs, whenever I choose on of the two series I see an error starting with a " 403 Forbidden" from Nginx, I don't know where it comes from.

I tried  to change preferred languages from French to English, still the same.
I tried recreating the libray with a different name (no accent), still the same.

TheTVDb and OpenMovieDb  areused to fetch informations

The other libraries are not impacted, some are set in French, other in English.

Any help ?

Thanks

**Logs**
```
[2019-07-31 11:01:44.967 +00:00] [ERR] HTTP request failed with message: "<html>
<head><title>403 Forbidden</title><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script></head>
<body bgcolor=\"white\">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
[2019-07-31 11:01:44.969 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

[2019-07-31 11:03:51.917 +00:00] [ERR] HTTP request failed with message: "<html>
<head><title>403 Forbidden</title><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script></head>
<body bgcolor=\"white\">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
[2019-07-31 11:03:51.918 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-07-31 11:03:51.969 +00:00] [ERR] HTTP request failed with message: "<html>
<head><title>403 Forbidden</title><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script></head>
<body bgcolor=\"white\">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
[2019-07-31 11:03:51.970 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-07-31 11:03:52.051 +00:00] [ERR] HTTP request failed with message: "<html>
<head><title>403 Forbidden</title><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script></head>
<body bgcolor=\"white\">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
[2019-07-31 11:03:52.052 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-07-31 11:03:52.078 +00:00] [ERR] HTTP request failed with message: "<html>
<head><title>403 Forbidden</title><script src=\"/cdn-cgi/apps/head/fmFm3KANnnfPtP1n_EgxUXUm2cE.js\"></script></head>
<body bgcolor=\"white\">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
[2019-07-31 11:03:52.079 +00:00] [ERR] Error processing request
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Debian 9
 - Browser: Firefox
 - Jellyfin Version: 10.3.7.0
 - Reverse proxy: apache

**Comment by bjoern-vh** [comment] 2019-07-31 11:51
I can confirm that. I have exactly the same problems since today.

OS: Ubuntu 18.04 LTS 64-Bit
Jellyfin: 10.3.7.0

**Comment by olibet** [comment] 2019-08-01 09:29
More informations :

I've the same error with every new show I had, even in older libraries.

If I add an episode to an already existing show, no error.

**Comment by oddstr13** [comment] 2019-08-01 10:48
Looks like one of the image fetchers are getting denied by the source website.

Can you go to the library settings, enable advanced, then disable one of them at a time and test inbetween?
Then report back here which one is causing the problem.

**Comment by olibet** [comment] 2019-08-01 13:42
Well, it's gone.
I think that TheTVDB was causing the problem, because I didin't see the same errors with movies.
But right now, everything is back in order. I'll continue checking for the next few days (I do check my logs, anyway x)) 
Maybe a change/problem on their (TheTVDB) side ?

**Comment by olibet** [comment] 2019-08-01 13:54
So, I checked on The TVDB's forums & site, a new version af the API has been released 2 days ago : 
https://www.thetvdb.com/blog/something_new

And some people reported having search and images problems : 
https://forums.thetvdb.com/viewforum.php?f=118&sid=bbfc965451474dd083b696365e2574a2

Thanks everyone for the help, I think we can close this :)

**Comment by olibet** [comment] 2019-08-02 07:57
My Bad, I closed the subject a bit too fast.
The issue is still present, only when TheTVDB is set as fetcher.
The new API version must be the cause

**Comment by anthonylavado** [comment] 2019-08-03 03:17
They have informed us that they are rolling back, so we’ll keep an eye on it.

**Comment by onny** [comment] 2019-08-08 08:49
@olibet Could you please rename the title of the issue to reflect the this is an issue of the tvdb plugin?

Thanks and best reggards,
Jonas

**Comment by cvium** [comment] 2019-08-15 12:00
If this persists, let us know. Closing this for now as it seems related to the v3 rollout.

**Closed by cvium** 2019-08-15 12:00 UTC
Labels: bug
