### ISSUE TITLE
[Issue]: Can't watch TV shows while they are recording (HDHomerun OTA)

### ISSUE THREAD

**Issue by numericOverflow** [jellyfin/jellyfin#6933] opened 2021-12-01 16:10 UTC
### Please describe your bug

I have an HDHomerun TV tuner set to record OTA TV shows via Jellyfin scheduler. I believe some time in the last maybe 6 months a code change was made to combine all the small ts files for a recording into a single, large episode file. Since that change, I can no longer record a show and watch it simultaneously. I'm using Roku devices to view the video.

Until JF is done recording, the single ts file can't be accessed by another process. I used to use Plex to view shows while simultaneously recording by JF. As of version 10.7.7, I can't watch recordings while they are recording using either plex or jellyfin.

I can't see anything obvious in the JF  log files, and will post them later today when I have access to my server.

Can anyone advise on what changed, or what is the correct procedure for simultaneous record & playback?

FYI - DVR capability is a *must* for modern video recording/streaming setup.  

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows server 2012R2
- Virtualization:
- Clients: Roku
- Browser: N/A
- FFmpeg Version:
- Playback Method: unknown
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage: local (NTFS)
```

### Jellyfin logs

```shell
Will get them later
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2021-12-01 17:04
Duplicate of #6415

**Closed** 2021-12-01 17:05 UTC
Labels: bug
