### ISSUE TITLE
State of AMD transcoding?

### ISSUE THREAD

**Issue by LegendaryB** [jellyfin/jellyfin#2787] opened 2020-04-06 17:10 UTC
Hey Guys,

I'm using a Ryzen 3 2200G and was wondering if transcoding with the graphic unit of it is supported? If yes does it have some restrictions for example only working when jellyfin directly running on the host and not in docker or other virtualization? And should I use VAAPI or AMD AMF? Currently I have a setup with a GTX 1060 but want to remove it because of power consumption. The content on my server is mainly HEVC to minimize the disk space needed. If I had enough space I would just convert all of it manually to H264 but unfortunately thats not the situation.

Kind Regards

**Comment by nyanmisaka** [comment] 2020-04-07 08:38
I wanted to recommend VAAPI, but due to an issue in the upstream `mesa` display driver, the HEVC video could not be decoded. This will be resolved in mesa 20.1. Or you may need to manually build the mesa driver. Another option is to use AMF on Windows.

**Comment by LegendaryB** [comment] 2020-04-07 13:24
Is mesa 20.1 already released but not yet embedded in jellyfin or is even the implementation missing?

**Comment by nyanmisaka** [comment] 2020-04-07 13:28
> Is mesa 20.1 already released but not yet embedded in jellyfin or is even the implementation missing?

It is an open source driver used by Intel and AMD GPUs, and Jellyfin will not include it. It is updated via apt or pacman. Mesa 20.1 may be released in May, you can get it by updating in ubuntu 20.04 LTS.

**Comment by LegendaryB** [comment] 2020-04-07 13:55
Okay thank you for clarification. Then I will wait for it. Hopefully I can then get rid of my GTX. Is this than also only working on the host or also in a docker container?

**Comment by nyanmisaka** [comment] 2020-04-08 02:19
> Okay thank you for clarification. Then I will wait for it. Hopefully I can then get rid of my GTX. Is this than also only working on the host or also in a docker container?

You can use VAAPI HWA in host and docker without additional drivers on AMD GPU. But first you need to read the documentation to learn how to set up.

**Comment by barolo** [comment] 2020-04-08 08:38
@LegendaryB 
I have the same APU, with Jellyfin 10.5.3 + Mesa 20.0.4 for the first time everything works perfectly, CPU is idling and transcoding is at ~120fps with FHD HEVC 10bit, subs work too finally
@nyanmisaka I really appreciate your work on this, thanks!

**Comment by LegendaryB** [comment] 2020-04-08 09:32
@barolo Are you running your setup in docker or on the host? Sounds good then I will also give it a shot on the coming long weekend I think.

@nyanmisaka Thanks for your help. Will take a look in the docu

**Comment by barolo** [comment] 2020-04-09 03:45
@LegendaryB I'm running it on host  
I was actually surprised by the quality of transcoded stuff, I'm guessing that it's due to high bitrates being used but the results are amazing

**Comment by barolo** [comment] 2020-04-09 13:24
Small correction, HDR is still borked, ther's no tone-mapping, colors are out of whack

**Comment by nyanmisaka** [comment] 2020-04-09 13:29
> Small correction, HDR is still borked, ther's no tone-mapping, colors are out of whack

Only Intel ICL and TGL supports HDR10 Tone Mapping now.

https://github.com/intel/media-driver

**Comment by barolo** [comment] 2020-04-09 13:32
> > Small correction, HDR is still borked, ther's no tone-mapping, colors are out of whack
> 
> Only Intel ICL and TGL supports HDR10 Tone Mapping now.
> 
> https://github.com/intel/media-driver

ffmpeg has its own tone-mapping filter, can't it be injected into chain?

**Comment by nyanmisaka** [comment] 2020-04-09 13:49
> ffmpeg has its own tone-mapping filter, can't it be injected into chain?

AFAIK Jellyfin does not currently support HDR output. You can learn how those filters are used for future reference.

**Comment by NCLI** [comment] 2020-04-14 12:24
Is there a reason to use VAAPI over AMD AMF?

**Comment by nyanmisaka** [comment] 2020-04-14 12:40
> Is there a reason to use VAAPI over AMD AMF?
> 
> VAAPI isn't very stable for me with the 2200g using docker, while AMF does at least work.

That was a failure in the linux kernel on Raven/Picasso that caused VAAPI to fail. I have also encountered when transcoding multiple videos at the same time. At present, AMF only has a hardware encoder, while the decoder is not native and the scaler has no hardware acceleration, resulting in the GPU cannot be fully utilized. I have reminded the AMF team and hope that they can submit patches for these components to ffmpeg as soon as possible.

**Comment by NCLI** [comment] 2020-04-14 13:12
So the fix for VAAPI would be to grab a newer kernel?

**Comment by nyanmisaka** [comment] 2020-04-14 13:34
> So the fix for VAAPI would be to grab a newer kernel?

I have tried to update to the 5.6 kernel before but this issue still exists.

This is the reason I speculate as the system freezes during failure and cannot recover by itself. It may also be an issue caused by the mesa driver. I didn't encounter this kind of issue on AMD discrete graphics card, so I said this is a specific issue of APU. If you encounter a similar problem, you can report it to [mesa](https://gitlab.freedesktop.org/mesa/mesa) or [amd-gfx](https://lists.freedesktop.org/mailman/listinfo/amd-gfx).

**Comment by NCLI** [comment] 2020-04-14 13:40
Will do ASAP.

But in summary, on Linux, I guess there is no good way to utilize HW transcoding with an AMD APU.

**Comment by nyanmisaka** [comment] 2020-04-14 13:51
> Will do ASAP.
> 
> But in summary, on Linux, I guess there is no good way to utilize HW transcoding with an AMD APU.

VAAPI is very stable for old AMD GPUs that use UVD/VCE. For APU and RX 5000 series using VCN, stability is still a problem.

So I recommend using AMF on window 10 when it is fully implemented in ffmpeg. Not long ago, the AMF team was testing their patch and hoped to submit it in a few months.

`amdgpu-pro` makes it possible to use AMF via Vulkan on Linux, but when accessing VCN in this way, the above issue will also appear on the APU, so I guess the kernel driver is flawed.

**Comment by nyanmisaka** [comment] 2020-04-14 14:11
> Will do ASAP.
> 
> But in summary, on Linux, I guess there is no good way to utilize HW transcoding with an AMD APU.

Forgot to remind you. If it is error below, it is only related to mesa and will be fixed in 20.1.
I mentioned this issue in https://github.com/jellyfin/jellyfin/pull/2503 before.

`Failed to render parameter buffer: 6 (invalid VASurfaceID).`

**Comment by NCLI** [comment] 2020-04-14 14:12
Ok. I will close the report for now, and see if it is solved before reporting a new one then.

As for using Windows, that's not really realistic for me. My server runs other stuff too, and I'm not migrating everything just for this.

**Comment by LegendaryB** [comment] 2020-04-26 08:40
@nyanmisaka Sorry to bother you again but it is now merged, right? Do I need to install something additional? Running jellyfin from docker. Host system is a freshly installed Debian 10. In the jellyfin log I still see the error:
```
[Parsed_scale_vaapi_2 @ 0x5652c98715c0] Failed to render parameter buffer: 6 (invalid VASurfaceID).
Error while filtering: Input/output error 
```

Kind Regards

**Comment by nyanmisaka** [comment] 2020-04-27 06:41
> @nyanmisaka Sorry to bother you again but it is now merged, right? Do I need to install something additional? Running jellyfin from docker. Host system is a freshly installed Debian 10. In the jellyfin log I still see the error:
> 
> ```
> [Parsed_scale_vaapi_2 @ 0x5652c98715c0] Failed to render parameter buffer: 6 (invalid VASurfaceID).
> Error while filtering: Input/output error 
> ```
> 
> Kind Regards

AFAIK Mesa version 20.1 has not been released yet, and is expected to be released in May. But I am not sure if it will be available in your distribution at once it is released.

**Comment by LegendaryB** [comment] 2020-04-27 10:15
@nyanmisaka So my only option would be to build it myself right? I also don't think that it will be integrated into debian right away

**Comment by barolo** [comment] 2020-04-27 13:21
> @nyanmisaka So my only option would be to build it myself right? I also don't think that it will be integrated into debian right away

Or just get one from 'buntu repos, there are several gaming oriented which provide, git, prerelease Mesa

**Comment by barolo** [comment] 2020-04-27 13:25
> @nyanmisaka So my only option would be to build it myself right? I also don't think that it will be integrated into debian right away

Or just get one from 'buntu repos, there are several gaming oriented ( e.g padoka's ) which provide, git, prerelease Mesa

**Comment by janfribogar** [comment] 2020-05-08 15:28
I'm a noob at linux systems but I really want to use my 2400ge ryzen APU with hardware encode/decode in a linux NAS.
I'm now using in Windows Server 2019 and is working perfectly in Jellyfin but I really want to move to OpenMediaVault in my NAS and use AMD AMF in the docker Jellyfin.
My question: is it really posible to do it right now? If yes, what do I have to do? If no, it will be posible in the near future (inside docker)?

**Comment by barolo** [comment] 2020-05-09 01:09
> I'm a noob at linux systems but I really want to use my 2400ge ryzen APU with hardware encode/decode in a linux NAS.
> I'm now using in Windows Server 2019 and is working perfectly in Jellyfin but I really want to move to OpenMediaVault (Dedian 10) in my NAS and use AMD AMF in the docker Jellyfin.
> My question: is it really posible to do it right now? If yes, what do I have to do? If no, it will be posible in the near future (inside docker)?

You'd need never Mesa, 20.1+, Debian is very conservative with their updates and it will take time before it reaches stable, or even testing [ aka Debian 11 ]it just entered their experimental branch.

**Comment by janfribogar** [comment] 2020-05-12 15:20
Ok I will stick with windows by now. But I'm having a problem.
In my Windows server installation I can run Jellyfin making decode and encode perfect without problems but when i install Jellyfin in the same PC but in a Windows 10 installation it can only decode with the same movie. Can someone help me to understand what's the diferrence and how to solve it?

**Comment by NCLI** [comment] 2020-05-28 08:47
The new mesa 20.1 is now released, but I'm still seeing really high CPU-usage(100%) while transcoding. How do I tell if it's actually working?

**Comment by barolo** [comment] 2020-05-28 18:39
> The new mesa 20.1 is now released, and installed on my system, but I'm still seeing really high CPU-usage(100%) while transcoding. How do I tell if it's actually working? @nyanmisaka

What are you trying to transcode, are we talking about the same APU? I have 2200G and the CPU usage during transcoding is very low

**Comment by NCLI** [comment] 2020-05-28 21:00
2400g pro. Transcoding 10bit 4K hevc.

Are you running jellyfin in a docker, or on bare metal?

**Comment by NCLI** [comment] 2020-05-28 22:05
NVM, still getting the exact same error with 20.1 when I actually ask Jellyfin to use it:

`[Parsed_scale_vaapi_2 @ 0x55de4ea8e380] Failed to render parameter buffer: 6 (invalid VASurfaceID).`

@nyanmisaka

**Comment by barolo** [comment] 2020-05-28 22:10
@NCLI I'm running bare metal, 4k works for me too

**Comment by Milokita** [comment] 2020-06-06 02:09
> 
> 
> @NCLI I'm running bare metal, 4k works for me too

May I ask which version of ubuntu did you use?

**Comment by barolo** [comment] 2020-06-06 02:56
> > @NCLI I'm running bare metal, 4k works for me too
> 
> May I ask which version of ubuntu did you use?

I'm not using Ubuntu, I'm running Gentoo

**Comment by NCLI** [comment] 2020-06-18 21:37
For others using the official docker image who come here, the attached docker-compose.yml and Dockerfile will allow you to use hardware acceleration on the latest AMD APUs, by updating Mesa inside the docker container.

YMMV, but it works for me. Just extract them to the same folder, add your media library to docker-compose.yml, and run docker-compose.
[docker-compose.zip](https://github.com/jellyfin/jellyfin/files/4801305/docker-compose.zip)

**Comment by barolo** [comment] 2020-06-19 00:43
@NCLI Wait, it works with open AMD/MEsa drivers?

**Comment by barolo** [comment] 2020-06-19 02:08
@NCLI It only works with closed driver isn't it?

**Comment by Milokita** [comment] 2020-06-19 02:09
> 
> 
> For others using the official docker image who come here, the attached docker-compose.yml and Dockerfile will allow you to use hardware acceleration with the latest AMD APUs, by updating Mesa inside the docker container.
> 
> YMMV, but it works for me. Just extract them to the same folder, add your media library to docker-compose.yml, and run docker-compose.
> [docker-compose.zip](https://github.com/jellyfin/jellyfin/files/4801315/docker-compose.zip)

does this work for docker running inside debian 10?

**Comment by NCLI** [comment] 2020-06-19 09:14
> @NCLI It only works with closed driver isn't it?
Nope, works with the MESA driver as-of 20.1.
> > For others using the official docker image who come here, the attached docker-compose.yml and Dockerfile will allow you to use hardware acceleration with the latest AMD APUs, by updating Mesa inside the docker container.
> > YMMV, but it works for me. Just extract them to the same folder, add your media library to docker-compose.yml, and run docker-compose.
> > [docker-compose.zip](https://github.com/jellyfin/jellyfin/files/4801315/docker-compose.zip)
> 
> does this work for docker running inside debian 10?
Shouldn't make a difference. Dockerfiles and docker-compose.yml are OS-agnostic, AFAIK.

**Comment by barolo** [comment] 2020-06-19 13:03
@NCLI it only works with closed drivers, until Khronos publishes their Vulkan encoding extensions.
According to AMD themselves https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/4#issuecomment-645550088

**Comment by NCLI** [comment] 2020-06-19 17:44
That's AMF. I'm talking about VA-API, which is supported by the Ryzen APUs.

**Comment by barolo** [comment] 2020-06-20 00:09
Yeah, AMF. this thread got confusing since it talks about both. Vaapi been working fine for some time

**Comment by NCLI** [comment] 2020-06-20 14:40
Yes, but not in the official docker-container, since it requires a newer version of MESA. Hence my post, which addresses that.

**Comment by Milokita** [comment] 2020-06-21 12:24
> 
> 
> That's AMF. I'm talking about VA-API, which is another type of HWA supported by the Ryzen APUs.

I tried your patch on my debian 10, AMD 2200G CPU, the problem presists when try to enable hardware encoding using both VAPPI & AMF while playing a HEVC video

**Comment by nyanmisaka** [comment] 2020-06-22 16:01
> For others using the official docker image who come here, the attached docker-compose.yml and Dockerfile will allow you to use hardware acceleration with the latest AMD APUs, by updating Mesa inside the docker container.
> 
> YMMV, but it works for me. Just extract them to the same folder, add your media library to docker-compose.yml, and run docker-compose in said folder.
> [docker-compose.zip](https://github.com/jellyfin/jellyfin/files/4801315/docker-compose.zip)
> 
> EDIT: This enables VA-API acceleration, for those wondering which type of hwa I was talking about.

Since Mesa 20.1 also contains some other 10-bit fixes, it is difficult to backport to the previous stable version. If you want to use HWA with AMD GFX in docker, you need to update Mesa in docker.

**Comment by NCLI** [comment] 2020-06-25 09:14
> > That's AMF. I'm talking about VA-API, which is another type of HWA supported by the Ryzen APUs.
> 
> I tried your patch on my debian 10, AMD 2200G CPU, the problem presists when try to enable hardware encoding using both VAPPI & AMF while playing a HEVC video

So you shut down your original Docker, and created a new one using this docker-compose.yml? Can you post the output from running the docker-compose command?

**Comment by rderensy** [comment] 2020-06-26 09:53
I tried installing Debian 11 Bullseye to have the latest MESA version (`vainfo: Driver version: Mesa Gallium driver 20.1.1 for Radeon RX550/550 Series (POLARIS12, DRM 3.36.0, 5.6.0-2-amd64, LLVM 10.0.0)`) but VAAPI (nor AMF) still doesn't work for transcoding HEVC using the RX550.

I get these errors/warnings in the journalctl:
    Jun 26 11:50:04 xxx jellyfin[22305]: [11:50:04] [ERR] FFMpeg exited with code 1
    Jun 26 11:50:04 xxx jellyfin[22305]: [11:50:04] [WRN] cannot serve /mnt/temp/7a7079bcd5c82d67208e6be3561e6e130.ts as transcoding quit before we got there
    Jun 26 11:50:05 xxx jellyfin[22305]: [11:50:05] [ERR] FFMpeg exited with code 1
    Jun 26 11:50:06 xxx jellyfin[22305]: [11:50:06] [WRN] cannot serve /mnt/temp/8ce7e8dd93cc1f0eb75a3611fb8597030.ts as transcoding quit before we got there
    Jun 26 11:50:06 xxx jellyfin[22305]: [11:50:06] [ERR] Error processing request: Could not find file '/mnt/temp/8ce7e8dd93cc1f0eb75a3611fb8597030.ts'. URL: http://xx.xx.xx.xx:8096/videos/62b44c44-1284-8523-7210-d5e863d69c97/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83Ny4wfDE1OTMxNjIzMDc4ODM1&MediaSourceId=62b44c44128485237210d5e863d69c97&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=8c862ad4ca5143ca926059a92c0f6f4e&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=e0389b5bb946bdcf94ef67e2b874e45b&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=VideoCodecNotSupported,AudioCodecNotSupported&allowVideoStreamCopy=false

Weird thing is, from what I understand, it shouldn't need transcoding right?
    Jun 26 11:50:06 xxx jellyfin[22305]: [11:50:06] [INF] Profile: Unknown Profile, Path: (...)/Planet Earth II/Season 1/Planet Earth II - S01E01.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
    Jun 26 11:50:06 xxx jellyfin[22305]: [11:50:06] [INF] Profile: Unknown Profile, No direct play profiles found for Path: (...)/Planet Earth II/Season 1/Planet Earth II - S01E01.mkv

**Comment by Milokita** [comment] 2020-06-26 11:52
> 
> 
> > > For others using the official docker image who come here, the attached docker-compose.yml and Dockerfile will allow you to use hardware acceleration with the latest AMD APUs, by updating Mesa inside the docker container.
> > > YMMV, but it works for me. Just extract them to the same folder, add your media library to docker-compose.yml, and run docker-compose in said folder.
> > > [docker-compose.zip](https://github.com/jellyfin/jellyfin/files/4801315/docker-compose.zip)
> > > EDIT: This enables VA-API acceleration, for those wondering which type of hwa I was talking about.
> > 
> > 
> > Since Mesa 20.1 also contains some other 10-bit fixes, it is difficult to backport to the previous stable version. If you want to use HWA with AMD GFX in docker, you need to update Mesa in docker.
> 
> That was my conclusion too, which is why I wrote this simple Dockerfile to automate the process.
> 
> > > That's AMF. I'm talking about VA-API, which is another type of HWA supported by the Ryzen APUs.
> > 
> > 
> > I tried your patch on my debian 10, AMD 2200G CPU, the problem presists when try to enable hardware encoding using both VAPPI & AMF while playing a HEVC video
> 
> So you rm'd your original Docker, and created a new one using this docker-compose.yml? Can you post the output from running the docker-compose command?

I did not remove the original jellyfin docker but stop it. 
Since the original runs on different user, path, port than default. 

Here is my docker.yml:
`

version: "3"
services:
    jellyfin:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: jellyfin-server
      ports:
        - "8096:8096"
        - "8920:8920"
      volumes:
        - /media/test/config:/config
        - /media/test/cache:/cache
        - /media/test/media:/media:ro
      devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
        - /dev/dri/card0:/dev/dri/card0
      environment:
        - PGID=1000
        - PUID=1000
      restart: on-failure
      privileged: true

`

docker compose:
`
Building jellyfin
Step 1/7 : FROM jellyfin/jellyfin
 ---> 5e41dfe87d74
Step 2/7 : RUN apt-get update && apt-get upgrade -y
 ---> Using cache
 ---> 8cf7a65cd243
Step 3/7 : RUN apt-get install -y gpg
 ---> Using cache
 ---> 9557b6b5cf6d
Step 4/7 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
 ---> Using cache
 ---> 53db8c0aba74
Step 5/7 : RUN echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu bionic main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-bionic.list
 ---> Using cache
 ---> 4a178360f7ac
Step 6/7 : RUN apt-get update
 ---> Using cache
 ---> 9da7f0a17aed
Step 7/7 : RUN apt-get upgrade -y
 ---> Using cache
 ---> 7cbc3c704931
Successfully built 7cbc3c704931
Successfully tagged test_jellyfin:latest

`

**Config in the hardware accel: AMD AMF, hardware encoding enabled**

the transcode log for playing a HEVC 1080p, AAC 5.1 video :

`
{"Protocol":"File","Id":"10f1ad91a3a2038b366e341af0f8f776","Path":"/media/ç™½é›ªå…¬ä¸»å’Œä¸ƒä¸ªå°çŸ®äºº.Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265/Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265.mp4","Type":"Default","Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":1392391637,"Name":"Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265","IsRemote":false,"ETag":"b362e6928a972967190e35b5667d3ba4","RunTimeTicks":49912850000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"hevc","CodecTag":"hev1","Language":"und","TimeBase":"1/24000","CodecTimeBase":"1001/24000","VideoRange":"SDR","DisplayTitle":"1080P HEVC","IsInterlaced":false,"BitRate":2000850,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1448,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":"Video","AspectRatio":"4:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p10le","Level":120},{"Codec":"aac","CodecTag":"mp4a","Language":"eng","TimeBase":"1/48000","CodecTimeBase":"1/48000","DisplayTitle":"Eng AAC 5.1 Default","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":224000,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"srt","Language":"chi","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Chi","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/ç™½é›ªå…¬ä¸»å’Œä¸ƒä¸ªå°çŸ®äºº.Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265/Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265.chi.srt"},{"Codec":"srt","Language":"eng","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Eng","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":3,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/ç™½é›ªå…¬ä¸»å’Œä¸ƒä¸ªå°çŸ®äºº.Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265/Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265.eng.srt"}],"MediaAttachments":[],"Formats":[],"Bitrate":2231716,"RequiredHttpHeaders":{}}

/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -i file:"/media/ç™½é›ªå…¬ä¸»å’Œä¸ƒä¸ªå°çŸ®äºº.Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265/Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_amf -pix_fmt yuv420p  -b:v 8003400 -maxrate 8003400 -bufsize 16006800 -profile:v high -level 41  -g 72 -keyint_min 72 -sc_threshold 0 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -start_at_zero -vsync -1 -codec:a:0 aac -ac 2 -ab 224000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/dd263870c17fabd0be451ff85efd514d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/dd263870c17fabd0be451ff85efd514d.m3u8"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-vdpau --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-amf --enable-nvenc --enable-nvdec --enable-vaapi
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/media/ç™½é›ªå…¬ä¸»å’Œä¸ƒä¸ªå°çŸ®äºº.Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265/Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2020-05-11T19:14:31.000000Z
    title           : Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265-RARBG
    encoder         : Lavf58.20.100
    comment         : Snow.White.And.The.Seven.Dwarfs.1937.1080p.BluRay.x265-RARBG
  Duration: 01:23:11.29, start: 0.000000, bitrate: 2231 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1448x1080 [SAR 1:1 DAR 181:135], 2000 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2020-05-11T19:14:31.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2020-05-11T19:14:31.000000Z
      handler_name    : SoundHandler
Only '-vf scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2' read, ignoring remaining -vf options: Use ',' to separate filters
Only '-af volume=2' read, ignoring remaining -af options: Use ',' to separate filters
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_amf))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_amf @ 0x564f3a653000] DLL libamfrt64.so.1 failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x564f3a6e5780] Qavg: 65536.000
[aac @ 0x564f3a6e5780] 2 frames left in the queue on closing
Conversion failed!
`

**Comment by dkanada** [comment] 2020-06-26 12:08
This thread has become a generic troubleshooting issue and the original request was resolved some time ago if I can remember correctly, so I'll close this. Please move any further questions to the forum, reddit, or matrix for general troubleshooting. If an issue is discovered you can also open a new thread here on GitHub so we can start tracking it properly again.

**Closed by dkanada** 2020-06-26 12:08 UTC
Labels: support
