### ISSUE TITLE
Cannot disable artist posters

### ISSUE THREAD

**Issue by oliveconstant** [jellyfin/jellyfin#5825] opened 2021-04-15 16:21 UTC
**Describe the bug**

When creating a new music library with all metadata downloaders and fetchers disabled, Jellyfin still downloads and shows artist posters.

**System**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 86.0.1
 - Jellyfin Version: 10.7.2
 - Installed Plugins: none (except defaults: AudioDB, MusicBrainz, OMDb)
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. From `Dashboard > Libraries`, click on `Add Media Library`
2. From `Content type`, select `Music` and add a music folder that does not contain artist images either as separate files or embedded in audio files
3. Uncheck/disable *all* metadata downloaders/fetchers shown (e.g. `Music Artist metadata downloaders`, `MusicArtist Image Fetchers`, etc.)
4. Click on `Save` and wait for the scan to finish
5. Go to `Home > My Media > [Name of the library just created] > Artists`
6. Observe artist posters being shown

**Expected behavior**
Artist posters should not be fetched/shown

**Comment by 1337joe** [comment] 2021-11-15 10:36
Closing this as a duplicate of #5778

**Closed by 1337joe** 2021-11-15 10:36 UTC
Labels: bug, duplicate
