### ISSUE TITLE
Display time finished - as in more recent emby versions

### ISSUE THREAD

**Issue by jeff7269** [jellyfin/jellyfin#261] opened 2018-12-23 13:59 UTC
Title says it all, the more recent versions of emby have the finish time displayed. This is very helpful.

**Comment by anthonylavado** [comment] 2018-12-23 22:03
When you say "Finish Time", what are you referring to?

Is it like an estimate of when the currently playing program will finish?

Assuming I'm starting a two hour movie at 12:00 PM, it would show "If you watch this movie/show, it will end at 2 PM"?

**Comment by jeff7269** [comment] 2018-12-23 23:46
Yes, that's right. It just takes the file duration and adds it to the current time.

**Comment by JustAMan** [comment] 2018-12-23 23:48
Hmm, it shows that for me during playback. Where do you want to see this information?

**Comment by jeff7269** [comment] 2018-12-24 00:19
After the rotten tomatoes rating on the info screen. "Finishes at"

**Comment by sparky8251** [comment] 2019-01-02 19:43
So... I see this "Ends At" in the most current dev on both movies and TV shows.

I doubt a change has been merged in for this either. Can anyone confirm if this issue even needs to be open?

**Comment by anthonylavado** [comment] 2019-01-03 02:09
I can confirm this is working on the latest release of Jellyfin on my server.

If you’re not seeing it, it might be because the layout doesn’t support it. For example, when viewing the webpage on my phone, it doesn’t show the “Ends at...” unless I turn it to landscape.

**Closed by anthonylavado** 2019-01-03 02:09 UTC
Labels: UI, feature, question
