### ISSUE TITLE
Clean Transcode Directory scheduled task does not work

### ISSUE THREAD

**Issue by eltiel** [jellyfin/jellyfin#3987] opened 2020-08-26 01:36 UTC
**Describe the bug**
Clean Transcode Directory does not get triggered when set as a scheduled task. Running it manually works fine

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker
 - Jellyfin Version: 10.6.3

**To Reproduce**
1. Set Clean Transcode Directory as a scheduled task
2. Wait for it to get triggered
3. Does not get triggered

**Expected behavior**
Clean Transcode Directory should be triggered at scheduled time

**Logs**
No entries at scheduled time, nothing to indicate what went wrong

**Comment by whalehub** [comment] 2020-08-28 09:14
This is a duplicate of #2075.

**Closed** 2020-08-28 09:17 UTC
Labels: bug
