### ISSUE TITLE
non-RC jellyfin version shown in RC

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5204] opened 2021-02-10 12:27 UTC
**Describe the bug**
Hello, I'm currently running 10.7.0-RC3 I think, and it just shows version 10.7.0 on the dashboard instead of the RC.
I initially downloaded this version just because I use the syncplay a lot, but now that I want to help find bugs again it's hard to remember what RC I'm on.
I'm using the stable-RC docker release channel.

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: All
 - Jellyfin Version: 10.7.0 RC3 I think, i dont know I only know its the current stable-rc release
 - Reverse Proxy: nginx

**To Reproduce**

1. On the current RC version go to the dashboard
2. Notice that the version there doesn't specify the current RC

**Expected behavior**
I expected it to say 10.7.0-rc3

**Comment by Bond-009** [comment] 2021-02-17 12:18
Duplicate of #599

**Closed by Bond-009** 2021-02-17 12:18 UTC
Labels: bug
