### ISSUE TITLE
Subtitles Not Loading, 10.5.3

### ISSUE THREAD

**Issue by Mozana** [jellyfin/jellyfin#2822] opened 2020-04-10 16:41 UTC
**Describe the bug**
Worked in version 15.0.0 but updated to the latest one and now the subtitles don't seems to appear on the shows, on version 15.0.0 it took a minute or 2 but they would load in but on the current version it seems to be a hit and miss as some subtitles would work and other wouldn't but they are both from the same provider which is slightly confusing.

I have currently downgraded back to 15.0.0 for now.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: N/A
 - Clients: Browser, Android
 - Browser: Microsoft Edge Chromium
 - Jellyfin Version: 10.5.3
 - Playback: Direct Play, Remux, Direct Stream, Transcode
 - Installed Plugins: AudioDB, MusicBrainz & Open Subtitles
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**
N/A

**Expected behavior**
When I play a video first it selects the en subtitles which is always automatically plus click manually should result in the subtitles appearing after 1-10seconds.

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dkanada** [comment] 2020-04-20 14:20
Duplicate of #2507 but this should be resolved in the latest version, please feel free to comment if you still have the issue.

**Closed by dkanada** 2020-04-20 14:20 UTC
Labels: bug
