### ISSUE TITLE
hardware decode checkboxes become deselected over time.

### ISSUE THREAD

**Issue by kkasberg** [jellyfin/jellyfin#2043] opened 2019-11-22 20:34 UTC
**Describe the bug**
I have checked the decode for all types of encoding.   I have a 1050 TI with driver patch.

**To Reproduce**
Paying media, and restarting server these check boxed become unchecked over time.

**Expected behavior**
Check boxes should stay as saved.

 - OS: Ubuntu 18.04 Docker
 - Browser:  Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: traefik

**Comment by Bond-009** [comment] 2019-11-22 20:43
Duplicate of #2010 which is a duplicate of #1726 and #1360

**Closed by Bond-009** 2019-11-22 20:43 UTC
Labels: bug
