### ISSUE TITLE
[JF >= 10.3] thumbnail extraction now pegs CPU at 100%

### ISSUE THREAD

**Issue by greyvv** [jellyfin/jellyfin#1269] opened 2019-04-21 04:11 UTC
New version maxes cpu and memory usage climbs to 100%.  Deleted existing docker and recreated new one from scratch.  same result

reverted docker to 10.2.2.  scans directories fine.  cpu and memory increase by expected amount

**Comment by mikey242** [comment] 2019-04-21 09:10
Yeah I have this problem too. Crashed my pi3 several times now due to intense cpu and mem usage.

**Comment by pedro-araujo** [comment] 2019-04-21 13:24
I believe this might be related to this FFMPEG issue:
- https://www.reddit.com/r/jellyfin/comments/bfe2c5/ffmpeg_consuming_vast_cpu_with_no_playback_since/

Can you guys check your log files and paste them here?

**Comment by ferferga** [comment] 2019-04-21 15:49
Same here. My first diagnose started by running a ssh session and seeing where the memory usage was going (as I thought it was related to rclone instead) using top. Saw this:

![Lots of ffprobe](https://user-images.githubusercontent.com/10274099/56472215-fd8a1f80-645b-11e9-8e13-b8cbd3caaa07.png)

I have many logs (from ffmpeg and jellyfin, different dates, captured exactly after a reboot and before my Pi dies). Which ones are necessary?

**Comment by ferferga** [comment] 2019-04-21 15:54
@pedro-araujo About the thread you mentioned: I also had same errors in 10.2 version, but it seems that it's getting worse in 10.3, as Jellyfin isn't capable of kill ffmpeg as the old version did.

**Comment by joshuaboniface** [comment] 2019-04-21 16:42
First question for everyone here: is "Enable chapter image extraction" enabled for your TV libraries? This is my first though: the upgrade triggered a scan, and with this option enabled JF spawns numerous ffmpeg processes to perform the image extraction. The issue seems to be that these are all started at once, rather than sequentially for a whole season. I'm doing some more testing to reproduce but confirmation of that setting will help.

**Comment by joshuaboniface** [comment] 2019-04-21 17:12
OK I think there's actually two issues going on here that are being conflated.

@greyvv, your output indicates that the processes causing issues are `ffprobe` - does the actual `ffmpeg` command ever start and use CPU?

The `ffprobe` calls are a standard part of the library scan that can't be disabled, since they're extracting the chapters from the media. The processes do look to be triggered asynchronously which is why you see dozens of processes. If this is really intensive on the system, it might be a storage speed problem.

Then there's the issue with chapter *image* extraction, which is what the Reddit post is about. I'm going to make a separate issue for that.

**Comment by Nosirus** [comment] 2019-04-21 18:07
same problem with docker on unraid server, but even when I do not activate the extraction of the chapters they are executed with the addition of a library, which finally causes the crash

**Comment by greyvv** [comment] 2019-04-21 18:15
my logs do only show endless ffprobe leading up to the crash.  my cpu and storage speed are pretty high end so i dont think that is at issue.

**Comment by ferferga** [comment] 2019-04-21 19:52
@joshuaboniface If it's useful, disabling Screen Grabber doesn't seems to do the trick when you are creating a new library. My Pi crashed again after deleting all my libraries and re-indexing them. Logs still show lines like, although I made sure to disable the Screen Grabber while re-creating my libraries:

```
Apr 21 21:45:49 raspberrypi jellyfin[6411]: [21:45:49] [INF] Killing ffmpeg process
Apr 21 21:45:49 raspberrypi jellyfin[6411]: [21:45:49] [ERR] ffmpeg image extraction failed for file:"/home/ferferga/flexcloud/Sagas/Doraemon/32. Doraemon en busca del escarabajo dorado (2015).mkv"
Apr 21 21:45:49 raspberrypi jellyfin[6411]: [21:45:49] [ERR] Error in Screen Grabber
```
Perhaps this is a different issue (screen grabber working althoough it's disabled) or another thing is going on?

**Comment by joshuaboniface** [comment] 2019-04-21 20:47
Yea there's layered bugs here, we'll have to dig into it a bit more.

1. ffprobe just happens, that's normal.
2. ffmpeg is being called regardless of library settings as a fallback, which shouldn't be happening with both "Screen Grabber" and the "Extract images" disabled.
3. The ffmpeg processes are spawned asychronously for performance reasons, but this triggers major load when scanning a TV season since it triggers all processes simultaneously.

**Comment by ferferga** [comment] 2019-04-21 20:49
@joshuaboniface Not only TV seasons: I re-added my movie library and my Pi crashed in 1 minute.

**Comment by anthonylavado** [comment] 2019-04-25 20:29
As per discussions on Matrix, it looks like part of what we need to check is here: https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L481

**Comment by spoolr** [comment] 2019-04-26 02:36
I'm suffering this problem as well,

But I'm struck by the idea suggested here that what's happening with ffprobe is normal.  I had more than 1000 ffprobes going.  8GB of memory runs out, 100% of cpu used.  Jellyfin GUI unresponsive.  When it started, the logs showed the dotnet process would die from out of memory errors.  But eventually that wasn't happening at all and the scan was stuck indexing at the "T"s.  I had to pkill ffprobe repeatedly to advanced the next batch being indexed just to get through the scan.  Once the ffprobes were done, the ffmpeg calls were able to continue.   The ffprobes were sleeping and never woke up.

**Comment by anthonylavado** [comment] 2019-04-26 04:32
@spoolr - Okay, that part is definitely not normal. This one has been tough to work through - we can seem to replicate the FFmpeg part of it easily enough, but not the ffprobe part yet.

A leading theory as to why this is happening is that we actually made the code surrounding this all *too* good. We fixed so many exceptions that slowed down the processing, and then made it fully asynchronous without a limit. In doing so, it just takes over because it got optimized so well.

We definitely want to tackle this for the next patch (it’s one of the few things left to do), but we have no idea where to start in the code.

**Comment by joshuaboniface** [comment] 2019-04-26 04:39
I *think* the ffprobe part might be related to slow storage - it's not something I've been able to replicate at all, but given how async it is if the processes start slowing down they could back up. @ferferga is your storage fast? Also, can you reproduce it and grab a `ps aux` output so we could see the details of the commands (sanitized however you need).

That evaluation is basically correct though. My systems are quite fast CPU and disk wise, so I see the load spike but it clears quickly, and I've only been scanning a TV library to test it - hence why I mentioned "seasons" before. But I can see how the same thing can happen with a movie library.

I think a queue in a separate thread rather than spawning all the processes at once is the best method, so we could decouple the scanning/library population (which we want to be fast) from the chapter/image extraction (which we don't *want* to be fast due to this issue). And just let that proceed sequentially in the background. *How* to implement this, though, is a very good question. I'm hoping someone more familiar with the C# code can suggest an option here - cc @Bond-009 @cvium @JustAMan @EraYaN @dkanada

**Comment by pedro-araujo** [comment] 2019-04-26 04:44
I have this problem and my storage is very slow. It's a filesystem from a NAS mounted over Samba on a RaspberryPi. The NAS itself is quite fast but Samba combined with the limited resources of a RaspberryPi make the access times significantly slow.

On 26 April 2019 06:39:17 CEST, "Joshua M. Boniface" <notifications@github.com> wrote:
>I *think* the ffprobe part might be related to slow storage - it's not
>something I've been able to replicate at all, but given how async it is
>if the processes start slowing down they could back up. @ferferga is
>your storage fast? Also, can you reproduce it and grab a `ps aux`
>output so we could see the details of the commands (sanitized however
>you need).
>
>That evaluation is basically correct though. My systems are quite fast
>CPU and disk wise, so I see the load spike but it clears quickly, and
>I've only been scanning a TV library to test it - hence why I mentioned
>"seasons" before. But I can see how the same thing can happen with a
>movie library.
>
>I think a queue in a separate thread rather than spawning all the
>processes at once is the best method, so we could decouple the
>scanning/library population (which we want to be fast) from the
>chapter/image extraction (which we don't *want* to be fast due to this
>issue). And just let that proceed sequentially in the background. *How*
>to implement this, though, is a very good question. I'm hoping someone
>more familiar with the C# code can suggest an option here - cc
>@Bond-009 @cvium @JustAMan @EraYaN @dkanada 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin/issues/1269#issuecomment-486923019

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ferferga** [comment] 2019-05-01 15:50
Already testing with 10.3.2 release...

**Comment by greyvv** [comment] 2019-05-01 16:10
same symptoms on my server as before.  created new docker.  memory usage climbs to 100%.   then process kswap0 uses about 80 - 90% cpu.  server becomes unresponsive requiring a hard reboot.  logs show image extraction going on during this time.  many ffprobe processes

**Comment by greyvv** [comment] 2019-05-01 16:12
i have an i5-4690 and 8G of ram.  70% of the ram is free before the docker is started

**Comment by ferferga** [comment] 2019-05-01 17:29
Same here. Can't stop this either because #1275 doesn't allow me to disable Screen Grabber, so I'm stuck with mixed-content and music libraries.

@greyvv Are you also experiencing issues when disabling Screen Grabber as in #1275 ?

**Comment by anthonylavado** [comment] 2019-05-01 17:38
Just to update - the part that's limited so far is FFmpeg doing Screen Grabber image extraction, but not FFprobe. From what we've seen, each FFprobe should only take a second or two per file, but it can still be a bit much.

Our temporary fix on the FFmpeg part, if you can believe it, is deliberately making it slower, by limiting it to two processes max with semaphores. We have a bigger plan to architect a better queue, possibly something configurable, and have it handle both FFmpeg and FFprobe, but it is not a hot fix anytime soon.

Can you believe that this is happening because we fixed so many bugs? The current working theory is that it was breaking so much before that we didn't notice it's true speed/power.

**Comment by ferferga** [comment] 2019-05-01 18:05
> Just to update - the part that's limited so far is FFmpeg doing Screen Grabber image extraction, but not FFprobe. From what we've seen, each FFprobe should only take a second or two per file, but it can still be a bit much.
> 
> Our temporary fix on the FFmpeg part, if you can believe it, is deliberately making it slower, by limiting it to two processes max with semaphores. We have a bigger plan to architect a better queue, possibly something configurable, and have it handle both FFmpeg and FFprobe, but it is not a hot fix anytime soon.
> 
> Can you believe that this is happening because we fixed so many bugs? The current working theory is that it was breaking so much before that we didn't notice it's true speed/power.

Yeah, I remember you or @joshuaboniface mentioned that. It's somewhat curious and fun to see, but it's great to see how the improvements are being made, even if they can bring some quirk and bugs during the transition :)

Btw, saw that @joshuaboniface quoted me in his last reply in this issue but I forgot to answer (sorry): My RPi sdcard is very fast (35-40 MB/s according to my tests in my own Pi) and the SDCard is a SanDisk Extreme one (around 100MB/s, but, unfortunately, impossible to reach in the Pi due to the bus size), so I doubt the problem is in the storage. However, I have my media mounted through a cached Google Drive remote in rclone, so, although it has similar reading and writing speeds than a normal storage, the latency while seeking or reading files will always be so much higher

**Comment by anthonylavado** [comment] 2019-05-02 17:07
Cross posting this because it's useful information:
https://github.com/jellyfin/jellyfin/issues/1275#issuecomment-488554812

**Comment by gerroon** [comment] 2019-05-21 23:46
I have high cpu usage too, I am not doing anything with it and the last time I added media was days ago. It is steadily using 2 cores at %94.5 each

**Comment by spoolr** [comment] 2019-07-04 02:28
It kills me that this is now marked low priority and unlikely to make the next release again.   I've been checking every few days for more than 2 months.  How can I work around this?  JellyFin is unusable until this is resolved for me.  Can I use Emby to index everything somehow and drop the files into JellyFin directories?

**Comment by anthonylavado** [comment] 2019-07-04 03:44
@spoolr Sorry we haven’t posted here, but the triage board is a WIP, so the statuses there don’t accurately reflect what will and won’t make any release yet.

To tell you the truth, we’re actually exploring alternatives to the current scanning processes. For example, in today’s logs from the dev chat room: https://matrix.to/#/!LCLiMJSFwJyNyVtqxj%3Amatrix.org/%24156216615281354mubYc%3Amatrix.org

And more where @EraYaN has actually put together a tool to benchmark scanning between MediaInfo and FFprobe: https://github.com/EraYaN/MediaInfoTest

Apologies for not keeping the the thread up to date, but this item certainly isn’t idle.

**Comment by gerroon** [comment] 2019-10-02 05:08
Fa@k you @stale

**Comment by evulhotdog** [comment] 2020-04-21 04:21
I believe this may be related to the following:

https://github.com/jellyfin/jellyfin/issues/2600
https://github.com/jellyfin/jellyfin/issues/2355
https://github.com/jellyfin/jellyfin/issues/2471

**Comment by sevenrats** [comment] 2023-10-04 21:33
the async nature of the scanner means this is to be expected. moving to feature request for the ability to throttle the library scan
https://features.jellyfin.org/posts/2356/throttle-the-library-scanner

**Closed by sevenrats** 2023-10-04 21:33 UTC
Labels: bug, help wanted, confirmed
