### ISSUE TITLE
PDF and MP3 are not showing 

### ISSUE THREAD

**Issue by PlayerRedOne** [jellyfin/jellyfin#4349] opened 2020-10-19 19:02 UTC
**Describe the bug**
Im am currently working on expanding the range of media and now wanted to add books (PDFs) and audio books (MP3). I have already been running movies (mp4) for 6 months without any problems. 

So I created the following directories on the external storage: 
Movies: /mnt/movies/*.mp4
Books (new): /mnt/movies/Books/Books/.../*.pdf
Audiobooks (new): /mnt/movies/Books/Audiobooks/.../*mp3

In the web interface I was able to create the folders as books, the directories are all displayed, except the files (PDF and MP3). 
![image](https://user-images.githubusercontent.com/70027346/96498914-fb6d7080-124c-11eb-897d-07dbda0566a0.png)

**System (please complete the following information):**
 - OS: Raspbian
 - Virtualization: no
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: Chrome 8x
 - Jellyfin Version: 10.6.4
 - Installed Plugins: AudioDB, Bookshelf, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Storage: External hard disk (USB)

**To Reproduce**

Please see above.

**Expected behavior**
The expected behavior is that the newly added media is recognized and displayed. 

**Logs**
Can not see any errors. 

[2020-10-19 20:00:14.846 +01:00] [INF] OnRefreshComplete "b326dab9cbc9e1ff1747c4fbc0eae035"
[2020-10-19 20:00:14.848 +01:00] [INF] OnRefreshStart "1f8419973f0f01a389f923b04676196b"
[2020-10-19 20:00:14.862 +01:00] [INF] OnRefreshComplete "1f8419973f0f01a389f923b04676196b"
[2020-10-19 20:00:14.863 +01:00] [INF] OnRefreshStart "f70ad82be0fa388abb01b179bf0a6eb5"
[2020-10-19 20:00:14.866 +01:00] [INF] OnRefreshComplete "f70ad82be0fa388abb01b179bf0a6eb5"
[2020-10-19 20:00:14.867 +01:00] [INF] OnRefreshComplete "97ea4548bcad6e1ab598e6f88eb141c6"
[2020-10-19 20:00:14.988 +01:00] [INF] OnRefreshComplete "6e8cc3a96959ec08419573761934796c"
[2020-10-19 20:00:18.520 +01:00] [INF] OnRefreshStart "2f0118e1ef43560d6e37b861422eacfe"
[2020-10-19 20:00:18.529 +01:00] [INF] OnRefreshStart "413468a366816fc20992790773219878"
[2020-10-19 20:00:18.531 +01:00] [INF] OnRefreshComplete "413468a366816fc20992790773219878"
[2020-10-19 20:00:18.532 +01:00] [INF] OnRefreshStart "b294cf699861f6118b8fcfeb178a5823"
[2020-10-19 20:00:18.546 +01:00] [INF] OnRefreshStart "2d5f71762b815611c02c720567edcdd4"
[2020-10-19 20:00:18.557 +01:00] [INF] OnRefreshComplete "2d5f71762b815611c02c720567edcdd4"
[2020-10-19 20:00:18.557 +01:00] [INF] OnRefreshStart "b5f2ab87e14f2a35c1394c3cc8032aef"
[2020-10-19 20:00:18.568 +01:00] [INF] OnRefreshComplete "b5f2ab87e14f2a35c1394c3cc8032aef"
[2020-10-19 20:00:18.568 +01:00] [INF] OnRefreshStart "b538e946ba7323527201c0a2ecc6748f"
[2020-10-19 20:00:18.577 +01:00] [INF] OnRefreshComplete "b538e946ba7323527201c0a2ecc6748f"
[2020-10-19 20:00:18.577 +01:00] [INF] OnRefreshComplete "b294cf699861f6118b8fcfeb178a5823"
[2020-10-19 20:00:18.591 +01:00] [INF] OnRefreshComplete "2f0118e1ef43560d6e37b861422eacfe"

**Comment by telans** [comment] 2020-10-20 04:31
See https://github.com/jellyfin/jellyfin/issues/3797, I believe this is a duplicate of this due to your mount points

**Comment by PlayerRedOne** [comment] 2020-10-23 13:47
Thank you @telans. I solved my issue by creating two softlinks in the media folder to the folders in the mountpoints. 

Not the best solution, but its fine for me as a hotfix.

**Closed** 2020-10-23 13:47 UTC
Labels: bug

**Comment by PlayerRedOne** [comment] 2020-10-23 13:49
> See #3797, I believe this is a duplicate of that issue due to your mount points

Hotfix: Create a softlink from a other directory.
