### ISSUE TITLE
DLNA HTTPS ISSUE

### ISSUE THREAD

**Issue by gnkidwell** [jellyfin/jellyfin#4599] opened 2020-11-27 17:08 UTC
So I just noticed this, if Jellyfin https is disabled, DLNA works without an issue, but the second https is enabled, upnp on the network stops working. This has been tested on both my Ubuntu container and Windows 10, and both servers have this same issue.

**System (please complete the following information):**
 - OS: Windows 10, Ubuntu Server 20.04
 - Virtualization: KVM container of UBNT Server 20.04
 - Clients: UPNP over network
 - Browser: Chrome
 - Jellyfin Version: 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to 'Dashboard-Advanced-Networking'
2. Click on 'Enable HTTPS'
3. Scroll down to 'Save'
4. Restart Service 

**Expected behavior**
Expected HTTPS to work with DLNA, but it does not

**Logs**
No errors in the logs

**Comment by PrplHaz4** [comment] 2020-11-27 20:27
I believe this issue will be fixed in 10.7 - there are a few similar issues open already.

**Comment by leonelsr** [comment] 2020-12-06 02:11
I can confirm this happens on Stable and latest Unstable (as of tonight);
DLNA stops working when you enable HTTPS. No mention about this on the logs no matter what verbosity level, and it happens even if "Require HTTPS" is unchecked.

**Comment by PrplHaz4** [comment] 2020-12-06 13:36
@BaronGreenback I think this was the one where the DLNA notify message was not getting the right port when HTTPS is enabled - any idea if that was supposed to be part of the changes already merged for RC1?

`https://myserver:8096` is sent instead of `https://myserver:8920`

**Comment by BaronGreenback** [comment] 2020-12-06 21:43
@PrplHaz4 That code is present - so it should work. Everything uses a central function that works with http/s and port numbers.

@leonelsr Can you enable dlna debug logs (in options). 

You'll also need to change the logging.default.json file and add

```
"MinimumLevel": {
          "Override": {
            "Emby.Dlna": "Debug",
``` 
and restart JF.

This should include the dlna output in the system logs. (You don't want to run in this state too long).
Could you post those logs please?

**Comment by leonelsr** [comment] 2020-12-07 06:40
> @PrplHaz4 That code is present - so it should work. Everything uses a central function that works with http/s and port numbers.
> 
> @leonelsr Can you enable dlna debug logs (in options).
> 
> You'll also need to change the logging.default.json file and add
> 
> ```
> "MinimumLevel": {
>           "Override": {
>             "Emby.Dlna": "Debug",
> ```
> 
> and restart JF.
> 
> This should include the dlna output in the system logs. (You don't want to run in this state too long).
> Could you post those logs please?

I have this on `logging.default.json`:

```
        "MinimumLevel": {
            "Default": "Warning",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning",
                "Emby.Dlna": "Debug",
                "Emby.Dlna.Eventing": "Debug"
            }
```

Restarted JF with HTTPS on and it simply doesn't show up anywhere (not even on Windows "Network" devices list, where it can always be seen when it's working).

On this log, I also tried to "Play To" my LG WebOS TV, doesn't work either.

But with HTTPS disabled, I can both "Play To" or browse JF libraries from that same TV, normally.

[log_20201207.log](https://github.com/jellyfin/jellyfin/files/5650834/log_20201207.log)

**Comment by BaronGreenback** [comment] 2020-12-07 18:42
PlayTo fix here - https://github.com/jellyfin/jellyfin/pull/4724

Still looking into https issue.

**Comment by BaronGreenback** [comment] 2020-12-07 22:17
Fixed https://github.com/jellyfin/jellyfin/pull/4729

**Closed** 2021-02-28 10:53 UTC
Labels: bug

**Comment by leonelsr** [comment] 2021-05-17 22:19
So.... This fix didn't make it into 10.7.5? I've upgraded, and activating HTTPS still breaks DLNA, even though everything works fine if HTTPS is disabled.

**Comment by leonelsr** [comment] 2021-06-10 04:57
> So.... This fix didn't make it into 10.7.5? I've upgraded, and activating HTTPS still breaks DLNA, no matter if "Require HTTPS" is checked or not. Everything works fine if HTTPS is disabled.

@BaronGreenback any insight on this?

**Comment by BaronGreenback** [comment] 2021-06-10 06:43
Dlna v1 and v1.1 specifically excludes https from the standard.

The fix simply reports this in the log and if http is  enabled, uses this as the preferred protocol. 

There is a 2.0 standard released which was not widely taken up as dlna was seen as old hat. This does include some secure connection method and is one of the things I'll be investigating. 

You can override what is being published ove r ssdp with the publishedserverurl command line option, but if the service still is not detecting jf, then it's because it's following the dlna standard and not because of any bug.

**Comment by BaronGreenback** [comment] 2021-06-10 06:44
Also worth mentioning than some clients only support ip addresses and not dns.

**Comment by Computerboss3000** [comment] 2022-01-18 16:14
Hello, i have installed Jellyfin 10.7.7 and for testing 10.8.0 and DLNA didnt work as soon i activate HTTPS is it a bug or doing i something wrong?
Greetings :)

**Comment by danalderman** [comment] 2024-05-12 17:14
Still seems to be the same in 10.9.  DLNA doesn't work unless you disable https access.
