### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by SirFireNewt** [jellyfin/jellyfin#1219] opened 2019-04-09 01:23 UTC
Currently the server can be ran from subdomains only, I personally prefer to run all my services from subdirectories  of the same domain.
`example.com/jellyfin` instead of `jellyfin.example.com`

Currently you can use the web UI on the subdomain /emby/ but setting this up with a reverse proxy prevents the android app from working

**Comment by bd4** [comment] 2019-05-13 14:59
I would also be interested in this. I luckily am able to set up a subdomain, but it's a lot more work than a subdirectory - add DNS entry, expand my let's encrypt cert (which required temporarily disabling the proxy on / so webroot could verify - I didn't want to convert to --nginx plugin because I already have webroot working for my other domains), re-enable proxy on /.

**Comment by OdinGitDat** [comment] 2019-05-16 01:11
Can you please explain to me how you got the reverse proxy working for the webUI, I'm on apache.

**Comment by bd4** [comment] 2019-05-16 12:30
@OdinGitDat I used nginx, but the manual has a great section on reverse proxy including Apache:
https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/

**Comment by OdinGitDat** [comment] 2019-05-16 15:01
@bd4 That guide does not cover hosting under a subdirectory, that's what the thread is about. I tried everything under the sun but I can't get it to work.

**Comment by joshuaboniface** [comment] 2019-05-16 15:08
Duplicate of #691

This is a planned feature now that Kestrel has landed. But right now there's reports both of it working, and it not working with URL rewriting in the reverse proxy. If you can test that out using e.g. `ModRewrite` that would help confirm.

**Comment by OdinGitDat** [comment] 2019-05-16 17:20
I'll happily test it out if you show me the rewrite conditions.

**Comment by oddstr13** [comment] 2019-05-16 18:41
This is what I'm currently using; https://gist.github.com/oddstr13/6384460ad92bfcef8bf56203e20c345d
Seems to be working just fine so far.
Do note that you may have some difficulty pointing some of the apps at the subdirectory, due to how the URL components are split up in 2-3 fields.

**Comment by Maltahl** [comment] 2019-05-17 09:38
> This is what I'm currently using; https://gist.github.com/oddstr13/6384460ad92bfcef8bf56203e20c345d
> Seems to be working just fine so far.
> Do note that you may have some difficulty pointing some of the apps at the subdirectory, due to how the URL components are split up in 2-3 fields.

Thank you so much! works for me now with that setup compared to the wiki.

But now i get some other issues with:
`We're unable to connect to the selected server right now. Please ensure it is running and try again.`

That appears despite the reverse proxy serving the site as expected.

**Comment by oddstr13** [comment] 2019-05-17 12:50
I'm going to need more details on that error, such as jellyfin version, what app and which version, and how you're connecting - and preferably the nginx access/error logs showing the failing request (and a few before and after).
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2019-07-29 16:59 UTC
Labels: feature

**Comment by cschwarck** [comment] 2020-05-18 14:48
> This is what I'm currently using; https://gist.github.com/oddstr13/6384460ad92bfcef8bf56203e20c345d
> Seems to be working just fine so far.
> Do note that you may have some difficulty pointing some of the apps at the subdirectory, due to how the URL components are split up in 2-3 fields.

For the nginx default config.. I'm trying to see what the default web-root is for Jellyfin so I can define this using the root setting. I'm not actually moving it to a sub dir, but would like to use something like: location /media and have it point to the actual jf web-root. root /var/www/default-install-path for nginx.

https://example.com/media - but this proxy to an internal vm with a standard jellyfin install.
