### ISSUE TITLE
I can't create the first user

### ISSUE THREAD

**Issue by castillofrancodamian** [jellyfin/jellyfin#4445] opened 2020-11-08 20:00 UTC
**Describe the bug**

 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 86
 - Jellyfin Version: 20201108.33-unstable
 - Networking: Host

1. In the terminal enter with root
```
docker run -d \
  --name jellyfin \
  -v /home/franco/datos/docker/jellyfin/cache:/cache \
  -v /home/franco/datos/docker/jellyfin/config:/config \
  -v /home/franco/datos/medios/flac:/flac \
  -v /home/franco/datos/medios/peliculas/español:/peliculas/español \
  -v /home/franco/datos/medios/peliculas/ingles:/peliculas/ingles \
  -v /home/franco/datos/medios/series/español:/series/español \
  -v /home/franco/datos/medios/series/ingles:/series/ingles \
  -v /home/franco/datos/torrents/flac:/torrents/flac \
  -v /home/franco/datos/torrents/peliculas/español:/torrents/peliculas/español \
  -v /home/franco/datos/torrents/peliculas/ingles:/torrents/peliculas/ingles \
  -v /home/franco/datos/torrents/series/español:/torrents/series/español \
  -v /home/franco/datos/torrents/series/ingles:/torrents/series/ingles \
  --user 1000:1000 \
  --net=host \
  --restart unless-stopped \
  jellyfin/jellyfin:unstable
```
2. I enter the command `chmod 777 -R /home/franco/data/docker/jellyfin` because I don't know how to make jellyfin write to the configuration folders.

3. I go to the browser and enter http://host:8096 and see the login page if I have created the first user.

I hope I can create the first user.

I have tried several snapshots of unstable Jellyfin and it happened too. Not in the stable version.

**Comment by crobibero** [comment] 2020-11-08 21:09
Duplicate of #4372

**Closed by crobibero** 2020-11-08 21:09 UTC
Labels: bug
