### ISSUE TITLE
Libraries chinese cannot be displayed normally

### ISSUE THREAD

**Issue by Herbertzz** [jellyfin/jellyfin#5930] opened 2021-04-29 02:57 UTC
The Chinese on the cover image of the media library has turned into squares and cannot be displayed normally.

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.7.2
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: yes: /web/index.html#!/home.html

**Comment by crobibero** [comment] 2021-04-29 03:46
Duplicate of https://github.com/jellyfin/jellyfin/issues/5930

**Closed by crobibero** 2021-04-29 03:46 UTC
Labels: bug
