### ISSUE TITLE
[Issue]: Windows poster.jpe not opening on web page

### ISSUE THREAD

**Issue by cinadr** [jellyfin/jellyfin#7016] opened 2021-12-18 17:30 UTC
### Please describe your bug

Scanning media on Windows x64 creates several poster.jpe files (which I assume should be jpg or jpeg). 
Opening a web connection to Jellyfin it generates several error messages in log.
Upon refreshing library Jelly intentionally saves these files with jpe extensions. (something converting a 4 letter extension to 3?)

Testing this on linux (in a HyperV VM) it is working. posters saved with jpg extensions and no error messages upon web requests.

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS: Windows Server 2019 Datacenter x64
- Virtualization: none
- Clients: Windows 11
- Browser: Google Chrome 96.0.4664.110
- FFmpeg Version: ffmpeg version n4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev9, Built by MSYS2 project)
- Playback Method: not applicable
```

### Jellyfin logs

Log excerpts has no relation as library refresh generates several similar lines...

```shell
[2021-12-18 18:07:11.771 +01:00] [ERR] [34] Emby.Drawing.ImageProcessor: Image conversion failed for "E:\JELLY\DATA\metadata\library\40\4041f7257f99f6035674d7cc8cdfb2dc\poster.jpe"
System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
   at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)

[2021-12-18 18:11:23.839 +01:00] [DBG] [25] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "E:\JELLY\DATA\metadata\library\2b\2b55a038e5919e76475b895e97339a9f\poster.jpe"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2021-12-18 17:58
Duplicate of https://github.com/jellyfin/jellyfin/issues/6972

**Closed by crobibero** 2021-12-18 17:58 UTC
Labels: bug
