### ISSUE TITLE
Sorting shows by "Date episode added" does not work as expected

### ISSUE THREAD

**Issue by D33M0N** [jellyfin/jellyfin#13265] opened 2024-12-22 00:30 UTC
**Describe The Bug**

Sorting shows by "Date episode added" does not work as expected -- I expect the list to be sorted by the date and time most recent singular or multiple episodes were added to the show folders and after the scan has picked it up. If you added entirely new show it would be first. If you added last aired episode to the folder, it would pump this old(er) show to the top.

**Steps To Reproduce**

1. Add an episode to the already existing show. (on my case, lets say s02e06 to the "[show name]/season 02/" folder)
2. In "Home" in "My Media" on "Shows"(or whatever you have named your shows library) icon/thumbnail click on 3 dots and refresh metadata and wait a little
3. observe that the unwatched episode number goes up by 1 on that show.
4. sort shows library by "Date episode added" and expect this show to be the first on the list. It is not. On my case the show remained still on 5th row on 47th place from the start (out of 160). Was there before I added the episode and remained there afterwards. Didn't move 1 spot in either direction.
5. (irrelevant to this bug, but to see the most recent activity, at least the sorting by "Date Played" works, as expected -- better to find the current show on 1st or 2nd line at least, not on 5th)

**Expected Behavior**

I would expect the sorting by "Date episode added" (to my library ... or by file creation date, either would be fine) work as expected.

**Logs**
there are no errors.

**Screenshots**

![Image](https://github.com/user-attachments/assets/6f1e0d98-3348-49dd-9de8-1b3de666dd2e)

as I just added it to the folders in system and file creation date was like couple of hours ago, it should be 1st in the list. Tried both options, file creation date and scanned date, doesn't work either way.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox 133
 - Jellyfin Version: 10.10.3

**Additional Context**
Doesn't work in LG WebOS TV either.

**Comment by felix920506** [comment] 2024-12-22 02:01
Duplicate of #6178

**Closed by felix920506** 2024-12-22 02:02 UTC
Labels: bug

**Comment by death69inc** [comment] 2025-04-08 13:12
hmmm wondering why its moved as duplicate of a movie sorting issue when its a tv sorting issue.  that still hasnt been fixed.

**Comment by manilx** [comment] 2025-04-23 09:29
same thing here. This sorting does NOT work. Works in Emby just fine.
