### ISSUE TITLE
Support ISO-8859-10 and other non-UTF encodings

### ISSUE THREAD

**Issue by Aanok** [jellyfin/jellyfin#2526] opened 2020-03-06 15:46 UTC
**Issue:**
Playback of ISO-8859-10 (Latin-9) encoded SubRip external subtitle fails because the server does not support the encoding.

**Media Info of the file**
```
General
Complete name                            : Aguirre The Wrath Of God (1972).en.srt
File size                                : 42.3 KiB
```

**Logs**
```
[2020-03-06 16:03:45.414 +01:00] [ERR] Error processing request
System.ArgumentException: 'ISO-8859-10' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(String path, String language, MediaProtocol protocol, Boolean requiresCharset, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Server System:**
 - OS: Debian 9.12
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: Software transcoding, Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
 - Reverse proxy: nginx
 - Other hardware notes: /
 
**Client System:**
 - Device: Desktop computer.
 - OS: Arch Linux
 - Client: Web/Browser
 - Browser: Firefox
 - Client and Browser Version: client 10.4.3, browser 73.0.1

**Miscellaneous**
A query to the relevant API endpoint (`/videos/...video id.../...stream id.../subtitles/2/stream.srt'`) returns a 404 error with the following body:
```
'ISO-8859-10' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
```

**Comment by JustAMan** [comment] 2020-03-06 16:05
Duplicate of https://github.com/jellyfin/jellyfin/issues/2200

**Closed** 2020-03-06 16:06 UTC
Labels: duplicate
