### ISSUE TITLE
Update Plugins Failed

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin#4052] opened 2020-09-04 16:11 UTC
**Describe the bug**
Scheduled task Update Plugins fails consistently with the following error:

> Access to the path 'Jellyfin.Plugin.Reports.dll' is denied. at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel) at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive) at System.IO.Directory.Delete(String path, Boolean recursive) at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: None
 - Jellyfin Version: 10.6.4 - This issue has been happening long before this version.

**To Reproduce**

1. Start Jellyfin Server
2. Scheduled task to update plugins fails
3. See error

**Expected behavior**
Plugins should auto update

**Additional context**
If I manually delete the plugins, and then install them, they work fine, but they won't auto update going forward.

**Comment by crobibero** [comment] 2020-09-04 16:13
Duplicate of https://github.com/jellyfin/jellyfin/issues/1623

**Closed by crobibero** 2020-09-04 16:13 UTC
Labels: bug
