### ISSUE TITLE
Jellyfin 10.7.2: Failed to load image of movie or tv show

### ISSUE THREAD

**Issue by cxlxin** [jellyfin/jellyfin#5812] opened 2021-04-14 14:14 UTC
**Describe the bug**
The image fails to load on the site of a movie or an episode of a TV show. The problem has been around since Jellyfin 10.7.2. On the start page, the thumbnail images for movies and TV shows load as usual.

The console is giving the following error message: "Failed to load resource: the server responded with a status of 400 (Bad Request)".

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: none
 - Clients: Browser
 - Browser: Google Chrome 89, Microsoft Edge 89
 - Jellyfin Version: 10.7.2
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Storage: local

**To Reproduce**

1. Go to a specific movie or episode of a TV show
2. See left card container is blurred and image failed to load
3. See error in browser console

**Expected behavior**
"Thumbnail" images of movies and TV shows should normally load.

**Screenshots**
<img width="1785" alt="Screenshot 2021-04-14 161859" src="https://user-images.githubusercontent.com/74431458/114725902-31dc0200-9d3d-11eb-99a7-d55f9f37686a.png">
![image](https://user-images.githubusercontent.com/74431458/114724103-854d5080-9d3b-11eb-8a80-b6b1e77d7a3c.png)

**Additional context**
The requested URL for example is the follwing: http://IP_TO_JELLYFIN:8096/Items/02e8ea35859af6433323199d26b894c5/Images/Primary?fillHeight=640&fillWidth=426.75&tag=c5109966211fe9e43373297086a4de00&quality=90

It should be: http://IP_TO_JELLYFIN:8096/Items/02e8ea35859af6433323199d26b894c5/Images/Primary?fullHeight=640&fullWidth=426.75&tag=c5109966211fe9e43373297086a4de00&quality=90

Look at the typos: "fillHeight=[...]" should be "fullHeight=[...]" and "fillWidth=[...]" should be "fullWidth=[...]".

**Comment by cvium** [comment] 2021-04-14 14:24
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2590

**Comment by crobibero** [comment] 2021-04-14 14:24
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2587

**Closed by cvium** 2021-04-14 14:24 UTC
Labels: bug
