### ISSUE TITLE
collection with name that includes ampersand are show with html entities in the web interface

### ISSUE THREAD

**Issue by eppesuig** [jellyfin/jellyfin#12572] opened 2024-09-03 13:55 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have two DVDs of Wallace & Gromit. When I scan the library, a new collection is created, and its name is "Wallace &amp;amp; Gromit - Collezione". As you see, the amperand letter is shown as (doubled) html entity.
This happens with other collection that contains that letter, i.e., "Monsters & Co."

### Reproduction steps

1. load a DVD of a file that incldues an & in the name
2. scan the library
3. check the collection result

### What is the current _bug_ behavior?

currently, this is the (Italiam) collection name "Wallace &amp;amp; Gromit - Collezione"

### What is the expected _correct_ behavior?

The correct displayed name should be "Wallace & Gromit - Collezione"

### Jellyfin Server version

10.9.10+

### Specify the build version

10.9.10+deb12

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-25-amd64
- Virtualization: no
- Clients: Browser
- Browser: Firefox 129.0.2 amd64
- FFmpeg Version: 5.1.4-3-bookworm
- Playback Method: Direct Stream
- Hardware Acceleration: VAAPI
- GPU Model: Intel Corporation HD Graphics 530
- Plugins: DLNA
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: NFS
```

### Jellyfin logs

```shell
.
```

**Comment by eppesuig** [comment] 2024-09-03 13:57
The issue shows incorrectly the wrong title. The wrong collection title shown by jellyfin is:
```
Wallace &amp;amp; Gromit - Collezione
```

**Comment by felix920506** [comment] 2024-09-03 14:03
Duplicate of #11424

**Closed by felix920506** 2024-09-03 14:03 UTC
Labels: bug
