### ISSUE TITLE
Segmentation fault when running jellyfin directly on original Raspberry Pi (armhf debian buster)

### ISSUE THREAD

**Issue by daviewales** [jellyfin/jellyfin#4959] opened 2021-01-05 11:26 UTC
**Describe the bug**

When I run `jellyfin` or `jellyfin --help`, I get a segmentation fault.
When I try to start jellyfin using `systemctl`, it doesn't start. (Presumably because of the segmentation fault?)

**System (please complete the following information):**
 - OS: Raspbian (debian buster)
 - Hardware: Original Raspberry Pi model B Rev 1
 - Architecture: armhf
 - Virtualization: None
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.6..4-1
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Local
 - Storage: N/A

**To Reproduce**

1. Install jellyfin using the [instructions for stable jellyfin on Debian](https://jellyfin.org/downloads/).
2. Attempt to start jellyfin

**Expected behavior**
Jellyfin should start without a segmentation fault.

**Logs**
I'm not sure where to find the logs.
I looked in `~/.local/share/` and `~/.config/`, but jellyfin hasn't created anything yet.

**Comment by Artiume** [comment] 2021-01-06 21:04
im not sure if jellyfin has ever been able to run on the original pi hardware.

**Comment by Bond-009** [comment] 2021-01-12 23:30
Duplicate of #5011

**Closed by Bond-009** 2021-01-12 23:30 UTC
Labels: bug
