### ISSUE TITLE
VAAPI [Enable hardware encoding] unchecks itself after playing particular videos

### ISSUE THREAD

**Issue by alexs20** [jellyfin/jellyfin#1726] opened 2019-09-09 18:13 UTC
That bug was reported in r/jellyfin reddit but i afraid that it just got lost.
So, the problem is as follow:
I am running latest jellyfin server in docker with passing /dev/dri device through.
I have VAAPI HW acceleration enabled and set to [/dev/dri/renderD128], [Enable hardware encoding] checkbox is checked.
Most of videos are playing ok and " intel_gpu_top" reports that GPU is involved in transcoding process.
But after playing a particular video jellyfin unchecks the [Enable hardware encoding] checkbox and after that is stops using GPU at all. Need to check it again and save to enable it again.

I do not see any log errors or any suspicious warnings.
Here are log files that i collected right after playing that video that resets the [Enable hardware encoding] checkbox.

ffmpeg_transcode_xxx.txt -> https://pastebin.com/rg5pvvWe
log_xxx_.log -> https://pastebin.com/9pjUcGhe

Let me know if you need additional info or logs

**Comment by joshuaboniface** [comment] 2019-09-09 18:15
Thanks @alexs20 it was still on my radar but hadn't had a chance to make the issue yet. Appreciate it!

**Comment by joshuaboniface** [comment] 2019-09-09 18:15
Damn wrong button... sorry!

**Comment by alexs20** [comment] 2019-09-09 19:33
An update.
i tried to run the latest 10.4.0 RC (nightly docker build)
and now i see the error

`[19:03:43] [INF] /usr/local/bin/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media/usb2/Carnival.Row/S01/Carnival.Row.s01e01.WEBRip.RGzsRutracker.avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 3808000 -bufsize 7616000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "hwdownload,format=nv12,scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/transcode/transcodes/a3d64f8b58b3260657f343b16f946782.m3u8" -y "/transcode/transcodes/a3d64f8b58b3260657f343b16f946782%d.ts"

[19:03:43] [ERR] FFMpeg exited with code 1
`
So, i descided to run that command manually and got the folowing
`
ffmpeg version 4.0.3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gnutls --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-cuvid --enable-nvenc --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, avi, from 'file:/media/usb2/Carnival.Row/S01/Carnival.Row.s01e01.WEBRip.RGzsRutracker.avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.3 | www.virtualdub-fr.org || (build 2550/release)
  Duration: 01:00:37.14, start: 0.000000, bitrate: 1997 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x304 [SAR 1:1 DAR 45:19], 1599 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[mpeg4 @ 0x558902f21780] No support for codec mpeg4 profile 15.
[mpeg4 @ 0x558902f21780] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
[libmp3lame @ 0x558902ee1200] 3 frames left in the queue on closing
Conversion failed!
`
Seems like my GPU does not support some MPEG4 format variations. And seems like that bug actually came from Emby [https://github.com/MediaBrowser/Emby/issues/2285]

Also i found that 10.4.0 RC is working differently than 10.3.7
Before, it just unchecked that HW acceleration checkbox and felt back to software transcoding, but not it still unchecks it, but there is no more fall-backs. It just continue to print errors and no video on client side, which is not a good behaviour IMHO. 

 So the proper behaviour, i think should be to check if HW accell supports particular media and only then use it, otherwise fall back to software transcoding without disabling that in settings.

**Comment by nevado** [comment] 2019-09-09 21:10
Dupe of https://github.com/jellyfin/jellyfin/issues/1360?

**Comment by alexs20** [comment] 2019-09-09 21:19
> Dupe of #1360?

Seems like yes, except that in my case i also tested on 10.4.0 RC, where that issue is became much worse.

**Comment by joshuaboniface** [comment] 2019-09-28 21:38
We're having issues with lack of VAAPI to test with. Can anyone affected provide server logs isolating just the behaviour here?

**Comment by joshuaboniface** [comment] 2019-09-28 21:38
Also might be worth trying the latest nightlies just in case.

**Comment by dkanada** [comment] 2019-09-29 07:23
see #1812

**Closed** 2019-09-29 15:43 UTC
Labels: bug
