### ISSUE TITLE
Automatic grouping of movies into collections

### ISSUE THREAD

**Issue by iacchi** [jellyfin/jellyfin#688] opened 2019-01-23 19:36 UTC
**Describe the bug**
The option to group movies into collections is not working. If I well understood the purpose of this option, when it is enabled if I have e.g. Lethal weapon 1, 2, 3 and 4 these should be automatically grouped in a single collection entry in the movie list, and then I can choose which movie I want to watch when I enter the collection.

**To Reproduce**
1. Go to Settings -> Library -> Display
2. Enable "Group movies into collections"
3. Open a Movie library in browse mode
4. Related movie series are not grouped together

**Expected behavior**
Movies get automatically grouped into collections.

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox
 - Jellyfin Version: 10.0.2.0

**Additional context**
New jellyfin installation, Emby was never installed in the system.

**Comment by g33kphr33k** [comment] 2019-01-23 19:54
Collections is currently a manual process. 

- Click and hold on a movie in your movie list to enable selections
- Click the 3 dot menu and select "Add to Collection"
- On the collections screen, either select an existing collection previously created or create a new collection.

**Comment by iacchi** [comment] 2019-01-23 20:22
Good to know (should we leave this bug open until this becomes automatic?). One question though: if I create a collection with my user, will such collection spread to all other users in the system as well?

**Comment by g33kphr33k** [comment] 2019-02-14 20:11
>  One question though: if I create a collection with my user, will such collection spread to all other users in the system as well?

Yes, it does show for other users.

**Comment by JustAMan** [comment] 2019-02-15 10:44
Right now all works as intended, so it's not a bug.
I have repurposed this as a feature request for automatic grouping of movies in collections.

**Comment by cvium** [comment] 2019-02-15 11:07
There is already a plugin for this, https://github.com/cvium/jellyfin-plugin-tmdbboxsets

**Comment by iacchi** [comment] 2019-02-15 11:29
Good to know!

**Comment by JustAMan** [comment] 2019-02-15 13:17
@iacchi can you try that plugin? We're hoping that it should close this issue for you.

**Comment by iacchi** [comment] 2019-02-15 14:14
I'll try it as soon as I get home (and as soon as I figure out how to install plugins... :P)

**Comment by iacchi** [comment] 2019-02-15 22:02
I have installed the plugin and it works as intended. The only thing I'm not sure I like is that it actually creates a "Collections" library as well, while it would be enough to have the groups in the original library (they are there as well) without making a new (sort of) library appear as well. Anyway, good enough for me, I guess you can close this issue if you want.

**Closed** 2019-02-15 22:02 UTC
Labels: feature

**Comment by JustAMan** [comment] 2019-02-16 00:14
> it actually creates a "Collections" library as well

@cvium can we make this behaviour configurable?

**Comment by cvium** [comment] 2019-02-16 05:43
Doesn't Emby's Auto Box Sets also do this?

**Comment by iacchi** [comment] 2019-02-16 12:02
Thank you cvium for checking. Do you guys think it's worth to have this as a feature request?

**Comment by bwaddington** [comment] 2019-02-27 22:24
could you please update jellyfin-plugin-tmdbboxsets to make it compatible with jellyfin version 10.2.1 and would it be possible to add this to the jellyfin plugin page thank you

**Comment by bwaddington** [comment] 2019-02-27 22:26
could you please update jellyfin-plugin-tmdbboxsets to make it compatible with jellyfin version 10.2.1 and would it be possible to add this to the jellyfin plugin page thank you

**Comment by JustAMan** [comment] 2019-02-28 13:34
Isn't it already there? cc @joshuaboniface

**Comment by Uatschitchun** [comment] 2019-03-03 11:12
I have all movie sets tagged within the corresponding nfo files. Will this plugin read them?

**Comment by sindizzy** [comment] 2021-07-11 05:25
I think this is very important feature. I have tons of movies that are part of collections and its great to see the collection in its own display. If I were to start looking at the code on how to do this....where would I look?

**Comment by cvium** [comment] 2021-07-11 06:45
@sindizzy what do you mean? We have a plugin that automatically creates collections and there's a library view option for grouping movies into collections

**Comment by sindizzy** [comment] 2021-07-18 02:44
@cvium I didnt realize the plugin had been up[dated. I was going by this post https://forum.jellyfin.org/t/sorting-of-movies-in-collections/2452/2 that said it was broken. I realize now that the bugs were fixed. I will try that plugin now.
