### ISSUE TITLE
 [WRN] Unable to find linked item at path E:\mp4

### ISSUE THREAD

**Issue by siyiye** [jellyfin/jellyfin#8694] opened 2022-11-04 05:58 UTC
### Please describe your bug

10.8.4-->10.8.7

Use the chrome browser or use the APP.

Click into any library, and go in circles. The server log goes crazy showing no video file found:
“[WRN] Unable to find linked item at path xxx.mkv”

### Jellyfin Version

10.8.0

### if other:

10.8.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[13:52:27] [WRN] Unable to find linked item at path xxx.mkv
[13:52:27] [WRN] Unable to find linked item at path xxxxx.mkv
[13:52:27] [WRN] Slow HTTP Response from .......
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siyiye** [comment] 2022-11-04 06:02
[14:01:21] [WRN] The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[14:01:21] [WRN] The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.

**Comment by siyiye** [comment] 2022-12-02 15:03
up for look

**Comment by denikrejn1000** [comment] 2023-01-08 20:03
Confirmed 
10.8.8 same error...

**Comment by Bond-009** [comment] 2023-01-09 14:44
Do you have the TMDb Box Sets Plugin installed?

**Comment by VigibotDev** [comment] 2023-03-08 17:38
I solved this by removing all Box Sets plugin data inside "/var/lib/jellyfin/data/collections/*" (just delete all file and do a plugin collection rescan)

**Comment by Bond-009** [comment] 2023-03-08 20:09
Closing as duplicate of #1907

**Closed by Bond-009** 2023-03-08 20:09 UTC
Labels: bug
