### ISSUE TITLE
Busy: database is locked

### ISSUE THREAD

**Issue by gadgrandez** [jellyfin/jellyfin#987] opened 2019-02-23 00:31 UTC
**Description**
In Google Kubernetes Engine (GKE), scaling up a pod running Jellyfin produces an unhandled exception.

**To Reproduce**
Just scale a pod running jellyfin.

<details>
  <summary>Logs</summary>

```
[00:10:38] [INF] Jellyfin version: 10.2.1.0
[00:10:38] [INF] Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache"]
[00:10:38] [INF] Operating system: Linux 4.14.89.0
[00:10:38] [INF] Architecture: X64
[00:10:38] [INF] 64-Bit Process: True
[00:10:38] [INF] User Interactive: True
[00:10:38] [INF] Processor count: 2
[00:10:38] [INF] Program data path: /config
[00:10:38] [INF] Application directory: /jellyfin/
[00:10:38] [INF] Setting cache path to /cache
[00:10:38] [INF] Loading assemblies
[00:10:38] [INF] Sqlite version: 3.26.0
[00:10:38] [INF] Sqlite compiler options: COMPILER=gcc-5.4.0 20160609,DEFAULT_FOREIGN_KEYS,ENABLE_COLUMN_METADATA,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS4,ENABLE_FTS5,ENABLE_JSON1,ENABLE_RTREE,THREADSAFE=1
[00:10:38] [INF] Default journal_mode for /config/data/users.db is wal
[00:10:38] [INF] PRAGMA synchronous=1
[00:10:38] [INF] Default journal_mode for /config/data/authentication.db is wal
[00:10:38] [INF] PRAGMA synchronous=1
[00:10:39] [INF] Default journal_mode for /config/data/activitylog.db is wal
[00:10:39] [INF] PRAGMA synchronous=1
[00:10:39] [INF] Default journal_mode for /config/data/displaypreferences.db is wal
[00:10:39] [INF] PRAGMA synchronous=1
[00:10:39] [INF] Disposing CoreAppHost
[00:10:39] [FTL] Unhandled Exception
Busy: database is locked
SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.CreateConnection(Boolean isReadOnly) in /repo/Emby.Server.Implementations/Data/BaseSqliteRepository.cs:line 103
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager) in /repo/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 101
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection) in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 612
   at Jellyfin.Server.Program.StartApp(StartupOptions options) in /repo/Jellyfin.Server/Program.cs:line 143
   at Jellyfin.Server.Program.Main(String[] args) in /repo/Jellyfin.Server/Program.cs:line 55
   at Jellyfin.Server.Program.<Main>(String[] args)

Unhandled Exception: SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, String& tail)
   at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.CreateConnection(Boolean isReadOnly) in /repo/Emby.Server.Implementations/Data/BaseSqliteRepository.cs:line 103
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager) in /repo/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 101
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection) in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 612
   at Jellyfin.Server.Program.StartApp(StartupOptions options) in /repo/Jellyfin.Server/Program.cs:line 143
   at Jellyfin.Server.Program.Main(String[] args) in /repo/Jellyfin.Server/Program.cs:line 55
   at Jellyfin.Server.Program.<Main>(String[] args)
Aborted (core dumped)
```
</details>

**System:**
 - OS: Docker
 - Jellyfin Version: 10.2.1

<details>
  <summary>Additional context</summary>

```
kubectl describe pod:
Name:               jellyfin-8568dd78cc-cglsm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               gke-jellyfin-cluster-main-pool-1b8895db-5xlg/10.142.0.23
Start Time:         Fri, 22 Feb 2019 18:38:27 -0500
Labels:             app=jellyfin
                    pod-template-hash=4124883477
Annotations:        kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container jellyfin
Status:             Running
IP:                 10.52.0.11
Controlled By:      ReplicaSet/jellyfin-8568dd78cc
Containers:
  jellyfin:
    Container ID:   docker://9574fc6b439f797e2008811567344c22c94dca6a048f5e3cb3ec22ee0b135e4c
    Image:          gcr.io/nube-217803/jellyfin:alpine
    Image ID:       docker-pullable://gcr.io/nube-217803/jellyfin@sha256:5a84dc3d83d548f20ab429cced2973c93fb482fd7289d2978027e6c73fd8f7c8
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    134
      Started:      Fri, 22 Feb 2019 19:25:54 -0500
      Finished:     Fri, 22 Feb 2019 19:25:56 -0500
    Ready:          False
    Restart Count:  14
    Requests:
      cpu:  100m
    Environment:
      GOOGLE_APPLICATION_CREDENTIALS:  /var/secrets/google/key.json
    Mounts:
      /config from jellyfin-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g49xk (ro)
      /var/secrets/google from google-cloud-key (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  jellyfin-config:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfs
    ReadOnly:   false
  google-cloud-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gcs-key
    Optional:    false
  default-token-g49xk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-g49xk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                   Message
  ----     ------     ----                ----                                                   -------
  Normal   Scheduled  51m                 default-scheduler                                      Successfully assigned default/jellyfin-8568dd78cc-cglsm to gke-jellyfin-cluster-main-pool-1b8895db-5xlg
  Normal   Created    50m (x4 over 51m)   kubelet, gke-jellyfin-cluster-main-pool-1b8895db-5xlg  Created container
  Normal   Started    50m (x4 over 51m)   kubelet, gke-jellyfin-cluster-main-pool-1b8895db-5xlg  Started container
  Normal   Pulling    49m (x5 over 51m)   kubelet, gke-jellyfin-cluster-main-pool-1b8895db-5xlg  pulling image "gcr.io/nube-217803/jellyfin:alpine"
  Normal   Pulled     49m (x5 over 51m)   kubelet, gke-jellyfin-cluster-main-pool-1b8895db-5xlg  Successfully pulled image "gcr.io/nube-217803/jellyfin:alpine"
  Warning  BackOff    1m (x223 over 51m)  kubelet, gke-jellyfin-cluster-main-pool-1b8895db-5xlg  Back-off restarting failed container
```
</details>

**Comment by BnMcG** [comment] 2019-02-23 22:42
What's your pod manifest?

**Comment by ploughpuff** [comment] 2019-03-01 00:46
SQLite was unable to open/create the library.db, and Busy indicates the database is locked.

Crashed process still retaining locks perhaps?

**Comment by jvanst** [comment] 2019-03-25 20:01
I am also encountering this exact problem, and I don't know which direction I should be looking for a solution. 

Here are my deployment and volume configs.

<details>
  <summary>Deployment</summary>
  
  ```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: default
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - image: gcr.io/project/jellyfin
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - gcsfuse
              - --implicit-dirs
              - -o
              - nonempty
              - project-media
              - /mnt/media
          preStop:
            exec:
              command:
              - fusermount
              - -u
              - /mnt/media
        name: jellyfin-sha256
        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: jellyfin-config
      restartPolicy: Always
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config
  ```
  
</details>

<details>
  <summary>PersistentVolumeClaim</summary>
  
  ```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  ```
  
</details>

**Comment by joshuaboniface** [comment] 2019-03-25 20:07
So the issue, at least as far as I understand it, is that Jellyfin is not being properly shut down by Kubernetes (probably making the terrible assumption that containerized infra seems to make, that they can just put a bullet in their containers with nary a care) and as a result the database stays locked and can't be reopened until the lock is cleared. You also wouldn't be able to open a second instance of Jellyfin targeting the same database file while the first is still running, since the effect is the same.

I suspect this won't happen if the container shuts down gracefully first (i.e. the Jellyfin process is allowed to terminate normally), but I don't use Kube and can't verify if any of what I said is correct or valid - it just sounds like the case.

**Comment by BnMcG** [comment] 2019-03-25 20:10
I use Jellyfin in Kubernetes and haven't had a problem with it, I've been running it for about a month with several restarts in between for upgrades.

Has jellyfin ever worked for you in Kubernetes, or is this a fresh startup?

-------- Original Message --------

**Comment by BnMcG** [comment] 2019-03-25 20:41
The only obvious difference I can see with my configuration is that I'm running Kubernetes on-prem and use NFS for binding PVCs... @jvanst I wonder if this is something to do with the storage backing your PVCs. Are you on GKE? Do you know what storage is backing your persistent volumes?

**Comment by jvanst** [comment] 2019-03-25 21:10
I only have issues when scaling replica pods. I am on GKE and the PVC are backed up by Google Compute disks. Have you been able to have many pods accessing a single PV?

**Comment by BnMcG** [comment] 2019-03-25 21:12
No, as @joshuaboniface said, you can't have multiple instances accessing a single SQLite database.

**Comment by BnMcG** [comment] 2019-03-26 13:18
Looking at the original issue again, I'd recommend this issue is closed (or at least untagged as a bug) - SQLite will throw this error when scaling pods because you can only have 1 process accessing the database. By definition, scaling a pod will have multiple processes trying to communicate with the same database. This will remain the case until #42 is implemented, and support for a proper RDBMS (PostgreSQL, MariaDB, SQL Server,  etc) is implemented.

**Comment by JustAMan** [comment] 2019-03-27 14:57
@gadgrandez I'm thinking of closing this issue in favor of #42, as the issue you're facing right now is somewhat "by design" - SQLite limitation. Any objections?

**Closed** 2019-03-30 01:23 UTC
Labels: bug

**Comment by ddurdle** [comment] 2019-10-13 22:34
Starting in sqlite 3.3, you can have multiple concurrent readers of a sqlite db file.  Obviously only one writer.  But the fact that you can have read-only clones does lead to some opportunities.
