### ISSUE TITLE
ubuntu focal 20.04

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin#2896] opened 2020-04-16 22:11 UTC
No focal repository. 
no ffmpeg compatiobilty , please solve asap

**Comment by crobibero** [comment] 2020-04-17 14:55
dupe of https://github.com/jellyfin/jellyfin/issues/2832

**Comment by dga4130-renato** [comment] 2020-04-17 16:46
rigt

**Closed** 2020-04-17 16:46 UTC
Labels: bug
