### ISSUE TITLE
4K playback on 1080p Android TV fails

### ISSUE THREAD

**Issue by Ozwel** [jellyfin/jellyfin#10453] opened 2023-10-22 11:59 UTC
any 4K content won’t play and lead to a playback error message then go back to content menu.

no problème with 1080p content.

the TV is 1080p only, I would expect transcoding to take place but I can’t even access to the video format settings during playback to force a 1080p transcoding format.

**Media Info of the file**
Every film in 4K format whatever its compression format.

**Logs**
https://wtf.roflcopter.fr/paste/?11e541343f08af1a#AMtPZz1yHwnvzXECMrJDr41kWJEJj4q57dHsGtMPcZ1Z

**FFmpeg Logs**
Check the link above

**Server System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: AMD 6800U
 - Reverse proxy: caddy
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: android TV Mi L32M5
 - OS: android tv
 - Client: Jellyfin app playstore
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by srcrist** [comment] 2023-10-22 15:55
Closing this issue as it does not reference a Jellyfin server bug. The transcoding log provided is not indicating any issues with the server. Playback failure can be caused by any number of other conditions. Please visit the support communities on our forums or the Matrix/Discord server and someone can help you look at the logs and figure out why the client is not requesting the correct video formats for your device.

**Closed by srcrist** 2023-10-22 15:55 UTC
