### ISSUE TITLE
*.ass not working

### ISSUE THREAD

**Issue by huanx9** [jellyfin/jellyfin#2700] opened 2020-03-28 21:00 UTC
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows
 - Virtualization:
 - Clients: Browser
 - Browser: Firefox 72~~
 - Jellyfin Version: Jellyfin 10.5.2 New
 - Playback: 
 - Installed Plugins: 
 - Reverse Proxy:
 - Base URL:
 - Networking:
 - Storage: 

*.ass   UTF-8 BOM  / UTF-8 / ANSI   Chinese language all   口口口口口口口口口口口口口口  
just  support English and number

*.ass = danmaku 

~~My English is bad ~~ , like this  

![](https://cdn.jsdelivr.net/gh/huanx9/img/img/Snipaste_2020-03-29_04-53-17.png)
![](https://cdn.jsdelivr.net/gh/huanx9/img/img/Snipaste_2020-03-29_04-53-28.png)

**Comment by Artiume** [comment] 2020-03-28 21:42
Looks like a duplicate of https://github.com/jellyfin/jellyfin/issues/2670

**Comment by huanx9** [comment] 2020-03-29 06:02
[thanks](https://github.com/jellyfin/jellyfin/issues/2670#issuecomment-602740958)

**Comment by dkanada** [comment] 2020-03-29 06:52
I'll close this for now in favor of that issue.

**Closed by dkanada** 2020-03-29 06:52 UTC
Labels: bug
