### ISSUE TITLE
set info in NFO not creating collections in JF

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#5477] opened 2021-03-10 21:17 UTC
**Describe the bug**
NFO for movie with set name does not result in JF creating a collection with that name.

**System (please complete the following information):**
 - OS: Armbian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 88
 - Jellyfin Version: 10.7.0

**To Reproduce**

Create movie.nfo file (all movies are in their own directory.
/media/movies/Avengers Endgame/movie.nfo
```
<movie>
        <set>MCU</set>
</movie>
```
No collection is created. I've tried several variations of movie.nfo
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
        <set>MCU</set>
</movie>
```
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
        <set>
                <name>MCU</name>
        </set>
</movie>
```
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
        <set>
                <name>MCU Collection</name>
        </set>
</movie>
```
I also tried with another movie incase the collection wouldn't show up with only one movie. Still didn't show up. Manually creating a collection with 1 movie shows up.

**Expected behavior**

Set info should be read from NFO. It appears there is code to do this.

**Comment by cvium** [comment] 2021-03-11 12:21
We have unit tests that verify that the CollectionName is set on the item. I don't see any references in the code to automatic collection creation though.

**Comment by SenorSmartyPants** [comment] 2021-03-11 15:38
So if I have a collection with at least one movie in it then set nfo should work correctly? I will test this today. 

Seems like an oversight to not create the collection if it is missing.

**Comment by SenorSmartyPants** [comment] 2021-03-11 18:19
I manually added one movie to a new collection. I removed two movies from the JF library that I want to add to that collection via NFO. Rescan library. Moved those two movie directories back into the JF library directory. Rescan library. Movies are added into JF library, but not added to collection.

**Comment by SenorSmartyPants** [comment] 2021-03-11 18:50
I can see in the debug log that MovieNfoProvider is being run on the movie import. But there is no more debug output from the provider.

**Comment by Ullmie02** [comment] 2021-03-19 18:12
Yes, CollectionName gets set but isn't used anywhere. So not a bug but a feature which doesn't exist.
If you however use a nfo like this
```
<set tmdbcolid="12345">MCU Collection</set>
```
in combination with the TMDb Boxset plugin, it could work. But the id has to be a valid TMDb Boxset id.

**Comment by the-lazy-fox** [comment] 2021-08-16 17:39
I also noticed that the Metadata saved into NFO a creating a format like <set>MCU</set> but Kodi is recommending to have a sub node “name”.
I have no collection created at all…
Any advices?

**Comment by cvium** [comment] 2021-08-17 07:12
@the-lazy-fox Please stop hijacking slightly related issues.

@SenorSmartyPants Sorry to close this after so long, but since it's a feature request it should be posted here https://features.jellyfin.org/

**Closed by cvium** 2021-08-17 07:12 UTC
Labels: feature
