### ISSUE TITLE
Broken album displays in music libraries

### ISSUE THREAD

**Issue by niftium** [jellyfin/jellyfin#3169] opened 2020-05-24 21:14 UTC
**Describe the bug**
Within my music library, several artists have all of their tracks lumped together under one album.  The metadata has been checked and should be dividing up tracks by their albums correctly.

**System (please complete the following information):**
 - OS: Xubuntu 20.04
 - Virtualization: none
 - Clients: Firefox, Android
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.5
 - Playback: all transcoding defaults untouched; no h/w acceleration
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: ?
 - Storage: local files

**To Reproduce**

1. Go to one of the affected artists in my music library; for this example, I'll use Sea Wolf
2. Click on Sea Wolf in the artist list
3. Look at the list of albums and the list of tracks below it.  All four Sea Wolf albums are dumped into one album "White Water, White Bloom".  

**Expected behavior**
Checking the metadata on individual songs shows that each file is correctly tagged with its respective album, so I would expect to see separate albums as I do for other artists who show up correctly.

**Logs**
Playback isn't affected, so no error is shown.

**Screenshots**
See the attached screenshot of the Sea Wolf page.

**Additional context**
I was able to fix one such issue with a different artist by taking the period out of a song "Mr." --> "Mr" and doing a metadata refresh.  I suspect Sea Wolf is breaking because of the comma in the album name above.  I suspect other songs/albums of being the culprit(s) of other broken artists.  For example, all Oasis (the artist) tracks are lumped under the album title "(What's the Story) Morning Glory?".  Another example would be the artist Doves; all of their tracks are lumped into the album "The Best of Doves: The Places Between".

![sea_wolf_example](https://user-images.githubusercontent.com/65871595/82765069-9585d580-9de1-11ea-86fc-9571c834c545.png)

**Comment by NovaCyntax** [comment] 2020-05-27 03:42
I have this same issue. My library is properly sorted in other media players, and the file hierarchy is proper.

![image](https://user-images.githubusercontent.com/20057705/82975460-80a86e00-9faa-11ea-8892-0fb8ff1c07ca.png)

**Comment by niftium** [comment] 2020-05-27 14:45
The issue with the artist that I was able to correct was with an artist that only has two albums and no tracks residing outside of their album's proper folders.

Screenshot of artist-level hierarchy:
![Screenshot_2020-05-27_09-13-28](https://user-images.githubusercontent.com/65871595/83023580-153abc80-9ffb-11ea-95f5-effe5ce1127d.png)

Screenshot of artist > album-level hierarchy (for affected album):
![Screenshot_2020-05-27_09-13-13](https://user-images.githubusercontent.com/65871595/83023606-1bc93400-9ffb-11ea-8816-5520f2f70431.png)

By removing the period in the track "Mr. Midnight", I was able to get the albums to divide out correctly again in Jellyfin.

**However (and this is important!):**

What NovaCyntax is describing is also definitely true.  I was able to fix a number of my broken artists by moving singles into their own folders under the artist hierarchy.  Not all, but most.  I have at least one instance where a track residing outside of the proper folder structure does NOT break the directory view.  I'm going to spend some more time going through my folders to see what remains broken.  I've read about wonky behavior due to unexpected folder structures, but I can't recall if that was here or on Reddit.

**Comment by NovaCyntax** [comment] 2020-05-27 21:21
I can confirm on my end that moving singles to a folder will prevent this behavior from occurring, pic related.

![image](https://user-images.githubusercontent.com/20057705/83073286-2fe25500-a03e-11ea-8c7f-aa9fb5e41035.png)

 If I run into specific instances of special characters breaking sorting in the future, I will provide examples. May be of interest to note that this phenomenon can occur based on two (possibly more) conditions.

**Comment by MegaS0ra** [comment] 2020-05-27 21:33
Same issue here.
The issue appeared after adding single songs in the artist folder. (Found out one of the albums had a song named "J.J. the Baker").

But for me, just moving the singles to their own folder didn't solve the problem (am I missing something?)
I had to rename the song without the dots, and after the automatic re-scan, it showed properly.
I renamed it back with the dots, and it's still okay.

**Comment by niftium** [comment] 2020-05-28 00:36
Since we appear to be dealing with multiple forms of breakage, I updated the bug title to more accurately reflect the core issue.

**Comment by NovaCyntax** [comment] 2020-05-28 00:54
> Same issue here.
> The issue appeared after adding single songs in the artist folder. (Found out one of the albums had a song named "J.J. the Baker").
> 
> But for me, just moving the singles to their own folder didn't solve the problem (am I missing something?)
> I had to rename the song without the dots, and after the automatic re-scan, it showed properly.
> I renamed it back with the dots, and it's still okay.

In my case, each single had to have its own unique folder. A folder named "Singles" containing all singles ended up being displayed incorrectly within the library as well.

**Comment by niftium** [comment] 2020-05-28 02:25
> > Same issue here.
> > The issue appeared after adding single songs in the artist folder. (Found out one of the albums had a song named "J.J. the Baker").
> > But for me, just moving the singles to their own folder didn't solve the problem (am I missing something?)
> > I had to rename the song without the dots, and after the automatic re-scan, it showed properly.
> > I renamed it back with the dots, and it's still okay.
> 
> In my case, each single had to have its own unique folder. A folder named "Singles" containing all singles ended up being displayed incorrectly within the library as well.

Interesting.  I just dumped everything into a folder called "Random" for each artist and got the mostly-good results that I did.

**Comment by NovaCyntax** [comment] 2020-05-28 04:07
I operate within a Linux environment, so I just wrote a quick bash script to find each file with a .mp3 extension within first-level directories, and for each found match it would create a folder titled the name of the track, and move the track to the folder. Re-scanning my library now, if there are any organization issues in the future it will likely be due to special characters/formatting in titles and such.

**Comment by niftium** [comment] 2020-09-25 20:34
Using a combination of all of the workarounds mentioned above, I think I've squashed all of the instances of this happening on my system.  I still believe this behavior is broken though.

**Comment by GarrickWinter** [comment] 2020-11-13 04:02
I've encountered this issue today, after adding a new album I bought from Bandcamp to my library. I already had an existing folder for this artist's music in my library that Jellyfin had been correctly displaying, but after adding this one everything suddenly got lumped into one mega-album.

None of the album's tracks had any periods, but one did have a comma, so I removed that. I also removed commas from all other filenames in that artist's folder. I should also note that I did previously have a single not in its own album that seemed to have worked fine, but after reading this thread, I stuck it in a folder of the same name alongside the other albums.

After taking the above steps and re-scanning the library, the artist's albums were displayed correctly again. So something is still wrong.

Version: 10.6.2
OS: Windows
Architecture: X64

**Comment by GarrickWinter** [comment] 2020-11-15 18:34
This happened again with another artist. This time the only thing I changed to fix the issue was moving singles or otherwise uncategorized songs that were in the artist folder directly (alongside album folders, rather than in an album folder) into their own album subfolders.

**Comment by niftium** [comment] 2020-11-15 18:41
> This happened again with another artist. This time the only thing I changed to fix the issue was moving singles or otherwise uncategorized songs that were in the artist folder directly (alongside album folders, rather than in an album folder) into their own album subfolders.

If you pull them out of that folder and leave them at the artist's root directory, does it break again?  That's the other side of the breakage coin - re-breaking, once fixed, isn't consistently reproducible for me.

**Comment by GarrickWinter** [comment] 2020-11-15 18:51
Woah. I tried that - I took one song from one of the newly-created album folders, cut it, and pasted it back to the root directory.

The result was that when I opened that artist in Jellyfin, I still saw all the albums, so they didn't merge back into one... but _any_ album I clicked on had no tracks in it at all.

I'm only able to find tracks by that artist through the search functionality, and when I view them and play them, they have artist information but the ones that are in album folders and don't have album metadata don't display their albums at all.

The ones that do have album metadata on the files themselves, well, they list the correct name of their album, but when I click on the album _name_ in the track view, it brings me back... to the exact same huge mega-album where all the tracks were dumped before I fixed this, and I can see all the tracks in this faulty album, even though I can't see that faulty album in the artist view.

**Comment by Mange** [comment] 2020-11-22 22:11
I can confirm the same issue in my library; a lot of artists have all their songs grouped into one of the albums. Seems to happen mostly on artists where I have a random track not part of an album directory.

I assume the artist's directory got tagged with the random track's album, and hence all other tracks in the hierarchy ends up under that album since it inherits the parent's metadata instead of its own…?
I checked the metadata tree under the admin, and strangely it displays all the *albums* as nested under the root for some reason.

Here's my structure:

```
music/
  Artists/
    Some Artist/
      Album 1/
        1. Track 1.mp3
        …
      Some Good Track.mp3
  Soundtracks/
    Some Movie/
      …
```

Yet, the metadata tree shows this as

```
music/
  Artists/
    Album 2/
```

If I click on "Album 2", assuming this is one such "merged" album, I see it's pointing to `music/Artists/Some Artist`, but has a `Title` set on it matching the album. "Some Good Track" happens to come from "Album 2".

![image](https://user-images.githubusercontent.com/1599/99918572-1170c400-2d18-11eb-9f2b-559ea477b120.png)

**Comment by Mange** [comment] 2020-11-23 20:14
I rebuilt my entire library from scratch to force all tracks to be under an album directory, and now I don't have that problem anymore.

Now I only have to deal with the redundancy of Jellyfin trying to identify things that are already correctly tagged and misidentifying things, and not being able to handle things that don't exist in MusicBrainz. That's an unrelated issue, of course. :smile:

**Comment by guix77** [comment] 2020-11-23 20:18
Did exactly the same thing few days ago.

Le lun. 23 nov. 2020 à 21:14, Magnus Bergmark <notifications@github.com> a
écrit :

**Closed** 2021-01-07 09:02 UTC
Labels: bug
