### ISSUE TITLE
[Issue]: [10.8.12] Transcoding problems with Intel GPU and Kernel 4.x (Synology)

### ISSUE THREAD

**Issue by vin86** [jellyfin/jellyfin#10568] opened 2023-11-11 15:48 UTC
I have installed on my Synology DS218+ Jellyfin 10.8.11. I have enabled transcoding e tone mapping; works perfectly without problems. 

I made to latest version 10.8.12. Unfortunately now transconding doens't works! I have wrote on official forum and i receveid this reply:

```
 Support for Linux kernel 4.x was dropped in the newer Intel drivers included in the official jellyfin docker. 4.X is the current version of the Linux kernel Synology uses with their OS. To be clear, this is something Intel did.

Your options are to stay on the official 10.8.11 image or experiment with using unofficial images.

https://docs.linuxserver.io/images/docker-jellyfin/
[https://github.com/linuxserver/docker-mo...encl-intel](https://github.com/linuxserver/docker-mods/tree/jellyfin-opencl-intel)
```
It's not possible develop a Docker Mods that use, in this version and future version, old intel drivers? I think that planning to upgrade Synology Kernel to new version 5.x are very remote in the short term

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: DSM 7.2 Synology
- Linux Kernel:4.x
- Virtualization:NO
- Clients: Browser, Android, Apple
- Browser: Chrome, Firefox
- FFmpeg Version: latest
- Playback Method: Transcode
- Hardware Acceleration: QSV
- GPU Model: Intel 
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-11-11 16:27
Docker mods are something specific to how Linuxserver has their images configured, so no.

**Comment by vin86** [comment] 2023-11-11 16:32
> Docker mods are something specific to how Linuxserver has their images configured, so no.

it's not possible found a workround for resolve this problem? I would like to avoid having installed a program that I will no longer be able to update.

i test also docker images of linuxserver jellyfin but i don't prefer to use vpp tone maping and vaapi

**Comment by sevenrats** [comment] 2023-11-16 15:15
Hi, the solution to your issue is to create a custom image which uses the older drivers.  Closing this support request because it is not a bug, and this is a bug tracker. Please join us on your forums or chat space if you have questions about how to use the software.

**Closed by sevenrats** 2023-11-16 15:15 UTC
Labels: bug
