### ISSUE TITLE
unsual transcoding dir name

### ISSUE THREAD

**Issue by Tricade** [jellyfin/jellyfin#2072] opened 2019-11-28 13:35 UTC
Hi together,

there is a "feature" or "bug" which makes the transcodes dir sometime new. After some days it looks like this path.

/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes

Greetings,
Tricade

**Comment by JustAMan** [comment] 2019-11-28 13:52
Duplicate of https://github.com/jellyfin/jellyfin/issues/1988, fixed by https://github.com/jellyfin/jellyfin/pull/1991 (the fix should be available in next major release - 10.5.0 - when it hits).

**Closed** 2019-11-28 13:52 UTC
Labels: duplicate
