### ISSUE TITLE
AndroidTV Client does not correctly set starting position of media when resuming playback for a second time

### ISSUE THREAD

**Issue by matthewkeogh50** [jellyfin/jellyfin#5896] opened 2021-04-22 22:16 UTC
Using the 0.11.5 android TV client with server version 10.7.2.

I've only noticed this on TV series to far....

To reproduce the issue:

1) Start playing a TV show and let it run for some time, lets say 30 mins.
2) Pause the show
3) logout of the tv client (not sure if this is required but wanted to make sure nothing was cached)
4) restart the playback. The client correctly identifies you left at min 30 and resumes from there. 

However, the progress bar at the bottom changes back to 0 seconds. So lets say you only watch 15 mins now and then pause following the above steps. You get restarted at min 15 when you would of expected min 45.

**Comment by crobibero** [comment] 2021-04-23 01:34
Duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/400

**Closed by crobibero** 2021-04-23 01:34 UTC
