### ISSUE TITLE
[10.7] Web client stopped working after upgrading

### ISSUE THREAD

**Issue by digitalentity** [jellyfin/jellyfin#5485] opened 2021-03-11 12:02 UTC
**Describe the bug**
After the upgrade the web-client stopped working. It loads the grey background and doesn't load the actual application.

Browser developer console is showing this:

```
main.3309837d9db1402ea3a1.bundle.js:2 Stored JSON credentials: {"Servers":[{"DateLastAccessed":1604236121208,"LastConnectionMode":2,"ManualAddress":"http://198.18.5.10:8096","manualAddressOnly":true,"Name":"jellyfin.sharlaimov.com","Id":"71814cf1f3b14903a7785f3d75f234bd","LocalAddress":"http://198.18.5.10:8096","UserId":"055cfca8eb77420985c0c3cc5e5d5dbf","AccessToken":"098646715d0a4396bd0c4b06b6017bae"}]}
main.3309837d9db1402ea3a1.bundle.js:2 Begin ConnectionManager constructor
main.3309837d9db1402ea3a1.bundle.js:2 returning instance from getOrAddApiClient
main.3309837d9db1402ea3a1.bundle.js:2 defining core routes
main.3309837d9db1402ea3a1.bundle.js:2 Begin getAvailableServers
main.3309837d9db1402ea3a1.bundle.js:2 loading installed plugins
main.3309837d9db1402ea3a1.bundle.js:2 epluginsList: []_callbacks: {registered: Array(1)}plugins: (...)__proto__: constructor: ƒ e()loadPlugin: ƒ (e)mapPath: ƒ (e,t,n)ofType: ƒ (e)plugins: (...)get plugins: ƒ ()__proto__: Object
main.3309837d9db1402ea3a1.bundle.js:2 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
```

**System (please complete the following information):**
 - Server OS: Ubuntu 20.04.2 LTS
 - Clients: tested Browser & Android
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.0

**To Reproduce**

**Comment by nielsvanvelzen** [comment] 2021-03-11 12:11
Duplicate of jellyfin/jellyfin-web#2493

**Closed by nielsvanvelzen** 2021-03-11 12:11 UTC
Labels: bug

**Comment by digitalentity** [comment] 2021-03-11 12:16
Thanks. https://github.com/jellyfin/jellyfin-web/issues/2493#issuecomment-793268549 fixed the issue
