### ISSUE TITLE
Is it normal for the memory usage to be this high?

### ISSUE THREAD

**Issue by maxtheking** [jellyfin/jellyfin#3680] opened 2020-07-24 09:11 UTC
I just upgraded my Jellyfin docker container to the latest version, and noticed a large spike in memory usage.
Is this normal? I did read that memory usage could be a bit higher on 10.6.0, but should it be this dramastic?

[Screenshot ](https://i.maxkoning.nl/MobaXterm_lXZMx4Iprk.png)

**Comment by theg00s3** [comment] 2020-07-24 10:37
Yeah mine's been going a bit wild as well. Sometimes it uses over 50% of my ram (I have 8gb) and I have to restart Jellyfin to get it down

**Comment by Bond-009** [comment] 2020-07-24 10:46
Should be fixed in 10.6.1

**Comment by theg00s3** [comment] 2020-07-24 11:32
> Should be fixed in 10.6.1

Do you know when 10.6.1 will come out?

**Comment by ToXinE** [comment] 2020-07-24 23:23
same as you @theg00s3  ![image](https://user-images.githubusercontent.com/6205053/88442591-660d3c80-ce15-11ea-8c77-fb2e4f395baf.png)

**Comment by LittleCannon** [comment] 2020-07-25 01:52
Same here. Debian, installed from repo, in 24 hours it goes over 5GB.
It would be nice to have small hint when could we expect 10.6.1

**Comment by nattycleopatra** [comment] 2020-07-25 07:33
I've been seeing the same issue, with Jellyfin 10.6.0 continuing to eat memory until there's nothing left to chomp on.

After my system barely survived the first time around (I've never seen load averages climbing above 2k(!) before), I used Docker's resource constraints to limit `jellyfin/jellyfin:10.6.0` to 3 GiB of RAM and 2 GiB of swap. While this avoids the whole system being disrupted, Jellyfin unfortunately uses up all of its allocation in less than 24 hours and starts throwing `System.OutOfMemoryException`s until restarted instead of cleaning up after itself.

Will revert back to 10.5.5 for the time being.

**Comment by davehope** [comment] 2020-07-25 07:37
Same here, but not much to add. Memory usage increases until Linux OOM killer kicks in, no issues prior to 10.6.0.

If there's some diagnostic logging we can enable and provide to help identify the cause, please do let me know.

**Comment by EVOTk** [comment] 2020-07-25 08:00
Same problem ! 
DSM 6.2.3-2
Docker 10.6.0 - Fresh install

**Comment by ToXinE** [comment] 2020-07-25 08:04
it is related to #2760 ? Because jellyfin is not usable anymore for more than 24Hours :(

**Comment by owenashurst** [comment] 2020-07-25 10:05
> I've been seeing the same issue, with Jellyfin 10.6.0 continuing to eat memory until there's nothing left to chomp on.
> 
> After my system barely survived the first time around (I've never seen load averages climbing above 2k(!) before), I used Docker's resource constraints to limit `jellyfin/jellyfin:10.6.0` to 3 GiB of RAM and 2 GiB of swap. While this avoids the whole system being disrupted, Jellyfin unfortunately uses up all of its allocation in less than 24 hours and starts throwing `System.OutOfMemoryException`s until restarted instead of cleaning up after itself.
> 
> Will revert back to 10.5.5 for the time being.

I don't think it's as simple as switching versions to downgrade now that they're migrating to EF Core - they said in the release notes that you need to copy multiple files etc but I'm not sure which ones. I could do with downgrading as the android clients are broken with the new release and I'm using docker so I can't do anything until either a fix is released or can safely downgrade.

**Comment by nattycleopatra** [comment] 2020-07-25 17:23
> > Will revert back to 10.5.5 for the time being.
> 
> I don't think it's as simple as switching versions to downgrade now that they're migrating to EF Core - they said in the release notes that you need to copy multiple files etc but I'm not sure which ones. I could do with downgrading as the android clients are broken with the new release and I'm using docker so I can't do anything until either a fix is released or can safely downgrade.

As the release notes made it quite clear you wouldn't be able to go back after running 10.6.0's database migrations in any easy way, I'd done as advised and backed up my config and cache data folders with [restic](https://restic.net/) prior to upgrading. Losing less than a week of library updates wasn't a big issue in my case.

I'm unfortunately not sure how one should go about downgrading without a backup.

**Comment by owenashurst** [comment] 2020-07-25 17:25
> > > Will revert back to 10.5.5 for the time being.
> > 
> > 
> > I don't think it's as simple as switching versions to downgrade now that they're migrating to EF Core - they said in the release notes that you need to copy multiple files etc but I'm not sure which ones. I could do with downgrading as the android clients are broken with the new release and I'm using docker so I can't do anything until either a fix is released or can safely downgrade.
> 
> As the release notes made it quite clear you wouldn't be able to go back after running 10.6.0's database migrations in any easy way

That's precisely my dilemma. I guess I'll just wait until 10.6.1.

**Comment by UltraHKR** [comment] 2020-07-26 19:03
This also happens on win server 2019, jellyfin 10.6.0 x64.

I saw yesterday using 6.6gb of ram.

**Comment by ricardoandren** [comment] 2020-07-27 11:59
Jellyfin keeps filling my swapspace even after sucking all of the memory dry, shouldnt this be an urgent fix thing?

**Comment by thisis-mental** [comment] 2020-07-28 20:24
Hi there,
I'm running v10.6.1 in Linuxserver docker container.
Memory is still getting higher and higher until the maximum allocated to final make the instance not responsive at all.
![image](https://user-images.githubusercontent.com/35723598/88717581-08346980-d121-11ea-927d-c6bbab7e220e.png)
Is there specific logs I can extract to help?

**Comment by jp8311** [comment] 2020-07-30 01:56
Version: 10.6.1

Operating System: Linux

Architecture: X64

Running as a docker image in UNRAID and I'm having the same problem with memory usage. Limited it to 50% of avaliable ram and it's starting to throw errors.

**Comment by n-peugnet** [comment] 2020-07-30 17:58
Same problem. It seems that, for some reason, the GC is not doing his job.

![jellyfin-heap-prometheus](https://user-images.githubusercontent.com/23519418/88956955-72264d80-d29e-11ea-8278-1a326ba35e93.png)

The scan seems to be the most memory intensive task so for now I disabled its scheduled task.

**Comment by sparky8251** [comment] 2020-07-30 18:44
I guess this means the prometheus exporter I implemented is already useful.

So, we know its scans. I guess the problem now is that we have no idea *how*. Going to need to do a bunch of git bisecting probably. Scanning shouldn't be capable of this based on the big changes I know of during the 10.6.z development cycle.

**Comment by sparky8251** [comment] 2020-07-30 20:54
So, question for everyone watching this issue and having abnormally high RAM usage that never seems to stop climbing:

Do you have music libraries?

**Comment by thisis-mental** [comment] 2020-07-30 20:56
Small one but yes.

**Comment by nattycleopatra** [comment] 2020-07-30 20:59
I don't have a music library on my instance. I do use a "Photos" one for videos without any metadata available, though.

**Comment by ricardoandren** [comment] 2020-07-30 21:00
I have no Music library and memory leaks still bad.

**Comment by LittleCannon** [comment] 2020-07-30 21:46
Since this is obviously related with syncing, my money is that this issue is related to database migration.
Soon as I start sync with kodi device (have 5 of them in house), RAM usage sky rockets.

**Comment by sparky8251** [comment] 2020-07-30 21:47
Considering the only things that are migrated into EF Core are users and their permissions + the activity events no one even knows about, no. Its not the database.

**Comment by crobibero** [comment] 2020-07-30 21:56
> 
> 
> Since this is obviously related with syncing, my money is that this issue is related to database migration.
> Soon as I start sync with kodi device (have 5 of them in house), RAM usage sky rockets.

What library types do you have?

**Comment by n-peugnet** [comment] 2020-07-30 22:04
We have all kinds of libraries with around 1.5K movies 3.5K albums and a few series.

**Comment by LittleCannon** [comment] 2020-07-30 22:09
> > Since this is obviously related with syncing, my money is that this issue is related to database migration.
> > Soon as I start sync with kodi device (have 5 of them in house), RAM usage sky rockets.
> 
> What library types do you have?

Movies (~400), TV Shows (~90), Music (~40 albums)

**Comment by theg00s3** [comment] 2020-07-30 23:39
> Do you have music libraries?

Yeah I do

**Closed** 2020-07-31 13:23 UTC

**Comment by LittleCannon** [comment] 2020-07-31 16:50
Just to confirm.
With latest  jellyfin-server_20200731.2-unstable no more memory leak.
For now everything works perfectly.

**Comment by theg00s3** [comment] 2020-07-31 19:45
Looks like I have something to look forward to in 10.6.2

**Comment by ThaFacialHair** [comment] 2022-03-20 21:46
Can confirm issue is not fixed, im running the newest version from the PPA on ubuntu server 20.04 im still seeing around 7gb of RAM usage when local streaming a movie. I have CUDA enabled and do have swap setup 
![jellyfinramleak](https://user-images.githubusercontent.com/41532673/159187285-f043a4d0-db06-4111-8b07-9f4288b49517.PNG)

**Comment by theg00s3** [comment] 2022-03-23 03:38
that's unrelated. this issue was regarding high ram usage when the server wasn't being used for streaming

**Comment by fromage9747** [comment] 2023-03-03 16:56
2023 and this is happening.  I will restart the docker container.  It will clear and shoot back up within 15 minutes.  Nothing is being watched.  Just idle.

**Comment by cvium** [comment] 2023-04-10 17:48
All information is required. It's not something we can reproduce. Anyone is who affected by it must do some digging on their own.

**Comment by joshuaboniface** [comment] 2023-04-10 18:34
To add on to @cvium's point:

There were definitely memory improvements in 10.7.z and 10.8.z that should avoid the whole 4+GB memory issue.

Currently, my instance is steady-state at about 2GB of RAM, with a data dir of about 1.3GB:

```
$ ps aux | grep '[U]SER\|[j]ellyfin'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
jellyfin     480  3.3 12.3 5393100 2023888 ?     Ssl  Apr01 442:04 /usr/bin/jellyfin --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg
$ sudo du -hs /srv/jellyfin/{cache,data}
368M    /srv/jellyfin/cache
980M    /srv/jellyfin/data
```

This seems perfectly reasonable to me. If this is similar to what you're seeing, then it might be an issue of expectations, not a bug. If it's far higher though, then it is a bug and needs to be reported.

So, at the very least, we'd need this sort of information: exactly how big is the data being loaded into RAM (library databases, etc.), how much RAM is it actually using, exactly what version, etc.

Given that this is a closed issue, I would suggest that anyone currently experiencing trouble collect this information into a *new* issue targeting the current version of Jellyfin (10.8.9).
