### ISSUE TITLE
Wrong content sorting in the Cyrillic alphabet

### ISSUE THREAD

**Issue by doskochdima** [jellyfin/jellyfin#12437] opened 2024-08-13 09:15 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Wrong content sorting in the Cyrillic alphabet after released version 10.9.0. You used transliteration for the Cyrillic, but it's different from the Cyrillic alphabet.

### Reproduction steps

1. Add a new file
2. Refresh metadata

### What is the current _bug_ behavior?

Sorting content in the wrong order (using transliteration)

### What is the expected _correct_ behavior?

Sorting content in the right order (using Cyrillic alphabet order)

### Jellyfin Server version

10.9.9+

### Specify commit id

c16135800c53873746321d0c9ea2fc36550511c1

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Android 14, IOS 17, Windows 11
- Linux Kernel: Linux 6.1.0-0.deb11.21-amd64
- Virtualization: Docker
- Clients: Browser, Android, IOS
- Browser: Chrome 127.0.6533.100
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No need
```

**Comment by felix920506** [comment] 2024-08-13 15:37
Duplicate of #11880

**Closed** 2024-08-13 15:37 UTC
Labels: bug
