### ISSUE TITLE
[Issue]: Jellyfin stumbles over track artist "∆®¥ \/\/∆®|\|∆∆®"

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin#10669] opened 2023-12-03 17:37 UTC
### Please describe your bug

One of my properly tagged (MusicBrainz Picard) albums has an artist name ([∆®¥ \/\/∆®|\|∆∆®](https://musicbrainz.org/recording/2b61ad4b-5af4-4b52-a1bd-efb547badab0)) that Jellyfin does not like at all.
It shows up as multiple fragments and variations.  

I'm pretty sure it's trying to split it on one of the many `/` or `\` 's

I also tried just removing it in the metadata editor in jellyfin and rescanning but the wrong artist entries remain.

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Linux Kernel: 6.2.0-37-generic (HWE)
- Virtualization: Bhyve
- Clients: Browser
- Browser: Firefox 121.0b6
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: Subtitle Extraction, Playback Reporting, Reports, Trakt
- Reverse Proxy: apache
- Base URL: /jellyfin
- Networking: virtio-net
- Storage: local
```

### Jellyfin logs

```shell
Nothing in the logs with regard to tag parsing.
```

### FFmpeg logs

```shell
n/a
```

### Please attach any browser or client logs here

n/a

### Please attach any screenshots here

<img width="540" alt="image" src="https://github.com/jellyfin/jellyfin/assets/379665/a6f91c25-4404-44ad-8fab-cd8c359b3a6d">
<img width="878" alt="image" src="https://github.com/jellyfin/jellyfin/assets/379665/ea0387a2-129c-445d-8368-29f667ff9d5d">

And under the artist tab:
<img width="618" alt="image" src="https://github.com/jellyfin/jellyfin/assets/379665/fc409da2-bb26-49c5-93da-a938c1d2d7ba">

Also interesting is that a few other variants show up in `/var/lib/jellyfin/metadata/artists` that do not show in the web ui, they some of these do show up in apps like fintunes.
```
root@artemis:/var/lib/jellyfin/metadata/artists# ls -l | head -n 9
total 443
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 18:20 \
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 18:19 |
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 16:55 ∆®
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 16:55 ∆∆®
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 18:23 ∆∆®"
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 18:23 "∆®¥ \ \ ∆®
drwxr-xr-x 2 jellyfin jellyfin 3 Dec  3 16:55 ∆®¥ \
drwxr-xr-x 2 jellyfin jellyfin 6 Dec  3 15:02 2 Brothers on the 4th Floor
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment] 2023-12-08 22:51
duplicate of #1756

**Closed by sevenrats** 2023-12-08 22:51 UTC
Labels: bug

**Comment by sjorge** [comment] 2023-12-08 23:26
Removing them from the tags doesn’t fix it, it seems to fetch the same info from MusicBrain.

Only way to have it ‘fixed’ is to delete the file.

**Comment by 1337joe** [comment] 2023-12-09 05:47
Typically this problem would be resolved in the scanner by adding the artist to the list [here](https://github.com/jellyfin/jellyfin/blob/0d5bbfda321f64ad78b5b74e7bdfbbbb8b64c7af/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L50) in `ProbeResultNormalizer`.

In the case of this artist this approach fails, and after a little debugging it looks like anything after the `|` is getting dropped by ffprobe before it even gets to Jellyfin. I've never seen another artist that uses `|`, nor do I see an obvious path for working around this.

**Comment by sjorge** [comment] 2023-12-09 10:48
Just for future people that find this issues, I manged to get it working but only with a **clean** library.
- remove existing library
- stop jellyfin
- nuke /var/lib/jellyfin/metadata/artists (it has the weird entries and it seems jellyfin can't delete them for some reason)
- start jellyfin
- `id3convert -s <filehere>`
- point `MusicBrainz Picard` at the album (it only showed that one track without the ✅ )
- **DO NOT SAVE** without first fixing the artist value, I set it to `Various Artists`
- save the changes
- add a new music library to jellyfin

I'm guessing somehow `MusicBrainz Picard`  was not *overriding* one of the tags, perhaps a v1 vs v2 tag issue.
Also once jellyfin sees the bad artist it seems to somehow trip up the library db, it also makes it impossible for jellyfin to remove the dir in the artists metadata. I logs that it does, no error but the dir always stays.

This was not a fun adventure.
