### ISSUE TITLE
Items API returns a type of "Video" for movies in a collection

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin#2826] opened 2020-04-10 21:27 UTC
**Describe the bug**

When calling the Items API (`/Users/<user_id>/Items` or `/Items`), the API returns the wrong type for the items.

Movies get the type "Video", which causes them to lose all metadata information in the web client (Posters, titles, etc).

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.3
 - Playback: n/a
 - Installed Plugins: None
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: n/a
 - Storage: cloud

**To Reproduce**

* Select multiple items
* Add them to a collection.
* Query the API to get the collection's children

**Expected behavior**

The API should return the proper information for the items as if they were part of a library, to allow the proper display of metadata on clients.

**Logs**

Here is a sample of the return from an API call:

```json
{
  "Items": [
    {
      "Name": "Zatôichi.kenka-tabi.1963.1080p.BluRay.FLAC.1.0.x264-EbP",
      "ServerId": "3f04000cbe6b4e038030c47157f213d6",
      "Id": "0f82f57000b689cb23b36d2a0d67a71d",
      "CanDelete": true,
      "HasSubtitles": true,
      "Container": "mkv,webm",
      "RunTimeTicks": 52696850432,
      "IsFolder": false,
      "Type": "Video",
      "UserData": {
        "PlaybackPositionTicks": 0,
        "PlayCount": 0,
        "IsFavorite": false,
        "Played": false,
        "Key": "0f82f570-00b6-89cb-23b3-6d2a0d67a71d"
      },
      "PrimaryImageAspectRatio": 2,
      "VideoType": "VideoFile",
      "ImageTags": {
        "Primary": "6ee34af68964ab6ca12e2ecfc9f11795"
      },
      "BackdropImageTags": [],
      "LocationType": "FileSystem",
      "MediaType": "Video"
    },
    {
      "Name": "Zatoichi.monogatari.1962.1080p.BluRay.FLAC.1.0.x264-EbP",
      "ServerId": "3f04000cbe6b4e038030c47157f213d6",
      "Id": "12be8dd080b63e0f41e0138bebcb0dc1",
      "CanDelete": true,
      "HasSubtitles": true,
      "Container": "mkv,webm",
      "RunTimeTicks": 57804001280,
      "IsFolder": false,
      "Type": "Video",
      "UserData": {
        "PlaybackPositionTicks": 0,
        "PlayCount": 0,
        "IsFavorite": false,
        "Played": false,
        "Key": "12be8dd0-80b6-3e0f-41e0-138bebcb0dc1"
      },
      "PrimaryImageAspectRatio": 2,
      "VideoType": "VideoFile",
      "ImageTags": {
        "Primary": "1b04ae30fae2f221cfc983c09a5ad5fd"
      },
      "BackdropImageTags": [],
      "LocationType": "FileSystem",
      "MediaType": "Video"
    },
    {
      "Name": "Zoku.Zatôichi.monogatari.1962.1080p.BluRay.FLAC.1.0.x264-EbP",
      "ServerId": "3f04000cbe6b4e038030c47157f213d6",
      "Id": "d47f228f2f4b2f6a37ea62f86ead7807",
      "CanDelete": true,
      "HasSubtitles": true,
      "Container": "mkv,webm",
      "RunTimeTicks": 43509751808,
      "IsFolder": false,
      "Type": "Video",
      "UserData": {
        "PlaybackPositionTicks": 0,
        "PlayCount": 0,
        "IsFavorite": false,
        "Played": false,
        "Key": "d47f228f-2f4b-2f6a-37ea-62f86ead7807"
      },
      "PrimaryImageAspectRatio": 2,
      "VideoType": "VideoFile",
      "ImageTags": {
        "Primary": "d935e74b296ca4ca1db2f13e648fd015"
      },
      "BackdropImageTags": [],
      "LocationType": "FileSystem",
      "MediaType": "Video"
    }
  ],
  "TotalRecordCount": 3,
  "StartIndex": 0
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/19396809/79024286-c936d400-7b82-11ea-8380-7ed051d3cbd4.png)

**Additional context**

Seems like some items are affected while some are not. Not sure of a proper way to replicate yet.

**Comment by Artiume** [comment] 2020-04-10 21:32
Duplicate of https://github.com/jellyfin/jellyfin/issues/2565

**Closed** 2020-05-15 21:01 UTC
Labels: bug
