### ISSUE TITLE
Media Randomly Stops During Playback Since Upgrade to 10.8.0

### ISSUE THREAD

**Issue by klaury** [jellyfin/jellyfin#7996] opened 2022-06-23 01:52 UTC
**Media Info of the file**

Done
**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Windows 11
 - Jellyfin Version: 10.8.1
 - Hardware settings & device: NVENC on GTX1650 5GBDDR
 - Reverse proxy:  no
 - Other hardware notes: Media on local Drive
[FFmpeg.Transcode-2022-06-22_17-09-11_3baef416a31c722254f6af0c5543ba25_378d65f5.log](https://github.com/jellyfin/jellyfin/files/8962915/FFmpeg.Transcode-2022-06-22_17-09-11_3baef416a31c722254f6af0c5543ba25_378d65f5.log)
[FFmpeg.Transcode-2022-06-22_17-09-15_3baef416a31c722254f6af0c5543ba25_28cedd5f.log](https://github.com/jellyfin/jellyfin/files/8962916/FFmpeg.Transcode-2022-06-22_17-09-15_3baef416a31c722254f6af0c5543ba25_28cedd5f.log)
[FFmpeg.Transcode-2022-06-22_17-09-16_3baef416a31c722254f6af0c5543ba25_e5a34d08.log](https://github.com/jellyfin/jellyfin/files/8962917/FFmpeg.Transcode-2022-06-22_17-09-16_3baef416a31c722254f6af0c5543ba25_e5a34d08.log)
[PValleyinfo.txt](https://github.com/jellyfin/jellyfin/files/8962957/PValleyinfo.txt)

 
**Client System (please complete the following information):**
 - Device: HTPC
 - OS: Windows
 - Client: Web/Browser
 - Browser: Chrome
 - Client and Browser Version 103.0.5060.53 (Official Build) (64-bit)

**Comment by cvium** [comment] 2022-06-23 05:41
Duplicate of https://github.com/jellyfin/jellyfin/issues/6957

**Closed by cvium** 2022-06-23 05:41 UTC
