### ISSUE TITLE
Media gets transcoded in Edge, even if it can handle the file.

### ISSUE THREAD

**Issue by DerP4si** [jellyfin/jellyfin#10474] opened 2023-10-26 09:51 UTC
**Media Info of the file**

Video
Titel: 4K HEVC HDR
Codec: HEVC
Profil: Main 10
Level: 150
Auflösung: 3840x1600
Seitenverhältnis: 2.40:1
Zeilensprungverfahren: No
Bildrate: 23.976025
Bitrate: 23398 kbps
Bit-Tiefe: 10 bit
Videobereich: HDR
Video range type: HDR10
Farbraum: bt2020nc
Farbübertragung: smpte2084
Primärfarben: bt2020
Pixelformat: yuv420p10le
Referenz-Frames: 1

Audio
Titel: German - Dolby Digital+ - 5.1 - Default
Sprache: ger
Codec: EAC3
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 640 kbps
Abtastrate: 48000 Hz
Standard: Yes
Erzwungen: No
Extern: No

Audio
Titel: English - Dolby Digital+ - 5.1
Sprache: eng
Codec: EAC3
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 768 kbps
Abtastrate: 48000 Hz
Standard: No
Erzwungen: No
Extern: No

**Stats for Nerds Screenshots**
![image](https://github.com/jellyfin/jellyfin/assets/28807283/bfbd055f-a3a7-4367-92de-80ee92b98839)

compared to Plex:

![image](https://github.com/jellyfin/jellyfin/assets/28807283/b97381e0-143b-4d56-91d5-f747099f6b57)

So the client is capable of playing HEVC Main 10bit but Jellyfin transcodes the full file.

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.11
 - Hardware settings & device:VAAPI on 5900HX (Vega 8 w. 3GB VRAM)
 - Reverse proxy: traefik
 - Other hardware notes: Media mounted in CIFS/SMB share
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Client: Web Client, Browser
 - Browser (if Web client): Microsoft Edge
 - Client and Browser Version: Version 118.0.2088.69

**Comment by felix920506** [comment] 2023-10-26 20:31
Duplicate of [jellyfin-web/#4899](https://github.com/jellyfin/jellyfin-web/issues/4899)

**Closed by felix920506** 2023-10-26 20:31 UTC
