### ISSUE TITLE
Playlist library bug

### ISSUE THREAD

**Issue by SegiH** [jellyfin/jellyfin#1413] opened 2019-05-27 23:39 UTC
Im using JF 10.3.3 on Windows 64 bit.

I think since around 10.3.0, I no longer have playlists listed under Library Order in Settings->Home Screen.

I now have to click on music and make playlists the default.

Theres also a playlist bug where in the user settings under the access tab if you don't have "Enable access to all libraries" checked, when you go to playlists, none of the playlists show up. All of my playlists are music based playlists and it never used to do this before 10.3.0

**Comment by sparky8251** [comment] 2019-06-25 19:13
Duplicate of #1347 and potentially #1436. Fixes appear to be incoming based on #1394 and #1437.

Closing.

**Closed by sparky8251** 2019-06-25 19:13 UTC
Labels: bug
