### ISSUE TITLE
Chinese library names are displayed as square

### ISSUE THREAD

**Issue by bingzhangdai** [jellyfin/jellyfin#5636] opened 2021-03-27 06:53 UTC
**Describe the bug**
Chinese library names are not showing properly.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Microsoft Edge Version 89.0.774.57 (Official build) (64-bit)
 - Jellyfin Version: 10.7.1

**Screenshots**

![image](https://user-images.githubusercontent.com/9895061/112712729-11721200-8f0c-11eb-81da-a976a74e4a82.png)

**Comment by nyanmisaka** [comment] 2021-03-27 07:38
https://github.com/jellyfin/jellyfin/pull/4863

https://github.com/jellyfin/jellyfin/issues/5008#issuecomment-758848489

Please pass the font folder into the container or install CJK fonts inside the container.

**Comment by bingzhangdai** [comment] 2021-03-27 07:56
I have installed the fonts.
![image](https://user-images.githubusercontent.com/9895061/112714232-4aae8000-8f14-11eb-9de0-7715a4ba6916.png)
![image](https://user-images.githubusercontent.com/9895061/112714248-66b22180-8f14-11eb-8805-b25b24a52e86.png)

I guess this happens because the server side handles the fonts rendering, but it generates the image before I could add the fonts. I use watchtower to auto upgrade the docker image. So, it is very likely that the server already generated the image before I config the fallback fonts. 

I also agree with you that "We should let frontend handle the fonts rendering." in https://github.com/jellyfin/jellyfin/issues/5008#issuecomment-758848489, but for now, how could I refresh the image?

**Comment by shuosiw** [comment] 2021-04-05 15:52
same problem.

i have mount the cjk fonts dir into jellyfin docker, and setting in the console of jellyfin. but i does not work..

**Comment by std4453** [comment] 2021-04-07 09:57
> I have installed the fonts.
> ![image](https://user-images.githubusercontent.com/9895061/112714232-4aae8000-8f14-11eb-9de0-7715a4ba6916.png)
> ![image](https://user-images.githubusercontent.com/9895061/112714248-66b22180-8f14-11eb-8805-b25b24a52e86.png)
> 
> I guess this happens because the server side handles the fonts rendering, but it generates the image before I could add the fonts. I use watchtower to auto upgrade the docker image. So, it is very likely that the server already generated the image before I config the fallback fonts.
> 
> I also agree with you that "We should let frontend handle the fonts rendering." in [#5008 (comment)](https://github.com/jellyfin/jellyfin/issues/5008#issuecomment-758848489), but for now, how could I refresh the image?
> 
> The server-side rendering can reduce the data transferred. It is an acceptable tradeoff, but the server can regenerate the image everyday if it finds the fonts or library change.

This fallback font setting is in the 'Playing' section, server-side rendering uses fontconfig to resolve fonts.

If you're running a jellyfin docker container on a linux machine, you can install CJK fonts (e.g. Noto Sans CJK), and mount your fontconfig directory `/usr/share/fontconfig` and fonts directory `/usr/share/fonts` to the same location in the jellyfin container.

With `docker-compose`, it's like:

```yaml
jellyfin:
    volumes:
      - /usr/share/fonts:/usr/share/fonts
      - /usr/share/fontconfig:/usr/share/fontconfig
```

In addition, you might need to delete existing library cover files, located at `config/metadata/library`, then refresh libraries to force a refresh. Depending on your situation, you might need to restart your jellyfin server after deleting.

For me, it works like a charm:

![image](https://user-images.githubusercontent.com/13191718/113848114-bae9bb00-97ca-11eb-8fc8-2943a076dcc1.png)

**Comment by bingzhangdai** [comment] 2021-04-07 12:15
@std4453 Could you tell me where is the "playing" section? I set the fallback fonts in the "playback" section. How do you install the CJK fonts? I just download the fonts from the Internet and mounting the two paths in your guide does not work.

Besides, I think, in common sense, by setting the fallback font folder, there should be no need for me to do that lots of manual work.

**Comment by std4453** [comment] 2021-04-07 12:21
> @std4453 Could you tell me where is the "playing" section? I set the fallback fonts in the "playback" section. How do you install the CJK fonts? I just download the fonts from the Internet and mounting the two paths in your guide does not work.
> 
> Besides, I think, in common sense, by setting the fallback font folder, there should be no need for me to do that lots of manual work.

Sorry, I mean playback, using Chinese translation so not very sure what that in English version is.

I don't think that's common sense since modularization is important and this setting should only impact the ASS rendering module. For server-side image rendering - although one might argue whether we do need it - providing a separate setting would be preferable.

My previous comment is only suggesting a way to fix your current problem by putting fonts to the correct location, I'm not a jellyfin collaborator and can't help modifying the code.

**Comment by std4453** [comment] 2021-04-07 12:24
@bingzhangdai BTW I think your issue is truely a duplicate of #5008 and should have already been fixed by #4863 already.

**Comment by bingzhangdai** [comment] 2021-04-07 12:35
@std4453 I still think Jellyfin should properly handle the fallback fonts, because I have already set it in the Playback section. There should be no need to add a separate setting for server-side image rendering. Jellyfin server knows where to find the fallback fonts. This is why this pr https://github.com/jellyfin/jellyfin/pull/4863 exits, but I guess this issue still exists in the docker installation method.

Mounting is an acceptable workaround. Thanks for your solution anyway. Let's wait for Jellyfin members comments.

**Comment by cvium** [comment] 2021-04-09 21:43
Duplicate of #5008

**Closed by cvium** 2021-04-09 21:43 UTC
Labels: bug

**Comment by tomcatmew** [comment] 2024-09-23 13:14
https://github.com/jellyfin/jellyfin/issues/5636#issuecomment-814781468

This is the perfect solution so far for solving the Chinese font issue. 
Highly suggest adding documentation about font configuration on the Jellyfin home page, that's would be super helpful for new comer Jellyfin users.

**Comment by p0358** [comment] 2024-10-22 09:22
> Highly suggest adding documentation about font configuration on the Jellyfin home page, that's would be super helpful for new comer Jellyfin users.

For future record, the PR jellyfin/jellyfin.org#1129 was originally created for it, but we agreed to replace it with jellyfin/jellyfin.org#1136 that is now WIP.

I now see where the original came from, since in this case the standard Noto CJK font was in the apt repos on the host and the paths for fontconfig were all compatible. The replacement is an instruction of mounting a directory of font files instead.
