### ISSUE TITLE
Download all titles for multi-episodes

### ISSUE THREAD

**Issue by northorsouth** [jellyfin/jellyfin#2980] opened 2020-04-25 15:42 UTC
I have several TV series that contain multiple episodes per file, usually 2, sometimes more. The naming convention I'm using for the files is "SXXEXX-EXX Title 1 ~ Title 2" which seems to work for TVDB scraping. But in jellyfin, the metadata is only downloaded for the first episode. I'd like to be able to see the title/description for each episode in the file. At the very least, download just the description/rating/thumbnail for the first episode, but show the titles of all episodes in the file. That way I can search my library for any episode in the series.

**Comment by PhasecoreX** [comment] 2020-08-31 21:15
This is still broken in the latest release. The episode list only shows an entry for the first episode in multi-episode videos.

**Comment by PhasecoreX** [comment] 2020-12-31 12:20
Nope, still broken in the latest release.

**Comment by tamburra** [comment] 2021-01-01 19:23
I really wish there was a method to get this to work.  I am currently manually changing all titles and descriptions on multi episodes just to get both titles and descriptions.

**Comment by viggy96** [comment] 2021-04-14 19:46
This is still a problem in 10.7.2.

**Comment by PhasecoreX** [comment] 2021-08-21 04:21
Just checked with the latest release, it still doesn't list all titles of multi episode files.

**Comment by cirilloblu** [comment] 2022-04-20 20:20
In a multi episode file, the second episode is tagged "missing":
![image](https://user-images.githubusercontent.com/1334771/164315245-c2d3fd36-d091-4359-bd2e-c96efa625bdd.png)

(When scrap this, only the first of the two episodes is set as "watched".)

**Comment by infinitepi** [comment] 2022-06-27 01:10
i am also having this problem.  episodes are names properly, i.e. s02e01-02, but only shows metadata for the first episode.
when viewing the list of episodes there is no indication that they are multi-episode files, so the list makes it look like there are missing episodes

**Comment by Gandalf-the-Blue** [comment] 2023-04-11 11:23
This is an issue for me too. I have a lot of series, especially cartoons/animated shows where each file is actually multiple episodes. Jellyfin does pick up that they are multiple episodes in the file properly and this can be seen in the .nfo files with episode and episodenumberend and there is title, but it only picks up for the first episode and not the others.
I really don't want to manually update the NFOs, that's going to be a whole lotta work

**Comment by haydenstith** [comment] 2023-04-24 04:12
Having been frustrated by this issue myself, I decided to dig around in the source code and I found out the issue has nothing to do with Jellyfin, the issue is with the plugins for the metadata providers. I actually fixed the one for the TVDB, pending a pull request. If you’re interested it’s here: https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/86

I will look into fixing the built in metadata providers if my pull request gets approved.

**Comment by haydenstith** [comment] 2023-06-19 13:04
My PR was just merged into the TVDB plugin and is set to be released with v10 of the plugin jellyfin/jellyfin-plugin-tvdb#89

**Comment by CarterMoody** [comment] 2023-06-19 23:14
@haydenstith Thanks for the PR... exactly what I'm looking for. How do I use this? Readme of the TVDB repo is useless. I did some searching but found nothing on setup after install. I see TVDB in my plugins on Jellyfin developer dashboard, but cannot add TVDB as a metadata provider. Also, does this require an API key? Thanks

**Comment by haydenstith** [comment] 2023-06-19 23:19
@CarterMoody If you have v10 installed it should work out of the box. You will need to restart your sever to get TVDB to show up as a metadata provider.

**Comment by CarterMoody** [comment] 2023-06-19 23:35
Not sure what I could be doing wrong here, but does show up in plugins manager, yet no change to available metadata providers.
![image](https://github.com/jellyfin/jellyfin/assets/45612260/e0106e80-a7f9-4f8e-b51f-9cda0396e760)
![image](https://github.com/jellyfin/jellyfin/assets/45612260/e1f5d456-d46c-454e-8146-1cdd24f42d1c)

**Comment by haydenstith** [comment] 2023-06-19 23:38
Did you install it from GitHub or the Repo? It should be on the public repo now. Install from the repo, restart your server, then try again.

**Comment by CarterMoody** [comment] 2023-06-19 23:50
Thanks for the help. I installed from the GitHub because it does not show up yet on the stable repo. Is this the one you are referring to? https://repo.jellyfin.org/releases/plugin/manifest-stable.json

That one seems to only fetch up to version 9

**Comment by haydenstith** [comment] 2023-06-19 23:53
Weird, mine auto updated to 10 when mine was on v9 (modified). I would say give it a try but I’m not sure why it’s stuck on 9 for you.

**Comment by CarterMoody** [comment] 2023-06-19 23:53
Interestingly when I check that .json in browser. it shows version 10. However when I go to install from Jellyfin plugin catalog, I only see up to version 9 
![image](https://github.com/jellyfin/jellyfin/assets/45612260/17df0330-c17a-4db8-9963-02a314b40ebc)

**Comment by haydenstith** [comment] 2023-06-19 23:57
![C2FCB89F-32ED-491D-BE6E-7E68FADA800E](https://github.com/jellyfin/jellyfin/assets/21245275/3e13110e-66f3-44c4-819e-50a9c4b77cf0)

That is really weird. Maybe yours is cached somewhere. Not sure how to clear it.

**Comment by CarterMoody** [comment] 2023-06-20 00:00
Oh well, I'll give it 24 hours and see what happens. Thanks again.

**Comment by matthewpritchett** [comment] 2023-06-25 16:41
Thank you for the fix for the titles!! Has been basically my biggest issue since using Jellyfin. Any thoughts on the future doing similar with the episodes plots?

**Comment by haydenstith** [comment] 2023-06-25 22:46
@matthewpritchett it actually already does that. It combines the titles and the summary with slashes separating them.

**Comment by matthewpritchett** [comment] 2023-06-25 22:49
@haydenstith Thank you! No idea how I didn’t notice that.

**Comment by srcrist** [comment] 2023-10-07 13:10
This issue is closed by https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/86.

**Closed by srcrist** 2023-10-07 13:10 UTC

**Comment by kjemmett** [comment] 2024-05-14 17:57
Working well in jellyfin v10.9 with TVDB plugin v11. Fails to scrape metadata in cases where the second episode in the file precedes the first in the episode ordering for scraping. As a quick check, non-successive episodes do work when the second episode is greater than the first. For example:

- Series - S01E01E02.mkv scrapes metadata correctly for successive episodes (most common scenario)
- Series - S01E01E03.mkv scrapes metadata correctly for non-successive episodes
- Series - S01E02E01.mkv fails to scrape any metadata for the file

This is an edge case but occurs often for children's shows with many episodes per season (~50+) and where episode ordering can vary between sources and databases based on air dates, production codes, physical media and streaming releases.

**Comment by fdf999** [comment] 2024-10-09 03:34
> Working well in jellyfin v10.9 with TVDB plugin v11. Fails to scrape metadata in cases where the second episode in the file precedes the first in the episode ordering for scraping. As a quick check, non-successive episodes do work when the second episode is greater than the first. For example:
> 
>     * Series - S01E01E02.mkv scrapes metadata correctly for successive episodes (most common scenario)
> 
>     * Series - S01E01E03.mkv scrapes metadata correctly for non-successive episodes
> 
>     * Series - S01E02E01.mkv fails to scrape any metadata for the file
> 
> 
> This is an edge case but occurs often for children's shows with many episodes per season (~50+) and where episode ordering can vary between sources and databases based on air dates, production codes, physical media and streaming releases.

Adding on to this, my case is even more edge case in that I have episodes from multiple different seasons and all type of episode ordering, all in the same file.
