### ISSUE TITLE
[Bug] Issue when re-import the same folder but with different metada laguange.

### ISSUE THREAD

**Issue by CyberPoison** [jellyfin/jellyfin#2463] opened 2020-02-25 10:43 UTC
Hi everyone, I noticed a bug when I import the same folder on my library twice time with different languages metadata this is one example how to reproduce it. 

**System (please complete the following information):**
 - Virtualization: K8S (but it's also works in Docker or any OS)
 - Clients: Every clients
 
**To Reproduce**
Mount the folder on a new library like this. 
E.g:. /mnt/tcrypt/movies
And select metada language, exemple:.
Portuguese. 

:. When is done recreate the same steps but with metadata language in English. .:

The library with metada in English should appear in Portuguese if you have the same folder as /mnt/tcrypt/movies

This is also a bug on emby but since emby have many restrictions, I prefer to report it here on jellyfin. 

**Expected behavior**
Different languages on every library instead of the the same if the same folder is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/60718477/75240524-c47db280-57c4-11ea-8b05-ad1a1cefe4b8.png)

![image](https://user-images.githubusercontent.com/60718477/75240710-1292b600-57c5-11ea-8ffe-476ba2edc2b1.png)

Kind Regards,
Anyone fell free to fix this bug.

**Comment by JustAMan** [comment] 2020-03-02 10:04
Duplicate of https://github.com/jellyfin/jellyfin/issues/1481

**Closed** 2020-03-02 10:04 UTC
Labels: bug, duplicate
