### ISSUE TITLE
In Synology, the Jellyfin service cannot be started.

### ISSUE THREAD

**Issue by daizhichao** [jellyfin/jellyfin#12920] opened 2024-10-31 07:50 UTC
### This issue respects the following points:

- [ ] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

In Synology, the Jellyfin service cannot be started.

### Reproduction steps

In Synology, the Jellyfin service cannot be started.

### What is the current _bug_ behavior?

In Synology, the Jellyfin service cannot be started.

### What is the expected _correct_ behavior?

.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10

### Environment

```markdown
- OS: DSM 7.2.2-72806
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:Bangumi、MetaShark、Open Subtitles
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Thu Oct 31 15:27:10 CST 2024
Starting Jellyfin command /var/packages/Jellyfin/target/service/bin/jellyfin --package-name=synology --datadir=/var/packages/Jellyfin/target/data --configdir=/var/packages/Jellyfin/target/config --webdir=/var/packages/Jellyfin/target/service/web --logdir=/var/packages/Jellyfin/target/logs --cachedir=/var/packages/Jellyfin/target/cache --ffmpeg=/var/packages/Jellyfin/target/bin/ffmpeg
[15:27:10] [INF] [1] Main: Jellyfin version: 10.10.0
[15:27:10] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /var/packages/Jellyfin/target/logs]"]
[15:27:10] [INF] [1] Main: Arguments: ["/volume1/@appstore/Jellyfin/service/bin/jellyfin.dll", "--package-name=synology", "--datadir=/var/packages/Jellyfin/target/data", "--configdir=/var/packages/Jellyfin/target/config", "--webdir=/var/packages/Jellyfin/target/service/web", "--logdir=/var/packages/Jellyfin/target/logs", "--cachedir=/var/packages/Jellyfin/target/cache", "--ffmpeg=/var/packages/Jellyfin/target/bin/ffmpeg"]
[15:27:10] [INF] [1] Main: Operating system: Linux 4.4.302+ #72806 SMP Thu Sep 5 13:44:44 CST 2024
[15:27:10] [INF] [1] Main: Architecture: X64
[15:27:10] [INF] [1] Main: 64-Bit Process: True
[15:27:10] [INF] [1] Main: User Interactive: True
[15:27:10] [INF] [1] Main: Processor count: 4
[15:27:10] [INF] [1] Main: Program data path: /var/packages/Jellyfin/target/data
[15:27:10] [INF] [1] Main: Log directory path: /var/packages/Jellyfin/target/logs
[15:27:10] [INF] [1] Main: Config directory path: /var/packages/Jellyfin/target/config
[15:27:10] [INF] [1] Main: Cache path: /var/packages/Jellyfin/target/cache
[15:27:10] [INF] [1] Main: Temp directory path: /tmp/jellyfin
[15:27:10] [INF] [1] Main: Web resources path: /var/packages/Jellyfin/target/service/web
[15:27:10] [INF] [1] Main: Application directory: /volume1/@appstore/Jellyfin/service/bin/
[15:27:10] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /var/packages/Jellyfin/target/cache
[15:27:11] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[15:27:11] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from /var/packages/Jellyfin/target/data/plugins/back_Bangumi_1.6.2.0/AnitomySharp.dll
[15:27:11] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null from /var/packages/Jellyfin/target/data/plugins/back_Bangumi_1.6.2.0/Fastenshtein.dll
[15:27:11] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /var/packages/Jellyfin/target/data/plugins/back_Bangumi_1.6.2.0/Jellyfin.Plugin.Bangumi.dll
[15:27:11] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.MetaShark, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null from /var/packages/Jellyfin/target/data/plugins/MetaShark_2.1.0.0/Jellyfin.Plugin.MetaShark.dll
[15:27:11] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null from /var/packages/Jellyfin/target/data/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[15:27:11] [ERR] [1] Jellyfin.Networking.Manager.NetworkManager: Unable to parse bind override: /jellyfin
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.1.195", "::1", "240e:3b4:38e5:b6d0:9209:d0ff:fe6a:cb76", "fe80::9209:d0ff:fe6a:cb76%3"]
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[15:27:11] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bangumi 1.6.2.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MetaShark 2.1.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Open Subtitles 20.0.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.0.0
[15:27:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.0.0
[15:27:14] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[15:27:14] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[15:27:14] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[15:27:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[15:27:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[15:27:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[15:27:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing EpisodeProvider
[15:27:15] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
Thu Oct 31 15:27:26 CST 2024
Stopping Jellyfin service :  (1317)
```

**Comment by nielsvanvelzen** [comment] 2024-10-31 07:54
Duplicate of #12885. You have an plugin incompatible with Jellyfin 10.10 installed which is causing the server to not start. Remove the plugin and everything should work again.

**Closed by nielsvanvelzen** 2024-10-31 07:54 UTC
Labels: bug

**Comment by daizhichao** [comment] 2024-10-31 08:03
These plugins were in normal use before.

**Comment by daizhichao** [comment] 2024-10-31 08:46
Although I don't know why these plugins could be used before but suddenly cannot be used, after I deleted all the plugins, Jellyfin did start up normally. Thank you very much for your answer.
