### ISSUE TITLE
Build Certificate expired

### ISSUE THREAD

**Issue by erwinkramer** [jellyfin/jellyfin#2231] opened 2020-01-05 17:21 UTC
**Describe the bug**
Certificate with CN = build.jellyfin.org is expired today. Possibly more because the update check for plugins fails with error` The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

**To Reproduce**
1. Go to https://repo.jellyfin.org/releases/server/portable/stable/
2. See certificate error in browser bar.

**Expected behavior**
Valid certificate ;)

**Logs**
When opening plugin screen on your server and check the console: 
` [ERR] Error processing request
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)`

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (chromium)
 - Jellyfin Version: 10.4.3 64x version
 - Installed Plugins: none
 - Reverse proxy: nope

**Comment by DarkVirtue** [comment] 2020-01-05 18:04
I'm getting a similar error when trying to connect to the Debian repo:

```
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 68.183.204.194 443]

E: The repository 'https://repo.jellyfin.org/debian buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by joshuaboniface** [comment] 2020-01-05 18:08
Was caused by a Let's Encrypr renewal script failure (didn't combine the key and cert into a combined cert for HAProxy). All fixed now.

**Closed by joshuaboniface** 2020-01-05 18:08 UTC
Labels: bug
