### ISSUE TITLE
Audio Imbalance Issue when Casting

### ISSUE THREAD

**Issue by Maakse** [jellyfin/jellyfin#10734] opened 2023-12-15 22:35 UTC
**Description**
When casting a program, there is an issue with the audio balance. The voice track's volume is lower than that of the sound effects, leading to an imbalance in audio output.

**Steps to Reproduce**
Cast a program using Jellyfin.
Observe the audio balance between voice and sound effects.
Note the discrepancy in volume, with the voice track being too low.
Expected Behavior
The audio balance during casting should maintain an equal volume between the voice track and sound effects for a more immersive experience.

**Comment by crobibero** [comment] 2023-12-15 23:30
This sounds more like a feature request for audio normalization then a bug report

**Comment by felix920506** [comment] 2023-12-16 05:14
This is a duplicate of #537 , which has been marked as a feature request. The feature request is being tracked here:
https://features.jellyfin.org/posts/2363/replay-gain-normalization

**Closed by felix920506** 2023-12-16 05:14 UTC
