### ISSUE TITLE
[Issue]: external internet required for local access

### ISSUE THREAD

**Issue by cegfault** [jellyfin/jellyfin#8420] opened 2022-09-17 21:31 UTC
### Please describe your bug

No client can connect to a local jellyfin server when there is no external internet.

I have unstable internet; it frequently goes down for minutes to a few hours.  The problem is the Jellyfin *server* is making an http request to `https://repo.jellyfin.org/releases/plugin/manifest-stable.json` on every client connection.

This is a serious flaw. Android, web browser, whatever, will just hang until there is the timeout and then a "select" server screen appears.  There is absolutely no reason whatsoever why a local server should break whenever external internet goes down.

This seems really easy to handle - make the web request in another thread/background, and silently handle the error if it doesn't complete. But (a) hanging the client until timeout is not a great way to handle this, and (b) on error simply breaking into a "select server" screen is very, very not okay.

So far the only solution is to twiddle your thumbs and wait for external internet.

Please note this is an error with the **server** making the web request, but it prevents any/all local clients from connecting to it.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: all
- Virtualization: all
- Clients: all
- Browser: all
- FFmpeg Version: all
- Playback Method: all
- Hardware Acceleration: all
- Plugins: all
- Reverse Proxy: all
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[ERR] An error occurred while accessing the plugin manifest: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jimdogx** [comment] 2022-09-17 22:00
I believe the server looks for plugins on server startup and then per schedule.  As a workaround, you can delete the "Update Plugin" Schedule under "Dashboard" --> "Scheduled Tasks" --> "Update Plugins".

**Comment by crobibero** [comment] 2022-09-17 22:43
>  The problem is the Jellyfin server is making an http request to https://repo.jellyfin.org/releases/plugin/manifest-stable.json on every client connection.

That doesnt seem correct, it should only check the repo during the scheduled task or when browsing for plugins.

Please provide full logs.

**Comment by cegfault** [comment] 2022-09-20 08:57
@crobibero You're right; it's being queued (logs below).  Nonetheless, it would seem that once the update fails no clients can connect to the server.

What's interesting is not the logs below, but what's missing: I don't see anything in the logs after this until I rebooted (ie, "`[INF] Received a SIGTERM signal, shutting down`")

I didn't think to look in the browser's console, but my hunch is that after the update fails something else is hanging or deadlocked, but I wouldn't know. The clients are definitely timing out....

```
[2022-09-18 14:03:42.688 +00:00] [INF] Queuing task "PluginUpdateTask"
[2022-09-18 14:03:42.692 +00:00] [INF] Executing "Update Plugins"
[2022-09-18 14:04:38.838 +00:00] [ERR] An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: Resource temporarily unavailable (repo.jellyfin.org:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)

[2022-09-18 14:04:38.856 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 56 seconds
[2022-09-18 14:04:38.865 +00:00] [INF] ExecuteQueuedTasks
```

**Comment by jimdogx** [comment] 2022-09-24 20:55
I'm at a loss.  I can't reproduce this.  I've blocked repo.jellyfin.org on my network and get the following excpetion:

```[14:52:40] [ERR] [58] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
System.Net.Http.HttpRequestException: No route to host (repo.jellyfin.org:443)
 ---> System.Net.Sockets.SocketException (65): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken) in /Users/jimi/Source/jellyfin-server/Emby.Server.Implementations/Updates/InstallationManager.cs:line 102
[14:52:40] [INF] [53] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[14:52:40] [INF] [53] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

Yet I'm still able to connect with both the Web client and a Roku client.  @cegfault is there by any chance anything else in the log (another exception that isn't related to the plugins)?

**Comment by Bond-009** [comment] 2022-12-07 15:29
Closing as can't reproduce and not enough info

**Closed by Bond-009** 2022-12-07 15:29 UTC
Labels: bug
