### ISSUE TITLE
need Douban.com metadata 

### ISSUE THREAD

**Issue by Sumxx** [jellyfin/jellyfin#1596] opened 2019-08-03 07:27 UTC
I am in China, I would like to have Douban metadata very much,Because most of my TV plays are now unrecognizable, I use them badly.

I also have a question about what format my filename should follow.
My current format is like this -> 外星生命.Another.Life.S01E01.中文字幕.WEB.1080p.mp4
He could not correctly identify success. All the plays are stacked together.

**Comment by anthonylavado** [comment] 2019-08-04 20:41
Duplicate of #1416, we’ll try to help there.

**Closed by anthonylavado** 2019-08-04 20:41 UTC
Labels: duplicate
