### ISSUE TITLE
[Issue]: The value cannot be an empty string. (Parameter 'rating')

### ISSUE THREAD

**Issue by unknown1818** [jellyfin/jellyfin#11571] opened 2024-05-12 16:47 UTC
### Please describe your bug

```
[16:43:23] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateRatingLevels: Recalculating parental rating levels based on rating string.
[16:43:23] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateRatingLevels'
System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[16:43:23] [FTL] [1] Main: Error while starting server
System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[16:43:23] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

### Reproduction Steps

Installed latest version 1 hour ago via watchtower

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[16:43:23] [INF] [1] Jellyfin.Server.Migrations.Routines.MigrateRatingLevels: Recalculating parental rating levels based on rating string.
[16:43:23] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateRatingLevels'
System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
[16:43:23] [FTL] [1] Main: Error while starting server
System.ArgumentException: The value cannot be an empty string. (Parameter 'rating')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Emby.Server.Implementations.Localization.LocalizationManager.GetRatingLevel(String rating, String countryCode)
   at Jellyfin.Server.Migrations.Routines.MigrateRatingLevels.Perform()
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[16:43:23] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[16:43:23] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2024-05-12 16:49
Duplicate of https://github.com/jellyfin/jellyfin/issues/11532

**Closed by crobibero** 2024-05-12 16:49 UTC
Labels: bug

**Comment by mgtroyas** [comment] 2024-12-07 08:46
Same problem here, Jellyfin 10.10.1 running on a QNAP NAS container.

`[2024-12-07 08:04:01.988 +00:00] [ERR] [84] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN8MGKNOGTBP"", Request id ""0HN8MGKNOGTBP:0000001C"": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (The value cannot be an empty string. (Parameter 'path'))
 ---> System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String fileName)
   at Jellyfin.Server.Infrastructure.SymlinkFollowingPhysicalFileResultExecutor.GetFileInfo(String path)
   at System.IO.Pipelines.Pipe.<>c.<.cctor>b__100_1(Object state)
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CancelRequestAbortedTokenCallback()`
