### ISSUE TITLE
Live TV transcoding Mpeg2 when it shouldn't

### ISSUE THREAD

**Issue by williamthrilliam** [jellyfin/jellyfin#11060] opened 2024-02-24 17:35 UTC
Live tv is using HDHomeRun FLEX 4K works pretty well, but it won't direct play to my nvidia Shield (android). Audio is a direct pass-through but it complains that the TranscodeReason=ContainerNotSupported even though Mpeg2 is supported on my device. The android client has direct stream live tv (transcoding is disabled) option under preferences > playback > live tv and bitstream for dolby digital and dts selected. I'm also using the ExoPlayer, the libvlc player just fails to direct stream and then both the video and audio are transcoded. Below are the logs when trying to play with ExoPlayer.

**Media Info of the file**
```
General
ID                                       : 1003 (0x3EB)
Complete name                            : http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts
Format                                   : MPEG-TS
Duration                                 : 8 s 559 ms
Overall bit rate mode                    : Variable
Law rating                               : TV-PG

Video
ID                                       : 49 (0x31)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Video
Commercial name                          : HDV 720p
Format version                           : Version 2
Format profile                           : Main@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Codec ID                                 : 2
Duration                                 : 8 s 559 ms
Bit rate mode                            : Variable
Maximum bit rate                         : 17.6 Mb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Active Format Description                : Letterbox 16:9 image
Frame rate                               : 59.940 (60000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Time code of first frame                 : 20:45:40;07
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open

Audio #1
ID                                       : 52 (0x34)
Menu ID                                  : 1 (0x1)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : 129
Duration                                 : 8 s 559 ms
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -803 ms
Stream size                              : 401 KiB
Service kind                             : Complete Main

Audio #2
ID                                       : 53 (0x35)
Menu ID                                  : 1 (0x1)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : 129
Duration                                 : 8 s 559 ms
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -451 ms
Stream size                              : 100 KiB
Service kind                             : Complete Main

Text #1
ID                                       : 49 (0x31)-CC1
Menu ID                                  : 1 (0x1)
Format                                   : EIA-608
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 8 s 559 ms
Duration of the visible content          : 2 s 504 ms
Start time (commands)                    : 10 h 23 min / 10 h 23 min
Start time                               : 10 h 23 min / 10 h 23 min
End time                                 : 10 h 23 min
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte
Count of events                          : 3
Count of RollUp events                   : 2
Count of PaintOn events                  : 1
Count of lines                           : 3
Maximum count of lines per event         : 2
Type of the first event                  : RollUp / RollUp

Text #2
ID                                       : 49 (0x31)-CC3
Menu ID                                  : 1 (0x1)
Format                                   : EIA-608
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 8 s 559 ms
Start time (commands)                    : 10 h 23 min / 10 h 23 min
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte
Count of lines                           : 0

Text #3
ID                                       : 49 (0x31)-1
Menu ID                                  : 1 (0x1)
Format                                   : EIA-708
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 8 s 559 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte

Text #4
ID                                       : 49 (0x31)-2
Menu ID                                  : 1 (0x1)
Format                                   : EIA-708
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 8 s 559 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte
```

**Logs**
```
[2024-02-24 10:42:54.757 -06:00] [INF] Opening channel stream from "Emby", external channel Id: "hdhr_7.1"
[2024-02-24 10:42:54.757 -06:00] [INF] Streaming Channel "hdhr_7.1"
[2024-02-24 10:42:54.758 -06:00] [INF] GetChannelStream: channel id: "hdhr_7.1". stream id: "native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2" profile: "native"
[2024-02-24 10:42:54.758 -06:00] [INF] Opening "SharedHttpStream" Live stream from "http://192.168.87.81:5004/auto/v7.1"
[2024-02-24 10:42:55.023 -06:00] [INF] Beginning "SharedHttpStream" stream to "/var/lib/jellyfin/transcodes/138a6f65a18842f28bd830c4de563d2a.ts"
[2024-02-24 10:42:55.023 -06:00] [INF] Live stream opened after 265.2611ms
[2024-02-24 10:42:55.023 -06:00] [INF] Returning mediasource streamId "native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2", mediaSource.Id "native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2", mediaSource.LiveStreamId null
[2024-02-24 10:42:55.023 -06:00] [INF] Live tv media info probe took "0.0002348" seconds
[2024-02-24 10:42:55.024 -06:00] [INF] Live stream opened: MediaSourceInfo { Protocol: Http, Id: "native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2", Path: "http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts", EncoderPath: null, EncoderProtocol: null, Type: Default, Container: "mpegts", Size: null, Name: null, IsRemote: False, ETag: null, RunTimeTicks: null, ReadAtNativeFramerate: False, IgnoreDts: True, IgnoreIndex: False, GenPtsInput: False, SupportsTranscoding: True, SupportsDirectStream: True, SupportsDirectPlay: False, IsInfiniteStream: True, RequiresOpening: True, OpenToken: null, RequiresClosing: True, LiveStreamId: "a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2", BufferMs: 0, RequiresLooping: False, SupportsProbing: True, VideoType: null, IsoType: null, Video3DFormat: null, MediaStreams: [MediaStream { Codec: "mpeg2video", CodecTag: null, Language: null, ColorRange: "tv", ColorSpace: null, ColorTransfer: null, ColorPrimaries: null, DvVersionMajor: null, DvVersionMinor: null, DvProfile: null, DvLevel: null, RpuPresentFlag: null, ElPresentFlag: null, BlPresentFlag: null, DvBlSignalCompatibilityId: null, Comment: null, TimeBase: "1/90000", CodecTimeBase: null, Title: null, VideoRange: "SDR", VideoRangeType: "SDR", VideoDoViTitle: null, LocalizedUndefined: null, LocalizedDefault: null, LocalizedForced: null, LocalizedExternal: null, DisplayTitle: "720p MPEG2VIDEO SDR", NalLengthSize: null, IsInterlaced: False, IsAVC: null, ChannelLayout: null, BitRate: 8000000, BitDepth: 8, RefFrames: 1, PacketLength: null, Channels: null, SampleRate: null, IsDefault: False, IsForced: False, Height: 720, Width: 1280, AverageFrameRate: 59.94006, RealFrameRate: 59.94006, Profile: "Main", Type: Video, AspectRatio: "16:9", Index: -1, Score: null, IsExternal: False, DeliveryMethod: null, DeliveryUrl: null, IsExternalUrl: null, IsTextSubtitleStream: False, SupportsExternalStream: False, Path: null, PixelFormat: "yuv420p", Level: 4, IsAnamorphic: False }, MediaStream { Codec: "ac3", CodecTag: "AC-3", Language: null, ColorRange: null, ColorSpace: null, ColorTransfer: null, ColorPrimaries: null, DvVersionMajor: null, DvVersionMinor: null, DvProfile: null, DvLevel: null, RpuPresentFlag: null, ElPresentFlag: null, BlPresentFlag: null, DvBlSignalCompatibilityId: null, Comment: null, TimeBase: "1/90000", CodecTimeBase: null, Title: null, VideoRange: null, VideoRangeType: null, VideoDoViTitle: null, LocalizedUndefined: null, LocalizedDefault: null, LocalizedForced: null, LocalizedExternal: null, DisplayTitle: "Dolby Digital - 5.1", NalLengthSize: null, IsInterlaced: False, IsAVC: null, ChannelLayout: "5.1", BitRate: 384000, BitDepth: null, RefFrames: null, PacketLength: null, Channels: 6, SampleRate: 48000, IsDefault: False, IsForced: False, Height: null, Width: null, AverageFrameRate: null, RealFrameRate: null, Profile: null, Type: Audio, AspectRatio: null, Index: -1, Score: null, IsExternal: False, DeliveryMethod: null, DeliveryUrl: null, IsExternalUrl: null, IsTextSubtitleStream: False, SupportsExternalStream: False, Path: null, PixelFormat: null, Level: 0, IsAnamorphic: null }], MediaAttachments: [], Formats: [], Bitrate: 8384000, Timestamp: null, RequiredHttpHeaders: [], TranscodingUrl: null, TranscodingSubProtocol: null, TranscodingContainer: null, AnalyzeDurationMs: 3000, TranscodeReasons: 0, DefaultAudioStreamIndex: null, DefaultSubtitleStreamIndex: null, VideoStream: MediaStream { Codec: "mpeg2video", CodecTag: null, Language: null, ColorRange: "tv", ColorSpace: null, ColorTransfer: null, ColorPrimaries: null, DvVersionMajor: null, DvVersionMinor: null, DvProfile: null, DvLevel: null, RpuPresentFlag: null, ElPresentFlag: null, BlPresentFlag: null, DvBlSignalCompatibilityId: null, Comment: null, TimeBase: "1/90000", CodecTimeBase: null, Title: null, VideoRange: "SDR", VideoRangeType: "SDR", VideoDoViTitle: null, LocalizedUndefined: null, LocalizedDefault: null, LocalizedForced: null, LocalizedExternal: null, DisplayTitle: "720p MPEG2VIDEO SDR", NalLengthSize: null, IsInterlaced: False, IsAVC: null, ChannelLayout: null, BitRate: 8000000, BitDepth: 8, RefFrames: 1, PacketLength: null, Channels: null, SampleRate: null, IsDefault: False, IsForced: False, Height: 720, Width: 1280, AverageFrameRate: 59.94006, RealFrameRate: 59.94006, Profile: "Main", Type: Video, AspectRatio: "16:9", Index: -1, Score: null, IsExternal: False, DeliveryMethod: null, DeliveryUrl: null, IsExternalUrl: null, IsTextSubtitleStream: False, SupportsExternalStream: False, Path: null, PixelFormat: "yuv420p", Level: 4, IsAnamorphic: False } }
[2024-02-24 10:42:55.024 -06:00] [INF] User policy for "williamthrilliam". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-02-24 10:42:55.024 -06:00] [INF] StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported ) "media:/videos/8ceacd18-fa9b-b535-2fef-8e0fa5a71d9e/master.m3u8?MediaSourceId=native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2&VideoCodec=hevc,h264&AudioCodec=ac3&AudioStreamIndex=-1&VideoBitrate=119616000&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=59.94006&api_key=<token>&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2&RequireAvc=false&SegmentContainer=ts&BreakOnNonKeyFrames=False&mpeg2video-level=4&mpeg2video-videobitdepth=8&mpeg2video-profile=main&mpeg2video-audiochannels=6&aac-audiochannels=8&TranscodeReasons=ContainerNotSupported"
[2024-02-24 10:42:55.125 -06:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 3000000 -fflags +igndts -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v mpeg2_qsv -autorotate 0 -i \"http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryslow -b:v 8000000 -maxrate 8000000 -bufsize 16000000 -g:v:0 180 -keyint_min:v:0 180 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=format=nv12\" -flags -global_header -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url \"hls/4ed744727a722ec7bdc761721a7b3acb/\" -hls_segment_filename \"/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb%d.ts\" -hls_playlist_type event -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb.m3u8\""
[2024-02-24 10:43:05.680 -06:00] [WRN] Slow HTTP Response from "http://192.168.87.128:8096/videos/8ceacd18-fa9b-b535-2fef-8e0fa5a71d9e/live.m3u8?DeviceId=ffbfa6ce19bb40e377a62c7ee80e73b82faafb27&MediaSourceId=native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2&VideoCodec=hevc,h264&AudioCodec=ac3&AudioStreamIndex=-1&VideoBitrate=119616000&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=59.94006&PlaySessionId=9412babbfa424690813b2f811d146388&api_key=b508c110a5a941b2bf69e6453db0699e&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2&RequireAvc=false&SegmentContainer=ts&BreakOnNonKeyFrames=False&mpeg2video-level=4&mpeg2video-videobitdepth=8&mpeg2video-profile=main&mpeg2video-audiochannels=6&aac-audiochannels=8&TranscodeReasons=ContainerNotSupported" to "192.168.87.49" in 0:00:10.5574749 with Status Code 200
```

**FFmpeg Logs**
```
/videos/8ceacd18-fa9b-b535-2fef-8e0fa5a71d9e/live.m3u8

{"Protocol":1,"Id":"native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2","Path":"http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mpegts","Size":null,"Name":null,"IsRemote":false,"ETag":null,"RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":false,"IsInfiniteStream":true,"RequiresOpening":true,"OpenToken":null,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_native_9098a73d5f0a41a094a99f31435d5a51_9bd74ef4e6a5237225e66a53427f8dd2","BufferMs":0,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"mpeg2video","CodecTag":null,"Language":null,"ColorRange":"tv","ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"720p MPEG2VIDEO SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":8000000,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":59.94006,"RealFrameRate":59.94006,"Profile":"Main","Type":1,"AspectRatio":"16:9","Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":4,"IsAnamorphic":false},{"Codec":"ac3","CodecTag":"AC-3","Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Dolby Digital - 5.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":384000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":8384000,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":3000,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -fflags +igndts -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v mpeg2_qsv -autorotate 0 -i "http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryslow -b:v 8000000 -maxrate 8000000 -bufsize 16000000 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=format=nv12" -flags -global_header -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/4ed744727a722ec7bdc761721a7b3acb/" -hls_segment_filename "/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb%d.ts" -hls_playlist_type event -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~23.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
[mpeg2video @ 0x555a09fe80c0] Invalid frame dimensions 0x0.
    Last message repeated 45 times
Input #0, mpegts, from 'http://192.168.87.128:8096/LiveTv/LiveStreamFiles/138a6f65a18842f28bd830c4de563d2a/stream.ts':
  Duration: N/A, start: 35535.586867, bitrate: N/A
  Program 1 
  Stream #0:0[0x31]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, progressive), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 17588800/0/0 buffer size: 7995392 vbv_delay: N/A
  Stream #0:1[0x34]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 384 kb/s
  Stream #0:2[0x35]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, mono, fltp, 96 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (mpeg2_qsv) -> hevc (hevc_qsv))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mpeg2_qsv @ 0x555a0a337fc0] More data is required to decode header
    Last message repeated 45 times
Output #0, hls, to '/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: hevc (hvc1 / 0x31637668), qsv(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 8000 kb/s, 59.94 fps, 90k tbn
    Metadata:
      encoder         : Lavc60.3.100 hevc_qsv
    Side data:
      cpb: bitrate max/min/avg: 8000000/0/8000000 buffer size: 16000000 vbv_delay: N/A
  Stream #0:1: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 384 kb/s
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
frame=  180 fps=0.0 q=-0.0 size=N/A time=00:00:02.88 bitrate=N/A speed=5.04x    
frame=  209 fps=192 q=-0.0 size=N/A time=00:00:03.42 bitrate=N/A speed=3.14x    
[hls @ 0x555a0a364f00] Opening '/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb0.ts' for writing
[hls @ 0x555a0a364f00] Opening '/var/lib/jellyfin/transcodes/4ed744727a722ec7bdc761721a7b3acb.m3u8.tmp' for writing
```

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - Ubuntu 23.04 (GNU/Linux 6.2.0-39-generic x86_64)
 - Jellyfin Version: 10.8.13
 - Hardware settings & device: QSV Intel(R) Pentium(R) Silver N6005 @ 2.00GHz
 - Reverse proxy: no
 - Other hardware notes: QSV and low power HuC and GuC works great, logs show that as well. 
 
**Client System (please complete the following information):**
 - Device: Nvidia Shield
 - OS: Android
 - Client: Android
 - Client and Browser Version: 0.16.5

**Comment by MichaelRUSF** [comment] 2024-03-01 22:51
It's transcoding b/c the MPEG-TS container was disabled in the exoplayer profile for compatibility [reasons](https://github.com/jellyfin/jellyfin-androidtv/pull/2695).

**Comment by williamthrilliam** [comment] 2024-03-01 23:23
Ah interesting. I’m surprised, it looks like I’m the first one to notice since the change. Any chance this will get fixed or is effort being aligned towards libvlc?

**Comment by MichaelRUSF** [comment] 2024-03-02 20:58
The developer is in the middle of a code rewrite, here is a message he recently posted. 

"We now have a [roadmap](https://github.com/orgs/jellyfin/projects/47) for the Android TV app. This will help prioritize bugs and feature requests.
Something missing? Create a [new issue](https://github.com/jellyfin/jellyfin-androidtv/issues/new/choose) or use the 👍 reaction on an existing issue!"

The app's main focus is exoplayer, libvlc is not really supported and will be removed temporarily at some point during the rewrite. I would suggest closing this issue, as it's not a bug with the server, and opening up a feature request on the Android TV repo.

**Closed** 2024-03-03 01:06 UTC
Labels: bug, live-tv
