### ISSUE TITLE
[Issue]: Certain search queries don't work properly

### ISSUE THREAD

**Issue by server-imp** [jellyfin/jellyfin#9943] opened 2023-06-30 22:20 UTC
### Please describe your bug

In my movie library I have the film "Her (2013)", but when I search for it it does not show up in the results.
I can see it inside the library, or through the actors movie listings. 

On the Jellyfin Discord I talked to someone about this, and they tested it for themself and could verify the glitch.
Not sure if it affects any other titles. I've tested with some other 3 letter titles and they seem fine. 

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS: Fedora Workstation
- Linux Kernel: 6.3.8-200
- Virtualization: Docker?
- Clients: Jellyfin Media Player
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by menonGitHub** [comment] 2023-07-30 13:50
Same issue here. 

searching for …

Unorthodox’ - fail
‘Unsane’ - success
‘Un orthodox’ - success
‘un sane’ - success
‘Unort hodox’ - success
‘Uns ane’ - success
Try once again,
‘Unorthodox’ - fail

**Comment by c4mz** [comment] 2023-09-30 00:39
Also here. If I search for the TV series "Dark", it does not show in the search.

**Comment by server-imp** [comment] 2023-09-30 12:13
Another example, tv series called "Extras" don't show up in results.
Seems there is some form of filter for the search that ignores "simple" names such as "her", "dark", "extras"..

**Comment by srcrist** [comment] 2023-10-07 13:17
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/5283.

**Closed by srcrist** 2023-10-07 13:17 UTC
Labels: bug
