### ISSUE TITLE
Default cast device does not automatically connect

### ISSUE THREAD

**Issue by fuzxi** [jellyfin/jellyfin#12423] opened 2024-08-11 03:59 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to Jellyfin 10.9.9, the default cast device no longer automatically connects when loading the Jellyfin home page in my browser. I can reproduce this with the Android Jellyfin client, Gelli, and jellyfin-mpv-shim, using both LibreWolf and Chromium. Unchecking and rechecking "Set as default" has no effect. If I downgrade back to 10.9.8, it works as expected.

### Reproduction steps

1. Open the Jellyfin home page in a browser
2. Open the Cast to Device menu
3. Connect to any device and set it as the default
4. Refresh the browser page

### What is the current _bug_ behavior?

The selected default cast device does not automatically connect.

### What is the expected _correct_ behavior?

The selected default cast device should automatically connect.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Debian
- Linux Kernel: 6.1.0
- Virtualization: Docker (using image `jellyfin/jellyfin`)
- Clients: jellyfin-mpv-shim, Android
- Browser: LibreWolf 128, Chromium 127
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Nothing useful here, just cast device connections/disconnections.
[2024-08-10 20:50:29.372 -07:00] [INF] [58] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.100" request
[2024-08-10 20:50:40.405 -07:00] [INF] [49] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.100" closed
[2024-08-10 20:50:40.632 -07:00] [INF] [49] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.100" request
```

**Comment by mkrsticch** [comment] 2024-08-11 12:15
I have the same problem

**Comment by karserasl** [comment] 2024-08-11 14:47
Me2.. with Jellyfin MPV shim

**Comment by Dev-Egor** [comment] 2024-08-12 16:57
Same issue

**Comment by fuzxi** [comment] 2024-08-12 17:12
Hi all, thanks for confirming. If you also have this issue and don't have additional info to add, please just click the thumbs up button on the initial issue comment instead of posting a reply. That way, people following the issue won't get spammed with notifications. Thanks!

**Comment by thornbill** [comment] 2024-08-12 17:58
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5878

**Closed by thornbill** 2024-08-12 17:58 UTC
Labels: bug
