### ISSUE TITLE
[Issue]: [10.8.0] more than 301 photos in directory => wrong fullscreen photo

### ISSUE THREAD

**Issue by 4ndreasH** [jellyfin/jellyfin#6844] opened 2021-11-14 10:29 UTC
### Please describe your bug

Please consider fixing bug #2294. The bug is present in 10.8.0 alpha1 and alpha2.

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:OpenSuse Tumbleweed
- Virtualization: -
- Clients: bowser, Android App
- Browser: firefox, chrome, opera
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- Plugins: -
- Reverse Proxy: apache (bug occurs also w/o proxy)
- Base URL: /jellyfin
- Networking: local
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment] 2021-11-14 10:37
Closing as duplicate of https://github.com/jellyfin/jellyfin-web/issues/2294

**Closed by nielsvanvelzen** 2021-11-14 10:37 UTC
Labels: bug
