### ISSUE TITLE
[Issue]: ffmpeg path missing when updating to 10.8.13-1 on CentOS 7

### ISSUE THREAD

**Issue by WhiteyDude** [jellyfin/jellyfin#10776] opened 2023-12-28 16:48 UTC
### Please describe your bug

I thought I should cross post https://github.com/pdulvp/jellyfin-qnap/issues/65#issuecomment-1871332247 to here, given the original issue was on a QNAP specific repo for some reason.

As mentioned, when upgrading (from 10.8.9-1 in my case) to 10.8.13-1, the ffmpeg path is not set in the web UI, and the error `FFmpeg path not set` is thrown in the logs when any playback is attempted.

This is resolved by building the custom jellyfin-ffmpeg (6.0.1) to replace my system ffmpeg (3.4.13) and then fiddling with multiple configuration points.

Given the other user and myself were both on CentOS 7, I suspect this may be an issue specific to Jellyfin detecting the OS binary or something similar.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method: N/A
- Hardware Acceleration: None
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: Yes (nginx)
- Base URL: N/A
- Networking: N/A
- Storage: N/A
- ffmpeg: 6.0.1 (from 3.4.13)
- OS: CentOS Linux release 7.9.2009 (Core) (/etc/redhad-release)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2023-12-29 05:58
Packaging issue

**Comment by kevincox** [comment] 2024-01-13 21:53
I'm seeing this as well on NixOS. But this is weird because the `--ffmpeg` flag is being passed.

```
[21:51:28] [INF] [1] Main: Jellyfin version: 10.8.13
[21:51:28] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DefaultRedirectPath, web/]", "[JELLYFIN_hostwebclient, false]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_kestrel__socketPath, /run/jellyfin/sock]", "[DOTNET_ROOT, /nix/store/szmmffbr3g6ksm9wzjlvh146xbqd6qc5-aspnetcore-runtime-6.0.25]", "[JELLYFIN_kestrel__socket, true]"]
[21:51:28] [INF] [1] Main: Arguments: ["/nix/store/djp6gg4vg4vlxd5hvf259qadh0rl093x-jellyfin-10.8.13/lib/jellyfin/jellyfin.dll", "--ffmpeg", "/nix/store/llgdha7k8lcnl48qf1zydkf40gga9k5x-jellyfin-ffmpeg-6.0-7-bin/bin/ffmpeg", "--webdir", "/nix/store/7cylgalm79si0wwxlk7pkarsm1qpg51h-jellyfin-web-10.8.13/share/jellyfin-web", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin"]
[21:51:28] [INF] [1] Main: Operating system: Linux
[21:51:28] [INF] [1] Main: Architecture: X64
[21:51:28] [INF] [1] Main: 64-Bit Process: True
[21:51:28] [INF] [1] Main: User Interactive: True
[21:51:28] [INF] [1] Main: Processor count: 12
[21:51:28] [INF] [1] Main: Program data path: /var/lib/jellyfin
[21:51:28] [INF] [1] Main: Web resources path: /nix/store/7cylgalm79si0wwxlk7pkarsm1qpg51h-jellyfin-web-10.8.13/share/jellyfin-web
[21:51:28] [INF] [1] Main: Application directory: /nix/store/djp6gg4vg4vlxd5hvf259qadh0rl093x-jellyfin-10.8.13/lib/jellyfin/
[21:51:28] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /var/cache/jellyfin
```

```
System.ArgumentException: FFmpeg path not set.
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory) in /build/source/Jellyfin.Api/Helpers/TranscodingJobHelper.cs:line 526
   at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest) in /build/source/Jellyfin.Api/Controllers/DynamicHlsController.cs:line 321
   at lambda_method1544(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager) in /build/source/Jellyfin.Server/Middleware/ServerStartupMessageMiddleware.cs:line 49
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager) in /build/source/Jellyfin.Server/Middleware/WebSocketHandlerMiddleware.cs:line 38
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager) in /build/source/Jellyfin.Server/Middleware/IpBasedAccessValidationMiddleware.cs:line 48
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager) in /build/source/Jellyfin.Server/Middleware/LanFilteringMiddleware.cs:line 43
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext) in /build/source/Jellyfin.Server/Middleware/QueryStringDecodingMiddleware.cs:line 37
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext) in /build/source/Jellyfin.Server/Middleware/LegacyEmbyRouteRewriteMiddleware.cs:line 52
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager) in /build/source/Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs:line 67
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in /build/source/Jellyfin.Server/Middleware/ExceptionMiddleware.cs:line 101
```

There is a similar error for accessing `ffprobe`. I have checked and the specified ffmpeg binary does exist and works properly.

The source files in the stack trace don't seem to exist anymore so IDK if this code has been changed.

**Comment by kevincox** [comment] 2024-01-13 21:55
It appears that this line is being hit, which is unexpected given that the command line argument was passed:

https://github.com/jellyfin/jellyfin/blob/e93d03d8cbff2122d7296f477604146f64758a73/Jellyfin.Api/Helpers/TranscodingJobHelper.cs#L524C38-L527

**Comment by kevincox** [comment] 2024-01-13 21:58
Ok, in this case it seems to come down to this error:

```
[WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: /nix/store/w4r7gwww16yv5yx1d7c1ba6h5kg6xhwr-jellyfin-ffmpeg-6.0-7-bin/bin/ffmpeg
```

https://github.com/jellyfin/jellyfin/blob/d40224128c031e38054090e063247b9a06e46f6d/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L308

But Jellyfin just silently continues rather than crashing :(

**Comment by kevincox** [comment] 2024-01-13 22:00
Ah, interestingly it seems that check isn't even using the path from the command line argument. Then it fails because some other path doesn't exist. IDK where it gets that other path from.

**Comment by kevincox** [comment] 2024-01-13 22:05
Ok, I figured it out. `/var/lib/jellyfin/config/encoding.xml` had a stale value of `<EncoderAppPath>`. Emptying this value seems to have made Jellyfin go back to using the command line argument. When Jellyfin re-wrote the config file it updated the tag to be `<EncoderAppPath />` so it looks like this change shouldn't recur.

I guess this was a breaking change in the previous release, but it seems like it is possible to manually clean up from it.

**Comment by kevincox** [comment] 2024-01-13 22:39
Actually I'm not sure anything has changed. I checked back to `10.8.11` and they behave the same. So maybe the path just happened to work in the past and it wasn't noticed that the config file was being preferred.

But either way once clearing the setting it should use the command-line option and the option to set it via the WebUI is disabled which is hopefully good enough to prevent it from re-appearing in the config file.

The behaviour of disabling and displaying an empty field in the Web UI when that is actually the value does seem pretty inconsistent though. It seems as though either of the following behaviours would make much more sense:

1. Use the config file options, don't disable the field, show the configured value.
2. Use the CLI value, disable the field and show either empty or the CLI value.

But showing the field as empty while using it in preference to the CLI value is very surprising.

**Comment by bjornbouetsmith** [comment] 2024-03-18 15:03
I just installed a fresh copy onto rocky linux 8.9 , and I also get this error.

I followed the instructions on how to get the server installed.

I have updated my /etc/jellyfin/encoding.xml to point to the version of ffmpeg that the jellyfin rpm installed.

I also get: `FFmpeg: Failed version check: /usr/bin/ffmpeg`

And when I try to play something it fails and log contains:
`[15:36:54] [ERR] [19] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/4ed2d744-4aff-8c86-fc61-87f6bcc8209f/live.m3u8.
Mar 18 15:36:54 player.root.dom jellyfin[123328]: System.ArgumentException: FFmpeg path not set.
`

So something is clearly broken since ffmpeg is installed.

This saddens me, since I have been looking forward for so long to use jellyfin instead of emby - and since now the jellyfin app is released for webOS 4.5 today, I wanted to install it - but since it does not work I need to go back to emby until this is fixed.

Is there any other information I can provide to help you guys to fix this issue?

My installation steps were basically:

~~~bash
sudo dnf install https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm
sudo dnf config-manager --enable powertools
sudo dnf install https://repo.jellyfin.org/files/server/centos/latest-stable/amd64/jellyfin-server-10.8.13-1.el7.x86_64.rpm
sudo dnf install https://repo.jellyfin.org/files/server/centos/latest-stable/amd64/jellyfin-web-10.8.13-1.el7.noarch.rpm
~~~

Enabled and started the server, added a librart and got stuck like this.

I tried manually update the `encoding.xml` file
`<EncoderAppPath>/usr/bin/ffmpeg</EncoderAppPath>
  <EncoderAppPathDisplay />
`
But the EncoderAppPathDisplay gets reset to nothing on every start.

When I manually try to invoke ffmpeg that was installed with emby:
`ffmpeg.x86_64                            4.2.9-1.el8                                @rpmfusion-free-updates
ffmpeg-libs.x86_64                       4.2.9-1.el8                                @rpmfusion-free-updates`

It gives the error:
`/usr/bin/ffmpeg: error while loading shared libraries: libva.so.2: cannot open shared object file: No such file or directory` 

running:
` sudo dnf install libva`

continues the problem:
`/usr/bin/ffmpeg: error while loading shared libraries: libmfx.so.1: cannot open shared object file: No such file or directory`

So clearly the ffmpeg that emby installs is broken, since its missing a lot of dependencies.

I have not gone down the entire rabbit hole, but perhaps satisfying _ALL_ the dependencies manually by running ffmpeg and installing all the packages, will potentially get rid of this error.

**Comment by felix920506** [comment] 2024-03-18 19:23
The setting should be changed by editing `server.xml`

Closing as this is a config issue and not a bug. Please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact

**Closed by felix920506** 2024-03-18 19:23 UTC
Labels: bug

**Comment by bjornbouetsmith** [comment] 2024-03-18 20:00
> The setting should be changed by editing `server.xml`
> 
> Closing as this is a config issue and not a bug. Please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact

So installing a fresh copy of jellyfin using the guide provided are not supposed to work out of the box?

Also what `server.xml`?

These are the configuration files provided by the installation
~~~bash
drwxr-xr-x. 4 jellyfin jellyfin 4096 Mar 18 15:13 dlna
-rw-r--r--. 1 jellyfin jellyfin 2055 Mar 18 15:34 encoding.xml
-rw-r--r--. 1 jellyfin jellyfin 1362 Mar 18 15:11 logging.default.json
-rw-r--r--. 1 jellyfin jellyfin 1362 Nov 29 04:52 logging.json
-rw-r--r--. 1 jellyfin jellyfin 2181 Mar 18 15:19 migrations.xml
-rw-r--r--. 1 jellyfin jellyfin 1405 Mar 18 15:19 network.xml
-rw-r--r--. 1 jellyfin jellyfin 5655 Mar 18 15:19 system.xml
drwxr-xr-x. 3 jellyfin jellyfin 4096 Mar 18 15:21 users

~~~

**Comment by felix920506** [comment] 2024-03-18 20:12
Correct file might have been lost in internal communications, but either way this is a packaging / config issue and not a server issue. RPM packages are no longer going to be maintained by JF in 10.9, and JF is moving towards RPMFusion packages. 

Errors in the instructions should be reported at https://github.com/jellyfin/jellyfin.org
