### ISSUE TITLE
[Issue]: Duplicate media library after a rename

### ISSUE THREAD

**Issue by POD319** [jellyfin/jellyfin#11937] opened 2024-06-03 02:53 UTC
### Please describe your bug

I renamed my media library, which led to both the old name and the new name existing as individual libraries. The only option I see to remove the old library is to 'select' it and then delete, which does nothing:

> There was an error deleting the item from the server. Please check that Jellyfin has write access to the media folder and try again.

I now have two media libraries listed and cannot remove the old one.

### Reproduction Steps

1. Visit Home
2. 'Select' the old media library that I want removed
3. Choose 'delete' from the menu in the top right
4. Confirm deletion

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:Windows 10
```

### Jellyfin logs

```shell
There are no logs for this event
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by POD319** [comment] 2024-06-03 02:56
I am also able to see the correct list of Libraries under Dashboard --> Libraries. This issue is occurring specifically on my user Home page.

**Comment by theguymadmax** [comment] 2024-06-03 03:45
Ran into this issue today as well. I renamed my "Home Videos and Photos" library to "Photos" and now there are two. This was on 10.9.3. Folder does not show up in the dashboard, just on the home screen. Also, the folder is not in the root directory. 

![double photo](https://github.com/jellyfin/jellyfin/assets/171496228/47a299b0-4aae-4199-9b71-c8f360a2c20f)

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\AppData\Local\jellyfin\root\default\Home Videos and Photos'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, EnumerationOptions enumerationOptions)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations)
   at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)`  

-

**Comment by gummykage** [comment] 2024-06-03 11:58
Duplicate of https://github.com/jellyfin/jellyfin/issues/11885

**Comment by POD319** [comment] 2024-06-03 15:20
That workaround didn't work for me. I still have both libraries showing up on the home screen with no way to remove either of them.

**Comment by POD319** [comment] 2024-06-04 18:04
> You could try to delete the library directly from the config folder:
> 
> * stop jellyfin (recommended)
> * go to the jellyfin config folder and navigate to `config/root/default`
> * all libraries should be represented by a folder -> delete the folder of the library that you want to get rid of
>   
>   * maybe it's a good idea to make a backup of the folder just in case
> * re-start jellyfin

Only the correct libraries are showing up there. The extra library is not visible.
The library only shows up in Home for the user under My Media.

**Comment by theguymadmax** [comment] 2024-06-04 18:28
@POD319 You’ll need to edit your database
1.	Download https://sqlitebrowser.org/ 
2.	Shutdown the server
3.	Open up /Jellyfin/data/library.db  (always backup first)
4.	Choose the “Browse Data” tab, right under that is the option to choose table type, select “TypedBaseItems”
5.	Enter “MediaBrowser.Controller.Entities.CollectionFolder” in the Filter in any column field
6.	Find the entry you want to get rid of. Right-click on the number and select delete record.
7.	Click the “Write Changes” button, then close the database and restart the server.

**Comment by POD319** [comment] 2024-06-04 20:23
> @POD319 You’ll need to edit your database
> 
> 1. Download https://sqlitebrowser.org/
> 2. Shutdown the server
> 3. Open up /Jellyfin/data/library.db  (always backup first)
> 4. Choose the “Browse Data” tab, right under that is the option to choose table type, select “TypedBaseItems”
> 5. Enter “MediaBrowser.Controller.Entities.CollectionFolder” in the Filter in any column field
> 6. Find the entry you want to get rid of. Right-click on the number and select delete record.
> 7. Click the “Write Changes” button, then close the database and restart the server.

Bingo, thank you very much. That removed the library from my user view.

Since this is a workaround and not a fix to the underlying issue, should I be keeping this open for a future version?

**Comment by gnattu** [comment] 2024-06-05 01:03
A fix is on the way and will contain mitigation method for you to remove the ghosting library

**Comment by felix920506** [comment] 2024-06-24 01:38
Closing as duplicate of #11885

**Closed** 2024-06-24 01:38 UTC
Labels: bug

**Comment by deanrobin333** [comment] 2024-07-17 19:19
> @POD319 You’ll need to edit your database
> 
> 1. Download https://sqlitebrowser.org/
> 2. Shutdown the server
> 3. Open up /Jellyfin/data/library.db  (always backup first)
> 4. Choose the “Browse Data” tab, right under that is the option to choose table type, select “TypedBaseItems”
> 5. Enter “MediaBrowser.Controller.Entities.CollectionFolder” in the Filter in any column field
> 6. Find the entry you want to get rid of. Right-click on the number and select delete record.
> 7. Click the “Write Changes” button, then close the database and restart the server.

________________________
This worked brilliantly. I only had to make some changes as I use ubuntu 24.04. 
- The database location is in  `/var/lib/jellyfin/data/library.db` and hence this file can only be opened by a root user. 
- Once you download the app image, you need to give execution rights to all users, then open the app image as root. 
- On the terminal where the file is downloaded you would do this:
  ```
chmod a+x DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage
sudo ./DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage
  ```
- replace `DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage` with the correct file name.
- the last code will open the AppImage as root, and then you can proceed to steps 4 to make changes. 

Works like a cham.

**Comment by blsz** [comment] 2024-08-04 19:53
The renamed library still contains orphaned folders belonging to the orphaned library.  These folders are not listed in the Library administration view but are still included in the new duplicated library.   Deleting the orphaned library as suggested by @POD319  does not delete the referenced folders.
