### ISSUE TITLE
Support base URL configuration inside Jellyfin

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#691] opened 2019-01-23 23:54 UTC
**Describe the feature you'd like**
Jellyfin should support user-configurable base URLs, e.g. `my.domain/jellyfin/`

**Additional context**
This is a very common deployment configuration for self-hosted services, to allow users to specify multiple services by path under a single domain on a single port, especially behind a reverse proxy.

UI configuration would be related to #192 and should likely be included with it.

**Comment by JustAMan** [comment] 2019-01-24 15:30
Seems to be a duplicate of #337

**Comment by joshuaboniface** [comment] 2019-01-24 15:32
@JustAMan Kinda, I'd consider this the "super-issue" of that one.

**Closed** 2019-07-29 17:00 UTC
Labels: feature
