### ISSUE TITLE
[Issue]: Reincarnating Plugin

### ISSUE THREAD

**Issue by Typhonragewind** [jellyfin/jellyfin#9741] opened 2023-05-08 15:26 UTC
### Please describe your bug

This is a weird one and I haven't found any logs yet to show you for it.

I used the plugin Jellyscrub for a long time, but a couple of weeks ago I decided to disable it as it was starting act weird (endlessly generating BIFF files on a loop through my entire collection). After i disabled it a few days it was on the loop again (despite being disabled). So this time, I removed it completely - only to have it return a few days later, still doing the loop.

This time i disabled and then removed it, and proceeded to immediately restart jellyfin. This time things seemed to have been solved. One week or so later (today) it was doing the loop again and when i checked, there were 2 instances of Jellyscrub (pic below).

I deleted them again today, but i'm not confident it won't reappear. Tagging Jallyscrub's creator here in case they have any insights @nicknsy 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 21
- Linux Kernel: 5.15
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/7875917/236863731-fafacc17-aa4a-4175-8505-d99a19ba9601.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Typhonragewind** [comment] 2023-05-17 16:34
I discovered the trigger for it reappearing: a restart. Whenever i restart the server, the plugin comes back, even if I have uninstalled it in the plugins screen, and even deleted the repository

**Comment by nicknsy** [comment] 2023-05-17 16:43
I have never had reports of something similar happening, and jellyfin should not load the plugin once it's disabled, so I'm not sure how a bug in jellyscrub could cause this behavior.

As for the plugin folder not deleting, that appears to be normal functionality: https://github.com/nicknsy/jellyscrub/issues/96#issuecomment-1492777830.

**Comment by felix920506** [comment] 2023-10-10 21:37
Closing this as a duplicate of #9059

**Closed by felix920506** 2023-10-10 21:37 UTC
Labels: bug
