### ISSUE TITLE
Version 10.0.0.0 (docker image): TVHeadEnd & IPTV plugin wont start

### ISSUE THREAD

**Issue by pw-h** [jellyfin/jellyfin#499] opened 2019-01-07 19:49 UTC
Running version 10.0.0.0 in a docker image on a synology DS918+

Upgraded from 3.5.2 ( i think) to make srt subs working again. srt subs work, but the TVHeadEnd and IPTV plugins fail to start with these errors (dlls load succesfully btw):

`[2019-01-07 17:52:11.975 +00:00] [ERR] Error creating "TVHeadEnd.LiveTvService"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Logging.ILogger' from assembly 'MediaBrowser.Model, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at SimpleInjector.Advanced.AdvancedExtensions.Verify(IDependencyInjectionBehavior behavior, ConstructorInfo constructor)
   at SimpleInjector.ContainerOptions.IsConstructableType(Type implementationType, String& errorMessage)
   at SimpleInjector.Container.TryBuildInstanceProducerForConcreteUnregisteredType(Type type, InjectionConsumerInfo context)
   at SimpleInjector.Container.GetInstanceProducerForType(Type serviceType, InjectionConsumerInfo consumer, Func`1 buildInstanceProducer)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Tuple`2 typeInfo) in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 520
[2019-01-07 17:52:11.994 +00:00] [ERR] Error creating "MediaBrowser.Channels.IPTV.Channel"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Logging.ILogManager' from assembly 'MediaBrowser.Model, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at SimpleInjector.Advanced.AdvancedExtensions.Verify(IDependencyInjectionBehavior behavior, ConstructorInfo constructor)
   at SimpleInjector.ContainerOptions.IsConstructableType(Type implementationType, String& errorMessage)
   at SimpleInjector.Container.TryBuildInstanceProducerForConcreteUnregisteredType(Type type, InjectionConsumerInfo context)
   at SimpleInjector.Container.GetInstanceProducerForType(Type serviceType, InjectionConsumerInfo consumer, Func`1 buildInstanceProducer)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Tuple`2 typeInfo) in /repo/Emby.Server.Implementations/ApplicationHost.cs:line 520
`

**Comment by anthonylavado** [comment] 2019-01-07 19:50
Yes, this is because of a change in logging. Duplicate of #480, but I'll mention the plugin names there too.

**Closed by anthonylavado** 2019-01-07 19:50 UTC
Labels: duplicate
