### ISSUE TITLE
Movies freezes

### ISSUE THREAD

**Issue by foncubierta** [jellyfin/jellyfin#2161] opened 2019-12-17 21:47 UTC
Good, I just installed jellyfin on my dedicated server, and the truth is that everything seems perfect, but reproduction fails me, sometimes in minute 1, sometimes in minute 20 ... different movies ... And it's always the same fault freezing of the image, the video stops and I have to change the quality or go back several minutes for the video to play again. If I put the video in very low quality for example 240p it does not usually fail me, but honestly the quality is very low. I had this same error with Plex before and so I changed to jellyfin thinking it was a plex problem.

Dedicated Server(with Jellyfin installed):
Atom C2750
2.4 GHz 8 cores
Ram: 8GB
Speed Internet: 300mb or more
Folder movie: Rclone Mount with google drive

My house(where I reproduce):
In my house I usually play with the laptop (intel i5 8gb of ram ..) or with chromecast and with both I have the same problem, the only thing I suspect is my internet speed that is only 12mb but I see youtube at 1080p without problems , and my ping to the dedicated server is 40ms.

In the jellyfin log it appears as if I stop the reproduction
¿Do you have any idea that it may be failing? Thanks.

**Comment by garikaib** [comment] 2019-12-18 03:43
I cannot be sure but I think the clue lies in your server specs which cannot handle transcoding since you  mention Plex had the same issues. I have a server with an Atom and that processor is too weak to transcode hence the constant buffering issues you are seeing. So everytime you are going back a few minutes allows that poor Atom to transcode ahead of you but since its too weak you are eventually catching up with it forcing another buffer episode:

**Possible solutions**

1. Avoid transcoding altogether by disa2bling it for every user in the Jellyfin Dashboard. This might mean you will not be able to play say HEVC files in the web or on your mobile phone.
2. Use Kodi and the Kodi addon to play videos with direct play (again no transcoding)

**Caveat**
Keep an eye on that speed. I have a 15 Mbps connection myself, you say yours is 12mb ( let's assume you mean 12 Mbps and not 12 MBS),this means that there are some files you will never be able to play from your server without transcoding ( which is impossible given your server stats). YouTube is special, they use a very efficient codec VP9. Videos are already transcoded in advance and seating on that server and when you press play the best file chunk is sent to you depending on your internet speed.

What this all means is that you have to be mindful of the nature of the file on the Jellyfin server before you can begin playing it. I would encourage you to have HEVC medium bitrate files and use Kodi to play them. No Remuxes for you.

**Comment by foncubierta** [comment] 2019-12-18 23:46
I can get for very little price difference a
  Xeon E3-1220
3.1 GHz 4 cores
West:
Xeon X3450
2.6 GHz 4 cores
Is it worth changing or will I get the same result?

**Comment by garikaib** [comment] 2019-12-19 07:48
Yeah, that would be the best course of action for you. Based on other benchmarks by others, I would recommend the first one. This should work for personal use.

**Comment by foncubierta** [comment] 2019-12-24 12:18
I have changed servers to:
   Xeon E3-1220
3.1 GHz 4 cores
But I am still the same, I have verified that when I send the video to chromecast (I send it from the jellyfin application of the android mobile) it does not perform the transcoding, that is, it plays in directstream (and due to my speed it freezes).
If I play from the web player or from an android device if I do the transcoding and I can watch the movie without problems in 1080p - 6 Mbps quality.
Any idea why you don't start transcoding on chromecast?

**Comment by JustAMan** [comment] 2020-01-13 15:42
Because a transcoding only happens when there are certain conditions met, like bitrate limit or unsupported codecs.
You probably didn't have a proper bitrate limit in place. Try fiddling with the settings.

I'm going to close this issue as this is not a bug, but rather all seems to be working as intended and just requires some configuration tweaks on your side.

**Closed by JustAMan** 2020-01-13 15:42 UTC
Labels: bug
