### ISSUE TITLE
[Issue]: Jellyfin app stops controlling casting unless I disconnect it and I restart the app

### ISSUE THREAD

**Issue by Harrenkyym** [jellyfin/jellyfin#8527] opened 2022-10-09 21:52 UTC
### Please describe your bug

I'm gonna copy my absolutely forgotten post: https://github.com/jellyfin/jellyfin-chromecast/issues/357

**Describe the bug**

When I cast a movie, from a certain minute the Jellyfin app lose the connection to Chromecast. I don't see any progress bar and when I select "use as remote control" I see as if nothing was casting. I have to disconnect from casting, close the app, restart it, connect to chromecast, see it it's working, if not, redo the same steps until I can reconnect and take the control again.

**To Reproduce**

1. Cast a movie
2. Wait until the Jellyfin app stops showing any progress and the connection to Chromecast displays a void screen.
3. See error
4. Disconnect from Chromecast
5. Close app
6. Open app and close again because the Chromecast device is not showing up
7. Open app
8. Connect to Chromecast again, see if now you regained control

**Expected behavior**

I expect to NEVER lose the control of the casting.

**Screenshots**

https://i.imgur.com/E7fcxb8.png
https://i.imgur.com/W1zCvNh.png
https://i.imgur.com/jQXGzpL.png

**System (please complete the following information):**

-   OS: Windows 10/Android 11
-   Browser: any
-   Jellyfin Version: last one
-   Cast client: The one with Google TV and remote.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Chromecast
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment] 2022-10-10 06:42
Please don't create new issues when you don't get a response. We're aware of issues with the Chromecast client but we just have nobody working on it.

Closing as a duplicate of https://github.com/jellyfin/jellyfin-chromecast/issues/357

**Closed by nielsvanvelzen** 2022-10-10 06:42 UTC
Labels: bug
