### ISSUE TITLE
[Issue]: No scroll on Lyrics (.lrc) in real time

### ISSUE THREAD

**Issue by xsaMNJfkltrwq5r3** [jellyfin/jellyfin#11982] opened 2024-06-06 04:50 UTC
### Please describe your bug

Using Lyrics file (.lrc) the lyrics don't appear to scroll down the page as the song continues.  No error is thrown, just a quality of life issue.  Certainly not a priority.

### Reproduction Steps

Using Jellyfin/Jellyfin Docker in UNRAID.  And placing lyrics (.lrc) file in album.  

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS: UNRAID
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser:Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No issues with playback.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment] 2024-06-06 06:18
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5487 Fixed by https://github.com/jellyfin/jellyfin-web/pull/5585

**Closed by Shadowghost** 2024-06-06 06:18 UTC
Labels: bug
