### ISSUE TITLE
newest ubuntu sercer cant install jellyfin

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin#8665] opened 2022-10-31 03:54 UTC
![image](https://user-images.githubusercontent.com/69903376/198927754-1a902192-84a2-4278-89f3-c1c5d6edb64e.png)

**Comment by nielsvanvelzen** [comment] 2022-11-01 11:35
Duplicate of #8671

**Closed by nielsvanvelzen** 2022-11-01 11:35 UTC
