### ISSUE TITLE
[Issue]: Error during ffprobe on certain files

### ISSUE THREAD

**Issue by Mikaka27** [jellyfin/jellyfin#7586] opened 2022-04-11 19:34 UTC
### Please describe your bug

During library scan some movies trigger an error when ffprobe tries to read the movie file. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Browser and Kodi
- Browser: Firefox 99.0 on Linux
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: VAAPI
- Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, NapiSub, OMDb, TMDb Box Sets, TVMaze, TheTVDB
- Reverse Proxy: nginx on docker
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[matroska,webm @ 0x5633d0d7c3c0] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 0x5633d0d7c3c0] EBML header parsing failed
file:/mnt/Filmy/10 Cloverfield Lane 2016 1080p HDRip x264 AAC-JYK/10 Cloverfield Lane 2016 1080p HDRip x264 AAC-JYK.mkv: Invalid data found when processing input
[19:14:14] [ERR] [4] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[matroska,webm @ 0x55735fda13c0] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 0x55735fda13c0] EBML header parsing failed
file:/mnt/Filmy/Ant-Man 2015 1080p BluRay x264 DTS-JYK/Ant-Man 2015 1080p BluRay x264 DTS-JYK.mkv: Invalid data found when processing input
[19:14:18] [ERR] [4] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5564c95983c0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5564c95983c0] moov atom not found
file:/mnt/Filmy/Spy (2015) [1080p]/Spy.2015.1080p.BluRay.x264.YIFY.mp4: Invalid data found when processing input
[19:14:18] [ERR] [54] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by svanhoutte** [comment] 2022-06-29 19:40
I have the same issue on linux install. 
[2022-06-29 15:28:09.982 -04:00] [ERR] Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

**Comment by AnonymousWebHacker** [comment] 2022-11-29 20:14
Fixed https://github.com/jellyfin/jellyfin/issues/7872#issuecomment-1331233286

**Comment by Shadowex3** [comment] 2023-03-11 08:28
> Fixed [#7872 (comment)](https://github.com/jellyfin/jellyfin/issues/7872#issuecomment-1331233286)

I don't think that's it. My ffmpeg path is set properly and I get this error too.

**Comment by cliffordsnow** [comment] 2023-08-12 00:34
Same problem here. Running new installation of Jellyfin 10.8.10 on Fedora linux 38 just for Jellyfin. Music playback works on files other than mp3 and m4a. Path of /usr/bin/ set for ffmpeg

ffmpeg is version 6

**Comment by AnonymousWebHacker** [comment] 2023-08-16 19:37
> Same problem here. Running new installation of Jellyfin 10.8.10 on Fedora linux 38 just for Jellyfin. Music playback works on files other than mp3 and m4a. Path of /usr/bin/ set for ffmpeg
> 
> ffmpeg is version 6

try using the path "/usr/share/jellyfin-ffmpeg"

**Comment by cliffordsnow** [comment] 2023-08-16 19:59
I don't have a "/usr/share/jellyfin-ffmpeg" path. Searching under /usr only returns a path for /usr/bin besides /usr/share/man and /usr/share/doc. 

I attempted to install ffmpeg-free but that wanted removed jellyfin.

**Comment by Shadowghost** [comment] 2023-08-17 08:48
We do not provide jellyfin-ffmpeg packaged for fedora. You can use the portable version though.

**Comment by srcrist** [comment] 2023-10-19 13:51
Closing this issue in favor of the better documented duplicate of https://github.com/jellyfin/jellyfin/issues/7710.

**Closed by srcrist** 2023-10-19 13:51 UTC
Labels: bug
