### ISSUE TITLE
OpenSubtitle plugin not found.

### ISSUE THREAD

**Issue by GAZ082** [jellyfin/jellyfin#5138] opened 2021-01-30 22:59 UTC
```
Jan 30 22:54:58 kraken jellyfin[9110]: MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Open Subtitles
Jan 30 22:54:58 kraken jellyfin[9110]:    at MediaBrowser.Api.PackageService.Post(InstallPackage request)
Jan 30 22:54:58 kraken jellyfin[9110]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
Jan 30 22:54:58 kraken jellyfin[9110]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
Jan 30 22:54:58 kraken jellyfin[9110]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
Jan 30 22:57:09 kraken jellyfin[9110]: [22:57:09] [INF] WS ::ffff:192.168.1.9 closed
Jan 30 22:57:10 kraken jellyfin[9110]: [22:57:10] [INF] WS ::ffff:192.168.1.9 request
Jan 30 22:57:12 kraken jellyfin[9110]: [22:57:12] [WRN] HTTP Response 200 to 192.168.1.9. Time (slow): 0:00:01.7354105. http://192.168.1.2:8096/Packages/Open Subtitles?AssemblyGuid=4b9ed42f-5185-48b5-9803-6ff2989014c4
Jan 30 22:57:16 kraken jellyfin[9110]: [22:57:16] [ERR] Error processing request. URL: http://192.168.1.2:8096/Packages/Installed/Open Subtitles?AssemblyGuid=4b9ed42f-5185-48b5-9803-6ff2989014c4&version=10.0.0.0
Jan 30 22:57:16 kraken jellyfin[9110]: MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Open Subtitles
Jan 30 22:57:16 kraken jellyfin[9110]:    at MediaBrowser.Api.PackageService.Post(InstallPackage request)
Jan 30 22:57:16 kraken jellyfin[9110]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
Jan 30 22:57:16 kraken jellyfin[9110]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
Jan 30 22:57:16 kraken jellyfin[9110]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Jellyfin.Server 10.6.4.0
raspbian - Pi3.

**Comment by crobibero** [comment] 2021-01-30 23:03
Duplicate of https://github.com/jellyfin/jellyfin/issues/5129

**Closed by crobibero** 2021-01-30 23:03 UTC
Labels: bug
