### ISSUE TITLE
Cannot compute blurhash fSystem.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mmedic** [jellyfin/jellyfin#12849] opened 2024-10-19 14:22 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

[2024-10-19 14:16:44.338 +00:00] [ERR] [16] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/jellyfin/data/metadata/library/c6/c6846ec6035eabaa0ab673c0ea3f59bb/landscape.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)

### Reproduction steps

1. Run a library scan

### What is the current _bug_ behavior?

NullPointerException is thrown and recorded in th elogs

### What is the expected _correct_ behavior?

No exception

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Linux
- Linux Kernel: Gentoo
- Virtualization: None
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-10-19 14:16:44.338 +00:00] [ERR] [16] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/jellyfin/data/metadata/library/c6/c6846ec6035eabaa0ab673c0ea3f59bb/landscape.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

**Comment by JPVenson** [comment] 2024-10-19 19:28
This looks like an internal error in the Blurhash lib. Is there anything special about that image?

**Comment by gnattu** [comment] 2024-10-20 03:49
Duplicate of #3687

**Comment by gnattu** [comment] 2024-10-20 04:28
See the linked issue for more info, we need someone can reproduce to test proposed changes.

**Closed by gnattu** 2024-10-20 04:28 UTC
Labels: bug
