### ISSUE TITLE
The following signatures were invalid

### ISSUE THREAD

**Issue by Gabriel-p** [jellyfin/jellyfin#4811] opened 2020-12-16 18:55 UTC
**Describe the bug**

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.jellyfin.org/ubuntu bionic InRelease: The following signatures were invalid: EXPKEYSIG 49023CD01DE21A7B Jellyfin Team <team@jellyfin.org>
W: Failed to fetch https://repo.jellyfin.org/ubuntu/dists/bionic/InRelease  The following signatures were invalid: EXPKEYSIG 49023CD01DE21A7B Jellyfin Team <team@jellyfin.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**System (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera (based on Ubuntu 18.04.4 LTS)
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: Chrome 87.0.4280.88
 - Jellyfin Version: 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: local

**To Reproduce**

1. Attempt to update my system with `sudo apt update`

**Expected behavior**

A normal update

**Logs**

**Screenshots**

**Additional context**

**Comment by nielsvanvelzen** [comment] 2020-12-16 18:56
Duplicate of #4802

See https://jellyfin.org/posts/jellyfin-apt-key/

**Closed by nielsvanvelzen** 2020-12-16 18:56 UTC
Labels: bug
