### ISSUE TITLE
transcoding-temp directory fills up with numerous .ts files on a number of media files, even when paused

### ISSUE THREAD

**Issue by InconsolableCellist** [jellyfin/jellyfin#2495] opened 2020-03-02 00:50 UTC
**Describe the bug**
Jellyfin has had a bug since at least 10.4.0 where the transcoding-temp directory fills up with .ts files for some media, even when it's paused. It'll consume all the disk space until it can't create any more, at which point Jellyfin will become unresponsive when you attempt to play anything.

**System (please complete the following information):**
Jellyfin 10.4.3 running in Docker, on Stable on a Linux x64 host

```
$ cat /etc/os-release
PRETTY_NAME="Devuan GNU/Linux ascii"
NAME="Devuan GNU/Linux"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

```
$ docker --version
Docker version 19.03.4, build 9013bf583a
```

Browser-independent (tried Firefox and Chromium on Linux, Firefox on OS X)

 - Playback: "Direct streaming"
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: None
 - Networking: LAN, Docker in "host" mode
 - Storage: NFS

**To Reproduce**
1. Play affected media. For example

```
Containermp4
Path/media/movies/The Equalizer (2014)/The.Equalizer.2014.1080p.BluRay.x264.anoXmous.backup.copy.from.purchased.disk.mp4
Size2636 MB
Video
Title1080P H264
CodecH264
Codec tagavc1
AVCYes
ProfileHigh
Level41
Resolution1920x808
Aspect ratio2.40:1
InterlacedNo
Framerate23.9760246
Bitrate2275 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL4
Audio
TitleEng AAC 5.1 Default
Languageeng
CodecAAC
Codec tagmp4a
ProfileLC
Layout5.1
Channels6 ch
Bitrate385 kbps
Sample rate48000 Hz
DefaultYes
Audio
TitleEng AAC stereo Default
Languageeng
CodecAAC
Codec tagmp4a
ProfileLC
Layoutstereo
Channels2 ch
Bitrate124 kbps
Sample rate48000 Hz
DefaultYes
```
2. Monitor the `config/transcoding-temp` directory
3. Note that the directory fills up with .ts files, even when the movie is paused. 
4. When you leave the movie-playing page the ts files are cleaned up

**Expected behavior**
1. The movie plays normally, ts files don't accumulate, and the disk space isn't used up without warning

**Logs**
`ls` every second: https://termbin.com/bzw1

**Comment by Artiume** [comment] 2020-03-02 01:31
So this is due to the fact that ffmpeg will continue to run until it has completely transcoded the movie. What sort of hardware are you running? 

Try nightly and see how it does, I discovered some issues in the throttler today, but it is currently merged in master

https://github.com/jellyfin/jellyfin/pull/2258

**Comment by InconsolableCellist** [comment] 2020-03-02 01:34
Oh, is this expected behavior? It looked like some movies don't do this. This is running in a VM that has adequate CPU, but only has 4 GB of free disk space. I didn't think that was a problem, but I suppose it is. I'll have to try and allocate more if this is normal.

I could try nightly too. I guess my intuition was that it'd build up a moderate buffer of ts files and then wait, like buffering a video on YouTube.

**Comment by Artiume** [comment] 2020-03-02 01:48
Yep, I personally use /dev/shm, but your transcoding folder has to be capable of holding the entire transcoded file in its cache. If a movie is 50GBs, the temp file could potentially balloon to the same size. 

You could put in a features request at https://features.jellyfin.org to have it maintain only the cache of the most recent 5 minutes or something to that effect, but it's trickier than it seems because we'd have to build the capability of seamless ffmpeg terminating and restarting (which is an end goal anyways).

**Comment by JustAMan** [comment] 2020-03-02 10:36
This is expected behaviour, not a bug. So I'm closing the issue.

**Closed by JustAMan** 2020-03-02 10:36 UTC
Labels: bug
