### ISSUE TITLE
[10.8.0 Release] Scanning Media deletes existing folder.jpg and redownloads another from the URL of the <thumb> even if you didn't set to update from internet.

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#7893] opened 2022-06-12 13:39 UTC
### Please describe your bug

10.7.7 behavior - Jellyfin would scan a folder find a jpg with poster in it's name and create a folder.jpg and use that for the postercard display. This resulted in absolutely awesome collections parsed by other nfo makers used mostly because Asian films aren't all listed by imdb  tmdb and such. Only when forcing an update where replace all images did it try and create a folder.jpg from the url of <thumb<.

10.8.0 behavior - Jellyfin will now scan a folder and download from the url of <thumb< and delete the existing folder.jpg and create one from the url of <thumb< as the image of full bluray cover of a movie it would result in centered shots of bluray spines in the postercard view. This is done with all metadata modifiers turned off, all scraping turned off.

The refreshing of folder.jpg when all settings are pointing not to refresh seems to be a new bug that has been present since the first beta.

A work around is to rename the <thumb< tag or even remove it completely. 
Another temporary work around is to be offline when you add your movies, create a new library, or scan and update the movie folder. It will default back to using the folder.jpg file without updating it. Problem is as soon as the library goes back online and the scheduled task that scans and updates the folder, it will immediately delete folder.jpg and redownload from the <thumb<url of cover</thumb<

Rolling back to 10.7.7 the behavior is back to normal.

Please stop the scan media function from automatically redownloading from <thumb< and deleting the existing folder.jpg.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
- Virtualization:
- Clients:Jellyfin Media Player
- Browser:Chrome (latest)
- FFmpeg Version:5.0
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment] 2022-06-12 13:50
deleting the <thumb>url of movie poster</thumb> also skips creating the folder.jpg and just automatically uses your movie-poster.jpg or poster.jpg for the postercard. It also uses the movie-cover.jpg for the backdrop.

File structure
movie.mkv
movie-poster.jpg
movie-cover.jpg
movie-trailer.mp4

When adding it to library no folder.jpg is created, Library behavior back to 10.7.7.

**Comment by augustusy** [comment] 2022-06-13 06:00
I have the same problem! Lots of the posters and fanarts found on the internet were suitable for me and now they've all been deleted by jellyfin without any notice, THAT REALLY MAKE ME VERY  ANGRY!!!

**Comment by cvium** [comment] 2022-06-13 07:45
Duplicate of https://github.com/jellyfin/jellyfin/issues/7836, fixed by https://github.com/jellyfin/jellyfin/pull/7873

**Closed by cvium** 2022-06-13 07:45 UTC
Labels: bug

**Comment by gummykage** [comment] 2022-06-13 16:55
Thank you @cvium !
