### ISSUE TITLE
QSV transcoding MJPEG setting doesn't stick (Docker 10.9 2024041505)

### ISSUE THREAD

**Issue by caeci11ius** [jellyfin/jellyfin#11403] opened 2024-04-22 14:27 UTC
### Please describe your bug

When selecting the option "Allow encoding in MJPEG format (used during trickplay generation)" from the playback > transcoding > intel quicksync page and pressing save at the end of the page, the setting is not preserved. Other changed settings preserve correctly as expected (e.g. allow encoding in HEVC format" above).

### Reproduction Steps

1. Using the docker unstable container (2024041505 build)
2. Select the playback > transcoding page from the settings dashboard
3. On the intel quicksync subpage, select the "Allow encoding in MJPEG format (used during trickplay generation)" option
4. Press the save button at the bottom of the page
5. Refresh the page - the setting will have deselected.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Ubuntu 24.04 nightly
- Linux Kernel: 6.8.0-31-generic
- Virtualization: Docker
- Clients: N/A
- Browser: Firefox 124.0.2
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: Intel QSV (on Alder Lake i5 12400)
- GPU Model: N/A (integrated)
- Plugins: N/A
- Reverse Proxy: Traefik v3 rc5
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-04-22 14:29
Duplicate of jellyfin/jellyfin-web#5363

**Closed by gnattu** 2024-04-22 14:29 UTC
Labels: bug
