### ISSUE TITLE
Subtitles stuck barely visible at top of screen in Chrome

### ISSUE THREAD

**Issue by wsmoses** [jellyfin/jellyfin#1458] opened 2019-06-13 02:02 UTC
**Describe the bug**
When playing a video in Google Chrome the subtitles are stuck off at the top of the screen barely visible.

**To Reproduce**
1. Play a video
2. Enable subtitles

**Expected behavior**
The subtitles should be at the bottom and visible as happens in Safari.

**Screenshots**
Expected (from Safari)
<img width="1474" alt="Screen Shot 2019-06-12 at 6 55 15 PM" src="https://user-images.githubusercontent.com/1260124/59398246-57181780-8d44-11e9-9c07-f8a3807b492e.png">
Chrome:
<img width="1580" alt="Screen Shot 2019-06-12 at 6 54 59 PM" src="https://user-images.githubusercontent.com/1260124/59398247-57181780-8d44-11e9-9666-02068e68be03.png">

**System (please complete the following information):**
 - OS: Mac OS
 - Browser: Google Chrome
 - Jellyfin Version: commit e3a3aebbf69855f527b7150304d83ca9abc955ff

**Comment by anthonylavado** [comment] 2019-06-13 04:24
Duplicate of #1405, which is related to https://github.com/jellyfin/jellyfin-web/issues/298.

Apparently if you update to Chrome 75, it should be fixed.

**Closed** 2019-06-13 04:25 UTC
Labels: bug, duplicate
