### ISSUE TITLE
[Issue]: No playback queue when casting

### ISSUE THREAD

**Issue by arthurEspooner** [jellyfin/jellyfin#7342] opened 2022-02-21 01:48 UTC
### Please describe your bug

Can't see the play queue when casting to other devices. Whether through jellyfin clients or DLNA.

I saw another post that the element is in the UI but it's hidden and the onClick was removed? Will you be adding back the ability to view a remote sessions queue or was this removed on purpose?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows
- Virtualization: None
- Clients: All
- Browser: All
- FFmpeg Version: 
- Playback Method: Any type of casting to another device
- Hardware Acceleration: No
- Plugins: None
- Reverse Proxy: No
- Base URL: 
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-02-21 01:57
Duplicate of this feature request
https://github.com/jellyfin/jellyfin-chromecast/issues/84

**Closed by crobibero** 2022-02-21 01:57 UTC
Labels: bug

**Comment by arthurEspooner** [comment] 2022-02-21 02:01
Nothing to do with chromecast. I can't see the play queue on the server itself when casting to any type of device. The element is in the UI but hidden. Will this be fixed?
