### ISSUE TITLE
Trakt plugin not working on latest master

### ISSUE THREAD

**Issue by Hello-User** [jellyfin/jellyfin#1087] opened 2019-03-09 20:43 UTC
**Describe the bug**
Trakt plugin does not seem to initialize correctly on latest master

**To Reproduce**
1. Compile master
2. Install Trakt plugin
3. Start Jellyfin-server

**Expected behavior**
No trakt plugin error at server start and authorization without a 404 error

**Logs**
At Server start:
```
[ERR] Error creating "Trakt.Api.TraktUriService" 
System.InvalidOperationException: Unable to resolve service for type 'Trakt.Api.TraktApi' while attempting to activate 'Trakt.Api.TraktUriService'. 
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider) 
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Users\Administrator\Jellyfin\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 479
```
When trying to authorize device:
`
[ERR] Could not find handler for "/emby/Trakt/Users/4f30d88c10ff4e0dab1d53200e46b067/Authorize"
`

**Screenshots**
[Error](https://i.imgur.com/GvMTFvP.png)

**System (please complete the following information):**
 - OS: [Windows]
 - Browser: [Chrome]
 - Jellyfin Version: [10.2.2 compiled from master]

**Additional context**
Works on latest release build

**Comment by anthonylavado** [comment] 2019-03-09 21:27
Hi there,
This is expected - all the plug-ins can be version dependent, and likely need to be rebuilt after every minor release.

For example, a plug-in built for 10.2.0 would work on 10.2.1 and 10.2.2, but not necessarily 10.3.

The latest master introduces several changes to this effect, and should be considered a “developement/bleeding edge” version,  or a stable release :-)

**Comment by hawken93** [comment] 2019-03-10 10:12
it's not a bug, but it is a nice heads up that the trakt plugin will need recompile to work with the next release :)

**Comment by anthonylavado** [comment] 2019-04-09 21:10
Closing for #1194

**Comment by alashow** [comment] 2019-04-20 06:57
@anthonylavado I'm experiencing this problem on my server. 
Jellyfin version: 10.3.0
Trakt plugin version: 2.0.0

Error log:
```
/emby/Trakt/Users/myid/Authorize
```

**Comment by sparky8251** [comment] 2019-04-20 10:47
Guess we might need to reopen this. Im reopening it for now, if it should be closed @anthonylavado can close it again.

**Comment by SenorSmartyPants** [comment] 2019-04-20 17:11
I'm getting this in my log with 10.3 and Trakt 2.0

`[2019-04-20 11:58:08.089 -05:00] [ERR] Error creating "Trakt.Api.TraktUriService"
System.InvalidOperationException: Unable to resolve service for type 'Trakt.Api.TraktApi' while attempting to activate 'Trakt.Api.TraktUriService'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)`

Also Trakt only displays one scheduled task and not two like it has been. 'Sync Library to Trakt' is there, but the other one to pull watched history is gone. And of course that's the one I use :)

**Comment by SenorSmartyPants** [comment] 2019-04-22 01:27
I uninstalled Trakt plugin 2.0. Restarted JF. re-installed trakt, restarted JF. Trakt picked up my user configs for trakt, but still had only one scheduled job listed.

**Comment by anthonylavado** [comment] 2019-04-22 03:04
Tagging in https://github.com/jellyfin/jellyfin-plugin-trakt/issues/13

**Comment by anthonylavado** [comment] 2019-04-25 05:05
Fixed as of https://github.com/jellyfin/jellyfin-plugin-trakt/pull/14. This is in the plugin catalog as version 3. Can you try it and check for us?

**Comment by alashow** [comment] 2019-04-25 08:39
Works for me

**Comment by alashow** [comment] 2019-04-25 08:44
Like @SenorSmartyPants said, only "Sync Library to Trakt" task is available for Trakt. Is this a bug too?

**Comment by anthonylavado** [comment] 2019-04-25 12:43
Yes, we’ve got that coming up in https://github.com/jellyfin/jellyfin-plugin-trakt/pull/17

Sorry for all the updates folks.

**Closed** 2019-06-17 07:11 UTC
Labels: bug
