### ISSUE TITLE
[Issue]: Playback stops just before the end since 10.8

### ISSUE THREAD

**Issue by Ulrar** [jellyfin/jellyfin#8002] opened 2022-06-24 11:09 UTC
### Please describe your bug

Since the upgrade to 10.8, playback often stops before the end of the file randomly. The episode is then marked as watched so it disapears from the frontpage and I have to go dig it up in the library to watch the end. I've had some episodes stop multiple times, so I have to watch the end in little batches of a few seconds.

No issues with the rest of the episode, only the last minute or so is problematic.
Can't figure out what the cause is, the logs don't show any errors and seem to blame the player : `Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.0"`

No issues when using external players like VLC or Kodi, but happens on both the web player in firefox and the android app using the default player.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Unraid
- Virtualization: Docker
- Clients: Browser, Android ..
- Browser: Firefox
- FFmpeg Version: 5.0.1-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: Intel QSV
- Plugins: Kodi Sync Queue, TVDB, Playback reporting ..
- Reverse Proxy: HAProxy
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
[2022-06-24 11:59:34.608 +01:00] [INF] [111] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6OTguMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC85OC4wfDE2NDczNzEzMTQ5OTk1-e0a9e666dc55424b97d34ee15d437edc-74e5f00f54c8afd24c6f4445635fd382"
[2022-06-24 11:59:55.017 +01:00] [INF] [102] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6OTguMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC85OC4wfDE2NDczNzEzMTQ5OTk1-e0a9e666dc55424b97d34ee15d437edc-74e5f00f54c8afd24c6f4445635fd382"
[2022-06-24 12:00:15.931 +01:00] [INF] [72] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6OTguMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC85OC4wfDE2NDczNzEzMTQ5OTk1-e0a9e666dc55424b97d34ee15d437edc-74e5f00f54c8afd24c6f4445635fd382"
[2022-06-24 12:00:22.053 +01:00] [INF] [111] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/config/data/transcodes/93eff5788c30398c3013eb7c43ba731c.m3u8"
[2022-06-24 12:00:23.927 +01:00] [INF] [15] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.0" playing "Worlds War Bizzare". Stopped at "2483523" ms
[2022-06-24 12:00:24.967 +01:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6OTguMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC85OC4wfDE2NDczNzEzMTQ5OTk1-e0a9e666dc55424b97d34ee15d437edc-74e5f00f54c8afd24c6f4445635fd382"
[2022-06-24 12:00:24.967 +01:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 06/24/2022 12:00:24
[2022-06-24 12:00:24.967 +01:00] [WRN] [15] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://my.domain.tld/Sessions/Playing/Stopped" to "172.21.7.55" in 0:00:02.915371 with Status Code 204
[2022-06-24 12:00:24.967 +01:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2022-06-24 12:00:25.465 +01:00] [INF] [93] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Starting User Changes Sync...
[2022-06-24 12:00:25.594 +01:00] [INF] [93] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: "USERSYNC" User "e0a9e666dc55424b97d34ee15d437edc"("Ulrar") posted 2 Updates: "74e5f00f54c8afd24c6f4445635fd382,9951b0815c3406b429c0d3191222dfb3"
[2022-06-24 12:00:25.594 +01:00] [INF] [93] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Changes Sync Finished Taking "00:00:00.1289919"
```

### FFmpeg logs

```shell
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"myfile.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:2 -map 0:0 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 4745236 -maxrate 4745236 -bufsize 9490472 -profile:v:0 high -level 51 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12,hwmap=derive_device=qsv,format=qsv" -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/93eff5788c30398c3013eb7c43ba731c%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/93eff5788c30398c3013eb7c43ba731c.m3u8"
[...]
frame=60897 fps=291 q=26.0 size=N/A time=00:42:19.86 bitrate=N/A dup=1 drop=0 speed=12.1x    
[hls @ 0x55b7fea72ac0] Opening '/config/data/transcodes/93eff5788c30398c3013eb7c43ba731c845.ts' for writing
[hls @ 0x55b7fea72ac0] Opening '/config/data/transcodes/93eff5788c30398c3013eb7c43ba731c846.ts' for writing
frame=60934 fps=291 q=26.0 Lsize=N/A time=00:42:21.14 bitrate=N/A dup=1 drop=0 speed=12.1x    
video:1471901kB audio:119133kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2022-06-24 11:14
Duplicate of #6957

**Closed by cvium** 2022-06-24 11:14 UTC
Labels: bug
