### ISSUE TITLE
Installing Jellyfin on Fedora 33 complains about missing jellyfin-web missing while already installed

### ISSUE THREAD

**Issue by pascal48** [jellyfin/jellyfin#5013] opened 2021-01-13 03:15 UTC
**Describe the bug**
Jellyfin will not install on Fedora 33 using `dnf install` and complains about the jellyfin-web package missing despite being already installed. 

**System (please complete the following information):**
 - OS: Fedora 33
 - Virtualization: RHEL 8.20 KVM
 - Jellyfin Version: 10.7.0~rc-2-1
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Direct attachment (macvtap)
 - Storage: 20GB vDisk

**To Reproduce**

1. Install RPMFusion for required deps
2. Install jellyfin-web and jellyfin-server RPMs normally from https://repo.jellyfin.org/releases/server/fedora/stable/ using `sudo dnf install <link>`
3. Attempt to install jellyfin-10.7.0
4. See dep error

**Expected behavior**
Jellyfin should be able to install as normal with both jellyfin-web and jellyfin-server RPMs already installed

**Logs**
```
[jakeadmin@localhost ~]$ sudo dnf search jellyfin
[sudo] password for jakeadmin: 
Last metadata expiration check: 0:07:16 ago on Tue 12 Jan 2021 08:54:59 PM CST.

Name Matched: jellyfin

jellyfin-server.x86_64 : The Free Software Media System Server backend
jellyfin-web.noarch : The Free Software Media System web client
[jellyvm@localhost ~]$ sudo dnf install https://repo.jellyfin.org/releases/server/fedora/stable/server/jellyfin-10.7.0~rc2-1.fc33.x86_64.rpm
Last metadata expiration check: 0:07:26 ago on Tue 12 Jan 2021 08:54:59 PM CST.
jellyfin-10.7.0~rc2-1.fc33.x86_64.rpm                                                                                     12 kB/s | 8.3 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides jellyfin-web < 10.7 needed by jellyfin-10.7.0~rc2-1.fc33.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by crobibero** [comment] 2021-01-13 03:22
Duplicate of https://github.com/jellyfin/jellyfin/issues/4938
Will be fixed by https://github.com/jellyfin/jellyfin/pull/4956

**Closed by crobibero** 2021-01-13 03:22 UTC
Labels: bug
