### ISSUE TITLE
[Issue]: [Intermittent] [10.8.1] Libraries are being deleted with Scheduled Scan

### ISSUE THREAD

**Issue by buzzzz2138** [jellyfin/jellyfin#8097] opened 2022-07-10 19:16 UTC
### Please describe your bug

Watch a video this morning everything working, nothing missing.  At 16:39 server time, the logs state the server Executing "Scan Media Library" followed by Stopping watching the directories and then removing the folders and all of the related media. 

The deletes continue until the libraries are gone.

If connection to the respective drives were lost, I would expect the libraries to still remain.  This is all on a local host.  Hard Drives are not networked and contained in the PC, running Debian (Open Media Vault).

Jellyfin 10.8.1
Architecture: X64
Jellyfin is contained in a Docker, showing that Jellyfin has been up for 12 days. 

After I noticed the libraries were gone, I was to add them back without any issues beyond having to Identify several files that always have issues. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization: No
- Clients: Browser/Android
- Browser: Firefox
- FFmpeg Version: Jellyfin
- Playback Method: NA
- Hardware Acceleration: NA
- Plugins: AudioDB, MusicBrainz, OMDB, Playback Reporting, Studio Images, TMDB
- Reverse Proxy: nginx
- Base URL:NA
- Networking:BA
- Storage:NA
```

### Jellyfin logs

```shell
[2022-07-10 16:39:11.763 +00:00] [INF] [111] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Scan Media Library"
[2022-07-10 16:39:11.763 +00:00] [INF] [111] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/TV"
[2022-07-10 16:39:11.765 +00:00] [INF] [111] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/New"
[2022-07-10 16:39:11.765 +00:00] [INF] [111] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/Movies"
[2022-07-10 16:39:11.769 +00:00] [INF] [111] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/Kids"
[2022-07-10 16:39:11.771 +00:00] [INF] [111] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2022-07-10 16:39:11.851 +00:00] [INF] [111] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Folder", Name: "Movies", Path: "/Movies", Id: 0a31dc55-aca1-e560-3b67-b2e61b2788b1
[2022-07-10 16:39:27.804 +00:00] [INF] [111] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Folder", Name: "TV", Path: "/TV", Id: ebea19dd-d1d9-1564-19ba-ab2f5dc55c16
[2022-07-10 16:40:22.298 +00:00] [INF] [111] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Folder", Name: "New", Path: "/New", Id: 3d61f4a2-8be4-7981-73a5-4eb7d98721f2
[2022-07-10 16:40:23.578 +00:00] [ERR] [39] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/config/data/playlists"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/playlists'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2022-07-10 16:40:23.587 +00:00] [INF] [39] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "CollectionFolder", Name: "Movies", Path: "/config/root/default/Movies", Id: f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805
[2022-07-10 16:40:23.598 +00:00] [INF] [39] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "CollectionFolder", Name: "New", Path: "/config/root/default/New", Id: 4c0a7f0b-28ff-6c78-07dc-5a4c212a2e9c
[2022-07-10 16:40:23.604 +00:00] [INF] [39] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "CollectionFolder", Name: "Shows", Path: "/config/root/default/Shows", Id: a656b907-eb3a-7353-2e40-e44b968d0225
[2022-07-10 16:40:23.636 +00:00] [ERR] [15] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/playlists'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
[2022-07-10 16:40:24.905 +00:00] [ERR] [111] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "/config/data/playlists"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data/playlists'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2022-07-10 16:40:31.623 +00:00] [INF] [67] Emby.Server.Implementations.Library.Validators.StudiosValidator: Deleting dead "Studio" "6d086358d3c974758fa5a5ce544ae5eb" "#anime-avatar @ irc.rizon.net"
```

### FFmpeg logs

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buzzzz2138** [comment] 2022-07-10 19:17
This does not occur with every Scan.

**Comment by flaminestone** [comment] 2022-07-14 13:57
Same problem. I lost all my media files, music and films. But empty folders is not deleted.
Version: 10.7.7
Virtualization: docker

My logs are the same as for @buzzzz2138 

```
[08:14:31] [INF] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
```
Then:
```
[19:18:16] [ERR] [10] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /media/Music/Metric
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Music/Metric'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.GetFileSystemChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken
```
Then:

```
[19:18:22] [ERR] [11] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for /media/Music/Radiohead/2007 - In Rainbows (CDS X X001J)
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Music/Radiohead/2007 - In Rainbows (CDS X X001J)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[19:18:23] [ERR] [5] MediaBrowser.Providers.Music.AlbumMetadataService: Error in TheAudioDB
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'RootObject', got string starting with: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
   at ServiceStack.Text.Common.DeserializeType`1.StringToTypeContext.DeserializeJson(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeType.cs:line 58
   at ServiceStack.Text.Json.JsonReader.<>c__DisplayClass3_0.<GetParseSpanFn>b__0(ReadOnlySpan`1 v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Json\JsonReader.Generic.cs:line 20
   at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
   at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 179
   at ServiceStack.Memory.NetCoreMemory.Deserialize(Stream stream, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 151
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromStream[T](Stream stream)
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
   at MediaBrowser.Providers.Plugins.AudioDb.AudioDbAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[19:18:23] [ERR] [10] MediaBrowser.Providers.Music.AlbumMetadataService: Error in TheAudioDB
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'RootObject', got string starting with: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
   at ServiceStack.Text.Common.DeserializeType`1.StringToTypeContext.DeserializeJson(ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeType.cs:line 58
   at ServiceStack.Text.Json.JsonReader.<>c__DisplayClass3_0.<GetParseSpanFn>b__0(ReadOnlySpan`1 v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Json\JsonReader.Generic.cs:line 20
   at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
   at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 179
   at ServiceStack.Memory.NetCoreMemory.Deserialize(Stream stream, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 151
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromStream[T](Stream stream)
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromFile[T](String file)
   at MediaBrowser.Providers.Plugins.AudioDb.AudioDbAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[19:18:24] [INF] [10] Emby.Drawing.ImageProcessor: Creating image collage and saving to /cache/temp/e08bde9dbff949e18266a050ff2c6371.png
[19:18:24] [INF] [10] Emby.Drawing.ImageProcessor: Completed creation of image collage and saved to /cache/temp/e08bde9dbff949e18266a050ff2c6371.png
[19:18:24] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 10 seconds
[19:18:24] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[19:18:25] [INF] [5] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Download
[19:18:25] [INF] [11] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media/Music
[19:28:31] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Clean Transcode Directory
[19:28:31] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task DeleteTranscodeFileTask
[19:28:31] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Clean Transcode Directory
[19:28:31] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Transcode Directory Completed after 0 minute(s) and 0 seconds
[19:28:31] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[19:28:32] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Download missing subtitles
[19:28:32] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task SubtitleScheduledTask
[19:28:32] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Download missing subtitles
[19:28:32] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Download missing subtitles Completed after 0 minute(s) and 0 seconds
[19:28:32] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[19:28:36] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Clean Log Directory
[19:28:36] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task DeleteLogFileTask
[19:28:36] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Clean Log Directory
[19:28:36] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Log Directory Completed after 0 minute(s) and 0 seconds
[19:28:36] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[19:28:37] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: TasksRefreshChannels
[19:28:37] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task RefreshChannelsScheduledTask
[19:28:37] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing TasksRefreshChannels
[19:28:37] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: TasksRefreshChannels Completed after 0 minute(s) and 0 seconds
[19:28:37] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[19:28:54] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Clean Cache Directory
[19:28:54] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task DeleteCacheFileTask
[19:28:54] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Clean Cache Directory
[19:28:54] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean Cache Directory Completed after 0 minute(s) and 0 seconds
[19:28:54] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[20:28:39] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Refresh Guide
[20:28:39] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task RefreshChannelsScheduledTask
[20:28:39] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Refresh Guide
[20:28:42] [INF] [20] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[20:28:42] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Refresh Guide Completed after 0 minute(s) and 3 seconds
[20:28:42] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[23:03:24] [INF] [19] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[23:03:24] [INF] [19] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[23:03:24] [INF] [19] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[01:59:59] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: DailyTrigger fired for task: Extract Chapter Images
[01:59:59] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task ChapterImagesTask
[01:59:59] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Extract Chapter Images
[02:00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Extract Chapter Images Completed after 0 minute(s) and 0 seconds
[02:00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[02:00:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 07/15/2022 02:00, which is 23:59:59.0031155 from now.
[03:03:24] [INF] [22] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[03:03:24] [INF] [22] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[03:03:24] [INF] [22] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[07:03:24] [INF] [5] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[07:03:24] [INF] [5] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[07:03:24] [INF] [5] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[07:18:14] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: IntervalTrigger fired for task: Scan Media Library
[07:18:14] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task RefreshMediaLibraryTask
[07:18:14] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
[07:18:14] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /media/Music
[07:18:14] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /media/Download
[07:18:14] [INF] [19] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[07:18:14] [INF] [18] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Betmen.Pattinson, Path: /media/Download/Betmen.Pattinson.2022.WEB-DLRip.feo.avi, Id: 3c6ae051-9cbd-6e33-bbdb-e786c93f0c66
[07:18:14] [INF] [23] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: MusicArtist, Name: Placebo, Path: /media/Music/Placebo, Id: 07c434ab-614a-1a93-c361-ef55a99429ff
...
```
Removing item for every media file

**Comment by Bond-009** [comment] 2022-07-18 22:14
Duplicate of #1714

**Closed by Bond-009** 2022-07-18 22:14 UTC
Labels: bug

**Comment by buzzzz2138** [comment] 2022-08-15 14:24
I don't know if this is related to #1714
I have 4 total libraries and 3 of them are on the same hard drive.   If the drive disconnected it should be all or none.  

Just today I had one library disappear.  The other ones on the same HDD stayed.
