### ISSUE TITLE
Can't select VAAPI on fresh install

### ISSUE THREAD

**Issue by Terror-Gene** [jellyfin/jellyfin#2732] opened 2020-04-01 15:30 UTC
**Describe the bug**
When Selecting VAAPI on a fresh install (with no prior config folder), I receive the message:
`There was an error processing the request. Please try again later.`
Manually making a `transcodes` folder in `/config/data/` resolves the issue.

**System:**
 - OS: Unraid
 - Virtualization: Docker (linuxserver/jellyfin)
 - Jellyfin Version: 10.5.2

**Expected behavior**
Default Transcodes folder would already exist or would be created when the page is saved.

**Logs**
`[01:39:25] [ERR] [7] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: /config/data/transcodes does not exist.`

**Comment by JustAMan** [comment] 2020-04-04 22:58
Duplicate of https://github.com/jellyfin/jellyfin/issues/2677

**Closed by JustAMan** 2020-04-04 22:58 UTC
Labels: bug
