### ISSUE TITLE
[Issue]: Allow tag still not working? (broken fix: #11377)

### ISSUE THREAD

**Issue by MustThinkOfAName** [jellyfin/jellyfin#11407] opened 2024-04-22 17:45 UTC
### Please describe your bug

First of all, thank you @gnattu for your work on this issue! 

I hope that I simply did something wrong and that everything indeed works as intended. But at least on my end the `Allow items with tags` feature is still broken.

In my current example, I've applied the allow filter for spy (which I have 6 shows matching). Everything seems to work properly on the homepage. `Continue watching` and `Next up` only show titles matching the tag.
![Screenshot from 2024-04-22 19-23-34](https://github.com/jellyfin/jellyfin/assets/60283063/debfca4e-7ae9-4483-a8b6-7ec99b10a97f)

As you can on the `My media` page, the list is empty. It does show on the top that 6 shows should be listed.
![Screenshot from 2024-04-22 19-22-49](https://github.com/jellyfin/jellyfin/assets/60283063/2faa38cb-413c-436e-b484-7aa3829e3d14)

I had already started an episode before applying the filter, hence the `Continue watching` section showing something. When I try clicking on the continue to play button. I have a loading animation that never goes away.

### Reproduction Steps

1. On the unstable branch running the latest [2024042215](https://hub.docker.com/layers/jellyfin/jellyfin/2024042215/images/sha256-82e6b91e46c34d56d32ecb992db99e8faca79a60536d7ed8c38def04b5858ece?context=explore) build.
2. With one user having some tags applied to them in the Allow items with tag set
3.  Try opening the media library or to click on continue playing
4. See no titles/a loading spinner that won't go away

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Synology DSM 7
- Linux Kernel: /
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox 123.0.1 & Chrome 124.0.6367.60
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Default
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2024-04-22 17:34:38.449 +00:00] [INF] [70] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:34:38.744 +00:00] [INF] [50] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:34:39.269 +00:00] [INF] [50] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:34:45.930 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:34:46.338 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:34:48.729 +00:00] [INF] [70] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:34:49.088 +00:00] [INF] [69] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:35:01.418 +00:00] [INF] [69] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:35:02.193 +00:00] [INF] [65] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:36:23.065 +00:00] [INF] [64] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:36:24.775 +00:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
[2024-04-22 17:36:39.060 +00:00] [INF] [64] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" closed
[2024-04-22 17:36:39.902 +00:00] [INF] [15] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "2a01:2a01:xxxxxxxxxxxxxx" request
```

### Please attach any browser or client logs here

![Screenshot from 2024-04-22 19-44-36](https://github.com/jellyfin/jellyfin/assets/60283063/61b470c3-aac0-4de7-8657-ebacf973c4ef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment] 2024-04-22 18:19
Shows won’t inherit tags from Genres and you will need to apply tags to each of the shows.

This is currently a design limitation as the tags will only be inherited from the direct parents. Like episodes inherits tags from shows.

**Comment by MustThinkOfAName** [comment] 2024-04-22 18:33
I've tried adding a custom tag to the show (testTag)

![Screenshot from 2024-04-22 20-23-31](https://github.com/jellyfin/jellyfin/assets/60283063/45f33269-b76a-493f-b436-1a0b1c6eee68)
![Screenshot from 2024-04-22 20-23-42](https://github.com/jellyfin/jellyfin/assets/60283063/06bbf899-bdcd-4167-a7b2-88a14f39f3de)
![Screenshot from 2024-04-22 20-23-53](https://github.com/jellyfin/jellyfin/assets/60283063/1da98831-821f-4d74-9df0-4547baa89bf2)

As you can see here, I have the same issue. 

I also tried adding the testTag to a movie.  This time the movie shows in my media list but clicking on it gives me the same spinning animation as well as an error
![Screenshot from 2024-04-22 20-28-04](https://github.com/jellyfin/jellyfin/assets/60283063/5a46710e-fdf3-4cf4-8761-b67996bc3bcc)
![Screenshot from 2024-04-22 20-28-15](https://github.com/jellyfin/jellyfin/assets/60283063/e5bc6cc0-9629-4089-a122-741d8216c23f)
![Screenshot from 2024-04-22 20-29-59](https://github.com/jellyfin/jellyfin/assets/60283063/906b0f43-acf5-4bf9-b4dc-c413b67a4305)

The logs server side are not more precise than the ones I have already posted (I assume the Uncaught promise is never returned and therefore the ws request is never closed?)

**Comment by gnattu** [comment] 2024-04-23 07:50
I've posted another proposed fix for this rather complicated situation. 

The problem is much more complicated than I previously anticipated and actually requires modification to the way data is queried from the databases. I have no idea why the blacklist is working with current settings and nobody reports bugs, but at least current handling is not good enough for whitelists.

**Closed** 2024-04-30 19:32 UTC
Labels: bug
