### ISSUE TITLE
Not showing subtitles when playing video on web or android app

### ISSUE THREAD

**Issue by mgcwolf** [jellyfin/jellyfin#2632] opened 2020-03-20 12:21 UTC
LOG:

[2020-03-20 11:59:30.772 +00:00] [WRN] HTTP Response 204 to "101.84.206.73". Time (slow): 0:00:00.5192406. "http://xxxxx:8096/Sessions/Playing/Progress"
[2020-03-20 11:59:31.164 +00:00] [WRN] Killing ffmpeg subtitle extraction process
[2020-03-20 11:59:31.255 +00:00] [WRN] Deleting extracted subtitle due to failure: "/var/lib/jellyfin/data/subtitles/c/c3c647c8-c50c-feab-30fe-f01027ae043f.srt"
[2020-03-20 11:59:31.301 +00:00] [ERR] ffmpeg subtitle extraction failed for file:"/mnt/nas-tv/Westworld/Season 3/Westworld.S03E01.Parce.Domine.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv" to /var/lib/jellyfin/data/subtitles/c/c3c647c8-c50c-feab-30fe-f01027ae043f.srt
[2020-03-20 11:59:31.440 +00:00] [ERR] Error processing request
System.Exception: ffmpeg subtitle extraction failed for file:"/mnt/nas-tv/Westworld/Season 3/Westworld.S03E01.Parce.Domine.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv" to /var/lib/jellyfin/data/subtitles/c/c3c647c8-c50c-feab-30fe-f01027ae043f.srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitleInternal(String inputPath, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractTextSubtitle(String[] inputFiles, MediaProtocol protocol, Int32 subtitleStreamIndex, String outputCodec, String outputPath, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetReadableFile(String mediaPath, String[] inputFiles, MediaProtocol protocol, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.GetSubtitleStream(MediaSourceInfo mediaSource, MediaStream subtitleStream, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by Artiume** [comment] 2020-03-20 13:08
Duplicate of https://github.com/jellyfin/jellyfin/issues/2525

Fix will be in next release

**Closed** 2020-03-20 14:38 UTC
