### ISSUE TITLE
Chromecast broken on 10.7.0-rc2

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#4918] opened 2021-01-01 18:13 UTC
**Describe the bug**
Unable to get Chromecast working on 10.7.0-rc2. I can connect fine, but when I start any playback it errors out with "MessageChromecastConnectionError". If I roll back to 10.6.4 it works fine again. It's the same on both Chrome browser and the Android app.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Android, Browser
 - Browser: Chrome 89.0.4356
 - Jellyfin 10.7.0-rc2
 - Reverse Proxy: nginx (letsencrypt cert)
 - Base URL: none
 - Networking: Bridge

**To Reproduce**
1. Update to 10.7.0-rc2
2. Connect to chromecast device
3. Start playback
4. MessageChromecastConnectionError gets thrown

**Expected behavior**
Playback starting

**Logs**
No error is logged.

**Comment by krutburken** [comment] 2021-01-01 19:39
Probably the same as https://github.com/jellyfin/jellyfin/issues/4616

**Comment by SigHunter** [comment] 2021-01-02 16:14
I have the same problem

**Comment by itsyoshio** [comment] 2021-01-03 22:46
+1

**Comment by caiusseverus** [comment] 2021-01-04 01:06
I also see this with RC2. The only difference with OP is I'm not using docker, but native install on Ubuntu 20.04. Server is behind nginx with domain name and certificate set up OK. It was working OK with 10.6.4.

**Comment by SteveDinn** [comment] 2021-01-04 02:12
I see this issue with 10.7 rc2 as well, but only with my Chromecast ultra. On my Chromecast with Google TV, the same content plays well when casted from the app.

**Comment by krutburken** [comment] 2021-01-04 11:34
If I change the networking type to host, it starts working in the browser. The Android app is still broken but it may not be updated with 10.7.0 support (?)

I guess the problem is that Jellyfin reports the docker IP instead of the host address, but unfortunately the setting to override the address does nothing.

What are the recommended settings to get this working on 10.7.0?

**Comment by nielsvanvelzen** [comment] 2021-01-04 12:05
> The Android app is still broken but it may not be updated with 10.7.0 support (?) The version is 2.2.3.

Version 2.2.3 of the Android app should work with 10.7. Please report any issues to the /jellyfin/jellyfin-android repositories so we can look into it.

**Comment by SigHunter** [comment] 2021-01-04 12:39
> 
> 
> I also see this with RC2. The only difference with OP is I'm not using docker, but native install on Ubuntu 20.04. Server is behind nginx with domain name and certificate set up OK. It was working OK with 10.6.4.

I'm also not using docker but a native windows install and I have this problem. Caddy reverse proxy, lets encrypt cert, working with 10.6.4 out of the box, does not with 10.7

**Comment by krutburken** [comment] 2021-01-04 12:56
> Version 2.2.3 of the Android app should work with 10.7. Please report any issues to the /jellyfin/jellyfin-android repositories so we can look into it.

Sure, though I'd like to get the 10.7.0 server working as intended first to rule out other issues. I _think_ the problem with the Android app is that it doesn't load the Unstable Chromecast client even when it's selected (it displays a very different UI when Unstable is used on Chrome. No change when using the app)

The browser only works when using Unstable, regardless of network type.

**Comment by SteveDinn** [comment] 2021-01-04 14:24
> > The Android app is still broken but it may not be updated with 10.7.0 support (?) The version is 2.2.3.
> 
> Version 2.2.3 of the Android app should work with 10.7. Please report any issues to the /jellyfin/jellyfin-android repositories so we can look into it.

I was using v2.2.3 & 10.7.0 RC2 when I commented previously.

**Comment by krutburken** [comment] 2021-01-04 15:58
For the others having similar issues. I managed to get it working using a bridged network.

set "LAN networks" to what you're using (I'm running 192.168.1.0/16).
set "Published Server URIs" to the external ip:port of the host running the service. Syntax: "external=http://192.168.1.100:8096"
Save settings.
Make sure /System/info/public is showing the correct LocalAddress you set above.
Restart service.

Still only the Unstable client that works though. I guess I'll make an issue for that.

**Comment by crobibero** [comment] 2021-01-09 15:04
https://github.com/jellyfin/jellyfin-chromecast/issues/113

**Comment by dza89** [comment] 2021-01-10 19:11
> For the others having similar issues. I managed to get it working using a bridged network.
> 
> set "LAN networks" to what you're using (I set it to 192.168.1.0/24).
> set "Published Server URIs" to the external ip:port of the host running the service. Syntax: "external=http://192.168.1.100:8096"
> Save settings.
> Make sure /System/info/public is showing the correct LocalAddress you set above.
> Restart service.
> 
> The unstable client works reliably in Chrome now, but playback from the android app is still broken. I guess I'll make an issue for that.

Thanks alot, this also works with full urls. Just didn't know you had to put external= into the box.

**Comment by krutburken** [comment] 2021-01-11 09:05
> Thanks alot, this also works with full urls. Just didn't know you had to put external= into the box.

No problem. This setting seems to be undocumented as of now. I randomly found the syntax in a google search. I'm honestly not sure what is the correct way to do it still, I only tried to duplicate what a host network looks like externally and it seems to work.

**Comment by hawken93** [comment] 2021-01-13 20:15
From my reading of this, the main complaint seems to be that the android app doesn't behave well? It runs jellyfin 10.6 and thus has the 10.6 problem (curl -fs `http://myserver/System/Info/Public` to see what it really tries to connect to, keep in mind chromecast doesn't do self-signed ssl or local-only DNS records without workaround. In 10.7 you are getting more control of this field, so you can work around this.),

In addition I think the stable chromecast version probably breaks with 10.7 I think because it asks for /mediabrowser URLs, check your server logs and see if it asks for things that aren't there. If jellyfin wants to keep stable working then those URLs must be reinstated, but nightly is not far away from becoming more useful.

**Comment by caiusseverus** [comment] 2021-01-13 21:26
There's two issues I think - the android app is misbehaving by requesting the stable chromecast version, even if nightly is selected in the use profile. I can see this in the reverse proxy logs. I have the /System/Info/Public set up so that it correctly shows the internal IP address on the local LAN, and the external URL (which is properly set up with SSL certificate) when accessing remotely.

I am unable to play to chromecast using chrome browser on PC however - that is correctly requesting the nightly chromecast version, however no transcoding starts and there is no playback on the device.

**Comment by dza89** [comment] 2021-01-13 21:41
I'm running the latest nightly, with Jellyfixer (custom /System/Info/Public) on the side

- Casting from browser is working
- Casting from the Android app is working half of the time (sometimes a Chromecast couldn't get connection to server)

I'm seeing other issues with chromecast but if this works for me, then others should get it to works as well.

**Comment by hawken93** [comment] 2021-01-16 21:34
Android app seems to have an ongoing issue where it will only start stable, which was broken.

Now I have gotten some small fixes in to the stable receiver, just to keep it working on 10.7 and therefore it should work, but we still have some work left to do, to be able to try the new one from android.

**Comment by hawken93** [comment] 2021-01-16 21:40
Android only uses stable receiver: https://github.com/jellyfin/jellyfin-android/issues/281

Stable receiver fixed for 10.7 in: https://github.com/jellyfin/jellyfin-android/issues/281

Please re-test and I think for those who still have problems, see if it can be this: https://github.com/jellyfin/jellyfin-chromecast/issues/113

**Comment by krutburken** [comment] 2021-01-17 14:31
Can confirm Stable reciever on Android now works on 10.7.0 (Unstable)

**Comment by caiusseverus** [comment] 2021-01-17 17:49
I have casting now works when initiated from Android with stable chromecast.

It does not work if initiating from Chrome browser on PC however - the connection is made and Jellyfin starts on the chromecast, but playback/transcoding never begins.

**Comment by krutburken** [comment] 2021-01-17 19:22
Works on both Browser and Android app on my setup. Stable is admittedly slightly slower on starting playback than unstable though.

**Comment by hawken93** [comment] 2021-01-18 18:01
> I have casting now working when initiated from Android with stable chromecast.
> 
> It does not work if initiating from Chrome browser on PC however - the connection is made and Jellyfin starts on the chromecast, but playback/transcoding never begins.

Are you connecting your browser to localhost to get this to work?

**Comment by caiusseverus** [comment] 2021-01-18 19:18
No. I'm connecting my browser to the domain name that is set up for my server, which is on a separate machine.

**Comment by rsg73** [comment] 2021-05-26 16:57
I have the same problem as @caiusseverus after updating to 10.7.5 from 10.6.4 on a Windows 10 machine.  I can cast from an Android with no problems.  However, when I attempt to cast from my PC to the Chromecast using Chrome, Jellyfin is able to make the connection (the Jellyfin logo appears on the TV screen), but then I get a message that says the Chromecast cannot connect to the server, which is obviously not true (Android working).  Anyhow, after poking around for a couple of hours and trying various tweaks, the only way I could get the stream to work from my PC was to connect to the server using the IP address of the server, and then cast the TAB from the Chrome options menu  instead of selecting the cast icon provided in the Jellyfin screen - and this ONLY worked when connected to the server via the IP address of the server.  If I used "localhost" or 127.0.0.1, no dice - just the same message as before.

I have since downgraded to 10.6.4 and the problem went away.

**Comment by eyJhb** [comment] 2021-08-14 23:37
I can hopefully cast some light on this.
From version 10.6.x to 10.7.x, the way `ServerAddress` was passed to the Chromecast has changed.
Previously it used the IP Jellyfin was bound on, ie. `192.168.1.11`, even if you visited the site using `jellyfin.mydomain.dk`, which worked fine for LAN networks.
In 10.7.x, it will use the domain you visit, to pass onto the Chromecast, ie `jellyfin.mydomain.dk`, which can yield a wide range of issues.

Here is what I have done, to ensure that my Chromecast works.

1. Ensure you are running the GPlay version of Jellyfin (OR use tho Chrome browser for Android/PC).
2. Ensure that your Jellyfin instance runs on HTTPS, otherwise the cast button will not show (not self signed, as this allows Jellyfin to connect to the Chromecast, but it won't play any media)
3. Ensure that the domain named used for your Jellyfin instance is reachable (keep in mind Chromecast DNS servers are hardcoded to 8.8.8.8 and 8.8.4.4, so using split DNS won't work)
3.1 You can make Chromecast use your local DNS by blocking 8.8.8.8 and 8.8.4.4
3.2 If you don't block it, you have to setup propper DNAT for your host, so that the external IP your domain resolves to, can be used from LAN

This is basically what I have done. My issue was mainly the split DNS, and 10.6.x using my LAN IP `192.168.1.11`, which the new version does not.

Do NOT use stuff such as "localhost", "127.0.0.1", as that will be the ServerAddress sent to the Chromecast, and will not work.

Also, if using a reverse proxy, you could try to circumvent and run Jellyfin without it for initial testing. 

My nginx config, if anyone is interested is the following (somewhat).

```
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name jellyfin.myserver.dk ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/jellyfin.myserver.dk/fullchain.pem;
		ssl_certificate_key /var/lib/acme/jellyfin.myserver.dk/key.pem;
		ssl_trusted_certificate /var/lib/acme/jellyfin.myserver.dk/chain.pem;
		location / {
			proxy_pass http://localhost:8096;
			include /nix/store/01yrl5vx38pd0i442gkla1hnid7lv7j1-nginx-recommended-proxy-headers.conf;
		}
		location /socket {
			proxy_pass http://localhost:8096;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
			include /nix/store/01yrl5vx38pd0i442gkla1hnid7lv7j1-nginx-recommended-proxy-headers.conf;
		}
	}

// proxy-headers.conf
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;
proxy_set_header        X-Forwarded-Host $host;
proxy_set_header        X-Forwarded-Server $host;
```

Not sure if this helps anybody. I have been on 10.6.x for a long time, just because I had this issue.

**Comment by srcrist** [comment] 2023-10-19 19:16
Closing issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/4616.

**Closed by srcrist** 2023-10-19 19:16 UTC
Labels: bug
