### ISSUE TITLE
[bug] metadata parsing incorrectly splitting artists with slash ("/") in name

### ISSUE THREAD

**Issue by williamentropy** [jellyfin/jellyfin#3813] opened 2020-08-03 22:24 UTC
**description:**

bands like "C/A/T" or "De/Vision" are split at the slash character and each segment is added as a separate artist.

in the metadata editor, "/" has been replaced with ";". on the recommendation from a reddit user, i re-tagged these files with picard in case the musicbrainz tag would override the string slicing - but it does not. in all cases, the initial ID3 tag contained the correct relevant information; in my test folders, picard added musicbrainz IDs to the existing files.

i went into the metadata editor and manually replaced ";" back to "/" but it only fixes the track tagging - the higher level album-artist, artist, and library metadata are not updated. in this example, the library contains 3 artists "A", "C", and "T" that all contain the same content.

related: note the album artist displays an alpha-sorted version of the artist array.

**system:**

- os: synology
- virtualization: docker
- clients: browser, gelli
- jellyfin version: 10.6.1
- playback: direct
- installed plug-ins: none
- networking: host
- storage: local

**expected behavior:**

artist name (and album-artist) display correctly (either initially or after override by metadata editor)

**screenshots:**

after initial library load:

![screen--cat-01](https://user-images.githubusercontent.com/13421792/89232052-72bf2c80-d59b-11ea-9040-28bbb8ac8db6.jpg)

post-picard and manual metadata editor "override":

![screen--cat-02](https://user-images.githubusercontent.com/13421792/89232108-96827280-d59b-11ea-8333-086284d418b5.jpg)

**Comment by Bond-009** [comment] 2020-09-03 09:55
Duplicate of #2305

**Closed by Bond-009** 2020-09-03 09:55 UTC
