### ISSUE TITLE
Enable Web Links for Image Paths in NFO Files and Prevent Jellyfin from Overwriting Them

### ISSUE THREAD

**Issue by Isaiasgamedev** [jellyfin/jellyfin#13123] opened 2024-11-29 08:13 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I'm trying to change the image links in the NFO files to web links to reduce the number of requests made to my server. I’d like to know if this is possible and if there’s a way to prevent Jellyfin from updating the NFO files on Linux. I have modified the files multiple times, but whenever I add new content, the NFO files get updated again.

Yes, I have ensured that the folder is not set to update in real-time, and I’ve also gone through each item individually to disable metadata updates. I believe it's important not to host everything locally; otherwise, every request has to go through the server. For a small server, this might not be an issue, but mine has over 300,000 pieces of content, resulting in a large number of simultaneous requests.

Is there a way to make this configuration permanent and prevent Jellyfin from overwriting the NFO files?

### Reproduction steps

Reproduction Steps
Locate and edit an existing NFO file generated by Jellyfin.

Replace the local image paths (e.g., file:///path/to/image.jpg) with web links (e.g., https://example.com/image.jpg).
Save the modified NFO file and confirm the changes are applied.

Ensure that:

The folder containing the media is set to not update in real-time.
Each item in the library has the metadata update option disabled.
Add a new media item to the same folder or library on the Jellyfin server.

Allow Jellyfin to scan for new content automatically or trigger a manual scan for the library.

Open the previously edited NFO file and verify if the web links were replaced with local paths again.

### What is the current _bug_ behavior?

Actual Result:
The NFO file is updated by Jellyfin, reverting the image links back to local paths.

### What is the expected _correct_ behavior?

Expected Result:
The NFO file retains the web links for images as originally modified.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0+

### Environment

```markdown
OS: Lubuntu 22.04 (ou versão instalada no sistema)
Linux Kernel: 5.15 (ou use uname -r para confirmar)
Virtualization: none
Clients: Browser, Android (substitua se necessário)
Browser: Chrome 93 (ou versão instalada)
FFmpeg Version: [e.g. 5.1.2-Jellyfin]
Playback Method: Direct Play
Hardware Acceleration: none
GPU Model: Intel UHD Graphics 630
Plugins: none (ou adicione plugins instalados, como Fanart)
Reverse Proxy: none
Base URL: none
Networking: Host
Storage: local
```

### Jellyfin logs

```shell
ERR] [46] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode 3x23 not found for series 447975:Os Feiticeiros Além de Waverly Place
[05:10:20] [ERR] [46] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Episode S03E24 not found for series 0:Os Feiticeiros de Waverly Place S03E24 (1)
[05:10:21] [ERR] [9] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode 3x24 not found for series 447975:Os Feiticeiros Além de Waverly Place
[05:10:21] [ERR] [23] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Episode S03E24 not found for series 0:Os Feiticeiros de Waverly Place S03E24
[05:10:21] [ERR] [23] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode 3x24 not found for series 447975:Os Feiticeiros Além de Waverly Place
[05:10:22] [ERR] [99] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Episode S03E25 not found for series 0:Os Feiticeiros de Waverly Place S03E25 (1)
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment] 2024-12-03 23:41
This is 2 things in one report:
- The NFO saver overwriting changes made to the NFO is working as intended.
- Allowing web image links for NFOs is a feature request and should be submitted to https://features.jellyfin.org

Closing this issue as it does not contain an actual bug.

**Closed by felix920506** 2024-12-03 23:41 UTC
Labels: bug
