### ISSUE TITLE
[Issue]: SyncPlay Always crashes in 10.9.1

### ISSUE THREAD

**Issue by ctessler** [jellyfin/jellyfin#11635] opened 2024-05-14 15:35 UTC
### Please describe your bug

With the upgrade to 10.9.0, SyncPlay is broken. I use the feature on the local network to play movies on multiple devices in different roams.  I also use the feature to watch movies with friends over the VPN. 

In both scenarios, SyncPlay is completely broken. There are multiple failure scenarios, in the best case starting a video will play for 15 seconds to one minute and then one of the clients will crash -- closing the browser window.  In the more common scenarios, just pressing play on one client will crash at least one other.

In the attached logs there two users doc and test attempt to watch a show "Grotesque" which  crashes after roughly 30 seconds. From the logs, Jellyfin appears to send a 'q' to the transcoder, but the log message does not indicate why.

### Reproduction Steps

Common Steps
1. In a browser, have the user Bob create a group
2. In a separate browser, have the user Alice join the group

Scenario 1, will reproduce 100% of the time upon passing step 4:
3. Begin playing a video
4. Video begins playing for 15 seconds to one minute 
5. Observe a crash in Alice or Bob's client 

Scenario 2, will not reproduce 100% of the time:
3. Select a video
4. Have Bob jump forward to any timestamp in the video
5. Observe a crash in Alice or Bob's client (this is not 100% reproducible)

Scenario 3, will reproduce 100% of the time upon passing step 4:
3. Begin playing a video
4. Have Alice jump forward to any timestamp in the video
5. Observe a crash in Alice or Bob's client 

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Virtualization
- Linux Kernel: 6.6.20 (TrueNAS)
- Virtualization: Docker/Kubernetes
- Clients: Browser
- Browser: Firefox 115.10.0esr
- FFmpeg Version: Unsure how to check
- Playback Method: Transcode
- Hardware Acceleration: None and VAAPI
- GPU Model: AMD Radeon Pro W7600
- Plugins: DLNA
- Reverse Proxy: None
- Base URL: http://jellyfin:8096
- Networking: NAT
- Storage: Local
```

### Jellyfin logs

```shell
[2024-05-14 15:29:59.082 +00:00] [INF] [88] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-05-14 15:29:59.083 +00:00] [INF] [88] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska,webm -noautorotate -i file:\"/mnt/video/series/the_x-files/s03/the_x-files_s03e14.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 7176300 -bufsize 14352600 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 \"expr:gte(t,n_forced*3)\" -sc_threshold:v:0 0 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1920\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1920/a\,1080))/2)*2,format=yuv420p\" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=3\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"80ee76791f9a644b9d51e78246aa411f-1.mp4\" -start_number 0 -hls_segment_filename \"/config/transcodes/80ee76791f9a644b9d51e78246aa411f%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/config/transcodes/80ee76791f9a644b9d51e78246aa411f.m3u8\""
[2024-05-14 15:30:01.388 +00:00] [INF] [83] Emby.Server.Implementations.SyncPlay.Group: Session "d932f84505d15bf4d2148226742998b9" joined group "27241657-5559-4830-8ef9-7f8833b8f2cd".
[2024-05-14 15:30:01.671 +00:00] [INF] [88] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "test". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-05-14 15:30:01.970 +00:00] [INF] [93] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-05-14 15:30:01.971 +00:00] [INF] [93] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska,webm -noautorotate -i file:\"/mnt/video/series/the_x-files/s03/the_x-files_s03e14.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 7176300 -bufsize 14352600 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 \"expr:gte(t,n_forced*3)\" -sc_threshold:v:0 0 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1920\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1920/a\,1080))/2)*2,format=yuv420p\" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=3\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"cf91f001c00c3a2b5c580e3ed052df6f-1.mp4\" -start_number 0 -hls_segment_filename \"/config/transcodes/cf91f001c00c3a2b5c580e3ed052df6f%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/config/transcodes/cf91f001c00c3a2b5c580e3ed052df6f.m3u8\""
[2024-05-14 15:30:30.413 +00:00] [INF] [99] Emby.Server.Implementations.SyncPlay.Group: Session "ddf4a16bd1123f55503072e98fc840e5" requested IgnoreWait in group "27241657-5559-4830-8ef9-7f8833b8f2cd" that is Waiting.
[2024-05-14 15:30:30.416 +00:00] [INF] [99] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/config/transcodes/80ee76791f9a644b9d51e78246aa411f.m3u8"
[2024-05-14 15:30:30.592 +00:00] [INF] [99] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-05-14 15:30:30.593 +00:00] [INF] [99] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/transcodes/80ee76791f9a644b9d51e78246aa411f.m3u8"
[2024-05-14 15:30:32.101 +00:00] [INF] [90] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.1" playing "Grotesque". Stopped at "30093" ms
[2024-05-14 15:30:33.562 +00:00] [INF] [99] Emby.Server.Implementations.SyncPlay.Group: Session "d932f84505d15bf4d2148226742998b9" requested Unpause in group "27241657-5559-4830-8ef9-7f8833b8f2cd" that is Waiting.
[2024-05-14 15:30:33.562 +00:00] [INF] [99] Emby.Server.Implementations.SyncPlay.Group: Group "27241657-5559-4830-8ef9-7f8833b8f2cd" switching from Waiting to Playing.
[2024-05-14 15:30:33.608 +00:00] [INF] [90] Emby.Server.Implementations.SyncPlay.Group: Session "d932f84505d15bf4d2148226742998b9" requested Ready in group "27241657-5559-4830-8ef9-7f8833b8f2cd" that is Playing.
[2024-05-14 15:30:34.939 +00:00] [INF] [97] Emby.Server.Implementations.SyncPlay.Group: Session "d932f84505d15bf4d2148226742998b9" requested IgnoreWait in group "27241657-5559-4830-8ef9-7f8833b8f2cd" that is Playing.
[2024-05-14 15:30:34.941 +00:00] [INF] [99] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/config/transcodes/cf91f001c00c3a2b5c580e3ed052df6f.m3u8"
[2024-05-14 15:30:35.080 +00:00] [INF] [99] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-05-14 15:30:35.080 +00:00] [INF] [99] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/transcodes/cf91f001c00c3a2b5c580e3ed052df6f.m3u8"
[2024-05-14 15:30:36.588 +00:00] [INF] [100] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.1" playing "Grotesque". Stopped at "1051" ms
[2024-05-14 15:30:50.399 +00:00] [INF] [99] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.0.1.142" closed
[2024-05-14 15:30:50.791 +00:00] [INF] [100] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.0.1.142" request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment] 2024-05-14 15:58
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5485

**Closed by thornbill** 2024-05-14 15:58 UTC
Labels: bug, syncplay
