### ISSUE TITLE
Refresh stuck at 15%

### ISSUE THREAD

**Issue by gllyrjones** [jellyfin/jellyfin#2561] opened 2020-03-09 22:37 UTC
**Describe the bug**
Xmltv refresh is stuck at 15% on 10.5.  
If I remove the Hdhomerun device then the refresh is successful. But adding it back its stuck again. 

It works fine when roll back to 10.4.3. 

**System (please complete the following information):**
 - OS Ubuntu 18
 - Virtualization: docker (jellyfin) 
 
 - Jellyfin Version: [10.5]
 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: apache
Using HDHomerun

**Logs**
21:29:52] [ERR] Could not find handler for /socket

[21:29:52] [ERR] Error processing request: Unable to find the specified file.

[21:29:53] [INF] xmltv path: http://www.xmltv.co.uk/feed/6743

[21:29:59] [INF] xmltv path: http://www.xmltv.co.uk/feed/6743

[21:30:00] [INF] xmltv path: http://www.xmltv.co.uk/feed/6743

[21:34:15] [ERR] Could not find handler for /socket

[21:34:15] [ERR] Error processing request: Unable to find the specified file.

[21:34:21] [WRN] HTTP Response 200 to 213.205.242.156. Time (slow): 0:00:01.3755263. http://192.168.1.197:8096/LiveTv/Recordings?UserId=d76c0428004e4c09a10b816937e3ff9d&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop

[21:34:34] [WRN] HTTP Response 200 to 213.205.242.156. Time (slow): 0:00:01.0481784. http://192.168.1.197:8096/Users/d76c0428004e4c09a10b816937e3ff9d/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=52f1cc5cfe5ba8c9452cebe7bca9e026

**Screenshots**

**Additional context**

**Comment by gllyrjones** [comment] 2020-03-13 20:12
I'm not sure what the 'socket' in the log is referring too. It's not my reverse proxy as I connect localy.

**Comment by gllyrjones** [comment] 2020-03-26 21:30
Still not resolved in 10.5.2

**Comment by JustAMan** [comment] 2020-04-03 14:17
Could this be a duplicate of https://github.com/jellyfin/jellyfin/issues/1932 ?

**Comment by gllyrjones** [comment] 2020-04-03 14:59
> Could this be a duplicate of #1932 ?

It seems so thanks, just to add it uses a lot of cpu until you stop the service.

**Comment by gllyrjones** [comment] 2020-04-03 15:03
> Could this be a duplicate of #1932 ?

Actually this might be a separate issue as the above ticket was opend last October. I (and others on Reditt) have only had this issue in 10.5.

**Comment by 0xseed** [comment] 2020-04-10 06:50
I am also experiencing this issue.

Something I have noticed is that adding my XMLTV file and refreshing guide data works initially when no channels have been mapped, it only gets stuck at 15% on refresh the moment I attempt to map a channel to a stream. I tried importing guide data I mapped to a channel/stream beforehand using xTeVe and got the same stuck at 15% result even when the XMLTV file only contained data for 1 channel.

**Comment by gllyrjones** [comment] 2020-04-13 21:44
How come this is not bothering anyone else, i would think a lot would be using xmltv guide and HD home run. Its so annoying, no body seems to want to fix it. Wish i could code.

**Comment by lokiberra** [comment] 2020-04-14 18:01
I am also having this issue. My setup is TVHeadEnd (using Antennas as a proxy) and xmltv (built using Webgrabplus+). Since upgrading to 10.5 (tried all versions) it never finished pulling in the guide. Rolling back to 10.4.3 allowed the guide to update fine.

**Comment by marioandujar** [comment] 2020-04-20 11:36
I have the same issue. With 10.4.3 works fine but in 10.5 doesn't works

**Comment by dkanada** [comment] 2020-04-27 11:05
I am going to close this issue in favor of #1932 since it was opened first so we can track progress in a single location.

**Closed by dkanada** 2020-04-27 11:05 UTC
Labels: bug
