### ISSUE TITLE
[Issue]: Playlist view not populating

### ISSUE THREAD

**Issue by Janik313** [jellyfin/jellyfin#10295] opened 2023-09-27 22:34 UTC
### Please describe your bug

I migrated my jellyfin, which i run using the offical docker container, from a barebones debian server install into a truenas ubuntu server environment. This worked largely without issues, but now im unable to view any of my music playlists in the playlist view. 

I checked the playlist.xml files, and all filepaths and user ids are still correct. My playlists also show up when i try to add a song to a new one. So i guess jellyfin still knows my playlists exists but its just not able to display them (which i guess is nice, but still kinda annoying).

On boot everything looks alright in the log, but whenever i try to load the playlists i get a "Slow http response" error.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Server LTS 22.04.3
- Linux Kernel: 5.15
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox, Chrome
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: none
- GPU Model: none
- Plugins: Intro Skipper, Playback Reporting, Open Subtitles, Trakt
- Reverse Proxy: nginx proxy manager
- Base URL: yes
- Networking: Bridge
- Storage: NFS
```

### Jellyfin logs

```shell
[2023-09-27 14:41:09.584 +00:00] [WRN] [102] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://jelly.janik313.net/Users/9151f63cc942460ca89f052ebc972f4a/PlayedItems/5836435de0ef6dcdc00b70ffd56a3f82?datePlayed=20230925095158" to "194.230.144.142" in 0:00:02.0104465 with Status Code 200
[2023-09-27 14:41:10.444 +00:00] [WRN] [108] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://jelly.janik313.net/Users/9151f63cc942460ca89f052ebc972f4a/Items?Recursive=true&ParentId=608e1ed1e97ee5c4556f3d0299ac9894&UserId=9151f63cc942460ca89f052ebc972f4a&IncludeItemTypes=Playlist" to "194.230.144.142" in 0:00:02.9302089 with Status Code 200
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/54064741/9ed8975c-dce8-46a3-9a93-ac5b582761d3)
![image](https://github.com/jellyfin/jellyfin/assets/54064741/7309d787-6bd9-4f0b-bc16-d695454d134a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Fluhzar** [comment] 2023-09-30 05:13
Appears to be duplicate of #10272

**Comment by daps94** [comment] 2023-09-30 11:40
+1 have this issue also pretty major issue for anyone who uses jellyfin for music . No more auto updating for me currently rebuilding everything on an earlier version.

**Comment by srcrist** [comment] 2023-10-07 15:22
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/10272

**Closed by srcrist** 2023-10-07 15:22 UTC
Labels: bug
