### ISSUE TITLE
Wrong FFMPEG command causes stream to crash

### ISSUE THREAD

**Issue by momokrono** [jellyfin/jellyfin#13143] opened 2024-12-01 22:51 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin 10.10.3

Running inside a docker container inside an Archlinux LXC container inside proxmox (I know, container-ception). iGPU passthrough. Intel HD Graphics 530.

When enabling VAAPI decoding/encoding, the generated FFMPEG causes the stream to crash.
For example, this is the command ffmpeg generated by jellyfin:
```sh
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/media/movies/input.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 8698857 -maxrate 8698857 -bufsize 17397714 -profile:v:0 high -sei -a53_cc -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "7eeb61c2df5e959093fb516f3ddeceef-1.mp4" -start_number 0 -hls_segment_filename "/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef.m3u8"
```
which crashes with
```
...
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hevc @ 0x5d076ef81dc0] No support for codec hevc profile 2.
[hevc @ 0x5d076ef81dc0] Failed setup for format vaapi: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'Parsed_setparams_0' and the filter 'auto_scale_0'
[vf#0:0 @ 0x5d076ef601c0] Error reinitializing filters!
[vf#0:0 @ 0x5d076ef601c0] Task finished with error code: -38 (Function not implemented)
[vf#0:0 @ 0x5d076ef601c0] Terminating thread with return code -38 (Function not implemented)
[vost#0:0/h264_vaapi @ 0x5d076ef1d580] Could not open encoder before EOF
[vost#0:0/h264_vaapi @ 0x5d076ef1d580] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_vaapi @ 0x5d076ef1d580] Terminating thread with return code -22 (Invalid argument)
[out#0/hls @ 0x5d076ef60800] Nothing was written into output file, because at least one of its streams received no packets.
```

So, I ran `docker exec -it jellyfin bash` to access the container and navigate to the `/media/media/movies` folder. Here I modified the command above, changing absolutely nothing except  `-vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,format=nv12:extra_hw_frames=24,hwupload"`

The key difference are:
- removed `scale_vaapi=`
- added `hwupload` at the end

Now, despite
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hevc @ 0x5c2eeefaf1c0] No support for codec hevc profile 2.
[hevc @ 0x5c2eeefaf1c0] Failed setup for format vaapi: hwaccel initialisation returned error.
```
the stream correctly starts:
```
[hls @ 0x5c2eeef72d80] Opening '/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef-1.mp4' for writing
Output #0, hls, to '/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264 (High), vaapi(tv, bt709, progressive), 1416x1080 [SAR 1:1 DAR 59:45], q=2-31, 8698 kb/s, 25 fps, 12800 tbn (default)
      Metadata:
        encoder         : Lavc61.3.100 h264_vaapi
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s
      Metadata:
        encoder         : Lavc61.3.100 libfdk_aac
[hls @ 0x5c2eeef72d80] Opening '/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef0.mp4' for writing
[hls @ 0x5c2eeef72d80] Opening '/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef1.mp4' for writing
[hls @ 0x5c2eeef72d80] Opening '/config/transcodes/7eeb61c2df5e959093fb516f3ddeceef2.mp4' for writing
```
and the transcoding uses the gpu, as visible via `intel_gpu_top`.

Is there a way to modify the ffmpeg command jellyfin generates?

### Reproduction steps

1. Enable VAAPI encode/decode for HEVC 10bit
2. Stream any HEVC 10bit video (mine is, specifically,  `hevc (Main 10), yuv420p10le(tv, bt709)`)
3. The website shows: Playback Error, failed due to a fatal player error.

### What is the current _bug_ behavior?

The stream crashes and a popup appears with "Playback Error, failed due to a fatal player error."

### What is the expected _correct_ behavior?

I can stream correctly

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Arch LXC inside Proxmox
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox
- FFmpeg Version: Bundled
- Playback Method: Stream
- Hardware Acceleration: VAAPI
- GPU Model: HD 503
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Host
- Storage: Local
```

### Jellyfin logs

```shell
jellyfin  |    at lambda_method836(Closure, Object)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin  |    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin  | [22:46:33] [INF] [20] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for Momo. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
jellyfin  | [22:46:33] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/transcodes/9f456475a425dbcf525513040085487a.m3u8
jellyfin  | [22:46:33] [INF] [14] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
jellyfin  | [22:46:33] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/media/movies/Input.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 8698857 -maxrate 8698857 -bufsize 17397714 -profile:v:0 high -sei -a53_cc -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24" -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "0c35422ecc189c04eea23c8c974c17ca-1.mp4" -start_number 0 -hls_segment_filename "/config/transcodes/0c35422ecc189c04eea23c8c974c17ca%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/0c35422ecc189c04eea23c8c974c17ca.m3u8"
jellyfin  | [22:46:33] [ERR] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 218
jellyfin  | [22:46:34] [ERR] [14] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/28da9935-6bb5-4407-65ad-336490756e6a/hls1/main/-1.mp4.
jellyfin  | MediaBrowser.Common.FfmpegException: FFmpeg exited with code 218
jellyfin  |    at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
jellyfin  |    at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
jellyfin  |    at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Boolean enableAudioVbrEncoding, Boolean alwaysBurnInSubtitleWhenTranscoding)
jellyfin  |    at lambda_method836(Closure, Object)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin  |    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
jellyfin  | [22:46:34] [INF] [16] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/transcodes/0c35422ecc189c04eea23c8c974c17ca.m3u8
jellyfin  | [22:46:35] [INF] [11] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.9.7 playing Input. Stopped at 0 ms
```

### FFmpeg logs

```shell
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from 'file:/media/media/movies/Input.mkv':
  Metadata:
    title           : Input
    encoder         : libebml v1.4.0 + libmatroska v1.6.1
    creation_time   : 2020-09-02T11:37:48.000000Z
  Duration: 01:05:35.10, start: 0.000000, bitrate: 5219 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 1416x1080, SAR 1:1 DAR 59:45, 25 fps, 25 tbr, 1k tbn (default)
      Metadata:
        BPS-eng         : 4167080
        DURATION-eng    : 01:05:29.440000000
        NUMBER_OF_FRAMES-eng: 98236
        NUMBER_OF_BYTES-eng: 2046786416
        _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
        _STATISTICS_WRITING_DATE_UTC-eng: 2020-09-02 11:37:48
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 832 kb/s
      Metadata:
        title           : English (5.1) (E-AC3)
        BPS-eng         : 832000
        DURATION-eng    : 01:05:35.104000000
        NUMBER_OF_FRAMES-eng: 122972
        NUMBER_OF_BYTES-eng: 409250816
        _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
        _STATISTICS_WRITING_DATE_UTC-eng: 2020-09-02 11:37:48
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: eac3, 48000 Hz, stereo, fltp, 224 kb/s
      Metadata:
        title           : English (Stereo)
        BPS-eng         : 224000
        DURATION-eng    : 01:05:30.048000000
        NUMBER_OF_FRAMES-eng: 122814
        NUMBER_OF_BYTES-eng: 110041344
        _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
        _STATISTICS_WRITING_DATE_UTC-eng: 2020-09-02 11:37:48
        _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 960x1440 [SAR 1:1 DAR 2:3], 90k tbr, 90k tbn (attached pic)
      Metadata:
        filename        : cover.jpg
        mimetype        : image/jpeg
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hevc @ 0x55d3390f1dc0] No support for codec hevc profile 2.
[hevc @ 0x55d3390f1dc0] Failed setup for format vaapi: hwaccel initialisation returned error.
Impossible to convert between the formats supported by the filter 'Parsed_setparams_0' and the filter 'auto_scale_0'
[vf#0:0 @ 0x55d3390d01c0] Error reinitializing filters!
[vf#0:0 @ 0x55d3390d01c0] Task finished with error code: -38 (Function not implemented)
[vf#0:0 @ 0x55d3390d01c0] Terminating thread with return code -38 (Function not implemented)
[vost#0:0/h264_vaapi @ 0x55d33908d580] Could not open encoder before EOF
[vost#0:0/h264_vaapi @ 0x55d33908d580] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_vaapi @ 0x55d33908d580] Terminating thread with return code -22 (Invalid argument)
[out#0/hls @ 0x55d3390d0800] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
```

**Comment by gnattu** [comment] 2024-12-01 23:06
Duplicate of #4196

HD 530 does not support full 10bit HEVC decoding and we require the chip to have full hardware decoding capability to benefit from our processing pipeline. You need to disable 10bit decoding for your system.

What you have did is just allowing CPU fallback and copy the frame to the hardware encoder afterwards anyway.

**Comment by felix920506** [comment] 2024-12-02 01:07
You need to uncheck the "HEVC 10 bit" option in the transcoding settings in the dashboard

**Closed by felix920506** 2024-12-02 01:07 UTC
