### ISSUE TITLE
Transcoding broken on IPTV streams

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#1627] opened 2019-08-15 06:07 UTC
**Media Info of the file**
It was a IPTV media stream

**Logs**
Can't find the Logs

**Stats for Nerds Screenshots**
https://imgur.com/a/mNYN5U8

**Server System ):**
 - OS: Docker on Ubuntu
 - Jellyfin Version: 10.3.7
 - Hardware settings & device: VAAPI on Intel Xeon
 - Reverse proxy: Dynamic DNS with Self Signed SSL
 - Other hardware notes: IPTV Stream
 
**Client System:**
 - Device: Samsung Galaxy Tab A 10.1
 - OS: Android 9 Pie
 - Client: Jellyfin Client
 - Client Version: 10.3.7

**Comment by JustAMan** [comment] 2019-10-10 11:58
Can it be related to https://github.com/jellyfin/jellyfin/issues/1529 ?

**Comment by olskar** [comment] 2020-01-08 20:58
I can confirm this bug on iptv, same error message

**Comment by olskar** [comment] 2020-01-08 21:07
This is from my log when happening @JustAMan stream is fine in vlc for example

```
 [2020-01-08 22:03:45.196 +01:00] [ERR] Error getting media sources
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetChannelMediaSources(BaseItem item, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvMediaSourceProvider.GetMediaSourcesInternal(BaseItem item, ActiveRecordingInfo activeRecordingInfo, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetDynamicMediaSources(BaseItem item, IMediaSourceProvider provider, CancellationToken cancellationToken)
```

**Comment by olskar** [comment] 2020-01-08 21:18
I see that @Bond-009 made some changes in https://github.com/jellyfin/jellyfin/pull/2142 related to this perhaps? But those changes should appear once 1.5.0 is out perhaps?

**Comment by PrplHaz4** [comment] 2020-01-08 22:35
I was not able to repro this on 10.4.3 - please provide the repro steps and a sample iptv stream if possible...

**Comment by JustAMan** [comment] 2020-01-10 13:51
I wonder if it is also affected by https://github.com/jellyfin/jellyfin/pull/2221

**Comment by olskar** [comment] 2020-01-14 08:39
Perhaps @JustAMan i will wait for 10.5 and check :)

**Comment by olskar** [comment] 2020-01-15 15:32
@PrplHaz4 
Reprosteps:

Add this https://raw.githubusercontent.com/notanewbie/LegalStream/master/packages/news/live.m3u8

Try to play CNN International Live Event (some channels work, others not)

**Comment by PrplHaz4** [comment] 2020-01-15 16:21
> @PrplHaz4
> Reprosteps:
> 
> Add this https://raw.githubusercontent.com/notanewbie/LegalStream/master/packages/news/live.m3u8
> 
> Try to play CNN International Live Event (some channels work, others not)

So maybe there is something in that specific stream that jf is having trouble with. Can you try to pull the media info for it?

I will attempt to repro with the same stream later.

**Comment by olskar** [comment] 2020-01-19 09:24
@PrplHaz4 

Here is media info for a channel that plays in VLC but not in jellyfin

![stream](https://user-images.githubusercontent.com/18314560/72678401-cf4a7680-3aa5-11ea-8162-b462cb31fcd8.png)

**Comment by PrplHaz4** [comment] 2020-01-19 11:51
> @PrplHaz4
> 
> Here is media info for a channel that plays in VLC but not in jellyfin
> 
> ![stream](https://user-images.githubusercontent.com/18314560/72678401-cf4a7680-3aa5-11ea-8162-b462cb31fcd8.png)

There are currently a few open issues for h265/hevc I believe. Most seem to be related to hardware decoding.  https://github.com/jellyfin/jellyfin/issues/2261

**Comment by olskar** [comment] 2020-01-19 14:07
That indeed seems to be related @PrplHaz4 Dont know if this should be marked as dublicate without the original reporter having the same error perhaps

**Comment by cvium** [comment] 2021-04-08 21:15
Open a new issue if it persists. I tried testing with some of the channels but a lot of them are defunct.

**Closed by cvium** 2021-04-08 21:15 UTC
Labels: media playback
