### ISSUE TITLE
Artist name split into multiple artists

### ISSUE THREAD

**Issue by 999eagle** [jellyfin/jellyfin#2305] opened 2020-01-19 10:47 UTC
**Describe the bug**

I have a song in my music library called POP/STARS by K/DA. Jellyfin splits the artist name into two different artists though, called K and DA. The song is tagged with the MusicBrainz IDs for album, song, artist and release group, so Jellyfin should just use that information instead of splitting the artist name at the slash.

**To Reproduce**

1. Add a song to your library by an artist with a slash in their name.
2. Jellyfin splits the artist into two artists and fails to find metadata for them.

**Expected behavior**

I expect Jellyfin to either not split the artist name at a slash at all or use the MusicBrainz IDs the song is tagged with to prevent this splitting.
Correct artist name for both song and album is K/DA, nothing else.

**Screenshots**

Searching for pop/stars in my library:
![image](https://user-images.githubusercontent.com/1221984/72679603-b1324580-3aa8-11ea-87ec-fc37cc2a597a.png)
Looking at the album:
![image](https://user-images.githubusercontent.com/1221984/72679607-c0b18e80-3aa8-11ea-8d16-d8f6975c3417.png)

**System (please complete the following information):**
 - OS: Docker on RPi 4
 - Browser: Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Anime, Email Notifications, Slack Notifications
 - Reverse proxy: træfik

**Comment by Bond-009** [comment] 2020-01-19 11:41
This is an issue with taglib-sharp https://github.com/mono/taglib-sharp/issues/193

**Comment by HimbeersaftLP** [comment] 2020-05-18 16:30
Yes, this issue definitely still exists and is very annoying

**Comment by 999eagle** [comment] 2020-05-18 19:42
Yep, this bug still exists.

**Comment by 999eagle** [comment] 2020-09-16 06:39
The bug still exists and still annoys we with the exact same album.

**Comment by HimbeersaftLP** [comment] 2020-09-16 12:08
The worst thing is that trying to manually correct it, completely breaks it. Now the artist isn't even in the list anymore, but the Track is still there.
There are also the artists AC/DC and Au/Ra with a slash in them.

**Comment by tonyfinn** [comment] 2020-11-16 14:01
I did some investigation with building `taglib-sharp` locally. I think it's being unfairly blamed here. As long as the ID3 tags are in ID3v2.4 format, `taglib-sharp` understands that the album artists are null delimited and not `/`, `;` or other characters. I checked with the master branch, but this code appears to be unchanged for 13 years, so I would expect similar results with 2.2/2.1. 

It is Jellyfin that further splits the artist names with these delimiters: 

https://github.com/jellyfin/jellyfin/blob/7caf1662eca2ea8826f3277e8b9d5c8c782fd03d/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L26

https://github.com/jellyfin/jellyfin/blob/7caf1662eca2ea8826f3277e8b9d5c8c782fd03d/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L1065

I think the split logic should be removed from Jellyfin - `taglib-sharp` is perfectly capable of handling the legacy seperators for ID3v2.3 tags, and it is incorrect to apply that logic to ID3v2.4 tags.

**Comment by dkanada** [comment] 2020-11-16 14:09
There's actually even an array of "exceptions" in there somewhere, but AC/DC is the only entry in that list. If the choice is between splitting or not splitting, we should avoid splitting album artists and split artists.

**Comment by tonyfinn** [comment] 2020-11-16 14:13
A few more minutes investigation reveals that the data isn't even coming from taglib-sharp in Jellyfin, it's coming from ffprobe, it appears taglib-sharp's only use is for images. If ffprobe can be coaxed to output the ID3 version or it's ok to read the file again to determine this, I think the split should only happen for ID3 < v2.4 (indicated by a 4 in the major version byte of the ID3 header).

**Comment by tonyfinn** [comment] 2020-11-17 00:48
So I've done yet more digging, and found this issue:

http://trac.ffmpeg.org/ticket/6949

It appears ffprobe (and ffmpeg in general) do not properly support ID3v2.4 multivalued tags -> they still treat it as a null terminated string (as in ID3v2.3) and not a null separated string list (as in ID3v2.4) and consequently terminate the string after the first null, removing all but the first entry.

So the (updated) options I can see to fix it:

1. The stopgap

Add "K/DA" to this exceptions list, as probably the second most common "band with a separator character in the name". However that just moves the problem to the next most common and some obscure artist could suddenly become popular in the future. Maybe make the list of non-splitting artists configurable.

2. Fix it in ffmpeg. 

The first part of this looks small and non-controversial enough - if the id3 version is 4, rather than using the C string functions that assume null terminators move to sn etc., strip off trailing nulls. There's already support for printing nulls as \x00 which is used for some of the PRIV fields which contain arbitrary binary date. 

However, the problem here is even in the structured forms of output from ffprobe (like JSON, as used in Jellyfin), there's no splitting of the list values, it's just the raw value from the tags exposed. This means that a client (in this case Jellyfin) would still have to perform the appropriate splits (on null for id3v2.4 or on the legacy "common seperator characters" for id3v2.3) on the result - and ffprobe does not pass back the id3 version in any structured format. So the question is where to put in the ffprobe response, which would require input from the ffmpeg developers. 

Probably at the "format" data level, but then that raises the question of it a submitted patch would have to populate this for all the various formats that ffmpeg supports, not to mention that even if ffmpeg did accept a patch submitted to fix it, waiting for that fixed version to get released and make its way out to distros will take some time.

3. Fix it in jellyfin by using something other than ffprobe for metadata

taglib-sharp is already included, but some of the playback data likely only comes from ffprobe, taglib-sharp for example is not going to take an arbitrary audio file and tell you the container format. Reading every file twice, one with ffprobe for playback required data and once with taglib-sharp for tag data with more edge cases covered would likely hurt performance.


----

In addition, the above would only fix it for ID3v2.4. While lots of common open source / Linux software does output ID3v2.4 tags, support is not so common in the Windows world it seems, with Windows itself only getting support in 2018 for the file picker, and also on Mac Finder apparently does not support ID3v2.4.

For ID3v2.3, the spec says that the Artist field can be seperated by / but not the Album Artist field - but then the Album Artist field as used by everyone is not actually in the spec either, TPE2 in the spec is meant for a backing band but is universally used for album artist. Also `;` is commonly used as a seperator but is not supported by the spec anywhere, more appearing to be a post-facto addition by media players who realised the AC/DC problem and looked for a character not in any popular band names. So actually fixing this on v2.3 tags with 100% compatibility with other players is just not possible.

**Comment by HimbeersaftLP** [comment] 2020-11-17 08:53
For audio files that use Vorbis Comments instead of ID3 (like flac, ogg, opus), ffmpeg always uses `;` as the separator, see
https://github.com/FFmpeg/FFmpeg/blob/04340e5e018603df5a158a5cddf81530005d8d2f/libavformat/oggparsevorbis.c#L177

Example:
```
Input #0, flac, from 'DEATH STRANDING_ Timefall (Original Music from the World of Death Stranding)/02 - Au_Ra - Ghost.flac':
  Metadata:
    TITLE           : Ghost
    ARTIST          : Au/Ra;Alan Walker
    ALBUM           : DEATH STRANDING: Timefall (Original Music from the World of Death Stranding)
    album_artist    : Au/Ra
    track           : 2
    disc            : 1
    GENRE           : Filme/Videospiele;Filmmusik
    DATE            : 2019-11-07
    LENGTH          : 178
    BPM             : 0
    PUBLISHER       : Sony Interactive Entertainment/RCA Records
    ISRC            : GBARL1901090
    BARCODE         : 886447933206
  Duration: 00:02:58.68, start: 0.000000, bitrate: 869 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

This issue could be alleviated a bit, by only splitting on `;` for those file types, although that still doesn't fix the underlying problem.

> Reading every file twice, one with ffprobe for playback required data and once with taglib-sharp for tag data with more edge cases covered would likely hurt performance.

I didn't look at the code of taglib-sharp, but doesn't it only read the metadata header part of the file?

**Comment by tnyeanderson** [comment] 2021-02-19 16:06
Just to add to the noise, I have the same issue with the artist `M|A|R|R|S`, leaving me with 4 one-letter artists :)

I agree with @HimbeersaftLP that we should only split on semicolon, at least as a stopgap until the upstream issue can be resolved (which seems like it could take a while, if it's ever done).... it may cause problems with other edge cases, but I think fewer than the current situation.

**Comment by JopoJP** [comment] 2021-02-24 09:35
It's unfortunate. A lot of software still have problems with this issue.

Many programs have implemented their own way of storing multiple artists and I guess that's somewhat one point why this feature never really have been adopted by devolopers.

What also would work, that you can choose a String or Letter or what ever, where you want to Split the Artists. 

Some have / some have \ some have ; and so on in their tags saved. 

Could be somewhat of a simple solution I guess.

**Comment by HimbeersaftLP** [comment] 2021-02-24 15:03
As I said above, if the format is using Vorbiscomments like opus, ogg and flac do, then only `;` is outputted by ffmpeg and all the other should be ignored by Jellyfin. The issue will still be there for MP3 (and other formats that use ID3) and artists with a `;` in the name, but it will be made a bit better.

**Comment by animaldaydream** [comment] 2021-02-26 01:42
One, adding LOONA / ODD EYE CIRCLE to the list of wrongfully split artists. Is there a workaround for this?

Second, and FWIW: Kodi uses multi-values only for the tags (mind the 's') Artists and Album Artists, and uses the Artist and Album Artist [sic] tags only for display where appropriate. Their wiki specifically explains how to setup Picard to add the multi-valued Album Artists tag, rather than just the Album Artist tag.

So, are the Artist and Album Artist tags meant to have only one value, and the Artists and Album Artists tags meant for multiple values? Or is this just a good compromise? Because it's a REALLY good compromise.

**Comment by certuna** [comment] 2021-03-29 07:58
> So, are the Artist and Album Artist tags meant to have only one value, and the Artists and Album Artists tags meant for multiple values?

They are meant for multiple values. Problem is, there are so many crappy music players that choke on multi-valued tags, that MusicBrainz has started using custom tags Artist**s** and Album Artist**s** instead.

If you look into the specs, for the artist field `TPE1`:

- [id3v2.3](https://id3.org/d3v2.3.0): separator is `/` - _this was of course a terrible design decision and causes problems with artists like AC/DC and K/DA_
- [id3v2.4](https://id3.org/id3v2.4.0-frames): separator is `<null>` - in this case, AC/DC or K/DA would not be split
- There's also `;` as a separator, which is against both standards, but people still use it.

The ffprobe bug is real, this is (partly) why Navidrome switched to [TagLib](https://taglib.org/).

**Comment by animaldaydream** [comment] 2021-04-01 03:12
> Problem is, there are so many crappy music players that choke on multi-valued fields

I don't know any music player that handles multiple Artist tags, that additionally handles Album Artist tags too, and has remote controls. This hits very close to home and hurts so much.

> and sophisticated modern players are smart enough to read this new multi-value field `ARTISTS`.

I would rather Jellyfin did that too though, because Picard tags the Artist tag with the official credit, "feat." "&" "×" ";" and so on where appropriate, and then the Artists tag for multiple values for use in database sorting. [Does it, anyway? I haven't checked. The last time I fed Jellyfin a library it was all tagged with beets, which straight up just **discards additional values for all fields**. I assumed it didn't but then all too late I realized my whole library was messed up and it sucks.]

This issue is not about that however.

> Note: multiple `Genre` values is another can of worms: multiple values are not allowed in id3v2.3 (that didn't stop people from doing it anyway with the non-standard separator `;`), they are null-separated in id3v2.4 (but people got so used to `;` that many of them still use that) and Vorbis still has the same issue as above (should be stored as multiple fields, but people still like `;` regardless)

One should assume the library is properly tagged. This is a media server, after all, probably most used by the power users. Adding workarounds to these should be an afterthought, still appreciated but not forced on everybody. [Not saying that's what you meant, just stating my opinion.] And that's why we're here anyways, our tags weren't just read _but interpreted_ as well and there is no workaround.

**Comment by certuna** [comment] 2021-04-02 08:29
> I don't know any music player that handles multiple Artist tags, that additionally handles Album Artist tags too, and has remote controls. 

If we're talking media servers: Emby, LMS and Roon can handle multiple artists/album artists, Spotify does too, and a number of players like foobar2000, MusicBee, Media Monkey and Kodi. It's not so bad out there...

Most other modern applications don't necessarily 'choke' on multi-valued artist tags, but just use the first one: Plex, Navidrome, Airsonic, Groove, Apple Music (but only when the frame is ISO-8859-1 encoded).

`ARTISTS` by the way is stored by Picard as a simple multi-valued field (so `First Artist<null>Second Artist`, it doesn't store the "feat." , "&" or "with". I'm not aware of any way to store that, except as a single string "First Artist with Second Artist", but then that's treated as one artist.

> One should assume the library is properly tagged.

I know, but at this point there are so many files out there with 'wrong' semicolon-separated strings that it kind of makes sense to just support it.

**Comment by animaldaydream** [comment] 2021-04-03 17:05
> If we're talking media servers: Emby, LMS and Roon can handle multiple artists/album artists, Spotify does too, and a number of players like foobar2000, MusicBee, Media Monkey and Kodi. It's not so bad out there...

My point was that no music player has all the features I need. On Linux, I meant to say. Quod Libet has good support for every tag, actually, but its MPD extension is quite poor. MALP loads that MPD server fine but there's no library and the queue only shows the song that's currently playing and only if it's not paused.

Kodi has excellent support for MusicBrainz tags, and the remote is excellent as well. I used that for a while until i figured out that the playlist saving function does not support paths with Unicode characters. They assume everyone uses ASCII. Supporting m3u8 would be a fine option but there's no support for that, like there's no support for OTF, and thus you just gotta use the Arial-based font option, which is uglier but does not turn everything into boxes. I think their devs are working under the assumption everyone's library is and should be ASCII only. The less said about that, the better.

> `ARTISTS` by the way is stored by Picard as a simple multi-valued field (so `First Artist<null>Second Artist`, it doesn't store the "feat." , "&" or "with". I'm not aware of any way to store that, except as a single string "First Artist with Second Artist", but then that's treated as one artist.

Picard stores all that as a single string on the Artist tag. It then stores multi-valued tags on the Artists tag. It might be able to store them via a custom script like the one Kodi mentions you need to use on their wiki though, but I don't know what the field is called, if any.

> I know, but at this point there are so many files out there with 'wrong' semicolon-separated strings that it kind of makes sense to just support it.

No, of course, but give us a choice! Mine aren't. And in a properly tagged library using today's taggers, they aren't.

**Comment by certuna** [comment] 2021-04-04 15:50
> Picard stores all that as a single string on the Artist tag.
That's not correct, I just checked: Picard stores multiple artists as null separated strings: 
![Screen Shot 2021-04-04 at 17 49 33](https://user-images.githubusercontent.com/62144283/113514314-2aaf3a00-956e-11eb-8cf3-a0b5ad8cc374.png)

**Comment by animaldaydream** [comment] 2021-04-04 16:13
> That doesn't seem to be correct, I just checked: Picard stores multiple artists in the Artist field as null separated strings:

Picard lets you write whatever you want, but when the tags just come from the MusicBrainz database, it stores it all as a single string.

![Screenshot_20210404_121012](https://user-images.githubusercontent.com/78395839/113514845-e193c180-953e-11eb-8db9-416864b1af58.png)

I'm sure Another Dude didn't come from MusicBrainz. You need to find a file which has two artists and hit lookup. Look at the new value.

**Comment by certuna** [comment] 2021-04-06 12:48
Ah yes, you're correct. This whole ARTIST/ARTISTS field thing is a bit of a clumsy hack, but I guess it works as long as the players are all smart enough to ignore the ARTIST field in the case the ARTISTS field is populated.

**Comment by Jones-Bones** [comment] 2021-08-08 12:27
Testing Music side of Jellyfin and wondered why band 20/20 showed up incorrectly. Is it possible to add [this exception](https://github.com/jellyfin/jellyfin/pull/6280/commits/020c0fc4cba9657b3cddf6ea237bb00a59fdf118) somewhere after Jellyfin is installed?

[MusicBrainz reports 7390 results](https://musicbrainz.org/search?query=%2F&type=artist&method=indexed) for artists containing `/` so whitelisting might not be a viable workaround in a long run.

**Comment by Shadowghost** [comment] 2022-05-05 17:40
Imho the correct way would be to use a proper tag format in your music supporting multiple tags of the same type (like ID3v2.4) and jellyfin parsing them correctly (which it will with the linked PR).

And if the available tag on the format doesn't support multiple tags of the same type we'd still need to apply some kind of processing.

**Comment by certuna** [comment] 2022-05-07 19:16
The problem is not with Jellyfin, it's with ffmpeg (which is what Jellyfin uses to read tags), more specifically [this bug](http://trac.ffmpeg.org/ticket/6949). Fix it there, and Jellyfin will happily use it.

**Comment by KucharczykL** [comment] 2022-08-30 08:32
Seems this will be fixed in ffmpeg itself according to the latest comments in http://trac.ffmpeg.org/ticket/6949

**Comment by certuna** [comment] 2022-08-30 14:06
Yes, great news. Ironically, we have a Plex developer to thank for this patch - Plex recently switched from their old Python tag reader library to ffmpeg, and immediately ran into this bug.

**Comment by Shadowghost** [comment] 2023-01-20 10:47
We switched to using taglib for tags which does support reading multiple instances of the same tag. We're still looking into integrating the mentioned patch into our FFmpeg.

**Closed by Shadowghost** 2023-01-20 10:47 UTC
Labels: bug, blocked, confirmed

**Comment by KucharczykL** [comment] 2023-01-20 12:16
That sounds good :) Is there any way to test the functionality right now?

**Comment by fuchsmich** [comment] 2023-04-29 11:14
What's the state of this issue now?

I installed 10.8.10 and rescanned the music library but artists still get split by a slash.

**Comment by animaldaydream** [comment] 2023-05-01 02:31
> I installed 10.8.10 and rescanned the music library but artists still get split by a slash.

Right. I thought this had been resolved but I do have an artist which has been divided, and you brought it to my attention.

The other artist was added to a blacklist, so I didn't see it before. But obviously there shouldn't be a hardcoded blacklist in the first place.

FLAC, of all containers, should not have this issue (like in my case is happening). It should support multiple values (and these files do have two values in place, but Jellyfin shows three).

I'm running latest Docker container.

**Comment by OdinGitDat** [comment] 2023-08-18 16:13
For what release is the permanent fix of this issue targeted?

**Comment by alex-kronish** [comment] 2023-12-17 19:49
The unstable docker container fixes this issue for me for the band Model/Actriz

On Stable it becomes two artists named "Actriz" and "Model"
On the unstable docker container it properly parses the artist as Model/Actriz.

Does anyone know when this will hit the stable branch?

**Comment by fuchsmich** [comment] 2025-05-12 08:50
I'm running 10.10.7 on Arch Linux and for me the issue is resolved now, but I don't know, which version exactly resolved this issue.

Thank you very much.
