### ISSUE TITLE
[Issue]: Playlists not listed

### ISSUE THREAD

**Issue by speediegq** [jellyfin/jellyfin#10475] opened 2023-10-26 15:59 UTC
### Please describe your bug

I moved my Jellyfin instance to a different server, and brought **music** playlists with me (i.e. simply copied them over) and this resulted in the playlists not being listed in any Jellyfin players. Then I tried creating an empty playlist and now the two playlists I copied over appeared in my list and play just fine. Now, if I remove this new empty playlist the two playlists once again disappear from my library. I'd imagine it's because those empty playlists are not in a database somewhere, but I don't really know.

Of course, the expected behavior is that these playlists appear in my library when I copy them over, without the need to create an empty playlist.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0
- Virtualization: None
- Clients: Jellyfin Web, Feishin
- Browser: Chromium 118
- GPU Model: Intel HD 3000
- Plugins: None
- Reverse Proxy: Apache
- Storage: Local
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/71722170/ed137f4d-7afe-4174-96a2-1f11c540bc27)
![image](https://github.com/jellyfin/jellyfin/assets/71722170/6ccc867f-177e-4169-bf25-e1c9222e0a77)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2023-10-26 19:10
Duplicate of #10374

**Closed** 2023-10-26 19:10 UTC
Labels: bug
