### ISSUE TITLE
[Issue]: Server does not check username/password when downloading videos

### ISSUE THREAD

**Issue by bingzhangdai** [jellyfin/jellyfin#10446] opened 2023-10-21 15:02 UTC
### Please describe your bug

My server's video links accidentally leaked to the Internet. I found the links are always available and the download link does not check the user credential.

```
root@nas:/t/test# wget -c --no-check-certificate https://mydomain.com/Videos/ccc9d0fa-e390-3edd-6ed7-6aff62ee88da/stream?static=true
--2023-10-21 23:00:12--  https://mydomain.com/Videos/ccc9d0fa-e390-3edd-6ed7-6aff62ee88da/stream?static=true
Resolving mydomain.com (mydomain.com)... 192.168.233.230
Connecting to mydomain.com (mydomain.com)|192.168.233.230|:443... connected.
WARNING: The certificate of ‘mydomain.com’ is not trusted.
WARNING: The certificate of ‘mydomain.com’ doesn't have a known issuer.
The certificate's owner does not match hostname ‘mydomain.com’
HTTP request sent, awaiting response... 200 OK
Length: 1468466888 (1.4G) [video/quicktime]
Saving to: ‘stream?static=true’

stream?static=true                   100%[======================================================================>]   1.37G   453MB/s    in 3.1s

2023-10-21 23:00:15 (453 MB/s) - ‘stream?static=true’ saved [1468466888/1468466888]

root@nas:/t/test# ls -alh
total 1.4G
drwxr-xr-x  2 root root   60 Oct 21 23:00  .
drwxrwxrwt 13 root root 1.2K Oct 21 23:00  ..
-rw-r--r--  1 root root 1.4G Aug 31  2020 'stream?static=true'
```

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-10-21 15:04
Closing as duplicate of https://github.com/jellyfin/jellyfin/issues/5415

**Closed** 2023-10-21 15:04 UTC
Labels: bug

**Comment by bingzhangdai** [comment] 2023-10-21 15:41
@crobibero for the quick fix in this situation, could you provide a suggestion on how to invalidate the leaked URL?

**Comment by Shadowghost** [comment] 2023-10-21 15:43
The URLs use the item ID, so moving all you media to a different directory and rescanning them should generate new IDs.
