### ISSUE TITLE
[Issue]: User Profile current password field is not validated, UI unclear

### ISSUE THREAD

**Issue by ToxicMushroom** [jellyfin/jellyfin#9905] opened 2023-06-18 12:26 UTC
### Please describe your bug

This morning I couldn't log in, I was very confused. The only thing I did yesterday was change my profile picture.
I then checked the jellyfin.db and see an entry for my user that my password changed around that time.

I never filled in the correct current password field on that page since I wasn't changing my password. 
But it changed it to blank anyway.
I also thought I needed to click that save button to complete changing my avatar but that's not the case, (just tested). Maybe the UI can show a toast that it was successfully changed and saved.

Steps to reproduce:
1. Have an account with a password
2. Go to your profile
3. Change your avatar (no feedback that it is saved or not)
4. Press save
5. Your password is now blank (even tho you didn't fill in your current password)

### Jellyfin Version

10.8.z

### Environment

```markdown
- Virtualization: Docker
- Browser: Firefox 114.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-06-19 12:51
Likely duplicate of https://github.com/jellyfin/jellyfin/issues/9208 but not enough information provided.

**Comment by ToxicMushroom** [comment] 2023-10-18 12:06
still not fixed, also if you need more info please say what kind of information you require, imo the reproduction steps are still clear enough

**Comment by sevenrats** [comment] 2023-12-17 01:15
i wager this is the result of not needing to enter the password if you are logged in as an admin user.

**Comment by cvium** [comment] 2023-12-18 06:56
Duplicate of #9208

**Closed by cvium** 2023-12-18 06:56 UTC
Labels: bug
