### ISSUE TITLE
"Next Up" doesn't show next season after finishing previous season

### ISSUE THREAD

**Issue by njsmith** [jellyfin/jellyfin#6079] opened 2021-05-19 05:31 UTC
**Describe the bug**

After I finish the last episode of season 1 for some show, I expect "Next up" to show the first episode of season 2. But, it doesn't -- the show disappears from "Next up" until I go find the show again and manually watch S02E01, at which point it starts appearing again (until I finish season 2, etc.).

I believe this is a new issue sometime in the last few months.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker (linuxserver/jellyfin)
 - Clients: Browser
 - Browser: Firefox 88.0.1
 - Jellyfin Version: 10.7.5 ("Server: e056eeb36611")
 - Playback: whatever jellyfin-web does
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TMDb box sets
 - Reverse Proxy: none? unless linuxserver/jellyfin includes one
 - Base URL: none
 - Networking: docker's usual port forwarding
 - Storage: local

**To Reproduce**

1. Watch the last episode of a TV show season, where there are more seasons.
2. Look at "Next up"
3. Observe that the show doesn't appear in "Next up".

**Expected behavior**

After I finish the last episode of a season, I expect the first episode of the next season to appear in "Next up".

**Logs**

**Screenshots**

**Additional context**

**Comment by njsmith** [comment] 2021-09-21 23:02
I'm still experiencing this with the latest stable releases.

**Comment by dannymichel** [comment] 2022-06-12 21:40
> I'm still experiencing this with the latest stable releases.

Have you figured out a workaround?

**Comment by neilsb** [comment] 2022-09-24 21:06
I'm assuming here when you "Next up" you're meaning next up on the home screen (not in the Show Detail page)?

If so, then I cannot reproduce this in 10.8.4.   Can you confirm if you are still seeing this issue please?

**Comment by njsmith** [comment] 2022-10-02 18:01
OK right, I should have updated this a while ago actually! I've narrowed it down more: I think my specific situation that tickles it is that I have seasons where the first episode is *not* "episode 1". Specifically I have a script to pull youtube videos into jellyfin, and since they don't naturally have season/episode metadata, I use the publication date to generate fake metadata for jellyfin. So a typical series might go S202209E27 -> S202209E30 -> S202210E05. Then after I watch S202209E30, the series disappears from my home screen "Next Up" section, rather than offering S202210E05.

I *suspect* there's something in the Next Up db query that's trying to do something cleverer than just sorting episodes by SxEy, and instead trying to find the next episode after a season end by explicitly looking for an E01? But I've gone digging for the query code several times and haven't been able to spot anything – though admittedly, I don't really understand the C# query building API.

**Comment by srcrist** [comment] 2023-10-08 07:48
Closing this issue as it does not reference a bona fide, reproducible Jellyfin bug. The symptoms appear to be the result of a bespoke, non-standard organizational structure. You might be able to resolve the issue be either using NFO files to create an arbitrary season structure of your choosing, or simply assigning the "season" and "episode number" in the metadata manually, and the Next Up feature should process it as any other series.

**Closed by srcrist** 2023-10-08 07:48 UTC
Labels: bug
