### ISSUE TITLE
Jellyfin 10.6.4 "Recently Added ___" never shows all files

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin#4335] opened 2020-10-15 13:57 UTC
For whatever reason, anytime a new episode/movie/series is added, the "recently added ___" library on Jellyfin's home screen will never show everything, most libraries will only show the most recent 2-4 items. As seen here for Latest Anime and Latest Cartoons: 
![library](https://user-images.githubusercontent.com/19889486/96139268-4e010280-0ec4-11eb-8f74-c3bf77d11ef6.PNG)

Except when I click the "latest anime" button, it takes me to a screen showing way more recently added items: 
![123456](https://user-images.githubusercontent.com/19889486/96139285-522d2000-0ec4-11eb-9a4c-13637822ab5f.PNG)

**System (please complete the following information):**
Windows 10 v1809
Chrome stable v86.0.4240.75
Jellyfin stable 10.6.4
Media is stored in Google Drive

**To Reproduce**
Add item to Jellyfin library, then refresh homepage

**Comment by Jinxyface** [comment] 2020-10-18 13:43
Let me know if there's any specific logs that might help with this.

**Comment by crobibero** [comment] 2020-10-18 14:41
This likely won’t be changed until the library db rewrite is completed.

**Comment by supaill2k** [comment] 2021-04-01 23:35
I've been searching this bug for weeks to find only 2 dead threads with no solution...If I've missed something I hope someone can point me in the right direction, but many items in my tv shows library and still only displaying 2 on home screen.

**Comment by cvium** [comment] 2021-04-07 11:22
duplicate of #1880... The issue is that the limit is per episode and not per show.

**Closed by cvium** 2021-04-07 11:22 UTC
Labels: bug
