### ISSUE TITLE
[Issue]: Actors images are not displayed

### ISSUE THREAD

**Issue by sergeykad** [jellyfin/jellyfin#9182] opened 2023-01-26 23:54 UTC
### Please describe your bug

Install Jellyfin and add Movies and/or Shows library
Images for actors are not displayed and there are errors in the log. Searching manually image for a specific actor fixes the problem for this specific actor.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows 11
- Virtualization: none
- Clients: Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: default
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-01-27 01:45:22.161 +02:00] [ERR] [97] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/metadata/People/A/Aaron Ashmore/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/A/Aaron Ashmore/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-01-27 01:45:22.163 +02:00] [ERR] [97] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/metadata/People/L/Luke Macfarlane/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/L/Luke Macfarlane/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-01-27 01:45:22.165 +02:00] [ERR] [97] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/metadata/People/T/Tamsen McDonough/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/metadata/People/T/Tamsen McDonough/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/12783618/214976366-a170a860-0b73-450a-8ef9-b338934a00e7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by traptegies** [comment] 2023-01-30 11:56
I am experiencing the same or a similar issue on 10.8.9 (also on 10.8.8 at least) lscr.io/linuxserver/jellyfin:latest docker install on Linux Mint 21.1.
Some actors (Chris Pratt, Zoe Saldaña, Dave Bautista, Vin Diesel) have missing images. Others (of the same movie), like Kurt Russel, have an image. The files and folders do not exist on the filesystem.
I manually created and added images for two actors (Chris Pratt, Zoe Saldaña) and adjusted owner and group from my user to root (same as it is for existing image files). The image for Zoe Saldaña is used after manually triggering the task to update the persons, Chris Pratt is not.
![cli of ownership](https://user-images.githubusercontent.com/115918211/215464421-ea41415e-7917-4734-af02-6f64554d38fb.png)

The path is correctly and automatically set in the .nfo file. Examples are from The Guardians of the Galaxy Vol. 2, but it happens at other movies and series, too.

Related Log:
`[2023-01-30 07:34:02.043 +01:00] [ERR] [48] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/C/Chris Pratt/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/C/Chris Pratt/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)`

The manually added image files:
![folder](https://user-images.githubusercontent.com/115918211/215465631-0cd4352d-0b87-44a1-87d4-be0b3c7d80cb.jpg)
![folder](https://user-images.githubusercontent.com/115918211/215469744-9e5d0de1-b258-4504-bf15-81ffe35e558d.jpg)

Part of the actors in the .nfo:
`  <actor>
    <name>Chris Pratt</name>
    <role>Peter Quill / Star-Lord</role>
    <type>Actor</type>
    <sortorder>0</sortorder>
    <thumb>/config/data/metadata/People/C/Chris Pratt/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Zoe Saldaña</name>
    <role>Gamora</role>
    <type>Actor</type>
    <sortorder>1</sortorder>
    <thumb>/config/data/metadata/People/Z/Zoe Saldaña/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Dave Bautista</name>
    <role>Drax the Destroyer</role>
    <type>Actor</type>
    <sortorder>2</sortorder>
    <thumb>/config/data/metadata/People/D/Dave Bautista/folder.jpg</thumb>
  </actor>`

**Comment by Killface1980** [comment] 2023-02-06 23:17
Same issue here.
In my case, I had a QNAP install of JF, now on Docker with different paths.
Result is errors in the console.
Scanning for actors didn't help.
To make the actors appear, I have to click on the empty actor image to get to the details page and force JF to redownload.


`[23:01:39] [ERR] [50] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/metadata/People/F/Franco Tocci/folder.jpg
System.IO.FileNotFoundException: File not found
File name: '/share/CACHEDEV1_DATA/.qpkg/jellyfin/database/metadata/People/F/Franco Tocci/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)`

**Comment by traptegies** [comment] 2023-02-07 08:37
> To make the actors appear, I have to click on the empty actor image to get to the details page and force JF to redownload.

I just found out, following your comment, the small images in a movie/series appear in my case after being once in the actor's detail page (where the images are already shown). Sometimes I need to reload the page before they appear. After having this done once, the images also survive a container restart. After having them loaded this way on one device (Chrome Websession), the images also appear in the Jellyfin Android App w/o having to repeat the procedure.
There are no log entries produced by doing this.

**Comment by jdyz** [comment] 2023-05-08 10:05
Same issue on version 10.8.10, but only for movies, Actor images are normal for the content type shows .
And I have tested versions from 10.7.7 to 10.8.10, only version 10.7.7 works.

**Comment by Bond-009** [comment] 2023-05-09 09:25
Closing as duplicate of #8288

**Closed by Bond-009** 2023-05-09 09:25 UTC
Labels: bug

**Comment by herigrosir** [comment] 2024-07-13 04:52
The solution you are waiting for is here, at the bottom of the information
https://forum.jellyfin.org/t-feature-requests
