### ISSUE TITLE
Movie parts do not automatically play one after another

### ISSUE THREAD

**Issue by giddie** [jellyfin/jellyfin#3212] opened 2020-05-31 16:58 UTC
When naming a movie like this:

* Movie (2020).part1.mkv
* Movie (2020).part2.mkv

Jellyfin will show "Movie" in the listings, and "Movie (2020).part2" in the "Additional Parts" section on the movie information screen, but playing the movie plays only the part1 file. The expected behaviour is that it should automatically play part2 after part1 has finish, like e.g. Kodi.

**Comment by holow29** [comment] 2020-09-07 19:54
I think related/same as: https://github.com/jellyfin/jellyfin/issues/1745

**Comment by giddie** [comment] 2021-01-06 15:56
Still affects me.

**Comment by cvium** [comment] 2021-04-09 13:21
Duplicate of #1745

**Closed by cvium** 2021-04-09 13:21 UTC
Labels: bug
