### ISSUE TITLE
[Issue]: Lock this item to prevent future changes - does not work

### ISSUE THREAD

**Issue by MoonOverMiami** [jellyfin/jellyfin#11294] opened 2024-04-04 05:52 UTC
### Please describe your bug

Lock this Item does not lock it completely. Critic and Community reviews that have been deleted by User are repopulated by a System Scan or moving the file to a new directory. I have read that is by design and that is how it works. This is NOT the way it should work. If a user enters a zero entry in a data field, Jellyfin should recognize that null entry and not repopulate it with new data.

### Reproduction Steps

Locking item and seeing it change.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:10.8.8
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment] 2024-04-04 17:48
It is hard to tell if you moved the file or not from your report. If you moved it, this is working as intended. If you didn't, then this behavior is a valid bug.

Please make the reproduction list a step by step list, for example:
1. Add media to a library
2. Change the rating, lock and save.
3. Refresh Metadata on the item using "replace all metadata"
4. See error

**Comment by Shadowghost** [comment] 2024-06-08 08:01
This should be fixed in 10.9.6 - if it is not, please reopen.

**Closed by Shadowghost** 2024-06-08 08:01 UTC
Labels: bug
