### ISSUE TITLE
Library Access: bug with content type Music

### ISSUE THREAD

**Issue by joern-h** [jellyfin/jellyfin#1347] opened 2019-05-03 12:00 UTC
**System details:**

Official Docker Image
Docker host: Arch Linux
CPU: Intel Xeon E3-1230v2
GPU: None

Library folder hierarchy:

media/
├── movies
│   └── a_movie.mp4
├── music
│   └── artist
│       └── album
│           └── song.mp3
└── shows
    └── show
        └── season
            └── S01E01.mp4

**The Bug:**

I have 3 librarys: 
Music: media/music
Movies media/movies
Shows: media/shows

And i can't play music from library Music which content type is "Music" with user "musicuser" which is only allowed to play content from library "Music".
The user is able to show artists, albums and songs, but cant play them.
Following error is shown on the web-interface: "PlaybackErrorNoCompatibleStream"

**Steps to reproduce:**

1. Create new user
2. Only allow access to music library
3. Try to play a song

**Log:**

[2019-05-03 13:08:51.242 +02:00] [WRN] "musicuser" is not permitted to access Library "Media Folders".

**Workaround:**

When i also allow access to the movie library, i am able to play songs again

**Note:** 

This occured after i updated from jellyfin 10.2.2 to 10.3.2
All other librarys restrictions work fine.

**Comment by pjeanjean** [comment] 2019-05-07 16:47
Just wanted to add that I have exactly the same issue since I updated from 10.2.X to 10.3.2

**Comment by pjeanjean** [comment] 2019-05-07 16:55
I have a similar issue since I updated from 10.2.X to 10.3.2, except that even my root user is restricted for music libraries (and adding new permissions does not change anything).

The issue is for files that used to work fine before, as well as newly added ones.

**Comment by pjeanjean** [comment] 2019-05-07 17:46
After some more testing, the permission issue also happens whenever I try to open any subfolder inside a library, unless my user has access granted to all libraries.

This looks like an issue with #930 but I don't have any development environment to check...

**Comment by joern-h** [comment] 2019-05-20 16:59
I figured it out...

`user.Policy.EnabledFolders.Any(i => new Guid(i) == item.Id)`
this is only true if item is the EnabledFolder, but false if it is a child of it (different id)

I'm now testing if my solution is 100% proof, maybe someone can help testing...
If all works on my server, i will create a pull request

**Comment by WisdomCode** [comment] 2019-06-03 11:24
I was searching for this issue quite a while, I have the same problem, and it expands further for me:
When looking up an actor (for movies) or an artist (for music), no movies (or albums respectively) are shown, the log gives me the same error at that point. The music playback is impossible as well. This also happens with my admin account, it is not bound to the actual level of user authorization, but to the accessible libraries: I have for every user a specific amount of libraries accessible, no one (not even the admin) can access all libraries. When this access is granted however, the bug disappears. 
I hope this was helpful, as this is especially annoying with music, not being able to access the albums of a specific artist.

**Comment by pjeanjean** [comment] 2019-06-03 12:35
Your issues are definitely caused by the same reason (Enforcement of access permissions with PR #930 ), but you should probably open another issue because the problem with actors and artists is a bit different than the ones discussed before...

Music albums and subfolders didn't work because there was no check for the permission of subfolders inside collections.
However, actors and artists exist outside of collections and are thus managed differently (they will not be fixed by joern_h's PR).

**Comment by anthonylavado** [comment] 2019-06-04 19:35
@pjeanjean @joern-h Apologies for asking instead of reviewing (limited time at the moment), are both fixes (#1394/#1437) needed then, or only one of them?

In either case, we'd like to get it targeted against the release branch I think, as it seems like a big enough bug.

**Comment by pjeanjean** [comment] 2019-06-05 06:35
Both are indeed needed,: joern-h's fix solves the issue for real subfolders (that still need to be checked for libraries permissions accesses) while mine solves the issue for virtual folders (that don't have an actual library).

**Comment by DrPandemic** [comment] 2019-06-27 02:26
https://github.com/jellyfin/jellyfin/pull/1394 was merged and seems to be fixing the issues.

**Closed by DrPandemic** 2019-06-27 02:26 UTC

**Comment by bmcgonag** [comment] 2019-12-07 01:19
I am experiencing this same issue after upgrading to 10.4.2 hosted through docker on Linux x64. 

I am unable to get into my TV Shows folder, on Roku.  I can get into the Jellyfin application, and when I select the TV Shows folder, it puts a message on the screen that says

> the library type is not yet implemented: tvshows

I can't seem to get around it, and it was working before the update for Jellyfin-Roku, so maybe it's an issue on that software only. Don't know. 

I do have all access to all libraries.

**Comment by anthonylavado** [comment] 2019-12-07 08:47
As mentioned in https://github.com/jellyfin/jellyfin-roku/issues/96, Roku is just going through refactoring right now.
