### ISSUE TITLE
10.8.0 RC2 Nextpvr Plugin [Issue]: 

### ISSUE THREAD

**Issue by Fraankensteen** [jellyfin/jellyfin#6971] opened 2021-12-11 13:39 UTC
### Please describe your bug

Nextpvr 6.0.0 plugin crashes Jellyfin 10.8.0 RC2.
Manually deleting Nextpvr plugin fixes crash.
manual install crashes jellyfin
repo install crashes jellyfin
I have posted the error line i could find and also the final messages from log

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS: Windows 11
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: Nextpvr 6.0.0
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2021-12-11 08:32:16.703 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2021-12-11 08:32:16.718 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AutoOrganize, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from 
"\Local\jellyfin\plugins\Auto Organize_10.0.0.0\AutoOrganize.dll"
[2021-12-11 08:32:16.724 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from 
"\Local\jellyfin\plugins\Fanart_8.0.0.0\Jellyfin.Plugin.Fanart.dll"
[2021-12-11 08:32:16.726 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "
"\Local\jellyfin\plugins\Kodi Sync Queue_7.0.0.0\Jellyfin.Plugin.KodiSyncQueue.dll"
[2021-12-11 08:32:16.733 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27" from 
"Local\jellyfin\plugins\Kodi Sync Queue_7.0.0.0\LiteDB.dll"
[2021-12-11 08:32:16.740 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.NextPVR, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null" from "\Local\jellyfin\plugins\NextPVR_6.0.0.0\Jellyfin.Plugin.NextPVR.dll"
[2021-12-11 08:32:16.746 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "\Local\jellyfin\plugins\TheTVDB_7.0.0.0\Jellyfin.Plugin.Tvdb.dll"
[2021-12-11 08:32:16.751 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "\Local\jellyfin\plugins\TheTVDB_7.0.0.0\TvDbSharper.dll"
[2021-12-11 08:32:16.754 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" from 
"\Local\jellyfin\plugins\TMDb Box Sets_8.0.0.0\Jellyfin.Plugin.TMDbBoxSets.dll"
[2021-12-11 08:32:16.761 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from 
"\Local\jellyfin\plugins\TVmaze_9.0.0.0\Flurl.dll"
[2021-12-11 08:32:16.765 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null" from 
"\Local\jellyfin\plugins\TVmaze_9.0.0.0\Flurl.Http.dll"
[2021-12-11 08:32:16.768 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TvMaze, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "\Local\jellyfin\plugins\TVmaze_9.0.0.0\Jellyfin.Plugin.TvMaze.dll"
[2021-12-11 08:32:16.784 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Polly, Version=7.0.0.0, Culture=neutral, PublicKeyToken=c8a3ffc3f8f825cc" from 
"\Local\jellyfin\plugins\TVmaze_9.0.0.0\Polly.dll"
[2021-12-11 08:32:16.790 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvMaze.Api.Client, Version=0.1.72.0, Culture=neutral, PublicKeyToken=null" from "\Local\jellyfin\plugins\TVmaze_9.0.0.0\TvMaze.Api.Client.dll"
[2021-12-11 08:32:16.925 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : ""
[2021-12-11 08:32:16.927 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-12-11 08:32:16.929 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "
"
[2021-12-11 08:32:16.942 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-12-11 08:32:16.944 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-12-11 08:32:19.739 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Auto Organize" "10.0.0.0"
[2021-12-11 08:32:19.742 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Fanart" "8.0.0.0"
[2021-12-11 08:32:19.745 -05:00] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.KodiSyncQueuePlugin: Jellyfin.Plugin.KodiSyncQueue is now starting
[2021-12-11 08:32:19.747 -05:00] [INF] [1] Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo: Creating DB Repository...
[2021-12-11 08:32:19.754 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Kodi Sync Queue" "7.0.0.0"
[2021-12-11 08:32:19.758 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "NextPVR" "6.0.0.0"
[2021-12-11 08:32:19.760 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "7.0.0.0"
[2021-12-11 08:32:19.762 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb Box Sets" "8.0.0.0"
[2021-12-11 08:32:19.765 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TVmaze" "9.0.0.0"
[2021-12-11 08:32:19.767 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.0.0"
[2021-12-11 08:32:19.768 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.0.0"
[2021-12-11 08:32:19.773 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.0.0"
[2021-12-11 08:32:19.775 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.0.0"
[2021-12-11 08:32:19.811 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.NextPVR.LiveTvService"


System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jellyfin.Plugin.NextPVR.RecordingsChannel.GetService()
   at Jellyfin.Plugin.NextPVR.RecordingsChannel.OnUpdateTimerCallbackAsync(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2021-12-11 17:08
Duplicate of https://github.com/jellyfin/jellyfin-plugin-nextpvr/issues/20

This has been fixed in plugin v7 so it shouldn’t happen for future versions

**Closed by crobibero** 2021-12-11 17:08 UTC
Labels: bug
