### ISSUE TITLE
.arw support

### ISSUE THREAD

**Issue by philippk80** [jellyfin/jellyfin#1575] opened 2019-07-28 19:42 UTC
**Describe the feature you'd like**
- support .arw viewing for picture gallery

**Additional context**
This is useful for using Jellyfin as gallery for users with  system-cameras

**Comment by oddstr13** [comment] 2019-07-28 19:43
What is a .awr?

**Comment by philippk80** [comment] 2019-07-28 19:45
Wow so fast. I was too slow to fix my typo.
I meant the .arw file-type which is used on sony system-cameras. 😄

**Comment by oddstr13** [comment] 2019-07-28 19:47
I'm inclined to say this is kind of a duplicate of #1328

**Comment by philippk80** [comment] 2019-07-28 19:48
I wasn't aware of the connection between this two formats. Already read this article. 
Thanks for linking.

**Closed** 2019-07-28 20:01 UTC
Labels: duplicate
