### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by vsviridov** [jellyfin/jellyfin#8000] opened 2022-06-24 05:49 UTC
### Please describe your bug

An episode would be playing normally and then it would just abruptly skip to the next one in the middle of the episode.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows
- Virtualization: None
- Clients: Browser and Android App
- Browser: Firefox 101.0.1
- FFmpeg Version: bundled
- Playback Method: Transcode
- Hardware Acceleration: AMD
- Plugins: defaults + anidb
- Reverse Proxy:none
- Base URL: none
- Networking: host
- Storage: local
```

### Please attach any browser or client logs here

Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Progress main.jellyfin.bundle.js:2:790705
Sending web socket message: KeepAlive main.jellyfin.bundle.js:2:794781
Received KeepAlive from server. main.jellyfin.bundle.js:2:837708
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Progress main.jellyfin.bundle.js:2:790705
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Progress main.jellyfin.bundle.js:2:790705
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Stopped main.jellyfin.bundle.js:2:790705
nowplaying event: playbackstop 9944.cbb0feb1a224d2040a2e.chunk.js:1:8285
nowplaying event: playbackstop playback-video.579827b3ba8d3c62c6e5.chunk.js:1:10918
playing next track main.jellyfin.bundle.js:2:177424
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Stopped main.jellyfin.bundle.js:2:790705
Requesting url without automatic networking: http://localhost:8096/Items/3e487a8c15a205b93e038f67ffd01c73…k=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 main.jellyfin.bundle.js:2:790705
AutoSet Audio - Previous was 1 - English 5.1 Surround - AAC - Default main.jellyfin.bundle.js:2:148608
AutoSet Audio - Score 6 for 1 - English 5.1 Surround - AAC - Default main.jellyfin.bundle.js:2:149087
AutoSet Audio - Score 3 for 2 - English Commentary - AAC - Stereo main.jellyfin.bundle.js:2:149087
AutoSet Audio - Using 1 score 6. main.jellyfin.bundle.js:2:149271
AutoSet Subtitle - No Stream Set main.jellyfin.bundle.js:2:148422
playing url: http://localhost:8096/videos/3e487a8c-15a2-05b9-3e03-8f67ffd…264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported htmlVideoPlayer-plugin.68be8029c47cf8067899.chunk.js:1:9343
setting new text track index to: -1 htmlVideoPlayer-plugin.68be8029c47cf8067899.chunk.js:1:20860
Active player: {"name":"Html Video Player","id":"htmlvideoplayer","playerName":"Html Video Player","playableMediaTypes":[false,true,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","SetShuffleQueue","PlayMediaSource","PlayTrailers","ToggleFullscreen","SetBrightness","SetAspectRatio","PlaybackRate"]} main.jellyfin.bundle.js:2:141859
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing main.jellyfin.bundle.js:2:790705
nowplaying event: playbackstart 9944.cbb0feb1a224d2040a2e.chunk.js:1:7787
nowplaying event: playbackstart 9944.cbb0feb1a224d2040a2e.chunk.js:1:8473
nowplaying event: playbackstart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2022-06-24 05:50
duplicate of #6957

**Closed by cvium** 2022-06-24 05:50 UTC
Labels: bug
