### ISSUE TITLE
[bug] [livetv]: Live TV > Guide > ... Menu > Categories do not function as expected

### ISSUE THREAD

**Issue by nwh3365** [jellyfin/jellyfin#10223] opened 2023-09-14 03:50 UTC
### Please describe your bug

Jellyfin v10.8.10; Docker image running on Ubuntu 22.04 server x64; New install of Ubuntu and Jellyfin; minimal configuration (basic configuration items like name, local network, HTTPS, SSL cert, add two HDHomerun tuners, TV Guide data provider (XMLTV via zap2xml), single user defined at initial configuration).

Under Live TV > Guide > ... Menu, there is a section called Categories with four checkboxes for movie, sports, kids, and news.  My expectation is that these checkboxes control which channels and which types of programs are displayed in the guide (e.g., if I only check movie, I should only see the channels that include programs in the movie category, and I should only see the programs on those channels that are in the movie category; if I check Sports and News, I should only see channels with programs that are in the sports or news categories, and only the programs that are in either of those categories, etc.).  The results of selecting various checkboxes are not as expected (see examples below).  I do not see any log entries generated while navigating through the examples below.

Examples:

I initially experienced this issue with a full 7-day guide, however to demonstrate the issue on a smaller, simpler scale, I reduced the current xmltv.xml file as produced by zap2xml by only keeping one program from each category (movie, sports, kids, news) and one program with no category assigned.  I then assigned the programs to sequential channels, and set them all to the same start/end time.  This allows me to quickly and easily demonstrate the issue visually as all the programs appear together on a single page of the guide.  Note that all I'm demonstrating is the guide display issue; I'm not concerned with actually watching the programs so the channels and times associated with the programs are not relevant.

Attached files include screenshots of each example (snapxxxxxx.png as indicated below), and the xmltv.xml (xmltv.txt) file that was used for the examples.

Open Live TV > Guide > ... Menu, then select Categories as follows:
snap400114.png: If I check everything, all channels and all programs are shown, including uncategorized programs (GREEN, PURPLE, DARK BLUE, LIGHT BLUE, NO COLOR); expected
This selection illustrates that there are five programs in the guide, one in each category/color plus one that has no category assigned.

Selecting only one category at a time:
snap400115.png: If I uncheck everything except Movie, only channels with movie programs are listed, and only the movie programs are listed (PURPLE); expected
snap400116.png: If I uncheck everything except Sports, all channels are removed entirely (they aren't listed at all) eventhough there are programs in the Sports category; expected to see all sports programs
snap400117.png: If I uncheck everything except Kids, only channels with kids programs are listed, and only the kids programs are listed (LIGHT BLUE); expected
snap400118.png: If I uncheck everything except News, all channels are removed entirely (they aren't listed at all) eventhough there are programs in the News category; expected to see all news programs

Selecting all but one category at a time:
snap400119.png: If I check everything except Movie, all I see are Kids programs; expected to see all programs except movie programs
snap400120.png: If I check everything except Sports, all channels are removed entirely; expected to see all programs except sports programs
snap400121.png: If I check everything except Kids, all channels are removed entirely; expected to see all programs except kids programs
snap400122.png: If I check everything except News, all channels are removed entirely; expected to see all programs except news programs

snap400123.png: If I check nothing, all channels are shown, but no programs are shown, not even the uncategorized program.

snap400124.png: If I again check everything, all channels and all programs are shown, including programs that don't have a category assigned (same as initial example)

Question/Discuss: How are (or should) programs that are in categories other than the four checkbox categories, and programs that are not assigned a category, be handled?  I would expect these programs to appear when all categories are selected and when no categories are selected, but it may make sense to have a separate checkbox to handle programs that are in categories other than the existing checkbox categories, or that are uncategorized (i.e., other/uncategorized).

I have not tested scenarios where a program is in multiple categories (e.g., a sports movie), but would expect it to show up if either sports or movie is selected.

The results above are from my simplified xmltv.xml EPG data.  When using the complete file as generated by zap2xml, the results are more difficult to interpret because programs that could be causing a channel to appear in the list may be several hours, or even days later in the guide.  The results seemed to vary from the examples above, but the results were similarly incorrect (e.g., only seeing one or some categories when other categories are also selected and programs in those categories are present in the guide).  I might see programs listed when either movie or kids is selected, but see nothing when sports or news is selected, when I can see sports and news programs in the guide if all categories are selected and thus know that they exist.

[xmltv.txt](https://github.com/jellyfin/jellyfin/files/12604494/xmltv.txt)

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Ubuntu 22.04.3 server
- Linux Kernel: 5.15
- Virtualization: Docker (jellyfin/jellyfin, latest, Image ID b27de364af61)
- Clients: Browser
- Browser: Firefox 117.0.1
- FFmpeg Version: jellyfin-ffmpeg5/now 5.1.3-1-bullseye amd64
- Playback Method: N/A
- Hardware Acceleration: none
- GPU Model: none
- Plugins: None beyond defaults
- Reverse Proxy: none
- Base URL: none
- Networking: docker ipvlan
- Storage: local
```

### Jellyfin logs

```shell
No log entries were displayed while navigating the examples described above.
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

![snap400114](https://github.com/jellyfin/jellyfin/assets/83049351/0b3691da-0738-4d30-bb3d-5fb5912c4b95)
![snap400115](https://github.com/jellyfin/jellyfin/assets/83049351/357ac399-3fb2-4fa9-935f-eeea58a3b9db)
![snap400116](https://github.com/jellyfin/jellyfin/assets/83049351/1e4b297b-94f2-4e2a-baa5-56370951ed9f)
![snap400117](https://github.com/jellyfin/jellyfin/assets/83049351/3dbc00f1-38f9-4c45-aa41-cde0991c385d)
![snap400118](https://github.com/jellyfin/jellyfin/assets/83049351/02353f6f-ecd8-4825-b136-b8bc0dc46a30)
![snap400119](https://github.com/jellyfin/jellyfin/assets/83049351/81822778-6b79-432c-9c68-9f991f306e75)
![snap400120](https://github.com/jellyfin/jellyfin/assets/83049351/be6bd1e2-6b24-4706-bf60-70041d7e7979)
![snap400121](https://github.com/jellyfin/jellyfin/assets/83049351/df852a54-96fd-4893-a15b-ae9b28bc0053)
![snap400122](https://github.com/jellyfin/jellyfin/assets/83049351/a895abc2-b486-43ab-9d0d-04af4031d5c1)
![snap400123](https://github.com/jellyfin/jellyfin/assets/83049351/3bb35861-ac90-4cf5-93d7-d092a39ac282)
![snap400124](https://github.com/jellyfin/jellyfin/assets/83049351/f2ae5e92-d9ca-4b3b-a403-a184a27136ec)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment] 2023-10-19 17:04
Closing this issue as it does not document a Jellyfin bug. Your request is precisely how this functionality already works. But the category information needs to be provided for Jellyfin via your Live TV provider's XML data or Jellyfin cannot filter based on the categories. If that information is provided, the filters work as you expect.

**Closed by srcrist** 2023-10-19 17:04 UTC
Labels: bug

**Comment by nwh3365** [comment] 2023-10-22 22:41
I respectfully disagree.  The category information is present in the XML file.  I can see it, as can Jellyfin as confirmed in the screenshots provided that show color-coded programming based on Jellyfin categories.  However, Jellyfin does not filter correctly based on these categories via the category checkbox selections.  Here are a few examples from my original post, with supporting screenshots provided above:

If I uncheck everything except Sports, all channels are removed entirely (they aren't listed at all) even though there are programs in the Sports category; expected to see all sports programs

If I uncheck everything except News, all channels are removed entirely (they aren't listed at all) even though there are programs in the News category; expected to see all news programs

**Comment by srcrist** [comment] 2023-10-22 22:58
I tested this before closing it and I am unable to reproduce this issue with my XML. If the information is present (and correctly formatted) the filtering works as expected.

This is everything:

![image](https://github.com/jellyfin/jellyfin/assets/29871690/c3b43e88-4a44-4b89-9e23-131458aa86fc)

This is only movies: 

![image](https://github.com/jellyfin/jellyfin/assets/29871690/a468a4cb-0301-4434-acf1-e3a42bc09b66)

This is only kids programming:

![image](https://github.com/jellyfin/jellyfin/assets/29871690/9194e118-e3c5-4ecc-9168-ff9d8672d5ab)

It is correctly filtering my channels according to the data contained in my XML. I'm afraid that this issue looks unique to your XML.
