### ISSUE TITLE
Ubuntu fails installation with certificate issue

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin#6770] opened 2021-11-04 01:43 UTC
**Describe the bug**

Installing from ubuntu repository fails with the following error:

```
Err:6 https://repo.jellyfin.org/ubuntu focal Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 68.183.204.194 443]
Reading package lists... Done
E: The repository 'https://repo.jellyfin.org/ubuntu focal Release' no longer has a Release file.
```

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Ubuntu

**To Reproduce**
```
sudo apt install apt-transport-https
wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
sudo apt update
sudo apt install jellyfin
```

**Expected behavior**
Jellyfin install correctly

**Comment by crobibero** [comment] 2021-11-04 01:53
Duplicate of https://github.com/jellyfin/jellyfin/issues/6686

**Closed by crobibero** 2021-11-04 01:53 UTC
Labels: bug
