### ISSUE TITLE
Seasons are not shown in a given TV Show's page

### ISSUE THREAD

**Issue by CyanBC** [jellyfin/jellyfin#4854] opened 2020-12-23 15:55 UTC
**Describe the bug**
"Shows" are not showing seasons. Cannot select an episode unless in "Episodes" view (which shows all episodes across all shows).

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Virtualization: Docker 20.10.1
 - Clients: Browser & IOS App
 - Browser: Firefox 84.0.1
 - Jellyfin Version: 10.7.0-Rc1
 - Playback: Irrelevant
 - Installed Plugins: Defaults + Kodi Sync Que, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: local
 - Storage: local

**To Reproduce**
1. Add a TV Series (folder/s) through Libraries as "Shows" type.
2. Go to "Shows" and select TV Series after scraping using TVDB as main scraper.
3. The page for the series will not list individual seasons, nor show episodes.
4. Episodes can be viewed in "Episodes" tab in the main "Shows" page

**Expected behavior**
Expect to be able to select Season number (and then episodes) from the selected TV shows main page.

**Screenshots**
![image](https://user-images.githubusercontent.com/16420413/103014342-f9dc6380-4581-11eb-8163-b958c9da1223.png)
![image](https://user-images.githubusercontent.com/16420413/103014415-1082ba80-4582-11eb-880b-783650506d55.png)
![image](https://user-images.githubusercontent.com/16420413/103014477-25f7e480-4582-11eb-8e38-1b6f1e60ca46.png)

**Additional context**
Seasons are not shown in web client, or ios client.
Note that episodes are scraped correctly. We can see the page for a given episode by going through the "Episodes" tab.

**Comment by cvium** [comment] 2020-12-23 16:10
Duplicate of #4691

**Closed by cvium** 2020-12-23 16:11 UTC
Labels: bug
