### ISSUE TITLE
[Parser] The Grand Tour (2016) - episodes not detected properly

### ISSUE THREAD

**Issue by Webbeh** [jellyfin/jellyfin#1483] opened 2019-06-22 15:16 UTC
Hi !

**Describe the bug**
While adding the tv show [The Grand Tour (2016)](https://www.thetvdb.com/series/the-grand-tour-2016), the scraper found all the episodes of the two seasons I added in my library, but reported them all as episode the episode [Black Tie, Black Night](https://www.thetvdb.com/series/storm-stories/episodes/314087) from the show Storm Stories.

What I reckon happened was that the scraper used the TV Show's ID from TheTVDB (which is 314087) as episode ID for all the found episodes.

The end result is that all my episodes were found but shown as Episode 11.

I tried naming them in a few different ways :
"Season xx / The Grand Tour SxxEyy - name.mkv"
"Season xx / SxxEyy.mkv"
"Season xx / Eyy.mkv"
"Season x / SxxEyy.mkv"
"Season x / Eyy.mkv"
...
None of them produced correct results.

Tried to identify it manually by title, by MovieDB ID, by IMDB ID, and picked a few of the different values returned by the Identify tool everytime, to no avail.

**Changing the parser from TheTVDB to TheMovieDB worked and my episodes parsed properly.**

**To Reproduce**
- Add "The Grand Tour" to your library
- Try to scrape it using the default options (TheTVDB)

**Expected behavior**
Episodes found and displayed correctly

**Logs**
No error logs, however, what's happening while the parsing is going on :
https://glassey.dev/jellyfin.log

**Screenshots**
Sorry, don't really want to redo my library with the TVDB parser for this just yet.
If absolutely necessary, I can provide it upon demand later.

**System (please complete the following information):**
 - OS: Arch Linux
 - Jellyfin Version: 10.3.5-1 (Arch Linux AUR package)

If you need anything, I guess I could provide the media upon request as well.

**Comment by marius-luca-87** [comment] 2019-06-23 07:47
Issue seems similar to https://github.com/jellyfin/jellyfin/issues/1467

**Comment by 0ddb0d** [comment] 2019-06-23 14:23
It would help if you would provide an example of an actual filename with path because this smells like you're using an unsupported naming scheme.

**Comment by Webbeh** [comment] 2019-06-23 14:30
Which is why I renamed it according to your naming schemes, as told in the first post.

Right now, the files are named as such :
`/data/Library/Series/The Grand Tour (2016)/Season 1/S01E01 The Holy Trinity.mkv`

Doesn't really matter anyway, since the TheMovieDB parser actually got them right.

What I know is happening is that when parsing the episodes, the show's TVDB ID is taken instead of the episode's ID, which is why it always showed the episode [https://www.thetvdb.com/series/storm-stories/episodes/314087](Black Tie, Black Night), which ID is the same as the Grand Tour show's ID (314087).

Again, parsing it with TheMovieDB works with the current naming scheme. All the other shows parsed properly with their Scene naming (example : Game.of.Thrones.s01e01.mkv).

**Comment by sparky8251** [comment] 2019-06-25 10:50
Do you have logs showing when these files were cataloged for both TVDB and TheMovieDB? It would be helpful when debugging this bizarre issue.

**Comment by sparky8251** [comment] 2019-06-25 18:22
Based on a careful reading of both, I am closing this as a duplicate of #1467.

I will be pasting your reports and descriptions of the issue into #1467 so they are not lost or forgotten.

**Closed by sparky8251** 2019-06-25 18:22 UTC
Labels: bug, question
