### ISSUE TITLE
Media library: items removed despite real time monitoring is disabled

### ISSUE THREAD

**Issue by akuropka** [jellyfin/jellyfin#13300] opened 2024-12-30 06:02 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Despite I disabled realtime monitoring of a library the content was removed.

### Reproduction steps

1. Create a library on a network share and disable realtime monitoring.
2. Wait and see.

### What is the current _bug_ behavior?

Content is removed.

### What is the expected _correct_ behavior?

Content is untouched unless I do a manual scan.

### Jellyfin Server version

Unstable

### Specify unstable release number

2024123005

### Specify the build version

10.11.0

### Environment

```markdown
- OS: Microsoft Windows [Version 10.0.26120.2705]
- Virtualization: none
- FFmpeg Version: 7.0.2
- Hardware Acceleration: NVENC
- GPU Model: NVIDIA GeForce RTX 2060 with Max-Q Design
- Reverse Proxy: none
- Base URL: none
- Storage: local, network
```

### Jellyfin logs

```shell
[2024-12-30 01:13:55.189 +01:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "D:\Media\Serien"
[2024-12-30 01:13:55.191 +01:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "D:\Media\China\Movies"
[2024-12-30 01:13:55.193 +01:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "D:\Media\Filme"
[2024-12-30 01:13:55.195 +01:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "D:\Media\Kids"
[2024-12-30 01:13:55.196 +01:00] [INF] [31] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "D:\Media\China\Dramas"
[2024-12-30 01:13:55.200 +01:00] [INF] [31] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-12-30 01:13:55.399 +01:00] [WRN] [31] MediaBrowser.Controller.Entities.BaseItem: Library folder "C:\ProgramData\Jellyfin\Server\data\playlists" is inaccessible or empty, skipping
[2024-12-30 01:13:55.472 +01:00] [WRN] [12] MediaBrowser.Controller.Entities.BaseItem: Library folder "C:\ProgramData\Jellyfin\Server\data\playlists" is inaccessible or empty, skipping
[2024-12-30 01:13:55.617 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 23", Path: "D:\Media\Wissen\Löwenzahn\Staffel 23", Id: 39e84b47-62bf-1131-d904-51ee559a9e43
[2024-12-30 01:13:57.351 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 1", Path: "D:\Media\Wissen\Löwenzahn\Staffel 01", Id: c0f02ea1-ef16-b27e-bfd8-58fecbc026ea
[2024-12-30 01:13:57.439 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 2", Path: "D:\Media\Wissen\Löwenzahn\Staffel 02", Id: 9c6081f6-3e4f-1da5-952b-3aaa9ae2d398
[2024-12-30 01:13:57.553 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 3", Path: "D:\Media\Wissen\Löwenzahn\Staffel 03", Id: 5740e918-fc6f-cf29-2df5-28301071e0ac
[2024-12-30 01:13:57.657 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 4", Path: "D:\Media\Wissen\Löwenzahn\Staffel 04", Id: 7cf5afd4-8aaf-7d80-fdbb-d2a3270f5c74
[2024-12-30 01:13:57.760 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 5", Path: "D:\Media\Wissen\Löwenzahn\Staffel 05", Id: 61b2199c-4b53-32c3-3ce6-2133768f7671
[2024-12-30 01:13:57.867 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 6", Path: "D:\Media\Wissen\Löwenzahn\Staffel 06", Id: cea95887-34bc-c295-b9d4-c163cbd53a92
[2024-12-30 01:13:57.957 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 7", Path: "D:\Media\Wissen\Löwenzahn\Staffel 07", Id: 8f3fac19-8eee-69d3-9137-09197961c1ee
[2024-12-30 01:13:58.030 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 8", Path: "D:\Media\Wissen\Löwenzahn\Staffel 08", Id: 48d94702-4956-e002-a896-1c997650d708
[2024-12-30 01:13:58.074 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 9", Path: "D:\Media\Wissen\Löwenzahn\Staffel 09", Id: d5cba6e3-c3fc-728c-d1ff-561254798e7c
[2024-12-30 01:13:58.169 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 11", Path: "D:\Media\Wissen\Löwenzahn\Staffel 11", Id: 3bd9dccd-17a3-97fd-3ada-9468592595f6
[2024-12-30 01:13:58.228 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 12", Path: "D:\Media\Wissen\Löwenzahn\Staffel 12", Id: d11d3de7-988b-06c9-5249-c99b9c260891
[2024-12-30 01:13:58.276 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 13", Path: "D:\Media\Wissen\Löwenzahn\Staffel 13", Id: 3df4dc01-ca82-f5fe-e766-284a730c5947
[2024-12-30 01:13:58.371 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 14", Path: "D:\Media\Wissen\Löwenzahn\Staffel 14", Id: b067f8e9-def4-66ec-8f93-600e55b3a573
[2024-12-30 01:13:58.412 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 15", Path: "D:\Media\Wissen\Löwenzahn\Staffel 15", Id: 7c77a570-45e2-264a-0f44-5517c9bad526
[2024-12-30 01:13:58.479 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 17", Path: "D:\Media\Wissen\Löwenzahn\Staffel 17", Id: 4bf8bd32-4f8d-930e-32a1-b1342f6654b6
[2024-12-30 01:13:58.521 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 18", Path: "D:\Media\Wissen\Löwenzahn\Staffel 18", Id: 7a3fae22-6f8a-54ec-09e5-8c84bde030b0
[2024-12-30 01:13:58.598 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 19", Path: "D:\Media\Wissen\Löwenzahn\Staffel 19", Id: bbaf8fb3-6876-7ae3-ae96-09eb29afdac0
[2024-12-30 01:13:58.686 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 20", Path: "D:\Media\Wissen\Löwenzahn\Staffel 20", Id: 2062d541-8105-fdb5-779d-868634e5d61c
[2024-12-30 01:13:58.786 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 21", Path: "D:\Media\Wissen\Löwenzahn\Staffel 21", Id: e8299686-d74e-a775-b678-79f017022519
[2024-12-30 01:13:58.874 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 22", Path: "D:\Media\Wissen\Löwenzahn\Staffel 22", Id: 9f4e185d-8732-6a22-5bc2-d209507242d5
[2024-12-30 01:13:58.921 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 24", Path: "D:\Media\Wissen\Löwenzahn\Staffel 24", Id: 78f91e90-e043-bb90-dc2b-75cfd8c800e4
[2024-12-30 01:13:58.993 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 25", Path: "D:\Media\Wissen\Löwenzahn\Staffel 25", Id: c613c499-9791-c640-52fd-cc533ec42d17
[2024-12-30 01:13:59.128 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 26", Path: "D:\Media\Wissen\Löwenzahn\Staffel 26", Id: c9d998b9-14c4-ed30-a19d-b8a966962341
[2024-12-30 01:13:59.273 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 27", Path: "D:\Media\Wissen\Löwenzahn\Staffel 27", Id: b3172cd5-b097-85d3-0d4a-6591212b9da0
[2024-12-30 01:13:59.376 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 28", Path: "D:\Media\Wissen\Löwenzahn\Staffel 28", Id: b058c55c-18d4-a1fd-32e7-4ef45c8bb109
[2024-12-30 01:13:59.505 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 29", Path: "D:\Media\Wissen\Löwenzahn\Staffel 29", Id: 6f050e62-b89c-90b3-3bf2-939bbeef9b35
[2024-12-30 01:13:59.618 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 30", Path: "D:\Media\Wissen\Löwenzahn\Staffel 30", Id: 3ae60656-a19f-d989-37ee-f72c12c777a2
[2024-12-30 01:13:59.690 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 31", Path: "D:\Media\Wissen\Löwenzahn\Staffel 31", Id: d99af8a2-813b-9f98-c4dd-6c4459c069e8
[2024-12-30 01:13:59.780 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 32", Path: "D:\Media\Wissen\Löwenzahn\Staffel 32", Id: 9a4bd457-ca2f-a2cc-c0bf-1406fa197ac7
[2024-12-30 01:13:59.880 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 33", Path: "D:\Media\Wissen\Löwenzahn\Staffel 33", Id: 7cdf8496-e9cf-e8ce-86fd-64ce655c0b84
[2024-12-30 01:13:59.985 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 34", Path: "D:\Media\Wissen\Löwenzahn\Staffel 34", Id: 8533ae73-9853-20a3-0086-ac0f312ad08e
[2024-12-30 01:14:00.081 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 35", Path: "D:\Media\Wissen\Löwenzahn\Staffel 35", Id: 1934ece5-9cd6-34c7-b880-a82dd8acd785
[2024-12-30 01:14:00.156 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 36", Path: "D:\Media\Wissen\Löwenzahn\Staffel 36", Id: a6b0cf41-1ab6-4a88-dfb9-ed0475159315
[2024-12-30 01:14:00.259 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 37", Path: "D:\Media\Wissen\Löwenzahn\Staffel 37", Id: 72de76ba-6a4a-f586-41c3-f75c2bd24675
[2024-12-30 01:14:00.361 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 38", Path: "D:\Media\Wissen\Löwenzahn\Staffel 38", Id: 4c914293-f76f-8b2d-c9bf-e58b3883a1a2
[2024-12-30 01:14:00.491 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 39", Path: "D:\Media\Wissen\Löwenzahn\Staffel 39", Id: d2c02aec-3f87-b21a-c395-410c995f9cea
[2024-12-30 01:14:00.569 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 40", Path: "D:\Media\Wissen\Löwenzahn\Staffel 40", Id: 7b9daab2-dbe5-7e17-2467-2dfd853c5ec1
[2024-12-30 01:14:00.642 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 41", Path: "D:\Media\Wissen\Löwenzahn\Staffel 41", Id: cc42f39f-9163-180a-75ba-32301c730d9b
[2024-12-30 01:14:00.734 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 42", Path: "D:\Media\Wissen\Löwenzahn\Staffel 42", Id: 958e47c3-b314-65ad-3e15-238260027319
[2024-12-30 01:14:00.806 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 43", Path: "D:\Media\Wissen\Löwenzahn\Staffel 43", Id: 9b7ea359-6a79-f0a1-e661-345dcced0e58
[2024-12-30 01:14:00.901 +01:00] [INF] [78] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Staffel 44", Path: "D:\Media\Wissen\Löwenzahn\Staffel 44", Id: 929e2ba3-3b23-bf68-207b-81e866a3c4eb
[2024-12-30 01:14:01.342 +01:00] [INF] [114] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scanne Mediensegmente" Completed after 0 minute(s) and 6 seconds
[2024-12-30 01:14:23.164 +01:00] [WRN] [79] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from "https://image.tmdb.org/t/p/original/6zvbWUUUhmV0Io9m3tN7PnI1w3S.jpg"
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\metadata\library\09\09961b6397e22077a55000379dee537a\poster.jpg' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, String retryPath, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-12-30 01:14:31.029 +01:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scanne Medien-Bibliothek" Completed after 0 minute(s) and 35 seconds
[2024-12-30 01:14:31.029 +01:00] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Media\China\Dramas"
[2024-12-30 01:14:31.029 +01:00] [INF] [46] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Media\Filme"
[2024-12-30 01:14:31.029 +01:00] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Media\China\Movies"
[2024-12-30 01:14:31.029 +01:00] [INF] [84] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Media\Serien"
[2024-12-30 01:14:31.029 +01:00] [INF] [62] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\Media\Kids"
```

### FFmpeg logs

```shell

```

### Additional information

The library is a local folder where inside is another folder as a link (`mklink /d`) pointing to a network share (`net use`).

**Comment by gnattu** [comment] 2024-12-30 06:32
Did you also disabled the scheduled task for library scanning?

**Comment by akuropka** [comment] 2024-12-30 06:51
No as I have other libraries saved local which should be updated.
My understanding was that switch would be enough to exclude this from scanning at all.
How can I achieve that one library will be only updates manually or disconnection of the remote storage won’t delete it to avoid unnecessary actions (including adding again).
Thank you. 🙏

**Comment by felix920506** [comment] 2024-12-30 07:41
Closing as this is working as intended.

**Closed** 2024-12-30 07:41 UTC
Labels: bug

**Comment by akuropka** [comment] 2024-12-30 08:28
@gnattu, @felix920506, yet, I would appreciate a hint how to deal best in my use case. Can I switch off library scanning and others still get updated through real-time scanning?

**Comment by gnattu** [comment] 2024-12-31 11:00
Yes, you can disable the scheduled task and solely rely on real-time monitoring. That is two separate functions works independently.

**Comment by akuropka** [comment] 2025-01-07 01:00
🙏
