### ISSUE TITLE
This client isn't compatible with the media and the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by mcdull** [jellyfin/jellyfin#7878] opened 2022-06-11 19:23 UTC
Error showing "This client isn't compatible with the media and the server isn't sending a compatible media format."
Everything were fine with 10.7.x
once update by apt install jellyfin-ffmpeg5, it install the 10.8.0 as well and start showing the message. Seems it does not find the cuda driver on new ffmpeg.  Tried 460 / 510 nvidia driver.

**Media Info of the file**
Any media requiring transcode

**Logs**
[2022-06-12 03:17:31.240 +08:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -threads 1 -autorotate 0 -i file:\"/mnt/itfest/TV/KOR/[UXN] 쓸쓸하고 찬란하神 - 도깨비.COMPLETE.UHDTV.60fps.x265.AAC.2160p-Once/[UXN] 쓸쓸하고 찬란하神 - 도깨비.E04.UHDTV.60fps.x265.AAC.2160p-Once.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p4 -b:v 9731378 -maxrate 9731378 -bufsize 19462756 -profile:v:0 high -g:v:0 180 -keyint_min:v:0 180 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=format=yuv420p\" -codec:a:0 libfdk_aac -ac 2 -ab 192000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/lib/jellyfin/transcodes/bd88c4b578e33b7b22d003c6f6ccbb3a%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/bd88c4b578e33b7b22d003c6f6ccbb3a.m3u8\""
[2022-06-12 03:17:31.269 +08:00] [ERR] FFmpeg exited with code 1
[2022-06-12 03:17:31.353 +08:00] [ERR] Error processing request. URL "GET" "/videos/ce779d12-84ee-4314-5e68-ff7fb58874a7/hls1/main/0.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1

**FFmpeg Logs**
[AVHWDeviceContext @ 0x562eadf33a80] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Device creation failed: -542398533.
Failed to set value 'cuda=cu:0' for option 'init_hw_device': Generic error in an external library

**Stats for Nerds Screenshots**
Nil

**Server System (please complete the following information):**
 - OS: Ubuntu (VM)
 - Jellyfin Version: 10.8.0
 - Hardware settings & device: NVENC on P40  (virtualized by GTX 1050 ti)
 - Reverse proxy: no
 - Other hardware notes: Media mounted in NFS
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Client: Web
 - Browser (if Web client): Chrome
 - Client and Browser Version: 102.0

**Comment by mcdull** [comment] 2022-06-11 19:41
apt install libnvidia-compute-510-server libnvidia-decode-510-server libnvidia-encode-510-server
seems fix the issue

**Comment by antipiot** [comment] 2022-06-12 20:56
What driver version you using? I had something similar and had to update to 470 nvidia drivers instead of 460 cause:
As far as i remember, that was causes by an incompatible cuda api version.

**Comment by professornope** [comment] 2022-06-12 21:14
This is happening for me as well, and I was on the minimum required version, 470.52.02, but I still got the error you're experiencing. I have almost exactly the same setup as you, though I'm running Debian 10 instead of Ubuntu w/ a reverse proxy.

While trying to find a fix, I stumbled upon this github issue from December. 
https://github.com/jellyfin/jellyfin/issues/7025

Seems to be related, as I ran the first command he posted, and it started to transcode videos again for me. The command in question is `/usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device opencl`

Try to run that without sudo, and see if that fixes the issue. Though it's a temporary fix, I'm thinking of just creating a startup script that runs that when first starting the jellyfin service or on reboot.

**Comment by mcdull** [comment] 2022-06-13 03:39
@professornope Thanks for your information.  I tried the work around and it works for me as well.
I have put it in a cronjob with @reboot so it will start with server boot.
i will try a few moment and see how it works or will revert to 10.7 and old ffmpeg for stability.

**Comment by mcdull** [comment] 2022-06-13 06:47
don't know if it is my internet connection or what.  The transcoded video is interrupt after like 10 or 15 minutes. Did not experiece before.  And its only 720kbps 480p stream so I guess it is not bandwidth issue.

**Comment by orlovnv** [comment] 2022-06-16 08:42
Have the same issue, try your advice, thank you

**Comment by nyanmisaka** [comment] 2022-06-16 08:46
Duplicate of https://github.com/jellyfin/jellyfin/issues/7025
Should be fixed by https://github.com/jellyfin/jellyfin/pull/7887

**Closed** 2022-06-27 16:19 UTC
