### ISSUE TITLE
IndexOutOfRangeException on passwords

### ISSUE THREAD

**Issue by Tolon28** [jellyfin/jellyfin#1423] opened 2019-05-31 01:08 UTC
**Describe the bug**
Server's web page shows loading circle, then black screen; running jellyfin.exe via command prompt shows System.IndexOutOfRangeException related to PasswordHash; looking at the network tab while loading the page shows some 500 requests

**To Reproduce**
1. Get precompiled binary for Windows
2. Install Jellyfin on Windows 10 via .ps1 script
3. Open server web page
4. In the quick start wizard, choose a long, strong entropy >= 25 char [A-Za-z0-9] password (via Keepass gen or whatever)
**(edit) 4.5 Set up easypin**
5. Upon finishing, refresh page

**Expected behavior**
Page loads as normal

**Logs**
(excerpt from running cmd instance after setting up and reloading page)
[...]
```
[03:28:20] [INF] StartupTrigger fired for task: Check for plugin updates
[03:28:20] [INF] Queueing task PluginUpdateTask
[03:28:20] [INF] Executing Check for plugin updates
[03:28:20] [INF] HttpClientManager GET: https://repo.jellyfin.org/releases/plugin/manifest.json
[03:28:20] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
[03:28:20] [INF] ExecuteQueuedTasks
[03:28:33] [ERR] Error processing request
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MediaBrowser.Model.Cryptography.PasswordHash..ctor(String storageString)
   at Emby.Server.Implementations.Library.UserManager.GetLocalPasswordHash(User user)
   at Emby.Server.Implementations.Library.UserManager.GetUserDto(User user, String remoteEndPoint)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MediaBrowser.Api.UserService.Get(GetUsers request, Boolean filterByDevice, Boolean filterByNetwork)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

```

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.3.3
 - Reverse proxy: none

**Additional context**
When reinstalling (deleting everything) and creating with shorter (~19 characters) password, all works fine

**(edit) part of issue was with setting up easypin, however the second time through with the new password I could still access the page normally (even with the OutOfRange exception), unsure**

**Comment by grayerkr** [comment] 2019-05-31 02:37
Maybe #1397  will fix this issue

**Comment by anthonylavado** [comment] 2019-05-31 04:57
Duplicate of #1386 which is fixed by #1406 :-)

**Comment by anthonylavado** [comment] 2019-05-31 04:58
We’ll have to test this.

**Comment by Tolon28** [comment] 2019-05-31 09:04
Setting up easypin seems to have caused an IndexOutOfRangeException, however with this new install the webpage still works, not too sure anymore

**Comment by sparky8251** [comment] 2019-06-25 18:59
Is this still an issue for you Tolon? We pushed a bunch of authentication bug fixes in the last ~30 days. If it is no longer an issue we should close this.

Thanks!

**Closed** 2019-07-07 05:28 UTC
Labels: bug, question
