### ISSUE TITLE
[Issue]: Unable to display more than 300 images

### ISSUE THREAD

**Issue by bjerem** [jellyfin/jellyfin#7671] opened 2022-04-27 19:26 UTC
### Please describe your bug

I use Jellyfin to view my photos and it's filed by month.
If I have more than 300 pictures in a directory, I can't display the rest of the images. Instead of the image 301, 302... , I see the 1st image of the directory.

This behavior is present in all clients (TV, browsers and phone apk). I guess the problem is the server.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Browsers and APK
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2022-04-27 22:46
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2294

All of the clients you mentioned are web wrappers.

**Closed by crobibero** 2022-04-27 22:46 UTC
Labels: bug
