### ISSUE TITLE
Crashes after migration from 10.6.4 to 10.7.0-rc2

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin#5003] opened 2021-01-11 21:23 UTC
**Describe the bug**
Jellyfin 10.7-rc2 cannot start after migrating from 10.6.4

**System (please complete the following information):**
 - OS: Fedora
 - Virtualization: Docker
 - Clients: N/a
 - Browser: N/a
 - Jellyfin Version: 10.7-rc2
 - Playback: N/a
 - Installed Plugins: don't know
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**
* Have a running docker instance with version `latest`
* Upgrade to tag `10.7.0-rc2-amd64`

**Expected behavior**

**Logs**
```
[21:10:24] [INF] [1] Main: Jellyfin version: 10.7.0
[21:10:24] [INF] [1] Main: Environment Variables: ["[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]"]
[21:10:24] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[21:10:24] [INF] [1] Main: Operating system: Linux
[21:10:24] [INF] [1] Main: Architecture: X64
[21:10:24] [INF] [1] Main: 64-Bit Process: True
[21:10:24] [INF] [1] Main: User Interactive: True
[21:10:24] [INF] [1] Main: Processor count: 4
[21:10:24] [INF] [1] Main: Program data path: /config
[21:10:24] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[21:10:24] [INF] [1] Main: Application directory: /jellyfin/
[21:10:24] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[21:10:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[21:10:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[21:10:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[21:10:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[21:10:24] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[21:10:24] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[21:10:24] [FTL] [1] Main: Error while starting server.
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturn`1' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.Init()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[21:10:24] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[21:10:24] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Screenshots**
n/a

**Additional context**

**Comment by crobibero** [comment] 2021-01-11 21:27
Duplicate of https://github.com/jellyfin/jellyfin/issues/4690

**Closed by crobibero** 2021-01-11 21:27 UTC
Labels: bug

**Comment by bmillemathias** [comment] 2021-01-11 21:33
Yep, sorry I just camez accross it.

thanks
