### ISSUE TITLE
Music Artists Do Not Automatically Get Separated

### ISSUE THREAD

**Issue by Thisisnotharry** [jellyfin/jellyfin#12344] opened 2024-07-26 19:24 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin correctly uses the Artist metadata tag of music files, however when multiple artists are present here (as many audio tagging applications do), Jellyfin does not automatically separate them into multiple different artists - cluttering up the artists list under a Music library.

### Reproduction steps

1. Get a music file with multiple different artists, each separated with a semicolon
2. Add it to a music library - scan the library for changes
3. The artists should be separated into their own categories, user is able to click on an artist individually

### What is the current _bug_ behavior?

![image](https://github.com/user-attachments/assets/ddeb03e4-b009-4008-b7ae-404efb3904f6)
As you can see in the above image, the users do not get automatically separated when a scan adds it to the library. 
In order to "automatically" get it to separate them, you need to:
1. Click the 3 dots on the track
2. Click Edit Metadata
3. Save metadata (without changing anything)
4. Done

### What is the expected _correct_ behavior?

Artists should be separated, as shown below:
![image](https://github.com/user-attachments/assets/1c692e3b-38a8-42b2-9697-912bf3224d26)
![image](https://github.com/user-attachments/assets/7c9d5a6e-bd5a-4146-8727-78fc63b64037)
As you can see, howevering over an artist in the song only highlights their name, indicating they are separated.

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS: Debian 12
- Virtualization: LXC
- Playback Method: Direct
- Storage: Network Share
```

### Jellyfin logs

```shell
Could not find anything of relevance to this problem in the logs.
```

### Additional information

Jellyfin explicitly tells you to "separate multiple artists with a semicolon".
![image](https://github.com/user-attachments/assets/14b08743-5d8c-45c3-803a-a49859925463)

This seems like an issue where this is not being detected automatically/checked for automatically. a scheduled task could help do this automatically on a media scan.

**Comment by felix920506** [comment] 2024-07-26 19:44
Duplicate of #10730

**Closed by felix920506** 2024-07-26 19:44 UTC
Labels: bug
