### ISSUE TITLE
[Issue]: After updating to 10.8.11, music playlists are gone

### ISSUE THREAD

**Issue by Emily-SAC** [jellyfin/jellyfin#10307] opened 2023-09-29 20:10 UTC
### Please describe your bug

After I updated to version 10.8.11, my music playlists are gone. They still exist in the system and I am able to add songs to them and create new lists, they just don't show up anymore. 

I have Jellyfin running on a TrueNas Scale Server and it's been updated to Version 10.8.11_15.0.8. This is when the issue occurred. 

### Jellyfin Version

10.8.z

### if other:

10.8.11_15.0.8

### Environment

```markdown
- OS:TrueNAS-SCALE-22.12.3.3
- Linux Kernel: unsure
- Virtualization: no
- Clients: Browser, Android, Android TV, Jellyfin Media Player App
- Browser: Firefox
- FFmpeg Version: unsure
- Playback Method: Direct Play
- Hardware Acceleration: No
- GPU Model: None
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
no relevant logs found, since the issue is not logged as an error or action in the logs
```

### FFmpeg logs

```shell
no recent FFmpeg logs in Jellyfin
```

### Please attach any browser or client logs here

no relevant browser or client logs

### Please attach any screenshots here

![grafik](https://github.com/jellyfin/jellyfin/assets/133243828/93741ae1-7843-451f-8621-5721ce49e963)
![grafik](https://github.com/jellyfin/jellyfin/assets/133243828/cedf447a-1643-4cd3-9bd7-cf972f7cbd6f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Fluhzar** [comment] 2023-09-30 05:13
Appears to be duplicate of #10272

**Closed** 2023-09-30 05:36 UTC
Labels: bug
