### ISSUE TITLE
[Issue]: Password resets without entering old password

### ISSUE THREAD

**Issue by matjako** [jellyfin/jellyfin#9274] opened 2023-02-08 12:52 UTC
### Please describe your bug

When using WEB based clients I edit any user profile, if I leave "current password" and "new password" fields empty and press "save" above "reset password", the empty password is saved and the user has empty password set.
If I am logged in as admin and change other user profile, and both password fields are empty, pressing "save" also sets new empty password.
 
It appears no check is made if current password is correct.

If possible change behavior to not allow empty passwords and also change "save" to "save password". It is really easy to not scroll down the page and just click the first save button that you see.

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Windows
- Virtualization: none
- Clients: web
- Browser: mozilla
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins: n/a
- Reverse Proxy: Nginx Proxy Manager
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment] 2023-02-08 13:44
> also change "save" to "save password"

This is web-specific and not server related.

Duplicate of #9208

**Closed by cvium** 2023-02-08 13:44 UTC
Labels: bug
