### ISSUE TITLE
Media library cover display problem

### ISSUE THREAD

**Issue by lizenghui** [jellyfin/jellyfin#5499] opened 2021-03-12 02:40 UTC
**Describe the bug**

**System:**
 - OS: ubuntu on pve
 - Virtualization: LXC
 - Clients: All
 - Browser: Chrome 88
 - Jellyfin Version: 10.7.0 release
 - Reverse Proxy: nginx

I am a Chinese user, please forgive my English.
I recently upgraded the 10.7.0 release version.
At present, other functions are normal, that is, the cover of the media library is not displayed properly.
Previously, 3 media were used to synthesize one, for example:
**Screenshots**
![image](https://user-images.githubusercontent.com/13620083/110883681-d45c2c00-831e-11eb-8a11-a5c7d3712923.png)
But I am currently like this:
**Screenshots**
![image](https://user-images.githubusercontent.com/13620083/110883759-f05fcd80-831e-11eb-808d-37c4bdc9d49a.png)
There are garbled characters like 口口, please help to see what the problem is.
I installed the jellyfin service manually with the deb package in the lxc of pve. The template of ubuntu20.04 is used

**Comment by cvium** [comment] 2021-04-20 09:21
Duplicate of https://github.com/jellyfin/jellyfin/issues/5008

**Closed by cvium** 2021-04-20 09:21 UTC
Labels: bug
