### ISSUE TITLE
Server dashboard theme not saved

### ISSUE THREAD

**Issue by random-human-being** [jellyfin/jellyfin#6969] opened 2021-12-10 18:20 UTC
### Please describe your bug

Using a browser, log into an admin account and go to: Display > Server dashboard theme.
Set any theme other than the current one and save your settings.
Verify that it's working by opening the dashboard, then close the browser, reopen it, and log back into the same account.
The change you had just made will have been reverted to the previous setting, that is to say the dashboard should be displayed with the wrong theme.

### Jellyfin Version

Other

### if other:

10.8.0-alpha2

### Environment

```markdown
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- Base URL: none
- Networking: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2021-12-10 18:27
Duplicate of #6875
Fixed by #6854

**Closed by crobibero** 2021-12-10 18:27 UTC
Labels: bug
