### ISSUE TITLE
Manually entered Actor: Spinning Circle when clicking an actor's name

### ISSUE THREAD

**Issue by mr-simba** [jellyfin/jellyfin#5493] opened 2021-03-11 15:39 UTC
**Describe the bug**
Jellyfin 10.7.0 in a docker file on a qnap nas.

**On a movie detail page:**
1) If the actor information comes from a metadata-service like TheMovieDB or The Open Movie Database:
All works as expected: When I click on an actor name, a page loads with the actor information and all his films in my database.
2) If I enter the actor manually to a movie:
Bug: When I click on a manually entered actor name, all I see is a black page with a spinning circle with different colors. 

**System (please complete the following information):**
 - OS: Linux 
 - Virtualization: Docker
 - Clients: Browser, Android
 - Jellyfin Version: 10.7.0

**Comment by mod242** [comment] 2021-03-28 15:56
I have the exact same issue. When adding new Movies with new Actors via NFO or adding Actors manually, they somehow aren't really added to Jellyfin. When clicking on the actor the spinning circle appears and the following is logged:

`Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/6ad9a332618f4ebe99cd77c3dfcd1534/Items/7cadcb1455ddb35f120872f5acab977d".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method874(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
`

**Comment by mod242** [comment] 2021-04-11 11:23
Just to let you know from my latest troubleshooting:
The Problem exists even when setting up everything from scratch with latest Releases and Nightlies. I just tried to build up a fresh library to see whether this problem is related to the upgrade path. You can easily reproduce by scraping movie-information from nfo with actors in it.

**Comment by cvium** [comment] 2021-04-11 12:08
@mod242 Can you provide a sample that reproduces it?

**Comment by mod242** [comment] 2021-04-11 14:56
@cvium Thanks for responding. Of course I'll provide an sample (sorry for not having done so earlier):
Just save the following nfo beside a movie and let it be scraped by jellyfin. You'll see that the Actor appears on the movie page, but as soon as you try to click it the exception arrises:

```
<movie>
  <title>Sample Movie</title>
  <originaltitle/>
  <sorttitle/>
  <epbookmark/>
  <year>2010</year>
  <rating>0.0</rating>
  <userrating>0.0</userrating>
  <votes>0</votes>
  <top250>0</top250>
  <set/>
  <plot>Sample Plot</plot>
  <outline>Sample Outline</outline>
  <tagline/>
  <runtime>121</runtime>
  <thumb></thumb>
  <fanart/>
  <mpaa/>
  <certification/>
  <id/>
  <tmdbid/>
  <tmdbCollectionId/>
  <country/>
  <status/>
  <code/>
  <premiered/>
  <watched>false</watched>
  <playcount/>
  <lastplayed/>
  <genre>Sample</genre>
  <genre></genre>
  <studio>Sample Studio</studio>
  <actor>
    <name>Sample Actor</name>
    <role/>
    <thumb></thumb>
    <profile/>
  </actor>
   <trailer/>
  <languages/>

</movie>
```

**Comment by cvium** [comment] 2021-04-11 15:10
Thank you. I will take a look later

**Comment by cvium** [comment] 2021-04-11 18:02
@mod242 The problem is this line https://github.com/jellyfin/jellyfin/blob/a4cac09d5b90dda5b7d7978e083676394022ffc1/MediaBrowser.Providers/Manager/MetadataService.cs#L240

Without either an ImageUrl or a ProviderId, the person is not saved to the DB.

**Comment by mod242** [comment] 2021-04-12 07:32
First of all: Thanks a million for tracing this down! (unfortunately I have little to no experience in C so it was hard for me to comprehend what's going on).
This matches my observation. In 10.7.x actors from nfo aren't added at all (even if you have an ImageUrl set), which is because the parsing of the ImageUrl from NFO was introduced after 10.7, I think. So I have no chance to add Actors individually in 10.7

In 10.8 Actors are added as soon as there is at least an ImageUrl set, but sometimes the People-Scraper adds wrong information for those actors (maybe because of fuzzy searching or so).

In 10.6.x everything works like it should (from my point of view), actors from NFOs are added "as is" and just reside there, so that you can search for movies where they appear. As long as you make sure, that you have Unique Names for the Actors, everything works.

I can't thank you enough for tracing this down, because I really wasn't sure, whether this is "intended" behaviour, or just something strange on my side (that's why I tried to isolate this).

**Comment by cactuzjak** [comment] 2021-04-15 22:21
I'm also experiencing this same issue. Hoping it gets fixed soon.

**Comment by mod242** [comment] 2021-04-16 06:57
@cvium Do you have an estimation whether this issue is "works as designed" or will be fixed? Just asking so I know how to deal with my collection. Workaround for me would be to deliver an pseudo-Image for every actor I want to add, but honestly I would prefer not to do so.

**Comment by cvium** [comment] 2021-04-19 07:12
@mod242 see #5852

**Closed** 2021-04-19 12:28 UTC
Labels: bug
