### ISSUE TITLE
[Issue]: Text appears as a box

### ISSUE THREAD

**Issue by s949492225** [jellyfin/jellyfin#10510] opened 2023-11-01 11:39 UTC
### Please describe your bug

Subtitles and media library fonts do not support Chinese, please make fonts support UTF-8.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:any
- Linux Kernel:any
- Virtualization:any
- Clients:any
- Browser:any
- FFmpeg Version:any
- Playback Method:any
- Hardware Acceleration:any
- GPU Model:any
- Plugins:any
- Reverse Proxy:any
- Base URL:any
- Networking:any
- Storage:any
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment] 2023-11-01 11:50
Please actually fill out the template.

**Comment by felix920506** [comment] 2023-11-01 17:16
Duplicate of #5008 and #9273

**Closed by felix920506** 2023-11-01 17:16 UTC
Labels: bug
