### ISSUE TITLE
Scan Media Library failed

### ISSUE THREAD

**Issue by Stefan300381** [jellyfin/jellyfin#9503] opened 2023-03-16 09:26 UTC
Hi,

I'm new to jellyfin and migrating from Kodi/Tinymediamanager. 
About half of the collection was scanned into the library before it failed but I have no clue why. 
I initiate several new scans but it still fails. Below you can see recent log entries (full file attached). 
Jellyfin runs ins Docker on Synology DS920+

How can I further troubleshoot the issue?

Thanks in advance

```
[2023-03-16 06:04:35.337 +01:00] [ERR] [80] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/K/Kevork Malikyan/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/K/Kevork Malikyan/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-03-16 06:04:58.464 +01:00] [ERR] [46] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/M/Martin Gordon/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/M/Martin Gordon/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-03-16 06:04:58.467 +01:00] [ERR] [46] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/data/metadata/People/S/Suzanne Roquette/folder.jpg"
System.IO.FileNotFoundException: File not found
File name: '/config/data/metadata/People/S/Suzanne Roquette/folder.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2023-03-16 06:05:03.445 +01:00] [ERR] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
   at Emby.Server.Implementations.Library.LibraryManager.SavePeopleMetadataAsync(IEnumerable`1 people, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, List`1 people, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass68_0.<<RefreshChildMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-03-16 06:05:03.755 +01:00] [INF] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Failed after 1 minute(s) and 37 seconds
[2023-03-16 06:05:03.912 +01:00] [INF] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-03-16 06:05:05.045 +01:00] [INF] [94] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/Filme"
```

[Log.txt](https://github.com/jellyfin/jellyfin/files/10988951/Log.txt)

**Comment by Hilko113** [comment] 2023-03-18 21:26
I had a similar problem after removing an old library location and adding a new library location.

The new library location contained about 1000 movies but when added Jellyfin only scanned about 200 of them and then gave the same error you got.

I found that the issue came from adding 1 specific movie.
I solved it by creating a new empty library location and then moving 100 movies from the 1000 in total each time.
By doing it per 100 movies I was able to locate the movie that caused this issue.

**Comment by Stefan300381** [comment] 2023-03-20 13:57
My guess into the blue is, this issue has something to do with the local nfo files generated by TinyNediaManager. In my local collection I checked how far the scan progressed and removed the nfo file from the first movie, that wasn't added to the library. A A new library scan succeeded to progress beyond the "problematic" movie. A new NFO was then written by jellyfin (as configured)

**Comment by guythnick** [comment] 2023-03-30 02:51
Started getting this same error after 3/14/2023

```
[2023-03-29 21:47:22.147 -05:00] [ERR] Error
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
   at Emby.Server.Implementations.Library.LibraryManager.SavePeopleMetadataAsync(IEnumerable`1 people, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, List`1 people, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass68_0.<<RefreshChildMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.AggregateFolder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2023-03-29 21:47:22.152 -05:00] [INF] "Scan Media Library" Failed after 6 minute(s) and 43 seconds
```

**Comment by guythnick** [comment] 2023-03-30 22:51
It turns out my issue was a bad file of some sort as well.  But, it was very obtuse and took a ton of time using trial and error to find the culprit.  No indication of what was wrong either.  It think something should be added at least to the debug logging during a library scan so you can see what file causes the scan to fail.

**Comment by andrewhaji** [comment] 2023-04-02 04:51
I just ran into this issue. Turns out a couple of my movies had French accents in the folder name, and that was causing the library scan to fail. Removing the accents has allowed the scan to complete successfully.

**Comment by ZhangTianrong** [comment] 2023-04-21 02:07
I have been facing the same issue for quite a while. I know It might be some erroneous nfo files or some characters not being correctly interpreted, but locating them is a nightmare. I really wish jellyfin could print out the file it's failing on in the log, at least in the debug log.

**Comment by jkhsjdhjs** [comment] 2023-05-30 16:03
The issue described here is actually not related to filenames. It occurs when jellyfin downloads images of movies/shows/actors etc. and the server doesn't set a content type in the response, such as for this image for example: https://image.tmdb.org/t/p/original/9U64DXfWKkCJSEpPjmpZ0Kz8t2k.jpg

https://github.com/jellyfin/jellyfin/blob/2cd29d1cfd5cb2586aab3862e857dc85e0117ca4/MediaBrowser.Providers/Manager/ProviderManager.cs#L178-L187

As displayed in the code snippet above, jellyfin actually checks if the content type is `null`, but continues anyways if the url doens't contain `imagecache`. Since `contentType` is now `null`, the check on line 187 throws a `NullReferenceException`.

This has already been fixed on the master branch, but not incorporated in a release yet: https://github.com/jellyfin/jellyfin/commit/b03f56c3d6e005b615780bcdc676bcd632e80395#diff-8f8acf750f48664b534955ef779d78781da387b994e062b47f6cb90ab12a9a8aR167-R170

**Comment by Bond-009** [comment] 2023-06-20 16:18
Closing as this should be fixed in master

**Comment by jkhsjdhjs** [comment] 2023-06-20 16:22
@Bond-009 Do you know if the fix will be contained in the next release? Looking at the commit date, the fix has been committed over a year ago, before 10.8.0 was even released.

**Comment by Bond-009** [comment] 2023-06-20 19:49
If we do another point release I'll try to remember to backport this, but more realistically this will have to wait until 10.9

**Comment by d3473r** [comment] 2023-09-18 11:51
I'm getting the same error but running a Docker build from master after the Fix was merged, so this error still persist and should be reopened

**Comment by DevYukine** [comment] 2023-09-21 13:45
Please backport a fix for this in the current version, its making Jellyfin only show half of all my movies here and there is no way to fix it on my side or have any workaround which makes switching from other media servers very hard, also switching to nightly (where it works as intended) is also not a good solution as all plugins break due to the code changes 😢

**Comment by jkhsjdhjs** [comment] 2023-09-21 14:29
@DevYukine The fix has already been backported to the 10.8 series of releases and will be part of the next release, see https://github.com/jellyfin/jellyfin/pull/9952.

**Comment by DevYukine** [comment] 2023-09-21 14:44
@jkhsjdhjs Thats nice to hear, but there is sadly no known time window for the next patch version release i assume? 👀

**Comment by jkhsjdhjs** [comment] 2023-09-21 14:49
As I'm not a jellyfin dev I can't answer this unfortunately.

**Comment by DevYukine** [comment] 2023-09-21 16:42
Hopefully a new version is released sonn enough, this issue makes it kinda impossible to import bigger libraries into jellyfin 👀

**Comment by jkhsjdhjs** [comment] 2023-09-21 16:52
That's true, I just built jellyfin myself with the fix applied, maybe that's an option for you as well.

**Comment by nielsvanvelzen** [comment] 2023-09-21 17:30
Another 10.8 release is unlikely to happen as focus is shifting to (alpha/beta/rc) 10.9

**Comment by DevYukine** [comment] 2023-09-21 17:55
> Another 10.8 release is unlikely to happen as focus is shifting to (alpha/beta/rc) 10.9

I understand that its annoying to release a patch version when the main focus i on the next minor release but this bug is making it impossible for me to watch half of my movies in jellyfin, i rather not have to build a forked version myself when other people have the exact same issue as me and it doesn't make much sense here as others do have the same issue.

**Comment by nielsvanvelzen** [comment] 2023-09-21 19:48
Apparently there is still interest to do another 10.8 release so it might still happen.

**Comment by srcrist** [comment] 2023-10-11 04:47
Issue closed by https://github.com/jellyfin/jellyfin/pull/9952

**Closed by srcrist** 2023-10-11 04:47 UTC
Labels: bug
