### ISSUE TITLE
Shows ending with a dot are ignored/not scanned

### ISSUE THREAD

**Issue by alashow** [jellyfin/jellyfin#3933] opened 2020-08-18 23:00 UTC
**Describe the bug**
I was trying to add ["The Venture Bros."](https://thetvdb.com/series/the-venture-bros) show to my library, but Jellyfin wouldn't detect them (while Plex & Emby were okay). Found out it was a problem with the dot at the end, so I tried removing it. Jellyfin detected the folder and added it to my library. I added the dot back, Jellyfin removed it with this log:
`Removing item, Type: Series, Name: The Venture Bros., Path: /mnt/share1/shows/The Venture Bros, Id: 433284bc-78df-1977-89ff-69a908247747`

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Jellyfin Version: 10.6.3
 - Storage: local

**Additional context**
It also removed any show with the same log when I added a dot at the end (`YOU' -> 'YOU.', 'Gotham' -> 'Gotham.'`).

**Comment by crobibero** [comment] 2020-08-18 23:10
Dupe of https://github.com/jellyfin/jellyfin/issues/3635

**Closed by crobibero** 2020-08-18 23:10 UTC
Labels: bug

**Comment by alashow** [comment] 2020-08-18 23:13
Should have searched for word "period" and not just "dot" before submitting an issue :)
