### ISSUE TITLE
[Issue]: Error reading video file containing ][ in filename

### ISSUE THREAD

**Issue by Michael-2207** [jellyfin/jellyfin#8066] opened 2022-07-05 06:40 UTC
### Please describe your bug

There is a movie named [Movie][City.Lights][HD].mp4 in the library, the filename will not be showed properly in the library. It only shows [Movie and the rest part after ][ will not be shown. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10
- Virtualization: Nil
- Clients: Brower
- Browser: Chrome 101
- FFmpeg Version: Default
- Playback Method: Default
- Hardware Acceleration: None
- Plugins:None
- Reverse Proxy:None
- Base URL:None
- Networking: host
- Storage:local
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ii41** [comment] 2022-07-18 12:18
Related: #5295

**Comment by Bond-009** [comment] 2022-07-18 21:18
Closing as duplicate of #5295

**Closed by Bond-009** 2022-07-18 21:18 UTC
Labels: bug
